// Extra 144 challenges (a25-a36, e25-e36, z25-z36, g25-g36, au25-au36, h25-h36)
import type { Challenge } from "./types";

export const EXTRA_CHALLENGES: Challenge[] = [
  // ── Aanwezigheid — 12 extra ──────────────────────────────────
  { id:"a25", title:"Telefoon parkeren bij thuiskomst", skill:"Aanwezigheid", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"De eerste 5 minuten thuis volledig aanwezig zijn.",
    why:"De overgang van werk naar thuis is een kritiek moment — volle aandacht dan zet de toon voor de avond.",
    steps:["Zet telefoon in lade/tas voor je binnenkomt.","Begroet kind eerst — geen scherm checken.","Stel 1 vraag over zijn/haar dag."],
    say:"Hé! Ik ben er. Hoe was je dag?", avoid:"Direct naar je telefoon grijpen." },
  
  { id:"a26", title:"Avondritueel zonder haast", skill:"Aanwezigheid", ageGroups:["0-2","3-5","6-9"], durationMin:10,
    goal:"Bedtijdroutine als kwaliteitstijd gebruiken.",
    why:"Kinderen zijn 's avonds vaak het meest open — haast verstoort dit kostbare venster.",
    steps:["Start 10 min eerder dan normaal.","Doe alles in hetzelfde tempo als je kind.","Laat 5 min ruimte voor spontaan gesprek."],
    say:"We hebben alle tijd. Ik geniet hiervan.", avoid:"Bedtijd als corvee behandelen." },

  { id:"a27", title:"Autorit zonder muziek", skill:"Aanwezigheid", ageGroups:["6-9","10-12","13-16"], durationMin:10,
    goal:"Stilte gebruiken als opening voor gesprek.",
    why:"Zonder prikkels ontstaat ruimte — kinderen vullen die stilte vaak met wat ze kwijt willen.",
    steps:["Zet bij een rit de muziek uit.","Zeg niks — wacht af.","Als er gepraat wordt: alleen luisteren."],
    say:"(stilte, gewoon rijden)", avoid:"De stilte vullen met vragen." },

  { id:"a28", title:"Echte nieuwsgierigheid tonen", skill:"Aanwezigheid", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Oprechte interesse in wat je kind fascineert.",
    why:"Kinderen voelen verschil tussen educatieve nieuwsgierigheid en echte interesse.",
    steps:["Vraag naar iets waar je kind echt in op gaat.","Laat hem/haar jou iets leren.","Stel vervolgvragen uit echte interesse."],
    say:"Leg het me nog een keer uit — ik wil het echt begrijpen.", avoid:"Vragen stellen terwijl je eigenlijk wacht tot je wat anders kan doen." },

  { id:"a29", title:"Dagelijks fysiek contact", skill:"Aanwezigheid", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Bewust 1 moment van fysieke nabijheid per dag.",
    why:"Aanraking verlaagt cortisol en verhoogt oxytocine bij beide — het is neurochemische verbinding.",
    steps:["Kies 1 vast moment (ochtend, thuiskomst, bedtijd).","Vraag toestemming als kind ouder is.","Omhelzing, hand op schouder, of samen zitten."],
    say:"Mag ik even een knuffel?", avoid:"Fysiek contact afdwingen." },

  { id:"a30", title:"Kind als gids", skill:"Aanwezigheid", ageGroups:["3-5","6-9","10-12"], durationMin:10,
    goal:"Letterlijk volgen waar je kind heen gaat.",
    why:"Volgen i.p.v. leiden geeft het kind autonomie en laat zien: jij bent interessant voor mij.",
    steps:["Zeg: 'Jij mag bepalen waar we heen gaan.'","Loop achter hem/haar aan.","Reageer op wat je kind laat zien."],
    say:"Jij bent de gids vandaag. Waar gaan we heen?", avoid:"Stiekem toch de kant op sturen die jij wil." },

  { id:"a31", title:"Ochtend samen ontbijten", skill:"Aanwezigheid", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:10,
    goal:"De dag samen beginnen zonder schermen.",
    why:"Samen eten activeert sociale hechting — ochtend is vaak het meest rustige moment.",
    steps:["Sta 10 min eerder op.","Zit samen aan tafel, ook al eet je kind weinig.","Stel 1 vraag over de dag die komt."],
    say:"Waar kijk je vandaag naar uit?", avoid:"Schermen aan tafel of iedereen apart eten." },

  { id:"a32", title:"Naast elkaar werken", skill:"Aanwezigheid", ageGroups:["6-9","10-12","13-16"], durationMin:10,
    goal:"Parallel spelen/werken als verbindingsvorm.",
    why:"Samen in dezelfde ruimte zijn zonder interactie-eis verlaagt druk en verhoogt gevoel van 'wij'.",
    steps:["Werk aan je eigen ding terwijl kind huiswerk/hobby doet.","In dezelfde ruimte, aan aparte dingen.","Af en toe korte blik/glimlach uitwisselen."],
    say:"Laten we samen in de kamer zitten. Jij je ding, ik het mijne.", avoid:"Voortdurend interrumperen met vragen." },

  { id:"a33", title:"Herinnering ophalen samen", skill:"Aanwezigheid", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Gedeelde herinnering als emotionele brug.",
    why:"Herinneringen delen activeert episodisch geheugen — dit versterkt het 'wij'-gevoel.",
    steps:["'Weet je nog toen...' — een moment delen.","Vraag kind om zijn versie.","Geniet samen van de herinnering."],
    say:"Weet je nog dat we samen...? Hoe herinner jij dat?", avoid:"Alleen jouw versie vertellen zonder kind erbij te betrekken." },

  { id:"a34", title:"Samen buiten zijn", skill:"Aanwezigheid", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:10,
    goal:"Natuur als verbindingsruimte gebruiken.",
    why:"Buiten zijn verlaagt stress en verhoogt openheid — natuur reguleert beiden.",
    steps:["Ga samen naar buiten zonder doel.","Loop, zit, of observeer samen.","Geen telefoon mee."],
    say:"Laten we even naar buiten. Gewoon zijn.", avoid:"Buiten zijn omzetten in sport of leermoment." },

  { id:"a35", title:"Kind iets leren aan jou", skill:"Aanwezigheid", ageGroups:["6-9","10-12","13-16"], durationMin:10,
    goal:"Rolwisseling: kind als leraar.",
    why:"Kind als expert behandelen verhoogt zelfwaarde en creëert verbinding via gedeelde focus.",
    steps:["Vraag kind om jou iets te leren wat hij/zij kan.","Wees een slechte leerling — stel domme vragen.","Complimenteer het lesgeven, niet het resultaat."],
    say:"Jij weet dit. Leer het mij eens.", avoid:"Doen alsof je het al weet of beter uitleggen." },

  { id:"a36", title:"Samen op een bankje zitten", skill:"Aanwezigheid", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Bewust samen stilzitten zonder agenda.",
    why:"Gedeelde rust zonder activiteitsdwang is zeldzaam en krachtig — het zegt: ik ben graag bij jou.",
    steps:["Ga samen ergens zitten (bank, trap, buiten).","Zeg: 'Laten we even niks doen.'","5 minuten samen in stilte."],
    say:"Even niks. Gewoon samen.", avoid:"Stilte onderbreken met praten of telefoon." },

  // ── Emotiecoaching — 12 extra ────────────────────────────────
  { id:"e25", title:"Emotie eerst, gedrag later", skill:"Emotiecoaching", ageGroups:["0-2","3-5","6-9","10-12"], durationMin:2,
    goal:"Altijd het gevoel erkennen vóór je het gedrag adresseert.",
    why:"Gevoelserkenning kalmeert het limbisch systeem — daarna is het brein toegankelijk voor grenzen.",
    steps:["Stop jezelf als je direct naar gedrag gaat.","Benoem eerst het gevoel dat je ziet.","Dan pas: gedrag bespreken."],
    say:"Je bent boos. (pauze) En het is niet oké om te slaan.", avoid:"Direct naar gedrag zonder gevoel te zien." },

  { id:"e26", title:"Gevoelsdagboek samen bijhouden", skill:"Emotiecoaching", ageGroups:["6-9","10-12"], durationMin:5,
    goal:"Dagelijks emoties bewust maken via schrijven/tekenen.",
    why:"Emotionele bewustwording is een trainbare vaardigheid — dagelijkse oefening verhoogt emotieregulatie.",
    steps:["Elke avond: vraag 'welk gevoel had je het meest vandaag?'","Laat kind het tekenen of opschrijven.","Geen oordeel — alleen observeren."],
    say:"Welk gevoel was er vandaag het meest?", avoid:"Het gevoel gaan oplossen of vragen waarom." },

  { id:"e27", title:"Emotionele granulariteit oefenen", skill:"Emotiecoaching", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Van brede naar specifieke gevoelsnamen gaan.",
    why:"Fijnmazigheid in emotielabels correleren direct met betere regulatie — 'gefrustreerd' is anders dan 'boos'.",
    steps:["Als kind 'boos' of 'verdrietig' zegt: vraag welke nuance.","Bied 2-3 opties (teleurgesteld, gefrustreerd, gekwetst).","Accepteer elke keuze."],
    say:"Is het boosheid? Of meer... frustratie? Of teleurstelling?", avoid:"Het kind vertellen welk gevoel het 'echt' heeft." },

  { id:"e28", title:"Trots benoemen", skill:"Emotiecoaching", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Trots als gevoel expliciet maken.",
    why:"Trots is een zeldzaam benoemd gevoel maar essentieel voor intrinsieke motivatie.",
    steps:["Als kind iets bereikt: vraag 'ben je trots?'","Laat het voelen landen.","Benoem jouw eigen trots ook."],
    say:"Jij bent vast trots op jezelf nu. Ik zie het.", avoid:"Direct overgaan naar 'en nu het volgende'." },

  { id:"e29", title:"Jaloezie normaliseren", skill:"Emotiecoaching", ageGroups:["3-5","6-9","10-12"], durationMin:5,
    goal:"Jaloezie als normaal gevoel behandelen zonder oordeel.",
    why:"Jaloezie wordt vaak onderdrukt omdat het 'niet hoort' — dat vergroot de intensiteit.",
    steps:["Benoem de jaloezie direct: 'Je bent jaloers.'","Zeg: 'Dat mag. Iedereen kent dat.'","Bespreek wat te doen met het gevoel."],
    say:"Je bent jaloers. Dat is oké. Wat heb je nu nodig?", avoid:"'Je hoeft niet jaloers te zijn' — dat ontkent de realiteit." },

  { id:"e30", title:"Schaamte zacht maken", skill:"Emotiecoaching", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Schaamte herkennen en verkleinen via verbinding.",
    why:"Schaamte groeit in isolatie — erkenning en normalisering zijn de enige remedie.",
    steps:["Herken schaamte (hoofd omlaag, stilte).","Zeg: 'Ik denk dat je je schaamt. Klopt dat?'","Deel een eigen schaamtemoment."],
    say:"Schaamte is zwaar. Ik voel dat ook wel eens. Het is menselijk.", avoid:"Schaamte bagatelliseren of negeren." },

  { id:"e31", title:"Verdriet met geduld", skill:"Emotiecoaching", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Verdriet zijn gang laten gaan zonder te repareren.",
    why:"Verdriet heeft een functie: verlies verwerken. Troosten mag pas als kind erom vraagt.",
    steps:["Zit naast je kind in stilte.","Zeg 1×: 'Ik ben hier.'","Wacht. Laat het verdriet zijn werk doen."],
    say:"Ik ben hier. Je mag zo lang verdrietig zijn als je moet.", avoid:"Direct afleiden of opvrolijken." },

  { id:"e32", title:"Angst valideren zonder op te lossen", skill:"Emotiecoaching", ageGroups:["3-5","6-9","10-12"], durationMin:5,
    goal:"Angst ernstig nemen ook als het jou irrationeel lijkt.",
    why:"Voor het kind is de angst real — bagatelliseren sluit af, valideren opent.",
    steps:["Zeg: 'Ik zie dat je bang bent.'","Vraag: 'Waar ben je precies bang voor?'","Bied aanwezigheid, geen oplossing."],
    say:"Ik zie dat je bang bent. Dat is echt voor jou. Ik ben hier.", avoid:"'Daar hoef je niet bang voor te zijn' — dat ontkent de ervaring." },

  { id:"e33", title:"Blijdschap verlengen", skill:"Emotiecoaching", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Positieve emoties bewust langer laten duren.",
    why:"Positieve emoties zijn korter dan negatieve — bewust aandacht geven vergroot welzijn.",
    steps:["Als kind blij is: benoem het.","Vraag: 'Wat maakt je nu blij?'","Laat het 30 seconden zijn zonder nieuwe activiteit."],
    say:"Je bent blij! Ik zie het. Wat geeft je dat gevoel?", avoid:"Direct overgaan naar de volgende activiteit." },

  { id:"e34", title:"Teleurstelling samen dragen", skill:"Emotiecoaching", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Teleurstelling erkennen zonder te fixen.",
    why:"Teleurstelling is een ontwikkelingskans — het wegpoetsen berooft kind van die les.",
    steps:["Erken de teleurstelling volledig.","Vraag: 'Wat is nu het hardste eraan?'","Zit erbij — los niks op."],
    say:"Dat is echt teleurstellend. Ik snap dat.", avoid:"'Het komt wel goed' of 'er zijn ergere dingen'." },

  { id:"e35", title:"Opwinding reguleren helpen", skill:"Emotiecoaching", ageGroups:["3-5","6-9"], durationMin:5,
    goal:"Hoge energie helpen kanaliseren zonder af te remmen.",
    why:"Opwinding is positief maar kan omslaan — vroeg reguleren voorkomt crashes.",
    steps:["Benoem de energie: 'Je hebt veel energie!'","Bied een fysieke uitlaatklep (rennen, springen).","Help tempo iets verlagen voor het omslaat."],
    say:"Jij hebt veel energie! Laten we het er even uitrennen.", avoid:"Direct afremmen of straffen voor opwinding." },

  { id:"e36", title:"Boosheid fysiek helpen ontladen", skill:"Emotiecoaching", ageGroups:["3-5","6-9","10-12"], durationMin:5,
    goal:"Fysieke uitlaat bieden voor boosheid.",
    why:"Boosheid zit in het lichaam — bewegen ontlaadt sneller dan praten.",
    steps:["Bied een fysieke activiteit: kussen slaan, rennen, springen.","Doe het samen als dat helpt.","Praat pas daarna."],
    say:"Ik zie dat je boos bent. Laten we het eruit bewegen.", avoid:"Alleen praten terwijl het lijf nog kookt." },

  // ── Zelfregulatie — 12 extra ─────────────────────────────────
  { id:"z25", title:"Boosheidstemperatuur meten", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Vroege signalen van opkomende boosheid herkennen.",
    why:"Interventie op niveau 3 is makkelijker dan op niveau 9 — vroegdetectie is de sleutel.",
    steps:["Check in bij jezelf: 'Hoe boos ben ik nu op 1-10?'","Bij 4: pauze nemen.","Bij 7+: uitstappen verplicht."],
    say:"Ik voel dat ik op een 6 zit. Ik neem een korte pauze.", avoid:"Pas ingrijpen als je al op 10 zit." },

  { id:"z26", title:"Honger als trigger herkennen", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Fysiologische staat koppelen aan geduldsniveau.",
    why:"Lage bloedsuiker vermindert prefrontale controle — honger = kortere lont.",
    steps:["Check: wanneer at ik voor het laatst?","Bij irritatie + honger: eerst eten.","Communiceer dit aan je kind."],
    say:"Ik ben prikkelbaar. Ik heb nog niet gegeten. Even eten, dan ben ik er beter.", avoid:"Hongeren en dan verbazen dat je ongeduldig bent." },

  { id:"z27", title:"Pauze-protocol activeren", skill:"Zelfregulatie", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Automatisme inbouwen voor escalatie.",
    why:"Protocols verminderen cognitieve load in het moment — het wordt reflexmatig.",
    steps:["Voel je spanning? Zeg: 'Ik neem een pauze.'","Loop weg, tel tot 20.","Kom pas terug als je rustiger bent."],
    say:"Ik neem even een pauze. Ben zo terug.", avoid:"Blijven staan terwijl je voelt dat je escaleert." },

  { id:"z28", title:"Negatieve gedachtenspiraal stoppen", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Catastroferen onderbreken met realiteitscheck.",
    why:"Negatieve gedachten activeren dezelfde stress als echte gebeurtenissen — stoppen vermindert cortisol.",
    steps:["Herken de spiraal ('dit gaat altijd fout').","Stop: 'Is dit echt waar?'","Formuleer een neutrale waarheid."],
    say:"Ik catastrofeer. Wat is de neutrale waarheid hier?", avoid:"Doorgaan met de negatieve gedachten zonder te checken." },

  { id:"z29", title:"Vergelijken stoppen", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Jezelf vergelijken met andere vaders onderbreken.",
    why:"Sociale vergelijking verhoogt schaamte en verlaagt zelfcompassie — het is toxisch voor regulatie.",
    steps:["Herken de vergelijking ('die vader doet het beter').","Stop: 'Ik vergelijk. Dat helpt niet.'","Herformuleer naar jouw eigen groei."],
    say:"Ik vergelijk mezelf. Dat stop ik nu. Ik focus op mijn eigen groei.", avoid:"Blijven vergelijken en jezelf tekort vinden." },

  { id:"z30", title:"Verwachting bijstellen realtime", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Te hoge verwachting direct naar beneden aanpassen.",
    why:"Boosheid komt vaak van verwachting ≠ realiteit — bijstellen voorkomt escalatie.",
    steps:["Voel je geïrriteerd? Vraag: 'Is mijn verwachting realistisch?'","Pas bij: 'Dit is normaal voor deze leeftijd.'","Reageer vanuit de nieuwe verwachting."],
    say:"Ik verwachtte te veel. Dit is normaal. Ik pas aan.", avoid:"Blijven reageren vanuit onrealistische verwachting." },

  { id:"z31", title:"Schuld omzetten in actie", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Schuldgevoel als signaal gebruiken, niet als zelfkastijding.",
    why:"Schuld wijst naar een waardenverschil — dat is nuttig. Eindeloos schuldgevoel verlamt.",
    steps:["Voel de schuld.","Vraag: 'Wat zegt dit over wat ik wil?'","Zet om in 1 concreet herstelmoment."],
    say:"Ik voel schuld. Dat betekent dat ik het anders wil. Mijn actie: X.", avoid:"Schuldgevoel blijven herkauwen zonder actie." },

  { id:"z32", title:"Perfectie loslaten bewust", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Goed genoeg als voldoende omarmen.",
    why:"Perfectionisme verhoogt stress en vermindert ouderplezier — 'good enough' is de standaard.",
    steps:["Herken moment van te hoge lat.","Vraag: 'Was 80% hier ook genoeg?'","Kies bewust voor genoeg."],
    say:"Dit is goed genoeg. Ik laat perfectionisme los.", avoid:"Elk moment behandelen alsof het perfect moet." },

  { id:"z33", title:"Slaap prioriteren", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Slaap als basis voor regulatie erkennen.",
    why:"Slaaptekort verlaagt prefrontale controle met 30-40% — het is biologie, geen karakter.",
    steps:["Noteer: hoe laat ga ik naar bed?","Zet alarm voor 'naar bed gaan'.","Communiceer naar partner dat dit prioriteit is."],
    say:"Ik slaap te weinig. Dat maakt me prikkelbaar. Ik pas het aan.", avoid:"Chronisch slaaptekort accepteren als normaal." },

  { id:"z34", title:"Eigen triggers documenteren", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Patronen in triggers ontdekken via loggen.",
    why:"Bewustzijn van triggers is stap 1 van verandering — documenteren maakt patronen zichtbaar.",
    steps:["Houd 1 week bij: wanneer werd ik boos?","Zoek naar patronen (tijd, situatie, vermoeidheid).","Kies 1 trigger om aan te werken."],
    say:"Ik zie het patroon. Ik word altijd boos als X. Daar ga ik op letten.", avoid:"Triggers ontkennen of negeren." },

  { id:"z35", title:"Zelfcompassie oefenen", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Jezelf behandelen zoals je een goede vriend zou behandelen.",
    why:"Zelfcompassie voorspelt betere regulatie en minder burn-out bij ouders.",
    steps:["Na een fout: wat zou je tegen een vriend zeggen?","Zeg dat tegen jezelf.","Formuleer 1 les en laat rest los."],
    say:"Ik deed het niet perfect. Ik ben ook een mens. Ik leer.", avoid:"Jezelf blijven veroordelen na een fout." },

  { id:"z36", title:"Hulp vragen durven", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Hulp als kracht zien, niet als zwakte.",
    why:"Geïsoleerde opvoeding verhoogt burnout — samen opvoeden is evolutionair normaal.",
    steps:["Herken waar je hulp kunt gebruiken.","Vraag concreet (wie, wat, wanneer).","Accepteer zonder 'ik had het zelf ook gekund'."],
    say:"Ik vraag hulp. Dat is slim.", avoid:"Alles zelf willen als bewijs van goed vaderschap." },

  // ── Grenzen — 12 extra ───────────────────────────────────────
  { id:"g25", title:"Grens als bescherming framen", skill:"Grenzen", ageGroups:["6-9","10-12","13-16"], durationMin:2,
    goal:"Grens koppelen aan zorg in plaats van macht.",
    why:"Tieners accepteren grenzen beter als ze voelen dat het uit liefde komt.",
    steps:["Begin: 'Ik zeg dit omdat ik om je geef.'","Benoem de zorg.","Dan pas: de grens."],
    say:"Ik stel deze grens omdat ik wil dat je veilig bent.", avoid:"'Omdat ik het zeg' als enige reden." },

  { id:"g26", title:"Grens herhalen zonder toevoegen", skill:"Grenzen", ageGroups:["3-5","6-9","10-12"], durationMin:2,
    goal:"Exact dezelfde zin herhalen bij weerstand.",
    why:"Toevoegen of harder praten leert het kind dat doorzeur en loont.",
    steps:["Zeg de grens.","Bij weerstand: exact dezelfde woorden.","Zelfde toon, zelfde volume."],
    say:"Naar bed. (herhaal exact)", avoid:"Bij elke herhaling harder of meer uitleggen." },

  { id:"g27", title:"Grens met empathie", skill:"Grenzen", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Nee zeggen op een manier die verbinding behoudt.",
    why:"Empathie bij grenzen verhoogt acceptatie en verlaagt weerstand aantoonbaar.",
    steps:["Erken de wens eerst.","Dan pas: nee.","Eventueel: alternatief."],
    say:"Ik snap dat je X wil. Het antwoord is nee. We kunnen wel Y.", avoid:"Nee zonder enige erkenning." },

  { id:"g28", title:"Timer als grens gebruiken", skill:"Grenzen", ageGroups:["3-5","6-9","10-12"], durationMin:5,
    goal:"Externe tijdslimiet zichtbaar maken.",
    why:"Een timer is neutraal — het is niet jij die stopt maar de tijd.",
    steps:["Gebruik altijd zichtbare timer.","Kondig aan wat er na de timer gebeurt.","Hou je eraan."],
    say:"Als de timer gaat, stoppen we. Jij ziet de timer.", avoid:"Tijdslimiet steeds verschuiven." },

  { id:"g29", title:"Grens van partner steunen", skill:"Grenzen", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Consistentie tussen ouders handhaven.",
    why:"Inconsistentie tussen ouders levert meer conflicten — united front werkt.",
    steps:["Bij twijfel: steun de ander.","Bespreek later onder vier ogen.","Nooit de ander ondergraven voor kind."],
    say:"Mama/papa heeft dat gezegd. Wij staan daarin samen.", avoid:"De ander afvallen om populair te zijn." },

  { id:"g30", title:"Grens vooraf stellen", skill:"Grenzen", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Verwachtingen voor de situatie benoemen.",
    why:"In het moment is het kind minder toegankelijk — vooraf werkt beter.",
    steps:["Voor de activiteit begint: verwachtingen.","Kort: 1-2 regels max.","Vraag bevestiging."],
    say:"Voor we beginnen: dit zijn de afspraken. Snap je dit?", avoid:"Regels pas noemen als ze overtreden zijn." },

  { id:"g31", title:"Grens herstellen na toegeven", skill:"Grenzen", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Inconsistentie herstellen door grens opnieuw in te stellen.",
    why:"Elke niet-gehandhaafd de grens verzwakt die grens — herstel is mogelijk.",
    steps:["Erken dat je toegaf.","'Ik had dat niet moeten toestaan.'","Stel grens opnieuw in."],
    say:"Vorige keer liet ik het gaan. Dat was niet duidelijk. De grens is: X.", avoid:"Doen alsof de overtreding niet gebeurde." },

  { id:"g32", title:"Positieve grens formuleren", skill:"Grenzen", ageGroups:["0-2","3-5","6-9","10-12"], durationMin:2,
    goal:"Gewenst gedrag benoemen in plaats van verbod.",
    why:"Het brein verwerkt positieve instructies sneller — 'loop' > 'ren niet'.",
    steps:["Vervang verboden door gewenst gedrag.","Wees concreet wat je WEL wil.","Herhaal positieve versie bij overtreding."],
    say:"Loop alsjeblieft.", avoid:"Altijd zeggen wat niet mag." },

  { id:"g33", title:"Grens met humor", skill:"Grenzen", ageGroups:["3-5","6-9","10-12"], durationMin:2,
    goal:"Lichte toon bij grens stellen.",
    why:"Humor verlaagt weerstand zonder de grens te ondermijnen.",
    steps:["Verpak grens in lichte zin.","Hou grens zelf serieus.","Check begrip."],
    say:"Tijd voor het grote bed-avontuur! Richting badkamer!", avoid:"Humor gebruiken als grens al overschreden is." },

  { id:"g34", title:"Grens bij anderen handhaven", skill:"Grenzen", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Consistent blijven ook in sociale situaties.",
    why:"Sociale druk is veelvoorkomende reden dat grenzen vallen — bewustzijn helpt.",
    steps:["Stel grens ook als anderen kijken.","Leg eventueel later uit waarom.","Ondersteun kind als anderen grens niet respecteren."],
    say:"Die afspraak hebben wij thuis. Die geldt ook hier.", avoid:"Grenzen laten vallen om anderen niet voor het hoofd te stoten." },

  { id:"g35", title:"Grens en gevoel scheiden", skill:"Grenzen", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Gedrag reguleren zonder gevoel te ontkennen.",
    why:"Gevoelens zijn altijd geldig — gedrag is wat begrensd wordt.",
    steps:["Erken gevoel volledig.","Dan pas: grens.","Twee aparte zinnen."],
    say:"Jij bent boos. (pauze) En toch: schoenen aan.", avoid:"Grens stellen op het gevoel." },

  { id:"g36", title:"Consequentie aankondigen voor grensovertreding", skill:"Grenzen", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Logische consequentie vooraf communiceren.",
    why:"Voorspelbare consequenties leren zelfcontrole — willekeur niet.",
    steps:["Bij grens: 'Als je X doet, dan Y.'","Eén keer herhalen.","Voer uit bij overtreding."],
    say:"Als je dit doet, dan gebeurt dit. Dat is de consequentie.", avoid:"Consequenties verzinnen in het moment." },

  // ── Autonomie — 12 extra ─────────────────────────────────────
  { id:"au25", title:"Echte keuzes aanbieden", skill:"Autonomie", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Alleen keuzes geven die jij werkelijk accepteert.",
    why:"Schijnkeuzes ondermijnen vertrouwen als kind doorheeft dat er maar 1 goed antwoord is.",
    steps:["Bied alleen opties die jij oké vindt.","Accepteer elke keuze.","Als je een keuze niet accepteert: maak er geen keuze van."],
    say:"Wil je eerder of later eten? Beide is goed.", avoid:"'Welk shirt?' en dan zeggen 'nee, niet die.'" },

  { id:"au26", title:"Probleemoplossing coachen", skill:"Autonomie", ageGroups:["6-9","10-12","13-16"], durationMin:10,
    goal:"Kind door oplossingsproces leiden zonder op te lossen.",
    why:"Coachen i.p.v. oplossen bouwt eigenaarschap en denkvermogen.",
    steps:["Vraag: wat is precies het probleem?","Vraag: welke oplossingen zie jij?","Vraag: welke ga je proberen?"],
    say:"Interessant probleem. Welke oplossingen zie jij zelf?", avoid:"Direct naar jouw oplossing springen." },

  { id:"au27", title:"Stijl respecteren", skill:"Autonomie", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Controle over uiterlijk loslaten.",
    why:"Controle over lichaam en uiterlijk is essentieel voor identiteit.",
    steps:["Kies 1 domein waar je loslaat (kleding, haar, kamer).","Laat kind beslissen.","Geen commentaar."],
    say:"Jouw kamer, jouw keuze.", avoid:"'Maar dat staat toch niet?'" },

  { id:"au28", title:"Verantwoordelijkheid toewijzen", skill:"Autonomie", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Kind eigenaar maken van vaste taak.",
    why:"Echte verantwoordelijkheid bouwt betrouwbaarheid en zelfvertrouwen.",
    steps:["Kies 1 taak die echt van kind wordt.","Maak duidelijk dat jij er niet meer op let.","Bespreek wekelijks hoe het gaat."],
    say:"Dit is vanaf nu jouw verantwoordelijkheid. Ik vertrouw erop.", avoid:"Toch controleren." },

  { id:"au29", title:"Conflict laten uitvechten", skill:"Autonomie", ageGroups:["6-9","10-12"], durationMin:10,
    goal:"Kinderen zelf laten oplossen.",
    why:"Conflicten zijn oefenplaatsen — ingrijpen berooft hen van de les.",
    steps:["Wacht eerst 2 minuten.","Grijp alleen in bij gevaar.","Als gevraagd: vraag wat zij kunnen doen."],
    say:"Jullie zijn slim genoeg om dit zelf op te lossen.", avoid:"Elk conflict direct oplossen." },

  { id:"au30", title:"Falen als les benoemen", skill:"Autonomie", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Fouten heretiketteren als leerkansen.",
    why:"Groeimindset wordt aangeleerd — fouten zijn informatie.",
    steps:["Na mislukking: 'Wat heb je nu geleerd?'","Deel eigen leermoment uit fout.","Celebreer poging onafhankelijk van resultaat."],
    say:"Wat heb je nu geleerd? Dat is waardevolle informatie.", avoid:"Focussen op wat fout ging." },

  { id:"au31", title:"Competentie versterken", skill:"Autonomie", ageGroups:["3-5","6-9","10-12"], durationMin:5,
    goal:"Kind laten voelen dat het dingen kan.",
    why:"Competentiegevoel motiveert meer dan beloningen.",
    steps:["Geef taak net boven niveau.","Ondersteun minimaal.","Benoem concreet wat lukte."],
    say:"Je deed dat zelf! Jij kon dat al.", avoid:"Te moeilijke taken waardoor falen zeker is." },

  { id:"au32", title:"Mening telt mee", skill:"Autonomie", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Kind ervaren dat zijn/haar mening beslissingen beïnvloedt.",
    why:"Inspraak verhoogt betrokkenheid en respect voor beslissingen.",
    steps:["Bij gezinsbeslissing: neem mening kind serieus mee.","Leg uit hoe het meewoog.","Ook als beslissing anders uitvalt."],
    say:"Jouw mening weegt mee. Wat vind jij?", avoid:"Inspraak simuleren maar uitkomst al vaststaan." },

  { id:"au33", title:"Eigen ochtend regelen", skill:"Autonomie", ageGroups:["10-12","13-16"], durationMin:5,
    goal:"Tiener eigen morgen laten organiseren.",
    why:"Autonomie over opstaan verhoogt motivatie en vermindert conflicten.",
    steps:["Spreek resultaat af (op tijd op school).","Laat hoe aan kind.","Grijp alleen in als resultaat uitblijft."],
    say:"Jij weet hoe laat je weg moet. Dat regel jij.", avoid:"Elke ochtend herinneren." },

  { id:"au34", title:"Grenzen bij vrienden", skill:"Autonomie", ageGroups:["10-12","13-16"], durationMin:5,
    goal:"Kind ondersteunen in grenzen stellen bij vrienden.",
    why:"Grenzen in vriendschappen stellen is een vaardigheid die geleerd moet worden.",
    steps:["Als kind klaagt: vraag wat kind zelf wil.","Bespreek hoe grens te stellen.","Oefen zin samen."],
    say:"Wat wil jij dat verandert? Hoe zou je dat zeggen?", avoid:"Vriend direct afwijzen of conflict overnemen." },

  { id:"au35", title:"Kind als expert", skill:"Autonomie", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Kind legitimiteit geven als expert over eigen leven.",
    why:"Behandeld worden als expert vergroot zelfvertrouwen en authenticiteit.",
    steps:["Vraag kind om advies waar het iets van weet.","Luister serieus.","Geef aan wat je ermee doet."],
    say:"Jij weet hier meer van dan ik. Wat zou jij doen?", avoid:"Altijd de expert zijn." },

  { id:"au36", title:"Risico toestaan", skill:"Autonomie", ageGroups:["3-5","6-9","10-12"], durationMin:10,
    goal:"Kleine risico's durven loslaten.",
    why:"Beheersbaar risico nemen is essentieel voor zelfvertrouwen.",
    steps:["Identificeer iets wat je normaal tegenhoudt.","Laat toe terwijl je in buurt blijft.","Benoem nadien: 'je deed dat zelf!'"],
    say:"Ik zie je — ga maar. Ik ben hier als je me nodig hebt.", avoid:"Constant 'pas op!' roepen." },

  // ── Herstel — 12 extra ───────────────────────────────────────
  { id:"h25", title:"Herstel na schreeuwen", skill:"Herstel", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Direct herstel na de meest voorkomende escalatie.",
    why:"Schreeuwen is meest voorkomende schade — direct herstel beperkt impact.",
    steps:["Zo snel mogelijk (min 10 min): ga naar kind.","'Ik schreeuwde. Dat was niet goed. Sorry.'","Geef ruimte voor reactie."],
    say:"Ik schreeuwde. Dat was niet oké. Sorry. Gaat het?", avoid:"Doen alsof het niet gebeurde." },

  { id:"h26", title:"Excuses in actie", skill:"Herstel", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:10,
    goal:"Sorry omzetten in concreet gedrag.",
    why:"'Sorry' zonder gedragsverandering verliest waarde — kind gelooft daden.",
    steps:["Zeg sorry.","Benoem wat je anders doet.","Doe dat anders, die dag nog."],
    say:"Sorry voor gisteren. Vandaag doe ik het zo: X.", avoid:"Sorry zonder gedragsverandering." },

  { id:"h27", title:"Kwetsbaarheid tonen", skill:"Herstel", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Emotionele openheid als herstelmechanisme.",
    why:"Kwetsbaarheid van vader normaliseert gevoelens en vergroot openheid kind.",
    steps:["Deel moment waarop jij kwetsbaar was.","Gebruik ik-taal, geen drama.","Vraag geen reactie — het is gift."],
    say:"Ik wil je iets vertellen over een moment dat ik het moeilijk had.", avoid:"Kwetsbaarheid als last op kind." },

  { id:"h28", title:"Check-in na moeilijke week", skill:"Herstel", ageGroups:["6-9","10-12","13-16"], durationMin:10,
    goal:"Na zwaar period actief herstellen.",
    why:"Weken met veel conflict hebben herstel nodig om niet te sedimenteren.",
    steps:["Na moeilijke week: erken hardop.","Vraag kind hoe het was.","Doe iets samen dat jullie allebei leuk vinden."],
    say:"Dit was een moeilijke week voor ons. Hoe was het voor jou?", avoid:"Moeilijke weken laten passeren zonder erkenning." },

  { id:"h29", title:"Gratitude ritueel", skill:"Herstel", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Dagelijkse dankbaarheid als smeermiddel.",
    why:"Positieve aandacht correleert direct met veerkracht bij moeilijke momenten.",
    steps:["Elke avond: noem 1 concreet ding dat je waardeert.","Specifiek — niet 'je was lief'.","Vraag kind om hetzelfde."],
    say:"Wat ik vandaag waardeerde: je hielp zonder dat ik het vroeg.", avoid:"Algemene complimenten zonder inhoud." },

  { id:"h30", title:"Verleden benoemen", skill:"Herstel", ageGroups:["10-12","13-16"], durationMin:10,
    goal:"Eerlijk zijn over moeilijke periodes uit verleden.",
    why:"Kinderen weten meer dan ouders denken — openheid schept vertrouwen.",
    steps:["Als er moeilijke periode was: benoem het.","Erken impact op kind.","Bied opening voor vragen."],
    say:"Ik weet dat die periode zwaar was. Heb je vragen?", avoid:"Moeilijke periodes toedekken." },

  { id:"h31", title:"Brief aan toekomstig kind", skill:"Herstel", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:10,
    goal:"Langetermijn intenties verwoorden.",
    why:"Schriftelijk formuleren versterkt kans op gedragsverandering.",
    steps:["Schrijf brief aan kind voor als hij/zij 18 is.","Vertel wat je hoopt voor relatie.","Bewaar brief."],
    say:"(schrijven) 'Lieve X, als je dit leest...'", avoid:"Te veelbelovend — hou het eerlijk." },

  { id:"h32", title:"Contact na afwezigheid", skill:"Herstel", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:10,
    goal:"Na lange afwezigheid band bewust herstellen.",
    why:"Heroveren van nabijheid kost tijd — actief investeren verkort periode.",
    steps:["Verwacht geen direct enthousiasme.","Wees aanwezig zonder te eisen.","Doe iets samen eind eerste dag terug."],
    say:"Ik was er even niet. Ik ben blij je te zien. Wat wil jij doen samen?", avoid:"Verwachten dat het direct weer hetzelfde is." },

  { id:"h33", title:"Foto's samen bekijken", skill:"Herstel", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:10,
    goal:"Gemeenschappelijke herinneringen als bindmiddel.",
    why:"Gedeelde herinneringen versterken 'wij'-gevoel en bieden herstelmateriaal.",
    steps:["Haal samen foto's op.","Vertel verhaal bij foto.","Vraag kind naar hun herinnering."],
    say:"Weet je nog dit? Vertel jouw herinnering.", avoid:"Alleen eigen verhalen, kind niet laten vertellen." },

  { id:"h34", title:"Toekomstfantasie delen", skill:"Herstel", ageGroups:["6-9","10-12","13-16"], durationMin:10,
    goal:"Gezamenlijke toekomst verbeelden.",
    why:"Gedeelde toekomstbeelden versterken verbondenheid en hoop.",
    steps:["Stel voor: 'Wat zou jij willen dat we volgend jaar samen doen?'","Luister enthousiast.","Zet 1 idee om in concrete afspraak."],
    say:"Als je het zelf mocht bepalen: wat zouden we volgend jaar samen doen?", avoid:"Beloven zonder het ooit te doen." },

  { id:"h35", title:"Fysiek herstel", skill:"Herstel", ageGroups:["0-2","3-5","6-9","10-12"], durationMin:2,
    goal:"Via lichaamstaal verbinding herstellen.",
    why:"Jonge kinderen herstellen sneller via aanraking dan woorden.",
    steps:["Ga rustig naast kind zitten.","Vraag of je arm om hem/haar mag slaan.","Zeg niets — laat aanraking spreken."],
    say:"Mag ik even naast je zitten?", avoid:"Woorden stapelen terwijl lichaam al genoeg zegt." },

  { id:"h36", title:"Positief afsluiten voor bed", skill:"Herstel", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Dag altijd in verbinding eindigen.",
    why:"Laatste emotie voor slapen kleurt hoe kind de nacht en volgende dag ervaart.",
    steps:["Noem 1 positief moment van dag.","Zeg 1 warme afsluitende zin.","Geef fysiek contact als dat oké is."],
    say:"Wat ik vandaag fijn vond van jou… Welterusten, ik hou van je.", avoid:"Dag afsluiten met conflict of les." },
];
