import type { Challenge } from "./types";

export const challenges: Challenge[] = [
  // ── A) Aanwezigheid ───────────────────────────────────────────
  {
    id: "a1",
    title: "Telefoon parkeren",
    skill: "Aanwezigheid",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 10,
    goal: "Volle aandacht kunnen geven zonder afleiding.",
    why: "Korte momenten van onverdeelde aandacht verhogen verbinding en maken corrigeren later makkelijker.",
    steps: [
      "Leg je telefoon uit zicht (niet op tafel).",
      "Kies één moment: eten, spel of bedtijd.",
      "Kijk actief: oogcontact, knikken, korte reacties.",
      "Als je afgeleid raakt: benoem en kom terug.",
    ],
    say: "Ik ben even helemaal bij jou.",
    avoid: "Toch 'even snel' iets checken.",
  },
  {
    id: "a2",
    title: "2-minuten check-in",
    skill: "Aanwezigheid",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Verbinden zonder direct te sturen of op te lossen.",
    why: "Kinderen voelen zich sneller gezien als jij eerst begrijpt, daarna pas stuurt.",
    steps: [
      "Stel 1 open vraag (geen ja/nee).",
      "Luister 30–60 sec zonder onderbreken.",
      "Vat samen in 1 zin.",
    ],
    say: "Dus je vond dat vooral irritant/spannend?",
    avoid: "Meteen met oplossingen of adviezen komen.",
  },
  {
    id: "a3",
    title: "Special time: kind leidt",
    skill: "Aanwezigheid",
    ageGroups: ["0-2", "3-5", "6-9", "10-12"],
    durationMin: 10,
    goal: "Volgen in plaats van regisseren.",
    why: "Als je kind mag leiden, groeit veiligheid en samenwerking.",
    steps: [
      "Laat je kind de activiteit kiezen.",
      "Jij volgt: geen lesgeven, geen corrigeren.",
      "Reageer warm: lachen, meedoen, korte opmerkingen.",
    ],
    say: "Jij kiest, ik doe mee.",
    avoid: "Overnemen of verbeteren ('nee zo moet het').",
  },
  {
    id: "a4",
    title: "Beschrijf wat je ziet",
    skill: "Aanwezigheid",
    ageGroups: ["3-5", "6-9"],
    durationMin: 5,
    goal: "Positief contact maken zonder oordeel.",
    why: "Beschrijven voelt veilig en vergroot aandacht/verbinding zonder prestatiedruk.",
    steps: [
      "Benoem 5× wat je kind doet ('je bouwt…').",
      "Gebruik een rustige toon.",
      "Laat daarna 2 seconden stilte.",
    ],
    say: "Je bent echt aan het proberen.",
    avoid: "Alles evalueren ('knap!') als standaard reflex.",
  },
  {
    id: "a5",
    title: "1-op-1 mini-ritueel",
    skill: "Aanwezigheid",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Voorspelbare connectie op een vast moment.",
    why: "Rituelen verlagen stress en verhogen samenwerking.",
    steps: [
      "Kies 1 vast moment (ochtend, thuiskomen, slapen).",
      "Kies 1 vaste actie (knuffel/high five/arm om schouder).",
      "Zeg steeds dezelfde korte zin.",
    ],
    say: "Fijn je te zien, we starten samen.",
    avoid: "Alleen doen als het 'goed' gaat.",
  },
  {
    id: "a6",
    title: "Aandacht vóór correctie",
    skill: "Aanwezigheid",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Eerst verbinding, dan grens/instructie.",
    why: "Correctie landt beter als je kind zich eerst gezien voelt.",
    steps: [
      "Geef 1 connect-zin ('ik zie je').",
      "Dan 1 duidelijke instructie.",
      "Herhaal rustig indien nodig.",
    ],
    say: "Ik zie je. En nu… schoenen aan.",
    avoid: "Corrigeren vanuit haast/irritatie.",
  },

  // ── B) Emotiecoaching ─────────────────────────────────────────
  {
    id: "e1",
    title: "Emotie labelen",
    skill: "Emotiecoaching",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Gevoel herkennen en benoemen zonder toe te geven aan het gedrag.",
    why: "Labelen helpt het zenuwstelsel kalmeren en voorkomt escalatie.",
    steps: [
      "Noem de emotie ('boos/verdrietig').",
      "Normaliseer ('dat snap ik').",
      "Wacht 2 seconden (stilte werkt).",
    ],
    say: "Je bent boos. Dat snap ik.",
    avoid: "Discussie over 'je mag niet boos zijn'.",
  },
  {
    id: "e2",
    title: "Gevoel oké, grens stevig",
    skill: "Emotiecoaching",
    ageGroups: ["3-5", "6-9", "10-12"],
    durationMin: 2,
    goal: "Warm begrenzen: emotie toelaten, gedrag begrenzen.",
    why: "Kind voelt zich begrepen én leert grenzen.",
    steps: [
      "Zeg: gevoel mag.",
      "Zeg: gedrag mag niet.",
      "Bied 1 alternatief.",
    ],
    say: "Je mag boos zijn, je mag niet slaan. Knijp in dit kussen.",
    avoid: "Dreigen/straffen in het heetst.",
  },
  {
    id: "e3",
    title: "Van preek naar empathie",
    skill: "Emotiecoaching",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Minder moraliserend, meer begrip.",
    why: "Empathie opent het gesprek; preken sluit af.",
    steps: [
      "Zeg 1 empathische zin.",
      "Stel 1 vraag.",
      "Pas daarna: optie/advies.",
    ],
    say: "Dat was rot. Wat heb je nu nodig?",
    avoid: "'Zie je nou wel…' toon.",
  },
  {
    id: "e4",
    title: "Keuzetaal bij emotie",
    skill: "Emotiecoaching",
    ageGroups: ["3-5", "6-9"],
    durationMin: 2,
    goal: "Regulatie ondersteunen met simpele keuzes.",
    why: "Keuzes geven grip en verminderen strijd.",
    steps: [
      "Bied 2 regulatie-opties (bij jou / rustig hoekje).",
      "Wacht 5 seconden.",
      "Herhaal exact dezelfde opties.",
    ],
    say: "Wil je even bij mij of even rustig in je hoek?",
    avoid: "Te veel opties geven.",
  },
  {
    id: "e5",
    title: "Puber: validate + nieuwsgierig",
    skill: "Emotiecoaching",
    ageGroups: ["13-16"],
    durationMin: 2,
    goal: "Contact houden zonder controle.",
    why: "Nieuwsgierigheid houdt de deur open, druk duwt dicht.",
    steps: [
      "Erken kort ('snap ik').",
      "Vraag nieuwsgierig ('wat gebeurde er?').",
      "Geen advies, alleen luisteren.",
    ],
    say: "Ik snap dat je daar klaar mee bent. Wat gebeurde er precies?",
    avoid: "Onderzoeken/ondervragen.",
  },
  {
    id: "e6",
    title: "Emoties achter gedrag",
    skill: "Emotiecoaching",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Onderliggende behoefte leren zien.",
    why: "Gedrag is vaak een signaal (moe, onzeker, teleurgesteld).",
    steps: [
      "Doe een zachte gok ('zou het kunnen dat…?').",
      "Check met 1 vraag.",
      "Bied steun (1 kleine actie).",
    ],
    say: "Is dit vooral teleurstelling of vooral spanning?",
    avoid: "Doen alsof je het zeker weet.",
  },

  // ── C) Zelfregulatie ──────────────────────────────────────────
  {
    id: "z1",
    title: "Stop–Adem–Zin",
    skill: "Zelfregulatie",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Pauzeren vóór reageren.",
    why: "Een mini-pauze voorkomt dat jij brandstof op het vuur gooit.",
    steps: [
      "Stop (1 seconde).",
      "1 diepe adem.",
      "Kies 1 rustige zin.",
    ],
    say: "Ik ga dit rustig doen.",
    avoid: "Doorpraten terwijl je kookt.",
  },
  {
    id: "z2",
    title: "Volume omlaag, boodschap kort",
    skill: "Zelfregulatie",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Kalm blijven en duidelijk zijn.",
    why: "Zachter + korter geeft vaak meer gezag dan harder + langer.",
    steps: [
      "Zacht praten.",
      "Max 7 woorden.",
      "Herhaal exact dezelfde zin.",
    ],
    say: "Nu schoenen aan.",
    avoid: "Steeds harder/meer woorden.",
  },
  {
    id: "z3",
    title: "Trigger herkennen",
    skill: "Zelfregulatie",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Patronen ontdekken (wanneer gaat het mis).",
    why: "Herkennen = voorspellen = voorkomen.",
    steps: [
      "Noteer 1 moment dat je geïrriteerd raakte.",
      "Wat voelde je in je lijf?",
      "Wat had je nodig (rust, hulp, pauze)?",
    ],
    say: "Ik ben overprikkeld, ik ga vertragen.",
    avoid: "Jezelf afbranden (het is data, geen oordeel).",
  },
  {
    id: "z4",
    title: "Ik-taal i.p.v. jij-taal",
    skill: "Zelfregulatie",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Minder beschuldigen, meer leiding geven.",
    why: "Ik-taal verlaagt verdediging en houdt contact.",
    steps: [
      "Zeg 'ik merk…'",
      "Zeg wat je nodig hebt/wat er nu gebeurt.",
      "Geef 1 volgende stap.",
    ],
    say: "Ik merk dat ik stress krijg. Ik wil dat we nu afronden.",
    avoid: "Sarcasme/steekjes.",
  },
  {
    id: "z5",
    title: "Herstart na escalatie",
    skill: "Zelfregulatie",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Kunnen resetten midden in gedoe.",
    why: "Resetten doorbreekt de cirkel van boos→boos.",
    steps: [
      "Zeg: 'dit ging mis'.",
      "Pauze 1 adem.",
      "Start opnieuw met 1 stap.",
    ],
    say: "Dit ging mis. We beginnen opnieuw. Wat is stap 1?",
    avoid: "Wie-begon-discussie.",
  },
  {
    id: "z6",
    title: "Zelfzorg micro",
    skill: "Zelfregulatie",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 5,
    goal: "Eigen batterij opladen vóór spitsuur.",
    why: "Een volle batterij = meer geduld en betere keuzes.",
    steps: [
      "5 minuten lopen/rekken/adem.",
      "Zeg tegen jezelf: 'ik laad op'.",
      "Ga daarna pas het lastige moment in.",
    ],
    say: "Ik laad even op zodat ik rustig kan blijven.",
    avoid: "Wachten tot je al leeg bent.",
  },

  // ── D) Grenzen ────────────────────────────────────────────────
  {
    id: "g1",
    title: "1 duidelijke instructie",
    skill: "Grenzen",
    ageGroups: ["3-5", "6-9", "10-12"],
    durationMin: 2,
    goal: "Helderheid geven zonder discussie.",
    why: "Kinderen reageren beter op korte, positieve instructies.",
    steps: [
      "Naam.",
      "Actie.",
      "Nu.",
    ],
    say: "Sam, jas aan. Nu.",
    avoid: "Vraagvorm als het geen keuze is.",
  },
  {
    id: "g2",
    title: "Keuze binnen kader",
    skill: "Grenzen",
    ageGroups: ["3-5", "6-9"],
    durationMin: 2,
    goal: "Samenwerking zonder machtsstrijd.",
    why: "Keuzes geven autonomie binnen jouw grens.",
    steps: [
      "Geef 2 opties die jij oké vindt.",
      "Wacht.",
      "Herhaal.",
    ],
    say: "Tandenpoetsen bij de wasbak of in de douche?",
    avoid: "5 opties geven.",
  },
  {
    id: "g3",
    title: "Eerst–dan",
    skill: "Grenzen",
    ageGroups: ["3-5", "6-9", "10-12"],
    durationMin: 2,
    goal: "Structuur aanbrengen met minimale strijd.",
    why: "Eerst-dan maakt verwachtingen duidelijk.",
    steps: [
      "Noem eerst de taak.",
      "Noem dan iets kleins leuks.",
      "Hou het concreet (tijd/activiteit).",
    ],
    say: "Eerst opruimen, dan 5 minuten lezen.",
    avoid: "'Dan' te groot/vaag.",
  },
  {
    id: "g4",
    title: "Regel vooraf",
    skill: "Grenzen",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Regels vóór conflict afspreken.",
    why: "In conflict is je kind minder bereikbaar; vooraf werkt beter.",
    steps: [
      "Benoem regel + tijd.",
      "Benoem wat jij doet om te helpen.",
      "Herhaal 1× kort.",
    ],
    say: "Om 19:30 gaat het scherm uit. Ik help je stoppen.",
    avoid: "Pas ingrijpen als jij er klaar mee bent.",
  },
  {
    id: "g5",
    title: "Consequent = kalm herhalen",
    skill: "Grenzen",
    ageGroups: ["3-5", "6-9", "10-12"],
    durationMin: 2,
    goal: "Consistent zijn zonder boos te worden.",
    why: "Kalm herhalen is voorspelbaar en veilig.",
    steps: [
      "Zeg dezelfde zin.",
      "Zelfde toon.",
      "Zelfde vervolgstap.",
    ],
    say: "Ik help je nu naar de badkamer.",
    avoid: "Elke herhaling bozer/harder.",
  },
  {
    id: "g6",
    title: "Grenzen met relatie",
    skill: "Grenzen",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Stevig én warm begrenzen.",
    why: "Warmte houdt contact; grens geeft veiligheid.",
    steps: [
      "Erken wens/emotie.",
      "Zeg grens.",
      "Bied nabijheid.",
    ],
    say: "Ik snap dat je door wil. Toch is het klaar. Kom, ik blijf bij je.",
    avoid: "Koud 'omdat ik het zeg'.",
  },

  // ── E) Autonomie ──────────────────────────────────────────────
  {
    id: "au1",
    title: "Laat 1 ding zelf oplossen",
    skill: "Autonomie",
    ageGroups: ["3-5", "6-9", "10-12"],
    durationMin: 5,
    goal: "Niet redden/overnemen.",
    why: "Zelf oplossen bouwt competentie en zelfvertrouwen.",
    steps: [
      "Vraag: 'wat is je plan?'",
      "Wacht (stilte).",
      "Help pas als het echt vastloopt.",
    ],
    say: "Wat zou jij nu kunnen proberen?",
    avoid: "Meteen fixen omdat het sneller is.",
  },
  {
    id: "au2",
    title: "Compliment op moeite",
    skill: "Autonomie",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Inzet/strategie waarderen i.p.v. alleen resultaat.",
    why: "Kind leert: moeite loont, fouten mogen.",
    steps: [
      "Noem moeite ('je bleef proberen').",
      "Noem strategie ('je probeerde een andere manier').",
      "Hou het kort.",
    ],
    say: "Je bleef proberen, ook toen het lastig was.",
    avoid: "Alleen resultaat prijzen.",
  },
  {
    id: "au3",
    title: "Taken als teamwork",
    skill: "Autonomie",
    ageGroups: ["3-5", "6-9", "10-12"],
    durationMin: 5,
    goal: "Samenwerken i.p.v. commanderen.",
    why: "Samen doen verlaagt weerstand en leert routine.",
    steps: [
      "Zeg: '2 minuten samen'.",
      "Zet timer.",
      "Stop als timer klaar is.",
    ],
    say: "We doen dit samen tot de timer gaat.",
    avoid: "Toch alles zelf doen.",
  },
  {
    id: "au4",
    title: "Puber: autonomie met afspraak",
    skill: "Autonomie",
    ageGroups: ["13-16"],
    durationMin: 2,
    goal: "Vrijheid geven met duidelijke randvoorwaarden.",
    why: "Afspraak = vertrouwen + verantwoordelijkheid.",
    steps: [
      "Vraag hun voorstel.",
      "Noem jouw grenzen.",
      "Maak 1 duidelijke afspraak.",
    ],
    say: "Wat vind jij een eerlijke afspraak? Dit zijn mijn grenzen…",
    avoid: "Alles controleren of alles loslaten.",
  },
  {
    id: "au5",
    title: "Keuze reflectie",
    skill: "Autonomie",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Consequenties leren overzien.",
    why: "Reflectie bouwt verantwoordelijkheid zonder preek.",
    steps: [
      "Vraag 2 opties.",
      "Vraag: 'wat gebeurt er dan?'",
      "Laat kind kiezen.",
    ],
    say: "Als je optie A kiest, wat is het gevolg?",
    avoid: "Strikvragen ('gotcha').",
  },
  {
    id: "au6",
    title: "Eén stap vooruit",
    skill: "Autonomie",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Realistische groei: klein en haalbaar.",
    why: "Kleine verbeteringen houden motivatie hoog.",
    steps: [
      "Kies 1 mini-doel voor morgen.",
      "Formuleer als gedrag ('eerst adem…').",
      "Zet het in 1 zin.",
    ],
    say: "Morgen probeer ik: eerst adem, dan praten.",
    avoid: "Te groot doel ('nooit meer boos').",
  },

  // ── F) Herstel ────────────────────────────────────────────────
  {
    id: "h1",
    title: "Sorry + herstelzin",
    skill: "Herstel",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Verantwoordelijkheid nemen en repareren.",
    why: "Herstel na fouten maakt de relatie sterker en leert je kind herstelgedrag.",
    steps: [
      "Zeg sorry.",
      "Noem jouw gedrag (niet het kind).",
      "Zeg wat je anders doet.",
    ],
    say: "Sorry dat ik schreeuwde. Dat was niet oké. Ik ga rustiger praten.",
    avoid: "'Sorry maar jij…'",
  },
  {
    id: "h2",
    title: "Reconnect na conflict",
    skill: "Herstel",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Relatie herstellen zonder opnieuw ruzie te bespreken.",
    why: "Een korte reconnect geeft veiligheid en rust.",
    steps: [
      "Ga dichtbij (naast zitten).",
      "Zeg 1 warme zin.",
      "Klaar (niet doorpraten).",
    ],
    say: "We zijn oké. Ik ben bij je.",
    avoid: "De les herhalen.",
  },
  {
    id: "h3",
    title: "Reparatievraag",
    skill: "Herstel",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Kind leren benoemen wat helpt.",
    why: "Kind leert emoties en behoeften uitspreken.",
    steps: [
      "Vraag: 'wat heb je nodig?'",
      "Luister (niet verdedigen).",
      "Doe 1 kleine herstelactie.",
    ],
    say: "Wat zou jou nu helpen?",
    avoid: "Defensief reageren.",
  },
  {
    id: "h4",
    title: "Waardering uitspreken",
    skill: "Herstel",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Positieve balans in de relatie.",
    why: "Regelmatige waardering verhoogt samenwerking en veiligheid.",
    steps: [
      "Kies 1 concreet moment.",
      "Zeg specifiek wat je waardeert.",
      "Hou het kort.",
    ],
    say: "Ik waardeer dat je net stopte toen ik het vroeg.",
    avoid: "Algemeen 'goed zo' zonder inhoud.",
  },
  {
    id: "h5",
    title: "Team-zin",
    skill: "Herstel",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Samen tegen het probleem (niet tegen elkaar).",
    why: "Team-taal verlaagt strijd en vergroot samenwerking.",
    steps: [
      "Zeg: wij tegen het probleem.",
      "Benoem volgende stap.",
      "Doe stap 1 direct.",
    ],
    say: "Wij tegen de driftbui. Volgende stap: water en adem.",
    avoid: "Het kind als probleem bestempelen.",
  },
  {
    id: "h6",
    title: "Puber: deur open zin",
    skill: "Herstel",
    ageGroups: ["13-16"],
    durationMin: 2,
    goal: "Contact openhouden zonder push.",
    why: "Pubers komen vaak later terug als de druk laag is.",
    steps: [
      "Zeg 1 zin.",
      "Geef ruimte.",
      "Check later nog eens kort.",
    ],
    say: "Ik ben beschikbaar als je wil praten. Geen druk.",
    avoid: "Blijven prikken/vragen.",
  },
  // ── A2) Aanwezigheid — extra 6 ───────────────────────────────
  {
    id: "a7",
    title: "Stilte samen verdragen",
    skill: "Aanwezigheid",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 5,
    goal: "Aanwezig zijn zonder altijd te praten.",
    why: "Comfortabele stilte vergroot vertrouwen — je kind hoeft niet altijd \'on\' te zijn.",
    steps: [
      "Zit naast je kind zonder gesprek te starten.",
      "Doe iets rustig samen (lezen, puzzel, buiten zitten).",
      "Laat hem/haar het gesprek beginnen als het er is.",
    ],
    say: "We hoeven niks te zeggen. Ik ben gewoon hier.",
    avoid: "De stilte vullen met vragen of opmerkingen.",
  },
  {
    id: "a8",
    title: "Aankomsritueel",
    skill: "Aanwezigheid",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "De overgang van werk naar thuis bewust maken.",
    why: "Een korte bewuste overgang reset je hoofd en geeft je kind een warm welkom.",
    steps: [
      "Stop 1 minuut buiten de deur: adem 3x diep.",
      "Zeg bij binnenkomst altijd dezelfde zin.",
      "Geef direct fysiek contact (knuffel, high five).",
    ],
    say: "Hé! Fijn jullie te zien. Ik ben er.",
    avoid: "Direct starten over problemen of agenda.",
  },
  {
    id: "a9",
    title: "Afleiding hardop benoemen",
    skill: "Aanwezigheid",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Eerlijk zijn over afleiding in plaats van het te verbergen.",
    why: "Kinderen merken toch dat je er met je hoofd niet bij bent — eerlijkheid bouwt vertrouwen.",
    steps: [
      "Als je afgeleid bent: zeg het.",
      "Leg uit wat je nodig hebt (\'5 min\').",
      "Kom terug en maak het contact alsnog.",
    ],
    say: "Ik ben even afgeleid. Geef me 5 minuten, dan ben ik er echt.",
    avoid: "Doen alsof je luistert terwijl je dat niet doet.",
  },
  {
    id: "a10",
    title: "Spiegel je kind",
    skill: "Aanwezigheid",
    ageGroups: ["0-2", "3-5", "6-9"],
    durationMin: 5,
    goal: "Non-verbaal verbinding maken door te spiegelen.",
    why: "Spiegelen (toon, tempo, houding) vergroot het gevoel van begrepen worden.",
    steps: [
      "Let op hoe je kind beweegt, praat, klinkt.",
      "Pas jouw tempo en volume iets aan op het zijne.",
      "Benoem wat je ziet: \'je bent lekker druk bezig!\'",
    ],
    say: "Jij hebt echt veel energie vandaag!",
    avoid: "Overdreven nadoen — dat voelt raar.",
  },
  {
    id: "a11",
    title: "Vragen zonder agenda",
    skill: "Aanwezigheid",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 5,
    goal: "Nieuwsgierig zijn zonder een punt te willen maken.",
    why: "Vragen met een verborgen agenda sluiten kinderen af — echte nieuwsgierigheid opent.",
    steps: [
      "Stel een vraag waarop je het antwoord echt niet weet.",
      "Luister zonder te sturen.",
      "Stel een vervolgvraag op wat je kind zegt.",
    ],
    say: "Wat vind jij eigenlijk het leukste aan school dit jaar?",
    avoid: "Vragen als \'heb je al je huiswerk wel gedaan?\'",
  },
  {
    id: "a12",
    title: "Schermvrij eten",
    skill: "Aanwezigheid",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 10,
    goal: "De tafel als verbindingsmoment gebruiken.",
    why: "Schermen bij eten halveren de kwaliteit van gesprek en contact aantoonbaar.",
    steps: [
      "Alle schermen van tafel — ook de jouwe.",
      "Stel 1 tafelgespreksvraag (bv. best/worst moment vandaag).",
      "Laat iedereen om beurten antwoorden.",
    ],
    say: "Vandaag eten we samen, zonder telefoon.",
    avoid: "Zelf je telefoon erbij houden voor noodgevallen.",
  },
  // ── E2) Emotiecoaching — extra 6 ──────────────────────────────
  {
    id: "e7",
    title: "Gevoelswoordenschat uitbreiden",
    skill: "Emotiecoaching",
    ageGroups: ["3-5", "6-9", "10-12"],
    durationMin: 5,
    goal: "Kind meer nuance geven in het benoemen van gevoelens.",
    why: "Meer gevoelswoorden = betere zelfregulatie en minder gedragsuitbarstingen.",
    steps: [
      "Vraag: \'Ben je boos, of ook een beetje bang of verdrietig?\'",
      "Bied 2-3 woorden aan als opties.",
      "Accepteer elk antwoord zonder te corrigeren.",
    ],
    say: "Is het meer teleurstelling of meer frustratie?",
    avoid: "Zeggen welk gevoel hij/zij echt heeft.",
  },
  {
    id: "e8",
    title: "Jouw emotie modelleren",
    skill: "Emotiecoaching",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Emotionele eerlijkheid als vader tonen.",
    why: "Kinderen leren emotieregulatie door te zien hoe jij omgaat met jouw gevoelens.",
    steps: [
      "Benoem je eigen gevoel hardop.",
      "Leg uit wat je doet: \'dus ik ga even ademen\'.",
      "Laat zien dat gevoelens oké zijn én beheersbaar.",
    ],
    say: "Ik merk dat ik gestrest ben. Ik doe even wat rustigers.",
    avoid: "Doen alsof jij geen gevoelens hebt.",
  },
  {
    id: "e9",
    title: "Lichaamssignalen benoemen",
    skill: "Emotiecoaching",
    ageGroups: ["3-5", "6-9", "10-12"],
    durationMin: 5,
    goal: "Kind helpen gevoelens te herkennen via het lichaam.",
    why: "Gevoelens beginnen in het lichaam — dat herkennen is stap 1 van zelfregulatie.",
    steps: [
      "Vraag: \'Wat voel je in je buik of borst?\'",
      "Koppel het aan een gevoel: \'dat klinkt als spanning\'.",
      "Geef 1 lichaamsactie als hulp (diep ademen, schudden).",
    ],
    say: "Ik zie dat je schouders omhoog gaan. Voel je spanning?",
    avoid: "Alleen praten over gevoelens, lichaam vergeten.",
  },
  {
    id: "e10",
    title: "Blije momenten labelen",
    skill: "Emotiecoaching",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Positieve emoties ook actief benoemen.",
    why: "Emotiecoaching gaat niet alleen over moeilijke gevoelens — ook vreugde benoemen versterkt het.",
    steps: [
      "Noem een positief gevoel als je het ziet.",
      "Verbind het aan wat er gebeurde.",
      "Laat het even landen.",
    ],
    say: "Je straalt! Ik zie dat je echt blij bent hiermee.",
    avoid: "Alleen gevoelens benoemen als er problemen zijn.",
  },
  {
    id: "e11",
    title: "Na de storm: terugkijken",
    skill: "Emotiecoaching",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 5,
    goal: "Leren van emotionele momenten zonder preek.",
    why: "Rustig terugkijken na een emotie bouwt emotionele intelligentie zonder beschuldiging.",
    steps: [
      "Wacht tot alles rustig is (minimaal 30 min na incident).",
      "Vraag: \'Wat denk je dat er toen speelde?\'",
      "Luister, stel 1 vervolgvraag, sluit positief af.",
    ],
    say: "Nu het rustig is: wat denk jij dat er toen speelde?",
    avoid: "Terugkijken als straf of les.",
  },
  {
    id: "e12",
    title: "Verhaal als emotiebrug",
    skill: "Emotiecoaching",
    ageGroups: ["3-5", "6-9"],
    durationMin: 10,
    goal: "Via een verhaal een gevoel bespreekbaar maken.",
    why: "Kleine kinderen praten makkelijker over een personage dan over zichzelf.",
    steps: [
      "Vertel een kort verhaal met een dier of held die hetzelfde voelt.",
      "Vraag: \'Wat denk jij dat de beer nu voelde?\'",
      "Verbind zachtjes: \'Ben jij ook wel eens zo?\'",
    ],
    say: "De beer was ook boos toen hij zijn beurt miste. Ken jij dat gevoel?",
    avoid: "Het verhaal te letterlijk maken.",
  },
  // ── Z2) Zelfregulatie — extra 6 ───────────────────────────────
  {
    id: "z7",
    title: "5-4-3-2-1 gronden",
    skill: "Zelfregulatie",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Uit je hoofd komen via zintuigen.",
    why: "Zintuiglijk gronden doorbreekt piekercycli en stress snel en effectief.",
    steps: [
      "Noem 5 dingen die je ziet.",
      "4 die je hoort, 3 die je voelt, 2 ruikt, 1 proeft.",
      "Doe dit hardop of in je hoofd.",
    ],
    say: "Ik ga even gronden. Vijf dingen die ik zie…",
    avoid: "Overslaan omdat het raar voelt.",
  },
  {
    id: "z8",
    title: "Boosheid fysiek afleiden",
    skill: "Zelfregulatie",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Spanning in het lichaam ontladen voor je reageert.",
    why: "Boosheid is energie — bewegen is sneller dan praten om het kwijt te raken.",
    steps: [
      "Loop even weg (fysiek afstand).",
      "Beweeg 30 seconden (trap op/af, rekken, schudden).",
      "Ga dan pas terug.",
    ],
    say: "Ik ga even bewegen. Ben zo terug.",
    avoid: "Wachten tot je rustig denkt terwijl je lijf nog kookt.",
  },
  {
    id: "z9",
    title: "Plan B bedenken",
    skill: "Zelfregulatie",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    durationMin: 5,
    goal: "Vooraf een alternatief gedrag bedenken voor lastige momenten.",
    why: "In het moment zelf is het brein minder beschikbaar — voorbereiding helpt echt.",
    steps: [
      "Identificeer 1 terugkerend lastig moment.",
      "Bedenk wat je dan anders wil doen.",
      "Schrijf het in 1 zin op.",
    ],
    say: "Als ik merk dat ik ga escaleren, doe ik: [plan B].",
    avoid: "Pas plannen maken als je al midden in het moment zit.",
  },
  {
    id: "z10",
    title: "Humor als ventiel",
    skill: "Zelfregulatie",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Spanning doorbreken met luchtigheid.",
    why: "Humor ontspant beiden — maar alleen als het niet sarcastisch of ten koste van het kind is.",
    steps: [
      "Zoek iets absurds in de situatie.",
      "Maak een lichte opmerking over de situatie, niet het kind.",
      "Lach samen — maar vang het gevoel daarna nog op.",
    ],
    say: "Dit is echt een Oscar-waardige driftbui. Indrukwekkend.",
    avoid: "Humor gebruiken om het echte gevoel te vermijden.",
  },
  {
    id: "z11",
    title: "Verwachtingen bijstellen",
    skill: "Zelfregulatie",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Minder frustratie door realistischer verwachten.",
    why: "Veel boosheid komt niet van het kind, maar van onze eigen te hoge verwachtingen.",
    steps: [
      "Vraag jezelf: \'Is dit normaal voor zijn of haar leeftijd?\'",
      "Pas je verwachting aan als dat nodig is.",
      "Reageer dan vanuit die nieuwe verwachting.",
    ],
    say: "Dit is gewoon wat een kind van deze leeftijd doet. Ik ga mee.",
    avoid: "Volwassen gedrag verwachten van een kind.",
  },
  {
    id: "z12",
    title: "Ochtend intentie zetten",
    skill: "Zelfregulatie",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "De dag bewust starten met 1 concreet voornemen.",
    why: "Een intentie van 10 seconden verhoogt de kans dat je hem uitvoert significant.",
    steps: [
      "Kies 1 woord of zin voor vandaag (bv. geduld).",
      "Zeg het hardop voor je de kinderen ziet.",
      "Kom er 's avonds op terug: is het gelukt?",
    ],
    say: "Vandaag kies ik voor: rustig blijven, ook als het druk wordt.",
    avoid: "Te veel intenties tegelijk — 1 is genoeg.",
  },
  // ── G2) Grenzen — extra 6 ─────────────────────────────────────
  {
    id: "g7",
    title: "Grens uitleggen op kindniveau",
    skill: "Grenzen",
    ageGroups: ["3-5", "6-9", "10-12"],
    durationMin: 5,
    goal: "Begrip kweken voor een grens zonder te moraliseren.",
    why: "Kinderen die de reden begrijpen volgen grenzen beter en met minder strijd.",
    steps: [
      "Leg de grens uit in max 2 zinnen.",
      "Gebruik concrete taal.",
      "Check begrip: \'snap je waarom?\'",
    ],
    say: "Dit mag nog niet omdat je hersenen dit nog niet aankunnen. Dat komt later.",
    avoid: "Lange uitleg die een preek wordt.",
  },
  {
    id: "g8",
    title: "Grens herstellen na toegeven",
    skill: "Grenzen",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    durationMin: 5,
    goal: "Terugkomen op een grens die je liet vallen.",
    why: "Inconsistentie is normaal — je kunt altijd resetten zonder gezichtsverlies.",
    steps: [
      "Erken dat je vorige keer toegaf.",
      "Leg rustig uit wat nu geldt.",
      "Houd deze keer wél vast.",
    ],
    say: "Vorige keer ging ik mee. Nu houd ik het bij: dit is de grens.",
    avoid: "Doen alsof het altijd zo was terwijl dat niet klopt.",
  },
  {
    id: "g9",
    title: "Ja op de behoefte",
    skill: "Grenzen",
    ageGroups: ["3-5", "6-9", "10-12"],
    durationMin: 2,
    goal: "Nee op gedrag, ja op de onderliggende behoefte.",
    why: "Een ja op de behoefte verzacht het nee op het gedrag enorm.",
    steps: [
      "Herken de behoefte achter het verzoek.",
      "Zeg nee op dit gedrag.",
      "Bied een alternatief aan dat tegemoetkomt aan de behoefte.",
    ],
    say: "Je wil aandacht — ja! Niet nu schreeuwen. Kom, we doen dit samen.",
    avoid: "Alleen de nee geven zonder de behoefte te zien.",
  },
  {
    id: "g10",
    title: "Non-verbale grens stellen",
    skill: "Grenzen",
    ageGroups: ["0-2", "3-5", "6-9"],
    durationMin: 2,
    goal: "Zonder woorden duidelijkheid geven.",
    why: "Jonge kinderen reageren sterker op houding en expressie dan op woorden.",
    steps: [
      "Ga op kniehoogte zitten.",
      "Maak rustig oogcontact.",
      "Schud langzaam het hoofd of leg hand op de schouder.",
    ],
    say: "(stil, rustig hoofdschudden met oogcontact)",
    avoid: "Van een afstand roepen — dat heeft geen autoriteit.",
  },
  {
    id: "g11",
    title: "Grens als zorg",
    skill: "Grenzen",
    ageGroups: ["10-12", "13-16"],
    durationMin: 2,
    goal: "Grens verbinden aan liefde, niet aan macht.",
    why: "Tieners accepteren grenzen beter als ze voelen dat het uit zorg komt, niet controle.",
    steps: [
      "Begin met: \'dit zeg ik omdat ik om je geef\'.",
      "Noem de concrete zorg.",
      "Stel de grens pas daarna.",
    ],
    say: "Ik zeg dit niet om je te controleren, maar omdat ik wil dat je veilig bent.",
    avoid: "Omdat ik het zeg als enige reden.",
  },
  {
    id: "g12",
    title: "Samen een weekregel maken",
    skill: "Grenzen",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 10,
    goal: "Kind mede-eigenaar maken van een huisregel.",
    why: "Regels die samen gemaakt zijn worden beter nageleefd.",
    steps: [
      "Kies 1 onderwerp (schermen, opruimen, bedtijd).",
      "Vraag kind om voorstel.",
      "Onderhandel tot iets waar jullie beide achter staan.",
    ],
    say: "Wat vind jij een eerlijke regel voor schermtijd in het weekend?",
    avoid: "Doen alsof je onderhandelt maar toch je eigen regel opleggen.",
  },
  // ── AU2) Autonomie — extra 6 ──────────────────────────────────
  {
    id: "au7",
    title: "Fout laten maken",
    skill: "Autonomie",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    durationMin: 5,
    goal: "Ruimte geven om te leren van fouten.",
    why: "Kinderen die fouten mogen maken ontwikkelen veerkracht en probleemoplossend vermogen.",
    steps: [
      "Herken wanneer je wilt ingrijpen om een fout te voorkomen.",
      "Check: is het echt gevaarlijk of alleen niet ideaal?",
      "Als het niet gevaarlijk is: laat het gaan.",
    ],
    say: "Ik zie dat dit misschien niet werkt. Probeer maar — je leert ervan.",
    avoid: "Elke fout vermijden om frustratie te voorkomen.",
  },
  {
    id: "au8",
    title: "Keuze uitleggen",
    skill: "Autonomie",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 5,
    goal: "Inzicht geven in het beslissingsproces.",
    why: "Uitleggen hoe jij een keuze maakt leert kinderen zelf keuzes te overdenken.",
    steps: [
      "Vertel hoe je zelf een keuze maakte.",
      "Noem de overwegingen die je had.",
      "Vraag: \'Hoe zou jij het aanpakken?\'",
    ],
    say: "Ik koos dit omdat… Wat zou jij doen?",
    avoid: "Altijd beslissingen nemen zonder uitleg.",
  },
  {
    id: "au9",
    title: "Verantwoordelijkheid teruggeven",
    skill: "Autonomie",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Kind eigenaar laten worden van zijn probleem.",
    why: "Als jij het probleem oplost, leert je kind dat hij dat niet hoeft.",
    steps: [
      "Als kind een probleem voorlegt: vraag eerst wat hij al geprobeerd heeft.",
      "Luister.",
      "Vraag: \'wat denk je dat een goede volgende stap is?\'",
    ],
    say: "Wat heb je zelf al geprobeerd?",
    avoid: "Meteen de oplossing geven.",
  },
  {
    id: "au10",
    title: "Eigen mening vragen",
    skill: "Autonomie",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 5,
    goal: "Kind leren een mening te vormen en uit te spreken.",
    why: "Kinderen wiens mening gevraagd wordt ontwikkelen zelfvertrouwen en identiteit.",
    steps: [
      "Vraag naar zijn mening over iets alledaags.",
      "Luister serieus.",
      "Reageer inhoudelijk, ook als je het er niet mee eens bent.",
    ],
    say: "Wat vind jij hier eigenlijk van? Ik ben benieuwd.",
    avoid: "Zijn mening wegwuiven of corrigeren.",
  },
  {
    id: "au11",
    title: "Klein risico toestaan",
    skill: "Autonomie",
    ageGroups: ["3-5", "6-9", "10-12"],
    durationMin: 10,
    goal: "Fysieke of sociale uitdaging durven loslaten.",
    why: "Beheersbaar risico nemen is essentieel voor zelfvertrouwen.",
    steps: [
      "Identificeer iets wat je normaal tegenhoudt.",
      "Laat het toe terwijl je in de buurt blijft.",
      "Benoem het nadien: \'je deed dat zelf!\'",
    ],
    say: "Ik zie je — ga maar. Ik ben hier als je me nodig hebt.",
    avoid: "Constant roepen pas op als het niet nodig is.",
  },
  {
    id: "au12",
    title: "Dagplanning zelf maken",
    skill: "Autonomie",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 10,
    goal: "Kind leren plannen en prioriteren.",
    why: "Plannen is een vaardigheid — het oefenen verhoogt zelfstandigheid.",
    steps: [
      "Geef 1 vrije ochtend of middag.",
      "Vraag kind om 3 dingen op te schrijven die hij wil doen.",
      "Laat hem de volgorde bepalen.",
    ],
    say: "Dit is jouw tijd. Wat ga jij doen vandaag?",
    avoid: "Achteraf beoordelen of het een goede planning was.",
  },
  // ── H2) Herstel — extra 6 ─────────────────────────────────────
  {
    id: "h7",
    title: "Verhaal herframen",
    skill: "Herstel",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 5,
    goal: "Na een conflict samen een nieuw verhaal maken.",
    why: "Het conflict herkaderen als wij leren samen in plaats van jij was fout heelt de relatie.",
    steps: [
      "Beschrijf het conflict in 1 zin vanuit wij.",
      "Benoem wat jullie beiden goed deden.",
      "Sluit af met: volgende keer doen we…",
    ],
    say: "We hadden allebei een moeilijk moment. We leren het nog.",
    avoid: "De schuld bij één persoon leggen.",
  },
  {
    id: "h8",
    title: "Fysiek herstel",
    skill: "Herstel",
    ageGroups: ["0-2", "3-5", "6-9", "10-12"],
    durationMin: 2,
    goal: "Via lichaamstaal verbinding herstellen.",
    why: "Jonge kinderen herstellen sneller via aanraking dan via woorden.",
    steps: [
      "Ga rustig naast je kind zitten.",
      "Vraag of je een arm om hem mag slaan.",
      "Zeg niets — laat de aanraking spreken.",
    ],
    say: "Mag ik even naast je zitten?",
    avoid: "Woorden stapelen terwijl het lichaam al genoeg zegt.",
  },
  {
    id: "h9",
    title: "Herstelritueel afspreken",
    skill: "Herstel",
    ageGroups: ["3-5", "6-9", "10-12"],
    durationMin: 5,
    goal: "Een vaste herstelafsluiter afspreken.",
    why: "Een herkenbaar ritueel maakt herstel voorspelbaar en veilig.",
    steps: [
      "Bedenk samen een herstelafsluiter (handdruk, zin, teken).",
      "Gebruik hem consequent na conflicten.",
      "Houd het licht — het mag ook grappig zijn.",
    ],
    say: "Herstel-handdruk? Dan is het klaar tussen ons.",
    avoid: "Herstel afhankelijk maken van excuses of toegeven.",
  },
  {
    id: "h10",
    title: "Schrijf een briefje",
    skill: "Herstel",
    ageGroups: ["6-9", "10-12", "13-16"],
    durationMin: 5,
    goal: "Herstel op papier als er geen gesprek mogelijk is.",
    why: "Een briefje werkt bij kinderen die verbaal dichtklappen na een conflict.",
    steps: [
      "Schrijf max 3 zinnen: sorry, wat je anders doet, dat je van ze houdt.",
      "Leg het op een plek waar ze het vinden.",
      "Verwacht geen directe reactie.",
    ],
    say: "Sorry voor eerder. Ik houd van je.",
    avoid: "Een lang briefje vol uitleg en zelfverdediging.",
  },
  {
    id: "h11",
    title: "Erkennen zonder verklaren",
    skill: "Herstel",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "Pijn erkennen zonder te rechtvaardigen.",
    why: "Verklaringen horen soms als excuses — erkenning alleen is krachtiger.",
    steps: [
      "Zeg wat je deed.",
      "Zeg dat het niet oké was.",
      "Stop daar — geen maar of omdat.",
    ],
    say: "Ik schreeuwde. Dat was niet oké. Punt.",
    avoid: "Excuses toevoegen die de verantwoordelijkheid verdunnen.",
  },
  {
    id: "h12",
    title: "Positief afsluiten voor slaaptijd",
    skill: "Herstel",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    durationMin: 2,
    goal: "De dag altijd in verbinding eindigen.",
    why: "De laatste emotie voor het slapengaan kleurt hoe een kind de nacht en volgende dag ervaart.",
    steps: [
      "Noem 1 positief moment van de dag.",
      "Zeg 1 warme afsluitende zin.",
      "Geef fysiek contact als dat oké is.",
    ],
    say: "Wat ik vandaag fijn vond van jou… Welterusten, ik hou van je.",
    avoid: "De dag afsluiten met een conflict of een les.",
  },

  // ═══════════════════════════════════════════════════════════════
  // EXTRA CHALLENGES — set 3 (voor een vol jaar)
  // ═══════════════════════════════════════════════════════════════

  // ── Aanwezigheid — extra 12 ───────────────────────────────────
  { id:"a13", title:"Verhaaltje zonder boek", skill:"Aanwezigheid", ageGroups:["0-2","3-5","6-9"], durationMin:10,
    goal:"Verbinding via verbeelding zonder extern hulpmiddel.",
    why:"Zelfverzonnen verhalen creëren unieke vader-kind herinneringen die boeken niet kunnen geven.",
    steps:["Vraag: wat voor held wil je in het verhaal?","Verzon samen een avontuur — laat kind details bepalen.","Laat het kind het einde kiezen."],
    say:"Jij bent de hoofdpersoon. Wat gebeurt er als eerste?", avoid:"Verhaal zelf helemaal sturen." },

  { id:"a14", title:"Ochtend samen starten", skill:"Aanwezigheid", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"De dag positief inzetten met gedeeld contact.",
    why:"Een rustige ochtend verbinding verlaagt cortisol voor beiden en verbetert het gedrag op school.",
    steps:["5 minuten samen aan tafel zonder scherm.","Vraag wat hij/zij vandaag leuk vindt aan de dag.","Geef een aanmoedigingszin mee."],
    say:"Wat is vandaag het ding waar je naar uitkijkt?", avoid:"Ochtend starten met taakoverdracht en instructies." },

  { id:"a15", title:"Tekening samen maken", skill:"Aanwezigheid", ageGroups:["3-5","6-9"], durationMin:10,
    goal:"Samen iets creëren zonder resultaat als doel.",
    why:"Creatief samendoen activeert spiegelneuroenen en verhoogt gevoel van verbondenheid.",
    steps:["Pak papier en stiften.","Jij begint, kind maakt af — of andersom.","Geen commentaar op het resultaat."],
    say:"Jij mag verder tekenen waar ik ben gestopt.", avoid:"Corrigeren of het 'mooier' maken." },

  { id:"a16", title:"Buiten wandelen zonder doel", skill:"Aanwezigheid", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:10,
    goal:"Samen in de natuur zijn als laagdrempelige verbinding.",
    why:"Bewegen naast elkaar (niet tegenover) verlaagt de drempel voor spontane gesprekken.",
    steps:["Ga naar buiten zonder bestemming.","Loop het tempo van je kind.","Benoem wat je ziet."],
    say:"Laten we gewoon lopen en kijken wat we tegenkomen.", avoid:"Wandeling omzetten in leermoment of sport." },

  { id:"a17", title:"Interesse oprecht verkennen", skill:"Aanwezigheid", ageGroups:["6-9","10-12","13-16"], durationMin:10,
    goal:"Leren wat je kind echt bezighoudt.",
    why:"Kennis van de echte interesses van je kind is de basis van elke goede relatie.",
    steps:["Vraag je kind je iets te leren over zijn/haar hobby.","Luister als leerling — stel vragen.","Complimenteer het kennen, niet het resultaat."],
    say:"Leg mij eens uit hoe dat werkt. Ik wil het echt begrijpen.", avoid:"Doen alsof je het al weet." },

  { id:"a18", title:"Bedtijd check-in", skill:"Aanwezigheid", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"De dag afsluiten met een moment van echte verbinding.",
    why:"Het donker en de ontspanning voor het slapen verlaagt de drempel om gevoelens te delen.",
    steps:["Ga even zitten op de rand van het bed.","Stel 1 vraag: wat was moeilijk vandaag?","Luister zonder op te lossen."],
    say:"Vertel me 1 ding dat moeilijk was vandaag. Ik luister.", avoid:"Snel de kamer uitlopen." },

  { id:"a19", title:"Samen koken", skill:"Aanwezigheid", ageGroups:["3-5","6-9","10-12"], durationMin:10,
    goal:"Alledaagse taak als verbindingsmoment gebruiken.",
    why:"Naast-elkaar-doen met een gemeenschappelijk doel versterkt gevoel van samenwerking.",
    steps:["Geef kind een echte taak (roeren, afwegen, snijden met veilig mes).","Vertel wat je doet terwijl je het doet.","Eet het resultaat samen op met trots."],
    say:"Jij mag dit gedeelte doen — het is echt belangrijk voor het recept.", avoid:"Alles zelf doen omdat het sneller gaat." },

  { id:"a20", title:"Foto van vandaag", skill:"Aanwezigheid", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Een bewust moment van de dag vastleggen samen.",
    why:"Samen een moment kiezen dat de moeite waard is om te fotograferen vergroot bewuste aandacht.",
    steps:["Vraag: wat was het beste moment vandaag?","Maak samen een foto van iets dat daarmee te maken heeft.","Kijk er samen naar en benoem waarom het bijzonder was."],
    say:"Wat was het mooiste moment vandaag? Laten we het fotograferen.", avoid:"Foto's maken van kind zonder samen te zijn in het moment." },

  { id:"a21", title:"Verrassingsbezoek op school", skill:"Aanwezigheid", ageGroups:["3-5","6-9","10-12"], durationMin:10,
    goal:"Laten zien dat je er voor hem/haar bent buiten de thuisroutine.",
    why:"Onverwachte aanwezigheid versterkt het basisgevoel van veiligheid: 'papa is er voor mij'.",
    steps:["Plan een kleine surprise (lunch brengen, samen naar school lopen).","Maak het gewoon — geen groot vertoon.","Geniet van zijn/haar reactie."],
    say:"Ik dacht: ik kom even langs. Gewoon omdat ik je wilde zien.", avoid:"Er van tevoren te veel over praten." },

  { id:"a22", title:"Lied van vroeger delen", skill:"Aanwezigheid", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Je eigen verhaal delen via muziek.",
    why:"Gedeelde kwetsbaarheid over jouw verleden versterkt de hechting.",
    steps:["Zet een lied op dat jij als kind of tiener luisterde.","Vertel waar je aan denkt.","Vraag kind om zijn/haar favoriete lied te delen."],
    say:"Dit lied deed ik altijd op als kind. Ik dacht aan jou toen ik het hoorde.", avoid:"Oordelen over elkaars muziek." },

  { id:"a23", title:"5 minuten stilzitten samen", skill:"Aanwezigheid", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Rust en aanwezigheid oefenen zonder activiteit.",
    why:"Bewust niets doen naast je kind is een zeldzaam en krachtig signaal van nabijheid.",
    steps:["Ga naast je kind zitten zonder agenda.","Zeg: we doen 5 minuten niks, gewoon samen.","Laat het in stilte zijn."],
    say:"Even niks. Gewoon samen.", avoid:"Stilte onderbreken met vragen of telefoon." },

  { id:"a24", title:"Aandacht als beloning", skill:"Aanwezigheid", ageGroups:["3-5","6-9","10-12"], durationMin:10,
    goal:"Laten zien dat jouw aanwezigheid de mooiste beloning is.",
    why:"Kinderen die aandacht als beloning ervaren worden minder materialistisch en meer intrinsiek gemotiveerd.",
    steps:["Koppel goed gedrag aan samen-tijd: 'omdat je dat fijn deed, doen we iets samen'.","Laat kind kiezen wat.","Wees er écht bij."],
    say:"Omdat jij dat zo goed deed, doe ik vandaag iets met jou alleen.", avoid:"Altijd materiële beloningen geven." },

  // ── Emotiecoaching — extra 12 ─────────────────────────────────
  { id:"e13", title:"Emotiekaart maken", skill:"Emotiecoaching", ageGroups:["3-5","6-9"], durationMin:10,
    goal:"Emotievocabulaire uitbreiden via creatieve oefening.",
    why:"Visuele representatie van gevoelens helpt kinderen die moeilijk verbaal zijn.",
    steps:["Teken samen een leeg gezicht.","Benoem een gevoel en tekenen uitdrukking.","Maak een 'emotiekaart' met 6-8 gevoelens."],
    say:"Hoe ziet blij eruit? En hoe ziet zenuwachtig eruit?", avoid:"Gevoelens vereenvoudigen tot blij/boos/verdrietig." },

  { id:"e14", title:"Gevoelensthermometer", skill:"Emotiecoaching", ageGroups:["6-9","10-12"], durationMin:5,
    goal:"Intensiteit van emoties leren inschatten.",
    why:"Gradatie begrijpen (een beetje boos vs. razend) helpt vroeg de-escaleren.",
    steps:["Bespreek: van 1 (beetje) tot 10 (max).","Vraag hoe hoog de thermometer nu staat.","Bespreek wat helpt op niveau 4 vs. niveau 9."],
    say:"Op een schaal van 1 tot 10 — hoe boos ben je nu?", avoid:"Altijd reageren alsof elk gevoel op niveau 10 zit." },

  { id:"e15", title:"Boze brief schrijven (niet sturen)", skill:"Emotiecoaching", ageGroups:["10-12","13-16"], durationMin:10,
    goal:"Emotionele ontlading via schrijven zonder schade.",
    why:"Expressief schrijven verlaagt emotionele intensiteit en verhoogt zelfbegrip.",
    steps:["Stel voor: schrijf alles op wat je voelt — niemand leest het.","Laat hem/haar schrijven zonder te kijken.","Daarna: verbranden/scheuren of bewaren — eigen keuze."],
    say:"Schrijf alles op wat je wil zeggen. Je hoeft het niet te sturen. Het is voor jou.", avoid:"Stiekem lezen of vragen wat erin staat." },

  { id:"e16", title:"Vader vertelt eigen mislukkingen", skill:"Emotiecoaching", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Veiligheid creëren door eigen kwetsbaarheid te tonen.",
    why:"Kinderen die zien dat vader ook faalt en herstelt leren: fouten zijn menselijk.",
    steps:["Vertel een moment dat jij gefaald hebt.","Beschrijf hoe je je voelde.","Vertel hoe je er mee omging."],
    say:"Mag ik je vertellen over een keer dat ik het echt verkeerd deed?", avoid:"Verhaal te perfect aflopen ('en toen werd alles goed')." },

  { id:"e17", title:"Emoties in films bespreken", skill:"Emotiecoaching", ageGroups:["6-9","10-12","13-16"], durationMin:10,
    goal:"Veilige afstand creëren om over gevoelens te praten.",
    why:"Personages bespreken verlaagt de drempel — het gaat 'niet over jou'.",
    steps:["Kies een moment in een film waar een personage sterk iets voelt.","Vraag: wat denk je dat hij/zij voelt?","Verbind zachtjes: 'Ken jij dat?'"],
    say:"Wat denk jij dat die jongen/dat meisje nu voelde?", avoid:"Meteen je eigen moraal koppelen aan de scène." },

  { id:"e18", title:"Boosheid in het lichaam voelen", skill:"Emotiecoaching", ageGroups:["6-9","10-12"], durationMin:5,
    goal:"Lichaamssignalen koppelen aan de emotie boosheid.",
    why:"Body awareness is de eerste stap in zelfregulatie — het hoofd volgt het lichaam.",
    steps:["Vraag: waar voel jij boosheid in je lijf?","Benoem jouw eigen plek (borst, kaken, schouders).","Oefen: span die plek aan en laat dan los."],
    say:"Ik voel boosheid altijd eerst in mijn kaken. Waar jij?", avoid:"Alleen over het gevoel praten, het lichaam vergeten." },

  { id:"e19", title:"Angst kleiner maken", skill:"Emotiecoaching", ageGroups:["6-9","10-12"], durationMin:10,
    goal:"Angst calibreren via realiteitstoets zonder bagatelliseren.",
    why:"Het brein vergroot dreigingen — bewust kalibreren activeert het rationele deel.",
    steps:["Vraag: wat is precies het ergste dat kan gebeuren?","Vraag: hoe groot is de kans dat dat echt gebeurt?","Vraag: wat zou jij dan doen?"],
    say:"Laten we de angst even bekijken. Wat is precies wat je bang voor bent?", avoid:"'Er is niks om bang voor te zijn' — dat sluit de angst op." },

  { id:"e20", title:"Verdriet ruimte geven", skill:"Emotiecoaching", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Verdriet toelaten zonder te repareren.",
    why:"Verdriet heeft een functie: verlies verwerken. Snel troosten onderbreekt dit proces.",
    steps:["Zit naast je kind bij verdriet.","Zeg: 'Je mag zo lang huilen als je nodig hebt.'","Wacht. Troost pas als kind het initiatief neemt."],
    say:"Je mag verdrietig zijn. Ik ben hier.", avoid:"Meteen afleiding aanbieden of opvrolijken." },

  { id:"e21", title:"Tevredenheid benoemen", skill:"Emotiecoaching", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Positieve emoties bewust verlengen.",
    why:"Positieve emoties zijn vluchtig — bewust aandacht geven aan tevreden momenten vergroot welzijn.",
    steps:["Merk op wanneer je kind tevreden/content is.","Benoem het: 'Ik zie een blije jou.'","Laat het even zin — geen nieuwe activiteit starten."],
    say:"Ik zie dat je tevreden bent nu. Dat is fijn om te zien.", avoid:"Tevreden momenten onderbreken met de volgende activiteit." },

  { id:"e22", title:"Vraag stellen i.p.v. oordelen", skill:"Emotiecoaching", ageGroups:["6-9","10-12","13-16"], durationMin:2,
    goal:"Nieuwsgierigheid als default reactie op gedrag.",
    why:"Vragen openen, oordelen sluiten. Een vraag geeft het kind de kans zichzelf te begrijpen.",
    steps:["Als je wil oordelen: stop, adem.","Formuleer een echte vraag ('wat maakte dat je dat deed?').","Luister het antwoord echt af."],
    say:"Wat maakte dat je dat koos?", avoid:"'Waarom doe je altijd...' — dat is een verkapt oordeel." },

  { id:"e23", title:"Empathie zonder oplossing", skill:"Emotiecoaching", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Aanwezig zijn bij pijn zonder te fixen.",
    why:"Empathie en oplossingen activeren ander gedrag in de ander — empathie bouwt band, oplossingen sluiten soms af.",
    steps:["Luister het volledige verhaal af.","Zeg: 'Dat klinkt echt zwaar/rot/verdrietig.'","Vraag: 'Heb je een oplossing nodig of wil je gewoon dat ik het hoor?'"],
    say:"Dat klinkt echt moeilijk. Wat heb je nu van mij nodig?", avoid:"Direct naar oplossingen springen." },

  { id:"e24", title:"Schaamte normaliseren", skill:"Emotiecoaching", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Schaamte verminderen door te normaliseren en zelf kwetsbaarheid te tonen.",
    why:"Schaamte gedijt in stilte en geheimhouding — licht erop zetten verkleint het.",
    steps:["Herken schaamte bij je kind (hoofd omlaag, vermijden).","Normaliseer: 'Ik schaam me ook wel eens. Iedereen doet dat.'","Deel een eigen moment van schaamte."],
    say:"Ik schaam me ook wel eens. Dat is heel menselijk.", avoid:"Schaamte versterken met opmerkingen over wat anderen denken." },

  // ── Zelfregulatie — extra 12 ──────────────────────────────────
  { id:"z13", title:"Boosheidsprotocol opstellen", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:10,
    goal:"Een persoonlijk protocol hebben voor de momenten dat je kookt.",
    why:"Vooraf bepaald gedrag kost minder cognitieve energie in het moment zelf.",
    steps:["Schrijf op: mijn signaal (wat voel ik in mijn lijf bij opkomende boosheid)?","Schrijf: mijn uitstap (wat doe ik dan?).","Schrijf: mijn terugkeer (hoe kom ik terug?)."],
    say:"Ik ga even weg. Ik ben zo terug als ik rustig ben.", avoid:"Het protocol pas maken als je al midden in een incident zit." },

  { id:"z14", title:"Schuldgevoel omzetten", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Schuldgevoel als informatie gebruiken, niet als zelfkastijding.",
    why:"Schuld signaleert een waardenverschil tussen je gedrag en je intentie — dat is nuttig, zelfkastijding niet.",
    steps:["Erken het schuld gevoel.","Vraag jezelf: wat zegt dit over wat ik echt wil?","Zet om in één concrete actie (herstel of gedragsverandering)."],
    say:"Ik voel schuld. Dat zegt me dat ik het anders wil. Wat is mijn volgende stap?", avoid:"Schuldgevoel als bewijs dat je een slechte vader bent." },

  { id:"z15", title:"Ademhalingsoefening met kind", skill:"Zelfregulatie", ageGroups:["3-5","6-9","10-12"], durationMin:5,
    goal:"Gezamenlijke regulatietechniek aanleren.",
    why:"Als jij en je kind dezelfde techniek kennen, kun je die in het moment samen inzetten.",
    steps:["Oefen samen: 4 tellen in, 4 vast, 6 tellen uit.","Doe dit 3 rondes.","Afspraak: als een van jullie dit doet, doet de ander mee."],
    say:"We doen samen de 4-4-6 adem. Klaar? In...", avoid:"Alleen kind de ademhaling laten doen." },

  { id:"z16", title:"Avond-evaluatie", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Dagelijkse zelfreflectie als vaste gewoonte.",
    why:"Korte dagelijkse reflectie vergroot zelfbewustzijn sneller dan langere wekelijkse sessies.",
    steps:["Elke avond: 1 ding dat goed ging vandaag als vader.","1 ding dat anders kon.","1 voornemen voor morgen."],
    say:"Vandaag ging goed: X. Morgen probeer ik: Y.", avoid:"Alleen de mislukkingen opschrijven." },

  { id:"z17", title:"Eigen behoeften erkennen", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Bewust zijn van wat jij nodig hebt om goed te kunnen geven.",
    why:"Onvervulde eigen behoeften lekken door in irritatie en ongeduld — erkenning vermindert dit.",
    steps:["Vraag jezelf: wat heb ik vandaag nodig? (rust, erkenning, beweging, verbinding).","Communiceer dat behoefte aan je partner/omgeving.","Neem 1 kleine stap om erin te voorzien."],
    say:"Ik merk dat ik rust nodig heb. Ik ga 10 minuten voor mezelf nemen.", avoid:"Eigen behoeften als zwakte of luxe zien." },

  { id:"z18", title:"Pauzeren bij escalatie", skill:"Zelfregulatie", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Bewust stoppen midden in een escalatie.",
    why:"Escalatiespiralen stoppen alleen als iemand uitstapt — dat ben jij als volwassene.",
    steps:["Zeg hardop: 'We stoppen nu even.'","Loop letterlijk weg (of ga zitten).","Kom terug na 1-2 minuten."],
    say:"We stoppen nu. Ik ben over 2 minuten terug.", avoid:"Doorgaan tot het explodeert." },

  { id:"z19", title:"Slaap en geduld koppelen", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Bewustzijn over de impact van slaapgebrek op jouw geduld.",
    why:"Slaaptekort verlaagt prefrontale activiteit — je geduld letterlijk kleiner wordt. Dit is biologie, geen zwakheid.",
    steps:["Noteer: op welke dagen ben ik het meest prikkelbaar?","Correleer met slaap.","Maak 1 afspraak om dit te verbeteren."],
    say:"Ik ben moe vandaag. Dat verklaart waarom ik prikkelbaar ben. Ik pas op.", avoid:"Slaapgebrek negeren en doorgaan alsof er niks aan de hand is." },

  { id:"z20", title:"Perfectionisme loslaten", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Goed genoeg omarmen als voldoende.",
    why:"Perfectionisme bij opvoeden leidt tot chronische stress voor vader en kind. 'Good enough parenting' is bewezen effectief.",
    steps:["Herken een moment waar je te hoge lat legde.","Stel jezelf de vraag: was 80% hier ook genoeg geweest?","Oefen met bewust genoeg laten zijn."],
    say:"Dit is goed genoeg. Ik hoef dit niet perfect te doen.", avoid:"Kinderen opvoeden alsof elk moment bepalend is." },

  { id:"z21", title:"Grenzen stellen naar volwassenen", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Eigen grenzen handhaven als model voor het kind.",
    why:"Kinderen leren grenzen stellen door te zien hoe jij dat doet — ook naar andere volwassenen.",
    steps:["Herken wanneer jij ja zegt maar nee bedoelt.","Oefen een directe nee in een situatie met lage inzet.","Benoem het naar je kind: 'ik zei nee omdat dat mijn grens is.'"],
    say:"Nee, dat werkt niet voor mij.", avoid:"Kinderen leren grenzen stellen maar zelf nooit nee zeggen." },

  { id:"z22", title:"Vergeven van jezelf", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Zelfcompassie als vaardigheid inoefenen.",
    why:"Vaders die zichzelf niet vergeven stapelen schuldgevoel op — dit leidt tot minder consistent gedrag.",
    steps:["Erken het fout gegane moment concreet.","Zeg tegen jezelf: 'Ik deed het niet goed. Ik ben ook een mens.'","Formuleer 1 les en laat de rest los."],
    say:"Ik heb het niet perfect gedaan. Ik vergaf het mezelf. Ik doe het morgen anders.", avoid:"Jezelf blijven straffen na een fout." },

  { id:"z23", title:"Trigger-dagboek bijhouden", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Patronen ontdekken in wanneer jij ontploft.",
    why:"Bewustzijn van triggers is de eerste stap in het veranderen ervan.",
    steps:["Houd 1 week bij: wanneer werd ik boos/geïrriteerd?","Let op patronen (tijd, situatie, vermoeidheid).","Kies 1 trigger om aan te werken."],
    say:"Ik merk dat ik altijd X doe als Y. Ik ga daar bewust op letten.", avoid:"Dagboek bijhouden als aanklacht tegen jezelf." },

  { id:"z24", title:"Hulp vragen durven", skill:"Zelfregulatie", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Hulp als teken van kracht zien, niet van zwakte.",
    why:"Geïsoleerde opvoeding verhoogt stressniveaus. Samen opvoeden — ook met anderen — is evolutionair normaal.",
    steps:["Identificeer 1 situatie waar je hulp kunt gebruiken.","Vraag concreet (wie, wat, wanneer).","Accepteer het zonder 'maar ik had het zelf ook gekund'."],
    say:"Ik vraag hulp bij X. Dat is slim, niet zwak.", avoid:"Alles zelf willen doen als bewijs van goed vaderschap." },

  // ── Grenzen — extra 12 ────────────────────────────────────────
  { id:"g13", title:"Grens uitleggen via gevoel", skill:"Grenzen", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Grenzen koppelen aan jouw gevoel in plaats van aan regels.",
    why:"'Ik voel X' is moeilijker te bestrijden dan 'de regel is X'. Het maakt jou menselijk en de grens persoonlijk.",
    steps:["Benoem de grens.","Leg uit welk gevoel erbij hoort ('ik voel me niet gerespecteerd als...').","Vraag of het kind dat begrijpt."],
    say:"Als je me zo aanspreekt, voel ik me niet gerespecteerd. Dat wil ik niet.", avoid:"Altijd naar regels of autoriteit verwijzen." },

  { id:"g14", title:"Grens als zelfrespect modelleren", skill:"Grenzen", ageGroups:["6-9","10-12","13-16"], durationMin:2,
    goal:"Laten zien dat jij ook grenzen mag hebben.",
    why:"Kinderen leren grenzen stellen door te zien hoe vader dat doet — ook in kleine dagelijkse dingen.",
    steps:["Als iets niet OK is: zeg het direct.","Gebruik ik-taal: 'ik wil dit niet'.","Hou het kort en zonder verontschuldiging."],
    say:"Dit wil ik niet. Ik ga dit even anders aanpakken.", avoid:"Altijd meegaan om conflict te vermijden." },

  { id:"g15", title:"Tijdslimiet met timer communiceren", skill:"Grenzen", ageGroups:["3-5","6-9","10-12"], durationMin:5,
    goal:"Grenzen in de tijd duidelijk en zichtbaar maken.",
    why:"Abstracte tijdsaanduidingen ('zo meteen') werken niet — een zichtbare timer geeft het brein houvast.",
    steps:["Gebruik altijd een zichtbare timer voor tijdsgrenzen.","Kondig aan wat er na de timer gebeurt.","Houd je aan de timer."],
    say:"Als de timer gaat, stoppen we. Je kunt de timer zien.", avoid:"Tijdslimiet steeds verschuiven." },

  { id:"g16", title:"Nee met empathie", skill:"Grenzen", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Nee zeggen op een manier die het kind zich begrepen laat voelen.",
    why:"Een nee met empathie wordt beter geaccepteerd dan een nee zonder — het is een vaardigheid, niet zwakte.",
    steps:["Erken de wens: 'ik snap dat je X wil'.","Zeg de nee duidelijk.","Bied eventueel een alternatief."],
    say:"Ik snap dat je door wil spelen. Het antwoord is nee. We kunnen later...", avoid:"Nee zeggen zonder enige erkenning van de behoefte." },

  { id:"g17", title:"Grens herhalen zonder escaleren", skill:"Grenzen", ageGroups:["3-5","6-9","10-12"], durationMin:2,
    goal:"Kalm consistent blijven bij weigering.",
    why:"Elke keer iets harder reageren leert het kind dat doordrukken loont.",
    steps:["Herhaal precies dezelfde zin.","Zelfde toon, zelfde volume.","Voeg niets toe."],
    say:"Ik zei: nu naar bed. (Herhaal exact, niets toevoegen.)", avoid:"Bij elke herhaling harder/meer uitleggen." },

  { id:"g18", title:"Positieve grens formuleren", skill:"Grenzen", ageGroups:["0-2","3-5","6-9","10-12"], durationMin:2,
    goal:"Grenzen als gewenst gedrag formuleren in plaats van verbod.",
    why:"Het brein verwerkt positieve instructies sneller dan verboden — 'loop' werkt beter dan 'ren niet'.",
    steps:["Vervang verboden door gewenst gedrag.","Wees concreet in wat je WEL wil.","Herhaal bij overtreding de positieve versie."],
    say:"Loop alsjeblieft. (i.p.v. ren niet)", avoid:"Altijd zeggen wat niet mag." },

  { id:"g19", title:"Grens van partner respecteren", skill:"Grenzen", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Consistentie in grenzen tussen ouders versterken.",
    why:"Kinderen zoeken de weg van minste weerstand — inconsistentie tussen ouders levert meer conflicten op.",
    steps:["Bespreek met partner: wat zijn onze niet-onderhandelbare grenzen?","Spreek af: bij twijfel steunen we elkaar.","Nooit de grens van de ander ondergraven voor het kind."],
    say:"Papa/mama heeft dat gezegd. Wij staan daarin samen.", avoid:"De ander als streng neerzetten om zelf populair te zijn." },

  { id:"g20", title:"Grens na overtreding herstellen", skill:"Grenzen", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Na het laten vallen van een grens deze herstellen.",
    why:"Elke keer dat een grens zonder consequentie overschreden wordt, verzwakt die grens.",
    steps:["Erken dat de grens niet gehandhaafd werd.","Herstel: 'Ik had dat niet moeten toestaan.'","Stel de grens opnieuw in."],
    say:"Vorige keer liet ik het gaan. Dat was niet duidelijk van mij. De grens is: X.", avoid:"Doen alsof de eerdere overtreding niet plaatsvond." },

  { id:"g21", title:"Grens vóór het moment", skill:"Grenzen", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Grenzen proactief instellen, niet reactief.",
    why:"In het moment van gedrag is het brein van het kind minder toegankelijk voor regels.",
    steps:["Benoem de verwachting voor de activiteit begint.","Houd het kort: 1-2 regels max.","Vraag een bevestiging ('snap je dit?')."],
    say:"Voor we beginnen: dit zijn de afspraken. Snap je dit?", avoid:"Regels pas noemen als ze overtreden zijn." },

  { id:"g22", title:"Grens met humor", skill:"Grenzen", ageGroups:["3-5","6-9","10-12"], durationMin:2,
    goal:"Grenzen stellen zonder zware sfeer.",
    why:"Lichte humor bij het stellen van grenzen verlaagt weerstand zonder de grens te ondermijnen.",
    steps:["Verpak de grens in een lichte zin of grapje.","Hou de grens zelf serieus.","Check of de boodschap is begrepen."],
    say:"Tijd voor het grote bed-monster avontuur! Richting badkamer, iedereen!", avoid:"Humor gebruiken als de grens al overschreden is." },

  { id:"g23", title:"Grens bij anderen (sociale situaties)", skill:"Grenzen", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Grenzen handhaven ook als anderen kijken.",
    why:"Sociale druk is een veelvoorkomende reden dat vaders grenzen laten vallen — bewustzijn helpt.",
    steps:["Stel je grens in ook als anderen je kind proberen te beïnvloeden.","Leg eventueel later uit waarom.","Ondersteun je kind als anderen de grens niet respecteren."],
    say:"Die afspraak hebben wij thuis. Die geldt ook hier.", avoid:"Grenzen laten vallen om anderen niet voor het hoofd te stoten." },

  { id:"g24", title:"Grens en gevoel scheiden", skill:"Grenzen", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Grens stellen zonder het gevoel van het kind te ontkennen.",
    why:"Gevoelens zijn altijd geldig — gedrag is wat gereguleerd wordt. Dit onderscheid is de basis van warm begrenzen.",
    steps:["Erken het gevoel volledig.","Dan pas: de grens stellen.","Twee aparte zinnen."],
    say:"Jij bent boos. (pauze) En toch: schoenen aan.", avoid:"Grens stellen op het gevoel in plaats van het gedrag." },

  // ── Autonomie — extra 12 ──────────────────────────────────────
  { id:"au13", title:"Echte keuzes geven", skill:"Autonomie", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:2,
    goal:"Onderscheid maken tussen echte keuzes en schijnkeuzes.",
    why:"Schijnkeuzes ondermijnen vertrouwen als het kind doorheeft dat er maar één goed antwoord is.",
    steps:["Bied alleen keuzes aan die jij werkelijk oké vindt.","Accepteer elke keuze.","Als je een keuze niet kan accepteren: maak er geen keuze van."],
    say:"Wil je eerder of later eten? Beide is goed voor mij.", avoid:"'Welk truitje wil je aan?' en dan zeggen 'nee, niet die.'" },

  { id:"au14", title:"Probleemoplossing coachen", skill:"Autonomie", ageGroups:["6-9","10-12","13-16"], durationMin:10,
    goal:"Kind door het oplossingsproces leiden zonder de oplossing te geven.",
    why:"Coachen i.p.v. oplossen bouwt eigenaarschap en probleemoplossend denkvermogen.",
    steps:["Vraag: wat is precies het probleem?","Vraag: welke oplossingen zie jij?","Vraag: welke ga je proberen?"],
    say:"Interessant probleem. Welke oplossingen zie jij zelf?", avoid:"Meteen naar jouw oplossing springen." },

  { id:"au15", title:"Eigen stijl respecteren", skill:"Autonomie", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Kind ruimte geven voor eigen expressie in kleding/haar/kamer.",
    why:"Controle over uiterlijk en ruimte is essentieel voor identiteitsontwikkeling.",
    steps:["Kies 1 domein waar je controle loslaat (kleding, kamer inrichten, haar).","Laat het kind volledig beslissen.","Geef geen commentaar."],
    say:"Jouw kamer, jouw keuze hoe het eruitziet.", avoid:"'Maar dat staat toch niet?'" },

  { id:"au16", title:"Verantwoordelijkheid toewijzen", skill:"Autonomie", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Kind eigenaar maken van een vaste taak.",
    why:"Echte verantwoordelijkheid — niet schijn — bouwt betrouwbaarheid en zelfvertrouwen.",
    steps:["Kies 1 taak die echt van het kind wordt (wasgoed, boodschapjes, planten).","Maak duidelijk dat jij er niet meer op let.","Bespreek wekelijks hoe het gaat."],
    say:"Dit is vanaf nu jouw verantwoordelijkheid. Ik vertrouw erop.", avoid:"Toch controleren of het gedaan is." },

  { id:"au17", title:"Ritme zelf bepalen", skill:"Autonomie", ageGroups:["10-12","13-16"], durationMin:10,
    goal:"Tiener eigen planning laten maken binnen kaders.",
    why:"Zelfbepaling over agenda is een kernbehoefte in de adolescentie.",
    steps:["Geef het kader (huiswerk voor X uur, thuis om X).","Laat het kind het hoe zelf bepalen.","Evalueer resultaat, niet methode."],
    say:"Het huiswerk moet voor morgen af zijn. Hoe jij dat aanpakt is jouw keuze.", avoid:"Constant checken hoe ver het is." },

  { id:"au18", title:"Conflict laten uitvechten", skill:"Autonomie", ageGroups:["6-9","10-12"], durationMin:10,
    goal:"Kinderen zelf conflicten leren oplossen.",
    why:"Conflicten zijn oefenplaatsen voor onderhandelen en empathie — ingrijpen beroofd hen van de oefening.",
    steps:["Als kinderen in conflict zijn: wacht eerst 2 minuten.","Grijp alleen in bij fysiek gevaar.","Als gevraagd: vraag wat zij zelf kunnen doen."],
    say:"Jullie zijn slim genoeg om dit zelf op te lossen. Wat denken jullie?", avoid:"Elk conflict onmiddellijk oplossen." },

  { id:"au19", title:"Falen als leermomenten benoemen", skill:"Autonomie", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Fouten heretiketteren als waardevolle informatie.",
    why:"Groeimindset — fouten als leerkansen zien — wordt aangeleerd, niet geboren.",
    steps:["Na een mislukking: 'Wat heb je nu geleerd?'","Deel je eigen leermomenten uit fouten.","Celebreer de poging, onafhankelijk van resultaat."],
    say:"Wat heb je nu geleerd? Dat is waardevolle informatie.", avoid:"Focussen op wat er fout ging in plaats van wat er geleerd werd." },

  { id:"au20", title:"Gevoel van competentie versterken", skill:"Autonomie", ageGroups:["3-5","6-9","10-12"], durationMin:5,
    goal:"Kind bewust laten voelen dat het dingen kan.",
    why:"Competentiegevoel is een basisbehoefte — het motiveert meer dan beloningen.",
    steps:["Geef een taak die net boven het niveau ligt.","Ondersteun minimaal.","Benoem concreet wat het kind lukte."],
    say:"Je deed dat zelf! Jij kon dat al.", avoid:"Te moeilijke taken geven waardoor falen zeker is." },

  { id:"au21", title:"Mening telt mee", skill:"Autonomie", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Kind ervaring geven dat zijn/haar mening beslissingen beïnvloedt.",
    why:"Inspraak — ook als je soms nee zegt — verhoogt betrokkenheid en respect voor beslissingen.",
    steps:["Neem bij een gezinsbeslissing de mening van je kind serieus mee.","Leg uit hoe het meewoog.","Ook als de beslissing anders uitvalt."],
    say:"Jouw mening weegt mee bij deze beslissing. Wat vind jij?", avoid:"Inspraak simuleren maar de uitkomst al vaststaan." },

  { id:"au22", title:"Eigen ritme 's ochtends", skill:"Autonomie", ageGroups:["10-12","13-16"], durationMin:5,
    goal:"Tiener eigen ochtend laten regelen.",
    why:"Autonomie over het opstaan en klaarmaken verhoogt motivatie en vermindert conflicten.",
    steps:["Spreek het resultaat af (op tijd op school).","Laat het hoe volledig aan het kind.","Grijp alleen in als het resultaat uitblijft."],
    say:"Jij weet hoe laat je weg moet. Dat regel jij.", avoid:"Elke ochtend herinneren en aansturen." },

  { id:"au23", title:"Eigen grenzen bij vriendschappen", skill:"Autonomie", ageGroups:["10-12","13-16"], durationMin:5,
    goal:"Kind ondersteunen in het stellen van eigen grenzen bij vrienden.",
    why:"Grenzen in vriendschappen stellen is een vaardigheid die geleerd moet worden — niet vanzelf gaat.",
    steps:["Als kind klaagt over een vriend: vraag wat het kind zelf wil.","Bespreek hoe een grens te stellen.","Oefen de zin samen."],
    say:"Wat wil jij dat er verandert? Hoe zou je dat kunnen zeggen?", avoid:"De vriend direct afwijzen of het conflict overnemen." },

  { id:"au24", title:"Kind als expert behandelen", skill:"Autonomie", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Kind legitimiteit geven als expert over zijn/haar eigen leven.",
    why:"Behandeld worden als expert over eigen ervaringen vergroot zelfvertrouwen en authenticiteit.",
    steps:["Vraag kind om advies over iets in jouw leven waar het iets van weet.","Luister serieus.","Geef aan wat je ermee doet."],
    say:"Jij weet hier meer van dan ik. Wat zou jij doen?", avoid:"Altijd de expert zijn in het gesprek." },

  // ── Herstel — extra 12 ────────────────────────────────────────
  { id:"h13", title:"Herstel na grote ruzie", skill:"Herstel", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:10,
    goal:"Grote conflicten volledig herstellen.",
    why:"Onhersteld conflict stapelt zich op in de hechtingsrelatie en vermindert veiligheid.",
    steps:["Wacht minimaal 1 uur na het conflict.","Neem het initiatief als vader.","Erken jouw aandeel zonder de ander aan te klagen."],
    say:"Dat was een grote ruzie. Ik wil dat we het herstellen. Mag ik beginnen?", avoid:"Wachten tot het kind het initiatief neemt." },

  { id:"h14", title:"Excuses in actie", skill:"Herstel", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:10,
    goal:"Sorry omzetten in concreet ander gedrag.",
    why:"'Sorry' zonder gedragsverandering verliest zijn waarde — het kind gelooft daden meer dan woorden.",
    steps:["Zeg sorry.","Benoem wat je anders gaat doen.","Doe dat anders, die dag nog."],
    say:"Sorry voor gisteren. Vandaag doe ik het zo: X.", avoid:"Sorry zeggen zonder concrete gedragsverandering." },

  { id:"h15", title:"Eigen jeugd reflecteren", skill:"Herstel", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:10,
    goal:"Patronen uit eigen opvoeding herkennen en doorbreken.",
    why:"Onbewuste herhaling van opvoedpatronen is een van de sterkste voorspellers van vergelijkbaar gedrag.",
    steps:["Denk aan een opvoedmoment van jouw vader.","Vraag: herken ik dit in mij?","Kies bewust anders als het niet goed werkte."],
    say:"Mijn vader deed dit zo. Ik kies ervoor het anders te doen omdat...", avoid:"Eigen opvoeding kritiekloos herhalen of volledig afwijzen." },

  { id:"h16", title:"Herstel na schreeuwen", skill:"Herstel", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Direct herstel na de meest voorkomende escalatie.",
    why:"Schreeuwen is de meest voorkomende schade in de vader-kind relatie — direct herstel beperkt de impact.",
    steps:["Zo snel mogelijk (minimaal 10 min): ga naar je kind.","'Ik schreeuwde. Dat was niet goed van mij. Sorry.'","Geef ruimte voor reactie."],
    say:"Ik schreeuwde net. Dat was niet oké. Sorry. Gaat het?", avoid:"Doen alsof het niet gebeurd is." },

  { id:"h17", title:"Kwetsbaarheid tonen", skill:"Herstel", ageGroups:["6-9","10-12","13-16"], durationMin:5,
    goal:"Emotionele openheid modelleren als herstelmechanisme.",
    why:"Kwetsbaarheid van vader normaliseert gevoelens en vergroot de bereidheid van het kind om open te zijn.",
    steps:["Deel een moment waarop jij je kwetsbaar voelde.","Gebruik ik-taal, geen drama.","Vraag geen reactie — het is een gift, geen uitwisseling."],
    say:"Ik wil je iets vertellen over een moment dat ik het moeilijk had.", avoid:"Kwetsbaarheid als last op het kind leggen." },

  { id:"h18", title:"Check-in na moeilijke week", skill:"Herstel", ageGroups:["6-9","10-12","13-16"], durationMin:10,
    goal:"Na een zwaar period van relatieschade actief herstellen.",
    why:"Weken met veel conflicten hebben herstel nodig om niet te sedimenteren tot negatief beeld.",
    steps:["Na een moeilijke week: erken het hardop.","Vraag kind hoe het was voor hem/haar.","Doe iets samen dat jullie allebei leuk vinden."],
    say:"Dit was een moeilijke week voor ons. Hoe was het voor jou?", avoid:"Moeilijke weken laten voorbij gaan zonder erkenning." },

  { id:"h19", title:"Gratitude als herstelritueel", skill:"Herstel", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:5,
    goal:"Dagelijkse dankbaarheid als smeermiddel voor de relatie.",
    why:"Positieve aandacht correleert direct met veerkracht bij moeilijke momenten.",
    steps:["Elke avond: noem 1 concreet ding dat je waardeert aan je kind van vandaag.","Specifiek — niet 'je was lief'.","Vraag kind om hetzelfde."],
    say:"Wat ik vandaag waardeerde aan jou: je hielp zonder dat ik het vroeg.", avoid:"Algemene complimenten ('je was geweldig') zonder inhoud." },

  { id:"h20", title:"Verleden benoemen", skill:"Herstel", ageGroups:["10-12","13-16"], durationMin:10,
    goal:"Eerlijk zijn over moeilijke periodes uit het verleden.",
    why:"Kinderen weten meer dan ouders denken — openheid schept vertrouwen.",
    steps:["Als er een moeilijke periode was (scheiding, ziekte, werk): benoem het.","Erken de impact op het kind.","Bied opening voor vragen."],
    say:"Ik weet dat die periode zwaar was. Heb je daar vragen over?", avoid:"Moeilijke periodes toedekken alsof ze niet bestonden." },

  { id:"h21", title:"Brief aan toekomstig kind", skill:"Herstel", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:10,
    goal:"Langetermijn intenties voor de relatie verwoorden.",
    why:"Schriftelijk formuleren van bedoelingen versterkt de kans op gedragsverandering.",
    steps:["Schrijf een brief aan je kind voor als hij/zij 18 is.","Vertel wat je hoopt voor jullie relatie.","Bewaar de brief."],
    say:"(schrijven) 'Lieve X, als je dit leest...'", avoid:"Te veelbelovend schrijven — hou het eerlijk." },

  { id:"h22", title:"Contact herstellen na afwezigheid", skill:"Herstel", ageGroups:["0-2","3-5","6-9","10-12","13-16"], durationMin:10,
    goal:"Na lange afwezigheid (werk, reis) de band bewust herstellen.",
    why:"Heroveren van nabijheid na afwezigheid kost tijd — actief investeren verkort die periode.",
    steps:["Verwacht geen direct enthousiasme na terugkomst.","Wees aanwezig en beschikbaar zonder te eisen.","Doe iets samen aan het eind van de eerste dag terug."],
    say:"Ik was er even niet. Ik ben blij je te zien. Wat wil jij doen samen?", avoid:"Verwachten dat het direct weer hetzelfde is." },

  { id:"h23", title:"Familiefoto's samen bekijken", skill:"Herstel", ageGroups:["3-5","6-9","10-12","13-16"], durationMin:10,
    goal:"Gemeenschappelijke herinneringen als bindmiddel gebruiken.",
    why:"Gedeelde herinneringen versterken het gevoel van 'wij' en bieden herstelmateriaal na conflicten.",
    steps:["Haal samen foto's op (telefoon of album).","Vertel een verhaal bij een foto.","Vraag kind naar hun herinnering aan hetzelfde moment."],
    say:"Weet je nog dit? Vertel jouw herinnering hieraan.", avoid:"Alleen eigen verhalen vertellen, kind niet laten vertellen." },

  { id:"h24", title:"Toekomstfantasie delen", skill:"Herstel", ageGroups:["6-9","10-12","13-16"], durationMin:10,
    goal:"Gezamenlijke toekomst verbeelden als verbindingspunt.",
    why:"Gedeelde toekomstbeelden versterken het gevoel van verbondenheid en hoop.",
    steps:["Stel voor: 'Wat zou jij willen dat we volgend jaar samen doen?'","Luister enthousiast.","Zet 1 idee om in een concrete afspraak."],
    say:"Als je het zelf mocht bepalen: wat zouden we volgend jaar samen doen?", avoid:"Beloven zonder het ooit te doen." },

];

export function pickRandomChallenge(
  ageGroup: import("./types").AgeGroup,
  skill: import("./types").Skill,
  excludeId?: string
): Challenge | undefined {
  // Primary pool: matches AND not excluded
  let pool = challenges.filter(
    (c) => c.skill === skill && c.ageGroups.includes(ageGroup) && c.id !== excludeId
  );
  // Fallback: ignore exclude (e.g. pool size = 1)
  if (pool.length === 0) {
    pool = challenges.filter((c) => c.skill === skill && c.ageGroups.includes(ageGroup));
  }
  if (pool.length === 0) return undefined;
  return pool[Math.floor(Math.random() * pool.length)];
}

export function getChallengeById(id: string): Challenge | undefined {
  return challenges.find((c) => c.id === id);
}

// Import en merge extra challenges
import { EXTRA_CHALLENGES } from "./challenges-extra";
challenges.push(...EXTRA_CHALLENGES);
