import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_24: InteractiveTask[] = [
  // ============================================================
  // AGE GROUP 0-2 (10 tasks)
  // ============================================================
  {
    id: 'aanw_0-2_250',
    skill: 'Aanwezigheid',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Rustig ochtendritueel',
    description: 'Begin de dag met een bewust en liefdevol ochtendmoment samen met je baby.',
    instructions: [
      'Haal je baby rustig uit bed en maak oogcontact voordat je iets anders doet.',
      'Benoem zacht wat je ziet: "Goedemorgen, je bent wakker, wat fijn om je te zien."',
      'Neem minstens twee minuten om je baby vast te houden zonder afleiding — geen telefoon.',
      'Let op de signalen van je baby: rekt hij zich uit, kijkt hij rond, maakt hij geluidjes?',
    ],
    reflection: 'Hoe voelde het om de dag te beginnen zonder haast? Merkte je iets nieuws aan je kind?',
    scienceNote: 'Voorspelbare ochtendrituelen versterken de gehechtheidsband en verlagen cortisolniveaus bij zuigelingen (Gunnar & Quevedo, 2007, Psychoneuroendocrinology).',
    durationMin: 5,
  },
  {
    id: 'emco_0-2_251',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Huilen bij overgang',
    description: 'Help je baby bij de overgang van spelen naar slapen door emoties te benoemen.',
    instructions: [
      'Herken de signalen dat je baby moe wordt: wrijven in de ogen, wegkijken, onrustig worden.',
      'Benoem de emotie zacht: "Je bent moe, het was een drukke dag voor jou."',
      'Begin het slapritueel op een vaste manier: dim het licht, zing een liedje of wieg zachtjes.',
      'Als je baby huilt, blijf kalm aanwezig en herhaal je troostende woorden op een rustige toon.',
    ],
    reflection: 'Kon je rustig blijven toen je baby huilde? Wat hielp jou om kalm te blijven?',
    scienceNote: 'Het benoemen van emoties bij pre-verbale kinderen ondersteunt de ontwikkeling van emotieregulatie via co-regulatie (Tronick, 2007, The Neurobehavioral and Social-Emotional Development of Infants and Children).',
    durationMin: 10,
  },
  {
    id: 'zelr_0-2_252',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Ademcheck bij verschonen',
    description: 'Gebruik het verschoonmoment om zelf even bewust te ademen en aanwezig te zijn.',
    instructions: [
      'Leg je baby op de verschoontafel en neem één diepe ademhaling voordat je begint.',
      'Merk op hoe jij je op dit moment voelt: gehaast, ontspannen, geïrriteerd?',
      'Verschoon rustig en maak er een speels contactmoment van met gekke geluidjes of gezichtjes.',
      'Sluit af met een korte buikknuffel en benoem: "Zo, lekker schoon, klaar voor de volgende avontuur."',
    ],
    reflection: 'Hoe vaak verschoon je op de automatische piloot? Wat veranderde er toen je bewust ademhaalde?',
    scienceNote: 'Mindful parenting — bewust aanwezig zijn bij routinehandelingen — vermindert ouderlijke stress en verhoogt sensitieve responsiviteit (Duncan, Coatsworth & Greenberg, 2009, Clinical Child and Family Psychology Review).',
    durationMin: 5,
  },
  {
    id: 'gren_0-2_253',
    skill: 'Grenzen',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Nee bij gevaar, ja bij verbinding',
    description: 'Leer je peuter zachte grenzen door een veilig alternatief te bieden.',
    instructions: [
      'Wacht tot je peuter iets pakt of doet dat niet mag (bijv. aan het fornuis komen).',
      'Zeg rustig en kort "Nee, dat is heet" terwijl je het kind zachtjes weghaalt.',
      'Bied direct een alternatief aan: "Je mag wél met deze pan spelen" of leid af met een ander voorwerp.',
      'Herhaal maximaal drie keer dezelfde boodschap — consistentie is belangrijker dan uitleg op deze leeftijd.',
    ],
    reflection: 'Hoe reageerde je peuter op de grens? Voelde het natuurlijk om meteen een alternatief te bieden?',
    scienceNote: 'Zachte grenzen met herdirectie ondersteunen de ontwikkeling van internalisatie van regels bij peuters (Kochanska, 2002, Developmental Psychology).',
    durationMin: 5,
  },
  {
    id: 'auto_0-2_254',
    skill: 'Autonomie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Zelf eten ontdekken',
    description: 'Geef je peuter ruimte om zelfstandig te eten en de rommel te accepteren.',
    instructions: [
      'Bereid fingerfood voor dat je peuter zelf kan pakken: stukjes banaan, brood, zachte groenten.',
      'Laat je peuter zelf pakken, voelen en proeven zonder het over te nemen.',
      'Weersta de neiging om schoon te vegen tijdens het eten — rommel hoort erbij.',
      'Benoem positief wat je ziet: "Jij pakt zelf de banaan, wat knap!" en sluit het eten samen af.',
    ],
    reflection: 'Hoe moeilijk was het om de controle los te laten? Wat liet je peuter je zien over zijn kunnen?',
    scienceNote: 'Baby-led weaning en autonomieondersteuning bij maaltijden bevorderen zelfregulatie van eetgedrag en motorische ontwikkeling (Townsend & Pitchford, 2012, BMJ Open).',
    durationMin: 15,
  },
  {
    id: 'hers_0-2_255',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Herstel na ongeduldmoment',
    description: 'Herstel de verbinding nadat je per ongeluk te scherp reageerde op je baby.',
    instructions: [
      'Erken bij jezelf dat je net te kortaf of ongeduldig was — dat is menselijk.',
      'Pak je baby op of ga op ooghoogte en zeg zacht: "Sorry lieverd, papa was even niet lief."',
      'Geef een knuffel of aai en laat je stem weer warm en rustig klinken.',
      'Neem een moment om te reflecteren: wat had je nodig om geduldiger te zijn?',
    ],
    reflection: 'Hoe voelde het om sorry te zeggen tegen je baby, ook al begrijpt hij de woorden nog niet?',
    scienceNote: 'Herstelmomenten na interactiebreuken zijn cruciaal voor veilige gehechtheid — het gaat niet om perfectie maar om "good enough" ouderschap (Tronick & Gianino, 1986, Zero to Three).',
    durationMin: 5,
  },
  {
    id: 'verb_0-2_256',
    skill: 'Verbinding',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Badtijd als verbindingsmoment',
    description: 'Maak van het badritueel een voorspelbaar en speels contactmoment.',
    instructions: [
      'Kondig het badje aan met dezelfde zin: "Tijd voor lekker in bad!" zodat je baby het herkent.',
      'Gebruik het water om zachtjes te spelen: spetteren, een badeendje, zingen van een vast liedje.',
      'Maak oogcontact en benoem lichaamsdelen terwijl je wast: "Dit is je buikje, dit zijn je teentjes."',
      'Sluit af met een warm handdoekmoment en een knuffel: "Lekker schoon, lekker warm bij papa."',
    ],
    reflection: 'Merkte je dat je baby het ritueel herkende? Welke reactie viel je op?',
    scienceNote: 'Voorspelbare verzorgingsrituelen bevorderen veilige gehechtheid doordat het kind de wereld als betrouwbaar leert ervaren (Bowlby, 1988, A Secure Base).',
    durationMin: 10,
  },
  {
    id: 'refl_0-2_257',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Dagboek van signalen',
    description: 'Houd een week lang bij welke signalen je baby geeft bij overgangsmomenten.',
    instructions: [
      'Kies drie vaste overgangsmomenten: wakker worden, eten, slapen.',
      'Schrijf elke dag kort op welke signalen je baby geeft vlak voor elk moment (geluidjes, bewegingen, gezichtsuitdrukkingen).',
      'Zoek na drie dagen naar patronen: reageert je baby altijd hetzelfde bij dezelfde overgang?',
      'Pas je aanpak aan op basis van wat je hebt geleerd en schrijf op wat er veranderde.',
    ],
    reflection: 'Welk patroon verraste je het meest? Hoe heeft observeren je begrip van je baby vergroot?',
    scienceNote: 'Reflectief functioneren — het vermogen om het innerlijk van je kind te begrijpen — is een sterke voorspeller van veilige gehechtheid (Slade, 2005, Attachment & Human Development).',
    durationMin: 15,
  },
  {
    id: 'emco_0-2_258',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Co-regulatie bij driftbui',
    description: 'Begeleid je peuter door een driftbui met kalmte en nabijheid.',
    instructions: [
      'Wanneer de driftbui begint, ga op ooghoogte zitten en zorg dat je kind veilig is.',
      'Zeg weinig woorden maar met warme toon: "Ik zie dat je boos bent. Ik ben hier."',
      'Bied fysiek comfort aan als je kind dat toelaat: een hand op de rug, armen openen.',
      'Wacht tot de storm voorbij is en benoem dan: "Dat was een groot gevoel. Het is nu weer rustig."',
    ],
    reflection: 'Wat gebeurde er in jouw lichaam tijdens de driftbui? Kon je je eigen spanning reguleren?',
    scienceNote: 'Co-regulatie door de ouder is de basis voor de ontwikkeling van zelfregulatie bij jonge kinderen (Schore, 2001, Infant Mental Health Journal).',
    durationMin: 10,
  },
  {
    id: 'verb_0-2_259',
    skill: 'Verbinding',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Welkom-thuisritueel',
    description: 'Creëer een vast ritueel voor het moment dat je thuiskomt van werk.',
    instructions: [
      'Spreek met je partner af dat je de eerste twee minuten volledig voor je baby bent als je thuiskomt.',
      'Leg je tas en telefoon neer voordat je je baby begroet — wees er helemaal.',
      'Gebruik elke keer dezelfde begroeting: "Papa is er weer! Wat heb ik je gemist!"',
      'Til je baby op, maak oogcontact en geef een knuffel voordat je iets anders doet.',
    ],
    reflection: 'Hoe reageerde je baby op het vaste thuiskomritueel? Merkte je verschil na een paar dagen?',
    scienceNote: 'Herenigingsgedrag na scheiding is een kernmaat van gehechtheidskwaliteit; voorspelbare hereniging verlaagt stress bij het kind (Ainsworth et al., 1978, Patterns of Attachment).',
    durationMin: 5,
  },

  // ============================================================
  // AGE GROUP 3-5 (10 tasks)
  // ============================================================
  {
    id: 'aanw_3-5_260',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Vijf minuten vloertijd',
    description: 'Ga elke dag vijf minuten op de grond zitten en volg het spel van je kleuter.',
    instructions: [
      'Zet een timer op vijf minuten en ga naast je kind op de grond zitten.',
      'Laat je kind bepalen wat jullie doen — volg zonder te sturen of suggesties te geven.',
      'Benoem hardop wat je kind doet: "Jij bouwt een hoge toren met rode blokken."',
      'Als de timer gaat, sluit positief af: "Dat was leuk samen. Dankjewel dat ik mocht meespelen."',
    ],
    reflection: 'Hoe moeilijk was het om vijf minuten lang niet te sturen? Wat deed je kind toen jij volgde?',
    scienceNote: 'Child-directed play (vloertijd) verhoogt de kwaliteit van de ouder-kindrelatie en vermindert gedragsproblemen (Eyberg et al., 2001, Parent-Child Interaction Therapy).',
    durationMin: 5,
  },
  {
    id: 'zelr_3-5_261',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Kalmte-anker bij ochtendstress',
    description: 'Gebruik een persoonlijk kalmte-anker als het ochtendritme uit de hand loopt.',
    instructions: [
      'Kies een fysiek anker dat je makkelijk kunt doen: voeten stevig op de grond, hand op je hart.',
      'Gebruik het anker zodra je merkt dat je stem luider wordt of je ademhaling versnelt.',
      'Neem drie langzame ademhalingen en zeg tegen jezelf: "Het hoeft niet perfect."',
      'Hervat de ochtendroutine vanuit deze rustigere staat en merk het effect op je kind.',
    ],
    reflection: 'Op welk moment had je het anker het hardst nodig? Merkte je kind het verschil in jouw energie?',
    scienceNote: 'Ouderlijke zelfregulatie is direct gerelateerd aan de kwaliteit van de ouder-kindinteractie, vooral bij stressvolle routinemomenten (Deater-Deckard et al., 2010, Developmental Psychology).',
    durationMin: 10,
  },
  {
    id: 'gren_3-5_262',
    skill: 'Grenzen',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Drie-stappen-grens bij bedtijd',
    description: 'Gebruik een heldere driestapmethode wanneer je kleuter de bedtijdgrens test.',
    instructions: [
      'Geef een vooraankondiging: "Over vijf minuten gaan we tanden poetsen en naar bed."',
      'Bij de grens, wees duidelijk en warm: "Het is nu bedtijd. Welk boekje wil je vanavond?"',
      'Als je kind protesteert, erken het gevoel en houd de grens: "Je wilt nog spelen, dat snap ik. En het is bedtijd."',
      'Houd het consequent — dezelfde drie stappen, elke avond, zonder uitzonderingen.',
    ],
    reflection: 'Hoe reageerde je kind op de voorspelbaarheid? Was het makkelijker of moeilijker dan je dacht?',
    scienceNote: 'Warme maar consistente grenzen bij bedtijdrituelen leiden tot minder slaapverzet en betere slaapkwaliteit bij peuters en kleuters (Mindell et al., 2006, Sleep).',
    durationMin: 10,
  },
  {
    id: 'auto_3-5_263',
    skill: 'Autonomie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Kleding kiezen met twee opties',
    description: 'Geef je kleuter elke ochtend een keuze uit twee outfits.',
    instructions: [
      'Leg de avond ervoor twee geschikte outfits klaar — allebei "goed" zodat elke keuze oké is.',
      "Laat je kind 's ochtends kiezen: 'Wil je het rode shirt of het blauwe shirt?'",
      'Accepteer de keuze zonder commentaar, ook als de combinatie niet matcht.',
      'Benoem de autonomie: "Jij hebt zelf gekozen, wat fijn dat je dat kunt!"',
    ],
    reflection: 'Hoe voelde het om de controle over de kleding los te laten? Wat deed het met de ochtendroutine?',
    scienceNote: 'Autonomieondersteuning door beperkte keuzes bieden verhoogt intrinsieke motivatie en zelfvertrouwen bij kleuters (Deci & Ryan, 2000, Self-Determination Theory).',
    durationMin: 5,
  },
  {
    id: 'hers_3-5_264',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Sorry-ritueel na schreeuwen',
    description: 'Maak een vast herstelritueel voor momenten waarop je je stem verhief.',
    instructions: [
      'Wacht tot je zelf weer rustig bent — herstel werkt niet vanuit activatie.',
      'Ga op ooghoogte bij je kind zitten en zeg: "Papa heeft net geschreeuwd. Dat was niet fijn voor jou."',
      'Benoem wat er bij jou speelde: "Ik was gestrest en dat is niet jouw schuld."',
      'Maak een vast herstelgebaar samen: een speciale knuffel, een high five, of handen op elkaars hart.',
    ],
    reflection: 'Hoe reageerde je kind op je excuses? Merkte je opluchting — bij jezelf of bij je kind?',
    scienceNote: 'Herstel na interactiebreuken leert kinderen dat relaties bestand zijn tegen conflict en versterkt het vertrouwen (Siegel & Bryson, 2012, The Whole-Brain Child).',
    durationMin: 10,
  },
  {
    id: 'verb_3-5_265',
    skill: 'Verbinding',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Drie hoogtepunten aan tafel',
    description: 'Deel elke avond aan tafel drie leuke dingen van de dag met het gezin.',
    instructions: [
      'Begin zelf met het noemen van een hoogtepunt van jouw dag in eenvoudige woorden.',
      'Vraag je kind: "Wat was het leukste dat je vandaag hebt gedaan?"',
      'Luister zonder te corrigeren of door te vragen — accepteer wat je kind deelt.',
      'Sluit af met samen iets te benoemen waar jullie morgen naar uitkijken.',
    ],
    reflection: 'Wat deelde je kind dat je verraste? Hoe veranderde het de sfeer aan tafel?',
    scienceNote: 'Gedeelde maaltijden met positieve conversatie zijn geassocieerd met betere taalontwikkeling en emotioneel welzijn bij kinderen (Fiese et al., 2006, Journal of Marriage and Family).',
    durationMin: 10,
  },
  {
    id: 'refl_3-5_266',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Trigger-dagboek ochtendroutine',
    description: 'Houd een week lang bij welke momenten in de ochtendroutine jou het meest triggeren.',
    instructions: [
      'Schrijf elke ochtend na het wegbrengen drie dingen op: wat ging goed, wat was lastig, wat triggerde mij.',
      'Zoek na vijf dagen naar patronen: is het steeds hetzelfde moment of dezelfde situatie?',
      'Onderzoek wat er achter je trigger zit: tijdsdruk, behoefte aan controle, eigen jeugdervaringen?',
      'Bedenk één concrete aanpassing die je volgende week gaat proberen.',
    ],
    reflection: 'Welk patroon ontdekte je? Herken je iets van je eigen opvoeding in je triggers?',
    scienceNote: 'Reflective functioning bij ouders — het vermogen eigen gedragspatronen te herkennen — vermindert intergenerationele overdracht van onveilige gehechtheid (Fonagy et al., 2002, Affect Regulation, Mentalization and the Development of the Self).',
    durationMin: 15,
  },
  {
    id: 'emco_3-5_267',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Gevoelskleurplaat na school',
    description: 'Help je kleuter om gevoelens over de schooldag te uiten via kleuren.',
    instructions: [
      'Leg na school vier kleuren klaar: rood (boos), blauw (verdrietig), geel (blij), groen (rustig).',
      'Vraag: "Welke kleur past bij hoe je je voelt na school vandaag?"',
      'Laat je kind tekenen of kleuren terwijl je erbij zit — je hoeft niets te zeggen.',
      'Als je kind wil praten, luister dan en benoem: "Dus je voelt je een beetje blauw. Dat mag."',
    ],
    reflection: 'Welke kleur koos je kind het vaakst? Leerde je iets nieuws over hoe de schooldag voelt voor je kind?',
    scienceNote: 'Expressieve kunstvorm helpt jonge kinderen emoties te verwerken die ze verbaal nog niet goed kunnen uiten (Malchiodi, 2011, Handbook of Art Therapy).',
    durationMin: 10,
  },
  {
    id: 'aanw_3-5_268',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Telefoonvrij avonduur',
    description: 'Creëer een dagelijks telefoonvrij uur tussen avondeten en bedtijd.',
    instructions: [
      'Leg je telefoon op een vaste plek buiten de woonkamer — op stil, scherm naar beneden.',
      'Vertel je kind: "De telefoon gaat slapen. Nu is het papa-en-jij-tijd."',
      'Vul het uur met wat er organisch komt: spelen, voorlezen, kletsen, samen opruimen.',
      'Evalueer na een week: hoe voelde dit voor jou en wat merkte je bij je kind?',
    ],
    reflection: 'Hoe vaak greep je automatisch naar je telefoon? Wat veranderde er in het contact met je kind?',
    scienceNote: 'Technoference — onderbrekingen door technologie — is negatief geassocieerd met de kwaliteit van ouder-kindinteractie en kindgedrag (McDaniel & Radesky, 2018, Pediatric Research).',
    durationMin: 15,
  },
  {
    id: 'zelr_3-5_269',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen-ademhalingsoefening',
    description: 'Doe voor het slapengaan samen een eenvoudige ademhalingsoefening.',
    instructions: [
      'Ga samen op bed liggen en leg allebei een knuffeldier op je buik.',
      'Zeg: "We gaan het beertje laten schommelen. Adem in... het beertje gaat omhoog."',
      'Adem samen langzaam uit: "Het beertje gaat weer naar beneden. Lekker rustig."',
      'Doe dit vijf keer en fluister dan: "Je lichaam is nu lekker rustig. Welterusten."',
    ],
    reflection: 'Werd je kind rustiger na de oefening? Hoe voelde het voor jou om samen te vertragen?',
    scienceNote: 'Ademhalingsoefeningen activeren het parasympathisch zenuwstelsel en bevorderen ontspanning, ook bij jonge kinderen (Porges, 2011, The Polyvagal Theory).',
    durationMin: 5,
  },

  // ============================================================
  // AGE GROUP 6-9 (10 tasks)
  // ============================================================
  {
    id: 'verb_6-9_270',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Wandel-en-praat na school',
    description: 'Loop een vast rondje met je kind na school en luister naar zijn verhaal.',
    instructions: [
      'Plan een kort wandelrondje van tien minuten na school — maak het een gewoonte.',
      'Begin niet met vragen over school. Zeg: "Vertel maar, wat wil je kwijt?"',
      'Luister actief: knik, herhaal kort wat je kind zegt, stel geen doorvragen.',
      'Als je kind niets wil vertellen, loop dan samen in stilte — dat is ook verbinding.',
    ],
    reflection: 'Vertelde je kind meer tijdens het lopen dan wanneer je thuis vraagt? Waarom zou dat zo zijn?',
    scienceNote: 'Side-by-side activiteiten zoals wandelen verlagen de drempel voor emotionele communicatie bij kinderen, vooral bij jongens (Kindlon & Thompson, 1999, Raising Cain).',
    durationMin: 10,
  },
  {
    id: 'emco_6-9_271',
    skill: 'Emotiecoaching',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Emotie-thermometer bij huiswerk',
    description: 'Help je kind om frustratieniveaus bij huiswerk te herkennen en benoemen.',
    instructions: [
      'Teken samen een thermometer op papier met niveaus van 1 (rustig) tot 5 (koken van woede).',
      'Leg uit: "Als je bij 3 zit, mogen we even pauzeren. Waar zit je nu?"',
      'Check tijdens het huiswerk twee keer in: "Waar sta je nu op de thermometer?"',
      'Bij niveau 3 of hoger: pauzeer, doe samen iets lichamelijks (springen, schudden) en ga dan verder.',
    ],
    reflection: 'Hielp de thermometer je kind om frustratie te herkennen voordat het escaleerde?',
    scienceNote: 'Het aanleren van emotioneel vocabulaire en zelfmonitoring vermindert emotionele uitbarstingen bij schoolgaande kinderen (Gottman, Katz & Hooven, 1997, Meta-Emotion).',
    durationMin: 15,
  },
  {
    id: 'gren_6-9_272',
    skill: 'Grenzen',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Schermtijd-afspraken samen',
    description: 'Maak samen met je kind duidelijke afspraken over schermtijd na school.',
    instructions: [
      'Ga samen zitten en vraag: "Hoeveel schermtijd denk jij dat goed is op een schooldag?"',
      'Deel jouw grens: "Ik denk dat [X] minuten goed is. Laten we het uitproberen."',
      'Schrijf de afspraak samen op en hang het zichtbaar op (bijv. op de koelkast).',
      'Spreek af wat er gebeurt als de tijd om is: "Een waarschuwing vijf minuten van tevoren, dan stop."',
    ],
    reflection: 'Hoe voelde het om je kind inspraak te geven bij de grens? Hield je kind zich beter aan een zelf-meegemaakt regel?',
    scienceNote: 'Kinderen houden zich beter aan regels die ze begrijpen en waar ze inspraak in hadden, wat past bij inductief opvoeden (Hoffman, 2000, Empathy and Moral Development).',
    durationMin: 10,
  },
  {
    id: 'auto_6-9_273',
    skill: 'Autonomie',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Eigen ochtendroutine-planbord',
    description: 'Laat je kind een eigen ochtendroutine-planbord maken met pictogrammen.',
    instructions: [
      'Geef je kind een karton en stiften en vraag: "Wat moet je allemaal doen voor school?"',
      'Laat je kind de stappen tekenen in de volgorde die hij logisch vindt.',
      'Hang het bord op een plek die je kind zelf kiest — zijn kamer, de badkamer, de gang.',
      'Verwijs de komende week naar het bord in plaats van te commanderen: "Kijk eens op jouw planbord."',
    ],
    reflection: 'Had je kind een andere volgorde gekozen dan jij zou doen? Ging de ochtend soepeler met het bord?',
    scienceNote: 'Visuele routineplanners vergroten het gevoel van competentie en verminderen ouder-kindconflict bij dagelijkse routines (Lucyshyn et al., 2007, Journal of Positive Behavior Interventions).',
    durationMin: 15,
  },
  {
    id: 'hers_6-9_274',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Hersteloefening na ruzie',
    description: 'Gebruik een vast herstelgesprek na een conflict over huiswerk of taken.',
    instructions: [
      'Wacht tot jullie allebei rustig zijn — minimaal twintig minuten na het conflict.',
      'Begin met je eigen aandeel: "Ik was gefrustreerd en ik had rustiger kunnen praten."',
      'Vraag je kind: "Hoe voelde dat voor jou? Wat had je liever gehad?"',
      'Maak samen een plan: "Hoe gaan we het volgende keer anders doen?" en schrijf het op.',
    ],
    reflection: 'Wat vertelde je kind over hoe het conflict voelde? Verraste het antwoord je?',
    scienceNote: 'Expliciet herstelgedrag door ouders leert kinderen conflictresolutievaardigheden en versterkt de relatie (Gottman & DeClaire, 1997, Raising an Emotionally Intelligent Child).',
    durationMin: 15,
  },
  {
    id: 'refl_6-9_275',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Mijn vader, mijn kind, ik',
    description: 'Reflecteer op hoe jouw eigen vader omging met routines en wat je wilt overnemen of veranderen.',
    instructions: [
      'Schrijf drie dingen op die jouw vader deed bij dagelijkse routines (bedtijd, eten, school).',
      'Markeer wat je wilt behouden en wat je anders wilt doen.',
      'Schrijf voor elk "anders"-punt op hoe je het concreet wilt aanpakken.',
      'Deel één positieve herinnering met je kind: "Weet je wat opa altijd deed bij het eten..."',
    ],
    reflection: 'Welke patronen van je eigen vader herken je in jezelf? Wat wil je bewust doorbreken?',
    scienceNote: 'Het doorwerken van de eigen gehechtheidsgeschiedenis is de sterkste voorspeller van gehechtheidskwaliteit bij de volgende generatie (Van IJzendoorn, 1995, Psychological Bulletin).',
    durationMin: 15,
  },
  {
    id: 'aanw_6-9_276',
    skill: 'Aanwezigheid',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Instopritueel met aandacht',
    description: 'Maak van het instoppen een bewust moment van aandacht en verbinding.',
    instructions: [
      'Zit elke avond minstens vijf minuten op de bedrand — niet staand, niet gehaast.',
      'Stel één open vraag: "Waar denk je aan vanavond?" of "Wat zit er in je hoofd?"',
      'Luister zonder advies te geven. Zeg dingen als: "Dat klinkt belangrijk" of "Dank je dat je dat deelt."',
      'Sluit af met een vast ritueel: een zin, een gebaar, een liedje dat van jullie samen is.',
    ],
    reflection: 'Wat vertelde je kind in die vijf minuten dat het overdag niet had gezegd?',
    scienceNote: 'Bedtijdgesprekken zijn een uniek moment voor emotionele openheid; de overgang naar slaap verlaagt afweermechanismen bij kinderen (Fivush, 2008, Human Development).',
    durationMin: 10,
  },
  {
    id: 'zelr_6-9_277',
    skill: 'Zelfregulatie',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Pauzeknop voor papa',
    description: 'Leer je kind dat papa ook een pauze nodig heeft als het even te veel wordt.',
    instructions: [
      'Leg op een rustig moment uit: "Soms wordt het papa ook even te veel. Dan neem ik een pauze."',
      'Spreek een signaalwoord af, bijvoorbeeld "Pitstop!" dat betekent dat je even twee minuten nodig hebt.',
      'Gebruik het signaalwoord als het nodig is, ga even weg, adem, en kom terug.',
      'Zeg bij terugkomst: "Bedankt voor het wachten. Nu ben ik er weer helemaal."',
    ],
    reflection: 'Hoe reageerde je kind op het signaalwoord? Voelde het als zwakte of juist als kracht?',
    scienceNote: 'Ouders die emotieregulatie modelleren — inclusief het nemen van pauzes — leren kinderen dat gevoelens beheersbaar zijn (Morris et al., 2007, Clinical Psychology Review).',
    durationMin: 5,
  },
  {
    id: 'verb_6-9_278',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Weekendritueel creëren',
    description: 'Bedenk samen met je kind een weekendritueel dat van jullie samen is.',
    instructions: [
      'Vraag je kind: "Als wij elke week iets samen zouden doen, wat zou jij kiezen?"',
      'Kies samen één activiteit die haalbaar is: pannenkoeken bakken, een rondje fietsen, een bouwproject.',
      'Plan het op een vast moment (bijv. zaterdagochtend) en bescherm die tijd actief.',
      'Evalueer na vier weken samen: "Zullen we doorgaan, aanpassen of iets nieuws proberen?"',
    ],
    reflection: 'Wat betekent dit ritueel voor je kind? En wat doet het met jullie relatie?',
    scienceNote: 'Gezinsrituelen bieden emotionele veiligheid en versterken het gevoel van saamhorigheid, vooral in tijden van stress (Fiese, 2006, Family Routines and Rituals, Yale University Press).',
    durationMin: 15,
  },
  {
    id: 'emco_6-9_279',
    skill: 'Emotiecoaching',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Overgangsgevoelens benoemen',
    description: 'Help je kind om gevoelens rond de overgang van weekend naar schoolweek te verwoorden.',
    instructions: [
      'Praat op zondagavond even met je kind: "Hoe voel je je als je aan morgen denkt?"',
      'Benoem en normaliseer: "Sommige kinderen vinden het spannend of vervelend. Alles mag."',
      'Vraag: "Is er iets waar je tegenop ziet? Kunnen we daar samen iets voor bedenken?"',
      'Maak samen een klein plan: de schooltas alvast inpakken, een briefje in de broodtrommel, of een vast ochtendritueel.',
    ],
    reflection: 'Wat leerde je over hoe je kind de overgang naar school ervaart? Was je je daar eerder van bewust?',
    scienceNote: 'Emotiecoaching bij anticiperende angst helpt kinderen copingstrategieën te ontwikkelen en vermindert zondagavondstress (Gottman, 1997, Raising an Emotionally Intelligent Child).',
    durationMin: 10,
  },

  // ============================================================
  // AGE GROUP 10-12 (10 tasks)
  // ============================================================
  {
    id: 'auto_10-12_280',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Eigen huiswerkplanning',
    description: 'Laat je kind zelf een weekplanning maken voor huiswerk en toetsen.',
    instructions: [
      'Geef je kind een weekplanner (papier of digitaal) en vraag: "Hoe wil jij je huiswerk deze week verdelen?"',
      'Laat je kind zelf invullen zonder te corrigeren — ook als jij het anders zou doen.',
      'Spreek af dat je aan het eind van de week samen evalueert: "Wat werkte goed, wat wil je aanpassen?"',
      'Bied hulp aan als je kind erom vraagt, maar neem het niet over: "Ik help je denken, niet doen."',
    ],
    reflection: 'Hoe ging het met loslaten? Leerde je kind iets van een planning die niet perfect was?',
    scienceNote: 'Autonomieondersteuning bij schoolwerk is gerelateerd aan hogere intrinsieke motivatie en betere schoolprestaties (Grolnick & Ryan, 1989, Journal of Educational Psychology).',
    durationMin: 15,
  },
  {
    id: 'gren_10-12_281',
    skill: 'Grenzen',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Gesprek over digitale grenzen',
    description: 'Voer een respectvol gesprek over regels rond telefoon en gaming.',
    instructions: [
      'Kies een rustig moment (niet tijdens of na een conflict over schermtijd).',
      'Begin met luisteren: "Wat vind jij eerlijk als het gaat om je telefoon en games?"',
      'Deel jouw zorgen eerlijk: "Ik maak me soms zorgen over [concreet punt]. Begrijp je waarom?"',
      'Maak samen drie afspraken die jullie allebei redelijk vinden en schrijf ze op.',
    ],
    reflection: 'Luisterde je echt naar de argumenten van je kind? Waar kwam jullie het meest overeen?',
    scienceNote: 'Collaboratief grenzen stellen is effectiever bij pre-adolescenten dan eenzijdige regels, omdat het de relatie intact houdt en eigenaarschap vergroot (Grolnick, 2003, The Psychology of Parental Control).',
    durationMin: 10,
  },
  {
    id: 'emco_10-12_282',
    skill: 'Emotiecoaching',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Valideren bij vriendenruzie',
    description: 'Coach je kind door een sociaal conflict zonder het op te lossen.',
    instructions: [
      'Als je kind vertelt over een ruzie, begin met luisteren zonder advies: "Vertel, wat is er gebeurd?"',
      'Valideer het gevoel: "Dat klinkt alsof je je buitengesloten voelde. Dat is heel naar."',
      'Vraag: "Wat zou je het liefst willen dat er nu gebeurt?"',
      'Bied pas advies aan als je kind erom vraagt: "Wil je dat ik meedenk of wil je vooral even kwijt?"',
    ],
    reflection: 'Hoe moeilijk was het om niet meteen met een oplossing te komen? Wat had je kind eigenlijk nodig?',
    scienceNote: 'Emotievalidatie door ouders is geassocieerd met betere sociale competentie en emotieregulatie bij kinderen in de bovenbouw (Eisenberg et al., 1998, Psychological Bulletin).',
    durationMin: 10,
  },
  {
    id: 'hers_10-12_283',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Eerlijk over fout als vader',
    description: 'Deel een moment waarop je als vader een fout maakte en wat je ervan leerde.',
    instructions: [
      'Kies een geschikt moment — niet als reactie op iets dat je kind fout deed.',
      'Vertel eerlijk: "Weet je, gister toen ik [situatie], had ik dat beter kunnen doen."',
      'Leg uit wat je anders had gewild en waarom: "Ik had beter eerst kunnen luisteren."',
      'Vraag je kind: "Hoe voelde dat voor jou? Is er iets dat je wilt dat ik weet?"',
    ],
    reflection: 'Hoe reageerde je kind op je eerlijkheid? Voelde het kwetsbaar, en was dat oké?',
    scienceNote: 'Ouderlijke kwetsbaarheid en het erkennen van fouten modelleren emotionele intelligentie en versterken wederzijds vertrouwen (Brown, 2012, Daring Greatly).',
    durationMin: 10,
  },
  {
    id: 'aanw_10-12_284',
    skill: 'Aanwezigheid',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Autorit als gespreksmoment',
    description: 'Gebruik autoritten als natuurlijk moment voor gesprekken met je kind.',
    instructions: [
      'Zet tijdens de autorit de radio uit en je telefoon op niet-storen.',
      'Begin niet met directe vragen maar met een observatie: "Ik hoorde dat jullie een nieuw project hebben op school."',
      'Laat stiltes vallen — je kind hoeft niet meteen te praten.',
      'Als het gesprek op gang komt, luister meer dan je praat. De auto is een veilige plek omdat er geen oogcontact nodig is.',
    ],
    reflection: 'Vertelde je kind meer dan gebruikelijk? Wat maakt de auto anders dan de eettafel?',
    scienceNote: 'Zij-aan-zij communicatie zonder direct oogcontact verlaagt de drempel voor emotionele gesprekken, vooral bij oudere kinderen (Taffel, 2009, Childhood Unbound).',
    durationMin: 10,
  },
  {
    id: 'zelr_10-12_285',
    skill: 'Zelfregulatie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Herken je eigen patroon',
    description: 'Identificeer je automatische reactie als je kind tegengas geeft bij afspraken.',
    instructions: [
      'Denk aan de laatste drie keer dat je kind een afspraak betwistte. Wat was jouw eerste reactie?',
      'Herken het patroon: word je direct strenger, ga je in discussie, trek je je terug?',
      'Kies bewust een alternatieve reactie: "Ik merk dat ik meteen wil verdedigen. Ik ga eerst luisteren."',
      'Probeer de nieuwe reactie bij de volgende discussie en evalueer wat er veranderde.',
    ],
    reflection: 'Welk patroon ontdekte je bij jezelf? Waar komt dat vandaan denk je?',
    scienceNote: 'Bewustzijn van eigen automatische reactiepatronen (mentaliseren) is essentieel voor responsief ouderschap in de pre-adolescentie (Allen & Fonagy, 2006, Handbook of Mentalization-Based Treatment).',
    durationMin: 15,
  },
  {
    id: 'verb_10-12_286',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Kookavond samen',
    description: 'Kook samen het avondeten en maak er een wekelijks ritueel van.',
    instructions: [
      'Laat je kind een recept kiezen dat jullie samen gaan maken.',
      'Verdeel de taken eerlijk en geef je kind echte verantwoordelijkheid: snijden, roeren, kruiden.',
      'Praat tijdens het koken over van alles — het hoeft niet diep te zijn, gezelligheid telt.',
      'Eet samen op wat jullie gemaakt hebben en benoem: "Dit hebben wij samen gemaakt. Lekker hè?"',
    ],
    reflection: 'Hoe was de sfeer tijdens het koken? Merkte je een ander soort gesprek dan aan de eettafel?',
    scienceNote: 'Gezamenlijke activiteiten waarbij ouder en kind samenwerken bevorderen hechtere relaties en vergroten het gevoel van competentie bij het kind (Larson & Richards, 1994, Divergent Realities).',
    durationMin: 15,
  },
  {
    id: 'refl_10-12_287',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Brief aan je toekomstige kind',
    description: 'Schrijf een brief aan je kind over hoe je nu naar jullie relatie kijkt.',
    instructions: [
      'Neem een rustig moment en schrijf op papier (niet digitaal) een brief aan je kind.',
      'Beschrijf wat je nu waardeert aan wie je kind is en aan jullie relatie.',
      'Benoem eerlijk één ding waaraan je als vader wilt werken.',
      'Bewaar de brief. Overweeg om hem te delen op een betekenisvol moment, of bewaar hem voor later.',
    ],
    reflection: 'Wat kwam er boven toen je schreef? Was het moeilijk om positieve dingen over jezelf als vader te benoemen?',
    scienceNote: 'Expressief schrijven over relaties vergroot zelfbewustzijn en verbetert relatiekwaliteit (Pennebaker, 1997, Psychological Science).',
    durationMin: 15,
  },
  {
    id: 'hers_10-12_288',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Herverbinden na afstandelijkheid',
    description: 'Neem het initiatief om te verbinden als je kind zich terugtrekt.',
    instructions: [
      'Merk op wanneer je kind zich terugtrekt: korte antwoorden, deur dicht, weinig oogcontact.',
      'Dring niet aan maar laat weten dat je er bent: "Ik zie dat je even je eigen ruimte nodig hebt. Ik ben hier als je wilt praten."',
      'Bied later een laagdrempelig contactmoment aan: een drankje brengen, samen iets kijken, een wandeling.',
      'Als je kind opengaat, luister dan zonder verwijt over de afstandelijkheid.',
    ],
    reflection: 'Hoe voelde het om niet aan te dringen? Kwam je kind uiteindelijk naar je toe?',
    scienceNote: 'Het respecteren van de behoefte aan autonomie bij pre-adolescenten terwijl je beschikbaar blijft is kenmerkend voor een veilige basis in gehechtheid (Allen & Land, 1999, Handbook of Attachment).',
    durationMin: 10,
  },
  {
    id: 'aanw_10-12_289',
    skill: 'Aanwezigheid',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Overgangsritueel naar middelbare',
    description: 'Help je kind met de emotionele overgang naar de middelbare school.',
    instructions: [
      'Praat over gemengde gevoelens: "Het is normaal om tegelijk blij en zenuwachtig te zijn."',
      'Deel je eigen herinnering: "Toen ik naar de middelbare ging, voelde ik..."',
      'Maak samen een "toolkit": drie dingen die je kind kan doen als het spannend wordt op school.',
      'Plan een speciaal moment samen in de week voor de start: een uitje, een etentje, iets dat markeert dat er iets nieuws begint.',
    ],
    reflection: 'Welke gevoelens kwamen bij je kind naar boven? En welke herinneringen bij jou?',
    scienceNote: 'Ouderlijke begeleiding bij schooltransities vermindert angst en bevordert aanpassing; erkenning van gemengde gevoelens is hierbij cruciaal (Eccles et al., 1993, American Psychologist).',
    durationMin: 15,
  },

  // ============================================================
  // AGE GROUP 13-16 (10 tasks)
  // ============================================================
  {
    id: 'aanw_13-16_290',
    skill: 'Aanwezigheid',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Beschikbaar zijn zonder druk',
    description: 'Wees fysiek aanwezig in de buurt van je tiener zonder iets te verwachten.',
    instructions: [
      'Ga in dezelfde ruimte zitten als je tiener — lees een boek, werk aan iets.',
      'Zeg niets speciaals, stel geen vragen. Wees er gewoon.',
      'Als je tiener een opmerking maakt of iets deelt, reageer warm maar kort.',
      'Doe dit minstens drie avonden deze week en merk op wat er verandert.',
    ],
    reflection: 'Was het ongemakkelijk om niets te zeggen? Kwam je tiener uit zichzelf naar je toe?',
    scienceNote: 'Beschikbaarheid zonder opdringerigheid is een kernkenmerk van een veilige gehechtheidsbasis voor adolescenten (Moretti & Peled, 2004, Journal of Adolescence).',
    durationMin: 15,
  },
  {
    id: 'emco_13-16_291',
    skill: 'Emotiecoaching',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Luisteren zonder oordeel',
    description: 'Oefen met luisteren naar je tiener zonder te oordelen of te adviseren.',
    instructions: [
      'Wacht tot je tiener iets deelt — over school, vrienden, sociale media, wat dan ook.',
      'Luister volledig: geen telefoon, geen onderbreking, geen "in mijn tijd...".',
      'Reflecteer terug wat je hoort: "Dus je voelt je [gevoel] omdat [situatie]. Klopt dat?"',
      'Vraag alleen: "Wil je dat ik meedenk of wil je dat ik luister?" en respecteer het antwoord.',
    ],
    reflection: 'Hoe moeilijk was het om je mening voor je te houden? Wat leerde je over de wereld van je tiener?',
    scienceNote: 'Niet-oordelend luisteren bevordert zelfvertrouwen en emotionele openheid bij adolescenten (Steinberg, 2001, We Know Some Things: Adolescent-Parent Relationships in Retrospect).',
    durationMin: 10,
  },
  {
    id: 'zelr_13-16_292',
    skill: 'Zelfregulatie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Time-in voor jezelf',
    description: 'Neem bewust een time-in als een gesprek met je tiener dreigt te escaleren.',
    instructions: [
      'Herken je eigen escaalatiesignalen: snellere hartslag, luidere stem, de neiging om te dreigen.',
      'Zeg eerlijk: "Ik merk dat ik gefrustreerd raak. Ik wil dit gesprek goed voeren, dus ik neem even vijf minuten."',
      'Doe iets om te kalmeren: koud water, lopen, ademhalen.',
      'Kom terug en hervat het gesprek vanuit een rustigere plek: "Oké, ik ben er weer. Laten we opnieuw beginnen."',
    ],
    reflection: 'Hoe reageerde je tiener toen je eerlijk zei dat je een pauze nodig had?',
    scienceNote: 'Ouderlijke emotieregulatie modelleert gezonde copingstrategieën en vermindert de kans op destructieve conflictpatronen in het gezin (Patterson, 2002, Journal of Clinical Child Psychology).',
    durationMin: 10,
  },
  {
    id: 'gren_13-16_293',
    skill: 'Grenzen',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Onderhandelen over uitgaan',
    description: 'Voer een onderhandelingsgesprek over uitgaanstijden dat respectvol is voor beide kanten.',
    instructions: [
      'Nodig je tiener uit voor een "zakelijk gesprek": "Ik wil het hebben over uitgaansregels. Niet als straf, maar als afspraak."',
      'Laat je tiener eerst zijn voorstel doen. Luister serieus en schrijf het op.',
      'Deel jouw zorgen concreet: niet "ik vertrouw het niet" maar "ik wil weten dat je veilig bent."',
      'Kom samen tot een proefafspraak voor vier weken, evalueer daarna: "Als dit goed gaat, kunnen we het bijstellen."',
    ],
    reflection: 'Hoe voelde het om te onderhandelen in plaats van te bepalen? Wat zei dit over het vertrouwen tussen jullie?',
    scienceNote: 'Geleidelijke autonomieverruiming binnen duidelijke kaders ondersteunt de identiteitsontwikkeling van adolescenten (Baumrind, 1991, Journal of Early Adolescence).',
    durationMin: 15,
  },
  {
    id: 'auto_13-16_294',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Eigen weekendprogramma',
    description: 'Laat je tiener zelf het weekendprogramma invullen, inclusief verantwoordelijkheden.',
    instructions: [
      'Bespreek op vrijdagavond samen het weekend: "Wat wil je dit weekend doen? Welke taken pakken we aan?"',
      'Laat je tiener zelf kiezen wanneer hij taken doet — respecteer zijn planning.',
      'Spreek alleen het eindresultaat af, niet de route: "Zondag voor 17:00 moet je kamer opgeruimd zijn."',
      'Geef zondag feedback: "Je hebt het gedaan op jouw manier. Hoe vond je dat gaan?"',
    ],
    reflection: 'Kon je het loslaten als je tiener een andere volgorde koos dan jij? Wat deed dat met je?',
    scienceNote: 'Autonomieondersteuning bij dagelijkse taken in de adolescentie voorspelt betere zelfregulatie en minder probleemgedrag (Soenens & Vansteenkiste, 2010, Developmental Review).',
    durationMin: 10,
  },
  {
    id: 'hers_13-16_295',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Doorbreken van de koude muur',
    description: 'Neem het initiatief na een langere periode van afstand of stilte met je tiener.',
    instructions: [
      'Erken bij jezelf dat er afstand is gegroeid — dat is pijnlijk maar normaal.',
      'Zoek een laagdrempelig moment (in de auto, bij het eten) en zeg: "Ik merk dat het minder makkelijk gaat tussen ons. Dat vind ik jammer."',
      'Neem verantwoordelijkheid voor je eigen aandeel: "Misschien heb ik te veel geduwd of te weinig geluisterd."',
      'Stel een klein, concreet voorstel: "Zullen we dit weekend iets samen doen? Jij mag kiezen wat."',
    ],
    reflection: 'Hoe voelde het om de eerste stap te zetten? Wat zegt het over jouw kracht als vader?',
    scienceNote: 'Het nemen van initiatief voor herstel door ouders is cruciaal in de adolescentie; tieners verwachten dat de volwassene de eerste stap zet (Hughes, 2009, Attachment-Focused Parenting).',
    durationMin: 15,
  },
  {
    id: 'verb_13-16_296',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Meedoen in hun wereld',
    description: 'Toon oprechte interesse in iets waar je tiener enthousiast over is.',
    instructions: [
      'Vraag je tiener: "Vertel eens over [game/muziek/sport/serie] — ik wil het begrijpen."',
      'Luister alsof je een nieuw vak leert. Stel nieuwsgierige vragen, geen oordelende.',
      'Probeer het zelf: kijk een aflevering, luister naar een nummer, speel een potje mee.',
      'Deel je eerlijke ervaring: "Ik snap nu beter waarom je dit leuk vindt, ook al is het niet mijn ding."',
    ],
    reflection: 'Hoe reageerde je tiener op je oprechte interesse? Veranderde het iets in jullie dynamiek?',
    scienceNote: 'Ouderlijke betrokkenheid bij de interesses van adolescenten versterkt de relatie en verlaagt het risico op emotionele problemen (Hair et al., 2008, Journal of Family Psychology).',
    durationMin: 15,
  },
  {
    id: 'refl_13-16_297',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'De vader die ik wil zijn',
    description: 'Definieer bewust wie je wilt zijn als vader voor je tiener in deze fase.',
    instructions: [
      'Schrijf op: "Drie woorden die beschrijven hoe mijn tiener mij nu ervaart als vader."',
      'Schrijf op: "Drie woorden die beschrijven hoe ik wil dat mijn tiener mij ervaart."',
      'Vergelijk de twee lijsten. Waar zit het verschil en wat is er nodig om dat te overbruggen?',
      'Kies één concreet gedrag dat je deze week gaat veranderen en voer het uit.',
    ],
    reflection: 'Wat was het pijnlijkst om toe te geven? En wat gaf je het meeste hoop?',
    scienceNote: 'Zelfbewuste ouders die hun gedrag afstemmen op hun waarden tonen minder reactief en meer responsief ouderschap (Kabat-Zinn & Kabat-Zinn, 1997, Everyday Blessings: The Inner Work of Mindful Parenting).',
    durationMin: 15,
  },
  {
    id: 'zelr_13-16_298',
    skill: 'Zelfregulatie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Ochtendroutine zonder strijd',
    description: 'Laat je tiener zelf de gevolgen ervaren van een slechte ochtendroutine.',
    instructions: [
      'Stop met wekken, aanjagen en waarschuwen — laat je tiener zelf verantwoordelijk zijn.',
      'Leg van tevoren uit: "Vanaf nu is de ochtend jouw verantwoordelijkheid. Ik vertrouw erop dat je het kunt."',
      'Als het misgaat (te laat, ontbijt vergeten), reageer neutraal: "Dat is vervelend. Hoe ga je het morgen anders doen?"',
      'Geef een compliment als het goed gaat: "Je hebt het zelf geregeld. Knap."',
    ],
    reflection: 'Hoe moeilijk was het om niet in te grijpen? Wat leerde je tiener van de natuurlijke gevolgen?',
    scienceNote: 'Natuurlijke gevolgen laten ervaren — binnen veilige grenzen — bevordert zelfverantwoordelijkheid en executieve functies bij adolescenten (Steinberg, 2004, The 10 Basic Principles of Good Parenting).',
    durationMin: 5,
  },
  {
    id: 'gren_13-16_299',
    skill: 'Grenzen',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Grens als zorgboodschap',
    description: 'Formuleer een grens als uiting van zorg in plaats van controle.',
    instructions: [
      'Kies een actuele grens waar spanning over is (bedtijd, telefoon in slaapkamer, alcohol).',
      'Herformuleer de grens vanuit zorg: niet "Je mag niet..." maar "Ik maak me zorgen over... omdat ik om je geef."',
      'Leg uit wat de grens voor jou betekent: "Het helpt mij om te weten dat je veilig bent."',
      'Vraag je tiener hoe hij de grens ervaart en of er ruimte is voor aanpassing.',
    ],
    reflection: 'Hoe reageerde je tiener op de zorgboodschap? Was er meer begrip dan bij een verbod?',
    scienceNote: 'Adolescenten accepteren grenzen beter wanneer ze de onderliggende zorg begrijpen; dit versterkt internalisatie van normen (Kerr & Stattin, 2000, Child Development).',
    durationMin: 10,
  },
];
