import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_21: InteractiveTask[] = [
  // ============================================================
  // AGE GROUP 0-2 (10 tasks: 3 basis, 4 gevorderd, 3 expert)
  // ============================================================
  {
    id: 'aanw_02_100',
    skill: 'Aanwezigheid',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Stille observatie bij het spelen',
    description: 'Observeer je baby of peuter vijf minuten zonder in te grijpen tijdens vrij spel.',
    instructions: [
      'Zet je telefoon weg en ga op de grond zitten bij je kind.',
      'Observeer vijf minuten lang wat je kind doet zonder te sturen of speelgoed aan te bieden.',
      'Let op gezichtsuitdrukkingen, geluiden en bewegingen van je kind.',
      'Als je kind naar je kijkt, glimlach dan warm en benoem kort wat je ziet.',
    ],
    reflection: 'Wat viel je op aan het spel van je kind dat je normaal zou missen als je bezig bent met je telefoon?',
    scienceNote: 'Mindful aanwezigheid van ouders verhoogt de kwaliteit van ouder-kindinteracties en bevordert veilige hechting (Ainsworth, 1978; Biringen et al., 2014).',
    durationMin: 5,
  },
  {
    id: 'emco_02_101',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Emoties benoemen bij huilen',
    description: 'Benoem de emotie van je baby wanneer deze huilt of onrustig is.',
    instructions: [
      'Wacht het volgende huilmoment van je kind af (forceer dit niet).',
      'Pak je kind op of ga dichtbij en maak oogcontact.',
      'Benoem de mogelijke emotie: "Je bent verdrietig" of "Je schrikt ervan, h\u00e8?".',
      'Bied troost door te wiegen, zachtjes te praten of huid-op-huidcontact.',
      'Blijf kalmte uitstralen, ook als het huilen even aanhoudt.',
    ],
    reflection: 'Hoe voelde het om de emotie van je kind te benoemen in plaats van meteen het huilen te willen stoppen?',
    scienceNote: 'Het benoemen van emoties (affect labeling) activeert de prefrontale cortex en helpt bij emotieregulatie, ook bij zeer jonge kinderen (Lieberman et al., 2007).',
    durationMin: 10,
  },
  {
    id: 'zelr_02_102',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Ademhaling als anker',
    description: 'Gebruik je eigen ademhaling om kalm te blijven tijdens een onrustig moment met je baby.',
    instructions: [
      'Merk een moment op waarop je baby onrustig is en jij spanning voelt opkomen.',
      'Houd je baby vast en adem bewust drie keer diep in door je neus en uit door je mond.',
      'Voel hoe je lichaam ontspant bij elke uitademing.',
      'Praat met een langzame, lage stem tegen je kind terwijl je kalm blijft ademen.',
    ],
    reflection: 'Merkte je dat je eigen kalmte invloed had op de onrust van je baby?',
    scienceNote: 'Co-regulatie via het autonome zenuwstelsel van de ouder be\u00efnvloedt direct de stressrespons van het kind (Feldman, 2007; Porges\u2019 polyvagaaltheorie).',
    durationMin: 5,
  },
  {
    id: 'verb_02_103',
    skill: 'Verbinding',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Gezichtsspelletje',
    description: 'Speel een gezichtsspelletje met je baby om de sociale band te versterken.',
    instructions: [
      'Ga recht tegenover je baby zitten zodat jullie oogcontact kunnen maken.',
      'Trek langzaam een grappig gezicht en wacht op een reactie.',
      'Herhaal het gezicht als je kind lacht, of probeer een ander gezicht.',
      'Laat je kind ook "leiden" \u2013 imiteer de gezichtsuitdrukkingen van je baby.',
    ],
    reflection: 'Welke gezichtsuitdrukking van jou riep de sterkste reactie op bij je kind?',
    scienceNote: 'Protoconversaties en wederzijdse gezichtsimitatie zijn fundamenteel voor de ontwikkeling van sociale cognitie bij baby\u2019s (Trevarthen, 1979; Meltzoff & Moore, 1977).',
    durationMin: 5,
  },
  {
    id: 'gren_02_104',
    skill: 'Grenzen',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Zacht omleiden bij gevaar',
    description: 'Oefen het zacht omleiden van je peuter wanneer die iets gevaarlijks wil pakken.',
    instructions: [
      'Wacht tot je peuter naar iets toeloopt of kruipt dat niet mag (stopcontact, trap, etc.).',
      'Zeg kalm en kort: "Stop, dat is niet veilig."',
      'Leid je kind fysiek zacht om naar een veilig alternatief.',
      'Benoem het alternatief enthousiast: "Kijk, hier kun je mee spelen!"',
      'Herhaal dit consequent als de situatie zich weer voordoet.',
    ],
    reflection: 'Lukte het om kalm te blijven en niet boos of ge\u00efrriteerd te reageren bij het omleiden?',
    scienceNote: 'Positieve grenzen stellen via omleiding in plaats van straf ondersteunt de ontwikkeling van zelfregulatie bij peuters (Kochanska, 1997).',
    durationMin: 10,
  },
  {
    id: 'auto_02_105',
    skill: 'Autonomie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Zelf eten ontdekken',
    description: 'Laat je peuter zelfstandig eten ontdekken met fingerfood, zonder in te grijpen.',
    instructions: [
      'Bereid kleine stukjes zacht fruit, groente of brood voor op een bordje.',
      'Zet je peuter in de kinderstoel en plaats het bordje voor hem of haar.',
      'Laat je kind zelf pakken, voelen, proeven en knoeien zonder te corrigeren.',
      'Benoem wat je ziet: "Je pakt de banaan!" of "Je voelt hoe zacht dat is."',
      'Grijp alleen in bij verstikkingsgevaar; laat de rest gaan.',
    ],
    reflection: 'Hoe moeilijk was het om je kind te laten knoeien zonder in te grijpen? Wat zegt dat over jouw behoefte aan controle?',
    scienceNote: 'Baby-led weaning bevordert fijne motoriek, zelfregulatie bij eten en autonomie-ontwikkeling (Rapley & Murkett, 2008; Townsend & Pitchford, 2012).',
    durationMin: 15,
  },
  {
    id: 'hers_02_106',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Herstel na een geprikkeld moment',
    description: 'Herstel de verbinding met je baby nadat je zelf even ge\u00efrriteerd of overprikkeld was.',
    instructions: [
      'Denk terug aan een recent moment waarop je kortaf, gefrustreerd of afwezig was richting je kind.',
      'Neem je baby op schoot of in je armen en maak bewust oogcontact.',
      'Zeg zachtjes: "Papa was even niet lief/geduldig. Het spijt me. Ik ben er nu voor je."',
      'Geef een knuffel, aai over het hoofd, of zing een liedje dat je kind fijn vindt.',
    ],
    reflection: 'Hoe voelde het om tegen een baby sorry te zeggen, ook al begrijpt die de woorden nog niet?',
    scienceNote: 'Reparatie na een interactiebreuk (rupture-repair) is cruciaal voor veilige hechting en veerkracht; het gaat niet om perfectie maar om herstel (Tronick, 2007).',
    durationMin: 5,
  },
  {
    id: 'refl_02_107',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Dagboekmoment over je vaderschap',
    description: 'Schrijf kort op hoe je je voelt als vader van een baby of peuter.',
    instructions: [
      'Pak pen en papier of open een notitie-app na het slapengaan van je kind.',
      'Schrijf drie dingen op die je vandaag voelde als vader (positief \u00e9n negatief).',
      'Schrijf \u00e9\u00e9n moment op waarop je trots was op jezelf als vader.',
      'Schrijf \u00e9\u00e9n moment op dat je anders had willen doen.',
      'Lees het terug en wees mild voor jezelf.',
    ],
    reflection: 'Welk patroon zie je in je gevoelens als vader? Is er iets dat steeds terugkomt?',
    scienceNote: 'Reflectief functioneren (mentaliseren) bij ouders is een sterke voorspeller van veilige hechting bij het kind (Fonagy et al., 2002; Slade, 2005).',
    durationMin: 10,
  },
  {
    id: 'verb_02_108',
    skill: 'Verbinding',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen zingen',
    description: 'Zing een eenvoudig liedje voor je baby en beweeg samen op het ritme.',
    instructions: [
      'Kies een simpel kinderliedje zoals "Slaap kindje slaap" of "Twee emmertjes water halen".',
      'Zing het langzaam terwijl je je baby vasthoudt of tegenover je zet.',
      'Maak oogcontact en beweeg zachtjes op het ritme.',
      'Herhaal het liedje een paar keer en let op de reactie van je kind.',
    ],
    reflection: 'Hoe reageerde je baby op je stem en het ritme? Vond je het makkelijk of onwennig om te zingen?',
    scienceNote: 'Ouderlijk zingen verlaagt cortisol bij baby\u2019s en versterkt de emotionele band sterker dan spraak alleen (Trehub et al., 2015; Cirelli et al., 2018).',
    durationMin: 5,
  },
  {
    id: 'emco_02_109',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Spiegelen van blije momenten',
    description: 'Spiegel de vreugde van je kind door enthousiast mee te doen met positieve emoties.',
    instructions: [
      'Let op een moment waarop je kind blij is: lachen, brabbelen of enthousiast bewegen.',
      'Spiegel de emotie door zelf te glimlachen, te lachen of enthousiast te klinken.',
      'Benoem het: "Wat ben je blij! Dat is zo leuk h\u00e8!"',
      'Maak oogcontact en geniet zichtbaar mee van het moment.',
    ],
    reflection: 'Hoe voelde het om bewust mee te genieten van de vreugde van je kind? Doe je dit normaal automatisch?',
    scienceNote: 'Affectieve afstemming (attunement) op positieve emoties versterkt de hechtingsrelatie en leert kinderen dat hun emoties gezien worden (Stern, 1985).',
    durationMin: 5,
  },

  // ============================================================
  // AGE GROUP 3-5 (10 tasks: 3 basis, 4 gevorderd, 3 expert)
  // ============================================================
  {
    id: 'aanw_35_110',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Vijf minuten vloertijd',
    description: 'Speel vijf minuten mee met wat je kind zelf heeft gekozen om te doen.',
    instructions: [
      'Vraag je kind: "Waar wil je mee spelen? Ik doe mee!"',
      'Ga op de vloer zitten, op ooghoogte van je kind.',
      'Volg het spel van je kind zonder het over te nemen of te veranderen.',
      'Benoem wat je kind doet: "Jij bouwt een hoge toren!" of "De pop gaat slapen."',
    ],
    reflection: 'Was het moeilijk om het spel niet te sturen? Wat zegt dat over hoe je normaal met je kind speelt?',
    scienceNote: 'Child-led play (vloertijd) versterkt de ouder-kindrelatie en het gevoel van competentie bij het kind (Greenspan & Wieder, 2006; Landreth, 2012).',
    durationMin: 5,
  },
  {
    id: 'emco_35_111',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het emotiemonster tekenen',
    description: 'Teken samen met je kind een "emotiemonster" dat laat zien hoe het zich voelt.',
    instructions: [
      'Pak papier en kleurpotloden en ga samen aan tafel zitten.',
      'Vraag: "Als je gevoel een monster was, hoe zou dat eruitzien?"',
      'Laat je kind tekenen en stel vragen: "Welke kleur heeft het? Is het groot of klein?"',
      'Teken zelf ook een emotiemonster en deel wat jij voelt.',
      'Bespreek samen: "Wanneer komt dit monster bij jou op bezoek?"',
    ],
    reflection: 'Was je kind in staat om gevoelens uit te drukken via de tekening? Wat vertelde het monster jou?',
    scienceNote: 'Externalisering van emoties door creatieve expressie helpt kleuters om abstracte gevoelens concreet en hanteerbaar te maken (Malchiodi, 2012; Gottman, 1997).',
    durationMin: 15,
  },
  {
    id: 'zelr_35_112',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'De schildpad-techniek oefenen',
    description: 'Leer je kind de schildpadtechniek om zichzelf te kalmeren bij boosheid.',
    instructions: [
      'Vertel het verhaal van Schildpad Sjaak die boos werd en in zijn schild kroop om rustig te worden.',
      'Doe voor: trek je schouders op naar je oren (schild), adem diep in, en blaas langzaam uit.',
      'Oefen dit drie keer samen met je kind op een rustig moment.',
      'Spreek af dat jullie dit samen doen als iemand boos of gefrustreerd is.',
    ],
    reflection: 'Denk je dat je kind deze techniek zelf kan inzetten bij een volgend boos moment? Wat heb je nodig om het te herinneren?',
    scienceNote: 'De schildpadtechniek is een evidence-based zelfregulatiestrategie voor kleuters, ontwikkeld in het PATHS-curriculum (Greenberg & Kusché, 1993).',
    durationMin: 10,
  },
  {
    id: 'gren_35_113',
    skill: 'Grenzen',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'De keuze binnen de grens',
    description: 'Oefen met het geven van twee opties binnen een duidelijke grens.',
    instructions: [
      'Kies een situatie waarin je kind vaak weerstand biedt (aankleden, opruimen, tandenpoetsen).',
      'Geef twee keuzes binnen de grens: "Wil je eerst je broek of eerst je trui aan?"',
      'Accepteer de keuze van je kind zonder commentaar op welke beter is.',
      'Als je kind geen van beide wil, herhaal kalm: "Dit zijn de twee keuzes. Welke kies jij?"',
      'Benoem achteraf: "Jij hebt zelf gekozen, goed gedaan!"',
    ],
    reflection: 'Hoe reageerde je kind op het krijgen van keuzes? Verminderde het de strijd?',
    scienceNote: 'Beperkte keuzes bieden autonomie binnen structuur, wat de intrinsieke motivatie en coöperatie bij kleuters verhoogt (Deci & Ryan, 2000; Kohn, 2005).',
    durationMin: 10,
  },
  {
    id: 'auto_35_114',
    skill: 'Autonomie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Zelf schoenen aandoen',
    description: 'Geef je kind de ruimte om zelf schoenen aan te doen, ook als het lang duurt.',
    instructions: [
      'Kies een moment zonder tijdsdruk (niet vlak voor een afspraak).',
      'Zet de schoenen klaar en zeg: "Wil je proberen ze zelf aan te doen?"',
      'Wacht geduldig en grijp niet in, ook als het verkeerd om gaat.',
      'Moedig aan met: "Je probeert het echt goed!" in plaats van "Nee, andersom."',
      'Help alleen als je kind er zelf om vraagt.',
    ],
    reflection: 'Hoe voelde het om te wachten terwijl je kind worstelde? Wat leer je over je eigen geduld?',
    scienceNote: 'Het ondersteunen van autonomie bij dagelijkse taken bevordert het gevoel van competentie en eigenwaarde (Erikson\u2019s fase van autonomie vs. schaamte; Erikson, 1963).',
    durationMin: 10,
  },
  {
    id: 'hers_35_115',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Sorry zeggen en het goedmaken',
    description: 'Zeg bewust sorry na een moment waarop je te streng of ongeduldig was.',
    instructions: [
      'Denk terug aan een recent moment waarop je te hard reageerde richting je kind.',
      'Ga op ooghoogte bij je kind zitten en zeg: "Papa was net te boos/ongeduldig. Dat was niet fijn voor jou."',
      'Erken het gevoel van je kind: "Jij schrok daarvan, hè?"',
      'Vertel wat je anders had willen doen: "Ik had rustiger moeten praten."',
      'Sluit af met een knuffel of een samen-activiteit om de verbinding te herstellen.',
    ],
    reflection: 'Hoe reageerde je kind op je excuses? Merk je dat het de relatie herstelt?',
    scienceNote: 'Ouderlijke reparatie na conflicten modelleert emotionele verantwoordelijkheid en versterkt de veerkracht van de hechtingsrelatie (Siegel & Bryson, 2011; Tronick, 2007).',
    durationMin: 10,
  },
  {
    id: 'verb_35_116',
    skill: 'Verbinding',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen een boekje lezen',
    description: 'Lees een prentenboek voor en laat je kind de plaatjes vertellen.',
    instructions: [
      'Kies samen een prentenboek uit en ga knus zitten.',
      'Lees het boek langzaam voor en wijs plaatjes aan.',
      'Stel vragen: "Wat denk jij dat er nu gaat gebeuren?" of "Hoe voelt dit dier zich?"',
      'Laat je kind ook "voorlezen" door te vertellen wat het op de plaatjes ziet.',
    ],
    reflection: 'Welke vragen stelde je kind tijdens het lezen? Wat vertelde dat je over de belevingswereld van je kind?',
    scienceNote: 'Dialogisch voorlezen (vragen stellen, uitbreiden, herhalen) stimuleert taalontwikkeling en Theory of Mind bij kleuters (Whitehurst et al., 1988; Mol et al., 2008).',
    durationMin: 15,
  },
  {
    id: 'refl_35_117',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Je eigen opvoeding onder de loep',
    description: 'Reflecteer op hoe jouw eigen vader grenzen stelde en wat je daarvan wilt overnemen of veranderen.',
    instructions: [
      'Neem een rustig moment voor jezelf (na bedtijd van je kind).',
      'Denk aan drie regels of grenzen die jouw vader hanteerde toen jij klein was.',
      'Schrijf per regel op: wil ik dit overnemen, aanpassen of loslaten?',
      'Bedenk \u00e9\u00e9n concreet ding dat je morgen anders wilt doen op basis van deze reflectie.',
    ],
    reflection: 'Welke patronen uit je eigen opvoeding neem je onbewust over? Welke wil je bewust doorbreken?',
    scienceNote: 'Het Adult Attachment Interview toont aan dat reflectie op eigen hechtingservaringen de sterkste voorspeller is van veilige hechting bij de volgende generatie (Main & Goldwyn, 1998).',
    durationMin: 15,
  },
  {
    id: 'aanw_35_118',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het afscheidsritueel',
    description: 'Cre\u00eber een vast, warm afscheidsritueel voor wanneer je kind naar school of opvang gaat.',
    instructions: [
      'Bedenk samen een kort afscheidsritueel (bijv. drie keer knijpen in de hand, een speciaal gebaar, of een geheim woordje).',
      'Oefen het ritueel vandaag drie keer op speelse momenten.',
      'Leg uit: "Dit is ons speciale afscheid. Dan weet je dat papa aan je denkt."',
      'Voer het ritueel de komende week elke dag uit bij het afscheid.',
      'Evalueer na een week: vraag je kind of het ritueel helpt.',
    ],
    reflection: 'Geeft het ritueel jou als vader ook een rustiger gevoel bij het afscheid? Waarom wel of niet?',
    scienceNote: 'Voorspelbare afscheidsrituelen verminderen scheidingsangst en versterken het gevoel van veiligheid bij kleuters (Bowlby, 1969; Lieberman, 1993).',
    durationMin: 10,
  },
  {
    id: 'zelr_35_119',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Buikademhaling met knuffel',
    description: 'Oefen buikademhaling met je kind door een knuffel op de buik te leggen.',
    instructions: [
      'Laat je kind op de rug liggen en leg een knuffeldier op de buik.',
      'Zeg: "We gaan de knuffel laten schommelen. Adem diep in door je neus zodat je buik omhoog gaat."',
      'Doe mee door zelf ook te liggen met een knuffel op je buik.',
      'Adem samen vijf keer langzaam in en uit en tel hardop mee.',
    ],
    reflection: 'Lukte het je kind om bewust te ademen? Hoe was het om dit samen te doen?',
    scienceNote: 'Diafragma-ademhaling activeert het parasympathische zenuwstelsel en verlaagt stresshormonen, ook bij jonge kinderen (Porges, 2011; Kabat-Zinn, 1994).',
    durationMin: 5,
  },

  // ============================================================
  // AGE GROUP 6-9 (10 tasks: 3 basis, 4 gevorderd, 3 expert)
  // ============================================================
  {
    id: 'verb_69_120',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Roos en doorn van de dag',
    description: 'Deel samen het mooiste en het moeilijkste moment van de dag.',
    instructions: [
      'Kies een vast moment (bijv. aan tafel of voor het slapengaan).',
      'Vraag je kind: "Wat was je roos vandaag? En wat was je doorn?"',
      'Deel zelf ook je roos en doorn van de dag.',
      'Luister zonder oordeel en stel een vervolgvraag.',
    ],
    reflection: 'Leerde je iets nieuws over de dag van je kind dat je anders niet had geweten?',
    scienceNote: 'Dagelijkse emotionele gesprekken versterken de ouder-kindrelatie en ontwikkelen narratieve vaardigheden (Fivush et al., 2006; Bohanek et al., 2006).',
    durationMin: 5,
  },
  {
    id: 'emco_69_121',
    skill: 'Emotiecoaching',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het emotie-thermometer gesprek',
    description: 'Gebruik een denkbeeldige thermometer om de intensiteit van emoties te bespreken.',
    instructions: [
      'Teken samen een thermometer op papier met een schaal van 1 (kalm) tot 10 (koken van woede/verdriet).',
      'Vraag je kind: "Waar sta jij nu op de thermometer?"',
      'Bespreek wat er bij een 3 gebeurt en wat er bij een 8 gebeurt in het lichaam.',
      'Bedenk samen strategieën voor wanneer de thermometer boven de 6 komt.',
      'Hang de thermometer op een zichtbare plek in huis.',
    ],
    reflection: 'Kan je kind al onderscheid maken tussen verschillende intensiteiten van emoties? Wat heb je daarover geleerd?',
    scienceNote: 'Emotionele granulariteit \u2013 het vermogen om nuances in emoties te herkennen \u2013 is een beschermende factor voor mentale gezondheid (Barrett, 2017; Gottman, 1997).',
    durationMin: 15,
  },
  {
    id: 'refl_69_122',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'De vraag achter het gedrag',
    description: 'Reflecteer op uitdagend gedrag van je kind en zoek de onderliggende behoefte.',
    instructions: [
      'Denk aan een recent moment waarop je kind lastig gedrag vertoonde (zeuren, slaan, weigeren).',
      'Schrijf het gedrag op en stel jezelf de vraag: "Wat had mijn kind op dat moment nodig?"',
      'Bedenk minstens drie mogelijke behoeften (aandacht, veiligheid, autonomie, rust).',
      'Kies de meest waarschijnlijke behoefte en bedenk hoe je daar de volgende keer op kunt reageren.',
    ],
    reflection: 'Verandert het je kijk op het gedrag als je het ziet als een uiting van een behoefte in plaats van ongehoorzaamheid?',
    scienceNote: 'Gedrag als communicatie van onvervulde behoeften is een kernprincipe van de Circle of Security-benadering (Powell et al., 2013).',
    durationMin: 10,
  },
  {
    id: 'aanw_69_123',
    skill: 'Aanwezigheid',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Samen wandelen zonder doel',
    description: 'Maak een wandeling met je kind zonder bestemming en laat je kind de route bepalen.',
    instructions: [
      'Zeg tegen je kind: "We gaan wandelen. Jij mag kiezen: linksaf of rechtsaf?"',
      'Laat je kind bij elke kruising de richting kiezen.',
      'Loop zonder telefoon en praat over wat jullie onderweg zien en horen.',
      'Sta stil bij dingen die je kind interessant vindt, hoe klein ook.',
      'Sluit af met: "Wat was het leukste dat we tegenkwamen?"',
    ],
    reflection: 'Wat viel je op toen je geen doel of tijdsdruk had? Hoe was het om je kind te volgen?',
    scienceNote: 'Ongestructureerde buitentijd met een ouder bevordert aandacht, creativiteit en de ouder-kindrelatie (Louv, 2005; Ginsburg, 2007).',
    durationMin: 15,
  },
  {
    id: 'auto_69_124',
    skill: 'Autonomie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Zelf het ontbijt maken',
    description: 'Laat je kind zelfstandig een eenvoudig ontbijt bereiden.',
    instructions: [
      'Zeg de avond ervoor: "Morgen mag jij het ontbijt maken voor ons!"',
      'Leg de benodigde spullen op een bereikbare plek (brood, beleg, borden, messen).',
      'Laat je kind zelf keuzes maken over wat er op tafel komt.',
      'Help alleen als je kind erom vraagt en geef dan hints, geen oplossingen.',
      'Eet samen en bedank je kind oprecht voor het ontbijt.',
    ],
    reflection: 'Hoe reageerde je kind op de verantwoordelijkheid? Zag je trots of onzekerheid?',
    scienceNote: 'Huishoudelijke verantwoordelijkheden op jonge leeftijd voorspellen zelfstandigheid en welzijn op latere leeftijd (Rossmann, 2002; Vygotsky\u2019s zone van naaste ontwikkeling).',
    durationMin: 15,
  },
  {
    id: 'gren_69_125',
    skill: 'Grenzen',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen regels bedenken',
    description: 'Stel samen met je kind twee tot drie afspraken op voor schermtijd.',
    instructions: [
      'Ga samen zitten en zeg: "We gaan samen afspraken maken over schermtijd."',
      'Vraag je kind: "Wat vind jij een eerlijke afspraak?" en luister echt.',
      'Deel jouw zorgen en wensen op een respectvolle manier.',
      'Kom samen tot twee of drie afspraken en schrijf ze op.',
      'Hang de afspraken op een zichtbare plek en evalueer ze na een week.',
    ],
    reflection: 'Hoe was het om je kind mee te laten beslissen over regels? Houdt het zich beter aan zelfgemaakte regels?',
    scienceNote: 'Inductief grenzen stellen \u2013 waarbij kinderen meedenken over regels \u2013 leidt tot meer intrinsieke naleving dan autoritair opleggen (Baumrind, 1991; Grolnick, 2003).',
    durationMin: 10,
  },
  {
    id: 'hers_69_126',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'De herstelbrief',
    description: 'Schrijf samen een kort briefje na een ruzie om de verbinding te herstellen.',
    instructions: [
      'Wacht tot de emoties gezakt zijn na een conflict met je kind (minstens 30 minuten).',
      'Pak twee blaadjes papier en zeg: "Zullen we allebei een briefje schrijven over wat er gebeurde?"',
      'Schrijf op: wat je voelde, wat je anders had willen doen, en wat je fijn vindt aan jullie relatie.',
      'Wissel de briefjes uit en lees ze in stilte.',
      'Bespreek kort wat jullie allebei hebben opgeschreven en sluit af met een gebaar van verbinding.',
    ],
    reflection: 'Hoe voelde het om je gevoelens op te schrijven in plaats van uit te spreken? Was het makkelijker of moeilijker?',
    scienceNote: 'Expressief schrijven over emotionele ervaringen vermindert stress en bevordert emotionele verwerking (Pennebaker, 1997; Siegel, 2012).',
    durationMin: 15,
  },
  {
    id: 'zelr_69_127',
    skill: 'Zelfregulatie',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'De pauzeknop introduceren',
    description: 'Leer je kind een mentale "pauzeknop" te gebruiken voor het reageert op boosheid.',
    instructions: [
      'Leg uit: "In je hoofd zit een pauzeknop, net als bij een film. Als je boos wordt, kun je op pauze drukken."',
      'Oefen samen: doe alsof je boos bent, druk op een denkbeeldige knop op je hoofd, en vries als een standbeeld.',
      'Tel hardop tot vijf terwijl je bevroren staat en adem dan uit.',
      'Laat je kind dit drie keer oefenen met speelse scenario\u2019s.',
      'Spreek af: "Als ik zie dat je boos wordt, zeg ik \u2018pauzeknop\u2019 en dan proberen we het samen."',
    ],
    reflection: 'Geloof je dat je kind in een echt boos moment aan de pauzeknop kan denken? Wat kun je doen om te helpen?',
    scienceNote: 'Responsinhibitie \u2013 het vermogen om een automatische reactie te onderdrukken \u2013 is een kerncomponent van executieve functies die trainbaar is bij kinderen (Diamond, 2013).',
    durationMin: 10,
  },
  {
    id: 'verb_69_128',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Geheime handdruk bedenken',
    description: 'Bedenk samen een geheime handdruk die alleen van jullie twee\u00ebn is.',
    instructions: [
      'Zeg: "Wij gaan een geheime handdruk bedenken die alleen wij kennen!"',
      'Begin met een simpele handdruk en voeg stap voor stap grappige elementen toe (tikje, vuistje, vingerwiebel).',
      'Oefen tot jullie de handdruk allebei vlot kunnen.',
      'Gebruik de handdruk als begroeting, afscheid of tussendoor als verbindingsmoment.',
    ],
    reflection: 'Hoe reageerde je kind op het hebben van iets dat alleen van jullie is? Wat doet exclusiviteit voor de band?',
    scienceNote: 'Gedeelde rituelen en geheimen versterken het gevoel van belonging en de unieke ouder-kindband (Fiese et al., 2002).',
    durationMin: 5,
  },
  {
    id: 'emco_69_129',
    skill: 'Emotiecoaching',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Emotiedetective spelen',
    description: 'Word samen "emotiedetectives" die emoties opsporen in een film of tv-serie.',
    instructions: [
      'Kies een kort fragment (5-10 minuten) van een kindvriendelijke film of serie.',
      'Kijk samen en druk op pauze wanneer een personage een sterke emotie toont.',
      'Vraag: "Welke emotie voelt dit personage? Hoe kun je dat zien?"',
      'Bespreek: "Heb jij je ook weleens zo gevoeld? Wanneer was dat?"',
      'Ga door met kijken en herhaal dit bij twee of drie momenten.',
    ],
    reflection: 'Hoe goed kon je kind emoties herkennen bij anderen? Waren er emoties die moeilijk te benoemen waren?',
    scienceNote: 'Het herkennen van emoties bij anderen via mediamateriaal ontwikkelt empathie en emotionele geletterdheid (Denham et al., 2003; Gottman, 1997).',
    durationMin: 15,
  },

  // ============================================================
  // AGE GROUP 10-12 (10 tasks: 3 basis, 4 gevorderd, 3 expert)
  // ============================================================
  {
    id: 'aanw_1012_130',
    skill: 'Aanwezigheid',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen iets van je kind leren',
    description: 'Laat je kind jou iets uitleggen waar het goed in is of veel van weet.',
    instructions: [
      'Vraag je kind: "Wat is iets waar jij heel veel van weet? Kun je het mij uitleggen?"',
      'Luister aandachtig en stel oprechte vragen zonder te doen alsof je het al weet.',
      'Laat je kind de rol van leraar hebben en volg geduldig de uitleg.',
      'Bedank je kind en benoem specifiek wat je geleerd hebt.',
    ],
    reflection: 'Hoe voelde het om de leerling te zijn? Zag je trots bij je kind?',
    scienceNote: 'Rolwisseling waarbij het kind de expert is, versterkt zelfvertrouwen en de ervaring van competentie (Vygotsky, 1978; Bandura, 1997).',
    durationMin: 10,
  },
  {
    id: 'emco_1012_131',
    skill: 'Emotiecoaching',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Valideren zonder oplossen',
    description: 'Oefen met luisteren naar een probleem van je kind zonder meteen een oplossing te geven.',
    instructions: [
      'Wacht tot je kind iets vertelt dat het moeilijk vindt (school, vrienden, sport).',
      'Luister en zeg: "Dat klinkt echt vervelend" of "Ik snap dat je je zo voelt."',
      'Stel een open vraag: "Hoe was dat voor jou?" of "Wat deed dat met je?"',
      'Bied pas een oplossing aan als je kind erom vraagt, of vraag: "Wil je advies of wil je dat ik gewoon luister?"',
    ],
    reflection: 'Hoe moeilijk was het om niet meteen met een oplossing te komen? Wat deed het luisteren met je kind?',
    scienceNote: 'Emotionele validatie zonder probleemoplossing versterkt het gevoel gehoord te worden en is effectiever dan directe adviezen (Gottman, 1997; Linehan, 1993).',
    durationMin: 10,
  },
  {
    id: 'zelr_1012_132',
    skill: 'Zelfregulatie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Stresssignalen samen ontdekken',
    description: 'Ontdek samen welke lichamelijke signalen jullie voelen bij stress.',
    instructions: [
      'Ga samen zitten en teken elk een omtrek van een lichaam op papier.',
      'Vraag: "Waar in je lichaam voel je het als je gestrest of boos bent?"',
      'Kleur die plekken in en benoem wat er gebeurt (buikpijn, warm hoofd, strakke schouders).',
      'Doe hetzelfde voor jezelf en deel je eigen stresssignalen.',
      'Bedenk samen voor elke plek een strategie: "Als mijn buik knijpt, ga ik even naar buiten."',
    ],
    reflection: 'Kende je kind zijn eigen stresssignalen al? En kende jij die van jezelf?',
    scienceNote: 'Lichaamsbewustzijn (interoceptie) is fundamenteel voor emotieregulatie en het herkennen van eigen behoeften (Damasio, 1999; Price & Hooven, 2018).',
    durationMin: 15,
  },
  {
    id: 'gren_1012_133',
    skill: 'Grenzen',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'De familierechtbank',
    description: 'Bespreek een meningsverschil als een "rechtbank" waar beide partijen hun zaak mogen bepleiten.',
    instructions: [
      'Kies een meningsverschil dat speelt (bedtijd, huiswerk, schermtijd).',
      'Zeg: "We gaan dit bespreken als een rechtbank. Jij mag eerst je zaak bepleiten, dan ik."',
      'Laat je kind 2 minuten ononderbroken spreken en luister actief.',
      'Bepleit daarna jouw kant, ook in 2 minuten.',
      'Kom samen tot een "vonnis" dat voor beiden acceptabel is, eventueel met een proefperiode.',
    ],
    reflection: 'Hoe was het om je kind als gelijkwaardige gesprekspartner te behandelen? Kwam er een beter compromis uit?',
    scienceNote: 'Democratische gezinsprocessen waarin kinderen mogen meedenken, bevorderen morele ontwikkeling en probleemoplossend vermogen (Kohlberg, 1984; Baumrind, 1991).',
    durationMin: 15,
  },
  {
    id: 'auto_1012_134',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het weekbudget',
    description: 'Geef je kind een klein weekbudget en laat het zelf beslissen wat het ermee doet.',
    instructions: [
      'Geef je kind een klein bedrag (bijv. 5 euro) als weekbudget.',
      'Leg uit: "Dit is jouw geld voor deze week. Jij beslist wat je ermee doet: uitgeven, sparen of weggeven."',
      'Bemoei je niet met de keuze, ook als je kind het in jouw ogen verspilt.',
      'Bespreek aan het eind van de week: "Hoe voelde het om zelf te kiezen? Zou je het anders doen?"',
    ],
    reflection: 'Hoe moeilijk was het om je kind zelf te laten kiezen, ook als je het er niet mee eens was?',
    scienceNote: 'Financiële autonomie-ervaringen bevorderen besluitvaardigheid en leervermogen via natuurlijke consequenties (Shim et al., 2010; Deci & Ryan, 2000).',
    durationMin: 5,
  },
  {
    id: 'hers_1012_135',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het herstelinitiatief bij je kind leggen',
    description: 'Vraag je kind hoe het wil dat jullie een ruzie of miscommunicatie oplossen.',
    instructions: [
      'Na een conflict, wacht tot de emoties gezakt zijn (minstens een uur).',
      'Zeg: "We hadden net een vervelend moment. Hoe wil jij dat we dit oplossen?"',
      'Luister naar het voorstel van je kind zonder het af te wijzen.',
      'Deel wat jij nodig hebt en zoek samen een middenweg.',
      'Sluit af met een afspraak hoe jullie het de volgende keer eerder kunnen oplossen.',
    ],
    reflection: 'Hoe was het om het initiatief bij je kind te leggen? Kwam er een verrassende oplossing?',
    scienceNote: 'Het betrekken van kinderen bij het herstelproces versterkt hun agency en probleemoplossend vermogen (Greene, 2014; collaborative problem solving).',
    durationMin: 10,
  },
  {
    id: 'verb_1012_136',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen koken',
    description: 'Kook samen een maaltijd en verdeel de taken eerlijk.',
    instructions: [
      'Kies samen een recept dat je kind aanspreekt.',
      'Verdeel de taken: snijden, roeren, afmeten, afwassen.',
      'Werk samen in de keuken en praat over van alles en nog wat.',
      'Eet samen het resultaat op en vier wat jullie samen hebben gemaakt.',
    ],
    reflection: 'Hoe was de samenwerking? Welke momenten van verbinding voelde je tijdens het koken?',
    scienceNote: 'Gezamenlijke activiteiten met een gedeeld doel versterken de ouder-kindrelatie sterker dan passief samen zijn (Larson & Richards, 1994).',
    durationMin: 15,
  },
  {
    id: 'refl_1012_137',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Brief aan je toekomstige vader-zelf',
    description: 'Schrijf een brief aan jezelf als vader over twee jaar en beschrijf je ambities.',
    instructions: [
      'Pak pen en papier en schrijf bovenaan: "Beste toekomstige ik..."',
      'Beschrijf hoe je je nu voelt als vader en wat je goed vindt gaan.',
      'Schrijf op wat je over twee jaar anders of beter wilt doen.',
      'Sluit af met \u00e9\u00e9n concreet voornemen dat je morgen al kunt beginnen.',
      'Stop de brief in een envelop, plak hem dicht en bewaar hem.',
    ],
    reflection: 'Wat was het moeilijkste om op te schrijven? Wat zegt dat over waar je groeiruimte zit?',
    scienceNote: 'Toekomstgericht reflecteren activeert de prefrontale cortex en versterkt doelgericht gedrag (Schacter et al., 2012; Seligman, 2013).',
    durationMin: 15,
  },
  {
    id: 'aanw_1012_138',
    skill: 'Aanwezigheid',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Bijwonen en zien',
    description: 'Woon een activiteit van je kind bij en benoem achteraf specifiek wat je hebt gezien.',
    instructions: [
      'Ga naar een sporttraining, optreden of andere activiteit van je kind.',
      'Kijk aandachtig en onthoud twee of drie specifieke momenten.',
      'Zeg achteraf niet alleen "Je deed het goed" maar benoem concreet: "Ik zag dat je die bal perfect aannam."',
      'Vraag: "Hoe vond je het zelf gaan?"',
    ],
    reflection: 'Merkte je kind dat je echt hebt gekeken? Hoe reageerde het op je specifieke observaties?',
    scienceNote: 'Specifieke observaties ("Ik zag dat...") hebben meer impact op zelfvertrouwen dan generieke complimenten ("Goed gedaan") (Dweck, 2006; Henderlong & Lepper, 2002).',
    durationMin: 10,
  },
  {
    id: 'zelr_1012_139',
    skill: 'Zelfregulatie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Triggers in kaart brengen',
    description: 'Breng samen in kaart welke situaties triggers zijn voor boosheid of frustratie.',
    instructions: [
      'Teken samen een grote cirkel op papier en verdeel hem in taartpunten.',
      'Label elke punt met een situatie die boosheid of frustratie oproept (huiswerk, pesten, oneerlijkheid).',
      'Bespreek per trigger: "Wat gebeurt er dan in je hoofd en lichaam?"',
      'Bedenk per trigger \u00e9\u00e9n copingstrategie en schrijf die erbij.',
      'Doe dezelfde oefening voor jezelf en deel je eigen triggers openlijk.',
    ],
    reflection: 'Hebben jullie gedeelde triggers? Wat leer je van het feit dat je kind en jij soms op dezelfde dingen reageren?',
    scienceNote: 'Het identificeren van triggers is een kernstrategie in cognitieve gedragstherapie en vergroot het vermogen tot proactieve emotieregulatie (Beck, 1979; Siegel & Bryson, 2018).',
    durationMin: 15,
  },

  // ============================================================
  // AGE GROUP 13-16 (10 tasks: 3 basis, 4 gevorderd, 3 expert)
  // ============================================================
  {
    id: 'verb_1316_140',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Autorit-gesprek',
    description: 'Gebruik een autorit voor een laagdrempelig gesprek zonder oogcontact.',
    instructions: [
      'Plan bewust een moment dat je samen in de auto zit (boodschappen, training brengen).',
      'Begin met een open vraag: "Hoe gaat het eigenlijk echt met je?"',
      'Luister zonder oordeel en laat stiltes vallen \u2013 die zijn oké.',
      'Deel ook iets van jezelf: een herinnering aan jouw puberteit of iets waar je mee zit.',
    ],
    reflection: 'Was het makkelijker om te praten zonder oogcontact? Vertelde je tiener meer dan je verwachtte?',
    scienceNote: 'Zij-aan-zij gesprekken (zonder direct oogcontact) verlagen de drempel voor tieners om zich te openen, vooral bij jongens (Kindlon & Thompson, 1999).',
    durationMin: 15,
  },
  {
    id: 'emco_1316_141',
    skill: 'Emotiecoaching',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'De emotie achter de houding',
    description: 'Probeer de emotie te benoemen die schuilgaat achter afwijzend tienergedrag.',
    instructions: [
      'Merk een moment op waarop je tiener kortaf, chagrijnig of teruggetrokken is.',
      'Reageer niet op het gedrag maar op de mogelijke emotie: "Je lijkt gefrustreerd" of "Ik merk dat er iets is."',
      'Als je tiener afwijst, zeg dan: "Je hoeft er niet over te praten, maar ik ben er als je wilt."',
      'Geef ruimte \u2013 trek je fysiek terug maar blijf emotioneel beschikbaar.',
    ],
    reflection: 'Hoe reageerde je tiener op het benoemen van de emotie? Was afstand geven moeilijk voor je?',
    scienceNote: 'Tieners hebben een sterk ontwikkelde affectdetectie maar moeite met emotieregulatie door de nog onrijpe prefrontale cortex (Casey et al., 2008; Siegel, 2013).',
    durationMin: 5,
  },
  {
    id: 'zelr_1316_142',
    skill: 'Zelfregulatie',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'De afkoelperiode afspreken',
    description: 'Maak een afspraak over een afkoelperiode die jullie allebei mogen inroepen bij escalatie.',
    instructions: [
      'Kies een rustig moment en zeg: "Ik wil iets afspreken voor als we ruzie krijgen."',
      'Stel voor: "Als een van ons merkt dat het escaleert, mag diegene zeggen: ik neem een pauze."',
      'Spreek af: de pauze duurt minimaal 15 minuten, daarna komen jullie terug om het te bespreken.',
      'Maak duidelijk: "Een pauze is geen straf, het is zorg voor onze relatie."',
      'Oefen het een keer op een laag-conflict moment zodat het vertrouwd voelt.',
    ],
    reflection: 'Kun jij ook een pauze nemen als je merkt dat je zelf escaleert? Wat heb je daarvoor nodig?',
    scienceNote: 'Time-out als zelfregulatiestrategie (niet als straf) voorkomt escalatie en modelleert gezonde conflicthantering (Gottman & Silver, 1999; Patterson, 1982).',
    durationMin: 10,
  },
  {
    id: 'gren_1316_143',
    skill: 'Grenzen',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Onderhandelen over uitgaanstijden',
    description: 'Onderhandel samen over uitgaanstijden met wederzijds respect.',
    instructions: [
      'Begin het gesprek met: "Ik wil samen afspraken maken over uitgaanstijden waar we allebei achter staan."',
      'Vraag eerst: "Wat vind jij een redelijke tijd om thuis te zijn? En waarom?"',
      'Deel je eigen zorgen eerlijk zonder te dramatiseren.',
      'Zoek samen een compromis, eventueel met een proefperiode van twee weken.',
      'Bespreek ook: "Wat doen we als het een keer niet lukt om op tijd thuis te zijn?"',
    ],
    reflection: 'Hoe was het om te onderhandelen in plaats van regels op te leggen? Voelde je tiener zich serieus genomen?',
    scienceNote: 'Autoritatieve opvoeding \u2013 warmte combineren met duidelijke grenzen en dialoog \u2013 geeft de beste uitkomsten voor tieners (Steinberg, 2001; Baumrind, 1991).',
    durationMin: 15,
  },
  {
    id: 'auto_1316_144',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Eigen beslissing respecteren',
    description: 'Laat je tiener een beslissing nemen waar je het niet mee eens bent, zonder in te grijpen.',
    instructions: [
      'Identificeer een situatie waarin je tiener een keuze maakt die je niet zou maken (kleding, hobby, vriendengroep).',
      'Benoem \u00e9\u00e9n keer je zorg: "Ik maak me zorgen over X, omdat...".',
      'Zeg daarna: "Maar het is jouw keuze en ik respecteer die."',
      'Observeer de uitkomst zonder "ik had het je toch gezegd" te zeggen.',
      'Als de keuze goed uitpakt, benoem dat. Als het misgaat, bied steun aan zonder oordeel.',
    ],
    reflection: 'Hoe moeilijk was het om los te laten? Wat leer je over vertrouwen geven?',
    scienceNote: 'Psychologische autonomie-ondersteuning in de adolescentie voorspelt betere mentale gezondheid en een sterkere ouder-kindrelatie (Soenens et al., 2007; Ryan & Deci, 2017).',
    durationMin: 10,
  },
  {
    id: 'hers_1316_145',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het onuitgesproken gesprek',
    description: 'Breng iets ter sprake dat al langer onuitgesproken is tussen jou en je tiener.',
    instructions: [
      'Denk na over iets dat al een tijdje wringt maar niet uitgesproken is.',
      'Kies een rustig, privémoment en zeg: "Er is iets dat ik al een tijdje wil bespreken."',
      'Spreek vanuit jezelf: "Ik merk dat..." of "Ik voel me..." in plaats van "Jij doet altijd...".',
      'Luister naar de reactie van je tiener zonder in de verdediging te gaan.',
      'Sluit af met: "Ik ben blij dat we dit hebben besproken, ook als het ongemakkelijk was."',
    ],
    reflection: 'Hoe voelde het om het onuitgesproken uit te spreken? Wat leerde het je over je relatie met je tiener?',
    scienceNote: 'Het bespreken van onuitgesproken kwesties vermindert relationele spanning en vergroot intimiteit (Gottman, 2011; Johnson, 2008).',
    durationMin: 15,
  },
  {
    id: 'refl_1316_146',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Jouw puberteit versus die van je kind',
    description: 'Vergelijk je eigen puberteitservaring met die van je tiener en bespreek de verschillen.',
    instructions: [
      'Schrijf drie dingen op die jij moeilijk vond als tiener.',
      'Schrijf drie dingen op die jij denkt dat je tiener moeilijk vindt.',
      'Deel dit met je tiener en vraag: "Klopt dit? Of is er iets anders dat je lastig vindt?"',
      'Luister zonder te vergelijken wie het zwaarder had.',
    ],
    reflection: 'Zijn er opvallende overeenkomsten of verschillen? Helpt het je om je tiener beter te begrijpen?',
    scienceNote: 'Intergenerationele reflectie vergroot empathie en voorkomt dat ouders hun eigen onverwerkte ervaringen projecteren op hun kinderen (Fraiberg et al., 1975; Siegel & Hartzell, 2003).',
    durationMin: 15,
  },
  {
    id: 'aanw_1316_147',
    skill: 'Aanwezigheid',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Interesse tonen in hun wereld',
    description: 'Verdiep je oprecht in de muziek, games of social media van je tiener.',
    instructions: [
      'Vraag je tiener: "Wat luister je veel naar op het moment? Laat eens horen?"',
      'Luister zonder oordeel naar het nummer, de game of de content.',
      'Stel oprechte vragen: "Wat vind je er goed aan?" of "Waarom spreekt dit je aan?"',
      'Probeer het zelf een keer (luister het album, speel de game, bekijk de content).',
    ],
    reflection: 'Hoe reageerde je tiener op je oprechte interesse? Was het moeilijk om zonder oordeel te luisteren?',
    scienceNote: 'Oprechte interesse in de leefwereld van tieners communiceert respect en versterkt de hechtingsband in een fase waarin die onder druk staat (Allen & Manning, 2007; Steinberg, 2001).',
    durationMin: 10,
  },
  {
    id: 'verb_1316_148',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen sporten of bewegen',
    description: 'Doe samen een fysieke activiteit die je tiener leuk vindt.',
    instructions: [
      'Vraag je tiener: "Zullen we samen iets actiefs doen? Jij mag kiezen wat."',
      'Accepteer de keuze, ook als het niet jouw voorkeur is (skateboarden, dansen, voetballen).',
      'Doe voluit mee en lach om jezelf als het niet lukt.',
      'Geniet van de gedeelde ervaring zonder er een les of preek van te maken.',
    ],
    reflection: 'Hoe was het om fysiek samen bezig te zijn? Merkte je een verschil in de verbinding vergeleken met alleen praten?',
    scienceNote: 'Gezamenlijke fysieke activiteit verlaagt cortisol en verhoogt oxytocine bij beide partijen, wat de sociale band versterkt (Uvnäs-Moberg, 2003; Sothmann et al., 1996).',
    durationMin: 15,
  },
  {
    id: 'gren_1316_149',
    skill: 'Grenzen',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Je eigen grens stellen als vader',
    description: 'Communiceer een persoonlijke grens van jezelf op een respectvolle manier.',
    instructions: [
      'Identificeer iets dat je tiener doet dat jouw grens overschrijdt (respectloos praten, spullen lenen zonder vragen, beloftes breken).',
      'Kies een kalm moment en zeg: "Ik wil iets met je delen dat belangrijk voor me is."',
      'Formuleer je grens met een ik-boodschap: "Als jij X doet, voel ik me Y. Ik wil graag dat Z."',
      'Luister naar de reactie van je tiener en sta open voor dialoog.',
      'Wees consequent: handhaaf je grens de komende week zonder boos te worden.',
    ],
    reflection: 'Hoe voelde het om je eigen grens kwetsbaar te communiceren? Hoe reageerde je tiener op jouw eerlijkheid?',
    scienceNote: 'Het modelleren van gezonde grenzen en ik-boodschappen leert tieners assertiviteit en respectvolle communicatie (Gordon, 1970; Rosenberg, 2003, Geweldloze Communicatie).',
    durationMin: 10,
  },
];
