import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_16: InteractiveTask[] = [
  // Reflectie ronde 2 – leeftijd 0-2
  {
    id: 'refl_02_11',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Eén ding van vandaag',
    description: 'Denk na over één moment met je baby vandaag dat je bijblijft. Wat voelde je daarbij?',
    instructions: [
      'Pak een rustig moment als je baby slaapt.',
      'Denk terug aan één interactie – een glimlach, een huilbui, een voedsmoment.',
      'Vraag jezelf: wat voelde ik precies op dat moment?',
      'Schrijf het in één zin op of spreek het hardop uit.',
    ],
    reflection: 'Kleine alledaagse momenten bevatten veel informatie over hoe jij als vader reageert en groeit.',
    scienceNote: 'Dagelijkse zelfreflectie versterkt de responsiviteit van vaders (Pleck, 2010).',
    durationMin: 5,
  },
  {
    id: 'refl_02_12',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Mijn automatische reactie',
    description: 'Herken jouw automatische reactie op het huilen van je baby.',
    instructions: [
      'Denk terug aan de laatste keer dat je baby huilde.',
      'Wat deed jij als eerste – optillen, wachten, sussen, of iets anders?',
      'Was die reactie bewust of automatisch?',
      'Vraag je af: waar komt die automatische reactie vandaan?',
    ],
    reflection: 'Onze eerste reacties zijn vaak aangeleerd. Ze herkennen is de eerste stap naar bewuste keuzes.',
    scienceNote: 'Vroege zorgpatronen zijn sterk beïnvloed door eigen hechtingsgeschiedenis (Van IJzendoorn, 1995).',
    durationMin: 5,
  },
  {
    id: 'refl_02_13',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Wat vraagt mijn baby van mij?',
    description: 'Reflecteer op wat jouw baby nodig heeft dat jij (nog) moeilijk vindt te geven.',
    instructions: [
      'Denk aan een situatie de afgelopen week waarbij je moeite had te reageren.',
      'Wat vroeg je baby op dat moment?',
      'Wat maakte het lastig voor jou?',
      'Schrijf op wat je volgende keer anders zou willen doen.',
    ],
    reflection: 'Eerlijk kijken naar wat moeilijk is geeft je ruimte om te groeien als vader.',
    scienceNote: 'Mentaliseren – nadenken over de binnenkant van je kind – vergroot gevoeligheid (Fonagy et al., 2002).',
    durationMin: 10,
  },
  {
    id: 'refl_02_14',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Jouw gevoel als signaal',
    description: 'Gebruik jouw eigen gevoel als informatie over wat er speelt tussen jou en je baby.',
    instructions: [
      'Herinner je een moment dat je gefrustreerd, angstig of overweldigd was bij je baby.',
      'Vraag: wat zegt dit over mijn behoefte op dat moment?',
      'Hoe beïnvloedde jouw gevoel hoe je reageerde?',
      'Wat had jij zelf nodig om beter te kunnen reageren?',
    ],
    reflection: 'Vaders die hun eigen emoties herkennen, reguleren beter en reageren sensitiever.',
    scienceNote: 'Emotionele zelfkennis is een fundament van responsief ouderschap (Siegel & Hartzell, 2003).',
    durationMin: 10,
  },
  {
    id: 'refl_02_15',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Brief aan mijn jonge ik',
    description: 'Schrijf een korte brief aan jezelf als baby of peuter. Wat wou jij toen dat een vader deed?',
    instructions: [
      'Sluit je ogen en stel je voor hoe jij als klein kind was.',
      'Wat had je nodig van je vader (of vaderfiguur)?',
      'Schrijf dat op als een korte brief aan je jonge zelf.',
      'Lees het door en vraag: doe ik dit nu voor mijn eigen kind?',
    ],
    reflection: 'Verbinding met je eigen kindhood helpt je bewuster en empathischer te zijn als vader.',
    scienceNote: 'Reflectie op eigen gehechtheid voorspelt kwaliteit van ouderschap (Fonagy et al., 1991).',
    durationMin: 15,
  },
  {
    id: 'refl_02_16',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Mijn vaderschapswaarden',
    description: 'Formuleer drie kernwaarden die jij als vader wil belichamen.',
    instructions: [
      'Denk na: welke drie dingen zijn voor jou het allerbelangrijkst als vader?',
      'Schrijf ze op (bijv. veiligheid, plezier, eerlijkheid).',
      'Denk aan het gedrag van de afgelopen week – leefde je naar deze waarden?',
      'Kies één waarde en bedenk hoe je die morgen concreet kunt tonen aan je baby.',
    ],
    reflection: 'Duidelijke waarden geven richting aan je dagelijks vaderschap, ook in moeilijke momenten.',
    scienceNote: 'Waardengericht handelen vergroot welbevinden en consistentie in het ouderschap (Hayes et al., 2006).',
    durationMin: 15,
  },
  {
    id: 'refl_02_17',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Generatiepatronen doorbreken',
    description: 'Onderzoek welke patronen uit jouw eigen opvoeding je wil herhalen en welke je wil doorbreken.',
    instructions: [
      'Denk aan hoe jouw ouders reageerden als jij huilde of boos was.',
      'Wat deed dat met jou als kind?',
      'Welk patroon herhaal jij nu als vader (bewust of onbewust)?',
      'Welk patroon wil je bewust doorbreken? Schrijf een concrete stap op.',
    ],
    reflection: 'Bewustzijn van intergenerationele patronen is de sleutel tot verandering.',
    scienceNote: 'Intergenerationele overdracht van gehechtheid wordt doorbroken door "earned security" via reflectie (Siegel, 1999).',
    durationMin: 20,
  },
  {
    id: 'refl_02_18',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Dagboek van groei',
    description: 'Start een mini-dagboek van één week waarin je elke dag één moment van groei als vader noteert.',
    instructions: [
      'Koop een notitieboekje of open een notitie op je telefoon.',
      'Schrijf vandaag: datum + één moment waarop je bewust reageert als vader.',
      'Plan om dit de komende zes dagen te herhalen.',
      'Na zeven dagen: lees terug. Wat valt je op?',
    ],
    reflection: 'Schrijven over groei versterkt het zelfbewustzijn en maakt vooruitgang zichtbaar.',
    scienceNote: 'Expressief schrijven verlaagt stress en bevordert zelfinzicht (Pennebaker, 1997).',
    durationMin: 10,
  },
  {
    id: 'refl_02_19',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Drie dingen die goed gingen',
    description: 'Benoem drie dingen die je vandaag goed deed als vader van een baby of peuter.',
    instructions: [
      'Denk terug aan vandaag.',
      'Noem drie momenten of handelingen die je goed aanpakte (ook kleine dingen tellen).',
      'Sta bij elk moment even stil: wat deed je precies?',
      'Erken jezelf: "Ik was vandaag een goede vader omdat..."',
    ],
    reflection: 'Positieve zelfbevestiging bouwt zelfvertrouwen en motiveert vol te houden.',
    scienceNote: 'Erkenning van eigen krachten vergroot motivatie en veerkracht (Seligman, 2011).',
    durationMin: 5,
  },
  {
    id: 'refl_02_20',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Check-in met jezelf',
    description: 'Doe een snelle check-in: hoe voel jij je vandaag als vader?',
    instructions: [
      'Geef jezelf een score van 1-10: hoe aanwezig voelde ik me vandaag als vader?',
      'Geef jezelf een score van 1-10: hoe in balans voel ik me?',
      'Wat heeft vandaag energie gegeven? Wat heeft energie gekost?',
      'Wat heb jij morgen nodig om goed voor jezelf en je baby te zorgen?',
    ],
    reflection: 'Regelmatig inchecken bij jezelf helpt je eerder bij te sturen voordat je overvraagd raakt.',
    scienceNote: 'Zelfsturing begint bij zelfbewustzijn – een kernvaardigheid van effectief ouderschap (Baumeister & Vohs, 2004).',
    durationMin: 5,
  },

  // Reflectie ronde 2 – leeftijd 3-5
  {
    id: 'refl_35_11',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Wat vroeg mijn kind vandaag?',
    description: 'Bedenk de meest opvallende vraag die jouw peuter of kleuter vandaag stelde.',
    instructions: [
      'Herinner je de vragen die je kind vandaag stelde.',
      'Kies de meest opvallende of lastigste vraag.',
      'Hoe reageerde jij? Was je tevreden met die reactie?',
      'Wat had je anders kunnen zeggen of doen?',
    ],
    reflection: 'De vragen van peuters en kleuters zijn uitnodigingen tot verbinding en nieuwsgierigheid.',
    scienceNote: 'Responsief reageren op vragen van kinderen stimuleert taalontwikkeling en denkvermogen (Rowe, 2012).',
    durationMin: 5,
  },
  {
    id: 'refl_35_12',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Mijn geduld vandaag',
    description: 'Reflecteer op je geduld van vandaag met je peuter of kleuter.',
    instructions: [
      'Denk aan een moment waarop je geduld werd getest.',
      'Wat deed je kind dat moeilijk was voor jou?',
      'Hoe reageerde jij? Wat voelde je?',
      'Wat zou je de volgende keer anders doen of zeggen?',
    ],
    reflection: 'Geduld is een spier. Door te reflecteren op wanneer je tekortschiet, train je hem.',
    scienceNote: 'Geduld bij kleuters is gekoppeld aan hogere taalvaardigheid en minder gedragsproblemen (Raver et al., 2012).',
    durationMin: 5,
  },
  {
    id: 'refl_35_13',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Mijn toon van stem',
    description: 'Luister naar de toon van je stem in de interacties met je kind van de afgelopen dag.',
    instructions: [
      'Herinner je een gesprekje of situatie van vandaag met je kind.',
      'Welke toon had jouw stem? (warm, streng, geïrriteerd, vrolijk, neutraal?)',
      'Wat denk je dat je kind ervaarde door die toon?',
      'Hoe wil je morgen klinken als je met je kind praat?',
    ],
    reflection: 'Kinderen van 3-5 reageren meer op toon dan op woorden. Jouw stem is een krachtig instrument.',
    scienceNote: 'Prosodische warmte van de stem van ouders voorspelt emotionele veiligheid bij kleuters (Stern, 1985).',
    durationMin: 10,
  },
  {
    id: 'refl_35_14',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Wat doet fantasiespel met mij?',
    description: 'Reflecteer op hoe jij je voelt als je kind je uitnodigt mee te spelen in fantasiespel.',
    instructions: [
      'Denk aan de laatste keer dat je kind je uitnodigde om te spelen (superman zijn, thee drinken, raken huis bouwen).',
      'Wat voelde je? Genoot je of voelde je weerstand?',
      'Speelde je mee? Waarom wel of niet?',
      'Wat denk je dat fantasiespel betekent voor jouw kind?',
    ],
    reflection: 'Meedoen in fantasiespel is voor een kleuter de beste manier om zich geliefd en begrepen te voelen.',
    scienceNote: 'Vaderbetrokkenheid in spel bevordert sociale competentie en emotionele regulatie (Paquette, 2004).',
    durationMin: 10,
  },
  {
    id: 'refl_35_15',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Groeimindset als vader',
    description: 'Onderzoek of je jezelf ziet als een vader die kan groeien, of als iemand die "nu eenmaal zo is".',
    instructions: [
      'Denk aan een vaardigheid als vader die je lastig vindt (bijv. geduld, spelen, praten over gevoel).',
      'Denk je: "ik ben niet goed in dit" of "ik kan hier beter in worden"?',
      'Zoek een kleine stap die je deze week kunt zetten om te groeien in die vaardigheid.',
      'Schrijf die stap op en maak er een concrete afspraak van.',
    ],
    reflection: 'Vaders met een groeimindset groeien sneller en geven meer zelfvertrouwen door aan hun kinderen.',
    scienceNote: 'Groeimindset bij ouders hangt samen met groeimindset bij kinderen (Dweck, 2006; Bostwick et al., 2020).',
    durationMin: 10,
  },
  {
    id: 'refl_35_16',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Mijn vader, mijn spiegel',
    description: 'Vergelijk hoe jouw eigen vader omging met jou als kleuter met hoe jij nu omgaat met jouw kind.',
    instructions: [
      'Herinner je een vroege herinnering aan jouw vader (of vaderfiguur) toen je klein was.',
      'Hoe reageerde hij als jij boos, bang of blij was?',
      'Zie je overeenkomsten met jouw eigen reacties als vader?',
      'Wat wil je bewust anders doen? Schrijf dat op.',
    ],
    reflection: 'Onze vaders zijn onze eerste rolmodellen voor vaderschap – bewust of onbewust.',
    scienceNote: 'Vaders repliceren vaker het gedrag van hun eigen vader dan moeders dat van hun moeder doen (Pleck, 1997).',
    durationMin: 20,
  },
  {
    id: 'refl_35_17',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het verhaal dat ik vertel',
    description: 'Welk verhaal vertel jij over jouw vaderschap? Is het een verhaal van groei of van falen?',
    instructions: [
      'Schrijf in vijf zinnen op hoe jij je vaderschap zou omschrijven.',
      'Lees het terug: is het overwegend positief, neutraal of negatief?',
      'Welk deel van het verhaal klopt niet meer of is verouderd?',
      'Herschrijf het verhaal met een groeiperspectief.',
    ],
    reflection: 'Het verhaal dat we onszelf vertellen bepaalt ons gedrag. Een beter verhaal leidt tot beter vaderschap.',
    scienceNote: 'Narratieve zelfidentiteit beïnvloedt gedrag en motivatie op de lange termijn (McAdams, 2001).',
    durationMin: 20,
  },
  {
    id: 'refl_35_18',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Een pijnlijk moment reviseren',
    description: 'Kijk terug op een moment van de afgelopen maand dat je als vader niet trots op bent.',
    instructions: [
      'Denk aan een moment waarop je schreeuwde, afhakte of ongeduldig was.',
      'Beschrijf het moment zonder oordeel: wat gebeurde er?',
      'Wat had jij op dat moment nodig wat je niet had?',
      'Wat zou je nu anders doen als je dat moment opnieuw kon leven?',
    ],
    reflection: 'Terugkijken zonder zelfkritiek maar met nieuwsgierigheid is een teken van volwassen vaderschap.',
    scienceNote: 'Zelfcompassie bij vaders hangt samen met betere relaties met kinderen (Neff & Faso, 2015).',
    durationMin: 15,
  },
  {
    id: 'refl_35_19',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Mijn hoogtepunt van de week',
    description: 'Bespreek met je partner of een vriend wat het hoogtepunt van jouw vaderschap was deze week.',
    instructions: [
      'Denk terug aan de week: wanneer voelde je je het meest verbonden met je kind?',
      'Deel dit moment met iemand die je vertrouwt.',
      'Vraag ook: wat heeft jou geholpen om zo aanwezig te zijn?',
      'Maak een afspraak om dit vaker te doen.',
    ],
    reflection: 'Hoogtepunten delen versterkt je motivatie en helpt je begrijpen wat werkt in jouw vaderschap.',
    scienceNote: 'Sociale ondersteuning vergroot het welbevinden van vaders en de kwaliteit van vaderschap (Pleck & Masciadrelli, 2004).',
    durationMin: 10,
  },
  {
    id: 'refl_35_20',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Check-in kleuter',
    description: 'Vraag je kind van 3-5 jaar hoe het zijn dag vond – en luister echt.',
    instructions: [
      'Ga naast je kind zitten op gelijke hoogte.',
      'Vraag: "Wat was het leukste van vandaag?" en "Wat vond je moeilijk?"',
      'Luister zonder te onderbreken of op te lossen.',
      'Vertel daarna zelf ook één ding dat jij leuk vond vandaag.',
    ],
    reflection: 'Door je kind te vragen naar zijn dag modelleer je reflectie en versterk je de verbinding.',
    scienceNote: 'Gedeelde besprekingen van dagelijkse ervaringen versterken geheugen en emotioneel begrip bij kleuters (Fivush, 2011).',
    durationMin: 10,
  },

  // Reflectie ronde 2 – leeftijd 6-9
  {
    id: 'refl_69_11',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Terugblikken op een conflict',
    description: 'Denk terug aan een meningsverschil met je kind van 6-9 jaar van de afgelopen week.',
    instructions: [
      'Beschrijf kort wat er gebeurde.',
      'Hoe reageerde jij? Hoe reageerde je kind?',
      'Wat had je kind op dat moment nodig?',
      'Wat had jij nodig om beter te reageren?',
    ],
    reflection: 'Conflicten zijn leermomenten. Terugkijken helpt je patronen herkennen en doorbreken.',
    scienceNote: 'Ouders die reflecteren op conflicten lossen ze sneller op en beschadigen de relatie minder (Gottman et al., 1997).',
    durationMin: 10,
  },
  {
    id: 'refl_69_12',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Wat leert mijn kind van mij?',
    description: 'Stel jezelf de vraag: welk gedrag modelleer ik voor mijn kind van 6-9 jaar?',
    instructions: [
      'Denk aan drie dingen die je kind de afgelopen week van jou zag doen.',
      'Waren dat dingen die je trots op bent?',
      'Is er iets dat je kind van jou leert dat je liever niet wil overdragen?',
      'Wat wil jij bewust modelleren deze week?',
    ],
    reflection: 'Kinderen leren meer van wat je doet dan van wat je zegt. Jij bent het leerboek.',
    scienceNote: 'Sociaal leren via modelling is een primaire leerstrategie bij schoolkinderen (Bandura, 1977).',
    durationMin: 10,
  },
  {
    id: 'refl_69_13',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Kritische stem vs. ondersteunende stem',
    description: 'Analyseer de verhouding tussen kritiek en steun in jouw communicatie met je kind.',
    instructions: [
      'Denk aan de afgelopen dag: hoeveel keer zei je iets kritisch of corrigerends?',
      'Hoeveel keer zei je iets positiefs, aanmoedigends of liefdevols?',
      'Wat was de verhouding? (bijv. 5 kritisch / 2 positief)',
      'Bedenk drie concrete manieren om meer positieve feedback te geven.',
    ],
    reflection: 'De verhouding positief-negatief bepaalt sterk hoe je kind jou ervaart en hoe het zich ontwikkelt.',
    scienceNote: 'Gottman raadt een 5:1 positief-negatief ratio aan voor gezonde relaties (Gottman, 1994).',
    durationMin: 10,
  },
  {
    id: 'refl_69_14',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Mijn reactie op falen',
    description: 'Reflecteer op hoe jij reageert als je kind van 6-9 iets niet lukt.',
    instructions: [
      'Herinner je een moment dat je kind faalde of iets verpestte.',
      'Hoe reageerde jij? (teleurstelling tonen, oplossen, troosten, negeren?)',
      'Wat leerde je kind van jouw reactie over falen?',
      'Hoe wil je reageren als je kind de volgende keer faalt?',
    ],
    reflection: 'Hoe jij reageert op het falen van je kind bepaalt of het een groeimindset of faalangst ontwikkelt.',
    scienceNote: 'Ouders die falen normaliseren kweken veerkracht en doorzettingsvermogen (Dweck, 2006).',
    durationMin: 10,
  },
  {
    id: 'refl_69_15',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Gedeelde herinneringen maken',
    description: 'Creëer bewust een herinnering die jouw kind zal onthouden.',
    instructions: [
      'Denk: welke herinnering heeft jouw eigen vader jou gegeven die je nog steeds hebt?',
      'Bedenk één activiteit die je met je kind van 6-9 kunt doen die ze lang zullen onthouden.',
      'Plan het voor komend weekend.',
      'Na afloop: vraag je kind welke herinnering zij willen vasthouden van vandaag.',
    ],
    reflection: 'Vaders die bewust herinneringen creëren geven hun kinderen een rijker innerlijk leven mee.',
    scienceNote: 'Gedeelde positieve herinneringen met vader zijn beschermend voor de mentale gezondheid van kinderen (Cabrera et al., 2014).',
    durationMin: 15,
  },
  {
    id: 'refl_69_16',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Mijn blinde vlekken',
    description: 'Vraag iemand die jou goed kent om eerlijk terug te koppelen over jouw vaderschap.',
    instructions: [
      'Kies een persoon die jou en je kind goed kent (partner, vriend, familielid).',
      'Vraag hen: "Wat zie je mij als vader goed doen?" en "Wat zie je dat ik kan verbeteren?"',
      'Luister zonder te verdedigen.',
      'Kies één verbeterpunt en maak een concreet plan.',
    ],
    reflection: 'Blinde vlekken herkennen we zelf zelden. Anderen zien wat wij niet zien.',
    scienceNote: 'Externe feedback vergroot zelfinzicht effectiever dan zelfreflectie alleen (Eurich, 2017).',
    durationMin: 20,
  },
  {
    id: 'refl_69_17',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Tien jaar vooruit',
    description: 'Stel jezelf voor hoe jouw kind je herinnert als het 18 jaar is. Wat wil jij dat ze zeggen?',
    instructions: [
      'Sluit je ogen en stel je voor: je kind is 18. Het praat met een vriend over zijn vader.',
      'Wat hoop je dat ze zeggen?',
      'Schrijf drie dingen op die je wil dat ze over jou kunnen zeggen.',
      'Kies één van die drie: wat doe je al? Wat moet je nog versterken?',
    ],
    reflection: 'Vooruitdenken maakt bewuste keuzes in het heden makkelijker.',
    scienceNote: 'Toekomstgerichte reflectie activeert de prefrontale cortex en bevordert bewuste gedragssturing (Gilbert, 2006).',
    durationMin: 20,
  },
  {
    id: 'refl_69_18',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Reflecteren met je kind',
    description: 'Doe samen met je kind een mini-reflectie-oefening.',
    instructions: [
      'Ga samen zitten aan het einde van de dag.',
      'Vraag je kind: "Wat ging er goed vandaag?" en "Wat was moeilijk?"',
      'Deel zelf ook je antwoorden op die vragen.',
      'Sluit af met: "Wat kijk je morgen naar uit?"',
    ],
    reflection: 'Samen reflecteren modelleer je reflectievermogens én verbindt jullie.',
    scienceNote: 'Gezinnen die dagelijkse reflectie integreren rapporteren sterkere cohesie en betere kinduitkomsten (Froh et al., 2008).',
    durationMin: 15,
  },
  {
    id: 'refl_69_19',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Mijn beste vader-moment',
    description: 'Denk aan je meest trotse moment als vader van een kind in de basisschoolleeftijd.',
    instructions: [
      'Herinner je een moment waarbij je dacht: "Ja, zo wil ik als vader zijn."',
      'Beschrijf wat je deed en hoe je je voelde.',
      'Wat zorgde ervoor dat dat moment zo goed verliep?',
      'Hoe kun je vaker zulke momenten creëren?',
    ],
    reflection: 'Leren van je eigen successen is net zo krachtig als leren van je fouten.',
    scienceNote: 'Positieve zelfreflectie vergroot zelfeffectiviteit en doorzettingsvermogen (Bandura, 1997).',
    durationMin: 10,
  },
  {
    id: 'refl_69_20',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Wat heb ik vandaag geleerd van mijn kind?',
    description: 'Benoem één ding dat jij vandaag van je kind hebt geleerd.',
    instructions: [
      'Denk terug aan de interacties met je kind vandaag.',
      'Wat deed, zei of dacht je kind dat jou verraste of iets liet zien?',
      'Wat leerde jij daarvan – over je kind, over jezelf, of over het leven?',
      'Vertel je kind morgen wat je van hem/haar geleerd hebt.',
    ],
    reflection: 'Kinderen zijn onderschatte leraren. Wie met open ogen kijkt, leert elke dag.',
    scienceNote: 'Ouders die van kinderen leren rapporteren hogere voldoening in het ouderschap (Larson & Richards, 1994).',
    durationMin: 5,
  },

  // Reflectie ronde 2 – leeftijd 10-12
  {
    id: 'refl_1012_11',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Hoe bereikbaar ben ik?',
    description: 'Reflecteer op hoe bereikbaar jij bent voor je kind van 10-12 jaar.',
    instructions: [
      'Denk: hoe makkelijk is het voor mijn kind om met mij te praten over moeilijke dingen?',
      'Geef jezelf een score van 1-10 voor bereikbaarheid.',
      'Wat maakt jou bereikbaar? Wat maakt jou minder bereikbaar?',
      'Bedenk één concrete actie om bereikbaarder te zijn.',
    ],
    reflection: 'Bereikbaarheid is meer dan aanwezig zijn. Het betekent dat je kind weet dat het met jou terecht kan.',
    scienceNote: 'Vaders die als bereikbaar worden ervaren hebben kinderen met minder gedragsproblemen in de puberteit (Doyle et al., 2009).',
    durationMin: 10,
  },
  {
    id: 'refl_1012_12',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Mijn reactie op terugtrekken',
    description: 'Hoe reageer jij als je kind van 10-12 jaar zich terugtrekt of minder praat?',
    instructions: [
      'Herinner je een moment dat je kind stiller of afstandelijker was dan normaal.',
      'Wat deed jij? Liet je het gaan, probeerde je contact te maken, of werd je zelf geïrriteerd?',
      'Wat denk je dat je kind op dat moment nodig had?',
      'Hoe zou je het volgende keer aanpakken?',
    ],
    reflection: 'Terugtrekken is normaal bij preteens. Hoe jij reageert bepaalt of ze later wél terugkomen.',
    scienceNote: 'Ouders die het terugtrekken respecteren maar beschikbaar blijven bouwen de veiligste band (Allen et al., 2003).',
    durationMin: 10,
  },
  {
    id: 'refl_1012_13',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Mijn eigen puberteit herinneren',
    description: 'Denk terug aan jezelf op de leeftijd van je kind nu. Wat had jij nodig van jouw vader?',
    instructions: [
      'Herinner je hoe jij was op 10-12 jaar. Wat vond je leuk? Wat vond je moeilijk?',
      'Wat deed jouw vader goed in die periode?',
      'Wat miste je bij jouw vader?',
      'Hoe kun jij dat voor jouw kind anders doen?',
    ],
    reflection: 'Empathie voor je kind begint soms bij empathie voor je eigen jonge zelf.',
    scienceNote: 'Vaders die hun eigen adolescentie verwerkt hebben zijn effectievere opvoeders in de preteen-fase (Siegel, 2013).',
    durationMin: 15,
  },
  {
    id: 'refl_1012_14',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Mijn verwachtingen onder de loep',
    description: 'Analyseer welke verwachtingen je hebt van je kind van 10-12 jaar – zijn die realistisch?',
    instructions: [
      'Schrijf drie verwachtingen op die je nu hebt van je kind (bijv. schoolprestaties, gedrag, zelfstandigheid).',
      'Hoe realistisch zijn die verwachtingen voor deze leeftijd?',
      'Zijn die verwachtingen van jou... of van wat anderen van je kind verwachten?',
      'Pas één verwachting aan naar iets dat je kind kan bereiken.',
    ],
    reflection: 'Onrealistische verwachtingen zijn een bron van conflict. Realistische verwachtingen zijn motiverend.',
    scienceNote: 'Onrealistische ouderlijke verwachtingen correleren met lagere zelfwaarde bij kinderen (Pomerantz & Eaton, 2001).',
    durationMin: 15,
  },
  {
    id: 'refl_1012_15',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Gesprekken die ik vermijd',
    description: 'Wees eerlijk: zijn er gesprekken die jij vermijdt met je kind van 10-12?',
    instructions: [
      'Denk aan onderwerpen die je moeilijk vindt om met je kind te bespreken (seksualiteit, dood, geld, eigen fouten).',
      'Waarom vermijd je die gesprekken?',
      'Wat zou er gebeuren als je ze wél zou voeren?',
      'Kies één onderwerp en maak een plan om het deze maand aan te kaarten.',
    ],
    reflection: 'De gesprekken die we het meest vermijden zijn vaak de meest waardevolle.',
    scienceNote: 'Open communicatie over moeilijke onderwerpen beschermt preteens tegen riskant gedrag (Dishion & McMahon, 1998).',
    durationMin: 15,
  },
  {
    id: 'refl_1012_16',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Brief aan mijn kind',
    description: 'Schrijf een brief aan je kind van 10-12 jaar die je pas later deelt.',
    instructions: [
      'Schrijf een brief aan je kind over wie jij bent als vader, wat je wil voor hem/haar, en waarom je van hem/haar houdt.',
      'Wees oprecht en specifiek.',
      'Je hoeft de brief nu niet te geven – bewaar hem voor later (bijv. bij een verjaardag).',
      'Door de brief te schrijven verhelder je ook voor jezelf wat jij wil overdragen.',
    ],
    reflection: 'Een brief schrijven dwingt je tot diep nadenken over wat echt belangrijk is in jouw vaderschap.',
    scienceNote: 'Expressief schrijven over relaties vergroot de gehechtheid en het welzijn (Pennebaker & Smyth, 2016).',
    durationMin: 25,
  },
  {
    id: 'refl_1012_17',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Mijn vaderschap in een metafoor',
    description: 'Beschrijf je vaderschap aan de hand van een metafoor.',
    instructions: [
      'Kies een metafoor die jouw vaderschap beschrijft (bijv. een vuurtoren, een coach, een anker, een dak).',
      'Leg uit waarom je deze metafoor koos.',
      'Wat is het sterkste aspect van die metafoor voor jouw vaderschap?',
      'Wat ontbreekt er in de metafoor wat je nog wil toevoegen?',
    ],
    reflection: 'Metaforen helpen ons de essentie van complexe ervaringen te vatten.',
    scienceNote: 'Metaforisch denken activeert diepere cognitieve verwerking van identiteit (Lakoff & Johnson, 1980).',
    durationMin: 20,
  },
  {
    id: 'refl_1012_18',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Wat ik mijn kind meegeef',
    description: 'Reflecteer op de drie belangrijkste lessen die je bewust wil meegeven aan je kind.',
    instructions: [
      'Schrijf drie levenswijsheden op die jij je kind wil meegeven.',
      'Geef bij elke wijsheid een voorbeeld uit jouw eigen leven.',
      'Hoe modelleer je die wijsheden al – of nog niet?',
      'Bespreek één van die wijsheden vanavond met je kind.',
    ],
    reflection: 'Bewust nadenken over wat je wil overdragen maakt vaderschap intentioneler en diepgaander.',
    scienceNote: 'Intergenerationele overdracht van waarden hangt sterk samen met de kwaliteit van de vader-kindrelatie (Knafo & Schwartz, 2003).',
    durationMin: 20,
  },
  {
    id: 'refl_1012_19',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Ik ben trots op jou',
    description: 'Vertel je kind van 10-12 jaar specifiek waarom je trots op hem/haar bent.',
    instructions: [
      'Denk aan één iets specifieks dat je kind deed of liet zien de afgelopen week.',
      'Vertel je kind: "Ik ben trots op je omdat..."',
      'Wees concreet – niet "je bent zo goed" maar "jij deed X en dat liet zien dat..."',
      'Reflecteer achteraf: hoe reageerde je kind? Hoe voelde jij je?',
    ],
    reflection: 'Specifieke trots uitspreken is krachtiger dan algemene complimenten.',
    scienceNote: 'Specifieke ouderlijke erkenning verhoogt zelfeffectiviteit bij kinderen sterker dan algemene lof (Mueller & Dweck, 1998).',
    durationMin: 5,
  },
  {
    id: 'refl_1012_20',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Einde van de week ritueel',
    description: 'Sluit de week af met een check-in met je kind van 10-12 jaar.',
    instructions: [
      'Plan een vast moment aan het einde van de week (bijv. vrijdagavond).',
      'Stel drie vragen: "Wat was je hoogtepunt?", "Wat was moeilijk?", "Wat heb je nodig voor volgende week?"',
      'Beantwoord zelf ook die drie vragen.',
      'Maak er een ritueel van – elke week, hetzelfde moment.',
    ],
    reflection: 'Rituelen geven structuur en veiligheid. Een wekelijkse check-in bouwt vertrouwen op over tijd.',
    scienceNote: 'Gezinsrituelen bevorderen cohesie, veiligheid en welzijn bij kinderen (Fiese et al., 2002).',
    durationMin: 15,
  },

  // Reflectie ronde 2 – leeftijd 13-16
  {
    id: 'refl_1316_11',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Hoe gaat het echt met mij?',
    description: 'Doe een eerlijke check-in over hoe jij je voelt als vader van een tiener.',
    instructions: [
      'Schrijf op: wat zijn de drie grootste uitdagingen die jij nu ervaart als vader van een tiener?',
      'Hoeveel energie heb je om met die uitdagingen om te gaan (1-10)?',
      'Wat heb jij nodig om beter voor jezelf te zorgen?',
      'Maak één concrete afspraak met jezelf voor de komende week.',
    ],
    reflection: 'Goed voor jezelf zorgen is geen luxe – het is een vereiste voor goed vaderschap.',
    scienceNote: '"Put your own oxygen mask on first" – ouderlijk welbevinden voorspelt kwaliteit van ouderschap (Deater-Deckard, 2004).',
    durationMin: 10,
  },
  {
    id: 'refl_1316_12',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Wat denkt mijn tiener van mij?',
    description: 'Vraag je tiener hoe hij/zij jou ervaart als vader – en luister echt.',
    instructions: [
      'Vraag je tiener: "Als je één ding zou kunnen veranderen aan hoe ik als vader ben, wat zou dat zijn?"',
      'Luister zonder je te verdedigen.',
      'Dank hem/haar voor de eerlijkheid.',
      'Reflecteer daarna: klopt dit? Wat doe je ermee?',
    ],
    reflection: 'Feedback van je tiener vragen toont moed en modelt openheid voor groei.',
    scienceNote: 'Tieners wiens vaders om feedback vragen ervaren een hogere autonomie en meer verbinding (Soenens & Vansteenkiste, 2010).',
    durationMin: 15,
  },
  {
    id: 'refl_1316_13',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Mijn reactie op risicovol gedrag',
    description: 'Reflecteer op hoe jij reageert wanneer je tiener risicovol of grensverlengend gedrag vertoont.',
    instructions: [
      'Denk aan een recent moment waarbij je tiener iets deed dat jou zorgen baarde.',
      'Hoe reageerde jij? (angst, boosheid, controleren, bestraffen, praten?)',
      'Wat denk je dat je tiener met die reactie van jou leerde?',
      'Hoe wil jij reageren op risicovol gedrag van je tiener?',
    ],
    reflection: 'Jouw reactie op risico\'s bepaalt of je tiener de volgende keer eerlijk met je is.',
    scienceNote: 'Ouderlijke reacties op riskant gedrag die straf-georiënteerd zijn, verminderen eerlijk vertellen bij tieners (Kerr et al., 2010).',
    durationMin: 15,
  },
  {
    id: 'refl_1316_14',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Loslaten in de praktijk',
    description: 'Beschrijf hoe jij werkt aan het loslaten van je tiener.',
    instructions: [
      'Benoem drie gebieden waarop jij je tiener meer zelfstandigheid hebt gegeven.',
      'Benoem één gebied waarop loslaten voor jou moeilijk is.',
      'Wat zit er achter die moeite (angst, controlebehoefte, gewoonte)?',
      'Wat is een kleine stap richting meer loslaten op dat gebied?',
    ],
    reflection: 'Loslaten is de paradox van vaderschap: hoe meer je loslaat, hoe sterker de band.',
    scienceNote: 'Autonomie-ondersteuning door vaders hangt sterk samen met gezonde identiteitsontwikkeling bij tieners (Soenens et al., 2007).',
    durationMin: 15,
  },
  {
    id: 'refl_1316_15',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Mijn eigen puberteit opnieuw bekeken',
    description: 'Kijk met volwassen ogen terug op jouw eigen puberteit.',
    instructions: [
      'Herinner je hoe jij was als tiener. Wat was jouw grote strijd?',
      'Hoe was de relatie met jouw vader?',
      'Wat zou jij toen gewenst hebben dat hij anders deed?',
      'Hoe gebruik je die inzichten nu in je eigen vaderschap?',
    ],
    reflection: 'Onze onverwerkte tienerjaren kleuren hoe we reageren op de puberteit van ons eigen kind.',
    scienceNote: 'Vaders die hun eigen puberteit bewust verwerken hebben soepelere relaties met hun tieners (Siegel, 2013).',
    durationMin: 20,
  },
  {
    id: 'refl_1316_16',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Wie wordt mijn kind?',
    description: 'Reflecteer op de persoon die jouw tiener aan het worden is – los van jouw verwachtingen.',
    instructions: [
      'Beschrijf je tiener in vijf woorden – los van school of prestaties.',
      'Welke waarden zie je in hem/haar groeien?',
      'Zijn er dingen die je kind is die jij niet had verwacht?',
      'Kun jij die persoon volledig omarmen, ook de onverwachte delen?',
    ],
    reflection: 'Je kind is niet jouw verlengde. Het is een eigen mens. Die omarmen is een van de mooiste cadeaus.',
    scienceNote: 'Ouders die het individu van hun kind erkennen – los van hun eigen verwachtingen – bevorderen authentieke identiteitsontwikkeling (Kernis & Goldman, 2006).',
    durationMin: 20,
  },
  {
    id: 'refl_1316_17',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het echte gesprek',
    description: 'Plan een diepgaand gesprek met je tiener over iets wat er echt toe doet.',
    instructions: [
      'Bedenk één onderwerp dat jullie nooit of zelden bespreken maar dat belangrijk is.',
      'Nodig je tiener uit voor een wandeling of autorit (zij aan zij werkt beter dan tegenover elkaar).',
      'Begin het gesprek met: "Ik wil het eens met je hebben over..."',
      'Wees kwetsbaar en eerlijk. Geef ruimte voor hun mening.',
    ],
    reflection: 'Echte gesprekken gebeuren niet vanzelf. Ze vereisen moed en initiatief van de vader.',
    scienceNote: 'Zij-aan-zij activiteiten verlagen sociale drempel bij tieners en verhogen openheid (Tannen, 1990).',
    durationMin: 30,
  },
  {
    id: 'refl_1316_18',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Mijn nalatenschap als vader',
    description: 'Denk na over wat jij wil achterlaten als vader – wat wil je dat je tiener meeneemt?',
    instructions: [
      'Stel je voor dat je tiener later zijn/haar eigen kinderen opvoedt.',
      'Welke waarden, gewoonten of overtuigingen hoop je dat ze doorgeven vanuit jouw vaderschap?',
      'Welk deel van jouw vaderschap wil je dat ze NIET doorgeven?',
      'Schrijf een "vaderschapsmissie" van max. vijf zinnen.',
    ],
    reflection: 'Vaderschap is een keten door de generaties. Wat jij doet, klinkt door.',
    scienceNote: 'Intentioneel vaderschap met expliciete waarden hangt samen met positieve intergenerationele overdracht (Dollahite & Marks, 2009).',
    durationMin: 20,
  },
  {
    id: 'refl_1316_19',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Wat mijn tiener vandaag nodig had',
    description: 'Reflecteer aan het einde van de dag op wat jouw tiener vandaag nodig had.',
    instructions: [
      'Denk terug aan vandaag: was je tiener moe, gestrest, blij, terugtrekkend?',
      'Wat had hij/zij nodig op die momenten?',
      'Heb je dat gegeven? Zo niet, wat stond jou in de weg?',
      'Wat kun je morgen anders doen?',
    ],
    reflection: 'Dagelijks nadenken over de behoeften van je tiener maakt je een scherpere en empathischere vader.',
    scienceNote: 'Sensitieve responsiviteit bij tieners – behoeften herkennen en erop inspelen – bevordert aanpassing in de puberteit (Allen & Land, 1999).',
    durationMin: 5,
  },
  {
    id: 'refl_1316_20',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Drie dingen die ik vandaag goed deed',
    description: 'Erken drie dingen die je vandaag goed deed als vader van een tiener.',
    instructions: [
      'Schrijf drie concrete dingen op die je vandaag goed aanpakte als vader.',
      'Wees specifiek: niet "ik was geduldig" maar "ik luisterde naar zijn verhaal zonder te onderbreken".',
      'Vraag jezelf: welk effect had dit op mijn kind?',
      'Erken jezelf: "Ik deed vandaag mijn best als vader."',
    ],
    reflection: 'Zelfkennis omvat ook weten wat je goed doet. Vaders die zichzelf erkennen, gaan door.',
    scienceNote: 'Positieve zelfreflectie vergroot veerkracht en motivatie (Lyubomirsky et al., 2005).',
    durationMin: 5,
  },
];
