import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_7: InteractiveTask[] = [
  // ═══════════════════════════════════════════════════════════════
  // AUTONOMIE (50 taken: 5 leeftijdsgroepen × 10 taken)
  // ═══════════════════════════════════════════════════════════════

  // ── Autonomie · 0-2 jaar ──────────────────────────────────────
  {
    id: "auto_02_01",
    title: "Wacht voor je helpt",
    skill: "Autonomie",
    description: "Als je baby iets probeert (een speeltje pakken, optrekken), wacht dan 10 seconden voor je helpt. Observeer en laat het proberen.",
    duration: "3 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Zelfsturing begint al in het eerste levensjaar. Baby's die mogen worstelen met uitdagingen bouwen competentiegevoel op — de overtuiging dat ze dingen kunnen.",
    skillTip: "Gebruik die 10 seconden om te observeren wat je baby probeert. Zo leer jij je kind kennen.",
    vermijd: "Meteen helpen uit ongeduld of medelijden. Frustratie binnen veilige grenzen is leerzaam.",
    leerdoel: "Je leert ruimte te geven aan de eerste pogingen tot zelfstandigheid van je baby.",
    bron: "Piaget (1952) - The Origins of Intelligence in Children — sensorimotor exploration",
  },
  {
    id: "auto_02_02",
    title: "Volg het kind",
    skill: "Autonomie",
    description: "Laat je baby vandaag 15 minuten de leiding nemen tijdens het spel. Volg zijn aandacht, reageer op zijn initiatieven. Neem zelf geen initiatief.",
    duration: "15 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Child-led play versterkt de interne motivatie en het gevoel van controle bij baby's. Ouders die volgen in plaats van leiden, bouwen een veilige basis voor exploratie.",
    skillTip: "Beschrijf hardop wat je baby doet: 'Je rolt de bal.' Dat is betrokken zijn zonder het over te nemen.",
    vermijd: "Speelgoed aanreiken of het spel bijsturen. Laat de baby echt de leiding hebben.",
    leerdoel: "Je leert volgend aanwezig zijn in plaats van sturend.",
    bron: "Gerber (1979) - Resources for Infant Educarers — respectful caregiving",
  },
  {
    id: "auto_02_03",
    title: "Zelf eten proberen",
    skill: "Autonomie",
    description: "Geef je baby de kans om zelf te eten — ook als het een puinhoop wordt. Geef een stuk brood, een stukje banaan. Laat het ontdekken.",
    duration: "15 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Baby-led weaning — zelf eten leren — bevordert fijne motoriek, eigenaarschap over voeding en een gezonde relatie met eten. De puinhoop is de prijs van de ontwikkeling.",
    skillTip: "Leg een kleed onder de stoel. Accepteer de rommel van tevoren — dat geeft jou rust.",
    vermijd: "Steeds voeren als het kind morst. Dan leer je kind dat jij de controle over eten hebt.",
    leerdoel: "Je leert autonomie te stimuleren rond eten door los te laten.",
    bron: "Rapley & Murkett (2008) - Baby-Led Weaning — self-feeding & development",
  },
  {
    id: "auto_02_04",
    title: "Aankleden met eigen keuze",
    skill: "Autonomie",
    description: "Laat je peuter (18 maanden+) kiezen tussen twee setjes kleding. Houd twee opties omhoog en laat hem/haar wijzen of pakken.",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kleine keuzes vanaf jonge leeftijd bouwen de spier van autonomie op. Het gevoel van controle over kleine dingen reduceert frustratie en verhoogt medewerking.",
    skillTip: "Begrens de keuze tot twee opties — meer is overweldigend. Accepteer de keuze altijd.",
    vermijd: "De keuze terugnemen als je het er niet mee eens bent. Dan was er geen echte keuze.",
    leerdoel: "Je leert keuzevrijheid in te bouwen in dagelijkse routines.",
    bron: "Deci & Ryan (1985) - Intrinsic Motivation and Self-Determination in Human Behavior",
  },
  {
    id: "auto_02_05",
    title: "Exploratie zonder ingrijpen",
    skill: "Autonomie",
    description: "Laat je baby een nieuwe omgeving of nieuw speelgoed ontdekken zonder tussenkomst. Blijf in de buurt als veilige basis, maar grijp niet in.",
    duration: "10 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "De ouder als 'secure base' stelt het kind in staat om te exploreren. Baby's kijken regelmatig terug naar de ouder voor bevestiging — jouw aanwezigheid is genoeg.",
    skillTip: "Glimlach en knik als je baby naar je kijkt. Dat is de bevestiging die hij nodig heeft.",
    vermijd: "Schreeuwen 'pas op!' bij elke kleine uitdaging. Dat activeert de angstreactie in plaats van nieuwsgierigheid.",
    leerdoel: "Je leert je aanwezigheid te gebruiken als veilige basis zonder sturen.",
    bron: "Ainsworth et al. (1978) - Patterns of Attachment — secure base phenomenon",
  },
  {
    id: "auto_02_06",
    title: "Hulp vragen wachten",
    skill: "Autonomie",
    description: "Wacht met helpen tot je baby een signaal geeft dat hij hulp wil. Oogcontact, geluiden, uitgestoken armen. Help pas als het wordt gevraagd.",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Responsief reageren op hulpverzoeken — in plaats van preventief helpen — leert baby's dat hun communicatie effect heeft. Dat is de basis van effectief communiceren.",
    skillTip: "Observeer actief: wat zijn de signalen van jouw baby dat hij hulp wil? Leer zijn taal.",
    vermijd: "Helpen voordat het nodig is. Dan leer je je kind dat jij weet wat hij nodig heeft, niet zijzelf.",
    leerdoel: "Je leert onderscheid te maken tussen hulp bieden en autonomie ondersteunen.",
    bron: "Vygotsky (1978) - Mind in Society — zone of proximal development",
  },
  {
    id: "auto_02_07",
    title: "Peuter mee laten helpen",
    skill: "Autonomie",
    description: "Laat je peuter (16 maanden+) meehelpen met een simpele taak: sokken in de mand gooien, lepel op tafel zetten, doekje aangeven. Bedank hem serieus.",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Peuters willen van nature bijdragen. Door ze serieuze taken te geven, bevestig je hun competentie en bouw je gevoel van eigenwaarde op — lang voor ze dat woord kennen.",
    skillTip: "Zeg echt dankjewel — niet als lege lof maar als echte erkenning. Kinderen voelen het verschil.",
    vermijd: "De taak nadoen of verbeteren in het bijzijn van je kind. Dat ondermijnt het gevoel van bijdrage.",
    leerdoel: "Je leert competentie te stimuleren door je peuter echte taken te geven.",
    bron: "White (1959) - Motivation reconsidered: The concept of competence",
  },
  {
    id: "auto_02_08",
    title: "Laat het falen",
    skill: "Autonomie",
    description: "Als je baby iets probeert en het mislukt (toren omvalt, speeltje rol weg): blijf rustig en neutraal. Zeg: 'Oh, die viel om. Wil je het nog een keer proberen?'",
    duration: "3 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Hoe ouders reageren op falen bepaalt de tolerantie voor mislukking. Neutraal of nieuwsgierig reageren leert je kind dat falen normaal is en niet gevaarlijk.",
    skillTip: "Houd je gezichtsuitdrukking neutraal of licht geïnteresseerd. Je baby leest jouw reactie als sociale referentie.",
    vermijd: "Meehuilen of overdreven medelijden tonen. Dat bevestigt dat falen erg is.",
    leerdoel: "Je leert een gezonde reactie op falen te modelen voor je baby.",
    bron: "Bandura (1977) - Self-efficacy: Toward a unifying theory of behavioral change",
  },
  {
    id: "auto_02_09",
    title: "Tempo van het kind volgen",
    skill: "Autonomie",
    description: "Pas je tempo vandaag aan aan je baby of peuter — niet andersom. Als hij langzaam loopt, loop jij langzaam. Als hij stopt, stop jij.",
    duration: "15 min",
    ageGroups: ["0-2"],
    difficulty: "expert",
    points: 20,
    psychologie: "Tempo-afstemming versterkt de autonomieondersteuning en geeft het kind het signaal: jouw ritme telt. Dit is een van de subtielste maar krachtigste vormen van respect.",
    skillTip: "Gebruik dit tijdens een wandeling. Laat je peuter bepalen wanneer hij stopt om iets te bekijken.",
    vermijd: "Trekken of haasten. Dan is jouw agenda belangrijker dan zijn tempo.",
    leerdoel: "Je leert je eigen tempo los te laten en dat van je kind te volgen.",
    bron: "Stern (1985) - The Interpersonal World of the Infant — attunement & autonomy",
  },
  {
    id: "auto_02_10",
    title: "Nieuwe vaardigheid ruimte geven",
    skill: "Autonomie",
    description: "Als je baby of peuter een nieuwe vaardigheid oefent (lopen, traplopen, zelf drinken): weersta de neiging om het over te nemen. Begeleid alleen als het echt nodig is.",
    duration: "10 min",
    ageGroups: ["0-2"],
    difficulty: "expert",
    points: 20,
    psychologie: "Nieuwe vaardigheden worden geconsolideerd door herhaling. Ouders die te snel overnemen, onderbreken het oefenproces. Begeleiden ≠ overnemen.",
    skillTip: "Sta vlakbij maar raak niet aan. Je nabijheid biedt veiligheid; je handen niet ingrijpen biedt autonomie.",
    vermijd: "Ingrijpen bij de eerste mislukte poging. Meerdere pogingen zijn nodig voor leren.",
    leerdoel: "Je leert een nieuwe vaardigheid te begeleiden zonder het over te nemen.",
    bron: "Vygotsky (1978) - Scaffolding — zone of proximal development",
  },

  // ── Autonomie · 3-5 jaar ──────────────────────────────────────
  {
    id: "auto_35_01",
    title: "Wat is jouw plan?",
    skill: "Autonomie",
    description: "Als je kind een probleem heeft: vraag 'Wat is jouw plan?' in plaats van meteen een oplossing te bieden. Luister naar het antwoord.",
    duration: "3 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "'Wat is jouw plan?' activeert probleemoplossend denken en versterkt het gevoel van eigenaarschap. Het is één van de meest autonomie-bevorderende vragen die een ouder kan stellen.",
    skillTip: "Accepteer ook een onpraktisch plan. Het gaat om het denken, niet om de perfecte oplossing.",
    vermijd: "De vraag stellen en dan toch je eigen oplossing opleggen. Dan was de vraag nep.",
    leerdoel: "Je leert probleemoplossend denken te stimuleren in plaats van oplossingen te geven.",
    bron: "Faber & Mazlish (1980) - How to Talk So Kids Will Listen — problem-solving autonomy",
  },
  {
    id: "auto_35_02",
    title: "Kleding zelf kiezen",
    skill: "Autonomie",
    description: "Laat je kind vandaag volledig zelf kiezen wat het aantrekt — ook als het niet matcht. Aanvaard de keuze zonder commentaar.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kleding kiezen is voor kleuters een van de eerste autonome beslissingen. Het is veilig om fout te gaan. De les: mijn keuze telt.",
    skillTip: "Zeg 'leuke keuze' of niets. Niet: 'weet je zeker dat je dat wilt?' Want dan wankelt je acceptatie.",
    vermijd: "Commentaar geven op de keuze of het outfit wijzigen. Laat de keuze staan.",
    leerdoel: "Je leert keuzeruimte te geven en de keuze van je kind te respecteren.",
    bron: "Deci & Ryan (2000) - Self-Determination Theory — autonomy as basic psychological need",
  },
  {
    id: "auto_35_03",
    title: "Fout laten zijn",
    skill: "Autonomie",
    description: "Als je kind iets verkeerds doet (de verkeerde weg neemt, het speelgoed op de verkeerde manier gebruikt): laat het. Grijp alleen in als het gevaarlijk wordt.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Fouten zijn een leermiddel, geen probleem. Kinderen die hun fouten mogen ervaren, ontwikkelen een groei-mindset en meer veerkracht dan kinderen die worden gecorrigeerd voor ze falen.",
    skillTip: "Houd je in. Tien seconden wachten voor je iets zegt is soms genoeg om te zien dat je kind het zelf oplost.",
    vermijd: "'Zie je wel, ik had het je gezegd.' Dat breekt het vertrouwen en de moed.",
    leerdoel: "Je leert fouten te toestaan als krachtig leermiddel.",
    bron: "Dweck (2006) - Mindset — the role of failure in developing resilience",
  },
  {
    id: "auto_35_04",
    title: "Zelf problemen oplossen",
    skill: "Autonomie",
    description: "Als je kind ruzie heeft met een speelkammaraad: wacht. Observeer. Grijp pas in als het escaleert. Laat ze het eerst zelf proberen op te lossen.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Sociale probleemoplossing — leren onderhandelen, compromissen sluiten — wordt geleerd door oefening. Ouders die te snel ingrijpen, ontnemen kinderen dit cruciale oefenmoment.",
    skillTip: "Blijf in de buurt maar buiten het conflict. Je aanwezigheid is een veiligheidsnet.",
    vermijd: "Partij kiezen of een 'eerlijke' verdeling opleggen. Dat is jouw oplossing, niet die van hen.",
    leerdoel: "Je leert sociale autonomie te bevorderen door niet in te grijpen.",
    bron: "Selman (1980) - The Growth of Interpersonal Understanding — peer negotiation stages",
  },
  {
    id: "auto_35_05",
    title: "Eigen tempo bij aankleden",
    skill: "Autonomie",
    description: "Geef je kind 's ochtends extra tijd om zelf aan te kleden — ook als het langer duurt dan jij wil. Start 10 minuten eerder als dat nodig is.",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Zelfstandig aankleden is een complexe motorische en cognitieve taak voor kleuters. Haast van ouders saboteert het leerproces en verhoogt frustratie bij beiden.",
    skillTip: "Zeg: 'Ik ga vast mijn jas aantrekken. Roep maar als je klaar bent.' Dat geeft ruimte zonder druk.",
    vermijd: "Halverwege overnemen omdat het te lang duurt. Dan is de boodschap: je bent niet snel genoeg.",
    leerdoel: "Je leert autonomie te beschermen door tijd te creëren in de ochtend.",
    bron: "Montessori (1949) - The Absorbent Mind — practical life activities & independence",
  },
  {
    id: "auto_35_06",
    title: "Creatief werk niet beoordelen",
    skill: "Autonomie",
    description: "Als je kind een tekening, bouwwerk of verhaal maakt: reageer met 'vertel me erover' in plaats van 'wat mooi!' of het te beoordelen.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Externe evaluatie verschuift de motivatie van intern (ik doe dit omdat ik het leuk vind) naar extern (ik doe dit voor de goedkeuring). 'Vertel me erover' houdt de intrinsieke motivatie intact.",
    skillTip: "Stel vragen vanuit nieuwsgierigheid: 'Wat is dit?' of 'Wat deed je hier?' Dat nodigt uit tot verhalen.",
    vermijd: "'Wat mooi!' als automatische reactie. Het klinkt goed maar ondermijnt intrinsieke motivatie.",
    leerdoel: "Je leert intrinsieke motivatie te bewaken door niet te evalueren.",
    bron: "Deci et al. (1999) - A meta-analytic review of experiments examining the effects of extrinsic rewards",
  },
  {
    id: "auto_35_07",
    title: "Keuze in de dag",
    skill: "Autonomie",
    description: "Geef je kind vandaag drie echte keuzes: wat eet je bij het ontbijt (uit twee opties), wat doe je eerst na school, welk boekje voor het slapengaan.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Meerdere keuzemomenten per dag bouwen het gevoel van controle op. Kinderen met meer keuzes zijn minder oppositioneel en meer coöperatief bij momenten waar geen keuze is.",
    skillTip: "Beperk elke keuze tot twee opties. Meer opties leiden tot keuzestress en onbesluitvaardigheid.",
    vermijd: "Open vragen als 'wat wil je eten?' zonder begrenzing. Dat is te veel vrijheid voor een kleuter.",
    leerdoel: "Je leert autonomie in te bouwen in de structuur van de dag.",
    bron: "Iyengar & Lepper (2000) - When choice is demotivating — optimal choice structure",
  },
  {
    id: "auto_35_08",
    title: "Vraag in plaats van zeg",
    skill: "Autonomie",
    description: "Vervang vandaag vijf instructies door vragen: niet 'pak je jas' maar 'wat heb je nodig als het buiten koud is?' Laat je kind de conclusie trekken.",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Vragen activeren het kind als denker in plaats van als volger. Het leert zelfstandig conclusies te trekken — een fundamentele autonomievaardigheid.",
    skillTip: "Wees geduldig na de vraag. Kleuters hebben soms 10-15 seconden nodig voor ze antwoorden.",
    vermijd: "Zelf het antwoord geven als je kind te lang nadenkt. Dat ontkracht de vraag.",
    leerdoel: "Je leert instructies om te zetten in vragen die zelfstandig denken activeren.",
    bron: "Vygotsky (1978) - Scaffolding — guided participation",
  },
  {
    id: "auto_35_09",
    title: "Eigen oplossing uitproberen",
    skill: "Autonomie",
    description: "Als je kind een creatieve maar 'foute' oplossing bedenkt: laat het proberen. Kijk wat er gebeurt. Bespreek daarna samen wat er goed ging en wat niet.",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "expert",
    points: 20,
    psychologie: "Experimenteel denken — een idee proberen en evalueren — is een kernvaardigheid van autonoom functioneren. Het opbouwen van dit patroon begint met toestemming krijgen om te proberen.",
    skillTip: "Zeg van tevoren: 'Laten we jouw plan proberen.' Dan ben je erin mee, niet ertegen.",
    vermijd: "Zeggen 'dat gaat niet werken' voor het geprobeerd is. Dat is een remmer op initiatief.",
    leerdoel: "Je leert experimenteel denken te ondersteunen door je kind te laten proberen.",
    bron: "Piaget (1952) - Origins of Intelligence — assimilation, accommodation & experimentation",
  },
  {
    id: "auto_35_10",
    title: "Taken volledig delegeren",
    skill: "Autonomie",
    description: "Geef je kind een huishoudelijke taak die helemaal van hem is: de lage planten water geven, de was in de mand doen, de hond eten geven. Elke dag, zonder toezicht.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "expert",
    points: 20,
    psychologie: "Eigenaarschap over een taak bouwt verantwoordelijkheidsgevoel en competentie. Kinderen die echte taken hebben, voelen zich bijdragen aan het gezin — dat is een krachtige motivator.",
    skillTip: "Maak de taak visueel: een foto van de plant, een symbool op de kalender. Dat helpt de herinnering.",
    vermijd: "De taak overnemen als het kind het vergeet. Herinner liever: 'Wat was jouw taak vandaag?'",
    leerdoel: "Je leert eigenaarschap te geven door een echte, consequente verantwoordelijkheid te delegeren.",
    bron: "Montessori (1949) - The Absorbent Mind — real tasks build real competence",
  },

  // ── Autonomie · 6-9 jaar ──────────────────────────────────────
  {
    id: "auto_69_01",
    title: "Huiswerk zelf laten doen",
    skill: "Autonomie",
    description: "Laat je kind het huiswerk vandaag zonder hulp starten. Zeg: 'Begin maar, en als je vastloopt kom je naar mij.' Wacht tot het om hulp vraagt.",
    duration: "15 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Huiswerk is de oefenplek voor zelfregulatie en autonomie. Ouders die te snel helpen, ontnemen hun kind de kans om frustatietolerantie en doorzettingsvermogen op te bouwen.",
    skillTip: "Wees in de buurt maar niet naast je kind. Aanwezig maar niet ingrijpend.",
    vermijd: "Naast je kind zitten en meekijken. Dat verhoogt de druk en verlaagt de autonomie.",
    leerdoel: "Je leert vertrouwen te stellen in het zelfstandig werken van je kind.",
    bron: "Pomerantz et al. (2007) - The how, whom, and why of parents' involvement in children's academic lives",
  },
  {
    id: "auto_69_02",
    title: "Laat fout staan",
    skill: "Autonomie",
    description: "Als je kind huiswerk afgeeft met een fout die jij ziet: laat het staan. Zeg niets. Laat het kind van de leraar horen wat er mis was.",
    duration: "2 min",
    ageGroups: ["6-9"],
    difficulty: "expert",
    points: 20,
    psychologie: "De feedback van de leraar is een authentieke consequentie die krachtiger leert dan ouderlijke correctie. Ouders die fouten wegpoetsen, leren hun kind afhankelijkheid aan.",
    skillTip: "Als het moeilijk is om de fout te laten staan, vraag jezelf: 'Wie moet er hier leren?' Het kind, niet ik.",
    vermijd: "De fout eruit halen terwijl je kind even weg is. Eerlijkheid en vertrouwen zijn de basis.",
    leerdoel: "Je leert consequenties van fouten te laten werken zonder in te grijpen.",
    bron: "Dweck (2006) - Mindset — embracing mistakes as information",
  },
  {
    id: "auto_69_03",
    title: "Weekend zelf laten plannen",
    skill: "Autonomie",
    description: "Geef je kind vrijdagavond een vrij dagdeel in het weekend om zelf in te vullen. Geen suggesties, geen structuur. Observeer wat hij/zij kiest.",
    duration: "10 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Ongestructureerde tijd is cruciaal voor de ontwikkeling van zelfregulatie, creativiteit en intrinsieke motivatie. Kinderen die altijd gevuld worden, leren niet zelf te vullen.",
    skillTip: "Zeg: 'Dit dagdeel is van jou. Doe wat jij wil.' En ga dan weg. Niet kijken, niet sturen.",
    vermijd: "Na 20 minuten zeggen 'maar je kunt ook...' omdat je ziet dat je kind 'niks doet'. Niks doen is ook een keuze.",
    leerdoel: "Je leert ongestructureerde tijd te geven als ruimte voor autonome ontwikkeling.",
    bron: "Gray (2013) - Free to Learn — the value of unstructured play",
  },
  {
    id: "auto_69_04",
    title: "Beslissingen overdragen",
    skill: "Autonomie",
    description: "Kies één beslissing die jij normaal neemt voor je kind en draag die vandaag over: wat voor cadeau ze geven aan een vriendje, hoe ze hun kamer inrichten, wat voor sport ze willen.",
    duration: "10 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Autonomie-overdracht bij echte beslissingen versterkt het besluitvormingsvermogen en eigenaarschap. Kleine échte beslissingen zijn waardevoller dan grote nepdecisions.",
    skillTip: "Kies een beslissing met lage risico's maar hoge relevantie voor je kind. Dat maakt het betekenisvol.",
    vermijd: "De beslissing later toch terugdraaien. Als je overdraagt, draag je ook de uitkomst over.",
    leerdoel: "Je leert echte beslissingskracht over te dragen aan je kind.",
    bron: "Grolnick & Ryan (1989) - Parent styles associated with children's self-regulation",
  },
  {
    id: "auto_69_05",
    title: "Laat je kind uitleggen",
    skill: "Autonomie",
    description: "Vraag je kind iets uit te leggen dat jij al weet: een spelregel, hoe een app werkt, wat er in een boek stond. Luister serieus en stel vragen.",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "De protégé-effect: iemand iets uitleggen verdiept het eigen begrip en vergroot het gevoel van competentie. Door je kind de expert te laten zijn, draai je de hiërarchie gezond om.",
    skillTip: "Stel vragen alsof je het echt niet weet, ook als je het wel weet. Je oprechte nieuwsgierigheid is het cadeau.",
    vermijd: "Het gesprek overnemen of verbeteren. Laat je kind de expert zijn.",
    leerdoel: "Je leert je kind in de expert-rol te plaatsen als autonomie-bevorderaar.",
    bron: "Nestojko et al. (2014) - Expecting to teach enhances learning — the protégé effect",
  },
  {
    id: "auto_69_06",
    title: "Fout erkennen en doorgaan",
    skill: "Autonomie",
    description: "Als je kind een fout maakt en het wil opgeven: zeg alleen 'fouten horen erbij. Wat probeer je nu?' Laat het kind de volgende stap bepalen.",
    duration: "3 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Veerkracht na falen is een aangeleerde vaardigheid. De vraag 'wat probeer je nu?' houdt de regie bij het kind en activeert probleemoplossend denken in plaats van opgeven.",
    skillTip: "Normaliseer de fout: 'Ik maak ook fouten. Dat is hoe we leren.' Zeg het simpel en ga snel verder.",
    vermijd: "De fout analyseren of oplossen. Je kind heeft geen analyse nodig, het heeft een volgende stap nodig.",
    leerdoel: "Je leert veerkracht na falen te ondersteunen door de volgende stap terug te geven.",
    bron: "Seligman (1991) - Learned Optimism — explanatory style & resilience",
  },
  {
    id: "auto_69_07",
    title: "Avontuur alleen",
    skill: "Autonomie",
    description: "Laat je kind een kleine zelfstandige activiteit doen die het nog nooit alleen heeft gedaan: naar de supermarkt, naar een vriendje fietsen, alleen naar de bibliotheek.",
    duration: "30 min",
    ageGroups: ["6-9"],
    difficulty: "expert",
    points: 20,
    psychologie: "Zelfstandige uitstapjes bouwen competentiegevoel en ruimtelijk bewustzijn op. Overbeschermende ouders beperken dit cruciale leerproces.",
    skillTip: "Bespreek van tevoren wat het moet doen als er iets misgaat. Dan is het avontuur veilig én autonoom.",
    vermijd: "Stiekem meelopen of vlak achter rijden. Vertrouwen geven is het doel.",
    leerdoel: "Je leert loslaten door je kind een echt zelfstandig avontuur te geven.",
    bron: "Skenazy (2009) - Free-Range Kids — risk, independence & healthy development",
  },
  {
    id: "auto_69_08",
    title: "Geen antwoord geven",
    skill: "Autonomie",
    description: "Als je kind een vraag stelt die het zelf kan beantwoorden: zeg 'Wat denk jij?' en wacht. Geef je eigen antwoord pas als het kind echt vastzit.",
    duration: "3 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Ouders die te snel antwoorden, leren kinderen hulpeloos te zijn. 'Wat denk jij?' activeert het eigen denkproces en bouwt zelfvertrouwen in het eigen oordeel.",
    skillTip: "Houd de stilte vol. Kinderen vullen stilte als ouders lang genoeg wachten.",
    vermijd: "Je antwoord toch geven als het kind even nadenkt. Verwar nadenken niet met niet-weten.",
    leerdoel: "Je leert antwoorden terug te geven als autonomie-bevorderende strategie.",
    bron: "Faber & Mazlish (1980) - How to Talk So Kids Will Listen — encouraging autonomy",
  },
  {
    id: "auto_69_09",
    title: "Plan B laten bedenken",
    skill: "Autonomie",
    description: "Als het plan van je kind mislukt: zeg 'Wat is je plan B?' Wacht. Laat het kind een alternatief bedenken zonder jouw suggesties.",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Plannen B bedenken is een executieve functie die aangeleerd wordt door oefening. Kinderen die dit regelmatig oefenen, zijn flexibeler en veerkrachtiger.",
    skillTip: "Wees oprecht nieuwsgierig naar plan B, ook als het niet het beste plan is.",
    vermijd: "Meteen je eigen plan B aandragen. Dan is de vraag een schijnvraag.",
    leerdoel: "Je leert je kind flexibel denken te oefenen via plan B-denken.",
    bron: "Diamond (2013) - Executive Functions — flexibility & planning",
  },
  {
    id: "auto_69_10",
    title: "Bewust complimenteren op proces",
    skill: "Autonomie",
    description: "Vervang een resultaatcompliment door een procescompliment: niet 'wat goed dat je gewonnen hebt' maar 'ik zag hoe hard je je best deed. Dat was indrukwekkend.'",
    duration: "2 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Process praise versterkt de groeimindset en het geloof in eigen inspanning. Resultaatpraise koppelt eigenwaarde aan succes — wat prestatie-angst voedt.",
    skillTip: "Beschrijf concreet wat je zag: 'Ik zag dat je drie keer opnieuw begon toen het niet lukte.' Specifiek is krachtiger.",
    vermijd: "Lege complimenten: 'Geweldig!' zonder verdere inhoud. Dat voelt voor kinderen hol.",
    leerdoel: "Je leert je complimenten te richten op inspanning en proces in plaats van resultaat.",
    bron: "Dweck (2006) - Mindset — process vs. outcome praise",
  },

  // ── Autonomie · 10-12 jaar ────────────────────────────────────
  {
    id: "auto_1012_01",
    title: "Eigen agenda beheren",
    skill: "Autonomie",
    description: "Stop met het bijhouden van de agenda van je kind. Geef hem/haar een agenda en zeg: 'Dit is jouw verantwoordelijkheid nu.' Intervenieer alleen bij grote problemen.",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Agendabeheer is een executieve functie. Kinderen van 10-12 zijn klaar om dit te oefenen. Ouders die het blijven doen, bouwen afhankelijkheid in.",
    skillTip: "Geef een echte agenda — papier of digitaal. Bespreek één keer hoe het werkt. Daarna is het aan hen.",
    vermijd: "Elke avond vragen of alles is ingevuld. Dat is nog steeds jouw verantwoordelijkheid, niet die van hen.",
    leerdoel: "Je leert organisatie en planning over te dragen aan je kind.",
    bron: "Diamond (2013) - Executive Functions — planning & organization in middle childhood",
  },
  {
    id: "auto_1012_02",
    title: "Laat falen en leer ervan",
    skill: "Autonomie",
    description: "Als je kind iets vergeet (schoolwerk, gymspullen): niet redden. Laat de consequentie voelen en vraag daarna: 'Wat ga je volgende keer anders doen?'",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Falen met bijbehorende consequentie is een krachtige leermoment. Ouders die redden, nemen het leermoment weg. De reflectievraag daarna maakt het leerbaar.",
    skillTip: "Houd de vraag neutraal: 'Wat ga je volgende keer anders doen?' — niet 'hoe kan je zoiets vergeten?'",
    vermijd: "Bestraffen bovenop de consequentie. De consequentie is al de straf.",
    leerdoel: "Je leert loslaten en reflectie te stimuleren na falen.",
    bron: "Nelsen (1996) - Positive Discipline — natural consequences & learning",
  },
  {
    id: "auto_1012_03",
    title: "Eigen keuze in vriendschappen",
    skill: "Autonomie",
    description: "Laat je kind zelf bepalen wie zijn/haar vrienden zijn, ook als jij de keuze anders zou maken. Bespreek wel, maar respecteer de keuze.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Autonomie in vriendschappen is essentieel voor de ontwikkeling van een eigen identiteit. Ouders die teveel sturen, creëren afhankelijkheid of rebellie.",
    skillTip: "Blijf nieuwsgierig: 'Vertel me over die vriend. Wat vind je leuk aan hem/haar?' Dat houdt de deur open.",
    vermijd: "Vriendschappen verbieden of bekritiseren. Dat drijft je kind juist meer naar die vriend.",
    leerdoel: "Je leert autonomie te respecteren in vriendschapskeuzes.",
    bron: "Harris (1995) - Where is the child's environment? — peer group influence",
  },
  {
    id: "auto_1012_04",
    title: "Budget zelf beheren",
    skill: "Autonomie",
    description: "Geef je kind een wekelijks of maandelijks budget en laat hem/haar zelf beslissen hoe het wordt besteed. Geen commentaar, ook niet als het op is.",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Budgetbeheer leert uitgesteld genot, planning en prioritering — kernvaardigheden van autonomie. Fouten met geld op jonge leeftijd zijn veilig en leerzaam.",
    skillTip: "Start klein. Zakgeld van €5-10 per week is genoeg om te leren zonder grote gevolgen.",
    vermijd: "Bijspringen als het op is. Dan heeft budgetbeheer geen echte consequentie.",
    leerdoel: "Je leert financiële autonomie te introduceren als leeromgeving.",
    bron: "Whitebread & Bingham (2013) - Habit formation and learning in young children — financial literacy",
  },
  {
    id: "auto_1012_05",
    title: "Beslissen over eigen lichaam",
    skill: "Autonomie",
    description: "Respecteer de grenzen van je kind rondom aanraking, knuffels en lichamelijk contact. Vraag eerst: 'Mag ik je knuffelen?' en accepteer het antwoord.",
    duration: "2 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Lichaamsautonomie is een fundamenteel recht. Kinderen die leren dat hun lichaam van henzelf is, zijn beter in staat om grenzen te stellen en te herkennen.",
    skillTip: "Zeg het ook hardop: 'Jouw lichaam is van jou. Je hoeft niemand een knuffel te geven als je dat niet wilt — ook oma niet.'",
    vermijd: "Kinderen dwingen tot fysiek contact ('geef oma een kus') als ze dat niet willen.",
    leerdoel: "Je leert lichaamsautonomie te modelen en te respecteren.",
    bron: "Olweus (1993) - Bullying at School — body autonomy & personal boundaries",
  },
  {
    id: "auto_1012_06",
    title: "Eigen mening serieus nemen",
    skill: "Autonomie",
    description: "Vraag je kind zijn/haar mening over een gezinsbeslissing — bijv. de vakantiebestemming, een nieuw meubel, een familieafspraak. Weeg die mening echt mee.",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen van 10-12 zijn klaar om echt mee te denken. Serieus genomen worden in gezinsbeslissingen verhoogt het gevoel van eigenwaarde en verantwoordelijkheidsgevoel.",
    skillTip: "Leg uit waarom je hun mening vroeg en wat er mee is gedaan — ook als je er niet voor kiest.",
    vermijd: "Om de mening vragen maar hem dan negeren. Dat is erger dan helemaal niet vragen.",
    leerdoel: "Je leert de mening van je kind serieus te wegen in gezinsbeslissingen.",
    bron: "Aldgate et al. (2006) - The Developing World of the Child — participation rights",
  },
  {
    id: "auto_1012_07",
    title: "Hobby zelf kiezen",
    skill: "Autonomie",
    description: "Laat je kind een hobby of activiteit stoppen als hij/zij er klaar mee is — ook als jij er anders over denkt. Bespreek het, maar respecteer de keuze.",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Autonomie in vrijetijdsbesteding is sterk gekoppeld aan intrinsieke motivatie en welzijn. Kinderen die worden gedwongen door te gaan, ontwikkelen weerstand tegen de activiteit én tegen jou.",
    skillTip: "Bespreek: 'Wat wil je in de plaats? Of wil je even pauze?' Dat toont respect voor hun tempo.",
    vermijd: "Zeggen 'je hebt al betaald, dus je gaat door.' Geld is geen argument voor autonomieverlies.",
    leerdoel: "Je leert de keuze van je kind te respecteren in vrijetijdsbesteding.",
    bron: "Deci & Ryan (2000) - Self-Determination Theory — intrinsic motivation & well-being",
  },
  {
    id: "auto_1012_08",
    title: "Zelfstandig reizen",
    skill: "Autonomie",
    description: "Laat je kind voor het eerst zelfstandig met de bus of fiets ergens naartoe gaan. Plan het samen, bespreek de route, en laat hem/haar dan echt alleen gaan.",
    duration: "30 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Zelfstandig verplaatsen vergroot het gevoel van competentie en onafhankelijkheid enorm. Het is een concrete, voelbare ervaring van 'ik kan dit zelf'.",
    skillTip: "Spreek een contactmoment af: 'Laat weten als je er bent.' Dat is veiligheid zonder controle.",
    vermijd: "Stiekem meegaan of volgen. Vertrouwen is het geschenk dat je geeft.",
    leerdoel: "Je leert loslaten in een concrete, betekenisvolle situatie.",
    bron: "Gray (2013) - Free to Learn — independent mobility & competence",
  },
  {
    id: "auto_1012_09",
    title: "Eigen slaaptijden bepalen",
    skill: "Autonomie",
    description: "Geef je kind inspraak in zijn eigen slaaptijd: 'Wanneer denk jij dat je genoeg slaap krijgt?' Maak samen een experiment voor twee weken.",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Autonomie over slaap vergroot de intrinsieke motivatie om op tijd naar bed te gaan. Kinderen die meedenken over de reden, slapen vaak beter dan kinderen met opgedrongen bedtijden.",
    skillTip: "Maak het een experiment: 'Twee weken jouw bedtijd. Dan evalueren we hoe je je voelde.'",
    vermijd: "Te snel evalueren als het fout gaat. Twee weken is minimum voor een eerlijk experiment.",
    leerdoel: "Je leert autonomie te geven over een basisbehoefte als leermiddel.",
    bron: "Carskadon et al. (1998) - Adolescent sleep patterns — sleep need & autonomy",
  },
  {
    id: "auto_1012_10",
    title: "Verantwoordelijkheid voor een relatie",
    skill: "Autonomie",
    description: "Laat je kind zelf een conflict met een vriend of familielid oplossen. Bied aan om te helpen maar wacht op de vraag. Laat de relatieverantwoordelijkheid bij hem/haar.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Relationele autonomie — het vermogen om relaties zelf te navigeren — is een cruciale vaardigheid voor de adolescentie. Ouders die conflicten overnemen, vertragen deze ontwikkeling.",
    skillTip: "Vraag: 'Hoe wil jij dit aanpakken?' en wacht op het antwoord. Dan pas bied je hulp aan.",
    vermijd: "Meteen bellen met de ouders van het andere kind. Dat neemt de verantwoordelijkheid volledig over.",
    leerdoel: "Je leert relationele verantwoordelijkheid te laten bij je kind.",
    bron: "Selman (1980) - The Growth of Interpersonal Understanding — autonomy in relationships",
  },

  // ── Autonomie · 13-16 jaar ────────────────────────────────────
  {
    id: "auto_1316_01",
    title: "Mening vragen zonder te sturen",
    skill: "Autonomie",
    description: "Vraag je tiener zijn/haar mening over een maatschappelijk onderwerp — politiek, klimaat, nieuws. Luister. Reageer niet met jouw mening tenzij gevraagd.",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Identiteitsvorming bij tieners vereist het ontwikkelen van een eigen perspectief. Ouders die hun mening opleggen, remmen dit proces. Luisteren zonder oordeel ondersteunt het.",
    skillTip: "Zeg expliciet: 'Ik ben benieuwd naar jouw mening, niet om te debatteren maar om te begrijpen.'",
    vermijd: "Meteen tegenargumenten geven. Dan voelt je tiener dat zijn mening niet telt.",
    leerdoel: "Je leert identiteitsvorming te ondersteunen door meningen te vragen zonder te sturen.",
    bron: "Erikson (1968) - Identity: Youth and Crisis — identity formation in adolescence",
  },
  {
    id: "auto_1316_02",
    title: "Vertrouwen geven na fout",
    skill: "Autonomie",
    description: "Als je tiener een fout heeft gemaakt: herstel het vertrouwen actief. Zeg: 'Je hebt een fout gemaakt en ik vertrouw je nog steeds. Hier zijn de nieuwe afspraken.'",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Vertrouwen behouden na falen is een van de krachtigste signalen die een ouder kan geven. Het leert tieners dat fouten geen reden zijn voor totaalverlies van autonomie.",
    skillTip: "Maak het concreet: 'Ik vertrouw je met X omdat je Y hebt laten zien.' Specificiteit maakt vertrouwen geloofwaardig.",
    vermijd: "Vertrouwen volledig intrekken na één fout. Dat traint angst, niet verantwoordelijkheid.",
    leerdoel: "Je leert vertrouwen actief te herstel na een misstap.",
    bron: "Baumeister et al. (1994) - Losing control — how and why people fail at self-regulation",
  },
  {
    id: "auto_1316_03",
    title: "Keuzes zonder oordeel",
    skill: "Autonomie",
    description: "Als je tiener een keuze maakt waar jij het niet mee eens bent (muziek, kleding, vriendenkring): reageer neutraal. Vraag: 'Waarom kies je dat?' en luister echt.",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Tieners experimenteren met identiteit via keuzes. Oordeel van ouders drijft hen weg; nieuwsgierigheid houdt de verbinding intact en de deur open.",
    skillTip: "Na het luisteren: 'Interessant. Dank je dat je het me vertelt.' Niet meer dan dat.",
    vermijd: "'Begrijp je wel wat je aan het doen bent?' — dat is vermomd oordeel.",
    leerdoel: "Je leert nieuwsgierigheid als antwoord op keuzes waarmee je het niet eens bent.",
    bron: "Marcia (1966) - Development and validation of ego-identity status — identity exploration",
  },
  {
    id: "auto_1316_04",
    title: "Toekomst laten dromen",
    skill: "Autonomie",
    description: "Vraag je tiener: 'Als je over 10 jaar terugkijkt, wat hoop je dan gedaan te hebben?' Luister zonder te beoordelen of bij te sturen.",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Future orientation — nadenken over de eigen toekomst — is een sterke beschermende factor bij tieners. Het activeert eigenaarschap over het eigen leven.",
    skillTip: "Stel vervolgvragen vanuit nieuwsgierigheid: 'Wat zou je eerste stap zijn?' Niet: 'Heb je wel nagedacht over...?'",
    vermijd: "Jouw eigen toekomstdromen voor je kind projecteren op het gesprek.",
    leerdoel: "Je leert toekomstdenken te activeren zonder te sturen.",
    bron: "Nurmi (1991) - How do adolescents see their future? — future orientation & development",
  },
  {
    id: "auto_1316_05",
    title: "Laat de fout voelen",
    skill: "Autonomie",
    description: "Als je tiener iets vergeet, te laat is, of een afspraak niet nakomt: laat de consequentie voor zichzelf voelen. Ga niet redden. Vraag daarna: 'Wat leer je hiervan?'",
    duration: "3 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Tieners die beschermd worden van de gevolgen van hun fouten, missen cruciale leerervaring. De consequentie is de beste leraar — als de ouder niet reddend optreedt.",
    skillTip: "Hou 'Wat leer je hiervan?' vrij van toon. Het is een echte vraag, geen verwijt.",
    vermijd: "Zeggen 'zie je wel.' Dat frustreert en leert niets.",
    leerdoel: "Je leert tieners van hun eigen fouten te laten leren zonder te redden.",
    bron: "Nelsen (1996) - Positive Discipline for Teenagers — natural consequences",
  },
  {
    id: "auto_1316_06",
    title: "Grenzen van tiener respecteren",
    skill: "Autonomie",
    description: "Als je tiener aangeeft ergens geen zin in te hebben (familiebezoek, activiteit): luister, bespreek het eerlijk en weeg zijn/haar mening serieus mee in je beslissing.",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Tieners wier grenzen worden gerespecteerd door ouders, leren zelf grenzen stellen en respecteren. Het is ook een krachtig model voor gezonde relaties.",
    skillTip: "Onderscheid: verzoek ('ik wil liever niet') vs. weigering. Bij verzoek: bespreek. Bij weigering: bepaal jij — maar wel met uitleg.",
    vermijd: "Altijd toegeven als je tiener protesteert. Dat is niet respecteren, dat is capituleren.",
    leerdoel: "Je leert de grenzen van je tiener te wegen in gezinsbeslissingen.",
    bron: "Deci & Ryan (2000) - SDT — autonomy support in parent-adolescent relationships",
  },
  {
    id: "auto_1316_07",
    title: "Zelf contact met school",
    skill: "Autonomie",
    description: "Laat je tiener zelf contact opnemen met de school over een probleem, absentie of vraag. Bereid voor indien nodig, maar laat hem/haar het gesprek voeren.",
    duration: "10 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Advocate voor zichzelf zijn — zelf communiceren met autoriteiten — is een cruciale vaardigheid voor volwassenheid. Ouders die dit altijd overnemen, vertragen de ontwikkeling.",
    skillTip: "Oefen het gesprek van tevoren. Rollenspel thuis verlaagt de drempel enorm.",
    vermijd: "Naast je tiener staan en hem/haar prompts geven. Dan is het jouw gesprek, niet dat van hen.",
    leerdoel: "Je leert zelfadvocacy te stimuleren in communicatie met autoriteiten.",
    bron: "Wehmeyer (1999) - Self-Determination — advocacy & autonomy in adolescence",
  },
  {
    id: "auto_1316_08",
    title: "Vertrouwen uitspreken",
    skill: "Autonomie",
    description: "Zeg vandaag expliciet tegen je tiener: 'Ik vertrouw je. En ik verwacht dat je dat vertrouwen waardig bent.' Zeg het zonder aanleiding — gewoon zo.",
    duration: "2 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Verwachtingen uitspreken heeft een self-fulfilling prophecy effect. Tieners die weten dat hun ouder hen vertrouwt, gedragen zich vaker in lijn met dat vertrouwen.",
    skillTip: "Zeg het als er geen conflict is. Vertrouwen uitspreken in rustige tijden is krachtiger dan tijdens een crisis.",
    vermijd: "Het te koppelen aan een voorwaarde: 'Ik vertrouw je als...' Dan is het geen vertrouwen maar een deal.",
    leerdoel: "Je leert vertrouwen actief en expliciet te communiceren.",
    bron: "Rosenthal & Jacobson (1968) - Pygmalion in the Classroom — expectation effects",
  },
  {
    id: "auto_1316_09",
    title: "Eigen risico's inschatten",
    skill: "Autonomie",
    description: "Bespreek met je tiener een situatie waarin hij/zij een risico neemt: uitgaan, een nieuw vriendengroep, een sportevenement. Vraag: 'Wat zijn de risico's? Hoe ga je ermee om?'",
    duration: "10 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Risicobeoordeling is een aangeleerde vaardigheid. Tieners die dit bespreken met een ouder, zijn beter in staat om risico's in te schatten dan tieners bij wie alles verboden is.",
    skillTip: "Luister naar hun risico-inschatting voor je de jouwe geeft. Ze zijn vaak slimmer dan je denkt.",
    vermijd: "Het gesprek beëindigen met verbieden. Het doel is bewustwording, niet controle.",
    leerdoel: "Je leert risicobeoordeling te oefenen met je tiener in plaats van risico's weg te houden.",
    bron: "Steinberg (2008) - A social neuroscience perspective on adolescent risk-taking",
  },
  {
    id: "auto_1316_10",
    title: "Los laten met vertrouwen",
    skill: "Autonomie",
    description: "Laat je tiener een weekend of avond zonder check-ins gaan. Geen berichten, geen 'ben je er al?' Vertrouw op wat jullie hebben besproken.",
    duration: "2 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Loslaten is de laatste grote les van vaderschap. Tieners die voelen dat ze worden losgelaten, keren terug. Tieners die worden vastgehouden, vluchten.",
    skillTip: "Spreek één check-in af: 'Laat me weten als je thuiskomt.' Dat is genoeg. Meer is controle.",
    vermijd: "Berichten sturen als je niets hoort. Vertrouwen geef je, dat check je niet.",
    leerdoel: "Je leert loslaten als de krachtigste daad van liefde voor een tiener.",
    bron: "Steinberg (2001) - We Know Some Things — autonomy granting & healthy adolescent development",
  },
];
