import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_27: InteractiveTask[] = [
  // ============================================================
  // AGE GROUP 0-2 (10 tasks)
  // ============================================================
  {
    id: 'aanw_0-2_400',
    skill: 'Aanwezigheid',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Telefoon weg bij thuiskomst',
    description: 'Leg je telefoon bewust weg als je thuiskomt en richt je volledig op je baby.',
    instructions: [
      'Zet je telefoon op stil en leg hem in een andere kamer voordat je je kind begroet.',
      'Ga op ooghoogte van je baby en maak oogcontact terwijl je zacht praat.',
      'Besteed de eerste 10 minuten uitsluitend aan fysiek contact: tillen, knuffelen, samen op de grond zitten.',
      'Merk op hoe je baby reageert op jouw volledige aanwezigheid — kijk naar lachjes, brabbelen of ontspanning.',
    ],
    reflection: 'Hoe voelde het om de overgang van werk naar thuis bewust te markeren? Merkte je verschil in de reactie van je baby?',
    scienceNote: 'Onderzoek van Feldman (2007) toont aan dat vaderlijke aanwezigheid en sensitieve responsiviteit in het eerste levensjaar de oxytocineproductie bij zowel vader als kind verhoogt, wat de hechtingsband versterkt.',
    durationMin: 10,
  },
  {
    id: 'emco_0-2_401',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Eigen frustratie benoemen',
    description: 'Benoem hardop je eigen frustratie wanneer je baby huilt en je moe bent.',
    instructions: [
      'Wanneer je baby huilt en je merkt dat je gefrustreerd raakt, pauzeer en haal drie keer diep adem.',
      'Zeg hardop (ook al begrijpt je baby de woorden nog niet): "Papa voelt zich nu een beetje moe en gefrustreerd, maar dat is oké."',
      'Pak je baby liefdevol op en zeg: "Ik ben er voor je, we komen hier samen doorheen."',
      'Reflecteer achteraf: hoe veranderde het benoemen van je emotie de intensiteit ervan?',
    ],
    reflection: 'Baby\'s pikken emotionele signalen op lang voordat ze taal begrijpen. Hoe veranderde jouw stemtoon nadat je je gevoel benoemde?',
    scienceNote: 'Siegel & Hartzell (2003) beschrijven in "Parenting from the Inside Out" hoe het benoemen van emoties ("name it to tame it") de amygdala-activiteit vermindert en emotionele regulatie bevordert bij de ouder zelf.',
    durationMin: 10,
  },
  {
    id: 'zelr_0-2_402',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Slaapgebrek-check',
    description: 'Ontwikkel een bewuste strategie om met slaapgebrek om te gaan zonder je frustratie op je gezin te richten.',
    instructions: [
      'Houd een week lang bij hoe je slaapkwaliteit je stemming en geduld beïnvloedt — noteer elke ochtend kort je energieniveau (1-10).',
      'Identificeer je "rode zone": bij welk energieniveau merk je dat je sneller geïrriteerd raakt?',
      'Maak een concreet plan met je partner: wie neemt welke nacht? Kun je een powernap van 20 minuten inplannen?',
      'Oefen een "reset-ritueel" voor moeilijke momenten: 5 seconden inademen, 7 seconden uitademen, herhaal 3 keer.',
    ],
    reflection: 'Slaapgebrek is een van de grootste stressoren voor nieuwe vaders. Welk patroon ontdekte je en hoe kun je hier structureel mee omgaan?',
    scienceNote: 'Onderzoek van Mindell et al. (2015) toont dat slaapgebrek bij ouders leidt tot verminderde executieve functies en emotieregulatie, wat de kwaliteit van ouder-kindinteracties direct beïnvloedt.',
    durationMin: 15,
  },
  {
    id: 'gren_0-2_403',
    skill: 'Grenzen',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Werk-thuis grens maken',
    description: 'Creëer een bewust overgangsritueel tussen werk en vaderschap.',
    instructions: [
      'Kies een fysieke handeling die het einde van je werkdag markeert: jas uit, handen wassen, of een kort blokje om.',
      'Zeg in gedachten of hardop: "Nu ben ik papa" terwijl je dit ritueel uitvoert.',
      'Laat werkgerelateerde gedachten bewust los — schrijf ze eventueel op een briefje voor morgen.',
      'Begroet je baby met een warm ritueel: een specifiek liedje, knuffel of begroetingszin.',
    ],
    reflection: 'Hoe helpt een fysiek overgangsritueel je om mentaal aanwezig te zijn? Merkte je dat het makkelijker werd om werk los te laten?',
    scienceNote: 'Ashforth et al. (2000) beschrijven hoe "boundary-crossing activities" helpen bij het schakelen tussen rollen, wat de kwaliteit van zowel werk als gezinstijd verbetert.',
    durationMin: 5,
  },
  {
    id: 'verb_0-2_404',
    skill: 'Verbinding',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Huid-op-huidmoment',
    description: 'Plan een bewust huid-op-huidmoment met je baby om je eigen hechtingsgevoelens te versterken.',
    instructions: [
      'Kies een rustig moment en trek je shirt uit. Leg je baby in alleen een luier op je borst.',
      'Adem rustig en focus op het fysieke contact — voel de warmte, de ademhaling van je baby.',
      'Praat zacht of zing een liedje. Merk op welke gevoelens er bij jou opkomen.',
      'Blijf minstens 10 minuten zo zitten. Sta jezelf toe om geraakt te worden door dit moment.',
    ],
    reflection: 'Welke emoties kwamen er bij je op tijdens dit contact? Voelde je weerstand of juist overgave? Beide zijn normaal.',
    scienceNote: 'Feldman et al. (2010) toonden aan dat huid-op-huidcontact (kangaroo care) door vaders de vader-kindgehechtheid significant versterkt en het cortisolniveau bij beide verlaagt.',
    durationMin: 15,
  },
  {
    id: 'hers_0-2_405',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Herstellen na een moeilijk moment',
    description: 'Oefen herstel nadat je gefrustreerd reageerde op je huilende baby.',
    instructions: [
      'Herken het moment: je reageerde kortaf, zuchtte diep, of legde je baby iets te abrupt neer.',
      'Geef jezelf compassie: "Ik ben menselijk, dit was een moeilijk moment."',
      'Pak je baby op, maak oogcontact en zeg op warme toon: "Sorry lieverd, papa was even niet zo lief. Ik ben er nu weer voor je."',
      'Reflecteer later: wat was de trigger? Was je moe, hongerig, of overprikkeld? Hoe kun je dit voorkomen?',
    ],
    reflection: 'Herstel is belangrijker dan perfectie. Hoe voelde het om jezelf toestemming te geven om fouten te maken en te herstellen?',
    scienceNote: 'Tronick (2007) toont met het "still face" paradigma aan dat het niet de breuk maar het herstel is dat de hechtingsrelatie vormt. Reparatie na miscommunicatie versterkt de relatie.',
    durationMin: 10,
  },
  {
    id: 'refl_0-2_406',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Brief aan je eigen vader',
    description: 'Schrijf een brief aan je eigen vader over wat je wel en niet wilt overnemen in je vaderschap.',
    instructions: [
      'Neem 15 minuten rustige tijd. Pak pen en papier (geen telefoon).',
      'Schrijf een brief aan je eigen vader. Begin met wat je waardeert aan hoe hij er was (of niet was).',
      'Beschrijf vervolgens wat je anders wilt doen. Wees eerlijk maar niet veroordelend.',
      'Sluit af met een belofte aan jezelf als vader. Je hoeft de brief niet te versturen — hij is voor jou.',
    ],
    reflection: 'Welke patronen uit je eigen opvoeding herken je al bij jezelf? Welk patroon wil je bewust doorbreken?',
    scienceNote: 'Siegel & Hartzell (2003) benadrukken dat ouders die een "coherent narratief" over hun eigen jeugd ontwikkelen, significant betere hechtingsrelaties met hun kinderen opbouwen.',
    durationMin: 15,
  },
  {
    id: 'auto_0-2_407',
    skill: 'Autonomie',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Zelf een verzorgmoment doen',
    description: 'Neem bewust een compleet verzorgmoment voor je rekening zonder hulp van je partner.',
    instructions: [
      'Kies een vast verzorgmoment: bad geven, verschonen of naar bed brengen.',
      'Doe dit volledig zelfstandig, zonder je partner om hulp te vragen (tenzij onveilig).',
      'Doe het op jouw manier — het hoeft niet precies zoals je partner het doet. Jouw manier is ook goed.',
      'Geniet van het gevoel van competentie: jij kunt dit. Je baby heeft jou ook nodig.',
    ],
    reflection: 'Hoe voelde het om dit zelfstandig te doen? Merkte je bij jezelf onzekerheid of juist trots?',
    scienceNote: 'Abraham et al. (2014) ontdekten dat vaders die zelfstandig zorgtaken uitvoeren dezelfde neurale "oudernetwerken" activeren als moeders, maar dat dit alleen gebeurt bij regelmatige, zelfstandige zorg.',
    durationMin: 10,
  },
  {
    id: 'emco_0-2_408',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Emotiedagboek bijhouden',
    description: 'Houd drie dagen een kort emotiedagboek bij over je gevoelens als nieuwe vader.',
    instructions: [
      'Schrijf elke avond drie dingen op: het mooiste moment, het moeilijkste moment, en je overheersende gevoel van de dag.',
      'Wees eerlijk — ook gevoelens als verveling, spijt of overweldiging mogen er zijn.',
      'Lees na drie dagen terug. Zie je patronen? Welke situaties roepen welke emoties op?',
      'Deel (als je wilt) één observatie met je partner of een vertrouwenspersoon.',
    ],
    reflection: 'Veel vaders vinden het lastig om gevoelens te benoemen. Werd het makkelijker naarmate je meer schreef?',
    scienceNote: 'Pennebaker (1997) toonde aan dat expressief schrijven over emoties de fysieke en mentale gezondheid verbetert, en Gottman (1997) benadrukt dat emotioneel bewustzijn de basis is voor emotiecoaching.',
    durationMin: 15,
  },
  {
    id: 'zelr_0-2_409',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Triggeranalyse als vader',
    description: 'Identificeer je persoonlijke triggers die overreacties uitlokken en maak een plan.',
    instructions: [
      'Denk aan de laatste drie keer dat je als vader sterker reageerde dan nodig. Schrijf de situaties op.',
      'Zoek het patroon: was het altijd dezelfde tijd, hetzelfde type gedrag, of dezelfde emotie bij jou?',
      'Koppel elke trigger aan een onderliggende behoefte: rust, erkenning, controle, of iets anders?',
      'Maak voor je top-trigger een "als-dan"-plan: "Als [trigger], dan [rustige reactie]."',
    ],
    reflection: 'Onze triggers komen vaak uit ons eigen verleden. Herken je in je triggers iets van hoe je zelf bent opgevoed?',
    scienceNote: 'Siegel (2012) beschrijft hoe onverwerkte ervaringen uit de eigen jeugd als "triggers" fungeren die automatische, ongereguleerde reacties uitlokken bij ouders — bewustwording is de eerste stap naar verandering.',
    durationMin: 15,
  },

  // ============================================================
  // AGE GROUP 3-5 (10 tasks)
  // ============================================================
  {
    id: 'refl_3-5_410',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Spiegel van je kind',
    description: 'Observeer welk gedrag van je peuter/kleuter je het meest raakt en onderzoek waarom.',
    instructions: [
      'Let vandaag bewust op een moment waarop je kind gedrag vertoont dat jou emotioneert (positief of negatief).',
      'Schrijf het moment kort op: wat deed je kind precies en wat voelde jij?',
      'Stel jezelf de vraag: herken ik dit gedrag van mezelf of van mijn eigen ouders?',
      'Bedenk wat dit je leert over jezelf. Je kind is vaak een spiegel van je eigen onverwerkte thema\'s.',
    ],
    reflection: 'Kinderen houden ons onbewust een spiegel voor. Wat leerde dit moment je over jezelf?',
    scienceNote: 'Siegel & Hartzell (2003) stellen dat kinderen vaak precies die emoties bij ons triggeren die verband houden met onze eigen onverwerkte hechtingservaringen.',
    durationMin: 10,
  },
  {
    id: 'aanw_3-5_411',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Mindful spelen',
    description: 'Speel 15 minuten met je kind zonder enige afleiding en volg volledig het spel van je kind.',
    instructions: [
      'Zet alle schermen uit. Leg je telefoon in een andere kamer.',
      'Ga naast je kind zitten en zeg: "Ik wil graag met jou spelen. Wat zullen we doen?"',
      'Volg het spel van je kind zonder te sturen. Doe mee in de wereld die je kind creëert.',
      'Wanneer je merkt dat je gedachten afdwalen (werk, taken), breng je aandacht zacht terug naar je kind.',
    ],
    reflection: 'Hoe vaak dwaalden je gedachten af? Wat zegt dat over je vermogen om present te zijn? Dit is een spier die je kunt trainen.',
    scienceNote: 'Kabat-Zinn & Kabat-Zinn (1997) beschrijven in "Everyday Blessings" hoe mindful ouderschap de kwaliteit van de ouder-kindrelatie fundamenteel verbetert door aanwezigheid zonder oordeel.',
    durationMin: 15,
  },
  {
    id: 'hers_3-5_412',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Sorry zeggen en het menen',
    description: 'Bied oprecht je excuses aan na een moment waarop je te streng of oneerlijk reageerde.',
    instructions: [
      'Wacht tot je zelf rustig bent. Ga op ooghoogte van je kind zitten.',
      'Zeg specifiek wat je verkeerd deed: "Het spijt me dat ik zo hard schreeuwde toen je melk morste."',
      'Erken het gevoel van je kind: "Dat was vast eng/verdrietig voor je."',
      'Vertel wat je anders wilt doen: "De volgende keer ga ik eerst diep ademhalen." Geef een knuffel als je kind dat wil.',
    ],
    reflection: 'Hoe voelde het om kwetsbaar te zijn tegenover je kind? Merkte je hoe je kind reageerde op je oprechte excuses?',
    scienceNote: 'Gottman (1999) identificeert "repair attempts" als de belangrijkste voorspeller van relatiesucces. Dit geldt ook voor ouder-kindrelaties: herstel na conflict versterkt het vertrouwen.',
    durationMin: 10,
  },
  {
    id: 'emco_3-5_413',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Hardop voelen',
    description: 'Model emotioneel bewustzijn door je eigen gevoelens de hele dag hardop te benoemen.',
    instructions: [
      'Benoem je emoties gedurende de dag hardop waar je kind bij is: "Papa is blij want de zon schijnt!"',
      'Benoem ook lastige emoties: "Papa is een beetje gefrustreerd omdat het druk was op het werk."',
      'Voeg altijd een strategie toe: "Dus ik ga even rustig zitten en diep ademhalen."',
      'Nodig je kind uit: "Hoe voel jij je nu? Je mag het altijd vertellen."',
    ],
    reflection: 'Kinderen leren emotieregulatie door het te zien bij hun ouders. Hoe reageerde je kind op jouw openheid?',
    scienceNote: 'Gottman et al. (1996) tonen aan dat kinderen van "emotiecoachende" ouders betere emotieregulatie, betere sociale vaardigheden en betere schoolprestaties hebben.',
    durationMin: 10,
  },
  {
    id: 'zelr_3-5_414',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Pauzeknop indrukken',
    description: 'Oefen bewust om een pauze te nemen voordat je reageert op uitdagend gedrag.',
    instructions: [
      'Wanneer je kind iets doet dat je irriteert, stop dan letterlijk met wat je doet.',
      'Zeg hardop: "Papa heeft even een pauze nodig om na te denken." Haal vijf keer diep adem.',
      'Stel jezelf de vraag: "Wat heeft mijn kind nu echt nodig?" in plaats van "Hoe stop ik dit gedrag?"',
      'Reageer pas daarna. Merk het verschil op tussen je eerste impuls en je doordachte reactie.',
    ],
    reflection: 'Wat was je eerste impuls en wat deed je uiteindelijk? Het verschil daartussen is je groei als vader.',
    scienceNote: 'Zelazo & Carlson (2012) tonen aan dat executieve functies (waaronder inhibitie) trainbaar zijn en dat ouders die hun eigen impulscontrole modelleren, deze vaardigheid aan hun kinderen overdragen.',
    durationMin: 5,
  },
  {
    id: 'gren_3-5_415',
    skill: 'Grenzen',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Respectvol nee zeggen',
    description: 'Oefen grenzen stellen op een manier die respect modelleert in plaats van macht.',
    instructions: [
      'Wanneer je "nee" moet zeggen, kniel dan eerst op ooghoogte van je kind.',
      'Erken de wens: "Ik snap dat je nog een koekje wilt. Dat is heel lekker, hè?"',
      'Stel de grens vriendelijk maar duidelijk: "We eten nu geen koekjes meer, want we gaan zo eten."',
      'Bied een alternatief: "Je mag kiezen: een stukje komkommer of een stukje paprika."',
    ],
    reflection: 'Hoe voelt het om grenzen te stellen zonder boos te worden? Kun je kordaat én warm tegelijk zijn?',
    scienceNote: 'Baumrind (1991) beschrijft hoe "autoritatief" opvoeden — warm maar met duidelijke grenzen — de beste uitkomsten geeft voor kinderen. Het gaat om structuur met respect.',
    durationMin: 5,
  },
  {
    id: 'auto_3-5_416',
    skill: 'Autonomie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Papa\'s eigen rustmoment',
    description: 'Laat je kind zien dat zelfzorg normaal is door bewust een rustmoment voor jezelf te nemen.',
    instructions: [
      'Vertel je kind: "Papa gaat even 5 minuten rustig zitten om op te laden. Daarna spelen we weer samen."',
      'Ga zichtbaar voor je kind zitten, sluit je ogen en adem rustig.',
      'Als je kind vraagt wat je doet, leg dan uit: "Iedereen heeft soms rust nodig. Ook papa\'s."',
      'Kom na 5 minuten terug en zeg: "Ik voel me weer lekker! Zullen we iets leuks doen?"',
    ],
    reflection: 'Voel je je schuldig als je even rust neemt? Waar komt dat gevoel vandaan? Zelfzorg is geen egoïsme.',
    scienceNote: 'Holt-Lunstad et al. (2010) tonen aan dat zelfzorg bij ouders niet alleen hun eigen welzijn verbetert, maar ook de kwaliteit van de ouder-kindrelatie — uitgeputte ouders zijn minder sensitief.',
    durationMin: 5,
  },
  {
    id: 'verb_3-5_417',
    skill: 'Verbinding',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Respectvol praten met partner',
    description: 'Model een respectvolle interactie met je partner waar je kind bij is.',
    instructions: [
      'Kies een moment waarop je kind in de buurt is en vraag je partner bewust iets op een warme, respectvolle manier.',
      'Gebruik "ik"-taal: "Ik zou het fijn vinden als..." in plaats van "Jij moet...".',
      'Luister actief naar het antwoord: knik, maak oogcontact, herhaal wat je partner zegt.',
      'Bedank je partner oprecht waar je kind het kan zien en horen.',
    ],
    reflection: 'Je kind leert over relaties door te kijken hoe jij met je partner omgaat. Wat leert je kind van jullie interacties?',
    scienceNote: 'Cummings & Davies (2010) tonen uitgebreid aan dat de kwaliteit van de partnerrelatie de belangrijkste voorspeller is van het welzijn van kinderen — zelfs belangrijker dan individuele opvoedstijl.',
    durationMin: 10,
  },
  {
    id: 'refl_3-5_418',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Opvoedpatronen doorbreken',
    description: 'Identificeer één negatief opvoedpatroon uit je eigen jeugd en maak een plan om het te doorbreken.',
    instructions: [
      'Denk aan een opvoedgewoonte van je eigen ouders die je niet wilt herhalen (bijv. schreeuwen, negeren, overmatig straffen).',
      'Schrijf eerlijk op: in welke situaties merk je dat je dit patroon zelf herhaalt?',
      'Bedenk een concreet alternatief gedrag. Schrijf het op als een "in plaats van... ga ik..."-zin.',
      'Vraag je partner of een vriend om je er (liefdevol) op te wijzen als ze het oude patroon zien.',
    ],
    reflection: 'Het doorbreken van generatiepatronen is moeilijk maar mogelijk. Welk patroon ontdekte je en hoe voelt het om dit onder ogen te zien?',
    scienceNote: 'Van IJzendoorn (1995) beschrijft de "intergenerationele overdracht van gehechtheid" en toont aan dat bewuste reflectie op eigen jeugdervaringen de kans op herhaling van negatieve patronen significant verkleint.',
    durationMin: 15,
  },
  {
    id: 'hers_3-5_419',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Herstellijst maken',
    description: 'Maak samen met je kind een "herstellijst" met manieren om het goed te maken na ruzie.',
    instructions: [
      'Ga op een rustig moment met je kind zitten en zeg: "Soms worden papa\'s en kinderen boos op elkaar. Dat is normaal."',
      'Vraag: "Wat helpt jou als je verdrietig bent? Een knuffel? Een liedje? Even samen zitten?"',
      'Schrijf of teken samen een lijstje met "hersteldingen" die jullie allebei fijn vinden.',
      'Hang de lijst op een zichtbare plek. Verwijs ernaar na een conflict: "Zullen we onze herstellijst erbij pakken?"',
    ],
    reflection: 'Door herstel te normaliseren, leer je je kind dat conflicten niet het einde zijn maar een kans om dichter bij elkaar te komen.',
    scienceNote: 'Gottman & DeClaire (1997) beschrijven hoe "repair rituals" de emotionele veiligheid in relaties vergroten. Kinderen die leren herstellen, ontwikkelen veerkrachtiger relaties later in hun leven.',
    durationMin: 15,
  },

  // ============================================================
  // AGE GROUP 6-9 (10 tasks)
  // ============================================================
  {
    id: 'verb_6-9_420',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Papa vertelt over zijn dag',
    description: 'Deel open en eerlijk hoe jouw dag was, inclusief moeilijke momenten.',
    instructions: [
      'Vertel tijdens het avondeten niet alleen "het was goed", maar deel echt hoe je dag was.',
      'Noem iets dat goed ging: "Ik heb een collega geholpen en dat voelde fijn."',
      'Noem ook iets dat lastig was: "Ik had een moeilijk gesprek en voelde me daarna onzeker."',
      'Sluit af met hoe je ermee omging: "Ik heb even gewandeld en dat hielp."',
    ],
    reflection: 'Door kwetsbaar te zijn, leer je je kind dat het oké is om niet altijd sterk te zijn. Hoe reageerde je kind?',
    scienceNote: 'Fivush et al. (2006) tonen aan dat gezinnen die "uitgebreide verhalen" delen over dagelijkse ervaringen, kinderen met een sterker zelfgevoel en betere emotieregulatie opvoeden.',
    durationMin: 10,
  },
  {
    id: 'aanw_6-9_421',
    skill: 'Aanwezigheid',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Eén-op-één papa-tijd',
    description: 'Plan wekelijks een vast moment alleen met je kind en bescherm dit tegen alle afleidingen.',
    instructions: [
      'Kies samen met je kind een vast wekelijks moment: "Dit is ons moment, elke zaterdag."',
      'Laat je kind kiezen wat jullie doen. Het gaat niet om de activiteit maar om de aandacht.',
      'Zet je telefoon uit (niet op stil, maar uit). Laat niets tussenkomen.',
      'Maak er een traditie van. Geef het een naam: "Papa-[naam]-tijd" of iets dat je kind leuk vindt.',
    ],
    reflection: 'Hoe voelde het om je telefoon helemaal uit te zetten? Merkte je verschil in de kwaliteit van het contact?',
    scienceNote: 'Pleck (2010) toont aan dat niet de hoeveelheid maar de kwaliteit van vader-kindtijd bepalend is voor de ontwikkeling. "Engaged fathering" met volledige aandacht heeft de sterkste positieve effecten.',
    durationMin: 15,
  },
  {
    id: 'zelr_6-9_422',
    skill: 'Zelfregulatie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Emotie-thermometer voor papa',
    description: 'Maak een emotie-thermometer voor jezelf en deel deze met je kind.',
    instructions: [
      'Teken samen met je kind een thermometer op papier, van groen (rustig) via oranje (gespannen) naar rood (boos/overweldigd).',
      'Leg uit: "Papa gebruikt dit ook. Nu ben ik hier" en wijs een plek aan.',
      'Gebruik de thermometer actief de komende dagen: "Papa zit nu op oranje, ik ga even ademhalen."',
      'Moedig je kind aan om ook de thermometer te gebruiken. Bespreek samen strategieën per kleur.',
    ],
    reflection: 'Door je eigen emoties zichtbaar te maken, normaliseer je gevoelens voor je kind. Hoe reageerde je kind op jouw openheid?',
    scienceNote: 'Eisenberg et al. (1998) tonen aan dat ouders die hun eigen emotieregulatie zichtbaar modelleren, kinderen opvoeden met significant betere zelfregulatievaardigheden.',
    durationMin: 10,
  },
  {
    id: 'gren_6-9_423',
    skill: 'Grenzen',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Eerlijk over eigen grenzen',
    description: 'Communiceer op een respectvolle manier je eigen grenzen naar je kind.',
    instructions: [
      'Wanneer je kind aandacht vraagt op een moment dat je echt niet kunt, wees dan eerlijk.',
      'Zeg niet: "Nu niet!" maar: "Ik wil heel graag met je spelen, maar ik moet eerst dit afmaken."',
      'Geef een concreet tijdstip: "Over 10 minuten ben ik er helemaal voor jou."',
      'Kom je belofte na. Als je zegt "over 10 minuten", zorg dan dat je er over 10 minuten bent.',
    ],
    reflection: 'Hoe kun je eerlijk grenzen stellen zonder dat je kind zich afgewezen voelt? Je belofte nakomen is hier de sleutel.',
    scienceNote: 'Bowlby (1988) benadrukt dat betrouwbaarheid — het nakomen van beloftes — de basis vormt van veilige gehechtheid. Kinderen hoeven niet altijd "ja" te horen, maar wel eerlijkheid en betrouwbaarheid.',
    durationMin: 5,
  },
  {
    id: 'emco_6-9_424',
    skill: 'Emotiecoaching',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Boosheid laten zien, niet uitageren',
    description: 'Oefen om je boosheid gezond te tonen als model voor je kind.',
    instructions: [
      'Wanneer je boos bent (niet op je kind, bijv. op het nieuws of een situatie), benoem dit expliciet.',
      'Zeg: "Ik ben nu boos omdat [reden]. Boos zijn is oké, maar ik ga niemand pijn doen."',
      'Toon je strategie: "Ik ga even stevig doorademen / een eindje lopen / het opschrijven."',
      'Kom terug en vertel: "Ik ben nu rustiger. Boos zijn gaat weer over als je er goed mee omgaat."',
    ],
    reflection: 'Hoe heeft jouw eigen vader omgegaan met boosheid? Wat wil je je kind leren dat anders is?',
    scienceNote: 'Gottman (1997) benadrukt dat het niet gaat om het vermijden van negatieve emoties, maar om het modelleren van gezonde manieren om ermee om te gaan. Dit noemt hij "emotiecoaching".',
    durationMin: 10,
  },
  {
    id: 'auto_6-9_425',
    skill: 'Autonomie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Je passie delen',
    description: 'Deel een hobby of passie met je kind en laat zien dat leren en groeien leuk is op elke leeftijd.',
    instructions: [
      'Kies iets waar jij enthousiast over bent: koken, muziek, sport, natuur, techniek.',
      'Nodig je kind uit op een manier die past bij de leeftijd: "Wil je mee kijken hoe papa dit doet?"',
      'Laat ook zien dat je nog aan het leren bent: "Kijk, dit gaat nog niet zo goed. Maar ik oefen."',
      'Vraag je kind om input: "Wat vind jij? Heb jij een idee?" Behandel je kind als een gelijkwaardige partner.',
    ],
    reflection: 'Door je eigen leerproces te laten zien, model je een growth mindset. Hoe reageerde je kind op jouw kwetsbaarheid?',
    scienceNote: 'Dweck (2006) toont aan dat kinderen die een "growth mindset" observeren bij hun ouders, zelf meer veerkracht en doorzettingsvermogen ontwikkelen bij uitdagingen.',
    durationMin: 15,
  },
  {
    id: 'refl_6-9_426',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Wekelijkse vader-reflectie',
    description: 'Voer een wekelijks reflectiemoment in over je vaderschap.',
    instructions: [
      'Kies een vast moment in de week (bijv. zondagavond) voor 15 minuten zelfreflectie.',
      'Beantwoord drie vragen: 1) Waar was ik deze week trots op als vader? 2) Wat had ik anders willen doen? 3) Wat neem ik mee naar volgende week?',
      'Schrijf je antwoorden kort op in een notitieboekje — zo kun je je groei over tijd volgen.',
      'Wees mild voor jezelf: groei gaat niet lineair. Elke week dat je reflecteert, ben je al bezig met bewust vaderschap.',
    ],
    reflection: 'Hoe voelt het om structureel te reflecteren? Zie je al patronen na een paar weken?',
    scienceNote: 'Schön (1983) beschrijft hoe "reflective practice" professionals helpt om te groeien. Cowan & Cowan (2000) passen dit toe op ouderschap: reflectieve vaders zijn sensitievere vaders.',
    durationMin: 15,
  },
  {
    id: 'hers_6-9_427',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Fout toegeven zonder excuus',
    description: 'Geef een fout toe aan je kind zonder excuses te maken of de schuld te verschuiven.',
    instructions: [
      'Denk aan een recente situatie waarin je oneerlijk was tegenover je kind (te streng, niet geluisterd, belofte gebroken).',
      'Ga naar je kind en zeg: "Ik wil je iets vertellen. Ik heb [specifieke fout] gedaan en dat was niet goed van me."',
      'Maak geen excuses ("ik was moe", "jij deed ook..."). Neem volledige verantwoordelijkheid.',
      'Vertel wat je de volgende keer anders wilt doen en vraag: "Kun je me vergeven?"',
    ],
    reflection: 'Hoe moeilijk was het om geen excuus toe te voegen? Wat zegt dat over hoe jij hebt geleerd om met fouten om te gaan?',
    scienceNote: 'Tangney et al. (2007) tonen aan dat oprechte schuldbeleving (zonder schaamte) en het nemen van verantwoordelijkheid de sterkste voorspellers zijn van relationeel herstel en prosociaal gedrag bij kinderen.',
    durationMin: 5,
  },
  {
    id: 'verb_6-9_428',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Gezamenlijk probleemoplossing',
    description: 'Los een gezinsprobleem samen met je kind op als gelijkwaardige partners.',
    instructions: [
      'Kies een terugkerend probleem in jullie gezin (bijv. rommel in de gang, ruzie over schermtijd).',
      'Zeg: "Ik heb jouw hulp nodig. Hoe kunnen we dit samen oplossen?" Behandel je kind als mede-eigenaar van het probleem.',
      'Luister écht naar de ideeën van je kind. Schrijf alle suggesties op zonder te oordelen.',
      'Kies samen een oplossing en probeer deze een week uit. Evalueer samen: "Werkt dit of moeten we iets anders proberen?"',
    ],
    reflection: 'Door je kind te betrekken bij probleemoplossing, model je samenwerking en respect. Welk idee van je kind verraste je?',
    scienceNote: 'Greene (2014) beschrijft in "The Explosive Child" hoe collaboratieve probleemoplossing niet alleen gedragsproblemen vermindert, maar kinderen ook leert dat hun stem ertoe doet.',
    durationMin: 15,
  },
  {
    id: 'zelr_6-9_429',
    skill: 'Zelfregulatie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Stress zichtbaar reguleren',
    description: 'Gebruik een stressvolle situatie als leermoment door je regulatiestrategie hardop te delen.',
    instructions: [
      'Wanneer je gestrest bent (file, kapot apparaat, slecht nieuws), beschrijf wat er in je gebeurt.',
      'Zeg: "Ik merk dat mijn hart sneller klopt en mijn schouders omhoog zitten. Dat betekent dat ik gestrest ben."',
      'Doe een regulatieoefening waar je kind bij is: schouders laten zakken, 4-7-8 ademhaling, of een glas water drinken.',
      'Benoem het resultaat: "Kijk, ik voel me al iets rustiger. Het probleem is er nog, maar ik kan er nu beter mee omgaan."',
    ],
    reflection: 'Hoe vaak ziet je kind jou omgaan met stress? Wat leren ze als ze alleen het resultaat (irritatie) zien versus het hele proces?',
    scienceNote: 'Porges (2011) beschrijft in de polyvagaaltheorie hoe kinderen co-regulatie leren door het observeren van de fysiologische regulatie van hun verzorgers. Zichtbare kalmering helpt kinderen hun eigen zenuwstelsel te reguleren.',
    durationMin: 10,
  },

  // ============================================================
  // AGE GROUP 10-12 (10 tasks)
  // ============================================================
  {
    id: 'aanw_10-12_430',
    skill: 'Aanwezigheid',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Aanwezig zonder agenda',
    description: 'Breng tijd door met je kind zonder doel of activiteit — gewoon samen zijn.',
    instructions: [
      'Ga in dezelfde ruimte zitten als je kind zonder een specifieke activiteit voor te stellen.',
      'Wees beschikbaar maar niet opdringerig. Lees een boek, doe een puzzel, of zit gewoon.',
      'Als je kind iets deelt of een gesprek begint, geef het je volle aandacht.',
      'Als er stilte is, laat die er zijn. Niet elke stilte hoeft gevuld te worden. Aanwezigheid is genoeg.',
    ],
    reflection: 'Hoe voelde het om samen te zijn zonder iets te "moeten"? Merkten jullie een ander soort verbinding?',
    scienceNote: 'Winnicott (1965) beschrijft het concept van "being alone in the presence of another" als fundamenteel voor emotionele ontwikkeling. Kinderen hebben soms geen interactie nodig, maar wel de zekerheid van nabijheid.',
    durationMin: 15,
  },
  {
    id: 'emco_10-12_431',
    skill: 'Emotiecoaching',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Over je eigen puberteit praten',
    description: 'Deel eerlijke herinneringen aan je eigen puberteit met je kind.',
    instructions: [
      'Kies een rustig, informeel moment (bijv. in de auto of tijdens een wandeling).',
      'Deel een herinnering uit je eigen jeugd: een moment waarop je je onzeker voelde, niet erbij hoorde, of iets stoms deed.',
      'Wees eerlijk en kwetsbaar: "Ik schaamde me daar echt voor. Ik dacht dat ik de enige was."',
      'Verbind het aan nu: "Als jij je ooit zo voelt, wil ik dat je weet dat het normaal is en dat je het mij mag vertellen."',
    ],
    reflection: 'Hoe reageerde je kind op je eerlijkheid? Merkte je dat kwetsbaarheid nabijheid creëert in plaats van afstand?',
    scienceNote: 'Habermas & Bluck (2000) tonen aan dat het delen van persoonlijke verhalen de identiteitsontwikkeling van pre-adolescenten ondersteunt en de ouder-kindrelatie versterkt.',
    durationMin: 10,
  },
  {
    id: 'zelr_10-12_432',
    skill: 'Zelfregulatie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Eigen schermtijd als model',
    description: 'Reflecteer op je eigen schermgebruik en stel regels op die ook voor jou gelden.',
    instructions: [
      'Check je schermtijd-statistieken op je telefoon. Wees eerlijk: hoeveel uur per dag zit je op je scherm?',
      'Bespreek dit openlijk met je kind: "Papa kijkt ook te veel op zijn telefoon. Dat wil ik veranderen."',
      'Maak samen gezinsregels die voor iedereen gelden: geen telefoon aan tafel, geen schermen na 21:00, etc.',
      'Houd je er zelf aan — je kind zal het onmiddellijk opmerken als je vals speelt.',
    ],
    reflection: 'Hoe voelt het om dezelfde regels als je kind te volgen? Wat leert dit je over hoe moeilijk zelfregulatie ook voor volwassenen is?',
    scienceNote: 'Coyne et al. (2017) tonen aan dat ouderschermgebruik direct correleert met kinderschermgebruik, en dat gedeelde gezinsregels effectiever zijn dan regels die alleen voor kinderen gelden.',
    durationMin: 10,
  },
  {
    id: 'gren_10-12_433',
    skill: 'Grenzen',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Nee zeggen op werk voor je gezin',
    description: 'Zeg bewust nee tegen een werkverzoek ten gunste van gezinstijd en bespreek dit met je kind.',
    instructions: [
      'Wanneer je de mogelijkheid hebt om extra werk aan te nemen dat ten koste gaat van gezinstijd, kies dan bewust voor je gezin.',
      'Vertel je kind wat je deed: "Er was een vergadering vanavond, maar ik heb gezegd dat ik niet kon. Ik wilde bij jullie zijn."',
      'Praat niet negatief over je werk — het gaat om de bewuste keuze, niet om klagen.',
      'Vraag je kind: "Merk je het als ik er ben? Wat vind je het fijnst als we samen zijn?"',
    ],
    reflection: 'Hoe voelde het om werk te laten voor wat het was? Welke boodschap geef je je kind over prioriteiten?',
    scienceNote: 'Greenhaus & Powell (2006) beschrijven hoe bewuste "work-family enrichment" niet alleen de gezinsrelatie verbetert, maar ook de werktevredenheid — het is geen zero-sum game.',
    durationMin: 10,
  },
  {
    id: 'auto_10-12_434',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Iets nieuws leren waar je kind bij is',
    description: 'Begin met iets nieuws leren en laat je kind je worstelingen zien.',
    instructions: [
      'Kies iets dat je altijd al wilde leren maar nooit hebt gedaan: een instrument, een taal, jongleren, tekenen.',
      'Oefen waar je kind bij is. Laat zien dat je fouten maakt en dat het frustrerend kan zijn.',
      'Benoem je proces: "Dit is echt moeilijk! Maar ik merk dat het elke keer een klein beetje beter gaat."',
      'Vraag je kind om tips of aanmoediging. Wissel de rollen om: laat je kind de leraar zijn.',
    ],
    reflection: 'Hoe reageerde je kind op het zien van jou als leerling? Wat leer je door jezelf kwetsbaar op te stellen?',
    scienceNote: 'Bandura (1986) toont met de sociale leertheorie aan dat kinderen niet leren van perfecte modellen, maar van modellen die moeite doen, falen, en doorzetten — zogenaamd "coping modeling".',
    durationMin: 15,
  },
  {
    id: 'hers_10-12_435',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Oud zeer erkennen',
    description: 'Erken een patroon uit het verleden dat je kind mogelijk heeft gekwetst.',
    instructions: [
      'Denk na over een terugkerend patroon: was je vaak afwezig, te kritisch, of emotioneel onbeschikbaar?',
      'Kies een rustig moment en zeg: "Ik wil met je praten over iets dat ik anders had willen doen."',
      'Wees specifiek: "Ik was het afgelopen jaar vaak te druk met werk. Ik weet dat je me miste. Het spijt me."',
      'Vraag niet om vergeving, maar bied het aan: "Ik werk eraan om dit te veranderen. Je mag altijd zeggen als je vindt dat het niet lukt."',
    ],
    reflection: 'Hoe voelde het om iets te erkennen zonder het goed te praten? Herstel gaat niet over gelijk krijgen maar over verbinding herstellen.',
    scienceNote: 'Hughes (2009) beschrijft hoe het erkennen van eerdere fouten door ouders het vertrouwen herstelt en kinderen leert dat relaties bestand zijn tegen imperfectie — een kernprincipe van PACE-therapie.',
    durationMin: 15,
  },
  {
    id: 'refl_10-12_436',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Vaderschap-waarden definiëren',
    description: 'Definieer je drie kernwaarden als vader en toets of je leven ermee in lijn is.',
    instructions: [
      'Schrijf op: "Als mijn kinderen later terugkijken, welke drie dingen wil ik dat ze over mij als vader zeggen?"',
      'Toets elke waarde: leef ik dit nu echt? Wat is het bewijs? Waar ziet mijn kind dit terug in mijn gedrag?',
      'Identificeer de grootste kloof: welke waarde leef je het minst? Wat staat er in de weg?',
      'Maak één concreet voornemen voor de komende week om die kloof te verkleinen.',
    ],
    reflection: 'Is er een verschil tussen de vader die je wilt zijn en de vader die je bent? Dat verschil is je groeimarge.',
    scienceNote: 'Deci & Ryan (2000) tonen met de zelfdeterminatietheorie aan dat handelen in lijn met je kernwaarden de intrinsieke motivatie en het welzijn verhoogt — dit geldt ook voor de vaderrol.',
    durationMin: 15,
  },
  {
    id: 'verb_10-12_437',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Actief luisteren oefenen',
    description: 'Oefen een gesprek met je kind waarin je alleen luistert, zonder advies te geven.',
    instructions: [
      'Vraag je kind: "Vertel me eens iets dat je bezighoudt op school of met vrienden."',
      'Luister zonder te onderbreken. Knik, maak oogcontact, en zeg alleen "hmm" of "vertel meer".',
      'Weersta de neiging om advies te geven of het probleem op te lossen. Zeg in plaats daarvan: "Dat klinkt [lastig/spannend/verdrietig]."',
      'Sluit af met: "Dank je dat je dit met me deelt. Wil je dat ik meedenk, of was het fijn om het te vertellen?"',
    ],
    reflection: 'Hoe moeilijk was het om geen advies te geven? Wat zegt dat over hoe jij gewend bent om te communiceren?',
    scienceNote: 'Rogers (1961) beschrijft hoe "unconditional positive regard" en actief luisteren de basis vormen voor vertrouwen. Kinderen in de pre-adolescentie hebben meer luisterende dan adviserende ouders nodig.',
    durationMin: 10,
  },
  {
    id: 'emco_10-12_438',
    skill: 'Emotiecoaching',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Tranen zijn oké, ook voor papa',
    description: 'Sta jezelf toe om emotie te tonen waar je kind bij is en normaliseer kwetsbaarheid.',
    instructions: [
      'Als je geraakt wordt door iets (een film, een herinnering, een mooi moment), probeer het niet te verbergen.',
      'Als je kind het opmerkt, wees eerlijk: "Ja, papa is een beetje ontroerd. Dit raakt me."',
      'Leg uit waarom: "Ik denk aan opa" of "Ik vind het zo mooi hoe jij dat deed."',
      'Als je kind ongemakkelijk reageert, normaliseer: "Het is gezond om te voelen. Dat geldt voor iedereen, ook voor mannen."',
    ],
    reflection: 'Hoe comfortabel ben je met het tonen van kwetsbaarheid? Waar heb je geleerd dat mannen niet mogen huilen?',
    scienceNote: 'Levant & Kopecky (1995) beschrijven "normative male alexithymia" — de culturele conditionering van mannen om emoties te onderdrukken. Onderzoek toont dat vaders die emoties tonen, zonen opvoeden met betere emotionele intelligentie.',
    durationMin: 5,
  },
  {
    id: 'gren_10-12_439',
    skill: 'Grenzen',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Grenzen uitleggen in plaats van opleggen',
    description: 'Leg de redenering achter je regels uit en nodig je kind uit om mee te denken.',
    instructions: [
      'Kies een regel waar je kind regelmatig tegenin gaat (bedtijd, schermtijd, huiswerk).',
      'In plaats van "omdat ik het zeg", leg uit: "Ik stel deze regel in omdat ik me zorgen maak om je slaap/gezondheid."',
      'Vraag: "Snap je waarom ik dit belangrijk vind? Heb jij een idee hoe we dit beter kunnen regelen?"',
      'Sta open voor aanpassingen als je kind met een goed argument komt. Laat zien dat je flexibel kunt zijn.',
    ],
    reflection: 'Hoe voelt het om controle te delen met je kind? Merk je dat uitleg meer respect oplevert dan macht?',
    scienceNote: 'Grolnick (2003) toont aan dat autonomie-ondersteunende ouders die regels uitleggen in plaats van opleggen, kinderen opvoeden met meer intrinsieke motivatie en minder verzet.',
    durationMin: 10,
  },

  // ============================================================
  // AGE GROUP 13-16 (10 tasks)
  // ============================================================
  {
    id: 'refl_13-16_440',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Eerlijk over je eigen fouten',
    description: 'Deel met je tiener een echte fout die je op hun leeftijd maakte en wat je ervan leerde.',
    instructions: [
      'Kies een fout uit je tienerjaren die relevant kan zijn: spieken, liegen, een vriend laten vallen, groepsdruk.',
      'Vertel het verhaal eerlijk, zonder het te romantiseren of te bagatelliseren.',
      'Deel wat je er destijds van voelde en wat je er nu — als volwassene — van hebt geleerd.',
      'Zeg niet "jij moet dit niet doen" maar: "Ik deel dit zodat je weet dat ik snap hoe lastig het soms is."',
    ],
    reflection: 'Hoe reageerde je tiener op je eerlijkheid? Merkte je dat authenticiteit meer impact heeft dan preken?',
    scienceNote: 'Steinberg (2001) toont aan dat adolescenten meer leren van authentieke verhalen van ouders dan van directe instructie. De ouder als "ervaringsbron" is effectiever dan de ouder als "autoriteit".',
    durationMin: 10,
  },
  {
    id: 'aanw_13-16_441',
    skill: 'Aanwezigheid',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Beschikbaar zijn zonder te controleren',
    description: 'Wees aanwezig in het leven van je tiener zonder opdringerig of controlerend te zijn.',
    instructions: [
      'Zoek "bijvangst-momenten": autorit, samen koken, een wandeling. Tieners praten makkelijker als ze niet recht tegenover je zitten.',
      'Stel open vragen zonder verborgen agenda: "Hoe gaat het eigenlijk?" en accepteer "goed" als antwoord.',
      'Deel iets van jezelf zonder iets terug te verwachten. Soms opent jouw openheid de deur.',
      'Laat je tiener weten: "Ik ben er als je me nodig hebt. Je hoeft niet te praten, maar ik luister altijd."',
    ],
    reflection: 'Hoe balanceer je betrokkenheid en ruimte geven? Merk je wanneer je tiener toenadering zoekt?',
    scienceNote: 'Allen & Manning (2007) beschrijven hoe adolescenten een "veilige basis" nodig hebben — ouders die beschikbaar zijn zonder te controleren. Dit bevordert zowel autonomie als gehechtheid.',
    durationMin: 10,
  },
  {
    id: 'emco_13-16_442',
    skill: 'Emotiecoaching',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Praten over mentale gezondheid',
    description: 'Open een gesprek over mentale gezondheid door eerst over je eigen ervaringen te praten.',
    instructions: [
      'Kies een moment waarop jullie alleen zijn en zeg: "Ik wil even over iets praten dat ik belangrijk vind."',
      'Deel je eigen ervaring: "Ik heb periodes gehad dat ik me down voelde / veel stress had / me eenzaam voelde."',
      'Normaliseer: "Dat is menselijk. Het betekent niet dat je zwak bent. Het betekent dat je hulp mag vragen."',
      'Sluit af met: "Als jij je ooit zo voelt, wil ik dat je weet dat je er niet alleen voor staat. Je kunt bij mij terecht, of bij iemand anders als dat makkelijker voelt."',
    ],
    reflection: 'Hoe comfortabel voelde dit gesprek? Mentale gezondheid bespreekbaar maken kan levens redden. Jouw openheid maakt dat mogelijk.',
    scienceNote: 'Radovic et al. (2017) tonen aan dat adolescenten die thuis over mentale gezondheid kunnen praten, eerder hulp zoeken bij problemen. Vaderlijke openheid over eigen kwetsbaarheid is hierin een sterke beschermende factor.',
    durationMin: 15,
  },
  {
    id: 'zelr_13-16_443',
    skill: 'Zelfregulatie',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Kalmte bewaren bij conflict',
    description: 'Oefen bewust om kalm te blijven tijdens een meningsverschil met je tiener.',
    instructions: [
      'Wanneer je tiener iets provocerends zegt of doet, merk dan eerst je eigen lichaamssignalen op: verhoogde hartslag, spanning in je kaak.',
      'Zeg: "Ik merk dat ik boos word. Ik wil dit gesprek goed voeren, dus ik neem even een pauze van 5 minuten."',
      'Loop weg (niet uit boosheid maar als bewuste keuze). Adem, drink water, beweeg kort.',
      'Kom terug en zeg: "Ik wil begrijpen wat je bedoelt. Kun je het nog een keer uitleggen?"',
    ],
    reflection: 'Hoe reageerde je tiener op je kalmte? Wat zou er zijn gebeurd als je direct had gereageerd vanuit boosheid?',
    scienceNote: 'Siegel (2013) beschrijft hoe de prefrontale cortex bij adolescenten nog in ontwikkeling is, waardoor zij afhankelijk zijn van de emotionele regulatie van hun ouders als co-regulatiebron.',
    durationMin: 10,
  },
  {
    id: 'gren_13-16_444',
    skill: 'Grenzen',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Eigen grenzen respecteren en modelen',
    description: 'Laat je tiener zien hoe jij op een gezonde manier grenzen stelt in je eigen leven.',
    instructions: [
      'Deel een voorbeeld uit je eigen leven waar je een grens stelde: "Ik heb tegen mijn baas gezegd dat ik niet in het weekend kan werken."',
      'Leg uit waarom: "Mijn gezinstijd is belangrijk voor me. Ik mag daar voor opkomen."',
      'Verbind het aan je tiener: "Jij mag ook grenzen stellen. Bij vrienden, online, overal."',
      'Vraag: "Is er iets in jouw leven waar je moeilijk nee tegen kunt zeggen?"',
    ],
    reflection: 'Grenzen stellen is een vaardigheid die je voorleeft. Hoe goed ben jij eigenlijk in nee zeggen?',
    scienceNote: 'Roth et al. (2009) tonen aan dat adolescenten die hun ouders gezonde grenzen zien stellen, zelf beter in staat zijn om peer pressure te weerstaan en assertief te zijn.',
    durationMin: 10,
  },
  {
    id: 'auto_13-16_445',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Je tiener om advies vragen',
    description: 'Vraag je tiener oprecht om advies over iets in jouw leven.',
    instructions: [
      'Kies iets waar je echt mee zit: een dilemma op werk, een technologische vraag, of een sociale situatie.',
      'Vraag je tiener: "Ik heb een probleem en ik zou graag jouw mening horen."',
      'Luister serieus naar het advies. Stel vervolgvragen. Behandel je tiener als een volwaardige gesprekspartner.',
      'Bedank oprecht: "Dat is een goed punt, daar had ik niet aan gedacht." En volg het advies op als het goed is.',
    ],
    reflection: 'Hoe reageerde je tiener op het gevraagd worden om advies? Wat doet het met de machtsbalans in jullie relatie?',
    scienceNote: 'Soenens & Vansteenkiste (2010) tonen aan dat het ondersteunen van de autonomie en competentie van adolescenten — ook door hen serieus te nemen — de intrinsieke motivatie en het zelfvertrouwen versterkt.',
    durationMin: 10,
  },
  {
    id: 'hers_13-16_446',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Diep herstel: afwezigheid erkennen',
    description: 'Erken periodes van emotionele of fysieke afwezigheid en begin het herstelproces.',
    instructions: [
      'Kies een rustig moment en zeg: "Ik wil eerlijk zijn over iets. Er zijn periodes geweest dat ik er niet genoeg voor je was."',
      'Wees specifiek zonder excuses: "Toen [periode/gebeurtenis] was ik te veel bezig met werk/mezelf/andere dingen."',
      'Erken de impact zonder het te minimaliseren: "Ik kan me voorstellen dat dat pijn deed of eenzaam voelde."',
      'Maak een concrete belofte: "Ik kan het verleden niet veranderen, maar ik wil er nu voor je zijn. Wat heb je nodig van mij?"',
    ],
    reflection: 'Dit is misschien het moeilijkste gesprek dat je als vader kunt voeren. Maar het is ook het begin van echt herstel.',
    scienceNote: 'Hughes & Baylin (2012) beschrijven hoe "blocked care" bij ouders kan worden hersteld door eerlijke erkenning en het heractiveren van het verzorgingssysteem. Tieners zijn bijzonder gevoelig voor de authenticiteit van dit proces.',
    durationMin: 15,
  },
  {
    id: 'verb_13-16_447',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Interesse tonen zonder te oordelen',
    description: 'Duik oprecht in de interesses van je tiener, ook als je er niets van begrijpt.',
    instructions: [
      'Vraag je tiener om je iets te laten zien van hun wereld: hun favoriete muziek, game, social media, of hobby.',
      'Luister en kijk zonder te oordelen. Stel vragen uit oprechte nieuwsgierigheid, niet om te testen.',
      'Zeg niet "dat snap ik niet" of "dat is niks", maar: "Wat vind je hier zo leuk aan?"',
      'Probeer mee te doen als je tiener dat aanbiedt, ook als je er slecht in bent. Lach om jezelf.',
    ],
    reflection: 'Hoe reageerde je tiener op je oprechte interesse? Verbinding begint bij het binnenstappen in de wereld van de ander.',
    scienceNote: 'Larson & Richards (1994) tonen aan dat adolescenten die voelen dat hun ouders oprecht geïnteresseerd zijn in hun wereld, meer openheid tonen en meer emotionele steun ervaren.',
    durationMin: 15,
  },
  {
    id: 'refl_13-16_448',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Brief aan je toekomstige zelf',
    description: 'Schrijf een brief aan jezelf over 5 jaar over de vader die je wilt zijn.',
    instructions: [
      'Neem 15 minuten en schrijf een brief aan jezelf over 5 jaar. Je kind is dan [leeftijd].',
      'Beschrijf de vader die je dan wilt zijn: hoe is je relatie met je kind? Wat doen jullie samen? Hoe voelt het?',
      'Wees eerlijk over je angsten: waar ben je bang voor? Wat zou je betreuren als je niets verandert?',
      'Sluit af met één concreet ding dat je vanaf vandaag anders gaat doen. Bewaar de brief en lees hem over een jaar terug.',
    ],
    reflection: 'Is de vader in je brief dezelfde als de vader die je nu bent? Het verschil is niet iets om je voor te schamen — het is je kompas.',
    scienceNote: 'Hershfield (2011) toont aan dat het schrijven aan je toekomstige zelf de verbinding met die toekomstige identiteit versterkt, wat leidt tot betere beslissingen in het heden — ook in de ouderrol.',
    durationMin: 15,
  },
  {
    id: 'zelr_13-16_449',
    skill: 'Zelfregulatie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Machtsstrijd vermijden',
    description: 'Herken wanneer een gesprek met je tiener een machtsstrijd wordt en stap er bewust uit.',
    instructions: [
      'Let op de signalen: stemverheffing, herhaling van argumenten, "ja maar" van beide kanten.',
      'Zeg: "Ik merk dat we allebei heel graag gelijk willen hebben. Dat helpt ons niet."',
      'Bied een alternatief: "Laten we allebei even nadenken en er vanavond/morgen op terugkomen."',
      'Reflecteer later: ging het echt om de inhoud, of om controle? Kun je loslaten zonder het gevoel te hebben dat je verliest?',
    ],
    reflection: 'Machtsstrijd winnen is de relatie verliezen. Hoe kun je je "gelijk" loslaten ten gunste van verbinding?',
    scienceNote: 'Patterson (1982) beschrijft "coercive cycles" waarbij ouder en kind elkaars negatieve gedrag versterken. Het bewust doorbreken van deze cyclus door de ouder is de effectiefste interventie.',
    durationMin: 5,
  },
];
