// Zelfregulatie – Ronde 2: 50 nieuwe interactieve taken (5 leeftijdsgroepen × 10)
import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_12: InteractiveTask[] = [

  // ─── 0-2 jaar ────────────────────────────────────────────────
  {
    id: 'zelf_02_11',
    title: 'Kalm zijn bij tantrums',
    skill: 'Zelfregulatie',
    description: 'Als je peuter een driftbui heeft: zet jezelf neer als een rots. Adem langzaam. Blijf rustig aanwezig. Laat hem de storm doormaken terwijl jij stabiel blijft.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Jouw kalmte tijdens zijn storm is de meest krachtige regulatiehulp die er is. Peuters hebben een gereguleerd zenuwstelsel naast zich nodig om hun eigen te kalmeren.',
    skillTip: 'Houd je adem regelmatig. Als jij gaat hyperventileren, gaat hij dat ook. Jouw lichaam reguleert het zijne.',
    vermijd: 'Vermijd schreeuwen terug, weglopen, of hem vasthouden als hij dat niet wil. Wees nabij maar niet dwingend.',
    leerdoel: 'Je ervaart hoe jouw eigen zelfregulatie de kern is van zijn regulatie-ondersteuning.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2011). The Whole-Brain Child.',
  },
  {
    id: 'zelf_02_12',
    title: 'Routine vasthouden onder druk',
    skill: 'Zelfregulatie',
    description: 'Houd vandaag een bedtijdroutine aan, ook als je moe bent of haast hebt. Bad, boek, bed – in die volgorde, in dat tempo. Routine is zijn zelfregulatie-steiger.',
    duration: '30 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Voorspelbare routines verlagen cortisol bij peuters en activeren het parasympathische systeem. Consistentie is letterlijk een kalmeerder voor het jonge zenuwstelsel.',
    skillTip: 'Benoem elke stap: "Nu bad, dan het boek, dan slapje." Voorspelbaarheid is de regulator.',
    vermijd: 'Vermijd de routine overslaan als het "wel goed gaat". Consistentie is de kracht, niet de uitzondering.',
    leerdoel: 'Je ervaart hoe consistente routine de zelfregulatie van je kind ondersteunt.',
    bron: 'Bowlby, J. (1988). A Secure Base.',
  },
  {
    id: 'zelf_02_13',
    title: 'Wachten modelleren',
    skill: 'Zelfregulatie',
    description: 'Zeg hardop als jij ergens op wacht of jezelf inhoudt: "Ik wil dit nu, maar ik wacht nog even." Dit modelleert uitstel van behoeftebevrediging op een zichtbare manier.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Kinderen leren zelfregulatie primair door observatie van volwassenen. Vader die zijn eigen impulsbeheersing verbaliseert, geeft een concreet model voor wachten en uitstellen.',
    skillTip: 'Gebruik het in kleine alledaagse situaties: op de oven wachten, een telefoon niet meteen pakken.',
    vermijd: 'Vermijd te geforceerd klinken. Kies echte momenten waarop je werkelijk even wacht.',
    leerdoel: 'Je modelleert impulsbeheersing door je eigen wachten hardop te verbaliseren.',
    bron: 'Mischel, W. (2014). The Marshmallow Test: Mastering Self-Control.',
  },
  {
    id: 'zelf_02_14',
    title: 'Overgangsmomenten voorbereiden',
    skill: 'Zelfregulatie',
    description: 'Kondig overgangen aan voor ze plaatsvinden: "Over vijf minuten stoppen we met spelen." Dan nogmaals bij twee minuten. Zo kan zijn zenuwstelsel zich voorbereiden.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Overgangen zijn voor peuters neurobiologische uitdagingen. Aankondigingen activeren het anticipatiesysteem en verminderen de shock van de overgang – minder cortisol, minder verzet.',
    skillTip: 'Gebruik ook visuele signalen: een timer, een kleurwisseling. Twee kanalen versterken het signaal.',
    vermijd: 'Vermijd abrupte overgangen zonder waarschuwing. "Nu stoppen" is neurobiologisch een aanval.',
    leerdoel: 'Je leert overgangen voorbereiden als preventieve zelfregulatie-ondersteuning.',
    bron: 'Porges, S.W. (2011). The Polyvagal Theory.',
  },
  {
    id: 'zelf_02_15',
    title: 'Zelfregulatie via sensorische input',
    skill: 'Zelfregulatie',
    description: 'Geef je opgewonden of geprikkelde peuter sensorische input om te kalmeren: stevige knuffel (deep pressure), langzaam wiegen, of rustig water. Observeer wat werkt voor hem.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Sensorische input activeert het proprioceptieve systeem en kalmeert het zenuwstelsel direct. Elk kind heeft een persoonlijk sensorisch profiel – leer dat van jouw kind kennen.',
    skillTip: 'Probeer verschillende inputs uit in rustige momenten. Dan weet je wat werkt als het nodig is.',
    vermijd: 'Vermijd te veel stimuli geven als hij overprikkeld is. Minder input, niet meer.',
    leerdoel: 'Je leert jouw kind\'s persoonlijke sensorische kalmeerstrategieën kennen.',
    bron: 'Ayres, A.J. (1979). Sensory Integration and the Child.',
  },
  {
    id: 'zelf_02_16',
    title: 'Pauze nemen als je aan het einde bent',
    skill: 'Zelfregulatie',
    description: 'Als je merkt dat je door alle vermoeidheid aan het einde van je geduld zit: neem een korte pauze. Leg je baby veilig neer. Stap even weg. Adem. Kom terug.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'De capaciteit om pauze te nemen als je regulatiegrens bereikt is een krachtige zelfregulatieskill. Het is veiliger dan doorgaan op de rand van verlies van controle.',
    skillTip: 'Zeg hardop: "Ik ga even kalmeren, dan kom ik terug." Dat modelleert ook voor je kind (als hij iets begrijpt).',
    vermijd: 'Vermijd te lang wegblijven. Een pauze is 2-5 minuten, geen vlucht.',
    leerdoel: 'Je leert pauze nemen als zelfregulatieactie bij extreme vermoeidheid.',
    bron: 'Neff, K. (2011). Self-Compassion: The Proven Power of Being Kind to Yourself.',
  },
  {
    id: 'zelf_02_17',
    title: 'Ritueel voor de slaap',
    skill: 'Zelfregulatie',
    description: 'Creëer een vaste volgorde voor bedtijd die altijd hetzelfde is: drie stappen, in dezelfde volgorde, op dezelfde toon. Houd dit elke avond aan.',
    duration: '15 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Vaste bedtijdrituelen activeren het parasympathische zenuwstelsel via voorspelbaarheid. Kinderen die vaste rituelen hebben, vallen sneller in slaap en slapen beter.',
    skillTip: 'Houd het simpel: bad, lied, neerlegen. Complexiteit werkt averechts bij moe zijn.',
    vermijd: 'Vermijd rituelen die hem activeren (wild spelen voor bed). Kalmerend is het criterium.',
    leerdoel: 'Je bouwt een regulerend bedtijdritueel dat via voorspelbaarheid kalmeert.',
    bron: 'Mindell, J.A. & Williamson, A.A. (2018). Benefits of a bedtime routine in young children.',
  },
  {
    id: 'zelf_02_18',
    title: 'Je eigen irritatie observeren',
    skill: 'Zelfregulatie',
    description: 'Let vandaag op het moment dat je geïrriteerd raakt door je kind. Benoem het intern: "Ik ben nu geïrriteerd." Observeer het, reageer er niet direct op. Kies dan bewust.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Observeren van eigen irritatie voor je erop reageert is een kernvaardigheid van emotieregulatie. De ruimte tussen prikkel en respons is de locatie van bewuste keuze.',
    skillTip: 'Gebruik een mentale pauzeknop: "Ik zie dat ik irritatie voel." Dat geeft al afstand.',
    vermijd: 'Vermijd jezelf veroordelen voor de irritatie. Het gevoel is normaal – de keuze in de respons is wat telt.',
    leerdoel: 'Je vergroot de ruimte tussen prikkel en reactie via bewuste observatie.',
    bron: 'Frankl, V. (1946). Man\'s Search for Meaning.',
  },
  {
    id: 'zelf_02_19',
    title: 'Ademhaling als ankerpunt',
    skill: 'Zelfregulatie',
    description: 'Oefen vandaag één keer bewust: houd je kind vast en concentreer je volledig op je eigen ademhaling gedurende vijf ademhalingen. Merk op hoe dat zijn toestand beïnvloedt.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Ademhaling is de snelste weg naar het parasympathische zenuwstelsel. Vijf bewuste ademhalingen verlagen aantoonbaar het cortisolniveau en verbeteren de responsiviteit.',
    skillTip: 'Langere uitademing dan inademing (4 tellen in, 6 tellen uit) activeert het vagotonische systeem het sterkst.',
    vermijd: 'Vermijd hyperventileren of forceren. Rustige, gewone ademhaling verlengd is al genoeg.',
    leerdoel: 'Je gebruikt ademhaling als snelle zelfregulatietool in de verzorging.',
    bron: 'Porges, S.W. (2011). The Polyvagal Theory.',
  },
  {
    id: 'zelf_02_20',
    title: 'Overprikkeling herkennen',
    skill: 'Zelfregulatie',
    description: 'Leer de signalen van overprikkeling bij je baby kennen: blikwegdraaien, huilen met hoge toon, handen voor gezicht. Stop dan met stimuleren en geef rust.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Overprikkeling is het vroegste zelfregulatie-signaal van baby\'s. Vader die dit herkent en respecteert leert het kind dat grenzen gerespecteerd worden – de basis van lichaamsbewustzijn.',
    skillTip: 'Stop alle stimulering, verlaag licht en geluid, houd rustig vast of leg zachtjes neer. Geef tijd.',
    vermijd: 'Vermijd meer stimuli toevoegen ("kijk, hier, wat is dit?"). Overprikkeling vraagt om afname van input.',
    leerdoel: 'Je leert de grens tussen stimulering en overprikkeling herkennen en respecteren.',
    bron: 'Brazelton, T.B. & Cramer, B.G. (1990). The Earliest Relationship.',
  },

  // ─── 3-5 jaar ────────────────────────────────────────────────
  {
    id: 'zelf_35_11',
    title: 'Turtle-techniek uitleggen',
    skill: 'Zelfregulatie',
    description: 'Leer je peuter de "schildpad": als je boos wordt, trek je je "schild" in (armen om je lijf), tel tot drie, dan kom je weer tevoorschijn. Doe het samen na.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'De turtle-techniek is een bewezen zelfregulatiestrategie voor jonge kinderen. Beweging (naar binnen trekken) koppelen aan kalmeren geeft een belichaamd anker voor de techniek.',
    skillTip: 'Maak het een spel in rustige momenten. Dan is het beschikbaar als het echt nodig is.',
    vermijd: 'Vermijd het forceren in de hitte van de emotie. Oefen altijd eerst in kalme situaties.',
    leerdoel: 'Je geeft je kind een belichaamde zelfregulatiestrategie.',
    bron: 'Webster-Stratton, C. (1990). Enhancing the effectiveness of self-administered videotape parent training for families with conduct-problem children.',
  },
  {
    id: 'zelf_35_12',
    title: 'Zijn wachtcapaciteit trainen',
    skill: 'Zelfregulatie',
    description: 'Vraag je kind bewust te wachten op iets kleins: zijn koek terwijl jij eerst water pakt, of starten met spelen terwijl jij even een sms beantwoordt. Erken daarna zijn wachten.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Impulsbeheersing is een spier die getraind kan worden. Kleine, dagelijkse wachtoefeningen vergroot de wachtcapaciteit van peuters significant over tijd.',
    skillTip: 'Maak het wachten concreet: "Ik tel tot tien, dan is het er." Concreet wachten is makkelijker dan abstract.',
    vermijd: 'Vermijd te lang laten wachten. Begin met 30 seconden en bouw langzaam op.',
    leerdoel: 'Je traint impulsbeheersing via kleine, dagelijkse wachtoefeningen.',
    bron: 'Mischel, W. (2014). The Marshmallow Test: Mastering Self-Control.',
  },
  {
    id: 'zelf_35_13',
    title: 'Rustig-hoekje inrichten',
    skill: 'Zelfregulatie',
    description: 'Maak samen een "rustig hoekje" in huis: een plek met een kussen, een knuffel, eventueel een boekje. Zeg: "Als je je heel boos of verdrietig voelt, mag je hier naartoe gaan."',
    duration: '20 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Een fysieke plek voor kalmeren geeft kinderen ruimtelijke controle over hun regulatieproces. Het is geen straf maar een hulpbron – een veilig kalmeer-anker.',
    skillTip: 'Laat hem de plek inrichten. Zijn eigenaarschap over het hoekje vergroot de bereidheid om het te gebruiken.',
    vermijd: 'Vermijd het "rustig hoekje" verwarren met time-out als straf. Het is altijd vrijwillig.',
    leerdoel: 'Je geeft je kind een fysieke zelfregulatiebron die hij zelf kan initiëren.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2014). No-Drama Discipline.',
  },
  {
    id: 'zelf_35_14',
    title: 'Zijn emotie beschrijven als weer',
    skill: 'Zelfregulatie',
    description: 'Vraag je kind: "Als jouw gevoel nu het weer was, welk weer zou het dan zijn?" Stormachtig? Zonnig? Bewolkt? Praat erover. Teken het eventueel.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Metaforen geven kinderen afstand van hun intense gevoelens. Het weer vergelijken maakt emoties concreter en makkelijker te communiceren en te observeren.',
    skillTip: 'Vraag ook: "Wat voor weer wil jij dat het wordt?" Dat introduceert regulatiedoelen op een speelse manier.',
    vermijd: 'Vermijd het weer als oordeel te gebruiken ("stormachtig is fout"). Alle soorten weer zijn normaal.',
    leerdoel: 'Je geeft je kind een emotie-metafoor die zelfobservatie vergroot.',
    bron: 'Siegel, D.J. (2010). Mindsight.',
  },
  {
    id: 'zelf_35_15',
    title: 'Zin uitstellen via tellen',
    skill: 'Zelfregulatie',
    description: 'Oefen samen met je kind het tellen tot vijf voor hij iets pakt, iemand aanraakt of iets gooit. Maak het een spelletje. Tel samen hardop. Beloon het wachten.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Tellen is een concrete, belichaamde stopzetting van impuls. Het geeft de prefrontale cortex tijd om het limbisch systeem te reguleren – zelfs bij jonge kinderen.',
    skillTip: 'Gebruik je vingers om te tellen – dat maakt het visueel en makkelijker te onthouden.',
    vermijd: 'Vermijd het tellen als straf of dreigement. Doe het altijd samen, speels.',
    leerdoel: 'Je geeft je kind een concrete impulsremmingsstrategie via tellen.',
    bron: 'Diamond, A. (2013). Executive Functions. Annual Review of Psychology.',
  },
  {
    id: 'zelf_35_16',
    title: 'Gevoels-thermometer gebruiken',
    skill: 'Zelfregulatie',
    description: 'Gebruik een (eerder gemaakte of nieuwe) emotie-thermometer samen. Vraag je kind dagelijks: "Waar zit je nu op de thermometer?" Help hem woorden te koppelen aan het niveau.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Regelmatig gebruik van een emotie-thermometer vergroot de emotionele geletterdheid en het vermogen tot vroege interventie – het kind leert zijn toestand te monitoren.',
    skillTip: 'Doe het ook voor jezelf. "Ik zit nu op een 2 (rustig). En jij?" Modelleert het gebruik.',
    vermijd: 'Vermijd het alleen te gebruiken als er al problemen zijn. Dagelijks gebruik normaliseert het.',
    leerdoel: 'Je vergroot dagelijks bewustzijn van emotionele toestand als zelfregulatiebasis.',
    bron: 'Greenberg, M.T. (2006). Promoting resilience in children and youth.',
  },
  {
    id: 'zelf_35_17',
    title: 'Frustratie-script instuderen',
    skill: 'Zelfregulatie',
    description: 'Oefen in een rustig moment een vaste zin die je kind kan gebruiken als hij gefrustreerd raakt: "Ik ben boos en ik wil dit zelf doen." Herhaal het samen drie keer.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Vooraf gerepeteerde scripts ("implementation intentions") activeren automatisch tijdens stressvolle situaties, ook als de prefrontale cortex al gedeeltelijk offline is.',
    skillTip: 'Kies een zin die bij hem past. Laat hem mee bepalen welke woorden hij gebruikt.',
    vermijd: 'Vermijd het instuderen tijdens een conflict. Altijd in rustige momenten.',
    leerdoel: 'Je geeft je kind een vooraf ingeoefend verbaal regulatiescript.',
    bron: 'Gollwitzer, P.M. (1999). Implementation intentions: Strong effects of simple plans.',
  },
  {
    id: 'zelf_35_18',
    title: 'Succesvol wachten vieren',
    skill: 'Zelfregulatie',
    description: 'Als je kind succesvol wacht, iets uitstelt, of zijn boosheid goed hanteert: vier dat. Niet overdreven – maar bewust erkennen: "Dat deed je goed. Je wachtte." Specifiek.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Positieve bekrachtiging van zelfregulatie vergroot de kans dat het herhaald wordt. Kinderen leren wat benoemd en gewaardeerd wordt door de mensen die ze liefhebben.',
    skillTip: 'Wees specifiek: "Je werd boos maar je sloeg niet. Je gebruikte woorden. Dat is moeilijk en je deed het."',
    vermijd: 'Vermijd algemene lof: "Goed gedaan!" Dat heeft minder effect dan specifieke erkenning.',
    leerdoel: 'Je versterkt zelfregulatie via gerichte positieve bekrachtiging.',
    bron: 'Dweck, C. (2006). Mindset: The New Psychology of Success.',
  },
  {
    id: 'zelf_35_19',
    title: 'Zijn hersenstorm uitleggen',
    skill: 'Zelfregulatie',
    description: 'Vertel je kind op zijn niveau over de "boze hersenen": als we heel boos zijn, doet ons denkhoofd even mee niet. "Dan helpt het om te stoppen en te ademen." Maak het simpel.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kinderen die begrijpen waarom ze moeite hebben met kalmeren, schamen zich minder en kunnen hun eigen processen beter waarnemen. Psycho-educatie verlaagt de drempel voor regulatie.',
    skillTip: 'Gebruik een eenvoudige metafoor: "Je denkhoofd gaat op vakantie als je heel boos bent. Dan moet je wachten tot hij terug is."',
    vermijd: 'Vermijd te technische uitleg. Simpel is beter dan correct.',
    leerdoel: 'Je vergroot zijn begrip van zijn eigen emotionele processen via passende psycho-educatie.',
    bron: 'Siegel, D.J. (2010). Mindsight.',
  },
  {
    id: 'zelf_35_20',
    title: 'Samen buiten energie kwijt',
    skill: 'Zelfregulatie',
    description: 'Als je kind overbezorgd, overprikkeld, of te opgespannen is: ga buiten bewegen. Rennen, springen, klauteren. Lichamelijke uitval vermindert emotionele spanning.',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Fysieke activiteit reguleert het zenuwstelsel via beweging en proprioceptie. Kinderen die kunnen bewegen, kalmeren sneller dan kinderen die stil moeten zitten.',
    skillTip: 'Doe mee. Ren samen. Dat maakt het leuker en versterkt de regulatie via co-beweging.',
    vermijd: 'Vermijd structurele activiteiten met regels. Vrij bewegen werkt sneller voor regulatie.',
    leerdoel: 'Je leert beweging als directe zelfregulatietool voor jonge kinderen inzetten.',
    bron: 'Ratey, J.J. (2008). Spark: The Revolutionary New Science of Exercise and the Brain.',
  },

  // ─── 6-9 jaar ────────────────────────────────────────────────
  {
    id: 'zelf_69_11',
    title: 'Impulsbeheersing bij schermen',
    skill: 'Zelfregulatie',
    description: 'Bespreek samen regels rondom schermen. Laat hem meebepalen: "Wanneer stop je? Hoe weet je dat?" Help hem zijn eigen grens te formuleren en te bewaken.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kinderen die hun eigen schermregels mede formuleren, houden zich er significant beter aan dan kinderen die regels opgelegd krijgen. Eigenaarschap vergroot zelfregulatie.',
    skillTip: 'Vraag: "Hoe voel je je als je gestopt bent na te veel schermtijd?" Dat maakt de consequentie voelbaar.',
    vermijd: 'Vermijd alleen de regel opleggen. Het gesprek erover is het meest educatief.',
    leerdoel: 'Je bevordert eigenaarschap over zelfregulatie via medeformulering van grenzen.',
    bron: 'Deci, E.L. & Ryan, R.M. (1985). Intrinsic Motivation and Self-Determination.',
  },
  {
    id: 'zelf_69_12',
    title: 'Cognitieve afstand nemen',
    skill: 'Zelfregulatie',
    description: 'Leer je kind: "Als je heel boos of verdrietig bent, probeer dan te kijken als een vliegje op de muur. Wat zie je dan?" Oefen dit samen met een scenario.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Cognitieve distantiëring (self-distancing) is een bewezen regulatiestrategie die kinderen in staat stelt emotionele intensiteit te verminderen via perspectiefsverandering.',
    skillTip: 'Gebruik ook de naamsvorm: "Stel dat jij je vriend was en hij vertelde je dit – wat zou je dan denken?" Naam of derde persoon helpt.',
    vermijd: 'Vermijd dit te gebruiken om zijn gevoel te minimaliseren. Het gaat om perspectief, niet om minimalisering.',
    leerdoel: 'Je geeft je kind cognitieve distantiëring als een concrete regulatiestrategie.',
    bron: 'Kross, E. & Ayduk, O. (2011). Making meaning out of negative experiences by self-distancing.',
  },
  {
    id: 'zelf_69_13',
    title: 'Plan B voorbereiden',
    skill: 'Zelfregulatie',
    description: 'Bespreek voor een moeilijke situatie (toets, sociale situatie): "Wat doe je als het moeilijk wordt? Wat is jouw plan B?" Help hem strategieën te formuleren voor hij ze nodig heeft.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Proactieve copingstrategieën verminderen de stress in de situatie zelf. Als hij al een plan heeft, hoeft de prefrontale cortex minder werk te doen in het moment.',
    skillTip: 'Stel concrete vragen: "Als je blokkeert bij de toets, wat doe je dan?" Specifiek plan is beter dan vaag voornemen.',
    vermijd: 'Vermijd het voor hem invullen. Het is zijn plan, niet het jouwe.',
    leerdoel: 'Je leert proactieve copingstrategieën formuleren als preventieve zelfregulatie.',
    bron: 'Lazarus, R.S. & Folkman, S. (1984). Stress, Appraisal, and Coping.',
  },
  {
    id: 'zelf_69_14',
    title: 'Zijn oplaadmoment kennen',
    skill: 'Zelfregulatie',
    description: 'Bespreek: "Wat geeft jou energie na een drukke dag?" Maak een lijst. Zorg dat er elke dag minstens één oplaadmoment in zit dat hij kiest.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Bewustzijn van persoonlijke herstelactiviteiten vergroot zelfzorg en voorkomt uitputting. Kinderen die weten wat hen oplaadt, kunnen proactief voor zichzelf zorgen.',
    skillTip: 'Onderscheid: opladen via rust (alleen zijn, lezen) versus opladen via contact (spelen, praten). Beide zijn geldig.',
    vermijd: 'Vermijd zijn oplaadmoment bepalen. Het is altijd zijn persoonlijke keuze.',
    leerdoel: 'Je vergroot zijn zelfkennis over herstel en energie als zelfregulatiebasis.',
    bron: 'Ryan, R.M. & Deci, E.L. (2001). On happiness and human potentials.',
  },
  {
    id: 'zelf_69_15',
    title: 'Stopwoord afspreken',
    skill: 'Zelfregulatie',
    description: 'Spreek met je kind een stopwoord af dat jullie allebei kunnen gebruiken als een gesprek of situatie te heet wordt: "Als ik [stopwoord] zeg, pauzen we even." Oefen het.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Een stopwoord geeft beide partijen een exit-strategie zonder gezichtsverlies. Het activeert de prefrontale cortex via de actie van het woord zeggen.',
    skillTip: 'Maak het woord grappig of onverwacht. Dat verlaagt de spanning op het moment van gebruik.',
    vermijd: 'Vermijd een stopwoord dat lui als aanval. "Rustig" of "stop" kan als kritiek overkomen. Kies iets neutruums.',
    leerdoel: 'Je introduceert een gedeeld escalatie-stopmechanisme voor moeilijke momenten.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2014). No-Drama Discipline.',
  },
  {
    id: 'zelf_69_16',
    title: 'Zelfregulatie na school',
    skill: 'Zelfregulatie',
    description: 'Geef je kind na school 15-20 minuten vrije decompressietijd voor er van hem gevraagd wordt. Geen vragen, geen huiswerk. Eerst landen. Dan pas contact.',
    duration: '20 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Kinderen hebben na school decompressietijd nodig om het cortisolpeil te verlagen. Sociale interactie of huiswerk onmiddellijk na school vergroot de stress-respons.',
    skillTip: 'Maak dit een vaste routine die hij verwacht. "Eerst 20 minuten jouw tijd, dan samen." Dat geeft zekerheid.',
    vermijd: 'Vermijd direct vragen hoe school was. Dat is aanraking terwijl hij nog moet landen.',
    leerdoel: 'Je respecteert zijn regulatiebehoefte na school als preventieve strategie.',
    bron: 'Repetti, R.L. (1994). Short-term and long-term processes linking job stressors to father-child interaction.',
  },
  {
    id: 'zelf_69_17',
    title: 'Emotie-surfing uitleggen',
    skill: 'Zelfregulatie',
    description: 'Vertel je kind: "Emoties zijn als golven – ze komen op, worden groter, en gaan dan vanzelf voorbij. Je hoeft er niet in te verdrinken. Je kunt er op surfen."',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Het "emotie-surfing" concept (urge surfing) leert kinderen dat emoties tijdelijk zijn en dat ze er getuige van kunnen zijn zonder erdoor meegesleurd te worden.',
    skillTip: 'Vraag hem hoe lang een golf duurt. "Heel lang? Of eigenlijk best snel voorbij?" Dat vergroot het inzicht.',
    vermijd: 'Vermijd de metafoor gebruiken om emoties te vermijden. Surfen is erbij blijven, niet weglopen.',
    leerdoel: 'Je geeft je kind het inzicht dat emoties tijdelijk zijn en observeerbaar.',
    bron: 'Kabat-Zinn, J. (1990). Full Catastrophe Living.',
  },
  {
    id: 'zelf_69_18',
    title: 'Zijn woede productief maken',
    skill: 'Zelfregulatie',
    description: 'Als je kind boos is, geef hem een productieve uitlaat: rennen, een kussen slaan, tekenen, schrijven. Bespreek daarna wat het deed. "Hoe voel je je nu?"',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Fysieke expressie van emotie helpt de neurotransmitterbalans te herstellen. Productieve uitlaten zijn effectiever dan verbale regulatie als de emotie hoog is.',
    skillTip: 'Laat hem zelf kiezen wat voor hem werkt. Elk kind heeft een ander voorkeurskanaal.',
    vermijd: 'Vermijd gewelddadige uitlaten als slaan tegen mensen. Richten op objecten of beweging is het doel.',
    leerdoel: 'Je helpt je kind persoonlijke, productieve uitlaatkleppen voor emotionele energie te vinden.',
    bron: 'Ratey, J.J. (2008). Spark: The Revolutionary New Science of Exercise and the Brain.',
  },
  {
    id: 'zelf_69_19',
    title: 'Nacht-ritual voor kalmte',
    skill: 'Zelfregulatie',
    description: 'Bouw samen een korte avondmeditatie of kalmeeroefening in voor het slapengaan: drie dingen die goed gingen, drie ademhalingen, één positieve gedachte over morgen.',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Een avondritueel van positieve reflectie en ademhaling activeert het parasympathische systeem, vermindert piekeren en verbetert de slaapkwaliteit significant.',
    skillTip: 'Doe het samen. Jouw deelname verhoogt de kans dat hij het volhoudt en normaliseert de praktijk.',
    vermijd: 'Vermijd het verplicht maken. Als hij het niet wil, sla dan over. Vrijwilligheid vergroot effectiviteit.',
    leerdoel: 'Je bouwt een dagelijks avondritueel voor emotionele verwerking en kalmte.',
    bron: 'Seligman, M.E.P. (2011). Flourish.',
  },
  {
    id: 'zelf_69_20',
    title: 'Fout toegeven – modelleren',
    skill: 'Zelfregulatie',
    description: 'De volgende keer dat jij te snel of te hard reageerde: zeg het tegen hem. "Ik reageerde te snel net. Dat was niet goed van me. Ik ga het anders proberen." Modelleer corrigeren.',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Vader die zijn eigen gebrek aan zelfregulatie erkent en corrigeert, toont dat: (1) iedereen fouten maakt, (2) je kunt ze herstellen, (3) zelfregulatie een vaardigheid is, geen eigenschap.',
    skillTip: 'Zeg precies wat je anders had willen doen. Concreet model is beter dan vaag excuus.',
    vermijd: 'Vermijd je excuus half-bewust maken zodat hij je vergeven moet. Doe het om hem iets te leren, niet voor jezelf.',
    leerdoel: 'Je modelleert zelfcorrectie na mislukte regulatie als normale en waardevolle respons.',
    bron: 'Schön, D.A. (1983). The Reflective Practitioner.',
  },

  // ─── 10-12 jaar ──────────────────────────────────────────────
  {
    id: 'zelf_1012_11',
    title: 'Schermen en slaap bespreken',
    skill: 'Zelfregulatie',
    description: 'Bespreek met je kind de relatie tussen schermgebruik voor bed en slaapkwaliteit. Laat hem zelf een experiment uitdenken: "Wat ga jij proberen en hoe merk je het verschil?"',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Blauw licht van schermen onderdrukt melatonine. Kinderen die dit begrijpen en er zelf een experiment over opzetten, vergroten hun intrinsieke motivatie voor schermhygiëne.',
    skillTip: 'Stel voor: "Probeer het 3 dagen en vertel me dan hoe je slaapt." Experiment is meer motiverend dan regel.',
    vermijd: 'Vermijd de regel opleggen. Maak het zijn experiment, zijn keuze.',
    leerdoel: 'Je vergroot zijn begrip van de slaap-scherm relatie en stimuleert zelfregie.',
    bron: 'Walker, M. (2017). Why We Sleep.',
  },
  {
    id: 'zelf_1012_12',
    title: 'Stress-management bespreekbaar maken',
    skill: 'Zelfregulatie',
    description: 'Bespreek: "Wat doe jij als je gestrest bent? Wat helpt?" Maak een lijst van zijn strategieën. Vraag daarna welke het meest helpt en waarom.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Reflectie op eigen copingstrategieën vergroot het metacognitieve bewustzijn en de effectiviteit van die strategieën. Kinderen die hun eigen aanpak kennen, zijn weerbaarder.',
    skillTip: 'Deel ook jouw stressmanagementstrategieën. Gelijkwaardigheid in het gesprek vergroot zijn openheid.',
    vermijd: 'Vermijd zijn strategieën evalueren. Dit is verkennen, niet beoordelen.',
    leerdoel: 'Je vergroot zijn kennis van en vertrouwen in zijn eigen copingstrategieën.',
    bron: 'Lazarus, R.S. & Folkman, S. (1984). Stress, Appraisal, and Coping.',
  },
  {
    id: 'zelf_1012_13',
    title: 'Omgaan met perfectionisme',
    skill: 'Zelfregulatie',
    description: 'Als je kind te hoge eisen aan zichzelf stelt of erg teleurgesteld is bij fouten: bespreek het. "Goed genoeg is ook genoeg. Perfectie bestaat niet." Geef een eigen voorbeeld.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Perfectionisme is een regulatierisico: het verhoogt cortisol chronisch en is geassocieerd met angst en burn-out. Vroeg herkennen en relativeren is preventief.',
    skillTip: 'Vraag: "Wat zou je zeggen tegen je beste vriend als hij dit maakte?" Dat activeert zelfcompassie.',
    vermijd: 'Vermijd "lekker makkelijk doen" als boodschap. Ambitie is mooi – perfectionisme is de valkuil.',
    leerdoel: 'Je herkent perfectionisme als regulatierisico en helpt hem zelfcompassie te ontwikkelen.',
    bron: 'Neff, K. (2011). Self-Compassion.',
  },
  {
    id: 'zelf_1012_14',
    title: 'Procrастinatie aanpakken',
    skill: 'Zelfregulatie',
    description: 'Als je kind iets uitstelt: vraag eerst waarom, dan pas samen kijken naar de eerste heel kleine stap. "Wat is het allerkleinste dat je kunt doen om te beginnen?"',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Uitstelgedrag is een regulatieprobleem: het kind vermijdt ongemak. De oplossing is de drempel verlagen via de kleinst mogelijke eerste stap die het ongemak draaglijker maakt.',
    skillTip: 'Maak de stap belachelijk klein. "Schrijf alleen jouw naam op het papier." Starten is de moeilijkste stap.',
    vermijd: 'Vermijd te duwen of te straffen. Begrijp eerst de vermijdingsreden.',
    leerdoel: 'Je helpt uitstelgedrag aan te pakken door de drempel te verlagen via mini-stappen.',
    bron: 'Steel, P. (2007). The Nature of Procrastination. Psychological Bulletin.',
  },
  {
    id: 'zelf_1012_15',
    title: 'Energie-budgettering leren',
    skill: 'Zelfregulatie',
    description: 'Bespreek met je kind dat energie eindig is, net als geld. "Hoeveel energie heb je vandaag? Waarvoor gebruik je het? Wat houdt er ook voor jou over?" Plan samen een dag.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Ego-depletion onderzoek toont dat zelfregulatie een beperkte resource is. Kinderen die dit begrijpen, leren proactief met hun energiereserves om te gaan.',
    skillTip: 'Gebruik een concreet metafoor: "Je hebt 10 energiepunten per dag. Wat kost hoeveel?" Maak het zichtbaar.',
    vermijd: 'Vermijd dit gebruiken als excuus. Begrip van limiet is een aanleiding voor slimmer plannen, niet minder doen.',
    leerdoel: 'Je vergroot zijn bewustzijn van energie als beperkte resource en hoe hij die verstandig inzet.',
    bron: 'Baumeister, R.F. et al. (1998). Ego depletion: Is the active self a limited resource?',
  },
  {
    id: 'zelf_1012_16',
    title: 'Cognitief herkaderen oefenen',
    skill: 'Zelfregulatie',
    description: 'Neem een negatieve gedachte van je kind ("ik ben slecht in wiskunde"). Leer hem ze te herkaderen: "Ik ben nog aan het leren met wiskunde." Probeer het samen op meerdere situaties.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Cognitief herkaderen is een van de best gedocumenteerde methoden voor emotieregulatie. Het "growth mindset" principe is direct gebaseerd op dit mechanisme.',
    skillTip: 'Voeg "nog" toe aan negatieve gedachten. "Ik kan dit niet" → "Ik kan dit nog niet." Eén woord verandert alles.',
    vermijd: 'Vermijd geforceerde positiviteit. "Ik ga dit supergeweldig doen!" is niet geloofwaardig.',
    leerdoel: 'Je introduceert cognitief herkaderen als concrete regulatiestrategie voor negatieve gedachten.',
    bron: 'Dweck, C. (2006). Mindset: The New Psychology of Success.',
  },
  {
    id: 'zelf_1012_17',
    title: 'Conflictescalatie doorbreken',
    skill: 'Zelfregulatie',
    description: 'Bespreek met je kind escalatiepatronen: "Hoe begint een ruzie? Wat maakt het groter? Wat zou je eerder kunnen doen om het klein te houden?" Reflecteer samen.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Bewustzijn van escalatiepatronen vergroot de mogelijkheid tot vroege interventie. Kinderen die hun eigen escalatiestijl kennen, kunnen eerder deëscaleren.',
    skillTip: 'Bespreek je eigen escalatiepatroon ook eerlijk. Dat vergroot zijn veiligheid om zijn eigen te delen.',
    vermijd: 'Vermijd dit als aanklacht ("jij escaleert altijd"). Gebruik "we" taal over patronen.',
    leerdoel: 'Je vergroot zijn bewustzijn van escalatiemechanismen en mogelijkheden voor vroege deëscalatie.',
    bron: 'Gottman, J. (1994). Why Marriages Succeed or Fail.',
  },
  {
    id: 'zelf_1012_18',
    title: 'Zijn "window of tolerance" kennen',
    skill: 'Zelfregulatie',
    description: 'Leg je kind uit: er is een zone waarin je goed kunt nadenken en keuzes maken. Buiten die zone (te opgewonden of te leeg) lukt dat niet. "Wat helpt jou om in die zone te blijven?"',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Het "window of tolerance" concept (Siegel) helpt kinderen begrijpen wanneer regulatie nodig is en waarvoor. Kennis van persoonlijke regulatie-grenzen vergroot de zelfmanagement.',
    skillTip: 'Maak het visueel: teken de drie zones (te weinig, goed, te veel). Vraag: "Waar ben jij nu?"',
    vermijd: 'Vermijd te technisch worden. Het concept uitleggen is genoeg – diepgaande theorie is niet nodig.',
    leerdoel: 'Je geeft je kind het concept van window of tolerance als zelfmanagementinstrument.',
    bron: 'Siegel, D.J. (2010). Mindsight.',
  },
  {
    id: 'zelf_1012_19',
    title: 'Zelfzorg als regulator',
    skill: 'Zelfregulatie',
    description: 'Bespreek met je kind: wat doe jij voor jezelf? Slaap, eten, bewegen, vriendentijd? Vertel hoe jij voor jezelf zorgt en vraag hem hoe hij dat doet.',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Zelfzorg is de fysiologische basis van zelfregulatie. Kinderen die goed slapen, bewegen en eten, zijn aantoonbaar beter in staat tot emotionele regulatie.',
    skillTip: 'Modelleer: "Ik merk dat als ik slecht slaap, ik minder geduldig ben." Concreet verbinden maakt het reëel.',
    vermijd: 'Vermijd de lijst als verplichtingen opleggen. Dit is bewustwording, geen regelgeving.',
    leerdoel: 'Je vergroot zijn begrip van zelfzorg als basis voor emotionele regulatiecapaciteit.',
    bron: 'Maslow, A. (1943). A Theory of Human Motivation.',
  },
  {
    id: 'zelf_1012_20',
    title: 'Impulsen vertragen via vragen',
    skill: 'Zelfregulatie',
    description: 'Leer je kind drie vragen die hij zichzelf kan stellen voor hij iets doet of stuurt: "Wil ik dit echt? Hoe voel ik me hier morgen over? Wat zou [name] doen?" Oefen samen.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Socratische zelfreflectie-vragen activeren de prefrontale cortex en vertragen impulsief gedrag. Drie vragen geven genoeg pauze voor bewuste keuze.',
    skillTip: 'Pas de derde vraag aan: gebruik iemand die hij bewondert en die hij goed kent.',
    vermijd: 'Vermijd de vragen opleggen in het moment. Oefen ze in rustige situaties zodat ze beschikbaar zijn.',
    leerdoel: 'Je geeft je kind een intern zelfreflectie-protocol voor impulsbeheersing.',
    bron: 'Diamond, A. (2013). Executive Functions.',
  },

  // ─── 13-16 jaar ──────────────────────────────────────────────
  {
    id: 'zelf_1316_11',
    title: 'Prefrontale cortex uitleggen',
    skill: 'Zelfregulatie',
    description: 'Leg je tiener uit dat de prefrontale cortex – het "denkende brein" – pas rond het 25e jaar volledig ontwikkeld is. "Dat verklaart waarom impulsbeheersing voor jou harder werken is dan voor mij."',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Begrip van de neurologische ontwikkeling vermindert schaamte over impulsiviteit bij tieners en moedigt hen aan om externe structuren en strategieën te gebruiken als hulp.',
    skillTip: 'Gebruik een toegankelijk beeld: "Je gaspedaal (amygdala) is bijna volwassen. Je rem (prefrontale cortex) is dat nog niet."',
    vermijd: 'Vermijd dit als excuus te gebruiken voor impulsief gedrag. Uitleg, niet rechtvaardiging.',
    leerdoel: 'Je vergroot zijn begrip van zijn neurobiologische toestand als basis voor zelfbegrip.',
    bron: 'Siegel, D.J. (2013). Brainstorm: The Power and Purpose of the Teenage Brain.',
  },
  {
    id: 'zelf_1316_12',
    title: 'Digitale impulsbeheersing',
    skill: 'Zelfregulatie',
    description: 'Bespreek met je tiener: voor hij iets post, stuurt, of reageert op sociale media – heeft hij een pauzegewoonte? Bespreek wat voor hem werkt als reminder om even te wachten.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Digitale impulsbeheersing is een cruciale moderne vaardigheid. Tieners die een "pauze-gewoonte" ontwikkelen voor online reacties, ervaren minder sociale conflicten en spijt.',
    skillTip: 'Spreek af: de "24-uur regel" voor gevoelige berichten – schrijf, bewaar, versuur de volgende dag als het nog logisch voelt.',
    vermijd: 'Vermijd de discussie over specifieke situaties uit het verleden. Bespreek strategieën voor de toekomst.',
    leerdoel: 'Je helpt je tiener een digitale pauzegewoonte te ontwikkelen als zelfregulatiestrategie.',
    bron: 'Twenge, J.M. (2017). iGen: Why Today\'s Super-Connected Kids Are Growing Up Less Rebellious.',
  },
  {
    id: 'zelf_1316_13',
    title: 'Grens stellen aan zichzelf',
    skill: 'Zelfregulatie',
    description: 'Bespreek een situatie waar je tiener zichzelf een grens zou moeten stellen (te laat opblijven, te veel gamen). Vraag: "Wat is jouw grens? Hoe bewaar je die?" Laat hem formuleren.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Grenzen stellen aan zichzelf is een hogere vorm van zelfregulatie die intrinsieke motivatie vereist. Tieners die hun eigen grenzen formuleren, houden zich er significant beter aan.',
    skillTip: 'Vraag: "Hoe weet je als je je eigen grens overschrijdt?" Bewustzijn van signalen is de sleutel.',
    vermijd: 'Vermijd zijn grenzen voor hem formuleren. Jouw grens is niet zijn grens.',
    leerdoel: 'Je stimuleert autonome grensformulering als kern van zelfregulatie bij tieners.',
    bron: 'Deci, E.L. & Ryan, R.M. (1985). Intrinsic Motivation and Self-Determination.',
  },
  {
    id: 'zelf_1316_14',
    title: 'Omgaan met groepsdruk',
    skill: 'Zelfregulatie',
    description: 'Bespreek een situatie van groepsdruk. Vraag: "Wanneer doe jij mee aan iets wat je eigenlijk niet wil? Wat voelt er dan in je? Wat helpt je dan?" Luister volledig.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Groepsdruk activeert het sociale beloningssysteem bij tieners extra sterk. Bewustzijn van dit mechanisme vergroot de mogelijkheid tot autonome keuze in groepssituaties.',
    skillTip: 'Deel een eigen voorbeeld van groepsdruk toen jij tiener was. Dat normaliseert het en vergroot vertrouwen.',
    vermijd: 'Vermijd moraliseren over groepsdruk. Exploreer het samen, oordeel niet.',
    leerdoel: 'Je vergroot zijn bewustzijn van groepsdruk-mechanismen en mogelijkheden voor autonome keuze.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'zelf_1316_15',
    title: 'Slaaphygiëne samen verkennen',
    skill: 'Zelfregulatie',
    description: 'Bespreek slaaphygiëne samen als experiment: "Stel je slaapt 8 uur 3 dagen achter elkaar. Wat merk je dan?" Ontwerp een experiment dat hij vrijwillig wil uitvoeren.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Slaap is de meest onderschatte regulatiefactor bij tieners. Slaaptekort verlaagt aantoonbaar de impulscontrole, emotionele regulatie en cognitieve flexibiliteit.',
    skillTip: 'Koppel slaap aan iets wat hij waardeert: sport, denken, gamen. "Met meer slaap doe je dat beter." Maak het relevant.',
    vermijd: 'Vermijd de regel opleggen. Het experiment-frame vergroot zijn intrinsieke motivatie.',
    leerdoel: 'Je vergroot zijn begrip van slaap als zelfregulatiebasis via een vrijwillig experiment.',
    bron: 'Walker, M. (2017). Why We Sleep.',
  },
  {
    id: 'zelf_1316_16',
    title: 'Mindfulness eenvoudig introduceren',
    skill: 'Zelfregulatie',
    description: 'Introduceer een eenvoudige mindfulness-oefening: "Merk de volgende keer dat je je gestrest voelt op: stop, merk vijf dingen op die je ziet, vier die je hoort, drie die je voelt."',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'De 5-4-3 sensorische grounding-techniek activeert het parasympathische systeem via zintuiglijke aandacht. Ze is bewezen effectief bij het verminderen van acute stressrespons.',
    skillTip: 'Doe de oefening eerst samen in een rustig moment, zodat hij hem kent als hij hem nodig heeft.',
    vermijd: 'Vermijd het woord "meditatie" als dat weerstand oproept. Zeg "grounding-oefening" of "focus-techniek".',
    leerdoel: 'Je introduceert een concrete, wetenschappelijk onderbouwde kalmeer-techniek die hij zelf kan inzetten.',
    bron: 'Kabat-Zinn, J. (1990). Full Catastrophe Living.',
  },
  {
    id: 'zelf_1316_17',
    title: 'Zijn patroon van vermijding herkennen',
    skill: 'Zelfregulatie',
    description: 'Bespreek: "Is er iets in jouw leven dat je steeds uitstelt of vermijdt? Wat maakt dat zo moeilijk?" Help hem het vermijdingspatroon te zien zonder het te veroordelen.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Vermijding is een regulatiestrategie die op korte termijn werkt maar lange termijn schade doet. Bewust maken van vermijdingspatronen is de eerste stap naar actieve regulatie.',
    skillTip: 'Vraag: "Hoe voelt het als je het uitstelt? Hoe als je het toch doet?" Contrast vergroot motivatie.',
    vermijd: 'Vermijd dit als aanklacht of les. Exploreer nieuwsgierig zijn patroon samen.',
    leerdoel: 'Je helpt je tiener vermijdingspatronen te herkennen als regulatiemechanisme.',
    bron: 'Hayes, S.C. et al. (1999). Acceptance and Commitment Therapy.',
  },
  {
    id: 'zelf_1316_18',
    title: 'Zijn waarden als kompas',
    skill: 'Zelfregulatie',
    description: 'Bespreek met je tiener: "Als je vastzit of niet weet wat je moet doen – wat zijn de drie waarden die dan je kompas kunnen zijn?" Help hem die formuleren.',
    duration: '20 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Waarden-gebaseerde zelfregulatie is de meest duurzame vorm van gedragssturing. Tieners die hun waarden kennen, nemen veerkrachtiger beslissingen onder druk.',
    skillTip: 'Gebruik concrete vragen: "Wat is voor jou het allerbelangrijkste in hoe je leeft?" Niet wat hij moet zijn, maar wat hij wil zijn.',
    vermijd: 'Vermijd je eigen waarden als correct presenteren. Zijn waarden zijn zijn waarden.',
    leerdoel: 'Je helpt je tiener zijn eigen waarden als intern regulatiekompas te formuleren.',
    bron: 'Hayes, S.C. et al. (1999). Acceptance and Commitment Therapy.',
  },
  {
    id: 'zelf_1316_19',
    title: 'Zelfregulatie bij conflicten bespreekbaar',
    skill: 'Zelfregulatie',
    description: 'Na een conflict waarbij jullie allebei de controle verloren: bespreek het eerlijk. "Wat zou ik anders hebben gewild van mezelf? En jij?" Beide kanten.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Gezamenlijke reflectie na verlies van regulatie normaliseert het proces en biedt een model voor eerlijke zelfbeoordeling. Het herstelt de relatie en leert beiden te groeien.',
    skillTip: 'Begin zelf. Jouw eerlijkheid maakt zijn eerlijkheid mogelijk.',
    vermijd: 'Vermijd dit te vroeg na het conflict doen. Wacht tot er volledig rust is.',
    leerdoel: 'Je oefent gezamenlijke regulatiereflectie als groeimodel na conflicten.',
    bron: 'Gottman, J. (1994). Why Marriages Succeed or Fail.',
  },
  {
    id: 'zelf_1316_20',
    title: 'Zijn eigen coach zijn',
    skill: 'Zelfregulatie',
    description: 'Vraag je tiener: "Als jij je eigen coach was in moeilijke momenten – wat zou die dan zeggen?" Laat hem een intern coach-stemmetje formuleren dat hij kan activeren.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Zelf-coaching via internalisering van een ondersteunende stem is een bewezen techniek uit compassiegerichte therapie. Het vergroot de capaciteit voor zelfdirected regulatie.',
    skillTip: 'Vraag: "Wat zou je beste vriend of iemand die je bewondert zeggen?" Dan kun je die stem internaliseren.',
    vermijd: 'Vermijd een coach-stem die alleen positief is. Een eerlijke, ondersteunende stem is geloofwaardiger.',
    leerdoel: 'Je helpt je tiener een intern zelfcoaching-perspectief te ontwikkelen.',
    bron: 'Gilbert, P. (2010). The Compassionate Mind.',
  },
];
