// Emotiecoaching – Ronde 2: 50 nieuwe interactieve taken (5 leeftijdsgroepen × 10)
import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_11: InteractiveTask[] = [

  // ─── 0-2 jaar ────────────────────────────────────────────────
  {
    id: 'emot_02_11',
    title: 'Benoem zijn vermoeidheid',
    skill: 'Emotiecoaching',
    description: 'Als je baby tekenen van vermoeidheid toont (ogen wrijven, huilen, blik wegdraaien): benoem het rustig. "Je bent moe, hè? Dat is oké, we gaan zo slapen."',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Baby\'s hebben geen woorden voor hun toestand. Vader die benoemt wat hij ziet geeft het kind een emotioneel kader – de eerste stap naar zelfregulatie.',
    skillTip: 'Gebruik een rustige, zachte stem. De toon communiceert meer dan de woorden.',
    vermijd: 'Vermijd "je bent niet moe, je hebt net geslapen." Geloof zijn signalen boven jouw planning.',
    leerdoel: 'Je leert lichamelijke toestanden benoemen als vroege vorm van emotiecoaching.',
    bron: 'Siegel, D.J. & Hartzell, M. (2003). Parenting from the Inside Out.',
  },
  {
    id: 'emot_02_12',
    title: 'Kalmeer mee met hem',
    skill: 'Emotiecoaching',
    description: 'Als je baby erg huilt en jij gespannen raakt: stop dan bewust. Adem diep. Kalmeer eerst jezelf. Dan pas je kind kalmeren. Voel het verschil.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Baby\'s spiegelen het zenuwstelsel van hun verzorger. Een gespannen vader kalmeert een huilende baby niet – een rustige vader wel. Jouw regulatie gaat voor zijn regulatie.',
    skillTip: 'Drie lange uitademingen. Schouders laten zakken. Dan pas oppakken.',
    vermijd: 'Vermijd doorgaan met troosten terwijl je zelf in paniek bent. Dat versterkt zijn distress.',
    leerdoel: 'Je leert co-regulatie: eerst jezelf kalmeren, dan je kind.',
    bron: 'Porges, S.W. (2011). The Polyvagal Theory.',
  },
  {
    id: 'emot_02_13',
    title: 'Zijn lach beantwoorden',
    skill: 'Emotiecoaching',
    description: 'Als je baby lacht of kirt: stop met wat je doet en beantwoord zijn positieve emotie volledig. Lach terug. Reageer met enthousiasme. Vier zijn vreugde samen.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Positieve emoties bevestigen is net zo belangrijk als negatieve erkennen. Het leert het kind dat vreugde welkom is en deelbaar – de basis van sociale emotie.',
    skillTip: 'Overdrijf gerust. Grote ogen, brede glimlach, enthousiaste stem. Baby\'s reageren daar het sterkst op.',
    vermijd: 'Vermijd een vlak of neutraal gezicht als hij lacht. "Still face" bij positieve emotie is net zo pijnlijk.',
    leerdoel: 'Je leert positieve emoties bevestigen als gelijkwaardige coaching-vaardigheid.',
    bron: 'Tronick, E. (2007). The Neurobehavioral and Social-Emotional Development of Infants.',
  },
  {
    id: 'emot_02_14',
    title: 'Angst erkennen bij nieuwe situaties',
    skill: 'Emotiecoaching',
    description: 'In een nieuwe situatie (bezoek, een nieuwe plek): als je baby angstig reageert, zeg dan: "Dit is nieuw. Dat is spannend. Ik ben bij je." Geef hem tijd.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Vreemdheidsangst is een gezonde ontwikkelingsfase. Vader die dit erkent en aanwezig blijft (in plaats van te forceren) leert het kind dat angst draagbaar is.',
    skillTip: 'Houd hem vast maar forceer geen contact met anderen. Laat hem je borst als veilige basis gebruiken.',
    vermijd: 'Vermijd "er is niets aan de hand" of hem naar iemand anders duwen. Erkenning eerst.',
    leerdoel: 'Je leert angst bij nieuwe situaties als normaal en dragelijk te begeleiden.',
    bron: 'Bowlby, J. (1988). A Secure Base.',
  },
  {
    id: 'emot_02_15',
    title: 'Frustratie in spel benoemen',
    skill: 'Emotiecoaching',
    description: 'Als je peuter iets probeert maar mislukt (een blok past niet, een deur gaat niet open) en hij begint te huilen of gooien: benoem het: "Dat lukt niet en dat is frustrerend."',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Frustratie is de vroegste vorm van zelfregulatie-uitdaging. Vader die het benoemt geeft taal aan de ervaring en helpt het kind leren dat frustratie normaal en passeerbaar is.',
    skillTip: 'Bied daarna rustig hulp aan: "Wil je hulp of doe je het nog een keer zelf?"',
    vermijd: 'Vermijd direct overnemen. Laat hem eerst even zelf de frustratie voelen voor je ingrijpt.',
    leerdoel: 'Je leert frustratie in spel als eerste les in emotiecoaching te gebruiken.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'emot_02_16',
    title: 'Speels benoemen bij het spiegelen',
    skill: 'Emotiecoaching',
    description: 'Houd je baby voor een spiegel. Benoem wat hij ziet: "Dat ben jij! Jij lacht! Wat een blij gezicht!" Verander zijn uitdrukking met je eigen gezicht en beschrijf het.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Spiegelspel vergroot zelfherkenning en emotioneel bewustzijn. Vader die gezichtsuitdrukkingen benoemt verbindt gevoel aan woordtaal – vroege emotiecoaching.',
    skillTip: 'Maak duidelijke gezichten: heel blij, verrast, droef. Kinderen detecteren deze al vroeg.',
    vermijd: 'Vermijd alleen positieve uitdrukkingen. Droef en verrast zijn ook leerzame emoties.',
    leerdoel: 'Je koppelt zichtbare emotie-uitdrukkingen aan taal via spiegelspel.',
    bron: 'Stern, D. (1985). The Interpersonal World of the Infant.',
  },
  {
    id: 'emot_02_17',
    title: 'Huilen zonder haast stoppen',
    skill: 'Emotiecoaching',
    description: 'Laat je baby even huilen zonder hem meteen te willen stoppen. Houd hem vast, zeg "ik hoor je", adem rustig. Accepteer zijn emotie voor je hem sust.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Ouders die hun kind te snel proberen te kalmeren communiceren onbedoeld: "Je gevoel is niet welkom." Een moment lang aanwezig zijn bij huilen normaliseert emotie.',
    skillTip: 'Zeg: "Ik hoor je. Je bent boos/verdrietig/moe. Ik ben er." Dat is genoeg om te beginnen.',
    vermijd: 'Vermijd paniek bij langdurig huilen. Jouw kalmte is zijn ankerpunt.',
    leerdoel: 'Je leert aanwezig zijn bij emotie zonder die meteen te willen beëindigen.',
    bron: 'Winnicott, D.W. (1960). The theory of the parent-infant relationship.',
  },
  {
    id: 'emot_02_18',
    title: 'Verhaaltje over gevoelens',
    skill: 'Emotiecoaching',
    description: 'Kies een prentenboek met een personage dat iets voelt – bang, blij, verdrietig. Lees het voor en benoem het gevoel van het personage terwijl je kijkt naar het gezicht.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Prentenboeken zijn krachtige emotiecoachingtools: ze bieden veilige afstand van het eigen gevoel en geven taal aan emotionele ervaringen.',
    skillTip: 'Wijs naar het gezicht van het personage: "Kijk, die is verdrietig – zie je zijn mond?" Maak het visueel.',
    vermijd: 'Vermijd alleen verhalen kiezen over gelukkige personages. Emotievariatie is waardevoller.',
    leerdoel: 'Je gebruikt verhalen als emotiecoaching-instrument.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'emot_02_19',
    title: 'Zijn boosheid opvangen',
    skill: 'Emotiecoaching',
    description: 'Als je peuter boos wordt (stompen, gooien, gillen): ga op zijn niveau zitten. Zacht maar rustig: "Je bent heel boos. Dat is oké. Ik wacht tot jij rustig bent."',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Boosheid bij peuters is een neurologisch onvermogen, geen gedragskeuze. Aanwezig blijven zonder te straffen of te vluchten leert het kind dat grote gevoelens draagbaar zijn.',
    skillTip: 'Houd zijn veiligheid in de gaten maar geef ruimte voor de emotie. Nabij maar niet in de weg.',
    vermijd: 'Vermijd schreeuwen terug of negeren. Beide vergroten de regulatie-uitdaging.',
    leerdoel: 'Je leert boosheid als normaal en dragelijk begeleiden in plaats van het te stoppen.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2011). The Whole-Brain Child.',
  },
  {
    id: 'emot_02_20',
    title: 'Gezichten spelen',
    skill: 'Emotiecoaching',
    description: 'Maak samen met je kind blije, droevige, boze, en verbaasde gezichten. Doe ze voor, doe ze na. Lach samen. Benoem ze: "Dit is blij! Dit is boos!"',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Gezichtsuitdrukkingen leren herkennen en namaken is de vroegste vorm van emotionele geletterdheid. Dit spelletje bouwt de emotionele woordenschat speels op.',
    skillTip: 'Overdrijf de uitdrukkingen. Hoe groter, hoe leuker en leerzamer voor baby\'s.',
    vermijd: 'Vermijd alleen de positieve gezichten doen. Alle basisemoties zijn even normaal.',
    leerdoel: 'Je bouwt emotionele geletterdheid via speels gezichten spelen.',
    bron: 'Ekman, P. (1992). An argument for basic emotions.',
  },

  // ─── 3-5 jaar ────────────────────────────────────────────────
  {
    id: 'emot_35_11',
    title: 'Emotie-kleur tekenen',
    skill: 'Emotiecoaching',
    description: 'Vraag je kind: "Welke kleur is blij? Welke kleur is boos? Welke kleur is verdrietig?" Laat hem die kleuren op een blaadje zetten. Praat erover.',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Kleuren koppelen aan emoties is een metacognitieve strategie die het kind helpt emoties te herkennen en te communiceren via een niet-verbale taal.',
    skillTip: 'Doe mee: "Voor mij is boos donkerrood. En voor jou?" Er is geen goed antwoord.',
    vermijd: 'Vermijd correcties als zijn kleurkeuze anders is dan "logisch". Elke keuze is zijn eigen.',
    leerdoel: 'Je vergroot emotionele geletterdheid via creatieve expressie.',
    bron: 'Greenberg, M.T. (2006). Promoting resilience in children and youth.',
  },
  {
    id: 'emot_35_12',
    title: 'Emoties in het boek herkennen',
    skill: 'Emotiecoaching',
    description: 'Kies een prentenboek. Stop regelmatig: "Hoe denk jij dat [personage] zich nu voelt?" Wacht op zijn antwoord. Vraag: "Hoe weet je dat?" Kijk samen naar het gezicht.',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Empathie oefenen via fictieve personages biedt veilige afstand. Kinderen leren emoties herkennen bij anderen voor ze die bij zichzelf kunnen benoemen.',
    skillTip: 'Stel open vragen: "Hoe weet je dat hij bang is?" Bewijzen zoeken vergroot het begrip.',
    vermijd: 'Vermijd het verhaal samenvatten. Dit gaat om de emotionele laag, niet de plot.',
    leerdoel: 'Je oefent perspectief nemen en emotieherkenning via verhalen.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'emot_35_13',
    title: 'Emotie-thermometer maken',
    skill: 'Emotiecoaching',
    description: 'Teken samen een thermometer met vijf niveaus: van "heel rustig" tot "super boos". Geef elk niveau een kleur en een emoji. Vraag je kind: "Waar ben jij nu?"',
    duration: '20 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Visuele schalen voor emotie-intensiteit helpen kinderen nuances te zien tussen emoties. Ze leren dat er gradaties zijn – niet alleen "goed" of "slecht" voelen.',
    skillTip: 'Hang de thermometer op en gebruik hem daarna echt. "Waar zit jij nu op de thermometer?"',
    vermijd: 'Vermijd alleen de boosheidsthermometer te maken. Maak ook een voor verdriet en spanning.',
    leerdoel: 'Je geeft je kind een visueel instrument voor emotie-intensiteitsherkenning.',
    bron: 'Greenberg, M.T. & Snell, J.L. (1997). Brain development and emotional development.',
  },
  {
    id: 'emot_35_14',
    title: 'Wat deed jij toen je boos was?',
    skill: 'Emotiecoaching',
    description: 'Vertel je kind een moment dat jij boos was (eerlijk, echt). Wat voelde je? Wat deed je? Wat hielp? Laat zien dat ook vaders boosheid voelen en ermee omgaan.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Ouderlijke zelfonthulling over eigen emoties normaliseert gevoelens bij het kind en geeft een model voor coping. Kinderen leren van hoe vader ermee omgaat.',
    skillTip: 'Kies een echt maar niet te intens voorbeeld. Iets herkenbaars voor een kind van zijn leeftijd.',
    vermijd: 'Vermijd verhalen over boosheid richting zijn andere ouder of volwassenen in zijn leven.',
    leerdoel: 'Je normaliseert boosheid door jouw eigen ervaring als model te delen.',
    bron: 'Brown, B. (2010). The Gifts of Imperfection.',
  },
  {
    id: 'emot_35_15',
    title: 'Rustig worden samen',
    skill: 'Emotiecoaching',
    description: 'Na een emotioneel moment (ruzie, boosheid): ga samen op de grond zitten. Adem samen drie keer diep in en uit. Zeg: "Ik merk dat we allebei weer rustiger worden."',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Gezamenlijke kalmeer-oefeningen na emotionele momenten herstel de verbinding en modelleren regulatietechnieken. Het kind ervaart dat kalmeren samen kan.',
    skillTip: 'Gebruik je eigen lichaam als voorbeeld: "Ik voel mijn schouders zakken. Voel jij dat ook?"',
    vermijd: 'Vermijd dit direct na het hoogtepunt van de emotie doen. Wacht tot de eerste storm voorbij is.',
    leerdoel: 'Je modelleert gezamenlijk rustig worden als regulatiestrategie.',
    bron: 'Porges, S.W. (2011). The Polyvagal Theory.',
  },
  {
    id: 'emot_35_16',
    title: 'Boze woorden versus boze handen',
    skill: 'Emotiecoaching',
    description: 'Leg je kind het verschil uit: "Boos zijn mag. Slaan mag niet. Je mag zeggen dat je boos bent, maar niet iemand pijn doen." Oefen samen: "Ik ben boos omdat..."',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Het onderscheid tussen het gevoel (altijd welkom) en het gedrag (grenzen stellen) is de kern van emotiecoaching. Kinderen moeten leren dat boosheid uiten mag, geweld niet.',
    skillTip: 'Oefen de zin "Ik ben boos omdat..." samen. Herhaling maakt het een automatisch alternatief voor slaan.',
    vermijd: 'Vermijd zeggen "je bent niet echt boos". Het gevoel klopt altijd – alleen het gedrag heeft grenzen.',
    leerdoel: 'Je leert het kind het onderscheid tussen gevoel en gedrag als kern van zelfregulatie.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'emot_35_17',
    title: 'Verdriet en troost',
    skill: 'Emotiecoaching',
    description: 'Als je kind verdrietig is: vraag eerst "wil je een knuffel of wil je even alleen zijn?" Respecteer zijn antwoord. Geef troost in de vorm die hij vraagt.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kinderen hebben verschillende troostbehoeften. Autonomie geven in hoe troost eruitziet leert hen hun eigen behoeften te kennen en communiceren – zelfreflectie in kiem.',
    skillTip: 'Soms is het antwoord "alleen zijn". Respecteer dat. Zeg: "Ik ben dichtbij als je me nodig hebt."',
    vermijd: 'Vermijd troost opleggen die jij nodig acht maar hij niet wil. Zijn behoefte staat centraal.',
    leerdoel: 'Je leert troost aanbieden die aansluit bij zijn behoeften, niet jouw instinct.',
    bron: 'Gordon, T. (1970). Parent Effectiveness Training.',
  },
  {
    id: 'emot_35_18',
    title: 'Het gevoel achter het gedrag',
    skill: 'Emotiecoaching',
    description: 'Als je kind moeilijk gedrag vertoont (pesten, dramatisch doen, weigeren): vraag jezelf eerst: "Welk gevoel zit hier achter?" Benoem dat gevoel voordat je het gedrag aanpakt.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Gedrag is altijd communicatie. Achter weerstand zit bijna altijd een onvervulde behoefte of een niet-erkend gevoel. Emotie erkennen vermindert de gedragsdruk.',
    skillTip: 'Vraag: "Wacht, ik zie jou... ben jij misschien [boos/bang/moe]?" Dan pas het gedrag bespreekbaar maken.',
    vermijd: 'Vermijd beginnen met het gedrag aanpakken. Start altijd bij het gevoel.',
    leerdoel: 'Je leert het gevoel achter het gedrag te zien en te adresseren.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2011). The Whole-Brain Child.',
  },
  {
    id: 'emot_35_19',
    title: 'Emotie-bibliotheek bouwen',
    skill: 'Emotiecoaching',
    description: 'Schrijf samen op een groot papier alle gevoelenswoorden die jullie kennen. Hoe meer, hoe beter. Hang het op en voeg elke dag nieuwe woorden toe als ze opkomen.',
    duration: '20 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Een grotere emotionele woordenschat is direct gecorreleerd met betere emotieregulatie. Kinderen die meer emotiewoorden kennen, kunnen hun gevoelens beter sturen.',
    skillTip: 'Voeg ook subtiele woorden toe: "teleurgesteld", "opgelucht", "zenuwachtig". Die nuanceren.',
    vermijd: 'Vermijd alleen de basics (blij, boos, bang, verdrietig). Er zijn er tientallen meer.',
    leerdoel: 'Je vergroot de emotionele woordenschat als instrument voor zelfregulatie.',
    bron: 'Lieberman, M.D. et al. (2007). Putting feelings into words: Affect labeling disrupts amygdala activity.',
  },
  {
    id: 'emot_35_20',
    title: 'Blij moment vieren',
    skill: 'Emotiecoaching',
    description: 'Als je kind iets fijns ervaart, vier dat bewust mee. Zeg: "Jij bent echt blij nu! Dat is zo leuk om te zien!" Geniet samen van zijn vreugde.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Positieve emoties delen en versterken (kapitaliseren) vergroot welzijn en sociale verbondenheid. Vader die zijn vreugde deelt, vergroot de impact van het positieve moment.',
    skillTip: 'Gebruik specifieke woorden voor blijdschap: "opgewonden", "trots", "euforisch". Vergroot de emotionele woordenschat.',
    vermijd: 'Vermijd vlak reageren op positieve emoties. Gedeelde vreugde is dubbele vreugde.',
    leerdoel: 'Je leert positieve emoties actief te benoemen en te versterken.',
    bron: 'Gable, S.L. et al. (2004). What do you do when things go right?',
  },

  // ─── 6-9 jaar ────────────────────────────────────────────────
  {
    id: 'emot_69_11',
    title: 'Emotie-detective spelen',
    skill: 'Emotiecoaching',
    description: 'Kijk samen een stuk van een film of serie (zonder geluid). Probeer allebei te raden wat de personages voelen aan hun gezicht en lichaamstaal. Vergelijk je gissingen.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Non-verbale emotieherkenning is een sleutelcomponent van empathie. Oefenen via film biedt een speelse, veilige context om deze vaardigheid te ontwikkelen.',
    skillTip: 'Pauzeer op een interessant gezicht en vraag: "Wat denk jij dat hij voelt? Hoe weet je dat?"',
    vermijd: 'Vermijd te snel het antwoord geven. Laat hem zelf nadenken.',
    leerdoel: 'Je oefent emotieherkenning via non-verbale signalen als empathieskill.',
    bron: 'Ekman, P. (1992). An argument for basic emotions.',
  },
  {
    id: 'emot_69_12',
    title: 'Zijn woede begrijpen',
    skill: 'Emotiecoaching',
    description: 'Als je kind boos op je is: vraag in plaats van te reageren: "Ik wil begrijpen waarom je boos bent. Kun je me dat uitleggen?" Dan: luister zonder je te verdedigen.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kinderen van 6-9 kunnen hun gevoelens steeds beter verwoorden als ze de ruimte krijgen. Vader die vraagt en luistert – in plaats van verdedigt – modelt emotionele volwassenheid.',
    skillTip: 'Herhaal wat je hoort: "Dus jij bent boos omdat..." Dat toont dat je echt luistert.',
    vermijd: 'Vermijd direct je eigen perspectief inbrengen. Eerst volledig begrijpen, dan pas reageren.',
    leerdoel: 'Je leert zijn boosheid als informatie te behandelen in plaats van als aanval.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'emot_69_13',
    title: 'Zenuwen normaliseren',
    skill: 'Emotiecoaching',
    description: 'Als je kind zenuwachtig is voor iets: zeg eerst "het is logisch dat je zenuwachtig bent, dat gevoel kennen wij allemaal." Dan: vraag wat helpt. Niet: "Dat valt wel mee."',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Normaliseren van angst vermindert de secundaire angst (angst voor de angst). Als vader zegt "dat is logisch" vermindert de amygdala-activatie.',
    skillTip: 'Deel een eigen moment van zenuwen: "Ik ben ook zenuwachtig als..." Dat normaliseert verder.',
    vermijd: 'Vermijd het minimaliseren ("dat is helemaal niet zo eng") of dramatiseren ("dat snap ik, het is ook eng").',
    leerdoel: 'Je leert angst normaliseren zonder te minimaliseren of te vergroten.',
    bron: 'Siegel, D.J. (2010). Mindsight.',
  },
  {
    id: 'emot_69_14',
    title: 'De STOP-techniek uitleggen',
    skill: 'Emotiecoaching',
    description: 'Leer je kind de STOP-techniek: Stop – Adem – Observeer hoe je je voelt – Pak een keuze. Oefen het samen in een rustig moment, niet tijdens conflict.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'De STOP-techniek is een bewezen mindfulness-gebaseerde aanpak voor emotieregulatie bij kinderen. Het geeft hen een concreet instrument om hun reacties te vertragen.',
    skillTip: 'Oefen het eerst op neutrale situaties ("je hebt zin in chips maar we eten over 10 min"). Dan wordt het beschikbaar bij echte spanning.',
    vermijd: 'Vermijd het alleen uitleggen als hij al in de emotie zit. Dan is de prefrontale cortex offline.',
    leerdoel: 'Je geeft je kind een concreet zelfregulatie-instrument dat hij zelfstandig kan inzetten.',
    bron: 'Kabat-Zinn, J. (1990). Full Catastrophe Living.',
  },
  {
    id: 'emot_69_15',
    title: 'Teleurstelling begeleiden',
    skill: 'Emotiecoaching',
    description: 'Als je kind teleurgesteld is (iets lukt niet, plannen gaan niet door): erken het eerst volledig. "Dat is echt jammer, ik begrijp dat je teleurgesteld bent." Geen oplossingen – alleen erkenning.',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Teleurstelling is een complexe sociale emotie die geleerd moet worden. Erkenning zonder minimalisering leert het kind dat dit gevoel normaal is en voorbijgaat.',
    skillTip: 'Wacht minimaal twee minuten voor je eventueel een alternatief aanbiedt. Erkenning heeft tijd nodig.',
    vermijd: 'Vermijd "volgende keer beter" of "er zijn ergere dingen". Zijn teleurstelling is nu zijn wereld.',
    leerdoel: 'Je leert teleurstelling volledig te erkennen voor je probeert te troosten of oplossen.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'emot_69_16',
    title: 'Complimenteren van emotieomgang',
    skill: 'Emotiecoaching',
    description: 'Als je kind een emotie goed hanteert (kalm blijft, woorden gebruikt in plaats van slaan, of zichzelf kalmeert): benoem het specifiek: "Ik zag dat je boos was maar je bleef met woorden praten. Dat is knap."',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Specifieke positieve bekrachtiging van emotieregulatie vergroot de kans dat het gedrag herhaald wordt. Kinderen leren van wat benoemd en gewaardeerd wordt.',
    skillTip: 'Gebruik de formule: "Ik zag dat je [situatie], en je deed [gedrag]. Dat is [kwaliteit]."',
    vermijd: 'Vermijd algemene complimenten als "je was lief". Specifiek is veel krachtiger.',
    leerdoel: 'Je versterkt goede emotieregulatie via gerichte positieve bekrachtiging.',
    bron: 'Dweck, C. (2006). Mindset: The New Psychology of Success.',
  },
  {
    id: 'emot_69_17',
    title: 'Schaamte bespreekbaar maken',
    skill: 'Emotiecoaching',
    description: 'Vraag je kind of er iets is waarvoor hij zich schaamt. Zeg eerst: "Ik ga niets geks van je denken – ik wil je alleen begrijpen." Luister. Geef geen oordeel.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Schaamte gedijt in stilte. Een vader die schaamte bespreekbaar maakt en niet oordeelt, helpt zijn kind schaamte te transformeren naar verantwoordelijkheid zonder zelfafkeer.',
    skillTip: 'Begin met een voorbeeld van jouw eigen schaamte – dan voelt hij dat hij veilig is.',
    vermijd: 'Vermijd bij zijn antwoord reageren met advies of mening. Alleen: "Ik hoor je. Dank je dat je dat deelt."',
    leerdoel: 'Je creëert een veilige ruimte voor schaamte, de meest verborgen emotie.',
    bron: 'Brown, B. (2012). Daring Greatly.',
  },
  {
    id: 'emot_69_18',
    title: 'Emotie-dagboek starten',
    skill: 'Emotiecoaching',
    description: 'Stel voor dat jullie allebei een weekje bijhouden welk gevoel er overdag het sterkst was. Aan het einde van de week: vergelijk. Geen oordeel – gewoon nieuwsgierigheid.',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Emotie-dagboeken vergoten emotioneel zelfbewustzijn. Kinderen die hun gevoelens bijhouden, leren patronen herkennen en krijgen meer controle over hun emotionele leven.',
    skillTip: 'Gebruik één woord per dag – dat is genoeg. Het doel is het patroon zien, niet het schrijven.',
    vermijd: 'Vermijd een dagboek afdwingen. Als hij het niet wil, is dat oké. Laat het vrijwillig zijn.',
    leerdoel: 'Je introduceert zelfobservatie als emotionele vaardigheid.',
    bron: 'Pennebaker, J.W. (1997). Opening Up: The Healing Power of Expressing Emotions.',
  },
  {
    id: 'emot_69_19',
    title: 'Onderscheid blij en opgelucht',
    skill: 'Emotiecoaching',
    description: 'Leg je kind het verschil uit tussen twee vergelijkbare emoties: blij en opgelucht. Geef voorbeelden van beide. Vraag hem: "Wanneer ben jij opgelucht?" Verdiep de woordenschat.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Emotionele granulariteit – het maken van onderscheid tussen vergelijkbare gevoelens – is geassocieerd met betere psychische gezondheid en betere sociale vaardigheden.',
    skillTip: 'Doe dit ook met andere koppels: bang/bezorgd, blij/trots, boos/gefrustreerd. Nuanceer.',
    vermijd: 'Vermijd te veel woorden tegelijk introduceren. Één onderscheid per gesprek is genoeg.',
    leerdoel: 'Je vergroot emotionele granulariteit als sleutel tot betere zelfregulatie.',
    bron: 'Barrett, L.F. (2017). How Emotions Are Made.',
  },
  {
    id: 'emot_69_20',
    title: 'Vraag naar zijn eerste reactie',
    skill: 'Emotiecoaching',
    description: 'Als er iets moeilijks is gebeurd: vraag je kind: "Wat voelde je als allereerste?" Niet wat hij deed – maar het allereerste gevoel. Luister aandachtig.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'De eerste emotionele reactie (voor de gedachte) is het primaire gevoel. Bewust worden van die laag vergroot het inzicht in eigen emotionele leven.',
    skillTip: 'Wees geduldig. Het eerste gevoel is soms moeilijker te benoemen dan het verhaal eromheen.',
    vermijd: 'Vermijd invullen voor hem. Wacht op zijn eigen woorden.',
    leerdoel: 'Je leert je kind bewust te zijn van het primaire gevoel voor het verhaal eromheen.',
    bron: 'Damasio, A. (1994). Descartes\' Error.',
  },

  // ─── 10-12 jaar ──────────────────────────────────────────────
  {
    id: 'emot_1012_11',
    title: 'Stress herkennen bij zijn leeftijd',
    skill: 'Emotiecoaching',
    description: 'Vertel je kind dat stress heel normaal is op zijn leeftijd. Bespreek: wat zijn typische stressoren voor kinderen van 10-12? Wat zijn de zijne? Luister zonder te minimaliseren.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Pre-pubers ervaren nieuwe stressbronnen (sociale vergelijking, prestatie) maar hebben nog niet altijd de cognitieve middelen om ze te reguleren. Normaliseren verlaagt de stressrespons.',
    skillTip: 'Vraag: "Wat maakt jou op dit moment het meest gestrest?" Luister echt.',
    vermijd: 'Vermijd vergelijken met jouw stressoren als kind. Zijn ervaring staat centraal.',
    leerdoel: 'Je normaliseert stress bij pre-pubers en vergroot zijn bewustzijn van eigen stressbronnen.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'emot_1012_12',
    title: 'Sociale emoties bespreken',
    skill: 'Emotiecoaching',
    description: 'Bespreek een sociale emotie: jaloezie, schaamte, of sociale angst. Leg uit wat het is. Vraag of hij het herkent. Deel een eigen ervaring ermee.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Sociale emoties worden dominant in de pre-puberteit maar worden zelden benoemd of besproken. Ze bespreekbaar maken vermindert schaamte en vergroot zelfinzicht.',
    skillTip: 'Wees eerlijk over jouw eigen jaloezie of sociale angst. Dat opent de deur voor hem.',
    vermijd: 'Vermijd moraliseren ("jaloezie is lelijk"). Verklaar de functie van de emotie.',
    leerdoel: 'Je maakt sociale emoties bespreekbaar als normale en informatieve gevoelens.',
    bron: 'Brown, B. (2012). Daring Greatly.',
  },
  {
    id: 'emot_1012_13',
    title: 'Emotie versus gedachte onderscheiden',
    skill: 'Emotiecoaching',
    description: 'Leg je kind het verschil uit: een gevoel is iets wat je ervaart (bang, boos), een gedachte is iets wat je denkt ("ze vinden me niet leuk"). Oefen samen voorbeelden.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Het onderscheid maken tussen gevoel en gedachte is een kernconcept in cognitieve gedragstherapie en vergroot de emotionele zelfregie van kinderen aanzienlijk.',
    skillTip: 'Gebruik de toets: "Kan ik dat voelen in mijn lichaam? Dan is het een gevoel." Concreet laten toetsen.',
    vermijd: 'Vermijd te abstracte uitleg. Gebruik concrete voorbeelden uit zijn eigen leven.',
    leerdoel: 'Je leert je kind het cruciale onderscheid tussen gevoel en gedachte.',
    bron: 'Beck, A.T. (1979). Cognitive Therapy of Depression.',
  },
  {
    id: 'emot_1012_14',
    title: 'Trigger-gesprek',
    skill: 'Emotiecoaching',
    description: 'Bespreek wat zijn triggers zijn: "Wat maakt jou het snelst boos of van streek?" Luister. Vraag wat er dan in hem omgaat. Help hem een eigen benaming te geven.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Triggers bewust kennen vergroot de mogelijkheid om er proactief mee om te gaan. Dit is een sleutelstap in de ontwikkeling van emotionele zelfregulatie.',
    skillTip: 'Deel ook jouw triggers. Gelijkwaardigheid in het gesprek verlaagt de drempel.',
    vermijd: 'Vermijd zijn triggers minimaliseren of analyseren. Alleen verkennen en begrijpen.',
    leerdoel: 'Je helpt je kind zijn persoonlijke triggers te kennen en benoemen.',
    bron: 'Siegel, D.J. & Hartzell, M. (2003). Parenting from the Inside Out.',
  },
  {
    id: 'emot_1012_15',
    title: 'Lichaamssignalen leren kennen',
    skill: 'Emotiecoaching',
    description: 'Vraag je kind: "Waar voel jij boosheid in je lichaam? Waar voel je angst?" Maak samen een lichaamstekening met kleurgebieden voor verschillende emoties.',
    duration: '20 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Lichamelijke emotie-awareness is gedocumenteerd als voorspeller van betere emotieregulatie. Onderzoek toont dat mensen emoties op vergelijkbare plekken in het lichaam ervaren.',
    skillTip: 'Gebruik de "body scan" methode: sluit je ogen en scan van hoofd naar voeten tijdens een emotie.',
    vermijd: 'Vermijd correcties als zijn lichaamssignalen anders zijn dan gemiddeld. Ze zijn altijd persoonlijk.',
    leerdoel: 'Je vergroot zijn lichaamsbewustzijn als vroeg waarschuwingssignaal van emoties.',
    bron: 'Nummenmaa, L. et al. (2014). Bodily maps of emotions.',
  },
  {
    id: 'emot_1012_16',
    title: 'Wat deed jij verkeerd?',
    skill: 'Emotiecoaching',
    description: 'Na een conflict of ruzie: ga later rustig zitten en vraag: "Wat deed jij in dat moment dat het erger maakte?" Dit is geen straf – het is zelfreflectie samen.',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Zelfreflectie na conflict vergroot de morele ontwikkeling en sociale verantwoordelijkheid. Kinderen die hun eigen aandeel leren zien, worden sociaal competenter.',
    skillTip: 'Begin zelf: "Wat deed ik dat het erger maakte?" Modelleer zelfreflectie voor je het vraagt.',
    vermijd: 'Vermijd dit in de hitte van het conflict. Wacht tot er rust is. Dan pas reflecteren.',
    leerdoel: 'Je leert zelfreflectie na conflict als routine in plaats van schuldgesprek.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2011). The Whole-Brain Child.',
  },
  {
    id: 'emot_1012_17',
    title: 'Omgaan met faalangst',
    skill: 'Emotiecoaching',
    description: 'Bespreek met je kind: "Wanneer ben jij bang om te falen?" Erken het. Leg dan uit: angst om te falen is normaal – het bewijs dat je iets geeft. Wat helpt jou dan?',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Faalangst neemt toe in de pre-puberteit door sociale vergelijking. Het normaliseren en herkaderen als "signaal dat het je iets waard is" vermindert de angstspiraal.',
    skillTip: 'Vertel een eigen moment van faalangst. Maak het reëel en persoonlijk.',
    vermijd: 'Vermijd zeggen "gewoon niet bang zijn" of "falen is leren". Dat minimaliseert de echte angst.',
    leerdoel: 'Je normaliseert faalangst en herkaadert het als betrokkenheidsignaal.',
    bron: 'Dweck, C. (2006). Mindset: The New Psychology of Success.',
  },
  {
    id: 'emot_1012_18',
    title: 'Eenzaamheid erkennen',
    skill: 'Emotiecoaching',
    description: 'Vraag je kind eens rustig: "Voel jij je weleens eenzaam, ook als je bij mensen bent?" Luister zonder te schrikken of te willen oplossen. Erken alleen.',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Eenzaamheid bij pre-pubers is veelvoorkomend maar bijna nooit bespreekbaar. Vader die het vraagt en accepteert, biedt een veilige haven voor een van de meest isolerende gevoelens.',
    skillTip: 'Als hij ja zegt: zeg niets. Knik. "Dat ken ik ook." Dat is al genoeg.',
    vermijd: 'Vermijd meteen oplossingen bieden: vrienden zoeken, activiteiten. Erkenning gaat voor.',
    leerdoel: 'Je maakt eenzaamheid bespreekbaar als normaal en dragelijk gevoel.',
    bron: 'Cacioppo, J.T. & Patrick, W. (2008). Loneliness: Human Nature and the Need for Social Connection.',
  },
  {
    id: 'emot_1012_19',
    title: 'Emotie coachen tijdens sport',
    skill: 'Emotiecoaching',
    description: 'Na een wedstrijd of sportmoment: bespreek niet de prestatie maar de emoties. "Hoe voelde je je toen je scoorde? Toen je verloor? Toen je een fout maakte?"',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Sport is een rijke context voor emotionele ervaringen. Vader die de emotionele laag bespreekt in plaats van de prestatie, helpt zijn kind sportiviteit en veerkracht te ontwikkelen.',
    skillTip: 'Stel open vragen over de emoties, niet over de keuzes. "Hoe voelde je je?" niet "Waarom schoot je zo?"',
    vermijd: 'Vermijd coaching-gedrag na afloop: wat hij anders moet doen. Nu gaat het om het gevoel.',
    leerdoel: 'Je leert sport als emotionele leeromgeving te gebruiken.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'emot_1012_20',
    title: 'Trots benoemen zonder prestatie',
    skill: 'Emotiecoaching',
    description: 'Zeg je kind dat je trots op hem bent – maar niet om een prestatie. Om wie hij is: zijn vriendelijkheid, zijn doorzettingsvermogen, zijn eerlijkheid. Wees specifiek.',
    duration: '5 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Trots die gekoppeld is aan karakter in plaats van resultaat versterkt intrinsieke motivatie en zelfwaarde. Het kind leert dat zijn waarde niet afhankelijk is van succes.',
    skillTip: 'Gebruik de formule: "Ik ben trots op jou omdat ik zie hoe jij [karaktereigenschap] bent in [situatie]."',
    vermijd: 'Vermijd trots koppelen aan cijfers, scores of resultaten. Dat versterkt prestatiegericht denken.',
    leerdoel: 'Je leert trots als emotionele voeding voor zijn identiteit in plaats van zijn prestaties.',
    bron: 'Dweck, C. (2006). Mindset: The New Psychology of Success.',
  },

  // ─── 13-16 jaar ──────────────────────────────────────────────
  {
    id: 'emot_1316_11',
    title: 'Puberbrein uitleggen',
    skill: 'Emotiecoaching',
    description: 'Leg je tiener op een toegankelijke manier uit wat er in zijn brein gebeurt: de amygdala is extra actief, de prefrontale cortex nog in ontwikkeling. "Je bent biologisch gebouwd om intenser te voelen."',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Tieners die begrijpen dat hun emotionele intensiteit neurologisch verklaard is, voelen minder schaamte over hun reacties en meer vermogen om ze te observeren.',
    skillTip: 'Gebruik analogieën: "Je gaspedaal (amygdala) is vol gas, je rem (prefrontale cortex) is nog in aanbouw." Simpel maar krachtig.',
    vermijd: 'Vermijd dit gebruiken om zijn emoties te verklaren of te relativeren. Uitleg, geen excuus.',
    leerdoel: 'Je vergroot zijn kennis van zijn eigen brein als basis voor zelfbegrip.',
    bron: 'Siegel, D.J. (2013). Brainstorm: The Power and Purpose of the Teenage Brain.',
  },
  {
    id: 'emot_1316_12',
    title: 'Zijn stresssignalen herkennen',
    skill: 'Emotiecoaching',
    description: 'Bespreek met je tiener: wat zijn jouw eerste signalen dat je gestrest raakt? (moodiness, terugtrekken, slapeloosheid, eetpatroon). Leer zijn persoonlijke stressmarkers kennen.',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Vroeg herkennen van persoonlijke stresssignalen vergroot de mogelijkheid tot proactieve regulatie. Tieners die dit kennen, kunnen eerder hulp zoeken of ingrijpen.',
    skillTip: 'Deel ook jouw stresssignalen. "Bij mij merk ik het eerst aan... en daarna..."',
    vermijd: 'Vermijd dit als diagnose-gesprek. Het gaat om zelfkennis, niet om labelen.',
    leerdoel: 'Je helpt je tiener zijn persoonlijke stresssignalen bewust te kennen.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'emot_1316_13',
    title: 'Omgaan met mislukking bespreken',
    skill: 'Emotiecoaching',
    description: 'Bespreek een recente mislukking of teleurstelling van je tiener. Niet om te analyseren – maar om te vragen: "Hoe voel je je daarmee nu? Wat maakt het het moeilijkst?"',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Tieners schamen zich sterk voor mislukkingen. Vader die ernaar vraagt zonder te oordelen of te analyseren geeft toestemming om teleurstelling te voelen zonder afkeer van zichzelf.',
    skillTip: 'Laat hem de toon bepalen. Als hij wil praten – luister. Als hij dat niet wil – wacht.',
    vermijd: 'Vermijd "next time, try harder" of lessen trekken. Eerst alleen het gevoel.',
    leerdoel: 'Je creëert een veilige ruimte voor schaamte bij mislukking.',
    bron: 'Brown, B. (2012). Daring Greatly.',
  },
  {
    id: 'emot_1316_14',
    title: 'Druk van buitenaf bespreken',
    skill: 'Emotiecoaching',
    description: 'Vraag je tiener: "Welke druk van buitenaf voel jij het sterkst op dit moment?" (sociale media, school, vrienden, verwachtingen). Luister. Erken het. Stel geen oplossingen voor.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Externe druk is een van de sterkste stressbronnen voor tieners. Bewust maken en bespreken van die druk vermindert de last van het stilzwijgend dragen ervan.',
    skillTip: 'Wees niet geschokt door wat hij zegt. Een neutrale, nieuwsgierige houding houdt hem pratend.',
    vermijd: 'Vermijd in oplossingsmodus schieten. Erkenning is al meer dan genoeg.',
    leerdoel: 'Je geeft ruimte aan de ervaring van sociale druk bij tieners zonder het weg te willen maken.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'emot_1316_15',
    title: 'Omgaan met boosheid op hem',
    skill: 'Emotiecoaching',
    description: 'Als jij boos bent op je tiener: vertel hem dat je boos bent zonder hem te beschuldigen. "Ik ben boos omdat ik me [genegeerd/ongerespecteerd] voel." Geen aanval, wel eerlijkheid.',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Vader die zijn eigen boosheid communiceert vanuit gevoel in plaats van aanval modelleert gezonde emotie-expressie en leert het kind hoe verantwoordelijk te communiceren.',
    skillTip: 'Gebruik ik-boodschappen: "Ik voel me...", "Voor mij is het..." Vermijd "jij altijd..." en "jij nooit..."',
    vermijd: 'Vermijd schreeuwen of verwijten terwijl je dit doet. Dit is alleen effectief in rust.',
    leerdoel: 'Je modelleert assertieve emotie-communicatie als alternatief voor reactieve uitbarstingen.',
    bron: 'Rosenberg, M.B. (2003). Nonviolent Communication: A Language of Life.',
  },
  {
    id: 'emot_1316_16',
    title: 'Depressieve gevoelens bespreekbaar maken',
    skill: 'Emotiecoaching',
    description: 'Vraag je tiener eens rustig: "Heb jij weleens periodes dat je je nergens voor kunt opwinden of je leeg voelt?" Luister. Oordeel niet. Dit opent een veilige deur.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Depressieve symptomen komen veelvuldig voor bij tieners maar worden zelden besproken. Vader die de vraag stelt geeft toestemming om een moeilijk onderwerp te benoemen.',
    skillTip: 'Als hij ja zegt: vraag hoe lang, hoe vaak. Overweeg professionele hulp als het structureel is.',
    vermijd: 'Vermijd schrikken of meteen in probleemoplossingmodus gaan. Eerst volledig luisteren.',
    leerdoel: 'Je opent een deur voor het bespreken van mentale gezondheid bij je tiener.',
    bron: 'Siegel, D.J. (2013). Brainstorm: The Power and Purpose of the Teenage Brain.',
  },
  {
    id: 'emot_1316_17',
    title: 'Kwetsbaarheid tonen bij fouten',
    skill: 'Emotiecoaching',
    description: 'De volgende keer dat jij een fout maakt: zeg dat hardop tegen je tiener. "Ik had dat anders moeten aanpakken, ik voelde me daarna niet goed over." Geen excuus – eerlijkheid.',
    duration: '5 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Kwetsbaarheid tonen bij fouten normaliseert imperfectie en laat zien dat verantwoordelijkheid nemen en gevoelens hebben menselijk en krachtig is.',
    skillTip: 'Voeg het gevoel erbij toe – dat is het meest emotiecoachende deel. "Ik voelde me... en dat was moeilijk."',
    vermijd: 'Vermijd excuses maken of zelfkritiek overdrijven. Gewoon eerlijk zijn is genoeg.',
    leerdoel: 'Je modelleert kwetsbaarheid en fouten erkennen als emotionele volwassenheid.',
    bron: 'Brown, B. (2012). Daring Greatly.',
  },
  {
    id: 'emot_1316_18',
    title: 'Grenzen benoemen vanuit gevoel',
    skill: 'Emotiecoaching',
    description: 'Leg je tiener een grens uit vanuit gevoel: "Als jij me afkapt, voel ik me niet gehoord. Dat doet iets met mij. Ik wil vragen of je dat anders kunt zeggen." Geen aanval, wel grens.',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Grenzen stellen vanuit gevoel (NVC-stijl) is de meest effectieve methode om grenzen te handhaven zonder de relatie te beschadigen. Het modelleert tegelijk assertiviteit.',
    skillTip: 'Gebruik: "Als jij [gedrag], voel ik [gevoel], en ik vraag je [verzoek]." Houd het clean.',
    vermijd: 'Vermijd veralgemeningen ("je respecteert me nooit"). Blijf bij het concrete gedrag.',
    leerdoel: 'Je modelleert grens stellen vanuit gevoel als alternatief voor conflict of passiviteit.',
    bron: 'Rosenberg, M.B. (2003). Nonviolent Communication: A Language of Life.',
  },
  {
    id: 'emot_1316_19',
    title: 'Angst voor de toekomst bespreken',
    skill: 'Emotiecoaching',
    description: 'Vraag je tiener: "Ben jij weleens bang voor hoe de toekomst eruitziet?" Luister. Erken. Deel ook jouw angsten als jongere. Vertel hoe je daarmee omging.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Toekomstangst is een van de meest voorkomende angsten bij tieners maar zelden bespreekbaar. Vader die het vraagt én zijn eigen ervaringen deelt normaliseert de angst.',
    skillTip: 'Wees eerlijk dat ook jij nu nog weleens bang bent voor de toekomst. Dat is meer verbindend dan "het komt goed".',
    vermijd: 'Vermijd direct geruststellen. "Het komt wel goed" sluit het gesprek. Eerst volledig erkennen.',
    leerdoel: 'Je normaliseert toekomstangst als menselijk en bespreekbaar.',
    bron: 'Siegel, D.J. (2013). Brainstorm.',
  },
  {
    id: 'emot_1316_20',
    title: 'Benoem wat je in hem bewondert',
    skill: 'Emotiecoaching',
    description: 'Vertel je tiener wat je in hem bewondert – niet als compliment maar als eerlijke observatie: "Ik zie hoe jij [situatie] aanpakt en dat bewonder ik echt in je."',
    duration: '5 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Bewondering van vader heeft een bijzondere kracht voor tieners: het vertelt hen dat hun identiteit positief is in de ogen van de persoon wiens oordeel er het meest toe doet.',
    skillTip: 'Kies een moment dat je hem echt verbaasde of raakte. Concrete bewondering is meer waard dan generiek.',
    vermijd: 'Vermijd er een "maar" achter plakken. Laat de bewondering zuiver en compleet zijn.',
    leerdoel: 'Je ervaart hoe specifieke bewondering zijn identiteitsgevoel versterkt.',
    bron: 'Brown, B. (2010). The Gifts of Imperfection.',
  },
];
