import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_26: InteractiveTask[] = [
  // ============================================================
  // AGE GROUP 0-2 (10 tasks)
  // ============================================================
  {
    id: 'aanw_0-2_350',
    skill: 'Aanwezigheid',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Verhaaltje met stemmen',
    description: 'Lees een kartonboekje voor met overdreven stemgeluiden en gezichtsuitdrukkingen.',
    instructions: [
      'Kies een kartonboekje met duidelijke plaatjes van dieren of voertuigen.',
      'Zet je baby of peuter op schoot zodat jullie samen de pagina\'s kunnen zien.',
      'Gebruik bij elk plaatje een ander stemgeluid of gezichtsuitdrukking (bv. "boe" voor de koe, grote ogen voor de uil).',
      'Let op de reactie van je kind en herhaal geluiden die een lach of reactie opwekken.',
    ],
    reflection: 'Welk geluid of welke uitdrukking riep de sterkste reactie op bij je kind? Wat zegt dat over wat hem of haar fascineert?',
    scienceNote: 'Gedeelde boekinteracties vanaf de babyleeftijd stimuleren taalontwikkeling en hechtingskwaliteit (Bus, Van IJzendoorn & Pellegrini, 1995, Review of Educational Research).',
    durationMin: 10,
  },
  {
    id: 'emco_0-2_351',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Zingende emoties',
    description: 'Zing korte liedjes die verschillende emoties uitbeelden terwijl je je kind vasthoudt.',
    instructions: [
      'Houd je kind dicht tegen je aan of zet het op je knie.',
      'Zing een vrolijk liedje (bv. "In de maneschijn") met een blij gezicht en levendige stem.',
      'Wissel af met een rustig, zacht slaapliedje met een kalme uitdrukking.',
      'Benoem de emotie: "Dat was een blij liedje! Nu een rustig liedje" en observeer de reactie van je kind.',
    ],
    reflection: 'Hoe reageerde je kind op de wisselingen in toon en tempo? Merkte je dat het je gezichtsuitdrukking volgde?',
    scienceNote: 'Baby\'s herkennen emotionele toon in zang eerder dan in spraak, wat bijdraagt aan emotionele afstemming (Trehub, 2001, Annals of the New York Academy of Sciences).',
    durationMin: 5,
  },
  {
    id: 'zelr_0-2_352',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Ritme met rammelaars',
    description: 'Maak samen muziek met rammelaars en leer je kind een eenvoudig ritme aan.',
    instructions: [
      'Pak twee rammelaars of zelfgemaakte schudbekers (rijst in een afgesloten flesje).',
      'Geef er een aan je kind en houd er zelf een vast.',
      'Schud een eenvoudig ritme voor: schud-schud-pauze, schud-schud-pauze.',
      'Moedig je kind aan om mee te doen en varieer het tempo langzaam; eindig met een duidelijke "stop!".',
    ],
    reflection: 'Lukte het je kind om even te pauzeren bij de stop? Vroege oefening met starten en stoppen bouwt zelfregulatie op.',
    scienceNote: 'Ritmische muziekactiviteiten ondersteunen de ontwikkeling van executieve functies en zelfregulatie bij jonge kinderen (Zentner & Eerola, 2010, PNAS).',
    durationMin: 10,
  },
  {
    id: 'gren_0-2_353',
    skill: 'Grenzen',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'De blokkengrens',
    description: 'Bouw samen een blokkentoren en oefen met de grens "voorzichtig" versus "boem!".',
    instructions: [
      'Zet een set zachte of houten blokken klaar op de grond.',
      'Bouw samen een toren en zeg bij elke blok: "Voorzichtig... voorzichtig...".',
      'Als de toren hoog genoeg is, zeg je: "Nu mag je... BOEM!" en laat je kind de toren omduwen.',
      'Herhaal en benoem het verschil: "Eerst voorzichtig bouwen, dan pas boem" zodat het kind leert wachten.',
    ],
    reflection: 'Kon je kind het wachten even volhouden voor het omduwen? Dit is een vroege vorm van impulscontrole leren.',
    scienceNote: 'Spel met duidelijke regels en herhaling ondersteunt de ontwikkeling van inhibitiecontrole bij peuters (Kochanska et al., 2001, Child Development).',
    durationMin: 10,
  },
  {
    id: 'auto_0-2_354',
    skill: 'Autonomie',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Welk boekje wil jij?',
    description: 'Laat je peuter kiezen uit twee boekjes om samen te lezen.',
    instructions: [
      'Houd twee kartonboekjes op zodat je kind ze allebei kan zien.',
      'Vraag: "Welk boekje wil je lezen? Dit of dit?" en wijs ze aan.',
      'Wacht geduldig tot je kind wijst, reikt of een geluid maakt.',
      'Bevestig de keuze enthousiast: "Jij kiest het boekje over de beer! Goed gekozen!" en lees het samen.',
    ],
    reflection: 'Hoe voelde het om je kind de keuze te geven? Kleine keuzemomenten bouwen het gevoel van autonomie op.',
    scienceNote: 'Het aanbieden van keuzes binnen een veilige structuur bevordert de autonomieontwikkeling conform de zelfdeterminatietheorie (Deci & Ryan, 2000, Psychological Inquiry).',
    durationMin: 10,
  },
  {
    id: 'hers_0-2_355',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Kiekeboe-terug',
    description: 'Gebruik kiekeboe als hersteloefening na een kort moment van afwezigheid.',
    instructions: [
      'Ga even achter je handen of een doek "verdwijnen" voor je kind.',
      'Wacht twee tot drie seconden en kom dan terug met een warm "Kiekeboe! Papa is er weer!".',
      'Herhaal dit drie of vier keer, en verleng de wachttijd heel geleidelijk.',
      'Eindig met een knuffel en de woorden: "Papa gaat soms even weg, maar papa komt altijd terug."',
    ],
    reflection: 'Hoe reageerde je kind op het steeds langer wachten? Dit spelletje oefent vertrouwen in terugkeer.',
    scienceNote: 'Kiekeboospel ondersteunt objectpermanentie en veilige hechting door voorspelbare hereniging (Piaget, 1954; Ainsworth et al., 1978).',
    durationMin: 5,
  },
  {
    id: 'verb_0-2_356',
    skill: 'Verbinding',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Vingerpoppenverhaal',
    description: 'Maak eenvoudige vingerpoppetjes en speel een kort verhaaltje voor je baby of peuter.',
    instructions: [
      'Teken met een pen twee simpele gezichtjes op je wijsvingers (blij en verbaasd).',
      'Laat de "poppetjes" met elkaar praten in verschillende stemmen: "Hallo! Hoe gaat het?" "Goed! Zullen we dansen?".',
      'Laat de poppetjes bewegen op de maat van een liedje dat je zingt.',
      'Betrek je kind door een poppetje zachtjes tegen zijn of haar handjes te laten "praten" en reacties af te wachten.',
    ],
    reflection: 'Hoe reageerde je kind op de poppetjes? Volgde het de bewegingen met de ogen of probeerde het ze aan te raken?',
    scienceNote: 'Poppenspel stimuleert gezamenlijke aandacht en sociale cognitie, fundamenten van Theory of Mind (Tomasello, 1995, Joint Attention as Social Cognition).',
    durationMin: 10,
  },
  {
    id: 'refl_0-2_357',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Spiegelverhaal',
    description: 'Ga met je kind voor de spiegel staan en vertel een verhaaltje over jullie spiegelbeeld.',
    instructions: [
      'Ga samen voor een grote spiegel staan of zitten.',
      'Wijs naar jullie spiegelbeeld en zeg: "Kijk, daar is papa! En daar ben jij!".',
      'Maak verschillende gezichtsuitdrukkingen en benoem ze: "Papa is blij! Papa is verbaasd!".',
      'Moedig je kind aan om ook gezichten te trekken en benoem wat je ziet: "Jij lacht! Wat een mooie lach!".',
    ],
    reflection: 'Herkende je kind zichzelf in de spiegel? Rond 18 maanden ontwikkelt zich zelfherkenning, een mijlpaal in zelfreflectie.',
    scienceNote: 'Zelfherkenning in de spiegel rond 18-24 maanden is een indicator van opkomend zelfbewustzijn (Lewis & Brooks-Gunn, 1979, Social Cognition and the Acquisition of Self).',
    durationMin: 5,
  },
  {
    id: 'emco_0-2_358',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Klankenverhaal',
    description: 'Vertel een kort verhaal met alleen klanken en emotionele geluiden, zonder woorden.',
    instructions: [
      'Houd je kind vast en begin een "verhaal" met alleen klanken: zachte brommende geluiden voor rust.',
      'Laat de klanken opbouwen naar opwinding: hogere tonen, snellere geluiden, een verrast "oooh!".',
      'Breng de klanken weer terug naar rust: langzame, lage, sussende geluiden.',
      'Let op hoe je kind meegaat in de emotionele boog van spanning naar ontspanning.',
    ],
    reflection: 'Merkte je dat je kind emotioneel meebewoog met de klanken? Dit is co-regulatie in actie.',
    scienceNote: 'Prosodie (melodie en ritme van de stem) is het primaire kanaal voor emotionele communicatie met pre-verbale kinderen (Fernald, 1989, Child Development).',
    durationMin: 5,
  },
  {
    id: 'verb_0-2_359',
    skill: 'Verbinding',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Trommel op papa',
    description: 'Laat je peuter op je lichaam "trommelen" terwijl je samen een liedje zingt.',
    instructions: [
      'Ga op de grond liggen of zitten en nodig je peuter uit om op je buik of benen te tikken.',
      'Zing een eenvoudig liedje (bv. "Klap eens in je handen") en laat je kind mee-trommelen op de maat.',
      'Wissel af: soms snel trommelen, soms langzaam, soms heel zacht, soms iets harder.',
      'Eindig met een knuffel en zeg: "Wat hebben wij lekker samen muziek gemaakt!".',
    ],
    reflection: 'Hoe voelde het lichamelijke contact gecombineerd met muziek? Dit soort spel versterkt de lijfelijke verbinding.',
    scienceNote: 'Ritmische lichamelijke interactie tussen ouder en kind versterkt de affectieve band en synchronisatie (Feldman, 2007, Psychological Bulletin).',
    durationMin: 10,
  },

  // ============================================================
  // AGE GROUP 3-5 (10 tasks)
  // ============================================================
  {
    id: 'aanw_3-5_360',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Verhalenverteller papa',
    description: 'Vertel een zelfverzonnen verhaaltje waarin je kind de hoofdpersoon is.',
    instructions: [
      'Ga samen op een gezellige plek zitten, bijvoorbeeld op de bank met een dekentje.',
      'Begin een verhaal: "Er was eens een dappere [naam kind] die op avontuur ging...".',
      'Verwerk elementen die je kind leuk vindt: favoriete dieren, plekken of speelgoed.',
      'Vraag tussendoor: "En wat denk je dat er toen gebeurde?" en bouw het antwoord in het verhaal in.',
    ],
    reflection: 'Hoe reageerde je kind op het horen van zijn of haar eigen naam in het verhaal? Wat voor elementen voegde het zelf toe?',
    scienceNote: 'Gezamenlijk verhalen vertellen valt binnen Vygotsky\'s zone van naaste ontwikkeling en bevordert narratieve vaardigheden (Vygotsky, 1978, Mind in Society).',
    durationMin: 15,
  },
  {
    id: 'emco_3-5_361',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het gevoelenstekening',
    description: 'Teken samen gezichten met verschillende emoties en bespreek wanneer je die voelt.',
    instructions: [
      'Pak papier en kleurpotloden en teken samen een groot rond gezicht.',
      'Vraag: "Hoe ziet een blij gezicht eruit?" en teken samen de mond, ogen en wenkbrauwen.',
      'Maak ook een boos, verdrietig en bang gezicht. Bespreek bij elk: "Wanneer voel jij je zo?".',
      'Laat je kind een eigen emotiegezicht tekenen en vraag: "Welk gevoel is dit? Vertel eens.".',
    ],
    reflection: 'Welke emotie was het makkelijkst om te tekenen en te bespreken? Welke was lastiger? Dat geeft inzicht in de emotionele woordenschat van je kind.',
    scienceNote: 'Creatieve expressie van emoties vergroot het emotionele vocabulaire en de emotieregulatie bij kleuters (Denham, 1998, Emotional Development in Young Children).',
    durationMin: 15,
  },
  {
    id: 'zelr_3-5_362',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Muzikale standbeelden',
    description: 'Speel het stopspel met muziek: bewegen als de muziek speelt, bevriezen als hij stopt.',
    instructions: [
      'Zet vrolijke kindermuziek aan (telefoon of Bluetooth-speaker).',
      'Beweeg en dans samen wild door de kamer zolang de muziek speelt.',
      'Pauzeer de muziek plotseling en roep "STANDBEELD!" - allebei helemaal stilstaan.',
      'Herhaal minstens zes keer en maak het steeds lastiger door langer te wachten voor je weer aanzet.',
    ],
    reflection: 'Lukte het je kind steeds beter om snel te stoppen? Dit spel traint de remmende controle, een kernaspect van zelfregulatie.',
    scienceNote: 'Stop-signaalspellen verbeteren inhibitiecontrole, een kerncomponent van executieve functies (Diamond & Lee, 2011, Science).',
    durationMin: 10,
  },
  {
    id: 'gren_3-5_363',
    skill: 'Grenzen',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'De puzzelafspraak',
    description: 'Maak samen een puzzel en oefen met de afspraak "eerst denken, dan leggen".',
    instructions: [
      'Kies een puzzel die net uitdagend genoeg is voor je kind (12-24 stukjes).',
      'Maak de afspraak: "We pakken steeds een stukje, kijken goed, en leggen het dan pas neer.".',
      'Help je kind door vragen te stellen: "Welke kleur zie je? Waar zou dat passen?".',
      'Als je kind gefrustreerd raakt, herinner aan de afspraak: "Rustig, eerst kijken, dan proberen. Geen haast.".',
    ],
    reflection: 'Hoe ging je kind om met stukjes die niet meteen pasten? Kon het de afspraak "eerst denken" volhouden?',
    scienceNote: 'Puzzels stimuleren ruimtelijk redeneren en probleemoplossend denken in Piagets pre-operationele fase (Levine et al., 2012, Developmental Science).',
    durationMin: 15,
  },
  {
    id: 'auto_3-5_364',
    skill: 'Autonomie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Jouw eigen kasteel',
    description: 'Laat je kind zelf een bouwwerk ontwerpen met blokken, kussens of dozen.',
    instructions: [
      'Verzamel bouwmaterialen: blokken, kussens, lege dozen, dekens.',
      'Zeg: "Jij bent de architect! Wat wil je bouwen? Een kasteel, een huis, een ruimteschip?".',
      'Laat je kind de leiding nemen. Help alleen als je kind erom vraagt.',
      'Bewonder het resultaat en vraag: "Vertel eens over wat je hebt gebouwd. Wie woont hier?".',
    ],
    reflection: 'Hoe voelde het om je kind de leiding te geven? Was het lastig om niet in te grijpen? Autonomie groeit als wij een stap terug doen.',
    scienceNote: 'Constructiespel bevordert ruimtelijk inzicht, planning en creativiteit en sluit aan bij Piagets constructivisme (Piaget, 1962, Play, Dreams and Imitation in Childhood).',
    durationMin: 15,
  },
  {
    id: 'hers_3-5_365',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het sorry-liedje',
    description: 'Verzin samen een kort liedje over sorry zeggen en opnieuw beginnen.',
    instructions: [
      'Vertel je kind: "Soms gaat er iets mis en dat is oké. Daar gaan we een liedje over maken!".',
      'Bedenk samen een simpele tekst, bijvoorbeeld op de melodie van "Altijd is Kortjakje ziek": "Soms word ik boos, dat kan gebeuren, dan zeg ik sorry, laten we het goedmaken.".',
      'Zing het liedje samen een paar keer en doe er bewegingen bij (hand op het hart bij "sorry").',
      'Spreek af: "Als een van ons sorry wil zeggen, mogen we dit liedje zingen.".',
    ],
    reflection: 'Hoe reageerde je kind op het idee dat fouten maken normaal is? Een herstelritueel maakt sorry zeggen makkelijker.',
    scienceNote: 'Herstelrituelen na conflicten versterken de veilige hechting en leren kinderen dat relaties tegen een stootje kunnen (Tronick, 2007, The Neurobehavioral and Social-Emotional Development of Infants and Children).',
    durationMin: 10,
  },
  {
    id: 'verb_3-5_366',
    skill: 'Verbinding',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen een lied kiezen',
    description: 'Luister samen naar drie kinderliedjes en kies samen jullie "vader-kind-lied".',
    instructions: [
      'Speel drie verschillende kinderliedjes af die je kind leuk zou kunnen vinden.',
      'Luister samen naar elk liedje en dans of beweeg er even op.',
      'Vraag na elk liedje: "Hoe vind je deze? Leuk of niet zo leuk?".',
      'Kies samen het lievelingsliedje en verklaar het tot "ons speciale vader-kind-lied" dat jullie vaker samen zingen.',
    ],
    reflection: 'Wat zegt de keuze van je kind over wat het aanspreekt? Een gedeeld liedje wordt een verbindend ritueel.',
    scienceNote: 'Gedeelde muzikale rituelen versterken de ouder-kindband en creeren een gevoel van "wij" (Cirelli et al., 2014, Developmental Science).',
    durationMin: 10,
  },
  {
    id: 'refl_3-5_367',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het droomverhaal',
    description: 'Vraag je kind naar een droom of fantasie en schrijf het samen op als een verhaaltje.',
    instructions: [
      'Vraag op een rustig moment: "Heb je iets leuks gedroomd? Of iets geks? Of wil je een verhaal verzinnen?".',
      'Schrijf of teken mee terwijl je kind vertelt. Stel open vragen: "En toen? Wie was erbij?".',
      'Lees het verhaal samen terug en vraag: "Hoe voelde dat in de droom? Was het spannend of fijn?".',
      'Bewaar het verhaaltje en lees het later samen nog eens terug.',
    ],
    reflection: 'Wat viel je op aan het verhaal of de droom van je kind? Kinderen verwerken via fantasie vaak echte ervaringen en gevoelens.',
    scienceNote: 'Narratieve expressie helpt kleuters om ervaringen te organiseren en emotioneel te verwerken (Bruner, 1990, Acts of Meaning).',
    durationMin: 15,
  },
  {
    id: 'aanw_3-5_368',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het fluisterverhaal',
    description: 'Vertel een verhaal volledig fluisterend en merk hoe de aandacht van je kind verscherpt.',
    instructions: [
      'Ga dicht bij je kind zitten en zeg: "Ik ga je een geheim verhaaltje vertellen, maar alleen fluisterend.".',
      'Begin zachtjes te fluisteren: een kort avontuurverhaal met spanning (bv. een dier dat iets zoekt in het bos).',
      'Bouw spanningsmomenten in door nog zachter te fluisteren of juist een korte pauze in te lassen.',
      'Eindig het verhaal en vraag fluisterend: "Wat vond je het spannendste stukje?".',
    ],
    reflection: 'Merkte je dat fluisteren de aandacht van je kind juist vergrootte? Stilte en nabijheid zijn krachtige vormen van aanwezigheid.',
    scienceNote: 'Fluisterend voorlezen vergroot auditieve aandacht en nabijheidsbeleving, wat de hechtingsrelatie versterkt (Bowlby, 1988, A Secure Base).',
    durationMin: 10,
  },
  {
    id: 'zelr_3-5_369',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'De langzame tekenaar',
    description: 'Teken samen een tekening in slow motion en oefen met geduld en controle.',
    instructions: [
      'Pak een groot vel papier en dikke stiften.',
      'Leg uit: "We gaan heel langzaam tekenen. Elke lijn duurt minstens vijf tellen.".',
      'Tel samen hardop terwijl je allebei een lijn trekt: "Een... twee... drie... vier... vijf.".',
      'Bouw het op: eerst lijnen, dan vormen, dan een heel plaatje. Bespreek hoe het voelt om langzaam te werken.',
    ],
    reflection: 'Was het moeilijk voor je kind (of voor jou) om zo langzaam te tekenen? Bewuste vertraging traint impulscontrole en mindfulness.',
    scienceNote: 'Bewuste vertraging van motorische handelingen versterkt de prefrontale cortexfuncties die betrokken zijn bij zelfregulatie (Blair & Razza, 2007, Developmental Psychology).',
    durationMin: 15,
  },

  // ============================================================
  // AGE GROUP 6-9 (10 tasks)
  // ============================================================
  {
    id: 'aanw_6-9_370',
    skill: 'Aanwezigheid',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Het voorleesuurtje',
    description: 'Lees samen een hoofdstuk uit een boek en bespreek het verhaal als gelijkwaardige lezers.',
    instructions: [
      'Kies samen een boek dat net boven het leesniveau van je kind ligt (bv. Dolfje Weerwolfje, De Waanzinnige Boomhut).',
      'Lees om de beurt een stuk voor: jij de moeilijke passages, je kind de makkelijkere.',
      'Pauzeer bij spannende momenten en vraag: "Wat denk je dat er gaat gebeuren?".',
      'Bespreek na het hoofdstuk: "Wie was jouw favoriete personage vandaag? Waarom?".',
    ],
    reflection: 'Hoe was het om samen te lezen in plaats van alleen voor te lezen? Gedeeld lezen creert een gelijkwaardig moment van verbinding.',
    scienceNote: 'Dialogisch lezen waarbij het kind actief participeert versterkt begrijpend lezen en woordenschat (Whitehurst et al., 1988, Developmental Psychology).',
    durationMin: 15,
  },
  {
    id: 'emco_6-9_371',
    skill: 'Emotiecoaching',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het emotiemuziekstuk',
    description: 'Luister samen naar een klassiek muziekstuk en bespreek welke emoties de muziek oproept.',
    instructions: [
      'Kies een gevarieerd klassiek stuk (bv. Peer Gynt Suite van Grieg of Carnival of the Animals van Saint-Saens).',
      'Luister samen met gesloten ogen naar een fragment van twee tot drie minuten.',
      'Vraag: "Welk gevoel krijg je bij deze muziek? Blij, verdrietig, spannend, boos?".',
      'Luister naar een tweede fragment met een andere sfeer en vergelijk: "Welke emotie voelde je nu? Was het anders?".',
    ],
    reflection: 'Waren jullie emoties bij de muziek hetzelfde of verschillend? Het bespreken van emoties via muziek is laagdrempelig en verdiepend.',
    scienceNote: 'Muziek activeert het limbisch systeem en biedt een veilige context om emoties te herkennen en bespreken (Juslin & Sloboda, 2010, Handbook of Music and Emotion).',
    durationMin: 15,
  },
  {
    id: 'zelr_6-9_372',
    skill: 'Zelfregulatie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het geduldige bouwwerk',
    description: 'Bouw samen een complex LEGO- of knutselproject waarbij je kind de instructies volgt.',
    instructions: [
      'Kies een bouwproject dat minstens 30 minuten duurt maar in etappes kan (LEGO-set, maquette, origami).',
      'Spreek af dat jullie elke stap rustig lezen voor je begint te bouwen.',
      'Als je kind gefrustreerd raakt, pauzeer en zeg: "Even ademhalen. Welke stap zijn we? Laten we die opnieuw bekijken.".',
      'Vier het resultaat en reflecteer: "Het was soms lastig, maar je bent doorgegaan. Dat is doorzettingsvermogen.".',
    ],
    reflection: 'Hoe ging je kind om met frustratie tijdens het bouwen? Het leren verdragen van frustratie is een cruciale vaardigheid.',
    scienceNote: 'Het volhouden bij uitdagende taken ontwikkelt frustratietolerantie en executieve functies (Mischel, Shoda & Rodriguez, 1989, Science).',
    durationMin: 15,
  },
  {
    id: 'gren_6-9_373',
    skill: 'Grenzen',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het spelregelontwerp',
    description: 'Verzin samen een bordspel met eigen regels en leer over eerlijk spel en grenzen.',
    instructions: [
      'Pak een groot vel papier, stiften en een dobbelsteen.',
      'Ontwerp samen een speelbord met start, finish en vakjes met opdrachten.',
      'Stel samen de regels op: "Wat mag wel? Wat mag niet? Wat gebeurt er als je vals speelt?".',
      'Speel het spel en houd je strikt aan de regels die jullie samen hebben gemaakt.',
    ],
    reflection: 'Hoe ging het om regels te bedenken en je er dan aan te houden? Kinderen die meedenken over regels respecteren ze beter.',
    scienceNote: 'Kinderen die betrokken worden bij het opstellen van regels internaliseren deze beter en vertonen meer zelfregulatie (Piaget, 1932, The Moral Judgment of the Child).',
    durationMin: 15,
  },
  {
    id: 'auto_6-9_374',
    skill: 'Autonomie',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Het eigen stripverhaal',
    description: 'Laat je kind een kort stripverhaal maken en help alleen als het erom vraagt.',
    instructions: [
      'Geef je kind een vel papier, verdeeld in zes vakjes (twee rijen van drie).',
      'Zeg: "Bedenk een kort verhaal en teken het als stripverhaal. Ik ben benieuwd!".',
      'Ga iets anders doen in de buurt, maar blijf beschikbaar als je kind hulp nodig heeft.',
      'Vraag na afloop je kind om het stripverhaal aan je "voor te lezen" en toon oprechte interesse.',
    ],
    reflection: 'Kon je het weerstaan om mee te sturen? Kinderen die creatief zelfstandig werken ontwikkelen intrinsieke motivatie.',
    scienceNote: 'Autonomie-ondersteunend ouderschap bevordert intrinsieke motivatie en creativiteit (Grolnick & Ryan, 1989, Journal of Personality and Social Psychology).',
    durationMin: 15,
  },
  {
    id: 'hers_6-9_375',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het herstelverhaal',
    description: 'Vertel een verhaal over een personage dat een fout maakt en het weer goedmaakt.',
    instructions: [
      'Vertel: "Ik ga je een verhaal vertellen over iemand die een fout maakt. Luister goed.".',
      'Vertel over een personage (bv. een ridder, een dier) dat per ongeluk iemand verdrietig maakt.',
      'Vraag halverwege: "Wat zou het personage kunnen doen om het goed te maken?".',
      'Bouw het antwoord van je kind in het verhaal in en rond af met een positieve afloop.',
    ],
    reflection: 'Welke herstelideeeen had je kind? Verhalen zijn een veilige manier om over fouten en herstel te praten.',
    scienceNote: 'Narratieve therapietechnieken helpen kinderen om probleemoplossing en herstelstrategieen te oefenen (White & Epston, 1990, Narrative Means to Therapeutic Ends).',
    durationMin: 10,
  },
  {
    id: 'verb_6-9_376',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Het duetlied',
    description: 'Kies een liedje en zing het als een duet: jij het ene couplet, je kind het andere.',
    instructions: [
      'Kies samen een liedje dat je kind kent (schoolliedje, popliedje, of Disney-nummer).',
      'Verdeel de coupletten: "Ik zing het eerste stuk, jij het tweede, en het refrein samen!".',
      'Oefen het twee keer, de tweede keer met meer gevoel en eventueel bewegingen erbij.',
      'Neem het op met je telefoon als je kind dat wil, en luister het samen terug.',
    ],
    reflection: 'Hoe voelde het om samen te zingen? Muziek maken met iemand creert een unieke vorm van synchronisatie en verbinding.',
    scienceNote: 'Samen zingen synchroniseert hartritmes en verhoogt oxytocineafgifte, wat de sociale band versterkt (Keeler et al., 2015, Frontiers in Psychology).',
    durationMin: 10,
  },
  {
    id: 'refl_6-9_377',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het uitvindersboek',
    description: 'Begin samen een "uitvindersboek" waarin je kind ideeen voor uitvindingen tekent en beschrijft.',
    instructions: [
      'Geef je kind een leeg schrift en zeg: "Dit is jouw uitvindersboek. Hierin schrijf je al je ideeen.".',
      'Bedenk samen de eerste uitvinding. Stel vragen: "Welk probleem wil je oplossen? Hoe zou je machine eruitzien?".',
      'Laat je kind de uitvinding tekenen en er een korte beschrijving bij schrijven.',
      'Reflecteer samen: "Wat zou er moeilijk zijn om dit echt te maken? Hoe zou je dat oplossen?".',
    ],
    reflection: 'Welk soort problemen wil je kind oplossen? De uitvindingen vertellen veel over waar je kind mee bezig is.',
    scienceNote: 'Uitvindend leren stimuleert metacognitie en probleemoplossend denken in de concreet-operationele fase (Piaget, 1964; Hmelo-Silver, 2004, Educational Psychology Review).',
    durationMin: 15,
  },
  {
    id: 'emco_6-9_378',
    skill: 'Emotiecoaching',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Rollenspel moeilijke situaties',
    description: 'Speel samen een moeilijke sociale situatie na en oefen verschillende reacties.',
    instructions: [
      'Vraag je kind: "Is er iets lastigs gebeurd op school of met vriendjes deze week?".',
      'Stel voor: "Zullen we het naspelen? Ik ben de ander, jij bent jezelf.".',
      'Speel de situatie na. Pauzeer en vraag: "Hoe voelde dat? Wat zou je ook kunnen zeggen of doen?".',
      'Speel het opnieuw met de nieuwe aanpak en bespreek: "Hoe voelde deze reactie anders?".',
    ],
    reflection: 'Welke alternatieve reactie voelde het beste voor je kind? Rollenspel biedt een veilige oefenruimte voor emotionele vaardigheden.',
    scienceNote: 'Rollenspel ontwikkelt sociaal-cognitieve vaardigheden en empathie via perspectief wisselen (Selman, 1980, The Growth of Interpersonal Understanding).',
    durationMin: 15,
  },
  {
    id: 'gren_6-9_379',
    skill: 'Grenzen',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het raadseltijdspel',
    description: 'Los samen raadsels op met een tijdslimiet en oefen met omgaan met tijdsdruk.',
    instructions: [
      'Zoek vijf leeftijdsgeschikte raadsels of denkpuzzels (bv. uit een raadselboek of online).',
      'Zet een timer op twee minuten per raadsel en leg uit: "We hebben twee minuten. Daarna gaan we naar de volgende.".',
      'Los samen op. Als de tijd om is en het niet gelukt is, zeg: "Jammer, maar we gaan verder. Soms moet je iets loslaten.".',
      'Bespreek na afloop: "Hoe voelde de tijdsdruk? Was het spannend of vervelend?".',
    ],
    reflection: 'Hoe reageerde je kind op het niet-afkrijgen? Leren omgaan met grenzen, ook tijdsgrenzen, is een waardevolle vaardigheid.',
    scienceNote: 'Tijdsgebonden taken leren kinderen omgaan met beperkingen en bevorderen cognitieve flexibiliteit (Zelazo et al., 2003, Monographs of the Society for Research in Child Development).',
    durationMin: 15,
  },

  // ============================================================
  // AGE GROUP 10-12 (10 tasks)
  // ============================================================
  {
    id: 'aanw_10-12_380',
    skill: 'Aanwezigheid',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Het leesmaatje',
    description: 'Lees allebei hetzelfde boek en bespreek het als een vader-kind boekenclub.',
    instructions: [
      'Kies samen een boek dat jullie allebei aanspreekt (bv. een avonturenroman of een grappig boek).',
      'Spreek af om deze week allebei de eerste drie hoofdstukken te lezen.',
      'Plan een vast moment om erover te praten: "Wat vond je ervan? Welk personage vind je het interessantst?".',
      'Deel ook jouw mening: "Ik vond dit deel verrassend, omdat..." Wees een gelijkwaardige gesprekspartner.',
    ],
    reflection: 'Hoe was het om met je kind over een boek te praten als gelijken? Dit soort gesprekken bouwen een intellectuele band op.',
    scienceNote: 'Gedeelde leesactiviteiten in de middelbare kindertijd bevorderen leesmotivatie en de ouder-kindrelatie (Baker, Scher & Mackler, 1997, Reading Research Quarterly).',
    durationMin: 15,
  },
  {
    id: 'emco_10-12_381',
    skill: 'Emotiecoaching',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'De emotieplaylist',
    description: 'Maak samen een playlist met liedjes voor verschillende stemmingen.',
    instructions: [
      'Pak je telefoon en open een muziekapp.',
      'Zeg: "We gaan een playlist maken. Voor elke stemming een liedje: blij, verdrietig, boos, ontspannen, energiek.".',
      'Laat je kind voor elke stemming een liedje kiezen. Kies er zelf ook een en leg uit waarom.',
      'Luister samen naar de playlist en bespreek: "Wanneer zou je dit liedje aanzetten? Helpt muziek jou met je gevoelens?".',
    ],
    reflection: 'Welke liedkeuzes verraste je? Muziekvoorkeuren geven een venster op het emotionele leven van je kind.',
    scienceNote: 'Muziekluisteren wordt door adolescenten actief gebruikt als emotieregulatiestrategie (Saarikallio & Erkkila, 2007, Nordic Journal of Music Therapy).',
    durationMin: 15,
  },
  {
    id: 'zelr_10-12_382',
    skill: 'Zelfregulatie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'De strategiepuzzel',
    description: 'Speel samen een strategiespel en reflecteer op planning en impulsbeheersing.',
    instructions: [
      'Kies een strategiespel: schaken, dammen, Stratego, of een kaartspel als Set.',
      'Speel een potje en denk hardop na over je zetten: "Ik overweeg dit, maar als ik dat doe, dan kan jij...".',
      'Moedig je kind aan ook hardop te denken. Vraag: "Waarom koos je die zet? Wat had je ook kunnen doen?".',
      'Reflecteer na afloop: "Welke zet was het slimst? Was er een moment dat je te snel reageerde?".',
    ],
    reflection: 'Hoe verliep het hardop nadenken? Metacognitie, nadenken over je eigen denken, is een hogere vorm van zelfregulatie.',
    scienceNote: 'Strategiespellen bevorderen planningsvermogen, werkgeheugen en metacognitieve vaardigheden (Bart, 2014, Frontiers in Psychology; Sala & Gobet, 2016, Educational Research Review).',
    durationMin: 15,
  },
  {
    id: 'gren_10-12_383',
    skill: 'Grenzen',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het debat',
    description: 'Voer een respectvol debat over een stelling en oefen met grenzen in een discussie.',
    instructions: [
      'Bedenk een leuke stelling, bv. "Huisdieren zijn beter dan geen huisdieren" of "Voetbal is leuker dan basketbal".',
      'Verdeel de rollen: een is voor, de ander is tegen (ongeacht je echte mening).',
      'Stel debatregels op: laat de ander uitpraten, geen schelden, gebruik argumenten, maximaal twee minuten per beurt.',
      'Voer het debat en bespreek na afloop: "Hoe was het om je aan de regels te houden, ook als je het niet eens was?".',
    ],
    reflection: 'Lukte het om respectvol van mening te verschillen? Debatteren leert grenzen respecteren in communicatie.',
    scienceNote: 'Constructieve argumentatie in de ouder-kindrelatie bevordert kritisch denken en sociale vaardigheden (Kuhn, 2005, Education and the Skills of Thinking).',
    durationMin: 15,
  },
  {
    id: 'auto_10-12_384',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het eigen project',
    description: 'Help je kind een creatief project plannen en zelfstandig uitvoeren.',
    instructions: [
      'Vraag: "Als je een project mocht doen deze week, wat zou je dan kiezen? Een tekening, een verhaal, een bouwwerk, een experiment?".',
      'Help bij het plannen: "Wat heb je nodig? Hoeveel tijd denk je dat het kost? Wanneer ga je eraan werken?".',
      'Laat je kind het project zelfstandig uitvoeren. Check af en toe in: "Hoe gaat het? Kan ik ergens mee helpen?".',
      'Wanneer het klaar is, bekijk het samen en vraag: "Waar ben je het meest trots op? Wat zou je volgende keer anders doen?".',
    ],
    reflection: 'Hoe voelde het om je kind een eigen project te laten doen? Zelfstandig creatief werk bouwt zelfvertrouwen en planningsvaardigheden.',
    scienceNote: 'Projectmatig werken bevordert zelfsturing en een groeimindset bij kinderen in de late kindertijd (Dweck, 2006, Mindset: The New Psychology of Success).',
    durationMin: 15,
  },
  {
    id: 'hers_10-12_385',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Het foutenverhaal',
    description: 'Deel een eigen fout uit je verleden en bespreek hoe je het hebt hersteld.',
    instructions: [
      'Zeg: "Ik wil je iets vertellen over een keer dat ik een fout maakte toen ik jong was.".',
      'Vertel een echt verhaal: wat je deed, hoe het misging, en hoe je je voelde.',
      'Vertel ook hoe je het hebt opgelost of goedgemaakt.',
      'Vraag: "Heb jij zoiets ook weleens meegemaakt? Hoe heb je dat opgelost?".',
    ],
    reflection: 'Hoe reageerde je kind op jouw kwetsbaarheid? Vaders die fouten delen, normaliseren onvolmaaktheid en moedigen openheid aan.',
    scienceNote: 'Ouderlijke zelfonthulling over eigen fouten normaliseert imperfectie en versterkt het vertrouwen in de relatie (Gottman & DeClaire, 1997, The Heart of Parenting).',
    durationMin: 10,
  },
  {
    id: 'verb_10-12_386',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het samenwerk-kunstwerk',
    description: 'Maak samen een kunstwerk waarbij jullie om de beurt een element toevoegen.',
    instructions: [
      'Pak een groot vel papier of canvas en verf, stiften of kleurpotloden.',
      'Spreek af: "We tekenen om de beurt. Ik begin met iets, en jij bouwt erop verder, en zo door.".',
      'Begin met een eenvoudige vorm of lijn. Laat je kind iets toevoegen. Ga zo vijf rondes door.',
      'Bekijk het eindresultaat samen en geef het een titel. Hang het op in huis.',
    ],
    reflection: 'Hoe was het om geen controle te hebben over het eindresultaat? Dit kunstwerk is letterlijk een co-creatie, net als jullie relatie.',
    scienceNote: 'Collaboratieve kunstactiviteiten bevorderen wederzijds respect en gedeeld eigenaarschap in de ouder-kindrelatie (Malchiodi, 2011, Handbook of Art Therapy).',
    durationMin: 15,
  },
  {
    id: 'refl_10-12_387',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'De tijdcapsule-brief',
    description: 'Schrijf allebei een brief aan je toekomstige zelf en bewaar hem voor over een jaar.',
    instructions: [
      'Pak allebei papier en een pen. Zeg: "We schrijven een brief aan onszelf over een jaar.".',
      'Schrijf op: wat je nu leuk vindt, wat je bezighoudt, een wens voor het komende jaar.',
      'Lees de brieven niet aan elkaar voor; doe ze in een envelop met de datum van volgend jaar.',
      'Bespreek: "Hoe denk je dat je over een jaar terugkijkt op deze brief? Wat zou er veranderd zijn?".',
    ],
    reflection: 'Hoe was het om na te denken over jezelf in de toekomst? Dit oefent perspectief nemen over de tijd.',
    scienceNote: 'Toekomstgericht denken stimuleert identiteitsontwikkeling en zelfreflectie in de preadolescentie (Harter, 2012, The Construction of the Self).',
    durationMin: 15,
  },
  {
    id: 'refl_10-12_388',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het dilemmakaartspel',
    description: 'Bespreek morele dilemma\'s en denk samen na over wat "het juiste" is.',
    instructions: [
      'Schrijf vijf morele dilemma\'s op kaartjes (bv. "Je vriend spiekt bij een toets. Wat doe je?" of "Je vindt geld op straat. Houd je het?").',
      'Trek om de beurt een kaartje en bespreek: "Wat zou jij doen? Waarom?".',
      'Stel doorvragen: "Maar wat als... Zou het anders zijn als... Hoe zou de ander zich voelen?".',
      'Sluit af: "Er is niet altijd een goed antwoord. Het gaat erom dat je nadenkt over waarom je iets kiest.".',
    ],
    reflection: 'Welk dilemma vond je kind het moeilijkst? Moreel redeneren verdiept zich door er open over te praten.',
    scienceNote: 'Morele dilemmagesprekken stimuleren het moreel redeneren conform Kohlbergs stadia van morele ontwikkeling (Kohlberg, 1981, The Philosophy of Moral Development).',
    durationMin: 15,
  },
  {
    id: 'auto_10-12_389',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'De codeertaak',
    description: 'Laat je kind je uitleggen hoe iets digitaals werkt, of ontdek het samen.',
    instructions: [
      'Kies een eenvoudige digitale activiteit: een Scratch-project, een website bouwen, of een puzzelapp.',
      'Als je kind hier al mee bezig is, vraag: "Kun je mij laten zien hoe dit werkt? Leg het me uit alsof ik er niks van weet.".',
      'Als het nieuw is voor jullie allebei, ontdek het samen. Laat je kind de leiding nemen.',
      'Zeg: "Ik vind het knap dat jij dit snapt" of "Wat goed dat we dit samen uitzoeken.".',
    ],
    reflection: 'Hoe voelde het om je kind de expert te laten zijn? Rolomkering versterkt het zelfvertrouwen en de autonomie.',
    scienceNote: 'Rolomkering waarbij het kind de expert is bevordert zelfeffectiviteit en competentiebeleving (Bandura, 1997, Self-Efficacy: The Exercise of Control).',
    durationMin: 15,
  },

  // ============================================================
  // AGE GROUP 13-16 (10 tasks)
  // ============================================================
  {
    id: 'aanw_13-16_390',
    skill: 'Aanwezigheid',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'De podcastluisteraar',
    description: 'Luister samen naar een podcast die je tiener interessant vindt en bespreek het.',
    instructions: [
      'Vraag je tiener: "Is er een podcast of YouTube-video die je goed vindt? Ik wil het samen bekijken.".',
      'Luister of kijk samen, zonder je telefoon erbij. Geef het je volle aandacht.',
      'Stel oprechte vragen: "Wat vind je hieraan interessant? Hoe ben je hierop gekomen?".',
      'Deel je eigen reactie eerlijk, ook als het niet jouw ding is: "Het is niet wat ik normaal luister, maar ik snap waarom je het boeiend vindt.".',
    ],
    reflection: 'Hoe was het om je te verdiepen in de wereld van je tiener? Aanwezigheid betekent ook: meegaan in hun interesses.',
    scienceNote: 'Ouders die oprechte interesse tonen in de activiteiten van adolescenten versterken de relationele nabijheid (Laursen & Collins, 2009, Handbook of Adolescent Psychology).',
    durationMin: 15,
  },
  {
    id: 'emco_13-16_391',
    skill: 'Emotiecoaching',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het songschrijfgesprek',
    description: 'Bespreek de tekst van een favoriet nummer van je tiener en de emoties erin.',
    instructions: [
      'Vraag: "Welk nummer luister je op het moment het vaakst? Zullen we de tekst eens samen lezen?".',
      'Zoek de songtekst op en lees hem samen door.',
      'Vraag: "Waarom spreekt dit nummer je aan? Herken je je in de tekst?".',
      'Deel ook een eigen ervaring: "Dit doet me denken aan toen ik... De muziek die ik toen luisterde was...".',
    ],
    reflection: 'Wat leerde je over het emotionele leven van je tiener via de muziek? Songteksten zijn vaak een veilige ingang voor diepere gesprekken.',
    scienceNote: 'Muziek fungeert voor adolescenten als identiteitsmarker en emotieregulator (North, Hargreaves & O\'Neill, 2000, Oxford Handbook of Music Psychology).',
    durationMin: 15,
  },
  {
    id: 'zelr_13-16_392',
    skill: 'Zelfregulatie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'De creatieve deadline',
    description: 'Werk samen aan een creatief project met een deadline en bespreek timemanagement.',
    instructions: [
      'Bedenk een gezamenlijk project dat in een uur af moet zijn: een kort filmpje, een fotoserie, een collage.',
      'Plan samen: "We hebben zestig minuten. Hoe verdelen we de tijd? Wat doen we eerst?".',
      'Werk samen met een timer zichtbaar. Halverwege: "We zijn op de helft. Liggen we op schema?".',
      'Reflecteer na afloop: "Hoe ging het plannen? Wat zouden we volgende keer anders doen?".',
    ],
    reflection: 'Hoe ging je tiener om met de tijdsdruk? Leren plannen onder druk is een essentiële vaardigheid voor school en later.',
    scienceNote: 'Tijdmanagementvaardigheden in de adolescentie voorspellen academisch succes en welzijn (Macan et al., 1990, Journal of Educational Psychology).',
    durationMin: 15,
  },
  {
    id: 'gren_13-16_393',
    skill: 'Grenzen',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het grensonderhandeling',
    description: 'Onderhandel samen over een huisregel en oefen met compromissen sluiten.',
    instructions: [
      'Kies een huisregel waar je tiener het niet mee eens is (bv. schermtijd, bedtijd, uitgaan).',
      'Zeg: "Ik wil hier samen over nadenken. Wat is jouw voorstel? Wat zou jij eerlijk vinden?".',
      'Luister echt en stel vragen: "Waarom vind je dat? Wat zou je bereid zijn om er tegenover te zetten?".',
      'Kom samen tot een compromis en schrijf het op. Spreek af om het over twee weken te evalueren.',
    ],
    reflection: 'Hoe voelde het om te onderhandelen in plaats van te dicteren? Tieners die meedenken over grenzen internaliseren ze beter.',
    scienceNote: 'Gezamenlijke besluitvorming over regels in de adolescentie bevordert internalisatie en vermindert verzet (Smetana, 2011, Adolescents, Families, and Social Development).',
    durationMin: 15,
  },
  {
    id: 'auto_13-16_394',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Jouw wereld, jouw uitleg',
    description: 'Laat je tiener je iets leren waar hij of zij veel van weet.',
    instructions: [
      'Zeg: "Ik wil dat jij mij iets leert. Kies iets waar je veel van weet: een game, een hobby, een vak op school.".',
      'Luister aandachtig en stel nieuwsgierige vragen. Probeer echt iets te leren.',
      'Zeg niet: "Dat snap ik niet" maar wel: "Kun je dat nog een keer uitleggen? Ik wil het echt snappen.".',
      'Bedank je tiener: "Dank je. Ik vind het gaaf dat jij hier zoveel van weet.".',
    ],
    reflection: 'Hoe reageerde je tiener op de rol van leraar? Erkenning van expertise is een krachtige vorm van respect.',
    scienceNote: 'Adolescenten die ervaren dat hun competentie erkend wordt, ontwikkelen een sterker gevoel van identiteit en eigenwaarde (Erikson, 1968, Identity: Youth and Crisis).',
    durationMin: 15,
  },
  {
    id: 'hers_13-16_395',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het eerlijke gesprek',
    description: 'Breng een onopgelost conflict ter sprake en werk samen aan herstel.',
    instructions: [
      'Kies een moment waarop het rustig is en zeg: "Er is iets dat me dwars zit. Ik wil het graag uitpraten.".',
      'Beschrijf je eigen gevoel zonder beschuldigen: "Ik voelde me... toen... omdat...".',
      'Vraag: "Hoe heb jij dat beleefd? Ik wil je kant horen.".',
      'Zoek samen naar een oplossing: "Hoe kunnen we dit in de toekomst anders doen? Wat hebben we allebei nodig?".',
    ],
    reflection: 'Hoe voelde het om kwetsbaar te zijn tegenover je tiener? Herstel begint met de moed om het gesprek aan te gaan.',
    scienceNote: 'Constructieve conflictresolutie in de ouder-adolescentrelatie voorspelt betere relatiektwaliteit en psychologisch welzijn (Branje, 2018, Child Development Perspectives).',
    durationMin: 15,
  },
  {
    id: 'verb_13-16_396',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Het gezamenlijke recept',
    description: 'Kook samen een maaltijd waarbij je tiener het recept kiest en de leiding neemt.',
    instructions: [
      'Zeg: "Jij kiest vanavond het recept. Wat je wilt, ik help mee.".',
      'Laat je tiener het recept opzoeken en de boodschappenlijst maken.',
      'Kook samen. Jij bent de assistent: "Wat moet ik doen? Jij bent de chef.".',
      'Eet samen het resultaat en zeg: "Dit is echt lekker. Goed gedaan, chef.".',
    ],
    reflection: 'Hoe was de dynamiek toen je tiener de leiding had? Samen iets praktisch doen creert verbinding zonder dat het "een gesprek" hoeft te zijn.',
    scienceNote: 'Gezamenlijke activiteiten zijn voor adolescenten vaak een prettigere verbindingsvorm dan directe gesprekken (Offer, 1969; Larson & Richards, 1994, Divergent Realities).',
    durationMin: 15,
  },
  {
    id: 'refl_13-16_397',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het levensvragengesprek',
    description: 'Stel je tiener drie grote levensvragen en deel ook je eigen antwoorden.',
    instructions: [
      'Kies een rustig moment (bv. een autorit, een wandeling) en zeg: "Ik heb drie vragen voor je. Geen goede of foute antwoorden.".',
      'Stel vragen als: "Waar wil je over tien jaar zijn?", "Wat vind je het belangrijkste in het leven?", "Wat zou je veranderen aan de wereld?".',
      'Luister zonder oordeel. Vraag door: "Waarom denk je dat? Hoe ben je daarop gekomen?".',
      'Deel je eigen antwoorden eerlijk en open, inclusief je twijfels.',
    ],
    reflection: 'Wat leerde je over de waarden en dromen van je tiener? Dit soort gesprekken bouwt diepe intellectuele en emotionele verbinding.',
    scienceNote: 'Open filosofische gesprekken ondersteunen identiteitsontwikkeling in de adolescentie (Marcia, 1966, Journal of Personality and Social Psychology; Meeus et al., 1999).',
    durationMin: 15,
  },
  {
    id: 'verb_13-16_398',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het muziekinstrument-experiment',
    description: 'Probeer samen een instrument te leren of experimenteer met digitale muziek.',
    instructions: [
      'Kies samen iets: gitaar, keyboard, ukelele, of een digitale muziek-app (bv. GarageBand).',
      'Zoek een beginnersvideo op YouTube en probeer samen het eerste liedje of de eerste beat te leren.',
      'Lach om de fouten. Zeg: "We zijn allebei beginners, dat is juist leuk.".',
      'Spreek af om het volgende week opnieuw te proberen en kijk of jullie beter worden.',
    ],
    reflection: 'Hoe was het om samen iets niet te kunnen? Gedeelde kwetsbaarheid schept verbinding, juist met tieners.',
    scienceNote: 'Gezamenlijk leren en gedeelde kwetsbaarheid versterken de relationele gelijkwaardigheid die adolescenten zoeken (Steinberg, 2001, Journal of Research on Adolescence).',
    durationMin: 15,
  },
  {
    id: 'hers_13-16_399',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'De brief die je niet verstuurt',
    description: 'Schrijf allebei een brief over iets wat jullie dwars zit, lees ze dan samen.',
    instructions: [
      'Zeg: "We gaan allebei een eerlijke brief schrijven. Over iets wat ons dwars zit in onze relatie, of in het leven. Geen censuur.".',
      'Schrijf tien minuten in stilte. Wees eerlijk maar respectvol.',
      'Lees de brieven aan elkaar voor, zonder onderbrekingen.',
      'Bespreek na het lezen: "Wat raakt je in mijn brief? Wat wil je erover zeggen?" Luister meer dan je praat.',
    ],
    reflection: 'Hoe voelde het om elkaars eerlijke woorden te horen? Schrijven biedt een veiligere ruimte dan spontaan praten.',
    scienceNote: 'Expressief schrijven bevordert emotionele verwerking en kan de relationele communicatie verbeteren (Pennebaker, 1997, Psychological Science).',
    durationMin: 15,
  },
];
