import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_19: InteractiveTask[] = [
  // ─────────────────────────────────────────────────────────
  //  AANWEZIGHEID – 0-2 (6 taken)
  // ─────────────────────────────────────────────────────────
  {
    id: 'aanw_02_51',
    skill: 'Aanwezigheid',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Stil vasthouden',
    description: 'Houd je baby vast zonder iets te doen – geen telefoon, geen tv, alleen jullie twee.',
    instructions: [
      'Pak je baby op en houd hem/haar tegen je borst.',
      'Leg je telefoon weg en zet alle schermen uit.',
      'Adem rustig en voel het gewicht van je baby tegen je lichaam.',
      'Blijf zo minstens vijf minuten zitten en merk op wat je voelt.',
    ],
    reflection: 'Aanwezigheid is geen activiteit – het is er simpelweg zijn. Je baby voelt jouw rust en leert daardoor de wereld te vertrouwen.',
    scienceNote: 'Huid-op-huidcontact verlaagt cortisol bij zowel vader als baby en bevordert de hechtingsrelatie (Feldman et al., 2010).',
    durationMin: 5,
  },
  {
    id: 'aanw_02_52',
    skill: 'Aanwezigheid',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Oogcontact bij de fles',
    description: 'Maak bewust oogcontact met je baby tijdens het voeden.',
    instructions: [
      'Geef je baby de fles of zit erbij terwijl je partner borstvoeding geeft.',
      'Zoek actief oogcontact met je baby terwijl hij/zij drinkt.',
      'Glimlach zacht en praat met rustige, lage stem.',
      'Merk op hoe je baby reageert op jouw blik – knipperen, ontspannen, vasthouden.',
    ],
    reflection: 'Voedingsmomenten zijn hechtingsmomenten. Door oogcontact te maken, word je meer dan alleen de flessen-gever – je wordt een veilige basis.',
    scienceNote: 'Wederzijds oogcontact synchroniseert de hersenactiviteit van ouder en kind en versterkt de hechtingsband (Feldman, 2012).',
    durationMin: 10,
  },
  {
    id: 'aanw_02_53',
    skill: 'Aanwezigheid',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Vloerspel zonder sturing',
    description: 'Ga op de grond bij je baby zitten en volg zijn/haar initiatief zonder te sturen.',
    instructions: [
      'Leg een paar eenvoudige speeltjes neer en ga naast je baby op de grond zitten.',
      'Laat je baby kiezen wat hij/zij wil aanraken of oppakken.',
      'Benoem wat je ziet: "Oh, je pakt de bal!" zonder het spel over te nemen.',
      'Volg minstens tien minuten lang het tempo en de interesse van je baby.',
    ],
    reflection: 'Door te volgen in plaats van te leiden laat je je baby merken: jouw interesses zijn belangrijk voor mij.',
    scienceNote: 'Child-led play verhoogt de kwaliteit van vader-kindinteractie en voorspelt veilige hechting (Grossmann et al., 2002).',
    durationMin: 10,
  },
  {
    id: 'aanw_02_54',
    skill: 'Aanwezigheid',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Ochtendbegroeting',
    description: 'Begin elke ochtend met een bewust welkomritueel voor je baby.',
    instructions: [
      'Ga als eerste naar je baby toe wanneer hij/zij wakker wordt.',
      'Buig je over het bedje en maak oogcontact met een warme glimlach.',
      'Zeg elke ochtend dezelfde zin, bijvoorbeeld: "Goedemorgen, lief kind van mij."',
      'Til je baby rustig op en houd hem/haar even dicht tegen je aan.',
    ],
    reflection: 'Een voorspelbaar ochtendmoment geeft je baby het signaal: ik ben er, elke dag opnieuw.',
    scienceNote: 'Voorspelbare overgangsrituelen verlagen stressreactiviteit bij jonge kinderen en versterken de gehechtheidsrelatie (Fiese et al., 2002).',
    durationMin: 5,
  },
  {
    id: 'aanw_02_55',
    skill: 'Aanwezigheid',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Bewust waarnemen van signalen',
    description: 'Oefen het herkennen en beantwoorden van subtiele signalen van je baby gedurende een heel uur.',
    instructions: [
      'Kies een uur waarin je volledig beschikbaar bent voor je baby.',
      'Observeer actief: hoe beweegt je baby, welke geluiden maakt hij/zij, waar kijkt hij/zij naar?',
      'Probeer elk signaal te beantwoorden – een blik beantwoorden, een geluid herhalen, een handbeweging volgen.',
      'Schrijf na afloop drie signalen op die je herkende en hoe je reageerde.',
    ],
    reflection: 'Sensitiviteit is niet aangeboren – het is een vaardigheid die je traint door bewust te kijken en te reageren.',
    scienceNote: 'Vaderlijke sensitiviteit – het accuraat waarnemen en prompt reageren op signalen – is de sterkste voorspeller van veilige vader-kindhechting (Lucassen et al., 2011).',
    durationMin: 60,
  },
  {
    id: 'aanw_02_56',
    skill: 'Aanwezigheid',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Telefoonvrij speeluur',
    description: 'Plan een volledig telefoonvrij uur met je baby en reflecteer op wat dat met jullie contact doet.',
    instructions: [
      'Zet je telefoon op vliegtuigmodus en leg hem in een andere kamer.',
      'Breng een vol uur door met je baby: spelen, knuffelen, rondlopen, ontdekken.',
      'Merk op wanneer je automatisch naar je telefoon wilt grijpen en keer terug naar het moment.',
      'Beschrijf na afloop het verschil in contact dat je ervoer zonder de afleiding van je telefoon.',
    ],
    reflection: 'Fysieke aanwezigheid zonder mentale aanwezigheid is als een lege stoel. Je baby voelt het verschil.',
    scienceNote: 'Technoference – digitale afleiding tijdens ouder-kindinteractie – is geassocieerd met verminderde responsiviteit en meer gedragsproblemen bij kinderen (McDaniel & Radesky, 2018).',
    durationMin: 60,
  },

  // ─────────────────────────────────────────────────────────
  //  AANWEZIGHEID – 3-5 (6 taken)
  // ─────────────────────────────────────────────────────────
  {
    id: 'aanw_35_51',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen iets bouwen',
    description: 'Bouw samen met je kind iets van blokken, lego of kussens en laat je kind de leiding nemen.',
    instructions: [
      'Pak bouwmateriaal (blokken, lego, kussens) en ga naast je kind zitten.',
      'Vraag: "Wat gaan we bouwen?" en laat je kind het plan maken.',
      'Help alleen als je kind erom vraagt – geef anders aanmoediging.',
      'Bewonder het eindresultaat samen en zeg wat je ervan vindt.',
    ],
    reflection: 'Als je kind de architect is en jij de bouwvakker, leer je het dat zijn/haar ideeën er toe doen.',
    scienceNote: 'Collaboratief spel waarbij het kind de leiding neemt bevordert autonomie en versterkt de ouder-kindrelatie (Ginsburg, 2007).',
    durationMin: 15,
  },
  {
    id: 'aanw_35_52',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Vertel-me-meer-gesprek',
    description: 'Stel je kind open vragen over zijn/haar dag en luister echt naar de antwoorden.',
    instructions: [
      'Kies een rustig moment, bijvoorbeeld na het eten of voor het slapengaan.',
      'Vraag: "Wat was het leukste van je dag?" en luister zonder te onderbreken.',
      'Stel vervolgvragen: "Vertel me meer!" of "Hoe voelde dat?"',
      'Vat samen wat je kind vertelde om te laten merken dat je echt luisterde.',
    ],
    reflection: 'Door oprechte nieuwsgierigheid te tonen leer je je kind: jouw verhaal is belangrijk voor mij.',
    scienceNote: 'Elaboratieve gespreksvoering door ouders versterkt het autobiografisch geheugen en de emotionele ontwikkeling van kinderen (Fivush et al., 2006).',
    durationMin: 10,
  },
  {
    id: 'aanw_35_53',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Fantasiespel meespelen',
    description: 'Stap volledig in de fantasiewereld van je kind en speel mee als personage.',
    instructions: [
      'Wacht tot je kind een fantasiespel begint (doktertje, winkel, superheld) of stel het voor.',
      'Vraag: "Wie ben ik in dit spel?" en accepteer de rol die je krijgt.',
      'Speel minimaal vijftien minuten mee zonder het verhaal te veranderen.',
      'Laat je kind het einde van het spel bepalen.',
    ],
    reflection: 'Voor een kind is fantasiespel bloedserieus. Door mee te spelen zeg je: ik neem jouw wereld serieus.',
    scienceNote: 'Vader-kind fantasiespel stimuleert de Theory of Mind-ontwikkeling en het sociaal begrip van kinderen (Dunn et al., 1991).',
    durationMin: 15,
  },
  {
    id: 'aanw_35_54',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Eén-op-één papa-dag',
    description: 'Plan een activiteit die alleen jij en je kind samen doen, zonder andere gezinsleden.',
    instructions: [
      'Kies samen met je kind een activiteit: naar het park, een wandeling, samen koken.',
      'Zorg dat je minstens een uur ongestoord samen bent.',
      'Laat je kind keuzes maken tijdens de activiteit: welke route, welk gerecht, welke speeltuin.',
      'Sluit af door te zeggen: "Ik vond het fijn om dit samen te doen."',
    ],
    reflection: 'Eén-op-één tijd is de valuta van hechting. Elk kind heeft momenten nodig waarop het de enige is.',
    scienceNote: 'Exclusieve vader-kindtijd is geassocieerd met hogere relatiekwaliteit en minder externaliserende gedragsproblemen (Pleck, 2010).',
    durationMin: 60,
  },
  {
    id: 'aanw_35_55',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Speciaal speelhalfuur',
    description: 'Geef je kind elke dag een vast halfuur onverdeelde aandacht en evalueer dit na een week.',
    instructions: [
      'Kies een vast moment op de dag (bijv. na het avondeten) als "papa-speeltijd".',
      'Laat je kind elke dag kiezen wat jullie doen in dat halfuur.',
      'Doe dit zeven dagen achter elkaar en leg na elke sessie kort vast hoe het ging.',
      'Evalueer na een week: wat merk je in het gedrag en de verbinding met je kind?',
    ],
    reflection: 'Consistentie is de sleutel. Een kort maar dagelijks ritueel bouwt meer hechting op dan incidentele lange activiteiten.',
    scienceNote: 'Dagelijkse voorspelbare ouder-kindinteracties zijn sterker geassocieerd met veilige hechting dan de totale hoeveelheid tijd (Lamb, 2010).',
    durationMin: 30,
  },
  {
    id: 'aanw_35_56',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Kind leidt de wandeling',
    description: 'Laat je kind een wandeling helemaal zelf leiden – tempo, richting, stops – en volg geduldig.',
    instructions: [
      'Ga samen naar buiten en zeg: "Vandaag bepaal jij waar we heen gaan."',
      'Volg het tempo van je kind, ook als dat langzaam is of vol omwegen.',
      'Toon interesse in alles waar je kind stopt: een steen, een insect, een plas.',
      'Weersta de neiging om te zeggen "kom, we gaan verder" – laat je kind het moment bepalen.',
    ],
    reflection: 'Een kind dat leidt en een vader die volgt – dat is de ultieme oefening in aanwezigheid en respect.',
    scienceNote: 'Child-directed activiteiten versterken het gevoel van autonomie en competentie, kernbehoeften uit de zelfdeterminatietheorie (Deci & Ryan, 2000).',
    durationMin: 30,
  },

  // ─────────────────────────────────────────────────────────
  //  EMOTIECOACHING – 0-2 (6 taken)
  // ─────────────────────────────────────────────────────────
  {
    id: 'emco_02_51',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Benoem het huilen',
    description: 'Geef woorden aan het huilen van je baby, ook al begrijpt hij/zij de woorden nog niet.',
    instructions: [
      'Als je baby huilt, ga er rustig naartoe en pak hem/haar op.',
      'Zeg op zachte toon: "Je huilt. Je hebt iets nodig. Papa is er."',
      'Probeer te raden wat het is: honger, moe, natte luier, behoefte aan nabijheid.',
      'Benoem het hardop: "Ik denk dat je moe bent. Laten we samen rustig worden."',
    ],
    reflection: 'Door emoties te benoemen leg je de basis voor emotionele geletterdheid – lang voordat je kind zelf kan praten.',
    scienceNote: 'Affect labeling door ouders activeert de prefrontale cortex en helpt kinderen later emoties te herkennen en reguleren (Lieberman et al., 2007).',
    durationMin: 5,
  },
  {
    id: 'emco_02_52',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Spiegelen van blije gezichten',
    description: 'Spiegel de positieve gezichtsuitdrukkingen van je baby om emotionele verbinding te versterken.',
    instructions: [
      'Wacht op een moment dat je baby lacht, kraait of een blij gezicht trekt.',
      'Spiegel dezelfde uitdrukking terug: lach als je baby lacht, maak grote ogen als je baby verrast kijkt.',
      'Voeg woorden toe: "Wat ben jij blij! Ja, dat is fijn hè!"',
      'Doe dit meerdere keren en merk op hoe je baby reageert op jouw spiegeling.',
    ],
    reflection: 'Spiegelen is de eerste emotiecoaching. Je baby leert: mijn gevoelens worden gezien en beantwoord.',
    scienceNote: 'Contingent spiegelen van affect is essentieel voor de ontwikkeling van emotieregulatie en zelfbewustzijn bij baby\'s (Gergely & Watson, 1996).',
    durationMin: 5,
  },
  {
    id: 'emco_02_53',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Troostprotocol ontwikkelen',
    description: 'Ontdek welke trooststrategieën het beste werken bij jouw baby en maak een persoonlijk protocol.',
    instructions: [
      'Observeer de komende dagen welke trooststrategieën je baby het snelst kalmeren: wiegen, zingen, huid-op-huid, wandelen, sussen.',
      'Rangschik de top drie strategieën die het beste werken.',
      'Probeer deze strategieën bewust en systematisch toe te passen bij het volgende huilmoment.',
      'Bespreek met je partner welke strategieën jullie allebei het effectiefst vinden.',
    ],
    reflection: 'Elke baby is anders. Door te observeren en te experimenteren word je expert in het troosten van jouw kind.',
    scienceNote: 'Sensitieve responsiviteit – het afstemmen van troostgedrag op de individuele behoeften van het kind – is de kern van veilige hechting (Ainsworth et al., 1978).',
    durationMin: 15,
  },
  {
    id: 'emco_02_54',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Emotiedagboek bijhouden',
    description: 'Houd drie dagen lang bij welke emoties je bij je baby waarneemt en hoe je erop reageert.',
    instructions: [
      'Maak een simpel schema: tijdstip, emotie van de baby, jouw reactie.',
      'Noteer minstens drie momenten per dag gedurende drie dagen.',
      'Let op patronen: zijn er vaste tijdstippen waarop je baby prikkelbaar of juist tevreden is?',
      'Reflecteer: wat leer je over de emotionele behoeften van je baby?',
    ],
    reflection: 'Een dagboek dwingt je tot bewust waarnemen. Patronen herkennen is de eerste stap naar effectieve emotiecoaching.',
    scienceNote: 'Ouders die structureel reflecteren op de emoties van hun kind ontwikkelen een hogere mentalisatiecapaciteit (Slade, 2005).',
    durationMin: 15,
  },
  {
    id: 'emco_02_55',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Emoties lezen bij onrust',
    description: 'Oefen het onderscheiden van verschillende soorten huilen en onrust bij je baby.',
    instructions: [
      'Luister de komende week aandachtig naar het huilen van je baby bij verschillende momenten.',
      'Probeer minstens drie soorten huilen te onderscheiden: honger, vermoeidheid, pijn, verveling, overstimulatie.',
      'Noteer de kenmerken: volume, ritme, gezichtsuitdrukking, lichaamshouding.',
      'Test je hypotheses door gericht te reageren en te kijken of je baby sneller kalmeert.',
    ],
    reflection: 'Een vader die het verschil hoort tussen hongerhuilen en vermoeidheidshuilen reageert accurater – en dat voelt je baby.',
    scienceNote: 'Ouders die accuraat onderscheid maken tussen verschillende huilsoorten vertonen hogere sensitiviteit en hun kinderen ontwikkelen veiliger hechting (Leerkes et al., 2009).',
    durationMin: 20,
  },
  {
    id: 'emco_02_56',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Still-face en herstel',
    description: 'Begrijp de kracht van emotionele beschikbaarheid door het still-face-experiment na te bootsen en te herstellen.',
    instructions: [
      'Speel interactief met je baby zoals je normaal doet – lachen, praten, aanraken.',
      'Houd kort (maximaal twintig seconden) een neutraal gezicht zonder te reageren en observeer hoe je baby reageert.',
      'Herstel direct daarna: glimlach, praat, pak je baby op en troost als dat nodig is.',
      'Reflecteer op wat je zag: hoe snel reageerde je baby op het wegvallen van jouw emotionele beschikbaarheid?',
    ],
    reflection: 'Dit experiment toont hoe sterk je baby op jouw emotionele aanwezigheid vertrouwt. Herstel na een breuk is essentieel.',
    scienceNote: 'Het still-face-experiment toont aan dat baby\'s vanaf twee maanden actief emotionele reciprociteit verwachten en stress ervaren bij het wegvallen ervan (Tronick et al., 1978).',
    durationMin: 10,
  },

  // ─────────────────────────────────────────────────────────
  //  EMOTIECOACHING – 3-5 (7 taken)
  // ─────────────────────────────────────────────────────────
  {
    id: 'emco_35_51',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Gevoelenskaarten maken',
    description: 'Maak samen met je kind eenvoudige kaarten met gezichten die verschillende emoties tonen.',
    instructions: [
      'Pak papier en stiften en teken samen gezichten: blij, boos, verdrietig, bang, verrast.',
      'Laat je kind de gezichten kleuren en er een naam aan geven.',
      'Leg de kaarten op tafel en vraag: "Welk gezicht past bij hoe jij je nu voelt?"',
      'Gebruik de kaarten de komende dagen als je kind moeite heeft om gevoelens onder woorden te brengen.',
    ],
    reflection: 'Emoties benoemen wordt makkelijker met visuele hulpmiddelen. Je kind leert: gevoelens hebben een naam.',
    scienceNote: 'Het gebruik van visuele emotielabels vergroot het emotioneel vocabulaire van jonge kinderen en ondersteunt emotieregulatie (Denham, 1998).',
    durationMin: 15,
  },
  {
    id: 'emco_35_52',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Boek over gevoelens lezen',
    description: 'Lees samen een prentenboek over emoties en praat over de gevoelens van de personages.',
    instructions: [
      'Kies een prentenboek waarin een personage duidelijke emoties ervaart.',
      'Lees het boek samen en pauzeer bij de emotionele momenten.',
      'Vraag: "Hoe voelt het konijntje zich hier? Waarom denk je dat?"',
      'Vraag: "Heb jij je ook weleens zo gevoeld?" en luister aandachtig.',
    ],
    reflection: 'Verhalen zijn een veilige manier om over emoties te praten – via een personage durft je kind meer te delen.',
    scienceNote: 'Dialogisch voorlezen over emoties vergroot het emotioneel begrip en de empathie van peuters en kleuters (Aram et al., 2017).',
    durationMin: 15,
  },
  {
    id: 'emco_35_53',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Emotie-thermometer',
    description: 'Introduceer een emotie-thermometer waarmee je kind de intensiteit van gevoelens kan aanwijzen.',
    instructions: [
      'Teken een thermometer op papier met onderin "een beetje" en bovenin "heel erg".',
      'Leg uit: "Als je boos bent, hoe boos? Een beetje of heel erg?"',
      'Oefen samen met voorbeelden: "Als iemand jouw speelgoed afpakt, waar zit je dan op de thermometer?"',
      'Gebruik de thermometer de komende week als je kind een sterke emotie ervaart.',
    ],
    reflection: 'Intensiteit leren herkennen is een cruciale stap. "Een beetje boos" vraagt een andere reactie dan "heel erg boos".',
    scienceNote: 'Het differentiëren van emotie-intensiteit is een kerncomponent van emotieregulatie-ontwikkeling bij kleuters (Izard et al., 2011).',
    durationMin: 15,
  },
  {
    id: 'emco_35_54',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Valideren voor corrigeren',
    description: 'Oefen het eerst valideren van de emotie van je kind voordat je gedrag corrigeert.',
    instructions: [
      'Wacht op een situatie waarin je kind boos of verdrietig reageert op iets.',
      'Zeg eerst: "Ik zie dat je boos/verdrietig bent. Dat mag." Geef hier minstens tien seconden ruimte.',
      'Vraag: "Wat is er gebeurd?" en luister zonder oordeel.',
      'Pas daarna, als je kind rustig is, bespreek je samen wat een betere reactie zou zijn.',
    ],
    reflection: 'Valideren is geen goedkeuren van gedrag – het is erkennen dat een gevoel er mag zijn. Dat maakt correctie daarna effectiever.',
    scienceNote: 'Emotiecoachende ouders die eerst valideren en dan grenzen stellen, hebben kinderen met betere emotieregulatie en minder gedragsproblemen (Gottman et al., 1996).',
    durationMin: 10,
  },
  {
    id: 'emco_35_55',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Papa\'s gevoelens delen',
    description: 'Deel op een leeftijdspassende manier jouw eigen gevoelens met je kind.',
    instructions: [
      'Kies een moment waarop je een duidelijke emotie voelt: moe, blij, gefrustreerd.',
      'Zeg tegen je kind: "Papa voelt zich vandaag een beetje moe. Dat komt door het werk."',
      'Voeg een copingstrategie toe: "Dus papa gaat even rustig zitten om weer energie te krijgen."',
      'Vraag je kind: "En hoe voel jij je vandaag?"',
    ],
    reflection: 'Door jouw emoties te delen leer je je kind twee dingen: emoties zijn normaal en er zijn manieren om ermee om te gaan.',
    scienceNote: 'Ouderlijke emotionele zelfonthulling op leeftijdspassend niveau bevordert de emotionele socialisatie en het empathisch vermogen van kinderen (Denham et al., 2007).',
    durationMin: 5,
  },
  {
    id: 'emco_35_56',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Emotie-detectivespel',
    description: 'Speel samen detective en zoek emoties in het dagelijks leven: bij anderen, in boeken, op tv.',
    instructions: [
      'Leg uit: "Vandaag zijn we emotie-detectives. We gaan kijken welke gevoelens we kunnen ontdekken."',
      'Ga samen naar buiten of kijk samen een programma en wijs emoties aan bij anderen.',
      'Vraag: "Hoe voelt die mevrouw zich denk je? Waaraan zie je dat?"',
      'Maak er een puntensysteem van: elk herkend gevoel levert een punt op.',
    ],
    reflection: 'Emoties herkennen bij anderen is de basis van empathie. Door er een spel van te maken wordt het leuk in plaats van moeilijk.',
    scienceNote: 'Het herkennen van emoties bij anderen (emotion recognition) is een voorspeller van sociale competentie en prosociaal gedrag bij kleuters (Izard et al., 2001).',
    durationMin: 20,
  },
  {
    id: 'emco_35_57',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Emotie-verhaal verzinnen',
    description: 'Verzin samen met je kind een verhaal waarin het hoofdpersonage dezelfde emotie voelt als je kind.',
    instructions: [
      'Denk aan een emotie die je kind recent sterk voelde (boosheid, angst, verdriet, trots).',
      'Begin een verhaal: "Er was eens een kleine beer die heel erg [emotie] was..."',
      'Laat je kind meebeslissen wat er in het verhaal gebeurt en hoe de beer zich voelt.',
      'Eindig samen met een oplossing: "En toen ontdekte de beer dat hij [copingstrategie] kon doen."',
    ],
    reflection: 'Door emoties in een verhaal te gieten krijgt je kind afstand en overzicht – en leert het dat elke emotie een verhaal heeft met een einde.',
    scienceNote: 'Narratieve verwerking van emoties bevordert emotieregulatie en cognitieve herstructurering bij jonge kinderen (Salmon & Bryant, 2002).',
    durationMin: 15,
  },

  // ─────────────────────────────────────────────────────────
  //  ZELFREGULATIE – 0-2 (6 taken)
  // ─────────────────────────────────────────────────────────
  {
    id: 'zelr_02_51',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Drie ademhalingen voor je reageert',
    description: 'Oefen drie diepe ademhalingen te nemen voordat je reageert op het huilen van je baby.',
    instructions: [
      'Als je baby begint te huilen, sta even stil voordat je in actie komt.',
      'Adem drie keer diep in door je neus en langzaam uit door je mond.',
      'Merk op hoe je lichaam zich voelt: schouders, kaak, buik.',
      'Ga daarna pas naar je baby toe en reageer vanuit een rustiger plek.',
    ],
    reflection: 'Drie seconden pauze kan het verschil maken tussen een gestreste reactie en een liefdevolle reactie.',
    scienceNote: 'Diepe ademhaling activeert het parasympathisch zenuwstelsel en verlaagt de cortisolrespons, waardoor ouders sensitiever kunnen reageren (Porges, 2011).',
    durationMin: 5,
  },
  {
    id: 'zelr_02_52',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Stresssignalen herkennen',
    description: 'Leer je eigen stresssignalen herkennen zodat je kunt ingrijpen voordat je overweldigd raakt.',
    instructions: [
      'Denk na over wat er in je lichaam gebeurt als je gestrest bent: strakke kaak, snelle hartslag, zweten.',
      'Schrijf je top drie lichaamssignalen op een briefje en hang het op de koelkast.',
      'Let de komende dagen bewust op deze signalen, vooral bij huilmomenten of slaaptekort.',
      'Als je een signaal opmerkt, zeg tegen jezelf: "Ik merk stress op. Ik ga even pauzeren."',
    ],
    reflection: 'Je kunt pas iets veranderen aan stress als je het op tijd herkent. Je lichaam waarschuwt altijd eerder dan je hoofd.',
    scienceNote: 'Interoceptief bewustzijn – het waarnemen van lichaamssignalen – is geassocieerd met betere emotieregulatie en minder impulsief reageren (Critchley & Garfinkel, 2017).',
    durationMin: 10,
  },
  {
    id: 'zelr_02_53',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Veilig neerleggen en pauzeren',
    description: 'Oefen het veilig neerleggen van je baby als je merkt dat je overweldigd raakt.',
    instructions: [
      'Herken het moment dat je frustratie te hoog oploopt bij aanhoudend huilen.',
      'Leg je baby veilig in het bedje of op een veilige plek.',
      'Loop naar een andere kamer en doe twee minuten iets kalmerends: koud water op je polsen, ademhalen, even naar buiten kijken.',
      'Ga terug als je je rustiger voelt en pak je baby weer op.',
    ],
    reflection: 'Je baby neerleggen is geen falen – het is de meest verantwoorde keuze die je kunt maken als vader wanneer je je grens voelt.',
    scienceNote: 'Het veilig neerleggen en even pauzeren is de aanbevolen strategie van kinderartsen om shaken-babysyndroom te voorkomen (Barr et al., 2009).',
    durationMin: 5,
  },
  {
    id: 'zelr_02_54',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Slaapdeprivatie-noodplan',
    description: 'Maak een concreet plan voor momenten van extreme vermoeidheid zodat je niet impulsief reageert.',
    instructions: [
      'Schrijf op wat je kunt doen als je extreem moe bent en je baby huilt: wie kun je bellen, wat kalmeert je, wat is je noodstrategie?',
      'Bespreek dit plan met je partner of een vertrouwenspersoon.',
      'Leg het plan op een zichtbare plek zodat je het kunt lezen wanneer je het nodig hebt.',
      'Oefen het plan mentaal door: stel je de situatie voor en loop de stappen door.',
    ],
    reflection: 'Een noodplan maken als je helder bent, beschermt je op de momenten dat je dat niet meer bent.',
    scienceNote: 'Proactieve copingplannen verminderen de impact van slaaptekort op ouderlijk functioneren en impulsieve reacties (Meltzer & Mindell, 2007).',
    durationMin: 15,
  },
  {
    id: 'zelr_02_55',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Triggerdagboek bijhouden',
    description: 'Houd een week lang bij welke situaties met je baby je het meest triggeren en zoek patronen.',
    instructions: [
      'Noteer elke dag minstens één moment waarop je frustratie of irritatie voelde bij je baby.',
      'Schrijf op: wat was de situatie, wat dacht je, wat voelde je, hoe reageerde je?',
      'Zoek na een week naar patronen: bepaalde tijdstippen, huilsoorten of omstandigheden.',
      'Maak voor je twee grootste triggers een specifiek actieplan.',
    ],
    reflection: 'Triggers zijn geen zwakte – ze zijn informatie. Hoe beter je ze kent, hoe beter je kunt kiezen hoe je reageert.',
    scienceNote: 'Zelfmonitoring van emotionele triggers vergroot het metacognitief bewustzijn en vermindert automatische reactiepatronen (Gross, 2015).',
    durationMin: 15,
  },
  {
    id: 'zelr_02_56',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Body-scan bij nachtvoedingen',
    description: 'Doe een korte body-scan tijdens nachtvoedingen om je lichaam bewust te ontspannen.',
    instructions: [
      'Als je \'s nachts opstaat voor je baby, begin met drie diepe ademhalingen.',
      'Scan terwijl je de fles geeft of je baby vasthoudt je lichaam van hoofd tot voeten.',
      'Merk spanning op in je schouders, kaak, handen en laat deze bewust los.',
      'Eindig met de gedachte: "Dit moment gaat voorbij. Ik ben er voor mijn kind."',
    ],
    reflection: 'Nachtvoedingen zijn zwaar, maar ze zijn ook intieme momenten. Een body-scan helpt je om er aanwezig voor te zijn in plaats van alleen te overleven.',
    scienceNote: 'Mindfulness-gebaseerde body-scans verlagen stresshormonen en verbeteren de slaapkwaliteit, ook bij korte toepassingen (Hölzel et al., 2011).',
    durationMin: 10,
  },

  // ─────────────────────────────────────────────────────────
  //  ZELFREGULATIE – 3-5 (6 taken)
  // ─────────────────────────────────────────────────────────
  {
    id: 'zelr_35_51',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen ademhalen met de buikbeer',
    description: 'Leer je kind buikademhaling door samen met een knuffel op de buik te ademhalen.',
    instructions: [
      'Ga samen op de grond liggen en leg elk een knuffel op jullie buik.',
      'Zeg: "We gaan de beer laten schommelen. Adem in... de beer gaat omhoog. Adem uit... de beer gaat omlaag."',
      'Doe vijf ademhalingen samen en maak er een spel van.',
      'Gebruik deze techniek later als je kind boos of overstuur is: "Zullen we de beer laten schommelen?"',
    ],
    reflection: 'Ademhaling is de eenvoudigste regulatietechniek die er bestaat. Door er een spel van te maken leert je kind het ongemerkt.',
    scienceNote: 'Diepe buikademhaling activeert de nervus vagus en verlaagt de fysiologische stressrespons bij zowel kinderen als volwassenen (Lehrer & Gevirtz, 2014).',
    durationMin: 10,
  },
  {
    id: 'zelr_35_52',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Pauzeer-en-kies-spel',
    description: 'Oefen het pauzeren voor je reageert door er samen een spel van te maken.',
    instructions: [
      'Leg uit: "We gaan het pauzeer-spel spelen. Als ik STOP zeg, sta je stil als een standbeeld."',
      'Speel het spel: rennen, dansen, bewegen – en dan STOP.',
      'Na het stilstaan vraag je: "Wat ga je nu kiezen om te doen?"',
      'Koppel het later aan echte situaties: "Kun je even pauzeren en kiezen, net als in het spel?"',
    ],
    reflection: 'Impulsen leren remmen is als een spier trainen. Het pauzeer-spel traint die spier op een leuke manier.',
    scienceNote: 'Spellen die executieve functies trainen (inhibitie, werkgeheugen) verbeteren de zelfregulatie van kleuters significant (Diamond & Lee, 2011).',
    durationMin: 10,
  },
  {
    id: 'zelr_35_53',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Rustige-plek samen inrichten',
    description: 'Richt samen met je kind een "rustige plek" in waar het naartoe kan als het zich overweldigd voelt.',
    instructions: [
      'Kies samen een hoekje in huis dat de "rustige plek" wordt.',
      'Laat je kind kiezen wat erin komt: een kussen, een knuffel, een boekje, een kleurplaat.',
      'Leg uit: "Dit is jouw plekje om rustig te worden. Geen straf, maar een fijne plek."',
      'Gebruik de plek samen de eerste keer: ga er samen zitten en doe een ademhalingsoefening.',
    ],
    reflection: 'Een rustige plek is geen time-out maar een time-in. Het leert je kind: ik mag even stoppen als het te veel wordt.',
    scienceNote: 'Een fysieke regulatieplek (calm-down corner) helpt kinderen bij het internaliseren van regulatiestrategieën en verlaagt de behoefte aan externe regulatie (Siegel & Bryson, 2012).',
    durationMin: 20,
  },
  {
    id: 'zelr_35_54',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Woede-vulkaan tekenen',
    description: 'Help je kind begrijpen hoe boosheid opbouwt door samen een woede-vulkaan te tekenen.',
    instructions: [
      'Teken samen een vulkaan met drie zones: groen (rustig), oranje (een beetje boos), rood (uitbarsting).',
      'Bespreek: "Wat voel je als je in het groen bent? En in het oranje?"',
      'Bedenk samen strategieën voor de oranje zone: ademhalen, weglopen, om hulp vragen.',
      'Hang de vulkaan op en verwijs ernaar als je kind boos begint te worden: "Waar zit je nu op de vulkaan?"',
    ],
    reflection: 'Kinderen die leren dat boosheid opbouwt, leren ook dat ze kunnen ingrijpen voordat de vulkaan uitbarst.',
    scienceNote: 'Psycho-educatie over de opbouw van emoties helpt kinderen bij het ontwikkelen van vroegtijdige regulatiestrategieën (Greenberg et al., 1995).',
    durationMin: 15,
  },
  {
    id: 'zelr_35_55',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Vader en kind kalmeerplan',
    description: 'Maak samen met je kind een gezamenlijk kalmeerplan voor als jullie allebei boos zijn.',
    instructions: [
      'Zeg: "Soms word ik ook boos, net als jij. Laten we samen een plan maken."',
      'Schrijf of teken samen de stappen: stoppen, ademhalen, zeggen wat je voelt, een oplossing bedenken.',
      'Oefen het plan door een denkbeeldig scenario door te spelen.',
      'Spreek af: "Als een van ons boos wordt, zeggen we: laten we ons plan gebruiken."',
    ],
    reflection: 'Een gezamenlijk kalmeerplan maakt regulatie tot een teameffort. Je kind leert: papa worstelt ook en we lossen het samen op.',
    scienceNote: 'Gezamenlijke emotieregulatie-strategieën versterken de co-regulatie en het vertrouwen in de ouder-kindrelatie (Eisenberg et al., 1998).',
    durationMin: 20,
  },
  {
    id: 'zelr_35_56',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Reflectiegesprek na een boze bui',
    description: 'Voer na een boze bui van je kind (of van jezelf) een reflectiegesprek over wat er gebeurde.',
    instructions: [
      'Wacht tot jullie allebei weer rustig zijn (minstens twintig minuten na het incident).',
      'Begin met: "Wat gebeurde er net? Hoe voelde jij je?"',
      'Deel ook jouw ervaring: "Ik merkte dat ik ook boos werd. Dat was niet fijn."',
      'Eindig met: "Wat kunnen we de volgende keer anders doen?" en schrijf het samen op.',
    ],
    reflection: 'Reflecteren na een conflict is krachtiger dan straffen. Het leert je kind dat fouten leermomenten zijn, geen eindpunten.',
    scienceNote: 'Post-conflict reflectie bevordert metacognitie en emotioneel leren, en is effectiever dan straf voor het verminderen van herhaling van ongewenst gedrag (Gottman, 1997).',
    durationMin: 15,
  },

  // ─────────────────────────────────────────────────────────
  //  GRENZEN – 0-2 (7 taken)
  // ─────────────────────────────────────────────────────────
  {
    id: 'gren_02_51',
    skill: 'Grenzen',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Rustig nee zeggen',
    description: 'Oefen het rustig en liefdevol "nee" zeggen als je baby iets gevaarlijks doet.',
    instructions: [
      'Wacht op een moment dat je baby iets pakt of doet dat niet mag (aan een snoer trekken, iets in de mond stoppen).',
      'Zeg kalm en vriendelijk: "Nee, dat is niet voor jou" met een rustige stem.',
      'Verplaats je baby zachtjes weg van het gevaar of neem het voorwerp weg.',
      'Bied direct een alternatief: "Hier, pak deze maar" en geef iets dat wél mag.',
    ],
    reflection: 'Een grens stellen bij een baby gaat niet over gehoorzaamheid maar over veiligheid. De toon is belangrijker dan de woorden.',
    scienceNote: 'Jonge kinderen begrijpen toon en lichaamstaal eerder dan woorden – een kalme, consequente toon is effectiever dan een strenge (Kochanska, 2002).',
    durationMin: 5,
  },
  {
    id: 'gren_02_52',
    skill: 'Grenzen',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Omgeving babyveilig maken',
    description: 'Maak een deel van je huis volledig babyveilig zodat je minder "nee" hoeft te zeggen.',
    instructions: [
      'Loop door je woonkamer op handen en knieën en bekijk de ruimte vanuit het perspectief van je baby.',
      'Verwijder of beveilig alles wat gevaarlijk of verboden is: stopcontacten, scherpe hoeken, kleine voorwerpen.',
      'Creëer een zone waar je baby vrij kan ontdekken zonder dat je constant hoeft in te grijpen.',
      'Tel hoeveel keer je "nee" zegt in een uur – in een babyveilige omgeving zou dat minder moeten zijn.',
    ],
    reflection: 'De beste grens is een onzichtbare grens. Hoe veiliger de omgeving, hoe meer je baby kan ontdekken en hoe minder conflicten er zijn.',
    scienceNote: 'Omgevingsaanpassing (environmental scaffolding) vermindert de noodzaak voor verbale correctie en verlaagt ouderstress (Holden & West, 1989).',
    durationMin: 30,
  },
  {
    id: 'gren_02_53',
    skill: 'Grenzen',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Consistente slaapgrens',
    description: 'Oefen het consequent handhaven van het slapritueel, ook als je baby protesteert.',
    instructions: [
      'Bepaal een vast slapritueel: bad, boekje, knuffel, liedje, bedje.',
      'Voer het ritueel elke avond in dezelfde volgorde uit.',
      'Als je baby protesteert, blijf kalm en herhaal: "Het is slaaptijd. Papa is hier."',
      'Wees consequent gedurende minstens vijf dagen en merk op wat er verandert.',
    ],
    reflection: 'Een vast ritueel is een liefdevolle grens. Het zegt: ik bepaal wanneer het slaaptijd is, omdat ik weet dat je slaap nodig hebt.',
    scienceNote: 'Consistente slaprituelen zijn geassocieerd met betere slaapkwaliteit en minder gedragsproblemen bij jonge kinderen (Mindell et al., 2015).',
    durationMin: 20,
  },
  {
    id: 'gren_02_54',
    skill: 'Grenzen',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Grenzen bij bijten en slaan',
    description: 'Reageer effectief en liefdevol als je peuter begint te bijten of te slaan.',
    instructions: [
      'Als je peuter bijt of slaat, pak zachtjes zijn/haar hand vast en zeg: "Au, dat doet pijn. We slaan niet."',
      'Zet je peuter even op de grond of een stap achteruit – korte, rustige afstand.',
      'Bied een alternatief: "Je mag op het kussen slaan" of "Je mag papa een knuffel geven."',
      'Herhaal dit elke keer op exact dezelfde manier – consistentie is de sleutel.',
    ],
    reflection: 'Bijten en slaan is normaal peutergedrag – het is geen agressie maar communicatie. Jouw taak is het vertalen naar betere communicatie.',
    scienceNote: 'Consequente, niet-straffende grensstelling bij agressief gedrag van peuters leidt tot snellere afname dan strenge straf (Kochanska & Aksan, 2006).',
    durationMin: 5,
  },
  {
    id: 'gren_02_55',
    skill: 'Grenzen',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Afleiden en heroriënteren',
    description: 'Oefen het afleiden van je baby naar een veilig alternatief in plaats van alleen "nee" te zeggen.',
    instructions: [
      'Observeer wanneer je baby iets doet dat niet mag.',
      'In plaats van alleen "nee" te zeggen, bied enthousiast een alternatief: "Kijk, hier is iets leuks!"',
      'Verplaats de aandacht van je baby naar het nieuwe object of de nieuwe activiteit.',
      'Doe dit bewust tien keer in de komende dagen en merk op hoe effectief het is vergeleken met alleen "nee" zeggen.',
    ],
    reflection: 'Afleiden is geen zwakte in opvoeding – het is slimme grensstelling die past bij het ontwikkelingsniveau van een baby.',
    scienceNote: 'Heroriëntatie-strategieën zijn effectiever dan verbale correctie bij kinderen onder de twee jaar vanwege de beperkte ontwikkeling van inhibitieve controle (Kopp, 1982).',
    durationMin: 10,
  },
  {
    id: 'gren_02_56',
    skill: 'Grenzen',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Grenzen afstemmen met partner',
    description: 'Bespreek met je partner jullie gezamenlijke grenzen en zorg voor consistentie.',
    instructions: [
      'Plan een moment waarop je baby slaapt om met je partner te praten over grenzen.',
      'Bespreek: welke regels hanteren we? Waar zijn we het eens, waar verschillen we?',
      'Maak afspraken over minstens drie situaties: slaaptijd, eten, veiligheid.',
      'Spreek af hoe jullie reageren als de ander een grens anders handhaaft: niet ondermijnen, later bespreken.',
    ],
    reflection: 'Consistentie tussen ouders is de sterkste grens die er bestaat. Een kind dat tegengestelde signalen krijgt raakt in de war.',
    scienceNote: 'Consistentie tussen opvoeders (interparental consistency) is een sterke voorspeller van gedragsregulatie en emotionele veiligheid bij kinderen (Lindsey & Mize, 2001).',
    durationMin: 30,
  },
  {
    id: 'gren_02_57',
    skill: 'Grenzen',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Nee zeggen zonder schuldgevoel',
    description: 'Onderzoek je eigen schuldgevoelens bij het stellen van grenzen en leer deze los te laten.',
    instructions: [
      'Denk aan een moment waarop je je schuldig voelde over een grens die je stelde bij je baby.',
      'Schrijf op: wat was de situatie, wat voelde je, welke gedachte zat erachter?',
      'Onderzoek: is deze gedachte waar? Of projecteer je iets uit je eigen opvoeding?',
      'Herformuleer: "Een grens stellen is geen liefde onthouden – het is liefde in actie."',
    ],
    reflection: 'Veel vaders vermijden grenzen uit angst de band te beschadigen. Maar grenzen zijn juist wat een kind veiligheid geeft.',
    scienceNote: 'Permissief ouderschap uit schuldgevoel is geassocieerd met meer gedragsproblemen, terwijl autoritatief ouderschap (warm én grenzenstellend) de beste uitkomsten geeft (Baumrind, 1991).',
    durationMin: 15,
  },

  // ─────────────────────────────────────────────────────────
  //  GRENZEN – 3-5 (6 taken)
  // ─────────────────────────────────────────────────────────
  {
    id: 'gren_35_51',
    skill: 'Grenzen',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Twee keuzes geven',
    description: 'Geef je kind twee acceptabele opties in plaats van een open vraag of een bevel.',
    instructions: [
      'Kies een moment waarop je kind iets moet doen (aankleden, eten, opruimen).',
      'In plaats van "Doe je jas aan" of "Wat wil je aan?", zeg: "Wil je de rode jas of de blauwe jas?"',
      'Accepteer de keuze van je kind en benoem het: "Jij kiest de rode jas. Goed gekozen!"',
      'Pas dit de hele dag toe en merk op hoeveel minder weerstand je krijgt.',
    ],
    reflection: 'Twee keuzes geven is grenzen stellen én autonomie bieden tegelijk. Je kind voelt controle binnen jouw kader.',
    scienceNote: 'Het bieden van beperkte keuzes binnen duidelijke grenzen ondersteunt de autonomiebehoefte van kinderen en vermindert oppositiegedrag (Deci & Ryan, 2000).',
    durationMin: 10,
  },
  {
    id: 'gren_35_52',
    skill: 'Grenzen',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'De huisregels tekenen',
    description: 'Maak samen met je kind een poster met drie tot vijf huisregels in tekeningen.',
    instructions: [
      'Kies samen drie tot vijf belangrijke regels: "We slaan niet", "We ruimen op", "We luisteren naar elkaar."',
      'Teken of laat je kind de regels tekenen op een groot vel papier.',
      'Hang de poster op een zichtbare plek in huis.',
      'Verwijs naar de poster als een regel overtreden wordt: "Kijk, wat staat er op onze poster?"',
    ],
    reflection: 'Regels die je kind zelf heeft helpen tekenen voelen minder als opgelegde beperkingen en meer als afspraken.',
    scienceNote: 'Visuele regelreminders en kind-participatie in het opstellen van regels verhogen de naleving en het gevoel van ownership bij kinderen (Piaget, 1932).',
    durationMin: 20,
  },
  {
    id: 'gren_35_53',
    skill: 'Grenzen',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Empathie voor het nee',
    description: 'Oefen het erkennen van de teleurstelling van je kind als je nee zegt, zonder de grens op te geven.',
    instructions: [
      'Wacht op een moment dat je nee moet zeggen (geen snoep, niet nog een aflevering, geen speelgoed kopen).',
      'Zeg je nee en voeg direct empathie toe: "Ik snap dat je dat heel graag wilt. Dat is balen."',
      'Houd de grens vast, ook als je kind huilt of protesteert: "Ik begrijp dat je boos bent. Het antwoord blijft nee."',
      'Bied troost aan: "Wil je even bij mij zitten?" zonder de grens te veranderen.',
    ],
    reflection: 'Empathie bij een grens is geen inconsequentie – het is de combinatie die je kind leert: ik mag voelen wat ik voel, maar niet alles kan.',
    scienceNote: 'Autoritatief opvoeden (warmte + grenzen) leidt tot de beste sociaal-emotionele uitkomsten bij kinderen in alle leeftijdsgroepen (Baumrind, 1991).',
    durationMin: 10,
  },
  {
    id: 'gren_35_54',
    skill: 'Grenzen',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Consequenties vooraf bespreken',
    description: 'Leer je kind wat de consequenties zijn van een keuze voordat de situatie zich voordoet.',
    instructions: [
      'Kies een terugkerende situatie waarin je kind moeite heeft met regels (bijv. tv-tijd, speelgoed delen).',
      'Bespreek vooraf: "Je mag twee afleveringen kijken. Als de tweede is afgelopen, gaat de tv uit."',
      'Vraag je kind te herhalen: "Wat spreken we af?" zodat het duidelijk is.',
      'Voer de consequentie kalm uit als het zover is, zonder discussie: "We hadden afgesproken: twee afleveringen. De tv gaat nu uit."',
    ],
    reflection: 'Een consequentie is geen straf als het vooraf is besproken. Het is een afspraak nakomen – en dat leert je kind vertrouwen.',
    scienceNote: 'Voorspelbare, vooraf gecommuniceerde consequenties verminderen machtsstrijd en bevorderen internalisatie van regels bij kleuters (Patterson, 1982).',
    durationMin: 10,
  },
  {
    id: 'gren_35_55',
    skill: 'Grenzen',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Grenzen houden bij een driftbui',
    description: 'Oefen het kalm vasthouden van een grens tijdens een volledige driftbui van je kind.',
    instructions: [
      'Als je kind een driftbui krijgt na een grens, ga op ooghoogte zitten.',
      'Zeg rustig: "Ik zie dat je heel boos bent. Ik blijf bij je, maar de regel verandert niet."',
      'Bied fysieke nabijheid aan als je kind dat toelaat, of geef ruimte als dat nodig is.',
      'Wacht tot de storm voorbij is en zeg dan: "Je bent weer rustig. Goed gedaan. Laten we verder gaan."',
    ],
    reflection: 'Een driftbui is geen aanval op jou – het is een kind dat overweldigd is door een emotie die het nog niet kan reguleren. Jouw kalmte is de anker.',
    scienceNote: 'Ouders die kalm blijven tijdens driftbuien en de grens vasthouden, helpen kinderen hun eigen regulatiecapaciteit te ontwikkelen (Kochanska et al., 2001).',
    durationMin: 15,
  },
  {
    id: 'gren_35_56',
    skill: 'Grenzen',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Grensanalyse: noodzakelijk of gewoonte?',
    description: 'Evalueer je eigen grenzen en vraag je af welke echt nodig zijn en welke je uit gewoonte stelt.',
    instructions: [
      'Schrijf tien regels of grenzen op die je regelmatig handhaaft bij je kind.',
      'Verdeel ze in drie categorieën: veiligheid (niet-onderhandelbaar), waarden (belangrijk), gewoonte (misschien onnodig).',
      'Schrap of versoepl minstens twee regels die in de categorie "gewoonte" vallen.',
      'Bespreek met je partner welke grenzen jullie allebei echt belangrijk vinden en maak een gedeelde top vijf.',
    ],
    reflection: 'Minder regels die je consequent handhaaft zijn effectiever dan veel regels die je soms laat sloffen. Kies bewust.',
    scienceNote: 'Selectieve, consequente regelhandhaving is effectiever dan een groot aantal regels met inconsistente handhaving (Sanders, 2012).',
    durationMin: 20,
  },
];
