import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_4: InteractiveTask[] = [
  // ═══════════════════════════════════════════════════════════════
  // EMOTIECOACHING (50 taken: 5 leeftijdsgroepen × 10 taken)
  // ═══════════════════════════════════════════════════════════════

  // ── Emotiecoaching · 0-2 jaar ────────────────────────────────────
  {
    id: "emot_02_01",
    title: "Benoem wat je ziet",
    skill: "Emotiecoaching",
    description: "Als je baby huilt of onrustig is, zeg hardop: 'Je bent verdrietig' of 'Je bent gefrustreerd.' Benoem de emotie kalm en zonder te sussen.",
    duration: "2 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Affect labeling — het benoemen van emoties — activeert de prefrontale cortex en dempt de amygdala-activiteit. Zelfs bij baby's helpt een kalme stem met emotiewoorden om het zenuwstelsel te reguleren.",
    skillTip: "Gebruik eenvoudige woorden: boos, blij, bang, verdrietig. Je baby begrijpt de toon eerder dan het woord.",
    vermijd: "Meteen afleiden of sussen ('Shhh, stil maar') — dat leert je kind dat emoties weggestopt moeten worden.",
    leerdoel: "Je leert om emoties te benoemen in plaats van ze weg te nemen.",
    bron: "Lieberman et al. (2007) - Putting feelings into words: Affect labeling disrupts amygdala activity",
  },
  {
    id: "emot_02_02",
    title: "Spiegel de emotie",
    skill: "Emotiecoaching",
    description: "Als je baby blij lacht, lach terug. Als je baby huilt, maak een bezorgd gezicht. Spiegel 5 minuten lang elke emotie die je ziet.",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Spiegelneuronen zorgen ervoor dat baby's emoties leren herkennen door de gezichtsuitdrukkingen van hun ouders. Dit is de basis van empathie-ontwikkeling.",
    skillTip: "Overdrijf je gezichtsuitdrukking een beetje — baby's lezen grote expressies beter.",
    vermijd: "Een neutraal gezicht houden of niet reageren — dat verstoort de emotionele afstemming.",
    leerdoel: "Je leert emotioneel afstemmen op je baby door spiegeling.",
    bron: "Meltzoff & Moore (1977) - Imitation of facial and manual gestures by human neonates",
  },
  {
    id: "emot_02_03",
    title: "Rustig vasthouden bij huilen",
    skill: "Emotiecoaching",
    description: "Als je baby huilt, houd het stevig vast tegen je borst. Zeg niets, adem rustig en laat je hartslag het werk doen.",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Co-regulatie werkt via het autonome zenuwstelsel. Je rustige hartslag en ademhaling helpen je baby om zelf te reguleren. Dit heet 'fysiologische synchronie'.",
    skillTip: "Adem bewust langzaam: 4 tellen in, 6 tellen uit. Je baby voelt het verschil.",
    vermijd: "Wiebelen, heen en weer lopen of snel praten — dat verhoogt de spanning bij je baby.",
    leerdoel: "Je leert je eigen lichaam gebruiken als reguleermiddel voor je baby.",
    bron: "Feldman (2007) - Parent-infant synchrony: Biological foundations and developmental outcomes",
  },
  {
    id: "emot_02_04",
    title: "Emotie-dagboek baby",
    skill: "Emotiecoaching",
    description: "Schrijf vanavond 3 emoties op die je vandaag bij je baby zag. Wat was de trigger? Hoe reageerde je?",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Reflectief functioneren — het vermogen om na te denken over de innerlijke wereld van je kind — is een van de sterkste voorspellers van veilige hechting.",
    skillTip: "Wees specifiek: niet 'baby was lastig' maar 'baby huilde toen ik de kamer uitliep — misschien scheidingsangst'.",
    vermijd: "Jezelf veroordelen over hoe je reageerde. Dit is een oefening in waarnemen, niet in perfect zijn.",
    leerdoel: "Je leert patronen herkennen in de emoties van je baby.",
    bron: "Slade (2005) - Parental reflective functioning",
  },
  {
    id: "emot_02_05",
    title: "Stem als anker",
    skill: "Emotiecoaching",
    description: "Als je baby onrustig is, gebruik een lage, rustige stem. Herhaal steeds dezelfde zin: 'Papa is hier, het is goed.' Houd vol tot je baby kalmeert.",
    duration: "3 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Prosodie — de melodie van je stem — activeert het ventrale vagale systeem bij je baby. Een lage, ritmische stem signaleert veiligheid.",
    skillTip: "Herhaling is krachtig. Dezelfde zin steeds opnieuw geeft voorspelbaarheid en rust.",
    vermijd: "Je stem verhogen of sneller gaan praten als het huilen aanhoudt — dat escaleert.",
    leerdoel: "Je leert je stemtoon bewust inzetten om je baby te kalmeren.",
    bron: "Porges (2011) - The Polyvagal Theory",
  },
  {
    id: "emot_02_06",
    title: "Eigen emotie benoemen",
    skill: "Emotiecoaching",
    description: "Zeg vandaag minstens één keer hardop tegen je baby wat jij voelt: 'Papa is moe' of 'Papa is blij om je te zien.'",
    duration: "2 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Modeling — het voordoen van emotioneel bewustzijn — leert je kind al vroeg dat emoties benoembaar en normaal zijn. Dit legt de basis voor emotionele intelligentie.",
    skillTip: "Koppel het aan een moment: 'Papa is moe na het werk, maar blij om jou te zien.'",
    vermijd: "Alleen negatieve emoties benoemen. Laat ook positieve emoties horen.",
    leerdoel: "Je leert je eigen emoties hardop te benoemen als voorbeeld voor je kind.",
    bron: "Gottman et al. (1996) - Meta-Emotion Philosophy",
  },
  {
    id: "emot_02_07",
    title: "Troostprotocol",
    skill: "Emotiecoaching",
    description: "Bij het volgende huilmoment: stop wat je doet, pak je baby op, leg het tegen je schouder, en zeg: 'Ik ben hier.' Wacht tot het huilen afneemt.",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Responsiviteit — snel en warm reageren op distress — is de kernvoorwaarde voor veilige hechting. Het leert je baby: mijn signalen worden gehoord.",
    skillTip: "Het gaat niet om het stoppen van het huilen. Het gaat om het bieden van nabijheid.",
    vermijd: "Laten huilen om 'het af te leren' — bij baby's onder de 12 maanden is dit schadelijk voor de hechtingsrelatie.",
    leerdoel: "Je leert om het huilen van je baby te beantwoorden in plaats van op te lossen.",
    bron: "Ainsworth et al. (1978) - Patterns of Attachment",
  },
  {
    id: "emot_02_08",
    title: "Gezichtsuitdrukkingen benoemen",
    skill: "Emotiecoaching",
    description: "Wijs vandaag tijdens het spelen naar gezichten in een boekje of knuffel en benoem de emotie: 'Kijk, die beer is blij!' of 'Die is een beetje bang.'",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Baby's leren emoties herkennen door externe referenties. Door emoties te koppelen aan gezichten bouw je hun emotionele vocabulaire op.",
    skillTip: "Gebruik een boekje met duidelijke gezichtsuitdrukkingen. Wijs en benoem — dat is genoeg.",
    vermijd: "Te veel emoties tegelijk benoemen. Houd het bij 2-3 basisemoties per keer.",
    leerdoel: "Je leert emoties visueel en verbaal aan te bieden aan je baby.",
    bron: "Widen & Russell (2003) - A closer look at preschoolers' freely produced labels for facial expressions",
  },
  {
    id: "emot_02_09",
    title: "Frustratie tolereren",
    skill: "Emotiecoaching",
    description: "Als je baby probeert iets te pakken en het niet lukt: wacht 10 seconden voordat je helpt. Zeg: 'Je probeert het heel hard. Dat is lastig hè?'",
    duration: "3 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Getolereerde frustratie (binnen veilige grenzen) bouwt frustratietolerantie op. Door te benoemen in plaats van meteen te helpen, valideer je de inspanning.",
    skillTip: "Tien seconden voelt lang. Tel in je hoofd mee als het helpt.",
    vermijd: "Te lang wachten totdat de frustratie overgaat in paniek — lees de signalen van je baby.",
    leerdoel: "Je leert het verschil tussen frustratie begeleiden en frustratie wegnemen.",
    bron: "Tronick (2007) - The Neurobehavioral and Social-Emotional Development of Infants and Children",
  },
  {
    id: "emot_02_10",
    title: "Emotie na het slapen",
    skill: "Emotiecoaching",
    description: "Als je baby wakker wordt (uit dutje of 's ochtends), benoem meteen de emotie: 'Goedemorgen! Je bent blij hè?' of 'Was het eng om wakker te worden?'",
    duration: "2 min",
    ageGroups: ["0-2"],
    difficulty: "expert",
    points: 20,
    psychologie: "Het moment van wakker worden is een transitiemoment waarop het hechtingssysteem geactiveerd wordt. Een warme, emotioneel afgestemde begroeting versterkt veilige hechting.",
    skillTip: "Kom met een glimlach. Je gezicht is het eerste wat je baby ziet — maak het een fijn moment.",
    vermijd: "Gehaast reageren of meteen overgaan tot de orde van de dag.",
    leerdoel: "Je leert transitiemomenten te gebruiken voor emotionele verbinding.",
    bron: "Bowlby (1969) - Attachment and Loss",
  },

  // ── Emotiecoaching · 3-5 jaar ────────────────────────────────────
  {
    id: "emot_35_01",
    title: "Emotie-detective",
    skill: "Emotiecoaching",
    description: "Vraag je kind: 'Welk gevoel zit er in je buik vandaag?' Laat het kiezen uit: blij, boos, bang, verdrietig, of iets anders.",
    duration: "3 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen van 3-5 lokaliseren emoties vaak in hun lichaam. Door te vragen 'waar voel je het?' help je ze de verbinding te maken tussen lichaam en emotie.",
    skillTip: "Gebruik een emotiekaart of teken gezichtjes. Visuele hulpmiddelen werken beter dan alleen woorden op deze leeftijd.",
    vermijd: "Het antwoord corrigeren. Als je kind zegt 'ik voel groen' — ga daarin mee.",
    leerdoel: "Je leert je kind te helpen emoties te lokaliseren en te benoemen.",
    bron: "Gottman (1997) - Raising an Emotionally Intelligent Child",
  },
  {
    id: "emot_35_02",
    title: "Driftbui als leraar",
    skill: "Emotiecoaching",
    description: "Bij de volgende driftbui: ga op ooghoogte zitten, zeg 'Ik zie dat je heel boos bent' en wacht. Probeer niets op te lossen. Wees er alleen maar.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Tijdens een driftbui is de amygdala overactief en de prefrontale cortex offline. Redeneren werkt niet. Nabijheid en validatie wel — dat helpt het kind terug naar een gereguleerde staat.",
    skillTip: "Houd je handen open en zichtbaar. Dat signaleert veiligheid op een non-verbaal niveau.",
    vermijd: "Uitleggen waarom het gedrag niet kan — dat werkt pas als het kind weer rustig is.",
    leerdoel: "Je leert een driftbui te begeleiden in plaats van te bestrijden.",
    bron: "Siegel & Bryson (2011) - The Whole-Brain Child",
  },
  {
    id: "emot_35_03",
    title: "Het verhaaltje van de emotie",
    skill: "Emotiecoaching",
    description: "Verzin samen met je kind een kort verhaaltje over een beertje dat boos/bang/verdrietig is. Vraag: 'Wat zou het beertje kunnen doen?'",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Narratieve verwerking helpt kinderen om afstand te nemen van hun eigen emotie en er toch mee te oefenen. Het activeert zowel de taalcentra als de emotieregulatie.",
    skillTip: "Laat je kind het verhaal sturen. Jij stelt alleen vragen: 'En toen? Wat voelde het beertje?'",
    vermijd: "Het verhaal een 'les' maken. Het gaat om verkennen, niet om de juiste conclusie.",
    leerdoel: "Je leert emoties bespreekbaar te maken via verhalen.",
    bron: "Bruner (1990) - Acts of Meaning — narrative as sense-making",
  },
  {
    id: "emot_35_04",
    title: "Kleur je gevoel",
    skill: "Emotiecoaching",
    description: "Geef je kind papier en krijtjes. Vraag: 'Welke kleur heeft je gevoel vandaag? Teken het maar.' Bespreek het samen.",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Creatieve expressie biedt een uitlaatklep voor emoties die kinderen nog niet in woorden kunnen vatten. Het externaliseert de emotie, wat regulatie makkelijker maakt.",
    skillTip: "Teken mee! Als je zelf ook een 'gevoelskleur' tekent, normaliseert dat het proces.",
    vermijd: "Vragen 'waarom die kleur?' — het gaat om expressie, niet om uitleg.",
    leerdoel: "Je leert non-verbale manieren om emoties te bespreken met je kind.",
    bron: "Malchiodi (2011) - Handbook of Art Therapy",
  },
  {
    id: "emot_35_05",
    title: "Emotie-thermometer",
    skill: "Emotiecoaching",
    description: "Teken een thermometer op papier (1-5). Vraag je kind: 'Hoe boos/blij/bang ben je nu? Wijs maar aan.' Gebruik het de hele dag.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Een visuele schaal helpt kinderen om de intensiteit van emoties te leren inschatten. Dit is een voorstadium van zelfregulatie: eerst waarnemen, dan reguleren.",
    skillTip: "Hang de thermometer op de koelkast. Gebruik het zelf ook: 'Papa zit op een 3 vandaag.'",
    vermijd: "Alleen gebruiken bij negatieve emoties. Meet ook blijdschap en opwinding.",
    leerdoel: "Je leert je kind om emoties in gradaties te ervaren in plaats van zwart-wit.",
    bron: "Attwood (2006) - The Complete Guide to Asperger's Syndrome (emotie-thermometer oorsprong)",
  },
  {
    id: "emot_35_06",
    title: "Valideer voor je corrigeert",
    skill: "Emotiecoaching",
    description: "Als je kind ongewenst gedrag vertoont uit emotie (slaan, gooien): benoem EERST de emotie ('Je bent boos') voordat je het gedrag corrigeert.",
    duration: "2 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Emotiecoaching volgt de volgorde: valideer → begrijp → begrens. Als je begint met begrenzen voelt het kind zich niet gehoord en escaleert het gedrag.",
    skillTip: "De zin is: 'Je bent boos, dat snap ik. EN slaan mag niet.' Beide zijn waar.",
    vermijd: "Alleen begrenzen zonder te valideren: 'Stop daarmee!' zonder erkenning van het gevoel.",
    leerdoel: "Je leert de volgorde valideren-dan-begrenzen toe te passen.",
    bron: "Gottman (1997) - The 5 steps of Emotion Coaching",
  },
  {
    id: "emot_35_07",
    title: "Knuffelplek aanwijzen",
    skill: "Emotiecoaching",
    description: "Maak samen met je kind een 'rustplek' in huis: een hoekje met een kussen en een knuffel. Leg uit: 'Als je een groot gevoel hebt, mag je hier even zitten.'",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Een fysieke plek koppelen aan emotieregulatie helpt kinderen om zelf de stap te maken naar kalmeren. Het is geen strafhoek — het is een veilige haven.",
    skillTip: "Laat je kind de plek zelf inrichten. Noem het een 'knuffelplek' of 'rustpaleis', niet een 'time-out hoek'.",
    vermijd: "Het gebruiken als straf. Dan verliest de plek zijn functie als veilige haven.",
    leerdoel: "Je leert je kind een fysieke strategie aan voor emotieregulatie.",
    bron: "Shanker (2016) - Self-Reg: How to Help Your Child",
  },
  {
    id: "emot_35_08",
    title: "Emoties in het boekje",
    skill: "Emotiecoaching",
    description: "Lees vanavond een prentenboek en pauzeer bij elke emotie van een personage. Vraag: 'Hoe voelt de beer zich hier? Herken jij dat?'",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Bibliotherapie — het gebruik van verhalen om emoties te verkennen — helpt kinderen om emotioneel vocabulaire op te bouwen in een veilige context.",
    skillTip: "Kies boeken met duidelijke emoties: 'De kleur van emoties', 'Waar de wilde dingen zijn', 'Kikker is bang'.",
    vermijd: "Het antwoord voorzeggen. Laat je kind zelf benoemen wat het ziet.",
    leerdoel: "Je leert emoties te herkennen en bespreken via verhalen.",
    bron: "Heath et al. (2005) - Bibliotherapy: A resource to facilitate emotional healing",
  },
  {
    id: "emot_35_09",
    title: "Papa voelt ook",
    skill: "Emotiecoaching",
    description: "Vertel je kind vandaag over een moment dat jij je boos, bang of verdrietig voelde als kind. Houd het simpel en kort.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "expert",
    points: 20,
    psychologie: "Zelfopenbaring door ouders normaliseert emoties en leert kinderen dat alle mensen emoties hebben. Het vermindert schaamte rond 'negatieve' gevoelens.",
    skillTip: "Eindig met hoe je ermee omging: 'Ik was bang, en toen ging ik naar oma. Dat hielp.'",
    vermijd: "Te heftige of traumatische verhalen delen. Houd het leeftijdsgeschikt en licht.",
    leerdoel: "Je leert kwetsbaarheid te modelen als kracht.",
    bron: "Brené Brown (2012) - Daring Greatly — vulnerability as courage",
  },
  {
    id: "emot_35_10",
    title: "Emotie-weerbericht",
    skill: "Emotiecoaching",
    description: "Vraag aan tafel: 'Wat is jouw emotie-weerbericht vandaag? Zonnig? Bewolkt? Onweer?' Deel ook je eigen weerbericht.",
    duration: "3 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Metaforen helpen jonge kinderen om abstracte concepten (emoties) te begrijpen. Het weerbericht-format maakt het speels en laagdrempelig.",
    skillTip: "Maak er een dagelijks ritueel van — bijvoorbeeld bij het avondeten. Consistentie maakt het normaal.",
    vermijd: "Doorvragen als je kind 'zonnig' zegt terwijl het duidelijk niet zo is. Accepteer het antwoord.",
    leerdoel: "Je leert een dagelijks emotie-check-in ritueel te creëren.",
    bron: "Snel (2004) - De Vreedzame School — emotie-weerbericht methode",
  },

  // ── Emotiecoaching · 6-9 jaar ────────────────────────────────────
  {
    id: "emot_69_01",
    title: "Emotie-interview",
    skill: "Emotiecoaching",
    description: "Doe alsof je een interviewer bent. Vraag je kind: 'Meneer/mevrouw, wat was het sterkste gevoel dat u vandaag had?' Maak het grappig en luchtig.",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Humor verlaagt de drempel om over emoties te praten. Door het speels te maken voelt het minder bedreigend dan een 'serieus gesprek'.",
    skillTip: "Gebruik een pen als microfoon. Overdrijf je interviewersstem. Kinderen van deze leeftijd houden van rollenspel.",
    vermijd: "Het gesprek serieus of zwaar maken als je kind het luchtig houdt — ga mee in de toon.",
    leerdoel: "Je leert een speelse manier om emoties bespreekbaar te maken.",
    bron: "McGhee (2002) - Understanding and Promoting the Development of Children's Humor",
  },
  {
    id: "emot_69_02",
    title: "Luisteren zonder oplossing",
    skill: "Emotiecoaching",
    description: "Als je kind thuiskomt met een probleem (ruzie op school, oneerlijkheid): luister 3 minuten zonder advies te geven. Zeg alleen: 'Dat klinkt moeilijk' of 'Vertel meer.'",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen van 6-9 beginnen complexere sociale emoties te ervaren. Ze hebben eerst validatie nodig voordat ze openstaan voor oplossingen.",
    skillTip: "Zet een timer van 3 minuten in je hoofd. Pas daarna mag je vragen: 'Wil je dat ik meedenk?'",
    vermijd: "Meteen zeggen 'Dat is niet zo erg' of 'Dat had je anders moeten doen.'",
    leerdoel: "Je leert luisteren zonder te fixen.",
    bron: "Faber & Mazlish (2012) - How to Talk So Kids Will Listen",
  },
  {
    id: "emot_69_03",
    title: "Emotie-kaart maken",
    skill: "Emotiecoaching",
    description: "Maak samen een 'emotiekaart' met minstens 10 emoties (niet alleen blij/boos/bang). Denk aan: trots, jaloers, opgelucht, teleurgesteld, zenuwachtig.",
    duration: "15 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Emotionele granulariteit — het vermogen om emoties specifiek te benoemen — is gekoppeld aan betere emotieregulatie. Hoe meer woorden, hoe beter de regulatie.",
    skillTip: "Laat je kind emoties tekenen of emoji's erbij zetten. Hang de kaart op in de kamer.",
    vermijd: "Te veel sturen. Laat je kind zelf emoties bedenken, ook als ze ongewoon zijn.",
    leerdoel: "Je leert het emotionele vocabulaire van je kind uit te breiden.",
    bron: "Barrett (2017) - How Emotions Are Made — emotional granularity",
  },
  {
    id: "emot_69_04",
    title: "Wat zou jij doen?",
    skill: "Emotiecoaching",
    description: "Vertel een kort scenario: 'Stel je voor, je beste vriend speelt ineens met iemand anders. Hoe zou je je voelen? Wat zou je doen?'",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Hypothetische scenario's activeren perspective-taking en emotionele simulatie. Kinderen oefenen hiermee empathie en probleemoplossend denken.",
    skillTip: "Gebruik scenario's die dicht bij hun leven liggen: school, sport, vriendjes. Dat maakt het relevant.",
    vermijd: "Het 'juiste' antwoord opdringen. Er zijn meerdere goede manieren om met emoties om te gaan.",
    leerdoel: "Je leert je kind om te oefenen met emotionele situaties in een veilige context.",
    bron: "Denham (1998) - Emotional Development in Young Children",
  },
  {
    id: "emot_69_05",
    title: "Emotie-dagboekje starten",
    skill: "Emotiecoaching",
    description: "Geef je kind een klein schriftje. Vraag: 'Wil je elke avond 1 zin schrijven over hoe je je voelde vandaag?' Doe het samen de eerste week.",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Expressief schrijven over emoties vermindert stress en verbetert emotionele verwerking. Bij kinderen werkt het al met één zin per dag.",
    skillTip: "Schrijf zelf ook elke avond één zin in je eigen dagboek. Deel het als je kind dat wil.",
    vermijd: "Het dagboek lezen zonder toestemming. Het moet een veilige plek zijn.",
    leerdoel: "Je leert je kind om emoties te verwerken door ze op te schrijven.",
    bron: "Pennebaker (1997) - Writing about emotional experiences as a therapeutic process",
  },
  {
    id: "emot_69_06",
    title: "Emotie achter het gedrag",
    skill: "Emotiecoaching",
    description: "Als je kind vervelend doet, vraag jezelf hardop af: 'Ik vraag me af welk gevoel hierachter zit. Ben je misschien moe? Of gebeurde er iets op school?'",
    duration: "3 min",
    ageGroups: ["6-9"],
    difficulty: "expert",
    points: 20,
    psychologie: "Alle gedrag is communicatie. Door hardop te speculeren over de emotie achter het gedrag, model je mentaliseren — het nadenken over innerlijke staten.",
    skillTip: "Formuleer het als vraag, niet als feit: 'Zou het kunnen dat...' in plaats van 'Je bent gewoon moe.'",
    vermijd: "Het gedrag negeren. Benoem de emotie EN geef de grens: 'Je bent boos, en schreeuwen doen we niet.'",
    leerdoel: "Je leert onder het gedrag te kijken naar de emotie.",
    bron: "Fonagy et al. (2002) - Affect Regulation, Mentalization, and the Development of the Self",
  },
  {
    id: "emot_69_07",
    title: "Emotie-top-3",
    skill: "Emotiecoaching",
    description: "Vraag aan tafel: 'Wat waren je top-3 emoties vandaag?' Nummer 1 is de sterkste. Iedereen doet mee, ook papa.",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Het rangschikken van emoties stimuleert metacognitie — nadenken over je eigen denken en voelen. Dit is een cruciale vaardigheid voor zelfregulatie.",
    skillTip: "Begin zelf: 'Mijn nummer 1 was trots, want ik heb iets moeilijks afgemaakt op werk.'",
    vermijd: "Alleen over 'leuke' emoties praten. Geef ruimte aan lastige gevoelens.",
    leerdoel: "Je leert emoties te rangschikken en prioriteren als gezin.",
    bron: "Flavell (1979) - Metacognition and cognitive monitoring",
  },
  {
    id: "emot_69_08",
    title: "Lichaamsscan voor kinderen",
    skill: "Emotiecoaching",
    description: "Doe samen een mini-lichaamsscan: 'Sluit je ogen. Voel je iets in je hoofd? In je buik? In je benen? Waar zit het gevoel van vandaag?'",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Interoceptie — het vermogen om lichaamssignalen waar te nemen — is de basis van emotioneel bewustzijn. Kinderen die hun lichaam beter voelen, reguleren beter.",
    skillTip: "Doe het voor het slapengaan als rustmoment. Praat langzaam en rustig.",
    vermijd: "Het te lang maken. 2-3 minuten is genoeg voor deze leeftijd.",
    leerdoel: "Je leert je kind de verbinding tussen lichaam en emotie te voelen.",
    bron: "Craig (2009) - How do you feel? Interoception: the sense of the physiological condition of the body",
  },
  {
    id: "emot_69_09",
    title: "Emotie-film kijken",
    skill: "Emotiecoaching",
    description: "Kijk samen een film (bijv. Inside Out/Binnenstebuiten) en pauzeer bij emotionele scènes. Vraag: 'Wat voelt dit personage? Heb jij dat ook weleens?'",
    duration: "15 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Films bieden een veilige afstand om over emoties te praten. Door te pauzeren en te bespreken, maak je van passief kijken een actieve emotie-oefening.",
    skillTip: "Inside Out (Pixar) is perfect voor deze leeftijd — het maakt emoties letterlijk zichtbaar.",
    vermijd: "Te veel pauzeren. Kies 2-3 momenten, niet elke scène.",
    leerdoel: "Je leert media te gebruiken als springplank voor emotiegesprekken.",
    bron: "Mar & Oatley (2008) - The function of fiction is the abstraction and simulation of social experience",
  },
  {
    id: "emot_69_10",
    title: "Sorry + gevoel",
    skill: "Emotiecoaching",
    description: "Als je kind sorry moet zeggen, help het dan om het gevoel erbij te benoemen: 'Sorry dat ik je sloeg. Ik was boos omdat je mijn spel afpakte.'",
    duration: "3 min",
    ageGroups: ["6-9"],
    difficulty: "expert",
    points: 20,
    psychologie: "Een sorry met emotie-uitleg is effectiever dan een leeg 'sorry'. Het leert kinderen om verantwoordelijkheid te nemen voor zowel hun gedrag als hun emotie.",
    skillTip: "Oefen de formule: 'Sorry dat ik [gedrag]. Ik voelde me [emotie] omdat [reden].'",
    vermijd: "Forceren om sorry te zeggen als het kind nog midden in de emotie zit. Wacht tot het rustig is.",
    leerdoel: "Je leert je kind om excuses te verbinden aan emotioneel bewustzijn.",
    bron: "Lazare (2004) - On Apology — the psychology of meaningful apologies",
  },

  // ── Emotiecoaching · 10-12 jaar ──────────────────────────────────
  {
    id: "emot_1012_01",
    title: "Check-in zonder oordeel",
    skill: "Emotiecoaching",
    description: "Vraag je kind: 'Hoe gaat het écht met je?' en luister zonder reactie. Geen advies, geen oordeel, geen 'maar'. Alleen luisteren.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Pre-adolescenten beginnen een 'sociaal masker' te ontwikkelen. Een oordeelvrije check-in creëert een veilige ruimte om daarachter te kijken.",
    skillTip: "Doe het terloops — in de auto, tijdens een wandeling. Niet tegenover elkaar aan tafel (dat voelt als verhoor).",
    vermijd: "Doorvragen als je kind 'goed' zegt. Zeg: 'Oké, ik ben er als je wilt praten.' Laat het los.",
    leerdoel: "Je leert een oordeelvrije ruimte te creëren voor je kind.",
    bron: "Steinberg (2001) - We Know Some Things: Parent-Adolescent Relationships",
  },
  {
    id: "emot_1012_02",
    title: "Emotie-vocabulaire uitbreiden",
    skill: "Emotiecoaching",
    description: "Introduceer een 'nieuw' emotiewoord: ambivalent, nostalgisch, overweldigd, machteloos. Vraag: 'Herken je dat gevoel? Wanneer had je dat?'",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Emotionele granulariteit neemt toe met vocabulaire. Kinderen van 10-12 kunnen complexe en gemengde emoties ervaren maar missen vaak de woorden.",
    skillTip: "Koppel het aan een eigen ervaring: 'Ik voelde me ambivalent toen ik een nieuwe baan kreeg — blij én bang.'",
    vermijd: "Het als les presenteren. Het moet aanvoelen als een gesprek, niet als school.",
    leerdoel: "Je leert je kind om genuanceerder over emoties te denken en spreken.",
    bron: "Barrett (2017) - How Emotions Are Made",
  },
  {
    id: "emot_1012_03",
    title: "Emotie achter social media",
    skill: "Emotiecoaching",
    description: "Vraag je kind: 'Hoe voel je je na een half uur op je telefoon? Beter of slechter?' Luister zonder oordeel. Deel je eigen ervaring.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Social media triggert sociale vergelijking, FOMO en validatiebehoefte. Door de emotionele impact bespreekbaar te maken help je je kind om bewuster te scrollen.",
    skillTip: "Deel je eigen eerlijke ervaring: 'Ik merk dat ik me soms rot voel na Instagram. Jij ook?'",
    vermijd: "Meteen regels stellen of telefoon afpakken. Dit gesprek gaat over bewustwording, niet over controle.",
    leerdoel: "Je leert de emotionele impact van digitale media bespreekbaar te maken.",
    bron: "Twenge (2017) - iGen: Why Today's Super-Connected Kids Are Growing Up Less Rebellious",
  },
  {
    id: "emot_1012_04",
    title: "Gemengde emoties bespreken",
    skill: "Emotiecoaching",
    description: "Vertel je kind: 'Wist je dat je twee emoties tegelijk kunt voelen? Je kunt blij zijn dat je naar een feestje gaat én zenuwachtig.' Vraag: 'Wanneer had jij dat?'",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Rond 10-11 jaar ontwikkelen kinderen het vermogen om gemengde emoties te ervaren en begrijpen. Dit is een mijlpaal in de emotionele ontwikkeling.",
    skillTip: "Gebruik het woord 'én' in plaats van 'maar': 'Je bent boos én verdrietig' — beide zijn waar.",
    vermijd: "Simplificeren: 'Je bent gewoon boos.' Kinderen van deze leeftijd voelen complexer dan dat.",
    leerdoel: "Je leert je kind dat meerdere emoties tegelijk normaal zijn.",
    bron: "Harter & Buddin (1987) - Children's understanding of the simultaneity of two emotions",
  },
  {
    id: "emot_1012_05",
    title: "Emotie en lichaam verbinden",
    skill: "Emotiecoaching",
    description: "Vraag: 'Waar in je lichaam voel je stress? Schouders? Buik? Kaak?' Help je kind om de fysieke signalen te herkennen.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Somatische markers — lichaamssignalen die gekoppeld zijn aan emoties — zijn een vroeg waarschuwingssysteem. Wie ze herkent, kan eerder ingrijpen.",
    skillTip: "Deel je eigen somatische markers: 'Als ik gestrest ben, span ik mijn kaak aan. Bij jou?'",
    vermijd: "Het afdoen als 'inbeelding'. Lichaamssignalen zijn echt en waardevol.",
    leerdoel: "Je leert je kind om lichaamssignalen te gebruiken als emotioneel kompas.",
    bron: "Damasio (1994) - Descartes' Error — somatic marker hypothesis",
  },
  {
    id: "emot_1012_06",
    title: "Emotie-coach voor een vriend",
    skill: "Emotiecoaching",
    description: "Vraag: 'Als je beste vriend heel verdrietig is, wat zou je dan zeggen?' Bespreek samen wat helpt en wat niet helpt.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Perspective-taking en prosociaal gedrag nemen toe als kinderen leren hoe ze anderen emotioneel kunnen steunen. Het versterkt ook hun eigen emotionele intelligentie.",
    skillTip: "Bespreek het verschil tussen 'fixen' en 'er zijn'. Soms wil een vriend geen advies, maar een luisterend oor.",
    vermijd: "Sociaal wenselijke antwoorden aanmoedigen. Eerlijkheid is belangrijker.",
    leerdoel: "Je leert je kind om empathisch te reageren op emoties van anderen.",
    bron: "Eisenberg et al. (2006) - Prosocial Development",
  },
  {
    id: "emot_1012_07",
    title: "Trigger-detective",
    skill: "Emotiecoaching",
    description: "Bespreek samen: 'Wat zijn dingen die jou boos/gefrustreerd/verdrietig maken? Kun je er 3 noemen?' Schrijf ze samen op.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Triggeridentificatie is een kernvaardigheid van emotieregulatie. Wie zijn triggers kent, kan anticiperen in plaats van reageren.",
    skillTip: "Deel je eigen triggers: 'Bij mij is het als ik haast heb en jullie treuzelen. Dan word ik geïrriteerd.'",
    vermijd: "De triggers bagatelliseren: 'Daar hoef je toch niet boos om te worden.' Een trigger is een trigger.",
    leerdoel: "Je leert samen triggers in kaart te brengen als basis voor betere regulatie.",
    bron: "Gross (2015) - Emotion Regulation: Current Status and Future Prospects — trigger identification",
  },
  {
    id: "emot_1012_08",
    title: "Emotie-journal samen",
    skill: "Emotiecoaching",
    description: "Schrijf samen met je kind elk 3 emoties op die jullie deze week voelden. Vergelijk: hebben jullie dezelfde dingen gevoeld?",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Gedeelde reflectie verdiept de ouder-kindrelatie en normaliseert het hele spectrum van emoties. Het laat zien: papa voelt ook.",
    skillTip: "Wees eerlijk en kwetsbaar. Als je je zorgen maakte deze week, zeg dat.",
    vermijd: "Alleen 'stoere' of positieve emoties opschrijven. Model dat alle emoties welkom zijn.",
    leerdoel: "Je leert emotionele kwetsbaarheid te delen als vader.",
    bron: "Gottman (1997) - Meta-Emotion Philosophy — emotional awareness in families",
  },
  {
    id: "emot_1012_09",
    title: "Coping-toolbox",
    skill: "Emotiecoaching",
    description: "Maak samen een lijst: 'Wat kun je doen als je je rot voelt?' Muziek luisteren, tekenen, rennen, praten, schrijven. Hang het op in de kamer.",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Coping-strategieën zijn aan te leren. Kinderen die meerdere strategieën kennen, zijn veerkrachtiger omdat ze kunnen wisselen als één strategie niet werkt.",
    skillTip: "Sorteer de strategieën: wat werkt bij boosheid? Bij verdriet? Bij stress? Verschillende emoties vragen andere aanpak.",
    vermijd: "Alleen 'rustige' strategieën opschrijven. Soms werkt het juist om hard te rennen of te schreeuwen in een kussen.",
    leerdoel: "Je leert je kind een persoonlijke toolkit voor emotieregulatie te bouwen.",
    bron: "Compas et al. (2001) - Coping with stress during childhood and adolescence",
  },
  {
    id: "emot_1012_10",
    title: "Emotie-reflectie voor het slapen",
    skill: "Emotiecoaching",
    description: "Vraag voor het slapengaan: 'Wat was je fijnste moment vandaag? En je moeilijkste moment?' Deel ook jouw antwoord.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Een dagelijkse emotionele reflectie voor het slapen helpt bij het verwerken van de dag. Het vermindert piekeren en verbetert de slaapkwaliteit.",
    skillTip: "Houd het ritueel kort en consistent. Elke avond dezelfde 2 vragen — de kracht zit in de herhaling.",
    vermijd: "Er een lang gesprek van maken. Soms is het antwoord één zin, en dat is prima.",
    leerdoel: "Je leert een dagelijks reflectieritueel te creëren met je kind.",
    bron: "Emmons & McCullough (2003) - Counting blessings versus burdens — gratitude & well-being",
  },

  // ── Emotiecoaching · 13-16 jaar ──────────────────────────────────
  {
    id: "emot_1316_01",
    title: "Erken de storm",
    skill: "Emotiecoaching",
    description: "Als je tiener boos of emotioneel is, zeg: 'Ik zie dat dit je raakt. Je hoeft het niet uit te leggen, maar ik ben er.' Ga niet weg.",
    duration: "2 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Het puberbrein heeft een hyperactieve amygdala en een nog niet volgroeide prefrontale cortex. Emoties zijn intenser dan bij volwassenen. Erkenning kalmeert.",
    skillTip: "Fysieke nabijheid zonder aanraking werkt het best bij tieners. Blijf in de buurt, maar dring niet aan.",
    vermijd: "Zeggen 'Stel je niet aan' of 'Zo erg is het niet.' Dat invalideert de emotie.",
    leerdoel: "Je leert de intense emoties van je tiener te erkennen zonder te minimaliseren.",
    bron: "Casey et al. (2008) - The Adolescent Brain — amygdala-prefrontal development",
  },
  {
    id: "emot_1316_02",
    title: "Luisteren als je het niet snapt",
    skill: "Emotiecoaching",
    description: "Als je tiener vertelt over iets dat je niet begrijpt (online drama, vriendengroep), zeg: 'Ik snap het misschien niet helemaal, maar vertel. Het klinkt belangrijk.'",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Tieners stoppen met delen als ze merken dat ouders hun wereld niet serieus nemen. Eerlijk zeggen 'ik snap het niet, maar wil het begrijpen' is respectvoller dan doen alsof.",
    skillTip: "Stel vragen vanuit nieuwsgierigheid, niet vanuit controle: 'Hoe werkt dat dan?' in plaats van 'Waarom doe je dat?'",
    vermijd: "Hun problemen vergelijken met 'echte' problemen. Voor hen is het echt.",
    leerdoel: "Je leert te luisteren vanuit nieuwsgierigheid in plaats van begrip.",
    bron: "Laursen & Collins (2009) - Parent-Child Relationships During Adolescence",
  },
  {
    id: "emot_1316_03",
    title: "Deel een eigen worsteling",
    skill: "Emotiecoaching",
    description: "Vertel je tiener over een moment dat jij het moeilijk had als tiener. Wat voelde je? Wat deed je? Wat had je achteraf anders gewild?",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Reciprocal self-disclosure verdiept de relatie. Tieners waarderen ouders die eerlijk zijn over hun eigen fouten en kwetsbaarheden.",
    skillTip: "Kies een verhaal dat relevant is voor wat je tiener meemaakt. Maar maak het niet over jou — eindig met: 'Hoe is dat bij jou?'",
    vermijd: "Je eigen verhaal gebruiken als morele les: 'Zie je, daarom moet je...' Dat voelt als manipulatie.",
    leerdoel: "Je leert kwetsbaarheid te gebruiken om verbinding te maken met je tiener.",
    bron: "Jourard (1971) - Self-Disclosure: An Experimental Analysis of the Transparent Self",
  },
  {
    id: "emot_1316_04",
    title: "Emoties valideren bij conflict",
    skill: "Emotiecoaching",
    description: "Na een conflict met je tiener, ga later terug en zeg: 'Ik snap dat je boos was. Je had het recht om dat te voelen. De manier waarop was niet oké, maar het gevoel wel.'",
    duration: "3 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Het onderscheid maken tussen emotie (altijd oké) en gedrag (soms niet oké) is de kern van emotiecoaching. Tieners leren hierdoor dat hun emoties welkom zijn.",
    skillTip: "Timing is alles. Ga pas terug als jullie allebei rustig zijn — niet na 5 minuten, maar misschien na een uur.",
    vermijd: "De validatie gebruiken als opening om alsnog je punt te maken. Het is geen truc.",
    leerdoel: "Je leert emotie en gedrag te scheiden in je communicatie.",
    bron: "Gottman (1997) - Emotion Coaching — separating emotion from behavior",
  },
  {
    id: "emot_1316_05",
    title: "Emotie-check via tekst",
    skill: "Emotiecoaching",
    description: "Stuur je tiener een kort berichtje: 'Hoe gaat het met je vandaag? Echt?' Geen druk om te antwoorden. Geen follow-up als het stil blijft.",
    duration: "2 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Tieners communiceren vaak makkelijker via tekst dan face-to-face. Een laagdrempelig berichtje laat zien dat je denkt aan ze zonder fysieke druk.",
    skillTip: "Stuur het op een onverwacht moment — niet na school (dat voelt als controle) maar random op een zaterdagmiddag.",
    vermijd: "Doorvragen via tekst als je kind niet antwoordt. Het berichtje op zich is al de boodschap.",
    leerdoel: "Je leert digitale communicatie te gebruiken voor emotionele verbinding.",
    bron: "Uhls et al. (2014) - Five days at outdoor education camp without screens improves preteen skills",
  },
  {
    id: "emot_1316_06",
    title: "Normaliseer falen",
    skill: "Emotiecoaching",
    description: "Vertel je tiener over een keer dat jij faalde — een toets, een sollicitatie, een relatie. Wat voelde je? Wat leerde je? Hoe ging je verder?",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Faalangst is een van de grootste emotionele uitdagingen bij tieners. Door falen te normaliseren en te modelen hoe je ermee omgaat, verlaag je de drempel.",
    skillTip: "Wees specifiek en eerlijk. 'Ik zakte voor mijn rijexamen en ik schaamde me dood' werkt beter dan een vaag succesverhaal.",
    vermijd: "Eindigen met 'en kijk waar ik nu ben!' — dat maakt het alsnog een succesverhaal in plaats van een normalisering van falen.",
    leerdoel: "Je leert falen te normaliseren als onderdeel van groei.",
    bron: "Dweck (2006) - Mindset: The New Psychology of Success — growth mindset",
  },
  {
    id: "emot_1316_07",
    title: "Ruimte geven na school",
    skill: "Emotiecoaching",
    description: "Geef je tiener na school 30 minuten zonder vragen. Geen 'Hoe was je dag?' bij binnenkomst. Laat ze landen. Vraag later, als ze er klaar voor zijn.",
    duration: "2 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Na een schooldag vol sociale interactie zijn veel tieners emotioneel uitgeput. Ze hebben decompressietijd nodig voordat ze kunnen praten.",
    skillTip: "Zeg bij binnenkomst alleen: 'Hoi! Er staat eten als je wilt.' Meer niet.",
    vermijd: "Het persoonlijk opvatten als je tiener niet wil praten. Het gaat niet over jou.",
    leerdoel: "Je leert dat ruimte geven ook een vorm van emotiecoaching is.",
    bron: "Larson et al. (2002) - Changes in adolescents' interpersonal experiences",
  },
  {
    id: "emot_1316_08",
    title: "Emoties bij prestaties",
    skill: "Emotiecoaching",
    description: "Vraag na een toets of wedstrijd niet 'Hoe ging het?' maar 'Hoe voelde het?' Focus op de emotie, niet op het resultaat.",
    duration: "3 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Resultaatgerichte vragen versterken prestatiedruk. Emotiegerichte vragen leren je kind dat hun welzijn belangrijker is dan hun prestatie.",
    skillTip: "Als je kind een slecht cijfer haalt: 'Dat is balen. Hoe voel je je erover?' werkt beter dan 'Wat ging er mis?'",
    vermijd: "Meteen oplossingen aandragen: 'Volgende keer moet je eerder beginnen.' Eerst voelen, dan denken.",
    leerdoel: "Je leert emotie boven prestatie te stellen in je gesprekken.",
    bron: "Ryan & Deci (2000) - Self-Determination Theory — intrinsic vs extrinsic motivation",
  },
  {
    id: "emot_1316_09",
    title: "Respecteer de muur",
    skill: "Emotiecoaching",
    description: "Als je tiener zegt 'Laat me met rust': doe dat. Zeg: 'Oké, ik ben beneden als je me nodig hebt.' Loop weg zonder gekwetst te doen.",
    duration: "2 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Autonomiebehoefte is een kernbehoefte bij tieners. Door hun grens te respecteren, bouw je vertrouwen op. Ze komen terug als ze er klaar voor zijn.",
    skillTip: "Het kost moed om weg te lopen als je wilt helpen. Maar respect voor hun grens ís helpen.",
    vermijd: "Zeggen 'Goed, dan niet' op een passief-agressieve toon. Dat straft het stellen van een grens.",
    leerdoel: "Je leert de grenzen van je tiener te respecteren als vorm van emotionele steun.",
    bron: "Deci & Ryan (2000) - Self-Determination Theory — autonomy support",
  },
  {
    id: "emot_1316_10",
    title: "Emotie-gesprek op hun voorwaarden",
    skill: "Emotiecoaching",
    description: "Vraag je tiener: 'Wanneer en hoe wil jij het liefst praten over hoe het gaat? In de auto? Via tekst? 's Avonds laat?' Volg hun voorkeur.",
    duration: "3 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Tieners praten meer als ze controle hebben over het wanneer en hoe. Door hen de regie te geven, verhoog je de kans op openheid.",
    skillTip: "Veel tieners praten het makkelijkst als ze iets anders doen — autorijden, wandelen, gamen. Gebruik dat.",
    vermijd: "Formele 'we moeten praten'-momenten. Die activeren het alarmsysteem van je tiener.",
    leerdoel: "Je leert de communicatievorm aan te passen aan de behoefte van je tiener.",
    bron: "Steinberg & Silk (2002) - Parenting Adolescents — communication strategies",
  },
];
