// Verbinding – 50 interactieve taken (5 leeftijdsgroepen × 10)
import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_8: InteractiveTask[] = [

  // ─── 0-2 jaar ────────────────────────────────────────────────
  {
    id: 'verb_02_01',
    title: 'Oogcontact bij het eten',
    skill: 'Verbinding',
    description: 'Leg je telefoon weg tijdens het voeden of eten. Kijk je baby recht in de ogen en glimlach. Benoem wat je ziet: "Wat lekker, hè?"',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Oogcontact activeert het spiegelneuronensysteem en versterkt de hechtingssystemen in de amygdala. Herhaald positief oogcontact legt de basis voor sociaal vertrouwen.',
    skillTip: 'Houd je gezicht op 20-30 cm afstand – de optimale focusafstand voor baby\'s in de eerste maanden.',
    vermijd: 'Vermijd een strak of neutraal gezicht. Baby\'s zijn gevoelig voor "still face" – een emotieloos gezicht wekt angst op.',
    leerdoel: 'Je leert bewust aanwezig zijn en non-verbale verbinding opbouwen.',
    bron: 'Tronick, E. (2007). The Neurobehavioral and Social-Emotional Development of Infants and Children.',
  },
  {
    id: 'verb_02_02',
    title: 'Huidcontact – draag je baby',
    skill: 'Verbinding',
    description: 'Draag je baby 10-15 minuten tegen je borst, in een draagdoek of draagzak. Beweeg rustig en praat zacht. Voel de verbinding.',
    duration: '15 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Huidcontact stimuleert oxytocineproductie bij zowel vader als kind. Dit hormoon verlaagt stressniveaus en versterkt de gehechtheid.',
    skillTip: 'Huid-op-huidcontact (shirt uit) werkt het sterkst – ook bij vaders blijkt dit de hechtingshormonen te verhogen.',
    vermijd: 'Vermijd terwijl je loopt druk te bellen of sms\'en. Je baby voelt jouw spanning.',
    leerdoel: 'Je ervaart fysieke verbinding als fundament voor emotionele nabijheid.',
    bron: 'Feldman, R. (2007). Parent-infant synchrony and the construction of shared timing.',
  },
  {
    id: 'verb_02_03',
    title: 'Spiegel je baby na',
    skill: 'Verbinding',
    description: 'Doe 5 minuten niets anders dan je baby\'s geluiden en gezichtsuitdrukkingen nabootsen. Als hij "ba" zegt, zeg jij "ba". Als hij lacht, lach jij.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Mirroring (spiegelen) is de oervorm van verbinding. Het vertelt je kind: "Ik zie jou. Jij bestaat." Dit bouwt de basis voor gezonde zelfontwikkeling.',
    skillTip: 'Wacht even na elke respons – geef je baby de kans om ook te reageren. Dit is een echte dialoog!',
    vermijd: 'Vermijd overprikkeling door te snel of te druk te reageren. Rustig tempo is prettiger voor baby\'s.',
    leerdoel: 'Je ontwikkelt het vermogen om af te stemmen op de communicatiesignalen van je kind.',
    bron: 'Stern, D. (1985). The Interpersonal World of the Infant.',
  },
  {
    id: 'verb_02_04',
    title: 'Slaapliedje van jou',
    skill: 'Verbinding',
    description: 'Maak een eigen slaapliedje voor je baby – ook als je niet kunt zingen. Gebruik zijn naam erin. Zing het elke avond als vaste afsluiting.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'De stem van vader is uniek herkenbaar voor baby\'s al voor de geboorte. Een vast ritueel creëert veilige voorspelbaarheid – de kern van veilige hechting.',
    skillTip: 'Het gaat niet om kwaliteit maar om herhaling. Jouw stem is voor je baby de mooiste ter wereld.',
    vermijd: 'Vermijd een liedje van je telefoon. Jouw stem doet het werk, niet de muziek.',
    leerdoel: 'Je creëert een eigen verbindingsritueel dat je kind een leven lang bijblijft.',
    bron: 'Bowlby, J. (1988). A Secure Base: Parent-Child Attachment and Healthy Human Development.',
  },
  {
    id: 'verb_02_05',
    title: 'Vloertijd – op zijn niveau',
    skill: 'Verbinding',
    description: 'Ga op de grond liggen naast je baby of peuter. Laat hem de toon zetten. Volg zijn blik, pak wat hij pakt, reageer op wat hij doet.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Op gelijke hoogte communiceren verlaagt de machtsdrempel en vergroot het gevoel van gelijkwaardigheid. Dit helpt bij veilige hechting.',
    skillTip: 'Geen structuur, geen doel – gewoon aanwezig zijn. Laat de agenda los.',
    vermijd: 'Vermijd praten vanuit een stoel terwijl je kind op de grond speelt. De afstand communiceert onbereikbaarheid.',
    leerdoel: 'Je leert je kind te volgen in plaats van te leiden – een krachtige verbindingsvaardigheid.',
    bron: 'Landreth, G.L. (2012). Play Therapy: The Art of the Relationship.',
  },
  {
    id: 'verb_02_06',
    title: 'Dagboek voor je kind',
    skill: 'Verbinding',
    description: 'Schrijf vandaag één moment op dat je raakte – iets wat je baby deed of zei. Bewaar dit voor hem. Over 10 jaar leest hij het.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Reflectie verdiept de verbinding. Door te schrijven over je kind verwerk je jouw ervaringen als vader en vergroot je je bewustzijn van kleine, kostbare momenten.',
    skillTip: 'Gebruik een eenvoudig schrift of een notes-app. Geen perfecte zinnen nodig – gewoon eerlijk.',
    vermijd: 'Vermijd het alleen vastleggen van mijlpalen (eerste stapje). Juist de gewone momenten zijn goud.',
    leerdoel: 'Je leert bewust verbinding te waarderen en te documenteren.',
    bron: 'Siegel, D.J. & Hartzell, M. (2003). Parenting from the Inside Out.',
  },
  {
    id: 'verb_02_07',
    title: 'Baddiplomaat',
    skill: 'Verbinding',
    description: 'Neem de volledige badroutine op je vanavond. Maak er een spelletje van: zingen, plonsgeluiden, kietelen. Jij regelt alles – van douche tot pyjama.',
    duration: '20 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Zorgroutines zijn verbindingsmomenten. Als vader de zorg op zich neemt, ervaart het kind dat twee veilige volwassenen beschikbaar zijn. Dit vergroot de veerkracht.',
    skillTip: 'Praat hardop wat je doet: "Nu wassen we je haar..." Dit is taal- én verbindingsstimulering tegelijk.',
    vermijd: 'Vermijd gejaagdheid. Een rustige badroutine geeft veiligheid; een haastige geeft stress.',
    leerdoel: 'Je neemt actief zorgtaken op je en versterkt zo jouw rol als veilige hechtingsfiguur.',
    bron: 'Lamb, M.E. (2010). The Role of the Father in Child Development.',
  },
  {
    id: 'verb_02_08',
    title: 'Samen buiten kijken',
    skill: 'Verbinding',
    description: 'Ga buiten staan of zitten met je baby. Benoem samen wat je ziet: vogels, bomen, wolken. Wijs aan, laat reageren, deel de nieuwsgierigheid.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Gedeelde aandacht (joint attention) is een cruciale ontwikkelingsstap en verbindingservaring. Samen naar dezelfde dingen kijken bouwt wederzijds begrip op.',
    skillTip: 'Geef geen uitleg – dat is voor later. Nu gaat het om samen richten: "Kijk! Een hond!"',
    vermijd: 'Vermijd te veel stimuli tegelijk. Eén ding tegelijk geeft focus en rust.',
    leerdoel: 'Je oefent gedeelde aandacht, de basis van communicatie en empathie.',
    bron: 'Tomasello, M. (1995). Joint Attention as Social Cognition.',
  },
  {
    id: 'verb_02_09',
    title: 'Vader-babymassage',
    skill: 'Verbinding',
    description: 'Masseer rustig de handjes, voetjes en buik van je baby. Gebruik een beetje babyolie. Praat zacht erbij. Doe dit na het bad of voor het slapengaan.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Aanraking bevordert de afgifte van oxytocine en serotonine. Baby\'s die regelmatig worden aangeraakt vertonen een betere slaap, minder huilen en meer sociale responsiviteit.',
    skillTip: 'Gebruik lichte, vloeiende bewegingen. Volg je baby\'s lichaamstaal – als hij gespannen raakt, stop dan even.',
    vermijd: 'Vermijd harde of plotselinge aanrakingen. Veiligheid in aanraking is essentieel.',
    leerdoel: 'Je leert verbinding te geven via fysiek contact en afstemming op lichaamssignalen.',
    bron: 'Field, T. (2010). Touch for socioemotional and physical well-being: A review.',
  },
  {
    id: 'verb_02_10',
    title: 'Foto-moment van vandaag',
    skill: 'Verbinding',
    description: 'Maak vandaag één foto van een moment met je baby. Maar leg dan de telefoon weg en geniet nog 5 minuten volledig aanwezig van datzelfde moment.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Bewust aanwezig zijn na het vastleggen van een moment traint je brein om niet te vluchten naar documentatie maar te verblijven in de beleving zelf.',
    skillTip: 'Spreek jezelf toe: "Dit moment is nu. Ik ben hier." Eén zinnetje helpt je te aarden.',
    vermijd: 'Vermijd meteen te posten of te swipen. De verbinding zit in het moment, niet in de likes.',
    leerdoel: 'Je leert het verschil tussen vastleggen en beleven – en kiest bewust voor beleven.',
    bron: 'Kabat-Zinn, J. (1994). Wherever You Go, There You Are: Mindfulness Meditation in Everyday Life.',
  },

  // ─── 3-5 jaar ────────────────────────────────────────────────
  {
    id: 'verb_35_01',
    title: 'Speciale groet uitvinden',
    skill: 'Verbinding',
    description: 'Verzin samen met je kind een geheime begroeting: een speciale handshake, een knipoog-combo, een dansje. Oefen het samen en gebruik het elke dag.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Gedeelde rituelen creëren een "wij"-gevoel en bouwen een unieke vader-kindband. Ze activeren het beloningssysteem en geven het kind een gevoel van bijzonderheid.',
    skillTip: 'Laat het kind het meeste verzinnen. Jij voegt één element toe. Samen eigenaarschap vergroot de betekenis.',
    vermijd: 'Vermijd het vergeten van de groet. Herhaling maakt het ritueel krachtig.',
    leerdoel: 'Je leert een eigen verbindingsritueel te creëren dat verbinding zichtbaar maakt.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'verb_35_02',
    title: 'Luisterbeurt: vertel mij jouw dag',
    skill: 'Verbinding',
    description: 'Vraag je kind: "Wat was het leukste en het minst leuke van vandaag?" Luister volledig. Stel doorvragen. Geef geen advies, alleen aandacht.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Actief luisteren zonder oplossen vertelt je kind: "Jouw ervaringen doen ertoe." Dit versterkt het gevoel van gezien worden – de kern van verbinding.',
    skillTip: 'Gebruik "vertel me meer" en "wat vond je daar dan van?" als doorvragen. Simpel maar krachtig.',
    vermijd: 'Vermijd direct probleem oplossen. "Ik zou gewoon..." breekt de verbinding af.',
    leerdoel: 'Je leert de kracht van luisteren zonder agenda – verbinding door aanwezigheid.',
    bron: 'Gordon, T. (1970). Parent Effectiveness Training.',
  },
  {
    id: 'verb_35_03',
    title: 'Bouw iets absurds samen',
    skill: 'Verbinding',
    description: 'Pak samen blokken, lego, of willekeurige spullen. Zeg: "We gaan het gekste ding ter wereld bouwen." Geen regels, geen doel – gewoon samen bouwen.',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Vrij spelen zonder regels verlaagt de hiërarchie tussen vader en kind. Je bent gelijken. Dit schept een veilige, speelse ruimte voor echte verbinding.',
    skillTip: 'Zeg hardop gek dingen: "Dit is de turborakettoren!" Humor verdiept de speelse verbinding.',
    vermijd: 'Vermijd corrigeren of verbeteren van je kind\'s ideeën. Elk idee is goed.',
    leerdoel: 'Je ervaart verbinding door spel en humor – zonder prestatiegerichtheid.',
    bron: 'Brown, S. (2009). Play: How it Shapes the Brain, Opens the Imagination, and Invigorates the Soul.',
  },
  {
    id: 'verb_35_04',
    title: 'Knuffelminuut voor bedtijd',
    skill: 'Verbinding',
    description: 'Knuffel je kind één volle minuut voor het slapengaan. Houd hem stevig vast. Zeg niets – gewoon voelen. Adem samen langzaam in en uit.',
    duration: '2 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Een 20-seconden knuffel verhoogt al het oxytocinepeil. Eén minuut rustige knuffel voor slaaptijd activeert het parasympathische systeem en bereidt het kind voor op veilige slaap.',
    skillTip: 'Laat je kind bepalen wanneer de knuffel klaar is. Dat geeft hem controle en veiligheid.',
    vermijd: 'Vermijd een korte, afstandelijke knuffel uit gewoonte. Kwaliteit telt hier.',
    leerdoel: 'Je bouwt een fysiek veiligheidsritueel dat diepe verbinding verankert.',
    bron: 'Field, T. (2010). Touch for socioemotional and physical well-being.',
  },
  {
    id: 'verb_35_05',
    title: 'Vader-kind kookmoment',
    skill: 'Verbinding',
    description: 'Maak samen iets eenvoudigs: een boterham, een smoothie, een ei. Geef je kind een echte taak. Eet daarna samen op van wat jullie maakten.',
    duration: '20 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Samen iets maken en daarna samen genieten van het resultaat creëert een krachtig gevoel van gedeeld succes. Dit bouwt trots en verbondenheid tegelijk.',
    skillTip: 'Laat fouten er zijn. Gemorste melk is gewoon deel van het avontuur.',
    vermijd: 'Vermijd overnemen als het niet perfect gaat. Het proces is het doel, niet het resultaat.',
    leerdoel: 'Je leert verbinding te vinden in alledaagse activiteiten.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'verb_35_06',
    title: 'Wat ik leuk aan jou vind',
    skill: 'Verbinding',
    description: 'Vertel je kind drie concrete dingen die je leuk aan hem vindt. Niet "je bent lief" maar specifiek: "Ik vind het leuk hoe je altijd zo hard lacht bij grappige dingen."',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Specifieke positieve feedback is krachtiger dan generieke complimenten. Het vertelt het kind dat je echt kijkt en hem ziet als individu, niet als een rol.',
    skillTip: 'Kijk je kind aan terwijl je het zegt. Knielen op ooghoogte maakt de boodschap sterker.',
    vermijd: 'Vermijd algemene complimenten zoals "je bent geweldig". Ze voelen leeg voor kinderen.',
    leerdoel: 'Je leert gezien worden als liefdesuiting – specifiek en persoonlijk.',
    bron: 'Dweck, C. (2006). Mindset: The New Psychology of Success.',
  },
  {
    id: 'verb_35_07',
    title: 'Verhaaltje van samen',
    skill: 'Verbinding',
    description: 'Vertel voor bedtijd een verhaal waarin jullie samen de hoofdrolspelers zijn. Geef je kind inbreng: "En wat doe jij dan?" Maak het leuk en grappig.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Samen een verhaal beleven waarin je kind de held is, versterkt zijn zelfgevoel én de vader-kindband. Narratief delen is een van de krachtigste vormen van verbinding.',
    skillTip: 'Maak het kind tot de slimste, sterkste of grappigste figuur in het verhaal. Kinderen onthouden deze verhalen.',
    vermijd: 'Vermijd een standaard boek voorlezen. Dit is een eigengemaakt verhaal – samen.',
    leerdoel: 'Je ervaart de verbindingskracht van gezamenlijk verhalen maken.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2011). The Whole-Brain Child.',
  },
  {
    id: 'verb_35_08',
    title: 'Dans met mij',
    skill: 'Verbinding',
    description: 'Zet een liedje op dat je kind leuk vindt. Dans samen – gek, wild, rustig, egal. Laat je kind de moves bepalen. Doe ze na.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Muziek en beweging synchroniseren het zenuwstelsel van twee mensen. Samen dansen creëert een krachtige biofysiologische verbinding, boven op het plezier.',
    skillTip: 'Overdrijf de bewegingen. Lachen verdiept verbinding – dat is wetenschappelijk aangetoond.',
    vermijd: 'Vermijd kiezen van wat jij leuk vindt. Dit is zijn moment en zijn muziek.',
    leerdoel: 'Je ervaart verbinding door vrije, speelse gezamenlijke beweging.',
    bron: 'Porges, S.W. (2011). The Polyvagal Theory.',
  },
  {
    id: 'verb_35_09',
    title: 'Plattegrond van thuis tekenen',
    skill: 'Verbinding',
    description: 'Teken samen een plattegrond van jullie huis. Laat je kind aanwijzen waar iedereen slaapt, waar jullie eten. Praat over wat elk kamertje betekent.',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kinderen voelen sterke verbinding met de fysieke ruimte van hun thuis. Het bespreken van die ruimte activeert gevoelens van veiligheid en saamhorigheid.',
    skillTip: 'Voeg favoriet-plekje van elk gezinslid toe. Vraag: "Waarom is dát jouw favoriete plek?"',
    vermijd: 'Vermijd het overnemen van de tekening. Laat hem tekenen, ook al is het onherkenbaar.',
    leerdoel: 'Je verdiept verbinding door reflectie op gedeelde ruimte en herinneringen.',
    bron: 'Bowlby, J. (1988). A Secure Base.',
  },
  {
    id: 'verb_35_10',
    title: 'Stilte samen delen',
    skill: 'Verbinding',
    description: 'Ga samen buiten of in een rustige kamer zitten. Zeg: "Laten we eens luisteren naar alle geluiden." Zit 5 minuten samen stil en luister.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Stilte samen kunnen delen is een teken van diepe verbinding. Kinderen die leren stil te zijn naast hun vader ontwikkelen een veilige basis voor innerlijk leven.',
    skillTip: 'Fluister na afloop: "Wat hoorde jij?" en deel jouw antwoord ook.',
    vermijd: 'Vermijd het verbazen van je kind met plotselinge stilte zonder uitleg. Kondig het samen aan.',
    leerdoel: 'Je ervaart dat verbinding ook bestaat zonder woorden of actie.',
    bron: 'Kabat-Zinn, J. & Kabat-Zinn, M. (1997). Everyday Blessings.',
  },

  // ─── 6-9 jaar ────────────────────────────────────────────────
  {
    id: 'verb_69_01',
    title: 'Interview met je kind',
    skill: 'Verbinding',
    description: 'Doe alsof je een journalist bent die je kind interviewt. Stel vragen zoals: "Wat wil je later worden?", "Wat is je favoriete herinnering?", "Wat vind je het moeilijkst?" Neem het op als je kind dat leuk vindt.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Kinderen van 6-9 jaar ontwikkelen een sterk zelfconcept. Interesse tonen in hun gedachten en dromen bevestigt dat hun innerlijk leven waardevol is.',
    skillTip: 'Vraag ook naar wat hij lastig vindt – niet alleen het positieve. Dat laat echte interesse zien.',
    vermijd: 'Vermijd corrigeren van "verkeerde" antwoorden. Dit is geen quiz – het is een gesprek.',
    leerdoel: 'Je verdiept de verbinding door echte, nieuwsgierige interesse te tonen in wie je kind is.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'verb_69_02',
    title: 'Wandeling zonder doel',
    skill: 'Verbinding',
    description: 'Ga een wandeling maken zonder bestemming. Laat je kind de richting kiezen bij elke splitsing. Praat over wat je ziet, of praat helemaal niet. Gewoon samen lopen.',
    duration: '20 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Zij-aan-zij activiteiten verlagen de drempel voor openhartige gesprekken. Kinderen praten makkelijker zonder oogcontact – naast elkaar dan tegenover elkaar.',
    skillTip: 'Vermijd je telefoon volledig. Laat je kind het tempo bepalen.',
    vermijd: 'Vermijd een doel of prestatie aan de wandeling hangen ("we lopen 5 kilometer"). Laat het open zijn.',
    leerdoel: 'Je ervaart hoe ongestructureerde tijd samen de verbinding verdiept.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2011). The Whole-Brain Child.',
  },
  {
    id: 'verb_69_03',
    title: 'Jouw kinderjaar delen',
    skill: 'Verbinding',
    description: 'Vertel je kind iets over jezelf toen je zijn leeftijd had. Iets wat je leuk vond, iets wat je moeilijk vond, iets grappigs dat je deed. Vraag daarna hoe dat voor hem is.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Zelfonthulling door ouders vergroot de emotionele intimiteit en toont dat vader ook een mens is met een eigen verhaal. Dit vergroot empathie en verbondenheid.',
    skillTip: 'Kies een verhaal met een kleine kwetsbaarheid erin. Niet alleen successen – ook worstelingen zijn verbindend.',
    vermijd: 'Vermijd verhalen gebruiken als les of moraal. Vertel gewoon – zonder punt.',
    leerdoel: 'Je leert kwetsbaarheid als verbindingstool inzetten.',
    bron: 'Brown, B. (2010). The Gifts of Imperfection.',
  },
  {
    id: 'verb_69_04',
    title: 'Gezamenlijk project starten',
    skill: 'Verbinding',
    description: 'Start samen een klein project dat meerdere dagen duurt: een mini-tuin, een boekenplank bouwen, een stripverhaal tekenen. Bespreek samen het plan.',
    duration: '20 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Gedeelde projecten geven kinderen het gevoel dat vader echt in hun leven investeert. De verwachting van een vervolg versterkt de continuïteit van verbinding.',
    skillTip: 'Schrijf samen op papier wat jullie gaan maken. Een plan op papier maakt het concreet en spannend.',
    vermijd: 'Vermijd een project kiezen dat jij interessant vindt. Vertrek vanuit wat hij wil maken.',
    leerdoel: 'Je leert hoe gedeeld doel-stellen verbinding over tijd heen bouwt.',
    bron: 'Csikszentmihalyi, M. (1990). Flow: The Psychology of Optimal Experience.',
  },
  {
    id: 'verb_69_05',
    title: 'Kaartje schrijven',
    skill: 'Verbinding',
    description: 'Schrijf je kind een handgeschreven kaartje of briefje. Leg het op zijn kamer of in zijn broodtrommel. Schrijf iets specifieks: wat je zag, wat je trots op maakt, wat je fijn vindt.',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Een handgeschreven bericht is tastbaar en permanent – het kind kan het bewaren. Het toont dat vader bewust tijd nam voor hem, ook als hij er niet bij is.',
    skillTip: 'Gebruik zijn naam en een herinnering: "Gisteren zag ik hoe je..." Dat maakt het persoonlijk.',
    vermijd: 'Vermijd een appje of emoji-bericht sturen. Handgeschreven is echt anders.',
    leerdoel: 'Je ervaart de kracht van een fysiek, persoonlijk gebaar als uitdrukking van verbinding.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'verb_69_06',
    title: 'Vragen-spel bij het eten',
    skill: 'Verbinding',
    description: 'Tijdens het avondeten: elk gezinslid stelt één vraag die de anderen mogen beantwoorden. Geen mobiel. Vader begint.',
    duration: '20 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Regelmatige gezamenlijke maaltijden met gesprek zijn één van de sterkst gedocumenteerde beschermende factoren in de ontwikkeling van kinderen.',
    skillTip: 'Start met een grappige vraag om de drempel te verlagen. "Wie zou winnen: een gorilla of een ijsbeer?"',
    vermijd: 'Vermijd vragen over school of huiswerk. Dit is verbindingstijd, niet evaluatietijd.',
    leerdoel: 'Je bouwt een gezinsritueel van gedeelde aandacht en gesprek.',
    bron: 'National Center on Addiction and Substance Abuse. (2011). The Importance of Family Dinners.',
  },
  {
    id: 'verb_69_07',
    title: 'Tekening van jullie relatie',
    skill: 'Verbinding',
    description: 'Vraag je kind: "Teken jij en ik." Kijk hoe hij dat tekent. Vraag erna: "Vertel eens over je tekening." Teken daarna ook jij hetzelfde.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Tekenen over relaties activeert niet-verbale emotionele representaties. Je krijgt inzicht in hoe je kind jullie band beleeft – waardevolle informatie.',
    skillTip: 'Stel geen sturende vragen. "Vertel eens" is genoeg. Laat hem praten.',
    vermijd: 'Vermijd reageren als de tekening je verrast of teleurstelt. Vraag gewoon meer.',
    leerdoel: 'Je verdiept inzicht in hoe je kind jullie verbinding ervaart.',
    bron: 'Stern, D. (1985). The Interpersonal World of the Infant.',
  },
  {
    id: 'verb_69_08',
    title: 'Trots-moment benoemen',
    skill: 'Verbinding',
    description: 'Vertel je kind specifiek iets waar je trots op was deze week – niet over een cijfer of prestatie, maar over zijn karakter: doorzetten, aardig zijn, eerlijk zijn.',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Trots die gericht is op karakter in plaats van prestatie versterkt de intrinsieke motivatie en vertelt het kind wie hij is, niet alleen wat hij doet.',
    skillTip: 'Gebruik de formule: "Ik was trots toen jij... omdat... dat laat zien dat jij..."',
    vermijd: 'Vermijd trots koppelen aan resultaat: "Ik ben trots dat je een 9 haalde." Dat is prestatie, geen karakter.',
    leerdoel: 'Je leert verbinding te bouwen via erkentenis van wie je kind is.',
    bron: 'Dweck, C. (2006). Mindset: The New Psychology of Success.',
  },
  {
    id: 'verb_69_09',
    title: 'Helpen bij iets wat hij doet',
    skill: 'Verbinding',
    description: 'Vraag je kind: "Mag ik jou helpen met iets wat jij aan het doen bent?" Speel mee in zijn wereld. Volg zijn regels. Wees de assistent, niet de leider.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Binnentreden in de wereld van het kind als volgeling geeft hem controle en bevestigt dat zijn interesses waardevol zijn. Dit vergroot het gevoel van respect en verbinding.',
    skillTip: 'Vraag: "Hoe werkt dit?" en "Wat moet ik doen?" Echte nieuwsgierigheid, geen performance.',
    vermijd: 'Vermijd overnemen of verbeteren. Je bent te gast in zijn wereld.',
    leerdoel: 'Je ervaart verbinding als je kind de expert is en jij de leerling.',
    bron: 'Landreth, G.L. (2012). Play Therapy: The Art of the Relationship.',
  },
  {
    id: 'verb_69_10',
    title: 'Toekomstgesprek',
    skill: 'Verbinding',
    description: 'Stel je kind de vraag: "Als jij later groot bent, wat zou je dan het allerliefste doen?" Luister. Stel doorvragen. Deel ook jouw droom van toen je klein was.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Toekomstgesprekken activeren het zelf-narratief van het kind en laten zien dat vader geïnteresseerd is in zijn diepste wensen. Dit vergroot emotionele intimiteit.',
    skillTip: 'Geef nooit kritiek op zijn droom – hoe onrealistisch ook. Dromen zijn heilig in dit gesprek.',
    vermijd: 'Vermijd "ja maar dat is moeilijk" of praktische bezwaren. Laat de droom leven.',
    leerdoel: 'Je leert verbinding te verdiepen door naar iemands diepste wensen te luisteren.',
    bron: 'Gottman, J. (1999). The Marriage Clinic: A Scientifically Based Marital Therapy.',
  },

  // ─── 10-12 jaar ──────────────────────────────────────────────
  {
    id: 'verb_1012_01',
    title: 'Zijn wereld leren kennen',
    skill: 'Verbinding',
    description: 'Vraag je kind zijn favoriete YouTuber, game, of muziek met je te delen. Kijk of luister samen 10 minuten. Stel vragen. Oordeel niet.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Adolescenten trekken zich terug als ouders hun wereld afwijzen. Interesse in hun cultuur en media vergroot de bereidheid om ook moeilijkere onderwerpen te bespreken.',
    skillTip: 'Zeg: "Leg me uit waarom dit zo leuk is" – oprecht vragen, niet ironisch. Echte nieuwsgierigheid opent deuren.',
    vermijd: 'Vermijd commentaar op wat je ziet of hoort. Dit is géén evaluatiemoment.',
    leerdoel: 'Je oefent het binnengaan in de wereld van je kind zonder oordeel.',
    bron: 'Steinberg, L. (2011). Adolescence (9th ed.).',
  },
  {
    id: 'verb_1012_02',
    title: 'Samenwerken in de keuken',
    skill: 'Verbinding',
    description: 'Laat je kind een maaltijd kiezen en mee koken. Zorg dat hij een echte, betekenisvolle taak heeft. Eet daarna samen wat jullie maakten.',
    duration: '40 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Bijdragen aan het gezin met een tastbaar resultaat vergroot het gevoel van competentie en verbondenheid. Het kind voelt zich serieus genomen als volwaardige partner.',
    skillTip: 'Laat hem echt verantwoordelijk zijn voor één gerecht. Niet begeleiden – vertrouwen.',
    vermijd: 'Vermijd na elk stap commentaar geven. Laat hem zijn gang gaan.',
    leerdoel: 'Je ervaart verbinding via gedeelde verantwoordelijkheid en samenwerking.',
    bron: 'Deci, E.L. & Ryan, R.M. (1985). Intrinsic Motivation and Self-Determination in Human Behavior.',
  },
  {
    id: 'verb_1012_03',
    title: 'Brief aan de toekomst schrijven',
    skill: 'Verbinding',
    description: 'Schrijf elk een brief aan de andere: jij schrijft een brief aan hem over 10 jaar, hij schrijft er een aan jou. Stop ze in een envelop en spreek af wanneer jullie ze openen.',
    duration: '20 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Brieven aan de toekomst activeren toekomstoriëntatie, empathie en het bewust verwoorden van gevoelens. Het creëert een tijdscapsule van verbinding.',
    skillTip: 'Lees elkaars brief niet voor de afgesproken datum. De belofte maakt het ritueel krachtig.',
    vermijd: 'Vermijd te perfecte taal. Eerlijk en echt is meer waard dan mooi geformuleerd.',
    leerdoel: 'Je ervaart verbinding als intentioneel, langdurig gebaar.',
    bron: 'McAdams, D.P. (2001). The psychology of life stories. Review of General Psychology.',
  },
  {
    id: 'verb_1012_04',
    title: 'Geen telefoon-avond',
    skill: 'Verbinding',
    description: 'Spreek met je kind af: van na het eten tot bedtijd liggen alle telefoons weg. Doen jullie iets samen, of gewoon elk iets voor jezelf – maar samen in de ruimte.',
    duration: '60 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Schermtijd verlaagt de kwaliteit van aanwezigheid. Zelfs aanwezig zijn zonder activiteit vergroot het gevoel van verbondenheid als telefoons weg zijn.',
    skillTip: 'Zet je eigen telefoon als eerste weg – dan is de norm gezet zonder discussie.',
    vermijd: 'Vermijd het aankondigen als straf of les. Presenteer het als een gezinsexperiment.',
    leerdoel: 'Je ervaart wat het doet met de sfeer als schermen verdwijnen.',
    bron: 'Turkle, S. (2015). Reclaiming Conversation: The Power of Talk in a Digital Age.',
  },
  {
    id: 'verb_1012_05',
    title: 'Eerlijk gesprek: hoe gaat het écht?',
    skill: 'Verbinding',
    description: 'Vraag je kind: "Hoe gaat het écht met jou? Niet het standaard antwoord – echt." Wacht. Geef ruimte. Luister zonder te reageren op de inhoud.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'De overgang naar de puberteit gaat gepaard met terugtrekking. Actief uitnodigen voor echte gesprekken – zonder agenda – houdt de communicatiekanalen open.',
    skillTip: 'Als hij zegt "goed" – wacht dan gewoon. Vul de stilte niet in. Wacht op meer.',
    vermijd: 'Vermijd direct advies geven, problemen oplossen, of oordelen. Alleen luisteren.',
    leerdoel: 'Je leert echte openheid uitnodigen door actief te luisteren zonder te reageren.',
    bron: 'Gordon, T. (1970). Parent Effectiveness Training.',
  },
  {
    id: 'verb_1012_06',
    title: 'Hetzelfde boek lezen',
    skill: 'Verbinding',
    description: 'Kies samen een boek dat jullie allebei gaan lezen – apart, in jullie eigen tempo. Spreek af: elke avond 2-3 minuten bespreken wat jullie lazen.',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Gedeelde ervaringen creëren gedeelde referentiekaders. Een boek samen bespreken bouwt intellectuele intimiteit – een verdieping van verbinding.',
    skillTip: 'Vraag: "Wat vond jij van dit stuk?" Laat hem beginnen. Voeg daarna jouw mening toe.',
    vermijd: 'Vermijd een boek kiezen dat alleen jij interessant vindt. Kies samen – of laat hem kiezen.',
    leerdoel: 'Je bouwt een gedeeld intellectueel ritueel als vorm van verbinding.',
    bron: 'Csikszentmihalyi, M. (1990). Flow: The Psychology of Optimal Experience.',
  },
  {
    id: 'verb_1012_07',
    title: 'Mijn verhaal als kind van 11',
    skill: 'Verbinding',
    description: 'Vertel je kind over jezelf toen je zijn leeftijd was: wat was je grootste angst? Je beste vriend? Je grootste droom? Je pijnlijkste herinnering?',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Ouderlijke zelfonthulling – zeker met kwetsbaarheid – doorbreekt de mythe van de perfecte vader. Dit vergroot de emotionele veiligheid en maakt het kind vrijer om ook zichzelf te delen.',
    skillTip: 'Kies een verhaal dat echt gevoeld heeft. Niet angstaanjagend, maar authentiek.',
    vermijd: 'Vermijd het verhaal gebruiken om advies te geven. Het verhaal is op zichzelf genoeg.',
    leerdoel: 'Je ervaart hoe kwetsbaarheid de diepste verbinding schept.',
    bron: 'Brown, B. (2012). Daring Greatly.',
  },
  {
    id: 'verb_1012_08',
    title: 'Samen sport kijken of beleven',
    skill: 'Verbinding',
    description: 'Kijk een wedstrijd samen, of doe samen iets sportiefs. Praat erover. Duim samen. Leef je uit. Wees enthousiast samen.',
    duration: '30 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Gezamenlijke enthousiasme-ervaringen (bijv. sport) zijn krachtige verbindingsmomenten. Gedeeld plezier vergroot oxytocine en de band.',
    skillTip: 'Laat hem de sport kiezen – niet per se de jouwe. Zijn interesse staat centraal.',
    vermijd: 'Vermijd het uitleggen of corrigeren. Gewoon samen genieten is het doel.',
    leerdoel: 'Je ervaart verbinding via gedeelde passie en enthousiasme.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'verb_1012_09',
    title: 'Vragen-kaartjes maken',
    skill: 'Verbinding',
    description: 'Maak samen kaartjes met vragen die jullie aan elkaar willen stellen. Schrijf elk 5 vragen op. Wissel dan kaartjes uit en beantwoord ze beurtelings.',
    duration: '30 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Het zelf formuleren van vragen vergroot de betrokkenheid bij het gesprek. Het format maakt het speels en veilig om diepere vragen te stellen.',
    skillTip: 'Lach om de grappige vragen. Neem de serieuze serieus. Beide zijn verbindend.',
    vermijd: 'Vermijd defensief reageren op zijn vragen aan jou. Hij mag alles vragen.',
    leerdoel: 'Je leert verbinding te verdiepen via structuur van wederzijdse nieuwsgierigheid.',
    bron: 'Aron, A. et al. (1997). The experimental generation of interpersonal closeness.',
  },
  {
    id: 'verb_1012_10',
    title: 'Terugkijken op een goed moment',
    skill: 'Verbinding',
    description: 'Haal samen een herinnering op van een fijn moment dat jullie deelden. Bekijk foto\'s als die er zijn. Praat over wat dat moment zo bijzonder maakte.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Positieve herinneringen ophalen versterkt de band door gedeeld narratief. Dit bouwt de "relationship bank" op – het reservoir van positieve verbinding.',
    skillTip: 'Vraag: "Wat herinner jij je van dat moment?" Zijn versie kan anders zijn dan de jouwe – dat is goed.',
    vermijd: 'Vermijd alleen praten over grote uitjes. Kleine dagelijkse momenten zijn even krachtig.',
    leerdoel: 'Je ervaart hoe gedeeld geheugen een fundament voor verbinding is.',
    bron: 'Gottman, J. (1999). The Marriage Clinic.',
  },

  // ─── 13-16 jaar ──────────────────────────────────────────────
  {
    id: 'verb_1316_01',
    title: 'Onuitgenodigd toch aanwezig zijn',
    skill: 'Verbinding',
    description: 'Als je tiener thuis is maar op zijn kamer, klop dan aan en vraag: "Ik kom gewoon even gedag zeggen." Kom binnen, zeg drie zinnen, en ga dan weer weg. Geen agenda.',
    duration: '5 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Tieners willen autonomie maar hebben ook verbinding nodig. Korte, ongecompliceerde aanrakingen van verbinding bouwen vertrouwen zonder druk te zetten.',
    skillTip: 'Geef geen commentaar op zijn kamer, zijn muziek of zijn kleding. Gewoon: "Hé, ik wilde even kijken hoe je erbij zit."',
    vermijd: 'Vermijd een gesprek forceren. Drie zinnen is genoeg. Ga dan weg.',
    leerdoel: 'Je leert verbinding aanbieden zonder te eisen dat je kind reageert.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'verb_1316_02',
    title: 'Mening vragen over iets echts',
    skill: 'Verbinding',
    description: 'Vraag je tiener zijn mening over iets wat jij écht wil weten: een keuze je moet maken, een nieuwtje, een situatie op je werk. Luister serieus. Bedank hem voor zijn mening.',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Tieners voelen zich ernstig genomen als hun mening wordt gevraagd over echte volwassen kwesties. Dit vergroot de verbinding en stimuleert kritisch denken.',
    skillTip: 'Gebruik zijn mening ook echt. Zeg later: "Ik dacht nog aan wat je zei over..." Dat toont dat je echt luisterde.',
    vermijd: 'Vermijd vragen stellen als je eigenlijk geen antwoord wil. Dat voelen tieners meteen.',
    leerdoel: 'Je ervaart hoe respect voor zijn mening de verbinding verdiept.',
    bron: 'Deci, E.L. & Ryan, R.M. (1985). Intrinsic Motivation and Self-Determination.',
  },
  {
    id: 'verb_1316_03',
    title: 'Gezamenlijke playlist maken',
    skill: 'Verbinding',
    description: 'Maak samen een playlist op Spotify of YouTube: elk 10 nummers die je toevoegt. Luister daarna samen een tijdje en praat over de keuzes.',
    duration: '20 min',
    ageGroups: ['13-16'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Muzikale smaak is diep verbonden met identiteit bij tieners. Geïnteresseerd zijn in zijn muziek en hem laten zien in jouw smaak creëert wederzijds respect.',
    skillTip: 'Voeg echt nummers toe die jij leuk vindt – ook al zijn ze ouder. Authenticiteit werkt beter dan aanpassen.',
    vermijd: 'Vermijd commentaar op zijn muziek: "Dit is toch geen muziek?" sluit deuren.',
    leerdoel: 'Je ervaart verbinding via wederzijdse blootstelling aan elkaars culturele wereld.',
    bron: 'Arnett, J.J. (1995). Adolescents\' uses of media for self-socialization.',
  },
  {
    id: 'verb_1316_04',
    title: 'Autorit zonder muziek of radio',
    skill: 'Verbinding',
    description: 'De volgende keer dat jullie samen in de auto zijn: zet de radio of muziek uit. Praat over wat maar opkomt, of rijd gewoon in stilte. Beide is goed.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'De auto is een bijzondere verbindingsruimte voor tieners: zijdelings, met beperkt oogcontact, tijdelijk. Dit maakt openhartige gesprekken makkelijker.',
    skillTip: 'Begin met iets lichts of observeer iets buiten. "Kijk die auto eens." Zet de toon zonder dwang.',
    vermijd: 'Vermijd grote onderwerpen forceren. Laat het gesprek organisch gaan of helemaal niet.',
    leerdoel: 'Je leert ongestructureerde tijd als verbindingskans te herkennen.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'verb_1316_05',
    title: 'Excuses aanbieden als je fout zat',
    skill: 'Verbinding',
    description: 'Denk aan een moment deze week waarbij je te hard, te snel of oneerlijk was. Ga naar je tiener en zeg het recht voor zijn raap: "Ik was fout. Sorry."',
    duration: '5 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Echte excuses van vader zijn één van de krachtigste verbindingsmomenten die er zijn. Ze doorbreken de mythe van de onfeilbare ouder en bouwen vertrouwen.',
    skillTip: 'Zeg alleen sorry als je het meent. Een half excuus ("Sorry als je je zo voelt") doet meer schade dan geen excuus.',
    vermijd: 'Vermijd maar verklaren of verdedigen. "Sorry, maar..." is geen sorry.',
    leerdoel: 'Je ervaart hoe verantwoordelijkheid nemen de verbinding herstelt én verdiept.',
    bron: 'Gottman, J. (2011). Raising Emotionally Intelligent Children.',
  },
  {
    id: 'verb_1316_06',
    title: 'Film of serie samen kijken',
    skill: 'Verbinding',
    description: 'Laat je tiener een film of serie kiezen die hij wil kijken. Kijk samen. Praat erna 5 minuten over wat jullie zagen. Vraag naar zijn mening eerst.',
    duration: '90 min',
    ageGroups: ['13-16'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Film samen kijken biedt een gedeelde ervaring en een emotionele ingang voor gesprek. Na de film is er een veilige context om over gevoelens en waarden te praten.',
    skillTip: 'Stel vragen als: "Wat vond je het indrukwekkendste moment?" in plaats van "Was het goed?"',
    vermijd: 'Vermijd je telefoon pakken tijdens de film. Aanwezig zijn is de verbinding.',
    leerdoel: 'Je leert verbinding te vinden via gedeelde cultuurconsumptie.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'verb_1316_07',
    title: 'Schrijf op wat je waardeert',
    skill: 'Verbinding',
    description: 'Schrijf voor jezelf vijf dingen op die je waardeert aan je tiener – specifiek, concreet. Deel daarna één ding mondeling met hem, zonder verwachting van een reactie.',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Tieners kampen vaak met zelfkritiek en onzekerheid. Bevestiging van vader – specifiek en onverwacht – heeft een buitengewoon krachtig effect op zelfwaardering.',
    skillTip: 'Kies het moment goed. Niet als hij iets fout deed, niet als je hem iets vraagt. Gewoon zomaar.',
    vermijd: 'Vermijd "maar" toevoegen: "Ik vind je moedig, maar..." Laat het zuiver.',
    leerdoel: 'Je oefent het benoemen van wat je ziet en waardeert – onvoorwaardelijk.',
    bron: 'Brown, B. (2010). The Gifts of Imperfection.',
  },
  {
    id: 'verb_1316_08',
    title: 'Samen iets nieuws proberen',
    skill: 'Verbinding',
    description: 'Kies iets wat jullie allebei nog nooit hebben gedaan: een nieuw gerecht, een game, een sport. Doe het samen. Wees allebei beginner.',
    duration: '30 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Gedeelde noviteitservaringen versterken verbinding doordat beide personen kwetsbaar zijn als beginner. Vader die ook onzeker is normaliseert falen en vergroot verbondenheid.',
    skillTip: 'Lach om je eigen fouten. Toon dat onzekerheid normaal is voor volwassenen ook.',
    vermijd: 'Vermijd een activiteit kiezen waarbij jij duidelijk beter bent. Echte gelijkheid is het doel.',
    leerdoel: 'Je ervaart verbinding via gedeelde kwetsbaarheid en nieuwigheid.',
    bron: 'Brown, B. (2012). Daring Greatly.',
  },
  {
    id: 'verb_1316_09',
    title: 'Eigen jeugd delen – het moeilijke',
    skill: 'Verbinding',
    description: 'Vertel je tiener iets over jouw adolescentie dat je nooit eerder vertelde. Iets wat moeilijk was: ruzie, falen, onzekerheid, eenzaamheid.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Tieners voelen zich diep alleen in hun worsteling. Vader die zijn eigen adolescente pijn deelt, doorbreekt isolatie en toont dat overleven mogelijk is. Krachtige verbindingservaring.',
    skillTip: 'Kies een verhaal dat echt resoneerde. Maak het niet te dramatisch – gewoon eerlijk.',
    vermijd: 'Vermijd het verhaal gebruiken als "zie je wel, ik heb het ook zwaar gehad." Dat maakt het competitief.',
    leerdoel: 'Je ervaart hoe authentieke kwetsbaarheid de diepste verbinding schept.',
    bron: 'Brown, B. (2012). Daring Greatly: How the Courage to Be Vulnerable Transforms the Way We Live.',
  },
  {
    id: 'verb_1316_10',
    title: 'Plannen voor de toekomst bespreken',
    skill: 'Verbinding',
    description: 'Vraag je tiener waar hij over 5 jaar wil zijn. Luister volledig. Deel daarna één ding dat jij voor hem wil – niet wat je verwacht, maar wat jij voor hem hoopt.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Toekomstgesprekken met tieners zijn verbindend als ze open zijn – zonder druk of sturing. Vader die zijn hoop deelt (in plaats van verwachting) versterkt de veiligheid.',
    skillTip: 'Zeg: "Ik hoop voor jou dat..." niet "Ik wil dat jij..." Het verschil is enorm.',
    vermijd: 'Vermijd prestatiegericht praten over studie of werk. Focus op geluk en betekenis.',
    leerdoel: 'Je leert toekomstgesprekken te voeren als verbindingsmoment in plaats van planningsgesprek.',
    bron: 'Deci, E.L. & Ryan, R.M. (2000). Self-Determination Theory and the Facilitation of Intrinsic Motivation.',
  },
];
