// Verbinding – Ronde 2: 50 nieuwe interactieve taken (5 leeftijdsgroepen × 10)
import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_15: InteractiveTask[] = [

  // ─── 0-2 jaar ────────────────────────────────────────────────
  {
    id: 'verb_02_11',
    title: 'Zijn eerste woord herhalen',
    skill: 'Verbinding',
    description: 'Als je baby een geluid of proto-woord maakt: herhaal het terug. Houd dit tien minuten vol als een echte dialoog. Zijn stem gevolgd door jouw echo.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Vocale responsiviteit is een van de sterkste verbindingssignalen voor baby\'s. Het bevestigt: "Jouw stem doet ertoe en ik luister." Dit versterkt de taalbereidheid en de hechting.',
    skillTip: 'Voeg soms een kleine variatie toe: als hij "ba" zegt, zeg jij "ba-ba". Dat stimuleert verdere vocalisatie.',
    vermijd: 'Vermijd de hele dialoog overnemen. Wacht op zijn volgende uiting voor je reageert.',
    leerdoel: 'Je ervaart vocale responsiviteit als vroege verbindingsvorm.',
    bron: 'Trevarthen, C. (1979). Communication and cooperation in early infancy.',
  },
  {
    id: 'verb_02_12',
    title: 'Samen naar muziek luisteren',
    skill: 'Verbinding',
    description: 'Houd je baby vast en luister samen naar rustige muziek. Beweeg zacht mee. Kijk hem aan. Deel het muzikale moment bewust.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Muziek synchroniseert hersengolven en lichaamsritmes. Baby\'s die muziek delen met een zorger vertonen verhoogde sociale responsiviteit en een sterkere hechting.',
    skillTip: 'Kies rustige, melodieuze muziek. Kijk naar zijn reactie op verschillende melodieën – dat is hem leren kennen.',
    vermijd: 'Vermijd te harde of drukke muziek. Sensorische overprikkeling is het tegendeel van verbinding.',
    leerdoel: 'Je gebruikt muziek als gedeeld zintuiglijk verbindingsmoment.',
    bron: 'Trehub, S.E. (2003). The developmental origins of musicality.',
  },
  {
    id: 'verb_02_13',
    title: 'Zijn wereld benoemen',
    skill: 'Verbinding',
    description: 'Loop samen door een kamer of buiten. Benoem rustig alles wat hij ziet: "Kijk, een boom. Kijk, een vogel. Kijk, dat is blauw." Maak zijn wereld met woorden.',
    duration: '15 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Gedeelde aandacht koppelen aan taal is de basis van taalverwerving én verbinding. Vader die de wereld van zijn kind benoemt, bouwt letterlijk de neurale verbindingen voor taal en relatie.',
    skillTip: 'Volg zijn blik. Benoem wat hij kijkt, niet wat jij interessant vindt. Zijn aandacht is het kompas.',
    vermijd: 'Vermijd overladen met woorden. Eén woord per object, rustig. Minder is meer voor baby\'s.',
    leerdoel: 'Je verbindt taal aan gedeelde aandacht als dubbele verbindingservaring.',
    bron: 'Tomasello, M. (1995). Joint Attention as Social Cognition.',
  },
  {
    id: 'verb_02_14',
    title: 'Zijn eerste boek samen',
    skill: 'Verbinding',
    description: 'Lees een simpel prentenboek voor aan je baby, ook als hij nog te jong lijkt. Wijs naar plaatjes. Kijk hem aan. Varieer je stem. Dit is samen zijn.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Voorlezen versterkt taalontwikkeling, maar ook de hechting via stem, ritme en nabijheid. De combinatie van stem, gezicht en verhaal schept een rijke verbindingservaring.',
    skillTip: 'Je hoeft het verhaal niet te "lezen" – kijk naar de plaatjes en vertel. Jouw eigen woorden zijn net zo goed.',
    vermijd: 'Vermijd het boek neerleggen als hij afgeleid raakt. Volg zijn aandacht – dat is de les.',
    leerdoel: 'Je introduceert lezen als een verbindingsritueel via stem en aanwezigheid.',
    bron: 'Bus, A.G. et al. (1995). Joint book reading makes for success in learning to read.',
  },
  {
    id: 'verb_02_15',
    title: 'Huidcontact met bewuste aandacht',
    skill: 'Verbinding',
    description: 'Houd je baby vast en concentreer je volledig op het contact: zijn warmte, zijn gewicht, zijn ademhaling. Wees volledig aanwezig in het huidcontact.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Bewust huidcontact – niet automatisch maar intentioneel – vergroot de oxytocineafgifte bij beide partijen en verdiept de hechtingsband.',
    skillTip: 'Sluit je ogen een paar tellen en concentreer op de sensaties van het contact. Dat verdiept de aanwezigheid.',
    vermijd: 'Vermijd huidcontact terwijl je naar je telefoon kijkt. Bewust contact is het doel.',
    leerdoel: 'Je ervaart bewust huidcontact als intensere verbindingsvorm dan automatisch dragen.',
    bron: 'Field, T. (2010). Touch for socioemotional and physical well-being.',
  },
  {
    id: 'verb_02_16',
    title: 'Ritueel voor een nieuw seizoen',
    skill: 'Verbinding',
    description: 'Maak een klein ritueel rond een seizoensverandering: eerste keer buiten in de lente, eerste sneeuw, eerste herfstblad. Beleef het samen bewust.',
    duration: '15 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Seizoensrituelen geven structuur aan de tijd en creëren gedeelde herinneringen. Ze verbinden dagelijks leven met een groter ritme en een gedeeld bewustzijn.',
    skillTip: 'Maak het klein en concreet: "Kijk, het eerste blad dat valt. Dit is herfst." Dat is genoeg.',
    vermijd: 'Vermijd overplannen. Een simpel, bewust moment is waardevoller dan een groot uitje.',
    leerdoel: 'Je creëert seizoensrituelen als jaarlijkse verbindingsankers.',
    bron: 'Imber-Black, E. & Roberts, J. (1992). Rituals for Our Times.',
  },
  {
    id: 'verb_02_17',
    title: 'Contact na een lange dag',
    skill: 'Verbinding',
    description: 'Als je na een lange werkdag thuiskomt: neem bewust 5 minuten voor je baby voor je iets anders doet. Geen telefoon, geen eten, geen gesprekken. Eerst verbinding.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Het eerste contact na een afwezigheid is neurobiologisch een herstelmoment voor hechting. Bewust dit moment pakken herstelt de verbinding en signaleert: jij bent mijn prioriteit.',
    skillTip: 'Decomprimeer het eerst: was je handen, adem even, dan pas naar je kind. Dan kun je écht aanwezig zijn.',
    vermijd: 'Vermijd direct van werk naar kind gaan terwijl je nog in werkmentaliteit zit. Even resetten.',
    leerdoel: 'Je maakt het thuiskomen een bewust verbindingsmoment via intentionele transitie.',
    bron: 'Repetti, R.L. (1994). Short-term and long-term processes linking job stressors to father-child interaction.',
  },
  {
    id: 'verb_02_18',
    title: 'Zijn verbazing delen',
    skill: 'Verbinding',
    description: 'Als je baby iets ontdekt dat hem verrast (een nieuw geluid, een nieuw object): reageer met echte verbazing mee. Grote ogen, verraste stem. Deel zijn wonder.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Gedeelde verwondering (shared wonder) is een van de meest verbindende ervaringen voor baby\'s en ouders. Het synchroniseert emotionele toestand en bouwt gedeeld geheugen.',
    skillTip: 'Doe het echt. Baby\'s voelen nep-enthousiasme. Laat je echt verrassen door zijn wereld.',
    vermijd: 'Vermijd neerbuigend "dat is gewoon een blad." Voor hem is het magisch – en dat is het echte.',
    leerdoel: 'Je ervaart gedeelde verwondering als krachtige verbindingservaring.',
    bron: 'Stern, D. (1985). The Interpersonal World of the Infant.',
  },
  {
    id: 'verb_02_19',
    title: 'Afscheidskus ritueel',
    skill: 'Verbinding',
    description: 'Maak van elk afscheid (naar werk, naar bed) een bewust klein ritueel: dezelfde kus, hetzelfde woord, hetzelfde gebaar. Consequent herhalen.',
    duration: '2 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Voorspelbare afscheidsrituelen helpen baby\'s de afwezigheid te begrijpen en te tolereren. Ze communiceren: "Ik ga weg, maar ik kom terug." Dat is hechtingszekerheid.',
    skillTip: 'Houd het kort maar consequent. Hetzelfde elke dag. Variatie werkt averechts bij baby\'s.',
    vermijd: 'Vermijd stiekem wegglippen. Ook al voelt het makkelijker – het beschadigt het vertrouwen.',
    leerdoel: 'Je bouwt een afscheidsritueel dat veiligheid bij scheiding vergroot.',
    bron: 'Bowlby, J. (1988). A Secure Base.',
  },
  {
    id: 'verb_02_20',
    title: 'Vader-baby foto-ritueel',
    skill: 'Verbinding',
    description: 'Neem elke week dezelfde foto: jij en je baby in dezelfde pose of op dezelfde plek. Over een jaar heb je 52 beelden van jullie verbinding die groeide.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Visuele documentatie van groei versterkt het narratief van de relatie. Een wekelijkse reeks maakt de verbinding voelbaar in de tijd – zowel voor vader als later voor het kind.',
    skillTip: 'Laat iemand anders de foto nemen. Jij bent erin, niet achter de camera. Dat is de verbinding.',
    vermijd: 'Vermijd het zo perfect willen maken dat je het uitstelt. Een gewone foto elke week is beter dan een perfecte foto nooit.',
    leerdoel: 'Je creëert een visueel tijdsdocument van jullie groeiende verbinding.',
    bron: 'McAdams, D.P. (2001). The psychology of life stories.',
  },

  // ─── 3-5 jaar ────────────────────────────────────────────────
  {
    id: 'verb_35_11',
    title: 'Zijn droomwereld betreden',
    skill: 'Verbinding',
    description: 'Vraag je kind: "Vertel me over je droomwereld. Als jij een koninkrijk kon hebben, hoe zag dat er dan uit?" Luister volledig en stel vragen die zijn fantasie vergroten.',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Fantasiewerelden zijn ramen naar het innerlijk leven van het kind. Vader die serieus luistert en mee bouwt, verbindt zich met zijn diepste creatieve en emotionele leven.',
    skillTip: 'Vraag: "En wie woont er dan? En wat doen ze?" – bouw zijn wereld uit via vragen.',
    vermijd: 'Vermijd corrigeren of relativeren van zijn fantasie. Dit is zijn wereld – alles is mogelijk.',
    leerdoel: 'Je verbindt je met zijn innerlijk leven via gedeelde fantasie.',
    bron: 'Singer, J.L. & Singer, D.G. (1990). The House of Make-Believe.',
  },
  {
    id: 'verb_35_12',
    title: 'Traditie starten: vader-kind dag',
    skill: 'Verbinding',
    description: 'Spreek één vaste dag per maand af als "vader-kind dag": een halve of hele dag alleen met hem, zijn keuze voor activiteiten. Maak het een terugkerende traditie.',
    duration: '60 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Terugkerende speciale momenten bouwen een uniek identiteitsverhaal voor het kind: "Mijn vader en ik hebben een speciale dag." Dit versterkt de verbinding over tijd.',
    skillTip: 'Zet het vast in de agenda. Consistentie is de magie van tradities.',
    vermijd: 'Vermijd afzeggen tenzij het werkelijk onvermijdelijk is. De verwachting is deel van de verbinding.',
    leerdoel: 'Je bouwt een terugkerende vader-kind traditie als structurele verbindingsinvestering.',
    bron: 'Imber-Black, E. & Roberts, J. (1992). Rituals for Our Times.',
  },
  {
    id: 'verb_35_13',
    title: 'Zijn favoriete eten samen koken',
    skill: 'Verbinding',
    description: 'Maak zijn absolute favoriet gerecht samen. Laat hem zo veel mogelijk zelf doen. Geniet daarna samen van het resultaat.',
    duration: '30 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Samen koken combineert motorische participatie, smaaksensaties, trots en gedeeld plezier. Dit is een rijke verbindingservaring die meerdere zintuigen tegelijk aanspreekt.',
    skillTip: 'Laat hem de "chef" zijn. Jij bent de sous-chef die doet wat hij zegt. Dat geeft hem regie.',
    vermijd: 'Vermijd het perfectionistisch aanpakken. Zijn chaos is deel van zijn creativiteit.',
    leerdoel: 'Je ervaart koken als rijke multisensorische verbindingsactiviteit.',
    bron: 'Brown, S. (2009). Play: How it Shapes the Brain.',
  },
  {
    id: 'verb_35_14',
    title: 'Ontdektocht in de buurt',
    skill: 'Verbinding',
    description: 'Ga op ontdektocht in de buurt: zoek samen vijf dingen die jullie nog nooit eerder hadden opgemerkt. Markeer ze op een zelf gemaakte kaart.',
    duration: '30 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Gedeelde ontdekking vergroot de gedeelde aandacht en de verwondering. Het creëert ook een gezamenlijk narratief: "Wij ontdekten dit samen." Verbinding via avontuur.',
    skillTip: 'Laat hem de kaart tekenen na afloop. Zijn perspectief op de ontdekking is de rijkste versie.',
    vermijd: 'Vermijd een vaste route of bestemming. Het ontdekken is het doel, niet de aankomst.',
    leerdoel: 'Je ervaart gedeelde ontdekking als verbindingsmotor via gedeelde verwondering.',
    bron: 'Wilson, E.O. (1984). Biophilia: The Human Bond with Other Species.',
  },
  {
    id: 'verb_35_15',
    title: 'Zijn tekening begrijpen',
    skill: 'Verbinding',
    description: 'Bekijk een tekening van je kind aandachtig. Vraag: "Vertel eens over jouw tekening." Luister volledig. Stel vragen over details. Toon echte interesse in zijn wereld.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Tekeningen van kinderen zijn vensters op hun innerlijk leven. Vader die vraagt en luistert, verdiept de verbinding door zijn creatieve en emotionele wereld serieus te nemen.',
    skillTip: 'Zeg nooit "wat is dit?" – dat klinkt als het niet herkennen. Zeg "vertel me over dit deel." Dat opent.',
    vermijd: 'Vermijd zelf invullen wat het is. "Ah, een hond!" kan zijn "dat is opa." Vraag altijd eerst.',
    leerdoel: 'Je verdiept de verbinding door zijn creatieve expressie serieus te bevragen.',
    bron: 'Malchiodi, C.A. (1998). Understanding Children\'s Drawings.',
  },
  {
    id: 'verb_35_16',
    title: 'Nacht-wandeling',
    skill: 'Verbinding',
    description: 'Ga eens in de avondschemering of \'s avonds vroeg buiten wandelen. Kijk samen naar de sterren, de maan, het donkere bos. Deel het mysterie van de nacht.',
    duration: '20 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Ongewone ervaringen (nacht, donker, sterren) creëren een speciale verbindingskwaliteit. De lichte spanning en de gedeelde verwondering verdiepen de herinneringswaarde.',
    skillTip: 'Houd hem aan de hand of draag hem. Veiligheid en gedeeld avontuur versterken verbinding tegelijk.',
    vermijd: 'Vermijd zijn eventuele angst voor het donker wegwuiven. Erken: "Dat is een beetje spannend, hè? Ik ben bij je."',
    leerdoel: 'Je ervaart hoe gedeelde lichte spanning verbinding verdiept via gedeeld avontuur.',
    bron: 'Brown, S. (2009). Play: How it Shapes the Brain.',
  },
  {
    id: 'verb_35_17',
    title: 'Geheime taal maken',
    skill: 'Verbinding',
    description: 'Verzin samen een geheime taal of code: een paar woorden die alleen jullie begrijpen. Gebruik ze de komende week in gewone situaties.',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Een gedeelde geheime taal creëert een exclusief "wij" gevoel. Dat is een krachtige verbindingservaring die het kind doet voelen dat hij een speciale relatie met vader heeft.',
    skillTip: 'Maak het simpel. Drie tot vijf woorden zijn al genoeg voor een "geheime code".',
    vermijd: 'Vermijd het te complex maken. Eenvoud maakt het makkelijker te gebruiken.',
    leerdoel: 'Je creëert een exclusieve verbindingscode die jullie speciale "wij" markeert.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'verb_35_18',
    title: 'Zijn angst samen onder ogen zien',
    skill: 'Verbinding',
    description: 'Als je kind ergens bang voor is (het donker, een dier, een geluid): ga samen kijken of luisteren. Benoem zijn angst. Blijf naast hem. Laat hem weten dat vader er is.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Samen ogen zien voor een angst met vader naast je is een krachtige verbindingservaring. Het kind leert: angst is dragelijker met jou erbij. Dit versterkt veilige hechting.',
    skillTip: 'Ga samen stap voor stap. Dwing niets – maar blijf wel naast hem in zijn grensgebied.',
    vermijd: 'Vermijd "er is niets om bang voor te zijn." Zijn angst is reëel. Erken het en ga samen kijken.',
    leerdoel: 'Je ervaart hoe gezamenlijk angst trotseren de verbinding verdiept.',
    bron: 'Bowlby, J. (1988). A Secure Base.',
  },
  {
    id: 'verb_35_19',
    title: 'Gezamenlijk project afmaken',
    skill: 'Verbinding',
    description: 'Pak een eerder gestart project op (puzzel, tekening, bouwwerk) en maak het samen af. Vier het afronden samen.',
    duration: '20 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Gezamenlijk iets afronden versterkt het gevoel van gedeeld succes. Het narrative "wij maakten dit samen" is een krachtige verbindingsgeheugen.',
    skillTip: 'Laat hem de laatste stap doen of de "opening" verrichten. Hij is de voltooier – dat vergroot zijn trots.',
    vermijd: 'Vermijd het project overnemen als het traag gaat. Geduld is de verbindingsvaardigheid hier.',
    leerdoel: 'Je ervaart gedeeld succes als verbindingskracht via gezamenlijke afrondingservaring.',
    bron: 'Csikszentmihalyi, M. (1990). Flow.',
  },
  {
    id: 'verb_35_20',
    title: 'Kijk wat hij kan!',
    skill: 'Verbinding',
    description: 'Vraag je kind je iets te laten zien wat hij kan: een trucje, een beweging, een geluid. Kijk echt. Reageer met echte verrassing of bewondering. Vraag hem het nog eens te laten zien.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Bewonderd worden door vader is voor peuters en kleuters een van de krachtigste verbindingservaringen. Het bevestigt competentie én geeft een gevoel van gezien worden.',
    skillTip: 'Vraag: "Kan je dat nog een keer?" Herhaling toont dat zijn prestatie echt interessant is voor jou.',
    vermijd: 'Vermijd flauw of beleefd reageren. Echt enthousiasme is voelbaar en niet te faken.',
    leerdoel: 'Je ervaart bewondering geven als directe verbindingsvorm via erkenning van zijn competentie.',
    bron: 'White, R.W. (1959). Motivation reconsidered: The concept of competence.',
  },

  // ─── 6-9 jaar ────────────────────────────────────────────────
  {
    id: 'verb_69_11',
    title: 'Zijn wereld bezoeken op school',
    skill: 'Verbinding',
    description: 'Ga een keer naar school: haal hem op en vraag hem de school te laten zien. Zijn klas, zijn bureau, zijn lievelingsplek. Interesse in zijn dagelijkse wereld.',
    duration: '30 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Aanwezig zijn in zijn dagelijkse wereld vergroot de begrijping van zijn ervaringen en toont dat vader echt geïnteresseerd is in waar hij de meeste tijd doorbrengt.',
    skillTip: 'Stel concrete vragen: "Waar zit jij? Wie zit naast je? Wat doe je het liefst hier?" Zijn wereld leren kennen.',
    vermijd: 'Vermijd dit als controle of beoordeling. Het is nieuwsgierigheid en interesse in zijn leven.',
    leerdoel: 'Je vergroot je kennis van zijn dagelijkse wereld als verbindingsbasis.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'verb_69_12',
    title: 'Twee-speler spel bewust kiezen',
    skill: 'Verbinding',
    description: 'Kies bewust een spel voor twee: schaken, kaarten, rummikub, een computerspel voor twee. Speel het met volle aandacht. Win en verlies met gelijkmoedigheid.',
    duration: '30 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Tweepersoonssspelen zijn gestructureerde verbindingsruimtes. Ze creëren een gedeeld ritme van focus, humor en wedstrijd – verbinding via spelinteractie.',
    skillTip: 'Laat hem soms winnen, maar laat ook zien hoe je verliest. Dat is ook een les die verbinding vraagt.',
    vermijd: 'Vermijd altijd laten winnen. Eerlijk spelen is respectvoller dan altijd toegeven.',
    leerdoel: 'Je ervaart spelen als gestructureerde verbindingsvorm via gedeeld ritme en focus.',
    bron: 'Brown, S. (2009). Play: How it Shapes the Brain.',
  },
  {
    id: 'verb_69_13',
    title: 'Zijn held leren kennen',
    skill: 'Verbinding',
    description: 'Vraag je kind wie zijn held is: een sporter, personage, youtuber, of iemand in zijn leven. Vraag waarom. Leer die held een beetje kennen samen met hem.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Helden zijn identiteitsmodellen. Wie iemand bewondert, vertelt je iets over zijn waarden en wie hij wil zijn. Interesse in zijn held is interesse in zijn identiteit.',
    skillTip: 'Vraag: "Wat maakt hem voor jou een held?" – dat gaat naar de waarden achter de bewondering.',
    vermijd: 'Vermijd zijn heldenkeuze beoordelen of minimaliseren. Zijn held is zijn keuze.',
    leerdoel: 'Je verdiept de verbinding door interesse te tonen in zijn identiteitsmodellen.',
    bron: 'Marcia, J.E. (1966). Development and validation of ego-identity status.',
  },
  {
    id: 'verb_69_14',
    title: 'Zijn schooldag reconstrueren',
    skill: 'Verbinding',
    description: 'Vraag je kind zijn schooldag van uur tot uur te reconstrueren. Stel vragen bij elk onderdeel. Wees oprecht geïnteresseerd in de details van zijn dag.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Gedetailleerde aandacht voor zijn dag communiceert: "Jouw dagelijkse leven is interessant en waardevol voor mij." Dit verdiept de verbinding via oprechte nieuwsgierigheid.',
    skillTip: 'Vraag naar een specifiek moment: "Wat was het meest verrassende moment vandaag?" – dat geeft een ingang.',
    vermijd: 'Vermijd het samenvatten door hem. Laat hem het vertellen. Jij luistert.',
    leerdoel: 'Je vergroot de verbinding via gedetailleerde nieuwsgierigheid naar zijn dagelijks leven.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'verb_69_15',
    title: 'Gezamenlijk ritme in sport',
    skill: 'Verbinding',
    description: 'Doe samen een lichamelijke activiteit met ritme: rennen, fietsen, zwemmen, basketbal. Synchroniseer je beweging. Luister naar elkaars tempo.',
    duration: '30 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Bewegingssynchronisatie vergroot de interpersoonlijke verbinding. Samen bewegen synchroniseert het zenuwstelsel en verhoogt wederzijdse sympathie en verbondenheid.',
    skillTip: 'Pas je tempo aan naar zijn tempo, niet andersom. Dat communiceert: jij bent het maatstaf.',
    vermijd: 'Vermijd competitie als primair doel. Samen bewegen is het doel, niet wie wint.',
    leerdoel: 'Je ervaart bewegingssynchronisatie als directe verbindingsvorm.',
    bron: 'Feldman, R. (2007). Parent-infant synchrony and the construction of shared timing.',
  },
  {
    id: 'verb_69_16',
    title: 'Hem voorstellen aan jouw wereld',
    skill: 'Verbinding',
    description: 'Neem je kind mee naar een plek die voor jou betekenisvol is: je werkplek, een plek uit je jeugd, een favoriete plek. Deel waarom het bijzonder is voor jou.',
    duration: '30 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Jouw wereld met hem delen verdiept de verbinding via zelfonthulling. Het kind leert: vader heeft ook een wereld, een verleden, een verhaal. Dat vergroot de empathie en de band.',
    skillTip: 'Vertel een persoonlijk verhaal over de plek. Dat maakt het echt en menselijk.',
    vermijd: 'Vermijd de plek alleen tonen – vertel ook wat die plek voor jou betekent.',
    leerdoel: 'Je verdiept de verbinding via zelfonthulling van jouw persoonlijke wereld.',
    bron: 'Brown, B. (2012). Daring Greatly.',
  },
  {
    id: 'verb_69_17',
    title: 'Grappig moment vastleggen',
    skill: 'Verbinding',
    description: 'Schrijf vandaag een grappig of bijzonder moment met je kind op. Lees het hem voor. Bewaar het. Bouw een verzameling van jullie grappige herinneringen.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Gedeelde humor en positieve herinneringen zijn de "emotionele bank" van relaties. Bewust investeren via vastleggen vergroot de saldo aan positieve verbinding.',
    skillTip: 'Bewaar ze in een schrift of map. Over een jaar lees je ze samen en lacht je opnieuw.',
    vermijd: 'Vermijd alleen grote of bijzondere momenten vastleggen. Kleine grappige dagmomenten zijn ook goud.',
    leerdoel: 'Je bouwt bewust een gedeelde bank van positieve herinneringen en humor.',
    bron: 'Gottman, J. (1999). The Marriage Clinic.',
  },
  {
    id: 'verb_69_18',
    title: 'Samen nadenken over een groot vraagstuk',
    skill: 'Verbinding',
    description: 'Stel je kind een grote vraag: "Waarom is de hemel blauw? Waarom zijn er mensen? Waarom dromen we?" Denk samen hardop. Er hoeft geen antwoord te zijn.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Samen denken over grote vragen bouwt intellectuele intimiteit en geeft het kind het gevoel dat zijn denken serieus genomen wordt. Verbinding via gedeeld nadenken.',
    skillTip: 'Zeg "ik weet het ook niet" als dat waar is. Niet-weten samen is rijker dan een kant-en-klaar antwoord.',
    vermijd: 'Vermijd Wikipedia. Laat het gesprek gaan voor je informatie opzoekt.',
    leerdoel: 'Je ervaart intellectuele intimiteit als verbindingsvorm via gedeeld nadenken.',
    bron: 'Csikszentmihalyi, M. (1990). Flow.',
  },
  {
    id: 'verb_69_19',
    title: 'Zijn verdriet delen',
    skill: 'Verbinding',
    description: 'Als je kind iets deelt wat hem verdrietig maakt: ga naast hem zitten. Zeg niets. Leg eventueel je hand op zijn schouder. Wees er. Dan pas vragen.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Stil aanwezig zijn bij verdriet is de meest krachtige verbindingsvorm. Het communiceert: "Jouw verdriet is draagbaar met mij erbij." Dat is de definitie van veilige verbinding.',
    skillTip: 'Vraag pas na twee minuten: "Wil je praten?" Stilte is ook verbinding.',
    vermijd: 'Vermijd meteen het probleem willen oplossen. Aanwezigheid is de troost – niet de oplossing.',
    leerdoel: 'Je ervaart stille aanwezigheid bij verdriet als de diepste verbindingsvorm.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2011). The Whole-Brain Child.',
  },
  {
    id: 'verb_69_20',
    title: 'Iets nieuws samen proberen',
    skill: 'Verbinding',
    description: 'Doe samen iets wat jullie allebei nog nooit hebben gedaan: een nieuw gerecht proeven, een instrument aanraken, een sport proberen. Wees allebei beginner.',
    duration: '30 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Gedeelde noviteitservaringen versterken verbinding omdat beide personen kwetsbaar zijn als beginner. De gedeelde onzekerheid schept gelijkwaardigheid en verbondenheid.',
    skillTip: 'Lach om jouw eigen onhandige pogingen. Dat normaliseert falen en maakt het veiliger voor hem.',
    vermijd: 'Vermijd een activiteit kiezen waarbij jij duidelijk beter bent. Echte gelijkheid is het doel.',
    leerdoel: 'Je ervaart gedeelde kwetsbaarheid als beginner als verbindingsvorm via noviteit.',
    bron: 'Brown, B. (2012). Daring Greatly.',
  },

  // ─── 10-12 jaar ──────────────────────────────────────────────
  {
    id: 'verb_1012_11',
    title: 'Zijn digitale wereld begrijpen',
    skill: 'Verbinding',
    description: 'Vraag je kind je zijn favoriete online game of app te laten zien en uit te leggen. Luister en stel echte vragen. Laat hem de expert zijn.',
    duration: '20 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Digitale werelden zijn sociale werelden voor kinderen van 10-12. Vader die interesse toont in zijn online leven, verbindt zich met een groot deel van zijn dagelijkse wereld.',
    skillTip: 'Stel vragen als een echte leerling: "Waarom doe je dat zo? Wat is jouw strategie?" Echte nieuwsgierigheid opent deuren.',
    vermijd: 'Vermijd commentaar op hoeveel tijd hij eraan besteedt. Dit is verbindingstijd, geen discussiemoment.',
    leerdoel: 'Je vergroot de verbinding door zijn digitale wereld serieus te betreden.',
    bron: 'Prensky, M. (2001). Digital Natives, Digital Immigrants.',
  },
  {
    id: 'verb_1012_12',
    title: 'Zonder scherm een avond',
    skill: 'Verbinding',
    description: 'Sluit alle schermen een avond af en doe iets samen: bordspel, kaarten, praten, tekenen. Geen structuur nodig – gewoon samen zijn zonder scherm.',
    duration: '90 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Schermvrije tijd creëert ruimte voor spontane verbinding. Gesprekken en activiteiten die ontstaan zonder scherm zijn rijker en intenser dan die naast schermgebruik.',
    skillTip: 'Kondig het aan als experiment, niet als straf: "Laten we eens kijken hoe dat voelt." Dat verlaagt de weerstand.',
    vermijd: 'Vermijd het als preek inleiden. Geen uitleg waarom schermen slecht zijn – gewoon iets doen samen.',
    leerdoel: 'Je ervaart hoe schermvrije tijd de kwaliteit van spontane verbinding vergroot.',
    bron: 'Turkle, S. (2015). Reclaiming Conversation.',
  },
  {
    id: 'verb_1012_13',
    title: 'Zijn sportmoment bewust bijwonen',
    skill: 'Verbinding',
    description: 'Woon een wedstrijd of training bij waar hij aan meedoet. Stap volledig weg van je telefoon. Kijk volledig. Praat daarna over wat je zag.',
    duration: '60 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Aanwezig zijn bij zijn activiteiten heeft een disproportioneel groot effect op zijn gevoel van gesteund worden. Zijn ogen zoeken jou. Jouw aanwezigheid is het geschenk.',
    skillTip: 'Noem na afloop één specifiek moment dat je zag. "Ik zag hoe je [concreet moment]." Dat toont echte aandacht.',
    vermijd: 'Vermijd coaching-commentaar ("had je niet beter..."). Dit is steunen, geen bijsturen.',
    leerdoel: 'Je ervaart hoe bewuste aanwezigheid bij zijn activiteiten verbinding schept zonder woorden.',
    bron: 'Bandura, A. (1977). Self-efficacy.',
  },
  {
    id: 'verb_1012_14',
    title: 'Diepgaandere vraag stellen',
    skill: 'Verbinding',
    description: 'Stel je kind een vraag die verder gaat dan oppervlakte: "Wat is iets wat jij gelooft dat de meeste mensen niet begrijpen?" Luister volledig. Vraag door.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Diepgaande vragen activeren intellectuele en emotionele intimiteit. Ze communiceren: "Ik wil je echt kennen, niet alleen de oppervlakte." Dit verdiept de verbinding significant.',
    skillTip: 'Bewaar een lijstje van diepe vragen. Gebruik er één per week. Zo bouw je geleidelijk een diepere verbinding.',
    vermijd: 'Vermijd het gesprek overnemen. Stel de vraag en luister dan. Jouw antwoord kan daarna.',
    leerdoel: 'Je vergroot de verbinding via diepgaande vragen als alternatief voor oppervlakkige gesprekken.',
    bron: 'Aron, A. et al. (1997). The experimental generation of interpersonal closeness.',
  },
  {
    id: 'verb_1012_15',
    title: 'Zijn online vrienden serieus nemen',
    skill: 'Verbinding',
    description: 'Vraag je kind over zijn online vrienden: wie zijn ze? Hoe kennen jullie elkaar? Wat doen jullie samen? Luister serieus – online vriendschappen zijn ook echte vriendschappen.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Online vriendschappen zijn voor kinderen van 10-12 even reëel als offline vriendschappen. Ze bagatelliseren vergroot de kloof tussen zijn wereld en die van vader.',
    skillTip: 'Stel vragen als: "Wat vind je leuk aan hem/haar? Wat doen jullie samen?" – dan leer je zijn sociale wereld kennen.',
    vermijd: 'Vermijd "dat zijn geen echte vrienden." Dat sluit een deur die moeilijk te heropenen is.',
    leerdoel: 'Je vergroot de verbinding door zijn online sociale wereld serieus te nemen.',
    bron: 'Subrahmanyam, K. & Smahel, D. (2011). Digital Youth: The Role of Media in Development.',
  },
  {
    id: 'verb_1012_16',
    title: 'Zijn gevoel bij een familie-issue',
    skill: 'Verbinding',
    description: 'Als er iets speelt in de familie (scheiding, ziekte, stress): vraag je kind hoe hij dat beleeft. Luister volledig. Erken zijn gevoel. Leg niet uit – erken alleen.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Kinderen die bij familie-issues worden betrokken en hun gevoel mogen hebben, herstellen beter dan kinderen die buiten gehouden worden. Verbinding via eerlijkheid en erkenning.',
    skillTip: 'Vraag: "Hoe voel jij je daarbij?" en laat alles wat hij zegt welkom zijn, ook als het moeilijk te horen is.',
    vermijd: 'Vermijd details delen die te belastend zijn voor zijn leeftijd. Zijn gevoel erkennen hoeft niet alles vertellen.',
    leerdoel: 'Je vergroot de verbinding door zijn beleving van gezinsgebeurtenissen serieus te nemen.',
    bron: 'Siegel, D.J. & Hartzell, M. (2003). Parenting from the Inside Out.',
  },
  {
    id: 'verb_1012_17',
    title: 'Samen vrijwilligerswerk doen',
    skill: 'Verbinding',
    description: 'Doe samen één keer iets voor anderen: soep uitdelen, boodschappen doen voor een buurman, iets organiseren voor school. Verbinding via gedeeld bijdragen.',
    duration: '60 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Samen bijdragen aan iets groters vergroot de verbondenheid via gedeeld doel en gedeeld altruïsme. Het creëert ook een gedeelde identiteit als "wij die helpen".',
    skillTip: 'Kies iets wat hij zelf koos of voorstelde. Zijn intrinsieke motivatie maakt het rijker.',
    vermijd: 'Vermijd het opdragen. Dit werkt alleen als het vrijwillig en gezamenlijk is.',
    leerdoel: 'Je ervaart verbinding via gedeeld doel en altruïsme als gezamenlijke activiteit.',
    bron: 'Post, S.G. (2005). Altruism, Happiness, and Health: It\'s Good to Be Good.',
  },
  {
    id: 'verb_1012_18',
    title: 'Zijn dromen voor de vakantie',
    skill: 'Verbinding',
    description: 'Vraag je kind: "Als jij de komende vakantie mocht bepalen – wat zou je dan willen?" Luister volledig. Maak er vervolgens één element van werkelijkheid.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Dromen serieus nemen en er iets van realiseren vergroot het gevoel van gewaardeerd worden. Het kind leert: vader luistert en handelt naar wat ik zeg.',
    skillTip: 'Kies één haalbaar element en maak dat echt. Dat is meer waard dan de grote droom die nooit uitkomt.',
    vermijd: 'Vermijd groot beloven en klein leveren. Beter een klein echt dan een groot onecht.',
    leerdoel: 'Je vergroot de verbinding door zijn dromen te erkennen en een deel er van te realiseren.',
    bron: 'Gottman, J. (1999). The Marriage Clinic.',
  },
  {
    id: 'verb_1012_19',
    title: 'Gezinsgeschiedenis vertellen',
    skill: 'Verbinding',
    description: 'Vertel je kind iets over de familie-geschiedenis: opa, oma, bijzondere momenten, moeilijke tijden. Maak hem deel van een groter verhaal dan alleen zijn eigen.',
    duration: '20 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kinderen die weten waar ze vandaan komen, hebben een sterkere identiteitsbasis. Familiegeschiedenis vertellen vergroot het gevoel van continuïteit en verbondenheid.',
    skillTip: 'Toon oude foto\'s als die er zijn. Dat maakt het concreter en tastbaarder.',
    vermijd: 'Vermijd alleen successen vertellen. Moeilijkheden en hoe die overwonnen werden zijn het meest verbindend.',
    leerdoel: 'Je vergroot zijn verbondenheid met de familiegeschiedenis als identiteitsfundament.',
    bron: 'McAdams, D.P. (2001). The psychology of life stories.',
  },
  {
    id: 'verb_1012_20',
    title: 'Zeg wat je in hem ziet',
    skill: 'Verbinding',
    description: 'Zeg je kind specifiek wat je in hem ziet als persoon: zijn karakter, zijn kwaliteiten, zijn unieke manier van zijn. Niet als compliment – als eerlijke observatie.',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Gezien worden door vader – specifiek en persoonlijk – is een van de meest krachtige verbindingservaringen voor kinderen. Het bouwt een stabiel zelfgevoel op.',
    skillTip: 'Gebruik "ik zie..." als opener: "Ik zie hoe jij..." – dan is het observatie, geen beoordeling.',
    vermijd: 'Vermijd generieke complimenten. Specifiek en persoonlijk is duizend keer waardevoller.',
    leerdoel: 'Je vergroot de verbinding via het specifiek benoemen van wie je kind is als persoon.',
    bron: 'Brown, B. (2010). The Gifts of Imperfection.',
  },

  // ─── 13-16 jaar ──────────────────────────────────────────────
  {
    id: 'verb_1316_11',
    title: 'Zijn muziek echt proberen te begrijpen',
    skill: 'Verbinding',
    description: 'Vraag je tiener je zijn favoriete artiest te laten horen. Luister echt. Vraag: "Wat spreekt je aan in deze muziek?" Leer zijn smaak kennen zonder oordeel.',
    duration: '20 min',
    ageGroups: ['13-16'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Muzikale smaak is een primaire identiteitsuitdrukking bij tieners. Vader die zijn muziek serieus neemt, neemt zijn identiteit serieus. Dat vergroot de verbinding sterk.',
    skillTip: 'Vraag naar de tekst: "Wat zegt hij hier?" – dat gaat naar wat hem raakt.',
    vermijd: 'Vermijd "is dit muziek?" of nonverbale afkeuring. Elke afwijzing sluit een deur.',
    leerdoel: 'Je vergroot de verbinding door zijn muzikale identiteitsuitdrukking serieus te nemen.',
    bron: 'Arnett, J.J. (1995). Adolescents\' uses of media for self-socialization.',
  },
  {
    id: 'verb_1316_12',
    title: 'Samen een serieuze afspraak plannen',
    skill: 'Verbinding',
    description: 'Plan bewust een activiteit met je tiener die hij zelf kiest. Zet het in de agenda, hou je er aan. Behandel het als een serieuze afspraak – want dat is het.',
    duration: '120 min',
    ageGroups: ['13-16'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Geplannd tijd voor tieners communiceert dat ze een prioriteit zijn, niet een tussendoortje. Tieners die vader zien als actief investeerder, zijn meer bereid om te verbinden.',
    skillTip: 'Laat hem de activiteit volledig bepalen. Geen suggesties – zijn keuze, zijn dag.',
    vermijd: 'Vermijd afzeggen tenzij absoluut onvermijdelijk. En als het toch moet: herplannen dezelfde week.',
    leerdoel: 'Je maakt verbinding met je tiener een gepland, serieus gezinsinvestering.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'verb_1316_13',
    title: 'Luisteren zonder oplossingen',
    skill: 'Verbinding',
    description: 'Als je tiener een probleem deelt: vraag eerst: "Wil je dat ik luister of wil je advies?" Volg zijn antwoord. Als hij luisteren wil: alleen luisteren. Niets meer.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Tieners stoppen met delen als ze advies krijgen dat ze niet vroegen. De simpele vraag "wil je luisteren of advies?" vergroot de bereidheid om te praten significant.',
    skillTip: 'Als hij zegt "luisteren": houd je er echt aan. Geen "maar heb je ook aan... gedacht?" Na afloop.',
    vermijd: 'Vermijd advies sluipen in "luistermodus". Vragen stellen kan ook sturing zijn.',
    leerdoel: 'Je leert de kracht van zuiver luisteren als verbindingsvorm bij tieners.',
    bron: 'Gordon, T. (1970). Parent Effectiveness Training.',
  },
  {
    id: 'verb_1316_14',
    title: 'Zijn passie echt leren kennen',
    skill: 'Verbinding',
    description: 'Vraag je tiener zijn grootste passie uit te leggen alsof jij er niets van weet. Luister een half uur. Stel echte vragen. Leer zijn wereld echt kennen.',
    duration: '30 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Passies zijn de kern van de identiteitsontwikkeling bij tieners. Vader die zijn passie serieus bestudeert, neemt zijn identiteit serieus. Dat is een krachtige verbindingservaring.',
    skillTip: 'Vraag aan het einde: "Wat wil jij later met deze passie?" – dat verbindt zijn huidige interesse met zijn toekomst.',
    vermijd: 'Vermijd de passie beoordelen op haalbaarheid. Dit is kennen, niet beoordelen.',
    leerdoel: 'Je vergroot de verbinding via diepgaande interesse in zijn kernidentiteit.',
    bron: 'Marcia, J.E. (1966). Development and validation of ego-identity status.',
  },
  {
    id: 'verb_1316_15',
    title: 'Erkennen dat het moeilijk is',
    skill: 'Verbinding',
    description: 'Zeg eens zonder verdere agenda: "Ik zie dat het op dit moment niet makkelijk voor je is. Dat begrijp ik." Niets meer. Laat die erkenning landen.',
    duration: '5 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Onvoorwaardelijke erkenning – zonder advies of oplossing – is een van de meest krachtige verbindingsgebaren voor tieners. Ze voelen zich gezien zonder te worden beoordeeld.',
    skillTip: 'Timing is alles. Kies een moment waarop hij niet in het midden van iets anders zit.',
    vermijd: 'Vermijd er iets achter plakken: "...maar je kunt er wel iets aan doen." Laat het zuiver.',
    leerdoel: 'Je ervaart hoe onvoorwaardelijke erkenning de sterkste verbinding biedt.',
    bron: 'Rogers, C.R. (1961). On Becoming a Person.',
  },
  {
    id: 'verb_1316_16',
    title: 'Zijn politieke bewustwording steunen',
    skill: 'Verbinding',
    description: 'Als je tiener maatschappelijk bewust wordt (klimaat, racisme, rechten): steun zijn betrokkenheid, ook als zijn standpunten sterker of anders zijn dan de jouwe.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Maatschappelijke betrokkenheid is een gezonde identiteitsontwikkeling bij tieners. Vader die dit steunt, verbindt zich met zijn groeiende morele en sociale bewustzijn.',
    skillTip: 'Vraag: "Hoe denk jij dat dit verbeterd kan worden?" – dat gaat naar zijn agentschap, niet alleen zijn opinie.',
    vermijd: 'Vermijd zijn standpunten relativeren als naïef. Neem ze serieus als de zijne.',
    leerdoel: 'Je vergroot de verbinding via steun voor zijn maatschappelijke identiteitsontwikkeling.',
    bron: 'Kohlberg, L. (1969). Stage and sequence.',
  },
  {
    id: 'verb_1316_17',
    title: 'Samen kwetsbaar zijn',
    skill: 'Verbinding',
    description: 'Deel iets met je tiener wat jou moeilijk valt: een angst, een onzekerheid, iets waar je mee worstelt. Echt en authentiek. Geen performance.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Kwetsbaarheid van vader doorbreekt de hiërarchie en opent een dieper verbindingsniveau. Tieners die vader als kwetsbaar mens zien, verbinden zich dieper dan met een onneembare autoriteit.',
    skillTip: 'Kies iets wat echt is maar niet overweldigend. Een echte worstelingen – geen crisis.',
    vermijd: 'Vermijd kwetsbaarheid als instrument gebruiken om empathie of iets anders te vragen. Deel, en laat het zijn.',
    leerdoel: 'Je ervaart kwetsbaarheid als diepste verbindingsvorm bij tieners.',
    bron: 'Brown, B. (2012). Daring Greatly.',
  },
  {
    id: 'verb_1316_18',
    title: 'Zijn toekomstige relaties bespreken',
    skill: 'Verbinding',
    description: 'Bespreek met je tiener hoe een goede relatie eruitziet voor hem. Niet romantisch/seksueel per se – maar: wat wil hij in vriendschappen, liefde, connecties?',
    duration: '20 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Toekomstige relatiewaarden bespreken helpt tieners een gezond relatiemodel te vormen. Vader die dat gesprek opent, beïnvloedt hoe zijn kind relaties gaat voeren.',
    skillTip: 'Deel ook jouw eigen relatiewaarden. Dat maakt het gesprek tweerichtingsverkeer.',
    vermijd: 'Vermijd het gesprek sturen naar jouw eigen verwachtingen voor hem. Het gaat om zijn visie.',
    leerdoel: 'Je vergroot de verbinding via open gesprek over relatiewaarden als gezamenlijke verkenning.',
    bron: 'Gottman, J. (1999). The Marriage Clinic.',
  },
  {
    id: 'verb_1316_19',
    title: 'Hem bedanken voor iets',
    skill: 'Verbinding',
    description: 'Bedank je tiener oprecht voor iets wat hij voor jou of het gezin deed. Specifiek en persoonlijk. "Dank je dat je... – dat betekende voor mij..."',
    duration: '5 min',
    ageGroups: ['13-16'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Dankbaarheid uiten van vader naar kind keert de verwachte richting om. Het communiceert gelijkwaardigheid en bevestigt zijn bijdrage als betekenisvol en gewaardeerd.',
    skillTip: 'Gebruik de formule: "Dank je voor [specifiek]. Het deed voor mij [impact]." Twee lagen maakt het echt.',
    vermijd: 'Vermijd algemeen "bedankt voor alles." Specifiek is veel waardevoller.',
    leerdoel: 'Je ervaart wederzijdse dankbaarheid als verbindingsvorm die gelijkwaardigheid toont.',
    bron: 'Emmons, R.A. & McCullough, M.E. (2003). Counting blessings versus burdens.',
  },
  {
    id: 'verb_1316_20',
    title: 'Brief die hij bewaart',
    skill: 'Verbinding',
    description: 'Schrijf je tiener een brief over wat jij ziet in hem, wat jij voor hem hoopt en wat jij van hem houdt. Geef hem die. Zeg: "Dit is van mij voor jou."',
    duration: '20 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Een handgeschreven brief van vader is een tastbaar, blijvend bewijs van verbinding. Tieners bewaren zulke brieven jaren en lezen ze opnieuw in moeilijke momenten.',
    skillTip: 'Schrijf met de hand. Dat voelt anders dan getypt. De imperfecties zijn het bewijs dat jij het schreef.',
    vermijd: 'Vermijd verwachtingen of verzoeken in de brief. Dit is liefde, geen prestatiecontract.',
    leerdoel: 'Je ervaart de kracht van een tastbaar, persoonlijk verbindingsdocument als blijvend geschenk.',
    bron: 'McAdams, D.P. (2001). The psychology of life stories.',
  },
];
