import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_23: InteractiveTask[] = [
  // ============================================================
  // AGE GROUP 0-2 (10 tasks: 3 basis, 4 gevorderd, 3 expert)
  // ============================================================
  {
    id: 'aanw_02_200',
    skill: 'Aanwezigheid',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Blote voeten in het gras',
    description: 'Laat je baby het gras voelen onder de voetjes voor zintuiglijke ontdekking.',
    instructions: [
      'Zoek een schoon stukje gras in de tuin of het park.',
      'Trek de schoentjes en sokjes van je kind uit.',
      'Zet of leg je kind voorzichtig op het gras en blijf dichtbij.',
      'Benoem wat je kind voelt: "Voel je het gras? Het kriebelt hè!"',
    ],
    reflection: 'Hoe reageerde je kind op de nieuwe textuur? Welke gezichtsuitdrukkingen zag je?',
    scienceNote: 'Zintuiglijke ervaringen in de natuur stimuleren neurale verbindingen in de vroege ontwikkeling (Fjørtoft, 2001 – Children and the natural environment).',
    durationMin: 10,
  },
  {
    id: 'emco_02_201',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Emoties bij waterplay',
    description: 'Begeleid je peuter door emoties tijdens waterspel in bad of buiten.',
    instructions: [
      'Vul een bak of babybadje met lauwwarm water en veilig speelgoed.',
      'Laat je kind vrij experimenteren met gieten, spatten en voelen.',
      'Benoem emoties die je ziet: "Wat vind je dat leuk! Je lacht zo blij!"',
      'Als je kind schrikt van spatten, benoem ook dat: "Oh, dat was een verrassing hè?"',
    ],
    reflection: 'Welke emoties zag je langskomen tijdens het waterspel? Hoe reageerde je kind op jouw woorden?',
    scienceNote: 'Emotiecoaching door ouders vergroot het emotioneel vocabulaire en de emotieregulatie van peuters (Gottman, Katz & Hooven, 1997 – Meta-Emotion).',
    durationMin: 15,
  },
  {
    id: 'zelr_02_202',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Schommelritme kalmeren',
    description: 'Gebruik ritmisch schommelen om je baby te helpen kalmeren.',
    instructions: [
      'Neem je baby op schoot of in je armen wanneer hij/zij onrustig is.',
      'Begin zachtjes heen en weer te wiegen in een rustig, voorspelbaar ritme.',
      'Neurie zachtjes een melodietje op het ritme van het wiegen.',
      'Merk op wanneer je baby rustiger wordt en pas je ritme langzaam aan.',
    ],
    reflection: 'Hoe snel reageerde je baby op het schommelritme? Voelde je zelf ook rustiger worden?',
    scienceNote: 'Ritmische vestibulair stimulatie activeert het parasympathisch zenuwstelsel en helpt bij co-regulatie (Barnard & Brazelton, 1990 – Touch: The foundation of experience).',
    durationMin: 10,
  },
  {
    id: 'verb_02_203',
    skill: 'Verbinding',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Buikje-aan-buikje tijd',
    description: 'Versterk de band door huid-op-huidcontact en buikligging samen.',
    instructions: [
      'Ga op je rug liggen op een zacht kleed of matje.',
      'Leg je baby op je buik, met het gezichtje naar jou toe.',
      'Maak oogcontact en praat zachtjes tegen je kind.',
      'Laat je kind je gezicht aanraken en exploreren terwijl je samen rust.',
    ],
    reflection: 'Hoe voelde het fysieke contact voor jou? Merkte je dat je kind ontspande?',
    scienceNote: 'Huid-op-huidcontact verhoogt oxytocineproductie bij zowel vader als kind en versterkt de hechtingsband (Feldman et al., 2010 – Skin-to-skin contact and paternal bonding).',
    durationMin: 10,
  },
  {
    id: 'gren_02_204',
    skill: 'Grenzen',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Veilig grenzen bij klimmen',
    description: 'Leer je peuter veilige grenzen kennen tijdens klimavonturen.',
    instructions: [
      'Zoek een lage, veilige klimstructuur op de speelplaats of gebruik kussens thuis.',
      'Laat je kind zelf klimmen terwijl jij dichtbij blijft als vangnet.',
      'Stel rustig een grens als het te hoog wordt: "Tot hier mag je klimmen, papa vangt je."',
      'Beloon de moed van je kind: "Wat knap dat je zo hoog durfde!"',
    ],
    reflection: 'Hoe balanceerde je tussen beschermen en ruimte geven? Accepteerde je kind de grens?',
    scienceNote: 'Fysiek uitdagend spel met duidelijke grenzen bevordert risico-inschatting en zelfvertrouwen bij peuters (Sandseter, 2009 – Risky play in early childhood education).',
    durationMin: 15,
  },
  {
    id: 'auto_02_205',
    skill: 'Autonomie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Zelf eten ontdekken',
    description: 'Laat je peuter zelfstandig voedsel verkennen met alle zintuigen.',
    instructions: [
      'Bereid een bord met gevarieerd fingerfood: zacht fruit, groente, brood.',
      'Zet je kind in de kinderstoel en plaats het bord binnen bereik.',
      'Laat je kind zelf pakken, voelen, ruiken en proeven zonder in te grijpen.',
      'Benoem wat je ziet: "Je pakt de banaan! Lekker zacht hè?"',
    ],
    reflection: 'Hoe moeilijk vond je het om niet in te grijpen bij de rommel? Wat ontdekte je kind zelf?',
    scienceNote: 'Baby-led weaning stimuleert fijne motoriek, autonomie en een gezonde relatie met voedsel (Rapley & Murkett, 2008 – Baby-Led Weaning).',
    durationMin: 15,
  },
  {
    id: 'hers_02_206',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Troostknuffel na schrik',
    description: 'Herstel de veiligheid na een schrikmoment met fysiek comfort.',
    instructions: [
      'Wanneer je kind schrikt of huilt na een val of hard geluid, ga naar hem/haar toe.',
      'Til je kind op en houd het stevig maar zacht tegen je borst.',
      'Adem bewust rustig en langzaam zodat je kind je hartslag en ademhaling voelt.',
      'Benoem wat er gebeurde: "Je schrok hè? Papa is bij je. Het is weer veilig."',
    ],
    reflection: 'Hoe snel kon je reageren? Merkte je dat jouw kalmte overdroeg op je kind?',
    scienceNote: 'Co-regulatie via fysiek contact is essentieel voor het ontwikkelen van een veilige hechtingsstijl (Bowlby, 1988 – A Secure Base).',
    durationMin: 5,
  },
  {
    id: 'refl_02_207',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Spiegelspel en lichaamsbewustzijn',
    description: 'Ontdek samen met je baby lichaamsdelen via een spiegel.',
    instructions: [
      'Ga met je baby voor een grote spiegel zitten.',
      'Wijs lichaamsdelen aan bij jezelf en bij je baby: "Dat is papa\'s neus, en dat is jouw neus!"',
      'Maak gekke gezichten en kijk hoe je baby reageert op de spiegelbeelden.',
      'Laat je baby de spiegel aanraken en zichzelf ontdekken.',
    ],
    reflection: 'Herkende je baby zichzelf of jou in de spiegel? Welke reacties vielen je op?',
    scienceNote: 'Spiegelherkenning is een mijlpaal in zelfbewustzijn die rond 18 maanden ontstaat (Amsterdam, 1972 – Mirror self-image reactions).',
    durationMin: 10,
  },
  {
    id: 'verb_02_208',
    skill: 'Verbinding',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Draagdoekwandeling in de natuur',
    description: 'Maak een wandeling in de natuur met je baby dicht tegen je aan.',
    instructions: [
      'Doe je baby in een draagdoek of drager, dicht tegen je borst.',
      'Wandel naar een rustig park, bos of groene omgeving.',
      'Vertel je baby onderweg wat je ziet: bladeren, vogels, wolken.',
      'Sta af en toe stil en luister samen naar de geluiden van de natuur.',
    ],
    reflection: 'Hoe reageerde je baby op de buitengeluiden en -geuren? Voelde de wandeling anders met je kind zo dichtbij?',
    scienceNote: 'Babydragen bevordert veilige hechting en vermindert huilen met gemiddeld 43% (Hunziker & Barr, 1986 – Increased carrying reduces infant crying).',
    durationMin: 15,
  },
  {
    id: 'zelr_02_209',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Zandbak zen',
    description: 'Help je peuter tot rust komen door sensorisch spel met zand.',
    instructions: [
      'Ga samen naar een zandbak of vul een bak met speelzand.',
      'Laat je kind zand door de vingers laten lopen en vormpjes maken.',
      'Doe zelf rustig mee en maak er een kalm, gezamenlijk moment van.',
      'Als je kind gefrustreerd raakt (vormpje lukt niet), help dan zonder over te nemen.',
    ],
    reflection: 'Zag je je kind tot rust komen door het sensorische spel? Hoe ging je om met frustratiemomenten?',
    scienceNote: 'Sensorisch spel activeert het proprioceptief systeem en heeft een kalmerend effect op het zenuwstelsel van jonge kinderen (Ayres, 1972 – Sensory Integration and Learning Disorders).',
    durationMin: 15,
  },

  // ============================================================
  // AGE GROUP 3-5 (10 tasks: 3 basis, 4 gevorderd, 3 expert)
  // ============================================================
  {
    id: 'aanw_35_210',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Natuurspeurtocht',
    description: 'Ga samen op zoek naar bijzondere dingen in de natuur.',
    instructions: [
      'Maak samen een lijstje van vijf dingen om te zoeken: een rood blaadje, een steen, een veertje, een bloem, een tak.',
      'Wandel samen door een park of bos en zoek de items.',
      'Laat je kind de leiding nemen: waar gaan we zoeken?',
      'Bewonder elke vondst samen en bespreek wat jullie zien, ruiken en voelen.',
    ],
    reflection: 'Hoe goed lukte het jou om het tempo van je kind te volgen? Wat ontdekte je kind dat jij niet had gezien?',
    scienceNote: 'Ongestructureerd buitenspel in de natuur verbetert aandacht en concentratie bij jonge kinderen (Kuo & Faber Taylor, 2004 – Children with attention deficits concentrate better after walk in park).',
    durationMin: 15,
  },
  {
    id: 'emco_35_211',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Gevoelens stampen en springen',
    description: 'Laat je kind boze of verdrietige gevoelens uiten via beweging.',
    instructions: [
      'Vraag je kind hoe het zich voelt en welke kleur of dier bij dat gevoel past.',
      'Ga naar buiten en bedenk een beweging bij het gevoel: boos = stampen, blij = springen, verdrietig = langzaam lopen.',
      'Doe de bewegingen samen en benoem het gevoel erbij: "We stampen de boosheid eruit!"',
      'Eindig met samen diep ademhalen en voelen hoe het gevoel veranderd is.',
    ],
    reflection: 'Veranderde het gevoel van je kind door de beweging? Hoe voelde het om zelf mee te doen?',
    scienceNote: 'Lichaamsgerichte emotieregulatie helpt kinderen om abstracte emoties concreet te ervaren en te verwerken (Greenspan & Wieder, 2006 – Engaging Autism / DIR-Floortime model).',
    durationMin: 10,
  },
  {
    id: 'zelr_35_212',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Schildpad-ademhaling',
    description: 'Leer je kind de schildpadademhaling als kalmeertechniek.',
    instructions: [
      'Ga samen op een rustige plek zitten, bij voorkeur buiten op het gras.',
      'Leg uit: "We gaan ademen als een schildpad. Langzaam inademen en je hoofd naar binnen trekken."',
      'Adem samen in (tel tot 4), houd vast (tel tot 2), en adem langzaam uit (tel tot 4).',
      'Herhaal vijf keer en bespreek hoe jullie je voelen: rustiger, slaperig, ontspannen?',
    ],
    reflection: 'Kon je kind het ritme volgen? Merkte je verschil in energie voor en na de oefening?',
    scienceNote: 'Ademhalingsoefeningen activeren de nervus vagus en verlagen cortisolniveaus bij kinderen vanaf 3 jaar (Porges, 2011 – The Polyvagal Theory).',
    durationMin: 5,
  },
  {
    id: 'gren_35_213',
    skill: 'Grenzen',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Stoeiregels samen maken',
    description: 'Stel samen veilige regels op voor stoeipartijen.',
    instructions: [
      'Ga samen op de grond zitten en vertel: "We gaan regels bedenken voor ons stoeigevecht."',
      'Laat je kind meedenken: wat mag wel en wat mag niet? Schrijf of teken de regels.',
      'Begin een korte stoeipartij en oefen met de regels: stoppen als iemand "stop" zegt.',
      'Evalueer samen na: "Hoe ging het? Hielden we ons aan de regels?"',
    ],
    reflection: 'Respecteerde je kind het stopwoord? Hoe voelde het om grenzen samen te bepalen in plaats van op te leggen?',
    scienceNote: 'Rough-and-tumble play met duidelijke grenzen leert kinderen zelfregulatie en sociale grenzen (Panksepp, 2007 – Can PLAY diminish ADHD?).',
    durationMin: 15,
  },
  {
    id: 'auto_35_214',
    skill: 'Autonomie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Eigen tuintje planten',
    description: 'Laat je kind zelf een plantje verzorgen van zaad tot spruit.',
    instructions: [
      'Koop samen zaadjes (tuinkers of zonnebloem) en een potje met aarde.',
      'Laat je kind zelf de aarde in het potje scheppen en het zaadje planten.',
      'Bepaal samen een plek voor het potje en maak een waterafspraak.',
      'Laat je kind elke dag zelf water geven en de groei bekijken.',
    ],
    reflection: 'Hoe reageerde je kind op de verantwoordelijkheid? Wat leerde het over geduld en zorg?',
    scienceNote: 'Tuinieren met kinderen bevordert verantwoordelijkheidsgevoel, geduld en verbondenheid met de natuur (Kellert, 2005 – Building for Life).',
    durationMin: 15,
  },
  {
    id: 'hers_35_215',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Verzoenwandeling',
    description: 'Herstel na een conflict door samen een korte wandeling te maken.',
    instructions: [
      'Wacht tot de eerste emoties gezakt zijn na een ruzie of boze bui.',
      'Stel voor: "Zullen we even samen naar buiten lopen? Frisse lucht doet ons goed."',
      'Loop samen zonder te praten over het conflict, wijs op dingen onderweg.',
      'Vraag na een paar minuten rustig: "Hoe voel je je nu? Zullen we het er samen over hebben?"',
    ],
    reflection: 'Merkte je dat de wandeling de spanning verminderde? Was het makkelijker om daarna te praten?',
    scienceNote: 'Wandelen naast elkaar verlaagt de confrontatiedrempel en bevordert open communicatie bij jonge kinderen (Oppezzo & Schwartz, 2014 – Give your ideas some legs).',
    durationMin: 10,
  },
  {
    id: 'verb_35_216',
    skill: 'Verbinding',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Samen koekjes bakken',
    description: 'Versterk de band door samen in de keuken iets lekkers te maken.',
    instructions: [
      'Kies samen een simpel koekjesrecept en leg de ingrediënten klaar.',
      'Laat je kind helpen met scheppen, roeren en vormpjes uitsteken.',
      'Praat tijdens het bakken: "Wat ruik je? Hoe voelt het deeg?"',
      'Geniet samen van het eindresultaat en deel de koekjes met het gezin.',
    ],
    reflection: 'Hoe was het om samen bezig te zijn zonder haast? Welk moment van verbinding viel je het meest op?',
    scienceNote: 'Samen koken stimuleert sensorische integratie, samenwerking en creëert positieve gedeelde herinneringen (Fiese et al., 2006 – Family routines and rituals).',
    durationMin: 15,
  },
  {
    id: 'refl_35_217',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Lichaamstekening met gevoelens',
    description: 'Teken samen een lichaam en ontdek waar gevoelens zitten.',
    instructions: [
      'Leg een groot vel papier neer en laat je kind erop liggen terwijl jij de omtrek tekent.',
      'Vraag: "Waar in je lichaam voel je blij? En waar voel je boos of bang?"',
      'Laat je kind met kleuren aangeven waar de gevoelens zitten.',
      'Bespreek samen: "Papa voelt boosheid hier in zijn buik. En jij?"',
    ],
    reflection: 'Wat leerde je over hoe je kind emoties lichamelijk ervaart? Waren er verrassingen?',
    scienceNote: 'Kinderen lokaliseren emoties in het lichaam, en bewustzijn hiervan verbetert emotieregulatie (Nummenmaa et al., 2014 – Bodily maps of emotions).',
    durationMin: 15,
  },
  {
    id: 'aanw_35_218',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Regenlaarzenwandeling',
    description: 'Trek je regenkleren aan en ontdek samen de regen.',
    instructions: [
      'Wacht op een regendag en trek samen regenlaarzen en -jassen aan.',
      'Ga naar buiten en zoek plassen om in te stampen.',
      'Luister samen naar de regen: op bladeren, op je capuchon, op de grond.',
      'Vang regendruppels in je hand en bekijk ze samen van dichtbij.',
    ],
    reflection: 'Hoe was het om bewust de regen te ervaren in plaats van te vermijden? Wat vond je kind het leukst?',
    scienceNote: 'Weersensitieve buitenactiviteiten verhogen de betrokkenheid en het welbevinden van kinderen (Gill, 2007 – No Fear: Growing up in a risk-averse society).',
    durationMin: 15,
  },
  {
    id: 'emco_35_219',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Dierengeluiden en emoties',
    description: 'Koppel diergeluiden aan emoties en beweeg als die dieren.',
    instructions: [
      'Benoem samen vier emoties: blij, boos, bang en verdrietig.',
      'Kies bij elke emotie een dier: blij = springend konijn, boos = brullende leeuw, bang = piepende muis, verdrietig = langzame schildpad.',
      'Beweeg samen door de kamer of tuin als elk dier en maak de geluiden.',
      'Vraag je kind: "Welk dier ben jij vandaag? Waarom?"',
    ],
    reflection: 'Hielp de dierenmetafoor je kind om over emoties te praten? Welk dier koos je kind?',
    scienceNote: 'Metaforen en rollenspel helpen kleuters om emoties te begrijpen en te bespreken (Harris, 2000 – Understanding Emotion in Childhood).',
    durationMin: 10,
  },

  // ============================================================
  // AGE GROUP 6-9 (10 tasks: 3 basis, 4 gevorderd, 3 expert)
  // ============================================================
  {
    id: 'aanw_69_220',
    skill: 'Aanwezigheid',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Stille wandeling in het bos',
    description: 'Wandel vijf minuten samen in stilte en ervaar de natuur met al je zintuigen.',
    instructions: [
      'Ga samen naar een bos of park en spreek af om vijf minuten stil te wandelen.',
      'Loop naast elkaar en richt je aandacht op wat je ziet, hoort, ruikt en voelt.',
      'Na vijf minuten staan jullie stil en deelt elk drie dingen die je opvielen.',
      'Bespreek samen wat het verschil was met een gewone wandeling.',
    ],
    reflection: 'Was de stilte lastig of juist prettig? Wat merkte je op dat je normaal zou missen?',
    scienceNote: 'Mindful wandelen in de natuur verlaagt stresshormonen en verhoogt aandacht bij kinderen (Kaplan & Kaplan, 1989 – The Experience of Nature).',
    durationMin: 15,
  },
  {
    id: 'emco_69_221',
    skill: 'Emotiecoaching',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Emotie-hardlopen',
    description: 'Gebruik verschillende loopstijlen om emoties fysiek te beleven.',
    instructions: [
      'Ga samen naar een veld of park met ruimte om te rennen.',
      'Bedenk samen hoe je rent bij verschillende emoties: woede = sprint, verdriet = joggen, vreugde = huppelen, kalmte = wandelen.',
      'Roep om de beurt een emotie en beweeg allebei op die manier.',
      'Bespreek na afloop: "Welke emotie voelde het sterkst in je lichaam?"',
    ],
    reflection: 'Hoe ervoer je kind het verband tussen bewegen en voelen? Welke emotie riep het vaakst?',
    scienceNote: 'Lichamelijke activiteit moduleert emotionele verwerking via de afgifte van endorfine en BDNF (Ratey, 2008 – Spark: The Revolutionary New Science of Exercise and the Brain).',
    durationMin: 10,
  },
  {
    id: 'zelr_69_222',
    skill: 'Zelfregulatie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Yoga-dieren in de tuin',
    description: 'Doe samen kinderyoga-houdingen gebaseerd op dieren buiten in de natuur.',
    instructions: [
      'Leg een mat of deken in de tuin of op een grasveld.',
      'Doe samen vijf dierenhoudingen: hond (downward dog), cobra, vlinder, boom en kat-koe.',
      'Houd elke houding vijf ademhalingen lang en benoem hoe je lichaam voelt.',
      'Eindig met samen op je rug te liggen en naar de wolken te kijken.',
    ],
    reflection: 'Welke houding vond je kind het leukst? Merkte je verschil in rustgevoel voor en na de oefening?',
    scienceNote: 'Kinderyoga verbetert zelfregulatie, lichaamsbesef en emotioneel welzijn (Khalsa et al., 2012 – Evaluation of the mental health benefits of yoga).',
    durationMin: 15,
  },
  {
    id: 'gren_69_223',
    skill: 'Grenzen',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Fair-play voetbal',
    description: 'Speel een potje voetbal en oefen samen met eerlijke regels en grenzen.',
    instructions: [
      'Maak samen een klein veld met jassen als doelpalen.',
      'Spreek drie eerlijkheidsregels af vóór het spelen, door je kind mee te laten beslissen.',
      'Speel een kort potje en pauzeer als een regel wordt overtreden: bespreek het rustig.',
      'Eindig met een "fair-play" handdruk en bespreek hoe het ging.',
    ],
    reflection: 'Hoe ging je kind om met verlies of fouten? Was het makkelijker om regels na te leven die het zelf had bedacht?',
    scienceNote: 'Sport met zelfontwikkelde regels bevordert moreel redeneren en internalisering van grenzen (Piaget, 1932 – The Moral Judgment of the Child).',
    durationMin: 15,
  },
  {
    id: 'auto_69_224',
    skill: 'Autonomie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Eigen route plannen',
    description: 'Laat je kind de route bepalen voor een wandeling of fietstocht.',
    instructions: [
      'Geef je kind een eenvoudige kaart van de buurt of laat het Google Maps gebruiken.',
      'Vraag: "Waar wil je naartoe? Jij mag de route bepalen."',
      'Volg de route van je kind, ook als het niet de snelste weg is.',
      'Bespreek onderweg: "Waarom koos je deze route? Wat zie je dat leuk is?"',
    ],
    reflection: 'Hoe voelde het om je kind de leiding te geven? Was je kind trots op de eigen route?',
    scienceNote: 'Autonomie-ondersteunend opvoeden bevordert intrinsieke motivatie en zelfvertrouwen (Deci & Ryan, 2000 – Self-Determination Theory).',
    durationMin: 15,
  },
  {
    id: 'hers_69_225',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Bouw samen iets na een conflict',
    description: 'Werk samen aan een bouwproject als fysieke manier om de band te herstellen.',
    instructions: [
      'Na een conflict, wacht tot de emoties gezakt zijn en stel voor: "Zullen we samen iets bouwen?"',
      'Kies een gezamenlijk project: een hut van takken, een Lego-bouwwerk of een zandkasteel.',
      'Werk samen en verdeel taken eerlijk: "Jij zoekt de takken, ik maak de basis."',
      'Praat tijdens het bouwen rustig over wat er gebeurde: "Ik vond het vervelend dat we ruzie hadden."',
    ],
    reflection: 'Hielp het gezamenlijke bouwen om de spanning te verminderen? Was het makkelijker om te praten terwijl jullie bezig waren?',
    scienceNote: 'Parallelle activiteiten verlagen de emotionele drempel voor herstelgesprekken, vooral bij jongens (Tronick, 2007 – The Neurobehavioral and Social-Emotional Development of Infants and Children).',
    durationMin: 15,
  },
  {
    id: 'verb_69_226',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Vuurtje stoken en marshmallows',
    description: 'Maak samen een kampvuurtje en geniet van marshmallows roosteren.',
    instructions: [
      'Zoek een veilige plek voor een vuurtje (vuurkorf, strand of kampeerterrein).',
      'Verzamel samen hout en bouw het vuurtje op, leg uit hoe vuur werkt.',
      'Rooster samen marshmallows en geniet van de warmte en het vuur.',
      'Vertel elkaar om de beurt een verhaal of herinnering bij het vuur.',
    ],
    reflection: 'Hoe was de sfeer bij het vuur? Deelde je kind spontaan verhalen of gedachten?',
    scienceNote: 'Vuur en warmte activeren het parasympathisch zenuwstelsel en bevorderen sociale binding (Wiessner, 2014 – Embers of society: Firelight talk among the Ju/\'hoansi Bushmen).',
    durationMin: 15,
  },
  {
    id: 'refl_69_227',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Lichaamsscan in de natuur',
    description: 'Doe een kindvriendelijke lichaamsscan liggend in het gras.',
    instructions: [
      'Zoek een rustig plekje in het gras en ga allebei op je rug liggen.',
      'Begeleid je kind: "Voel je voeten... je benen... je buik... je handen... je hoofd."',
      'Vraag bij elk lichaamsdeel: "Hoe voelt het daar? Warm? Ontspannen? Gespannen?"',
      'Eindig met drie diepe ademhalingen en bespreek wat jullie ontdekten.',
    ],
    reflection: 'Kon je kind benoemen wat het voelde in het lichaam? Welke lichaamsdelen waren het meest ontspannen of gespannen?',
    scienceNote: 'Lichaamsscan-meditatie verhoogt interceptief bewustzijn en vermindert angst bij kinderen (Schonert-Reichl & Lawlor, 2010 – Mindfulness Education for children).',
    durationMin: 10,
  },
  {
    id: 'verb_69_228',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Papa-kind obstacle course',
    description: 'Bouw samen een hindernisbaan in de tuin en doe hem samen.',
    instructions: [
      'Verzamel spullen: stoelen om onderdoor te kruipen, emmers om omheen te rennen, een touw om over te springen.',
      'Ontwerp samen de baan en bouw hem op in de tuin of het park.',
      'Doe de baan eerst samen en daarna om de beurt op tijd.',
      'Moedig je kind aan en vier elke prestatie, ongeacht de tijd.',
    ],
    reflection: 'Hoe was de samenwerking bij het ontwerpen? Genoot je kind meer van het bouwen of het rennen?',
    scienceNote: 'Fysiek uitdagend spel tussen vader en kind bevordert emotieregulatie en weerbaarheid (StGeorge & Freeman, 2017 – Father-child physical play).',
    durationMin: 15,
  },
  {
    id: 'aanw_69_229',
    skill: 'Aanwezigheid',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Steentjes keilen',
    description: 'Leer je kind steentjes keilen over het water en geniet van het moment.',
    instructions: [
      'Ga naar een meer, rivier of vijver met rustig water.',
      'Zoek samen platte steentjes die goed over het water kunnen scheren.',
      'Laat zien hoe je een steentje keilt en help je kind met de techniek.',
      'Tel samen de keren dat het steentje stuitert en vier elk record.',
    ],
    reflection: 'Hoe was de concentratie van je kind bij het oefenen? Genoot je van dit simpele, gezamenlijke moment?',
    scienceNote: 'Eenvoudige, herhaalbare buitenactiviteiten bevorderen flow-ervaringen en ouder-kindverbinding (Csikszentmihalyi, 1990 – Flow: The Psychology of Optimal Experience).',
    durationMin: 10,
  },

  // ============================================================
  // AGE GROUP 10-12 (10 tasks: 3 basis, 4 gevorderd, 3 expert)
  // ============================================================
  {
    id: 'aanw_1012_230',
    skill: 'Aanwezigheid',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Hardlopen zonder telefoon',
    description: 'Ga samen hardlopen en laat alle schermen thuis.',
    instructions: [
      'Spreek af om samen te gaan joggen in het park of de buurt.',
      'Laat allebei je telefoon thuis – geen muziek, geen afleiding.',
      'Loop in een tempo dat je allebei kunt volhouden en praat onderweg.',
      'Sta na afloop stil bij hoe het was om samen te bewegen zonder schermen.',
    ],
    reflection: 'Was het moeilijk om zonder telefoon te gaan? Waar praatten jullie over onderweg?',
    scienceNote: 'Gezamenlijk bewegen zonder digitale afleiding vergroot de kwaliteit van ouder-kindinteractie (Radesky et al., 2014 – Patterns of mobile device use by caregivers and children).',
    durationMin: 15,
  },
  {
    id: 'emco_1012_231',
    skill: 'Emotiecoaching',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Bokszak voor boosheid',
    description: 'Leer je kind om boosheid fysiek en veilig te uiten via een bokszak of kussen.',
    instructions: [
      'Hang een bokszak op of gebruik een groot kussen tegen de muur.',
      'Bespreek: "Boosheid is een energie in je lichaam. Die mag eruit, maar op een veilige manier."',
      'Laat je kind op de bokszak slaan terwijl je coacht: "Voel je de boosheid? Waar zit die?"',
      'Eindig met ademhalingsoefeningen en bespreek hoe het voelt na het boksen.',
    ],
    reflection: 'Hoe reageerde je kind op deze fysieke uitlaatklep? Veranderde de intensiteit van de boosheid?',
    scienceNote: 'Gecontroleerde fysieke expressie van woede in combinatie met reflectie is effectiever dan pure catharsis (Bushman, 2002; maar zie ook Gottman, 1997 – The Heart of Parenting).',
    durationMin: 10,
  },
  {
    id: 'zelr_1012_232',
    skill: 'Zelfregulatie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Ademhaling voor de wedstrijd',
    description: 'Oefen samen ademhalingstechnieken als voorbereiding op spannende momenten.',
    instructions: [
      'Ga samen zitten voor een sporttraining, toets of optreden.',
      'Leer de 4-7-8 techniek: inademen (4 tellen), vasthouden (7 tellen), uitademen (8 tellen).',
      'Doe drie rondes samen en bespreek hoe het voelt: "Merk je dat je hart rustiger klopt?"',
      'Spreek af om dit vaker samen te doen voor spannende momenten.',
    ],
    reflection: 'Kon je kind het verschil voelen voor en na de ademhaling? Vond je het zelf ook nuttig?',
    scienceNote: 'De 4-7-8 ademhalingstechniek activeert de parasympathische respons en vermindert prestatie-angst (Brown & Gerbarg, 2005 – Sudarshan Kriya yogic breathing).',
    durationMin: 5,
  },
  {
    id: 'gren_1012_233',
    skill: 'Grenzen',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Grenzen bij schermtijd na sport',
    description: 'Bespreek samen grenzen rondom schermtijd versus buitenspelen.',
    instructions: [
      'Ga samen iets actiefs doen: fietsen, voetballen of wandelen.',
      'Bespreek tijdens de activiteit: "Hoe voel je je nu versus na een uur gamen?"',
      'Maak samen een weekplanning: hoeveel uur buiten, hoeveel uur scherm?',
      'Laat je kind de verdeling voorstellen en onderhandel samen eerlijk.',
    ],
    reflection: 'Kon je kind het verschil benoemen tussen bewegen en schermtijd? Hoe eerlijk was de onderhandeling?',
    scienceNote: 'Kinderen die meedenken over schermtijdregels houden zich er beter aan (Valkenburg & Piotrowski, 2017 – Plugged In: How Media Attract and Affect Youth).',
    durationMin: 15,
  },
  {
    id: 'auto_1012_234',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Maaltijd helemaal zelf koken',
    description: 'Laat je kind een complete maaltijd plannen en koken met jou als hulpje.',
    instructions: [
      'Vraag je kind om een gerecht te kiezen en een boodschappenlijstje te maken.',
      'Ga samen boodschappen doen, maar laat je kind de leiding nemen.',
      'In de keuken is je kind de chef: jij helpt alleen als er gevraagd wordt.',
      'Eet samen het gerecht en geef oprecht complimenten over het resultaat.',
    ],
    reflection: 'Hoe ging je kind om met de verantwoordelijkheid? Was het moeilijk om niet in te grijpen?',
    scienceNote: 'Autonomie in dagelijkse taken vergroot het gevoel van competentie en eigenwaarde in de pre-adolescentie (Eccles et al., 1993 – Development during adolescence).',
    durationMin: 15,
  },
  {
    id: 'hers_1012_235',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Fietsen en praten na een fout',
    description: 'Ga samen fietsen na een conflict om ruimte te maken voor herstel.',
    instructions: [
      'Stel na een conflict voor: "Ik wil het graag goedmaken. Zullen we samen fietsen?"',
      'Fiets naast elkaar in een rustig tempo door een groene omgeving.',
      'Begin met luchtige onderwerpen en stuur langzaam naar het conflict: "Ik wil even zeggen dat het me spijt."',
      'Luister naar je kind zonder te verdedigen en bedank voor het eerlijke gesprek.',
    ],
    reflection: 'Was het makkelijker om naast elkaar te praten dan tegenover elkaar? Wat was het effect van de beweging?',
    scienceNote: 'Naast-elkaar-activiteiten verminderen de emotionele lading van moeilijke gesprekken, vooral bij pre-adolescenten (Kindlon & Thompson, 2000 – Raising Cain).',
    durationMin: 15,
  },
  {
    id: 'verb_1012_236',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Steen-workshop bij de rivier',
    description: 'Zoek samen mooie stenen en maak er iets van.',
    instructions: [
      'Ga samen naar een rivier, strand of bos en zoek bijzondere stenen.',
      'Sorteer de stenen op kleur, vorm of grootte en bespreek jullie favorieten.',
      'Maak samen iets: een steenmannetje, een toren of een mandala op de grond.',
      'Maak een foto van jullie creatie en laat het achter in de natuur.',
    ],
    reflection: 'Hoe was het om samen iets te creëren zonder eindresultaat-druk? Welke steen was je favoriet?',
    scienceNote: 'Creatieve buitenactiviteiten zonder prestatiedruk bevorderen intrinsieke motivatie en verbinding (Amabile, 1996 – Creativity in Context).',
    durationMin: 15,
  },
  {
    id: 'refl_1012_237',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Sterren kijken en levensvragen',
    description: 'Kijk samen naar de sterren en bespreek grote vragen.',
    instructions: [
      'Ga op een heldere avond samen buiten liggen op een deken.',
      'Kijk naar de sterren en wijs sterrenbeelden aan die je kent.',
      'Stel open vragen: "Wat denk je dat er achter de sterren is? Wat wil jij later ontdekken?"',
      'Luister aandachtig en deel ook je eigen verwondering.',
    ],
    reflection: 'Welke vragen stelde je kind die je verraste? Hoe voelde het om samen te verwonderen?',
    scienceNote: 'Gedeelde verwondering (shared awe) versterkt sociale verbondenheid en prosociaal gedrag (Piff et al., 2015 – Awe, the small self, and prosocial behavior).',
    durationMin: 15,
  },
  {
    id: 'emco_1012_238',
    skill: 'Emotiecoaching',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Emotie-dagboek na het sporten',
    description: 'Schrijf na een sport-activiteit samen op welke emoties er waren.',
    instructions: [
      'Doe samen een sport-activiteit: voetbal, hardlopen, zwemmen of fietsen.',
      'Pak daarna allebei een notitieboekje en schrijf drie emoties op die je voelde.',
      'Deel om de beurt je emoties en leg uit wanneer je ze voelde: "Bij de sprint voelde ik frustratie."',
      'Bespreek: "Hoe veranderden je emoties van begin tot eind?"',
    ],
    reflection: 'Werden jullie je bewuster van emoties door ze op te schrijven? Hadden jullie vergelijkbare ervaringen?',
    scienceNote: 'Expressief schrijven over emoties na fysieke activiteit vergroot emotioneel bewustzijn en verwerking (Pennebaker, 1997 – Writing about emotional experiences).',
    durationMin: 10,
  },
  {
    id: 'zelr_1012_239',
    skill: 'Zelfregulatie',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Balans-uitdaging',
    description: 'Doe samen balansoefeningen en merk hoe focus en kalmte samenhangen.',
    instructions: [
      'Ga samen op één been staan en kijk wie het langst kan balanceren.',
      'Probeer variaties: ogen dicht, armen omhoog, op een smal muurtje lopen.',
      'Bespreek: "Wat moet je doen om in balans te blijven? Rustig ademen helpt!"',
      'Maak de link: "Net als in balans staan, helpt rustig blijven ook bij lastige situaties."',
    ],
    reflection: 'Begreep je kind de link tussen lichamelijke en emotionele balans? Wie had de beste balans?',
    scienceNote: 'Balansoefeningen verbeteren executieve functies en zelfregulatie bij kinderen (Diamond & Lee, 2011 – Interventions shown to aid executive function development).',
    durationMin: 10,
  },

  // ============================================================
  // AGE GROUP 13-16 (10 tasks: 3 basis, 4 gevorderd, 3 expert)
  // ============================================================
  {
    id: 'aanw_1316_240',
    skill: 'Aanwezigheid',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen naar de sportschool',
    description: 'Ga samen trainen en wees aanwezig naast je tiener zonder te pushen.',
    instructions: [
      'Stel voor om samen naar de sportschool, het zwembad of een buitentraining te gaan.',
      'Laat je tiener kiezen wat jullie doen – jij volgt.',
      'Train naast elkaar en geniet van de gedeelde inspanning zonder te coachen.',
      'Praat na afloop bij een glas water: "Hoe vond je het?"',
    ],
    reflection: 'Hoe was het om naast je tiener te sporten zonder de leiding te nemen? Ontstond er vanzelf gesprek?',
    scienceNote: 'Gedeelde fysieke activiteiten zijn een effectieve manier om verbinding te behouden met adolescenten (Larson & Richards, 1994 – Divergent Realities).',
    durationMin: 15,
  },
  {
    id: 'emco_1316_241',
    skill: 'Emotiecoaching',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Wandelen als het moeilijk is',
    description: 'Ga wandelen wanneer je tiener het moeilijk heeft, als veilige ruimte voor emoties.',
    instructions: [
      'Merk wanneer je tiener gespannen of somber is en stel een wandeling voor, niet als verplicht.',
      'Loop naast elkaar en begin niet meteen over het probleem.',
      'Wacht tot je tiener zelf begint of vraag zachtjes: "Hoe gaat het eigenlijk echt met je?"',
      'Luister zonder oordeel of oplossingen; bevestig: "Dat klinkt zwaar. Ik snap dat je je zo voelt."',
    ],
    reflection: 'Opende je tiener zich tijdens de wandeling? Hoe moeilijk was het om niet direct oplossingen te bieden?',
    scienceNote: 'Adolescenten praten makkelijker over emoties tijdens parallelle activiteiten dan in face-to-face gesprekken (Steinberg, 2014 – Age of Opportunity).',
    durationMin: 15,
  },
  {
    id: 'zelr_1316_242',
    skill: 'Zelfregulatie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Koude douche-challenge',
    description: 'Daag elkaar uit met koud water als oefening in ongemak verdragen.',
    instructions: [
      'Bespreek het concept: "Koude blootstelling leert je om ongemak te verdragen en kalm te blijven."',
      'Begin samen met 30 seconden koud water aan het einde van de douche.',
      'Focus op de ademhaling: rustig blijven inademen door de neus.',
      'Bouw elke week 10 seconden op en bespreek hoe het werd: "Wat deed je om het vol te houden?"',
    ],
    reflection: 'Hoe ging je tiener om met het ongemak? Zie je een link met het verdragen van andere moeilijke momenten?',
    scienceNote: 'Gecontroleerde koude-blootstelling activeert de prefrontale cortex en traint stressrespons-regulatie (Huberman, 2021; gebaseerd op Šrámek et al., 2000 – Human physiological responses to cold).',
    durationMin: 5,
  },
  {
    id: 'gren_1316_243',
    skill: 'Grenzen',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Fysieke grenzen in sparring',
    description: 'Oefen respectvol sparren of worstelen met duidelijke grenzen.',
    instructions: [
      'Spreek samen regels af: geen gezicht, stoppen bij "stop", respect voor elkaars kracht.',
      'Begin met licht armworstelen of gecontroleerd duwen (staand, schouder tegen schouder).',
      'Let op de grens tussen speels en te hard: "Gaat het nog? Was dat te veel?"',
      'Bespreek na afloop: "Hoe weet je wanneer je een grens bereikt? Hoe geef je dat aan?"',
    ],
    reflection: 'Hoe respecteerde je tiener de grenzen? Was er een moment dat iemand bijna te ver ging?',
    scienceNote: 'Fysiek spel tussen vaders en adolescenten leert grensherkenning en zelfbeheersing (Fletcher et al., 2013 – Fathers and rough-and-tumble play).',
    durationMin: 10,
  },
  {
    id: 'auto_1316_244',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Eigen sportdoel stellen',
    description: 'Help je tiener een persoonlijk sportdoel te formuleren en een plan te maken.',
    instructions: [
      'Vraag: "Is er een fysiek doel dat je wilt bereiken? 5 km hardlopen, 10 push-ups, of iets anders?"',
      'Help je tiener een realistisch plan te maken met tussenstappen.',
      'Bied aan om samen te trainen, maar laat de keuze bij je kind.',
      'Check wekelijks in: "Hoe gaat het met je doel? Kan ik ergens bij helpen?"',
    ],
    reflection: 'Hoe gemotiveerd was je tiener door een eigen doel versus een opgelegd doel? Hoe ondersteun je zonder te pushen?',
    scienceNote: 'Autonome doelkeuze verhoogt intrinsieke motivatie en doorzettingsvermogen bij adolescenten (Ryan & Deci, 2017 – Self-Determination Theory).',
    durationMin: 10,
  },
  {
    id: 'hers_1316_245',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Samen klauteren na ruzie',
    description: 'Ga samen klimmen of klauteren als fysieke herstelmethode na een conflict.',
    instructions: [
      'Stel na een stevige ruzie voor om samen te gaan klimmen (klimhal, bomen, of een klauterpark).',
      'De fysieke uitdaging vraagt focus en vertrouwen op elkaar: "Ik zeker je, jij klimt."',
      'Wissel rollen: jij klimt ook en laat je tiener je zekeren of aanmoedigen.',
      'Bespreek onderweg of na afloop: "We moeten op elkaar vertrouwen hè? Dat geldt ook thuis."',
    ],
    reflection: 'Hielp de fysieke activiteit om de ruzie in perspectief te plaatsen? Voelde het vertrouwen sterker na het klimmen?',
    scienceNote: 'Gedeelde fysieke uitdagingen herstellen vertrouwen en verbinding door gedeelde kwetsbaarheid (Alon & Omer, 2006 – The psychology of daring in NVR).',
    durationMin: 15,
  },
  {
    id: 'verb_1316_246',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Barbecue-avond samen',
    description: 'Bereid samen een barbecue voor als gedeeld ritueel.',
    instructions: [
      'Plan samen een barbecue-avond en verdeel de taken: jij maakt het vuur, je tiener bereidt de salades.',
      'Werk naast elkaar in de tuin en geniet van het proces.',
      'Eet samen buiten en praat over alledaagse dingen: geen zware onderwerpen.',
      'Ruim samen op en bespreek: "Dit moeten we vaker doen, toch?"',
    ],
    reflection: 'Ontstond er natuurlijk gesprek tijdens het koken? Hoe was de sfeer anders dan bij een gewone maaltijd?',
    scienceNote: 'Gedeelde maaltijdrituelen versterken familiecohesie en bieden een veilige context voor communicatie (Fulkerson et al., 2006 – Family dinner meal frequency).',
    durationMin: 15,
  },
  {
    id: 'refl_1316_247',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Bergwandeling met levensvragen',
    description: 'Maak een uitdagende wandeling en bespreek diepere levensvragen.',
    instructions: [
      'Plan een langere wandeling (1-2 uur) naar een uitkijkpunt of heuvel.',
      'Stel onderweg open vragen: "Waar wil je over 5 jaar staan? Wat maakt jou jou?"',
      'Deel ook je eigen reflecties: "Toen ik zo oud was als jij, dacht ik..."',
      'Geniet op de top samen van het uitzicht en de stilte.',
    ],
    reflection: 'Welk onderwerp raakte je tiener het meest? Hoe was het om je eigen ervaringen te delen?',
    scienceNote: 'Fysiek uitdagende activiteiten in de natuur creëren openheid voor diepe reflectie en identiteitsontwikkeling (Kaplan & Kaplan, 1989 – The Experience of Nature; Erikson, 1968 – Identity: Youth and Crisis).',
    durationMin: 15,
  },
  {
    id: 'aanw_1316_248',
    skill: 'Aanwezigheid',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Surfles of SUP samen',
    description: 'Probeer samen een nieuwe watersport en wees gelijke beginners.',
    instructions: [
      'Boek samen een surfles, SUP-les of kano-uitje.',
      'Sta open voor het feit dat je tiener misschien sneller leert dan jij.',
      'Lach samen om jullie mislukkingen en moedig elkaar aan.',
      'Bespreek na afloop: "Hoe was het om samen iets nieuws te proberen?"',
    ],
    reflection: 'Hoe was het om allebei beginner te zijn? Was de dynamiek anders dan normaal?',
    scienceNote: 'Gedeelde nieuwe ervaringen activeren het beloningssysteem en versterken de relatie (Aron et al., 2000 – Couples shared participation in novel activities).',
    durationMin: 15,
  },
  {
    id: 'verb_1316_249',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Avondlijke ronde door de buurt',
    description: 'Maak er een gewoonte van om samen een avondwandeling te maken.',
    instructions: [
      'Stel voor om na het avondeten een rondje door de buurt te lopen.',
      'Laat gesprekken vanzelf ontstaan – geen agenda, geen verplicht praten.',
      'Loop in het tempo van je tiener en sta stil als hij/zij dat wil.',
      'Maak er een wekelijks ritueel van: jullie vaste wandelmoment.',
    ],
    reflection: 'Merkte je dat je tiener na een paar weken meer ging delen? Hoe voelt het ritueel voor jou?',
    scienceNote: 'Consistente, laagdrempelige rituelen zijn de basis van verbondenheid in de adolescentie (Phares et al., 2009 – Father involvement and adolescent adjustment).',
    durationMin: 10,
  },
];
