// Aanwezigheid – Ronde 2: 50 nieuwe interactieve taken (5 leeftijdsgroepen × 10)
import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_10: InteractiveTask[] = [

  // ─── 0-2 jaar ────────────────────────────────────────────────
  {
    id: 'aanw_02_11',
    title: 'Telefoon in een andere kamer',
    skill: 'Aanwezigheid',
    description: 'Leg je telefoon 20 minuten in een andere kamer. Speel of zit gewoon bij je baby. Geen scherm, geen afleiding. Merk op wat er verandert in de ruimte.',
    duration: '20 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Fysieke aanwezigheid van een telefoon – zelfs als hij niet gebruikt wordt – verlaagt de kwaliteit van aandacht. De hersenen blijven "wachten" op een melding.',
    skillTip: 'Zet hem ook op stil. Het geluid van meldingen is al genoeg om je uit de aanwezigheid te halen.',
    vermijd: 'Vermijd hem "even snel" checken. 20 minuten is 20 minuten.',
    leerdoel: 'Je ervaart wat volledige aanwezigheid zonder scherm voelt en doet.',
    bron: 'Ward, A.F. et al. (2017). Brain Drain: The Mere Presence of One\'s Own Smartphone Reduces Available Cognitive Capacity.',
  },
  {
    id: 'aanw_02_12',
    title: 'Vertraag één verzorgingsmoment',
    skill: 'Aanwezigheid',
    description: 'Kies één verzorgingsmoment vandaag (verschonen, voeden, aankleden) en doe het bewust langzamer. Praat, kijk, glimlach. Geen haast.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Haast communiceert aan baby\'s dat ze een klus zijn in plaats van een persoon. Vertragen activeert het zorgsysteem van de vader en de veiligheid van het kind.',
    skillTip: 'Benoem elke stap hardop: "Nu doe ik jouw sokje aan..." Dit koppelt taal aan aanwezigheid.',
    vermijd: 'Vermijd tegelijk de was sorteren of nadenken over je dag. Eén ding tegelijk.',
    leerdoel: 'Je leert verzorgmomenten als verbindingsmomenten te benutten.',
    bron: 'Stern, D. (1985). The Interpersonal World of the Infant.',
  },
  {
    id: 'aanw_02_13',
    title: 'Vijf ademhalingen samen',
    skill: 'Aanwezigheid',
    description: 'Houd je baby vast en adem vijf keer bewust in en uit. Synchroniseer met zijn ritme als dat kan. Voel het gewicht van hem in je armen.',
    duration: '2 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Gedeeld ademhalen synchroniseert het autonome zenuwstelsel van twee mensen. Dit verlaagt cortisol bij beide en activeert de parasympathische "rust en verbinding"-modus.',
    skillTip: 'Sluit je ogen als dat kan. Dat verdiept de lichamelijke aanwezigheid.',
    vermijd: 'Vermijd dit doen uit gewoonte. Doe het bewust, als een actieve keuze.',
    leerdoel: 'Je gebruikt ademhaling als anker voor aanwezigheid in het moment.',
    bron: 'Porges, S.W. (2011). The Polyvagal Theory.',
  },
  {
    id: 'aanw_02_14',
    title: 'Wat zie ik nu?',
    skill: 'Aanwezigheid',
    description: 'Kijk 2 minuten aandachtig naar je baby. Neem hem op: zijn gezichtsuitdrukking, zijn handen, zijn bewegingen. Wat zie je dat je normaal niet ziet?',
    duration: '2 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Bewuste observatie activeert dezelfde hersendelen als meditatie. Het traint de aandacht om in het nu te blijven in plaats van te vooruitlopen of terugblikken.',
    skillTip: 'Praat hardop wat je ziet: "Ik zie jouw kleine vingers... je kijkt me aan..." Dit verdiept de aandacht.',
    vermijd: 'Vermijd al plannen maken of dagdromen. Dit is alleen kijken.',
    leerdoel: 'Je traint gerichte aandacht als vaardigheid voor aanwezigheid.',
    bron: 'Kabat-Zinn, J. (1994). Wherever You Go, There You Are.',
  },
  {
    id: 'aanw_02_15',
    title: 'Nachtvoeding volledig aanwezig',
    skill: 'Aanwezigheid',
    description: 'Als je vannacht opstaat voor een voeding: geen telefoon. Zit in het donker, houd je kind vast, en wees er volledig. Luister naar de stilte. Voel het moment.',
    duration: '15 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Nachtvoedingen zijn vermoeiend maar ook intieme momenten. Vaders die ze bewust beleven rapporteren meer verbondenheid met hun kind, ondanks de slaaptekort.',
    skillTip: 'Beschouw het als een rustig cadeautje: de wereld slaapt, jij en je kind zijn wakker samen.',
    vermijd: 'Vermijd je slaapgebrek meten of tellen. Dit moment is niet over slaap.',
    leerdoel: 'Je ervaart hoe aanwezigheid ook midden in vermoeidheid mogelijk is.',
    bron: 'Feldman, R. (2007). Parent-infant synchrony and the construction of shared timing.',
  },
  {
    id: 'aanw_02_16',
    title: 'Bodyscan voor bedtijd',
    skill: 'Aanwezigheid',
    description: 'Voor je je baby neerlegt: scan je eigen lichaam van hoofd tot voeten. Waar zit spanning? Laat het los. Wees dan rustig en bewust aanwezig bij het neerlegen.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Ouders die gespannen zijn communiceren dit non-verbaal. Een bodyscan voor het neerlegen kalmeert het zenuwstelsel en maakt een rustige overdracht mogelijk.',
    skillTip: 'Drie ademhalingen na de scan. Dan pas bewegen.',
    vermijd: 'Vermijd dit overslaan als je moe bent – juist dan is het het meest waardevol.',
    leerdoel: 'Je leert jouw spanningstoestand te herkennen en bewust te kalmeren vóór contact.',
    bron: 'Kabat-Zinn, J. (1990). Full Catastrophe Living.',
  },
  {
    id: 'aanw_02_17',
    title: 'Eén speelmoment: jij volgt',
    skill: 'Aanwezigheid',
    description: 'Geef je baby of peuter 10 minuten volledig de leiding. Kijk wat hij pakt, wat hij wil. Jij volgt zijn ritme. Geen sturing, geen structuur.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Volgend spelen (child-led play) is één van de krachtigste methoden om hechtingsveiligheid te versterken. Het kind ervaart dat zijn initiatief welkom is.',
    skillTip: 'Als hij een speelgoed negeert dat jij interessant vindt – laat het los. Hij weet wat hij wil.',
    vermijd: 'Vermijd structuur aanbrengen of doelen stellen aan het spel.',
    leerdoel: 'Je oefent het volgen van je kind als actieve aanwezigheidsvaardigheid.',
    bron: 'Landreth, G.L. (2012). Play Therapy: The Art of the Relationship.',
  },
  {
    id: 'aanw_02_18',
    title: 'Zingen zonder reden',
    skill: 'Aanwezigheid',
    description: 'Zing een liedje voor je kind – niet als bedtijdritueel, maar gewoon zomaar. Midden op de dag. Kijk naar zijn reactie en blijf volledig aanwezig daarin.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Zingen activeert meerdere hersendelen tegelijk en trekt de volle aandacht van baby\'s. Het is ook een aanwezigheidsritueel voor de vader: je kunt niet zingen en tegelijk ergens anders zijn.',
    skillTip: 'Maak oogcontact terwijl je zingt. Improviseer de tekst over wat je ziet.',
    vermijd: 'Vermijd op je telefoon een liedje opzoeken. Zing uit je hoofd, hoe het ook klinkt.',
    leerdoel: 'Je ervaart zingen als een volledige aanwezigheidsoefening.',
    bron: 'Trevarthen, C. (1999). Musicality and the intrinsic motive pulse.',
  },
  {
    id: 'aanw_02_19',
    title: 'Bewust optillen',
    skill: 'Aanwezigheid',
    description: 'De volgende keer dat je je kind optilt: doe het bewust. Kijk hem aan, zeg zijn naam, pak hem op met beide handen en voel zijn gewicht. Geen automatisch gebaar.',
    duration: '1 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Routinematige handelingen worden automatisch en bewusteloos uitgevoerd. Ze bewust maken herstelt de aanwezigheid in gewone momenten.',
    skillTip: 'Herhaal dit elke keer dat je hem optilt vandaag. Elk keer bewust.',
    vermijd: 'Vermijd hem optillen terwijl je praat met iemand anders of naar je scherm kijkt.',
    leerdoel: 'Je transformeert automatische handelingen in bewuste verbindingsmomenten.',
    bron: 'Kabat-Zinn, J. (1994). Wherever You Go, There You Are.',
  },
  {
    id: 'aanw_02_20',
    title: 'Herken zijn signalen',
    skill: 'Aanwezigheid',
    description: 'Observeer je baby 10 minuten bewust. Schrijf dan op: welke signalen geeft hij als hij moe is? Hongerig? Gestimuleerd? Hoe herken jij zijn taal?',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Het leren lezen van kindersignalen is de kern van responsief ouderschap. Aanwezigheid zonder herkenning leidt niet tot echte verbinding.',
    skillTip: 'Maak een mentale of fysieke lijst. Zijn signalen zijn zijn taal – leer die taal.',
    vermijd: 'Vermijd gissen of veronderstellen. Kijk echt.',
    leerdoel: 'Je vergroot je gevoeligheid voor de non-verbale communicatie van je kind.',
    bron: 'Ainsworth, M.D.S. et al. (1978). Patterns of Attachment.',
  },

  // ─── 3-5 jaar ────────────────────────────────────────────────
  {
    id: 'aanw_35_11',
    title: 'Vertel wat je ziet',
    skill: 'Aanwezigheid',
    description: 'Kijk 5 minuten naar je kind terwijl hij speelt. Benoem hardop wat je ziet: "Je stapelt de blokken hoog op. Nu valt hij om. Je lacht." Geen oordeel, alleen beschrijving.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Sportcommentaar-stijl beschrijven (sportscasting) toont het kind dat je echt kijkt. Het geeft woorden aan zijn handelingen en vergroot zijn taalvaardigheid tegelijk.',
    skillTip: 'Gebruik een neutrale, warme toon – zoals een vriend die enthousiast commentaar geeft.',
    vermijd: 'Vermijd advies of instructies geven. "Pas op dat hij niet valt" is sturing, geen aanwezigheid.',
    leerdoel: 'Je oefent actieve, beschrijvende aanwezigheid zonder sturen.',
    bron: 'Landreth, G.L. (2012). Play Therapy: The Art of the Relationship.',
  },
  {
    id: 'aanw_35_12',
    title: 'Geen multitasking-regel',
    skill: 'Aanwezigheid',
    description: 'Stel voor jezelf een regel in: als je kind met je praat, stop je met wat je doet. Draai je naar hem toe. Oogcontact. Dan pas reageer je.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Multitasking tijdens een gesprek met een kind verlaagt de waargenomen kwaliteit van de relatie. Kinderen voelen onmiddellijk of ze prioriteit zijn of bijzaak.',
    skillTip: 'Oefen dit als een tastbare handeling: stop, draai, kijk, dan reageer. Vier stappen.',
    vermijd: 'Vermijd "ja, ja" zeggen terwijl je kookt of typt. Dat is geen aanwezigheid.',
    leerdoel: 'Je maakt aanwezigheid een actieve gewoonte in gewone gesprekken.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'aanw_35_13',
    title: 'Buiten niets doen',
    skill: 'Aanwezigheid',
    description: 'Ga buiten zitten of staan met je kind, zonder geplande activiteit. Laat hem bepalen wat er gebeurt. Jij zit erbij – aanwezig, rustig, beschikbaar.',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Ongestructureerde buitentijd met een aanwezige vader vergroot de veerkracht en creativiteit van kinderen. Aanwezigheid zonder agenda is een krachtig signaal.',
    skillTip: 'Weersta de drang om iets te organiseren. Gewoon er zijn is de activiteit.',
    vermijd: 'Vermijd je telefoon pakken als het "saai" wordt. Saai is precies de ruimte waar kinderen hun beste spel vinden.',
    leerdoel: 'Je leert aanwezig zijn zonder dat er iets hoeft te gebeuren.',
    bron: 'Brown, S. (2009). Play: How it Shapes the Brain.',
  },
  {
    id: 'aanw_35_14',
    title: 'Raad zijn gedachten',
    skill: 'Aanwezigheid',
    description: 'Kijk naar je kind terwijl hij speelt. Probeer te raden wat hij denkt of voelt. Vraag daarna: "Ik dacht dat je aan X dacht – klopt dat?" Luister naar zijn antwoord.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Actief perspectief nemen (mentalizing) versterkt de empathische verbinding en helpt kinderen hun eigen innerlijk leven te benoemen en begrijpen.',
    skillTip: 'Wees oprecht nieuwsgierig – niet bevestigend. Als je verkeerd raadt, is dat oké en informatief.',
    vermijd: 'Vermijd zijn gedachten voor hem invullen. De vraag stellen is voldoende.',
    leerdoel: 'Je oefent actief perspectief nemen als aanwezigheidsvaardigheid.',
    bron: 'Fonagy, P. et al. (2002). Affect Regulation, Mentalization, and the Development of the Self.',
  },
  {
    id: 'aanw_35_15',
    title: 'Zijn tempo volgen',
    skill: 'Aanwezigheid',
    description: 'Neem vandaag één activiteit in zijn tempo: lopen, eten, aankleden. Niet haastig. Volg zijn ritme, ook als het langzamer gaat dan jij wilt.',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Gehaaste ouders communiceren onbewust dat het kind een probleem is dat opgelost moet worden. Zijn tempo volgen geeft hem het gevoel van acceptatie en waardigheid.',
    skillTip: 'Bereken extra tijd in. Als je 10 minuten extra plant, verdwijnt de haast als stress.',
    vermijd: 'Vermijd subtiel duwen of haastige woorden. Zelfs "Kom, snel snel" breekt de aanwezigheid.',
    leerdoel: 'Je leert aanwezigheid ook in de tijdsdimensie – niet alleen in aandacht.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2011). The Whole-Brain Child.',
  },
  {
    id: 'aanw_35_16',
    title: 'Neem een foto met je ogen',
    skill: 'Aanwezigheid',
    description: 'Op een mooi moment vandaag: pak je telefoon NIET. Kijk in plaats daarvan bewust en zeg in jezelf: "Dit wil ik onthouden." Schrijf het later op.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Fotograferen activeert het registratiesysteem van het brein maar deactiveert de emotionele beleving. Bewust onthouden zonder camera vergroot aanwezigheid en geheugenkwaliteit.',
    skillTip: 'Zeg het hardop: "Ik wil dit moment onthouden." Dat verankert het in je geheugen.',
    vermijd: 'Vermijd de redenering "maar dan vergeet ik het". Bewuste aandacht onthoud je beter dan foto\'s.',
    leerdoel: 'Je kiest bewust voor beleving boven documentatie.',
    bron: 'Henkel, L.A. (2014). Point-and-shoot memories: The influence of taking photos on memory for a museum tour.',
  },
  {
    id: 'aanw_35_17',
    title: 'Zeg zijn naam met aandacht',
    skill: 'Aanwezigheid',
    description: 'Gebruik vandaag bewust de naam van je kind als je hem aanspreekt – niet "hé" of "jongen". Zijn naam, rustig uitgesproken, met oogcontact.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'De eigen naam is het krachtigste woord in iemands geheugen. Bewust de naam gebruiken activeert herkenning en veiligheid in het kind.',
    skillTip: 'Let ook op je toon. Dezelfde naam kan warm of koud klinken – kies bewust voor warm.',
    vermijd: 'Vermijd roepen van de naam als er iets mis is. Dan koppelt hij zijn naam aan spanning.',
    leerdoel: 'Je gebruikt zijn naam als instrument van aanwezigheid en erkenning.',
    bron: 'Moray, N. (1959). Attention in dichotic listening: Affective cues and the influence of instructions.',
  },
  {
    id: 'aanw_35_18',
    title: 'Echt lachen samen',
    skill: 'Aanwezigheid',
    description: 'Doe iets geks dat je kind echt aan het lachen maakt: een grappig geluid, een gekke dans, een onverwacht woord. En lach echt mee.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Gedeeld lachen synchroniseert het zenuwstelsel via geluid en beweging. Het is een van de snelste wegen naar echte aanwezigheid – je kunt niet echt lachen zonder er te zijn.',
    skillTip: 'Laat je verrassen. Als hij lacht om iets onverwachts, doe mee – niet beleefd maar echt.',
    vermijd: 'Vermijd geforceerd of beleefdheidslachen. Kinderen voelen het verschil direct.',
    leerdoel: 'Je ervaart lachen als een directe aanwezigheidsindicator.',
    bron: 'Dunbar, R.I.M. et al. (2012). Social laughter is correlated with an elevated pain threshold.',
  },
  {
    id: 'aanw_35_19',
    title: 'Wat speelt hij het liefst?',
    skill: 'Aanwezigheid',
    description: 'Observeer je kind een kwartiertje in zijn vrije spel. Wat kiest hij telkens? Schrijf drie dingen op die je ziet. Vraag hem daarna: "Wat vind jij het leukste om te spelen?"',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Speelkeuzes zijn ramen naar het innerlijk leven van een kind. Bewust observeren vergroot jouw kennis van wie hij is – en dat kennen is de basis van aanwezigheid.',
    skillTip: 'Vergelijk je observatie met zijn antwoord. Kloppen ze? Wat verbaast je?',
    vermijd: 'Vermijd zijn voorkeur interpreteren vanuit jouw smaak. Zijn spel is zijn eigen taal.',
    leerdoel: 'Je verdiept jouw kennis van je kind als individu via gerichte observatie.',
    bron: 'Piaget, J. (1962). Play, Dreams and Imitation in Childhood.',
  },
  {
    id: 'aanw_35_20',
    title: 'Einde van de dag check-in',
    skill: 'Aanwezigheid',
    description: 'Voor het slapengaan: zit een minuut naast je kind in stilte. Vraag: "Wat was jouw beste moment vandaag?" Luister. Deel daarna jouw moment ook.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Een vast dagafsluiting-ritueel verankert veiligheid en aanwezigheid. Kinderen die dit hebben, slapen beter en rapporteren meer gevoel van verbondenheid met hun vader.',
    skillTip: 'Houd het luchtig. Het is geen evaluatie – het is een gedeeld moment.',
    vermijd: 'Vermijd vragen over school of verplichtingen. Dit is het moment van de dag, niet de dag evalueren.',
    leerdoel: 'Je bouwt een dagelijks aanwezigheidsritueel dat verbinding verankert.',
    bron: 'National Center on Addiction and Substance Abuse. (2011). The Importance of Family Dinners.',
  },

  // ─── 6-9 jaar ────────────────────────────────────────────────
  {
    id: 'aanw_69_11',
    title: 'Vraag drie keer door',
    skill: 'Aanwezigheid',
    description: 'Als je kind iets vertelt vandaag: reageer en stel dan drie keer een doorvraag. Niet drie tegelijk – één voor één, wachtend op zijn antwoord.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Doorvragen communiceert dat jij echt geïnteresseerd bent, niet alleen beleefde aandacht geeft. Kinderen die ervaren dat vader doorvraagt, gaan meer delen.',
    skillTip: 'Gebruik: "En wat vond je dan?", "Hoe voelde dat?", "Wat deed jij toen?" Simpel maar krachtig.',
    vermijd: 'Vermijd gesloten vragen die een "ja/nee" uitlokken. Open vragen houden het gesprek gaande.',
    leerdoel: 'Je oefent actief luisteren met oprechte nieuwsgierigheid als kern.',
    bron: 'Gordon, T. (1970). Parent Effectiveness Training.',
  },
  {
    id: 'aanw_69_12',
    title: 'Zijn wereld in zijn ogen',
    skill: 'Aanwezigheid',
    description: 'Vraag je kind je school te beschrijven alsof jij nog nooit van scholen gehoord hebt. Luister alsof het echt nieuw voor je is. Stel naïeve vragen.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Naïeve nieuwsgierigheid (beginnersmind) doorbreekt aannames en maakt echte aandacht mogelijk. Kinderen voelen het als vader echt wil begrijpen, niet alleen maar vraagt.',
    skillTip: 'Doe alsof je een buitenaardse bent die school niet kent. "En wat is een juf precies?" Echt vragen.',
    vermijd: 'Vermijd je eigen schoolherinneringen inbrengen. Dit is zijn verhaal.',
    leerdoel: 'Je oefent aanwezigheid via echte, onbevooroordeelde nieuwsgierigheid.',
    bron: 'Suzuki, S. (1970). Zen Mind, Beginner\'s Mind.',
  },
  {
    id: 'aanw_69_13',
    title: 'Aanwezig bij zijn hobby',
    skill: 'Aanwezigheid',
    description: 'Kijk 15 minuten toe terwijl je kind zijn hobby beoefent. Geen telefoon. Geen commentaar. Gewoon volledig aanwezig zijn. Knik, glimlach, kijk.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Passieve maar aanwezige aanschouwer zijn communiceert: "Wat jij doet is het waard om naar te kijken." Dit vergroot het gevoel van waarde en motivatie bij het kind.',
    skillTip: 'Na afloop: één echte observatie noemen. "Ik zag hoe je dat herhaalde tot het lukte." Specifiek.',
    vermijd: 'Vermijd advies, aanmoediging of begeleiding. Alleen aanwezig zijn is de taak.',
    leerdoel: 'Je ervaart aanwezigheid als getuige-zijn zonder interveniëren.',
    bron: 'Dweck, C. (2006). Mindset: The New Psychology of Success.',
  },
  {
    id: 'aanw_69_14',
    title: 'Zijdelingse wandeling',
    skill: 'Aanwezigheid',
    description: 'Maak een wandeling zonder bestemming. Loop naast hem, niet voor hem. Volg zijn tempo. Als hij stil staat, sta jij stil. Praat als hij praat, zwijg als hij zwijgt.',
    duration: '20 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Zij-aan-zij activiteiten verlagen de drempel voor gesprek. De afwezigheid van direct oogcontact maakt het voor kinderen makkelijker om moeilijke of gevoelige dingen te delen.',
    skillTip: 'Als hij plotseling begint te praten over iets diepers: vertraag je stap en luister.',
    vermijd: 'Vermijd een route of doel opleggen. Dit is zijn wandeling.',
    leerdoel: 'Je ervaart zij-aan-zij aanwezigheid als uitnodiging voor spontaan delen.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2011). The Whole-Brain Child.',
  },
  {
    id: 'aanw_69_15',
    title: 'Afwezig herkennen en herstellen',
    skill: 'Aanwezigheid',
    description: 'Merk vandaag op wanneer je wegdwaalt in je hoofd tijdens een moment met je kind. Erken het intern: "Ik was er even niet." Keer dan bewust terug.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Het bewust herkennen van mentale afwezigheid en terugkeren is de kern van mindfulness. Vaders die dit oefenen zijn niet perfector aanwezig, maar herstelvaardiger.',
    skillTip: 'Gebruik een interne zin: "Ik ben er nu." Dat activeert de aandacht terug naar het moment.',
    vermijd: 'Vermijd jezelf bekritiseren als je wegdwaalt. Dat vergroot de afwezigheid. Gewoon terugkeren.',
    leerdoel: 'Je oefent aanwezigheids-herstel als vaardigheid: wegdrijven is normaal, terugkeren is de skill.',
    bron: 'Kabat-Zinn, J. (1990). Full Catastrophe Living.',
  },
  {
    id: 'aanw_69_16',
    title: 'Maak ruimte voor stilte',
    skill: 'Aanwezigheid',
    description: 'Zet na het avondeten 10 minuten geen muziek, tv of schermen aan. Zit gewoon samen in de ruimte. Laat eventueel een gesprek ontstaan – of niet.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Achtergrondgeluid en schermen vullen de ruimte die gesprekken nodig hebben om te kunnen ontstaan. Stilte is de voedingsbodem voor organische verbinding.',
    skillTip: 'Als het ongemakkelijk voelt: dat is normaal. We zijn niet gewend aan stilte. Houd het vol.',
    vermijd: 'Vermijd de stilte opvullen met een activiteit. Laat het open zijn.',
    leerdoel: 'Je creëert bewust ruimte voor organische verbinding door stilte toe te laten.',
    bron: 'Turkle, S. (2015). Reclaiming Conversation.',
  },
  {
    id: 'aanw_69_17',
    title: 'Eén vraag per dag',
    skill: 'Aanwezigheid',
    description: 'Stel jezelf als gewoonte in: elke dag één echte, persoonlijke vraag aan je kind. Niet over school – over zijn gedachten, gevoelens, dromen.',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Consistente dagelijkse vragen bouwen over tijd een diepere kennisrelatie op. Kinderen beginnen te verwachten dat vader geïnteresseerd is – en leven daarnaar toe.',
    skillTip: 'Varieer de vragen. Houd een lijstje bij van vragen die je wil stellen. Zo word je niet voorspelbaar.',
    vermijd: 'Vermijd dezelfde vraag elke dag ("Hoe was school?"). Variatie houdt het levendig.',
    leerdoel: 'Je bouwt een dagelijkse aanwezigheidspraktijk via structurele nieuwsgierigheid.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'aanw_69_18',
    title: 'Fysiek aanwezig bij verdriet',
    skill: 'Aanwezigheid',
    description: 'Als je kind vandaag verdrietig of gefrustreerd is: ga naast hem zitten (niet tegenover). Zeg niets. Leg eventueel je hand op zijn schouder. Wees er gewoon.',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Fysieke aanwezigheid bij negatieve emoties zonder oplossingsdruk is de meest krachtige vorm van emotionele steun. Het kind ervaart: "Mijn gevoel is draagbaar met jou erbij."',
    skillTip: 'Weersta de drang om te troosten met woorden. Aanwezigheid zelf is de troost.',
    vermijd: 'Vermijd "het is niet erg" of "niet huilen". Dat minimaliseert zijn gevoel.',
    leerdoel: 'Je leert aanwezig zijn bij emotie zonder te hoeven oplossen.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2011). The Whole-Brain Child.',
  },
  {
    id: 'aanw_69_19',
    title: 'Verras hem met aandacht',
    skill: 'Aanwezigheid',
    description: 'Doe iets onverwachts dat alleen gaat over jouw aandacht: stop midden op de dag onverwacht bij zijn kamer en zeg: "Hé, ik dacht even aan jou." Niets meer.',
    duration: '2 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Onverwachte positieve aandacht heeft een disproportioneel groot effect op de ervaren verbondenheid van kinderen. Het doorbreekt de verwachting en registreert als echt.',
    skillTip: 'Zeg er niets achteraan. Geen verzoek, geen advies. Gewoon dat ene zinnetje.',
    vermijd: 'Vermijd er een "maar" achter plakken. "Ik dacht aan je, maar je kamer..." werkt averechts.',
    leerdoel: 'Je gebruikt spontane aandacht als krachtig verbindingsinstrument.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'aanw_69_20',
    title: 'Wat weet ik echt van hem?',
    skill: 'Aanwezigheid',
    description: 'Schrijf tien dingen op die je weet over je kind: zijn angsten, zijn dromen, zijn favoriete dingen, zijn vrienden. Hoe veel weet je echt?',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Gottman noemt het "liefdeskaart" bijhouden: kennis van de innerlijke wereld van je kind. Hoe meer je weet, hoe beter je kunt afstemmen en aanwezig zijn.',
    skillTip: 'Waar het moeilijk wordt, is waar de groei zit. Dat zijn de vragen die je kunt stellen.',
    vermijd: 'Vermijd je tevredenstellen met oppervlakkige kennis. Wie is hij echt?',
    leerdoel: 'Je meet jouw kennis van je kind en identificeert waar meer nieuwsgierigheid nodig is.',
    bron: 'Gottman, J. (1999). The Marriage Clinic.',
  },

  // ─── 10-12 jaar ──────────────────────────────────────────────
  {
    id: 'aanw_1012_11',
    title: 'Zijn taal leren',
    skill: 'Aanwezigheid',
    description: 'Vraag je kind je te leren over iets wat hij gebruikt: een game, een app, een woord, een meme. Laat hem de expert zijn. Luister echt en probeer het te begrijpen.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Leren van je kind keert de machtsverhouding om en bevestigt zijn competentie. Dit vergroot de verbondenheid en het zelfvertrouwen van het kind tegelijk.',
    skillTip: 'Stel echte vragen. "Waarom doe je dat zo?" toont echte interesse. Nep-interesse voelen ze.',
    vermijd: 'Vermijd neerbuigend "leuk hoor" reageren. Echt proberen te begrijpen is het doel.',
    leerdoel: 'Je ervaart hoe omgekeerde rollen de verbinding en het zelfvertrouwen van je kind versterken.',
    bron: 'Deci, E.L. & Ryan, R.M. (1985). Intrinsic Motivation and Self-Determination.',
  },
  {
    id: 'aanw_1012_12',
    title: 'Checken zonder agenda',
    skill: 'Aanwezigheid',
    description: 'Klop aan bij je kind en zeg: "Ik kom even gedag zeggen, hoe is het?" En bedoel het echt. Geen follow-up vragen over school of verplichtingen. Alleen aandacht.',
    duration: '5 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Regelmatige, agendaloze check-ins van vader bouwen vertrouwen op over tijd. Kinderen gaan meer delen als ze weten dat er geen evaluatie of advies achter zit.',
    skillTip: 'Als hij meer vertelt dan je verwacht: luister. Zeg niets terug tenzij hij vraagt.',
    vermijd: 'Vermijd gesprekken altijd laten uitdraaien op verplichtingen. Dan houden ze alles in.',
    leerdoel: 'Je bouwt een gewoonte van regelmatige, veilige aanwezigheid zonder agenda.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'aanw_1012_13',
    title: 'Samen iets kijken dat hij kiest',
    skill: 'Aanwezigheid',
    description: 'Vraag je kind iets te kiezen dat jullie samen kijken – zijn keuze volledig. Kijk het echt, zonder commentaar. Wees aanwezig in zijn wereld.',
    duration: '30 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Bereid zijn om in iemands wereld te stappen zonder oordeel is een krachtig teken van respect. Voor kinderen van 10-12 is hun culturele keuze deel van hun identiteit.',
    skillTip: 'Stel na afloop één oprechte vraag: "Wat maakt dit voor jou zo leuk?" Geen samenvatting geven.',
    vermijd: 'Vermijd commentaar op de inhoud als het niet jouw smaak is. Dat sluit deuren.',
    leerdoel: 'Je oefent aanwezigheid in zijn wereld zonder jouw referentiekader op te leggen.',
    bron: 'Arnett, J.J. (2000). Emerging adulthood: A theory of development from the late teens through the twenties.',
  },
  {
    id: 'aanw_1012_14',
    title: 'Aanwezig bij een prestatie',
    skill: 'Aanwezigheid',
    description: 'Ga naar iets waar je kind trots op is of aan deelneemt: een wedstrijd, een presentatie, een optreden. Wees er volledig – niet met je hoofd bij je werk.',
    duration: '60 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'De aanwezigheid van vader bij prestaties heeft een disproportioneel groot effect op het zelfvertrouwen van het kind. Zien dat vader er is, registreert dieper dan een compliment achteraf.',
    skillTip: 'Zeg na afloop iets specifiek: "Ik zag dat je X deed, dat was indrukwekkend." Niet alleen "goed gedaan".',
    vermijd: 'Vermijd je telefoon als hij op het podium staat of speelt. Jouw aanwezige blik is het geschenk.',
    leerdoel: 'Je ervaart hoe fysieke aanwezigheid bij wat hij doet dieper werkt dan welk compliment ook.',
    bron: 'Bandura, A. (1977). Self-efficacy: Toward a unifying theory of behavioral change.',
  },
  {
    id: 'aanw_1012_15',
    title: 'Reageer op zijn gevoel, niet zijn woorden',
    skill: 'Aanwezigheid',
    description: 'Als je kind vandaag iets vertelt, probeer dan te reageren op wat je ziet dat hij voelt, niet op de inhoud. "Het klinkt alsof je er gefrustreerd over bent?" – dan pas luisteren.',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Empathisch reflecteren op gevoel in plaats van inhoud toont dat je echt aanwezig bent op het emotionele niveau van het gesprek – de laag die er écht toe doet.',
    skillTip: 'Gebruik: "Het klinkt alsof...", "Ik zie dat...", "Ik merk dat jij..." als starters.',
    vermijd: 'Vermijd direct reageren op de inhoud. "Maar had je dan niet gewoon..." is inhoud, niet gevoel.',
    leerdoel: 'Je leert emotioneel reflecteren als aanwezigheidsvaardigheid in gesprekken.',
    bron: 'Rogers, C.R. (1961). On Becoming a Person.',
  },
  {
    id: 'aanw_1012_16',
    title: 'Ochtend-ritual: even contact',
    skill: 'Aanwezigheid',
    description: 'Zorg elke ochtend voor een bewust moment van contact voordat de dag begint: een schouderklopje, een blik, een "Goede morgen" met oogcontact. Klein maar consistent.',
    duration: '2 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Consistente dagelijkse rituelen – hoe klein ook – bouwen een veilig anker van verbinding. Ze communiceren: "Jij bent de eerste aan wie ik denk vandaag."',
    skillTip: 'Houd het luchtig maar intentioneel. Neem even de tijd voor echt oogcontact.',
    vermijd: 'Vermijd het overslaan als je haast hebt. Juist dan is het het meest nodig.',
    leerdoel: 'Je bouwt een dagelijkse aanwezigheidsgewoonte die verbinding verankert.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'aanw_1012_17',
    title: 'Zijn zorg serieus nemen',
    skill: 'Aanwezigheid',
    description: 'Als je kind iets benoemt dat hem dwarszit – hoe klein ook – neem het volledig serieus. Ga zitten. Vraag door. Laat zien dat het ertoe doet voor jou.',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kinderen testen of hun zorg veilig is om te delen door kleine zorgen te uiten. Hoe vader reageert bepaalt of ze later grotere zorgen zullen delen.',
    skillTip: 'Behandel elke zorg alsof het de belangrijkste ter wereld is. Want voor hem, op dat moment, is dat zo.',
    vermijd: 'Vermijd "dat valt wel mee" of "dat is niet zo erg". Zelfs als het objectief klein is.',
    leerdoel: 'Je bouwt veiligheid voor grotere gesprekken door kleine zorgen serieus te nemen.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'aanw_1012_18',
    title: 'Stil naast hem zitten',
    skill: 'Aanwezigheid',
    description: 'Als je kind huiswerk maakt of iets op zijn kamer doet: vraag of je even erbij mag zitten. Zeg niets, doe je eigen ding. Gewoon in dezelfde ruimte zijn.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Parallel aanwezig zijn (parallel play bij volwassenen) communiceert beschikbaarheid zonder druk. Kinderen ervaren dat vader er ís zonder een gesprek te forceren.',
    skillTip: 'Neem iets mee om te lezen of te doen. Dit is geen inspectiemoment – het is gewoon samen zijn.',
    vermijd: 'Vermijd commentaar op zijn werk of zijn kamer. Je bent te gast.',
    leerdoel: 'Je ervaart hoe aanwezigheid ook mogelijk is zonder interactie.',
    bron: 'Winnicott, D.W. (1958). The capacity to be alone.',
  },
  {
    id: 'aanw_1012_19',
    title: 'Vraag naar zijn vrienden',
    skill: 'Aanwezigheid',
    description: 'Vraag je kind van 10-12 naar zijn vrienden: wie zijn zijn beste vrienden? Wat vind hij leuk aan hen? Is er iemand waarmee het nu minder goed gaat?',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Vriendschappen worden centraler in de identiteitsontwikkeling van pre-pubers. Interesse tonen in zijn sociale wereld is een directe weg naar zijn innerlijk leven.',
    skillTip: 'Onthoud namen. Vraag volgende week naar dezelfde personen. Dat toont dat je echt luisterde.',
    vermijd: 'Vermijd oordelen over zijn vrienden. Elke negatieve reactie sluit de deur.',
    leerdoel: 'Je vergroot jouw aanwezigheid in zijn sociale wereld door echte interesse.',
    bron: 'Rubin, K.H. et al. (2006). Peer interactions, relationships, and groups.',
  },
  {
    id: 'aanw_1012_20',
    title: 'Afronden met aandacht',
    skill: 'Aanwezigheid',
    description: 'De volgende keer dat jullie een gesprek of activiteit afsluiten: doe het bewust. Kijk hem aan. Zeg iets kleins. Maak er een echte afsluiting van in plaats van weglopers.',
    duration: '2 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Hoe iets eindigt bepaalt grotendeels hoe het onthouden wordt. Een bewuste afsluiting verankert de positieve ervaring en signaleert respect.',
    skillTip: 'Gebruik iets eenvoudigs: "Fijn dat we dit deden." Oprecht en simpel.',
    vermijd: 'Vermijd weglopen of het laten uitdoven. Een afsluiting is even belangrijk als een opening.',
    leerdoel: 'Je leert beginnen én eindigen van momenten met bewuste aandacht.',
    bron: 'Kahneman, D. (2011). Thinking, Fast and Slow.',
  },

  // ─── 13-16 jaar ──────────────────────────────────────────────
  {
    id: 'aanw_1316_11',
    title: 'Beschikbaar zijn zonder vragen',
    skill: 'Aanwezigheid',
    description: 'Laat je tiener weten: "Ik ben beschikbaar als je wil praten – geen vragen, geen verplicht gesprek." Dan: wacht. Doe geen moeite om hem ertoe te verleiden.',
    duration: '5 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Tieners praten vaker als ze weten dat aanwezigheid veilig is en vrijblijvend. De paradox: hoe minder je pusht, hoe meer ze delen.',
    skillTip: 'Zeg het één keer, duidelijk en oprecht. Niet herhalen. Laat het landen.',
    vermijd: 'Vermijd hem er subtiel op aanspreken als hij niet reageert. Wachten is de vaardigheid.',
    leerdoel: 'Je leert beschikbaarheid aanbieden zonder druk – de paradox van tienerverbinding.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'aanw_1316_12',
    title: 'Schermvrije autorit',
    skill: 'Aanwezigheid',
    description: 'Tijdens een rit in de auto: geen muziek, geen podcast, geen telefoon. Rijd. Kijk uit het raam. Als hij praat – luister. Als hij zwijgt – rijd gewoon.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'De auto is een uniek communicatievenster voor tieners: zijdelings, tijdelijk, vluchtroute aan het einde. Veel tieners brengen gevoelige onderwerpen in de auto ter sprake.',
    skillTip: 'Wees niet teleurgesteld als er niets gezegd wordt. De open ruimte heeft waarde op zichzelf.',
    vermijd: 'Vermijd het gesprek forceren. Stilte in de auto is ook aanwezigheid.',
    leerdoel: 'Je erkent de auto als bijzondere aanwezigheidsruimte en benut die.',
    bron: 'Csikszentmihalyi, M. & Larson, R. (1984). Being Adolescent.',
  },
  {
    id: 'aanw_1316_13',
    title: 'Aanwezig bij zijn slechte dag',
    skill: 'Aanwezigheid',
    description: 'Als je tiener duidelijk een slechte dag heeft: ga niet weg en stel geen vragen. Zit in dezelfde ruimte. Zeg: "Ik zie dat het niet makkelijk is vandaag." Dan: niets meer.',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Tieners willen bij slechte dagen eerst erkenning, dan pas verbinding. Te snel vragen of helpen werkt averechts. Stille aanwezigheid met erkenning is het krachtigst.',
    skillTip: 'Na je zin: zwijg. Kijk niet te intens. Doe iets kleins in de ruimte. Wees beschikbaar.',
    vermijd: 'Vermijd "vertel me wat er is" of "je kunt het me vertellen". Dat is druk, geen aanwezigheid.',
    leerdoel: 'Je leert aanwezig zijn bij negatieve emotie zonder te interveniëren.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2014). No-Drama Discipline.',
  },
  {
    id: 'aanw_1316_14',
    title: 'Zijn muziek zonder oordeel',
    skill: 'Aanwezigheid',
    description: 'Vraag je tiener zijn favoriete nummer te spelen. Luister volledig – ook als je het niet mooi vindt. Vraag daarna: "Wat betekent dit nummer voor jou?"',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Muziek is een primaire identiteitsuitdrukking voor tieners. Bereid zijn het te horen zonder oordeel is een krachtige uiting van respect voor wie hij is.',
    skillTip: 'Luister naar de tekst. Vraag naar specifieke regels. Dat toont dat je echt luisterde.',
    vermijd: 'Vermijd "dat is toch geen muziek" of nonverbale afkeuring. Die sluiten deuren.',
    leerdoel: 'Je ervaart aanwezigheid via oprechte interesse in zijn identiteitsuitdrukking.',
    bron: 'Arnett, J.J. (1995). Adolescents\' uses of media for self-socialization.',
  },
  {
    id: 'aanw_1316_15',
    title: 'Reactie uitstellen',
    skill: 'Aanwezigheid',
    description: 'De volgende keer dat je tiener iets doet of zegt dat je irriteert: tel tot tien voor je reageert. Adem. Observeer wat je voelt. Dan pas kiezen hoe je reageert.',
    duration: '5 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Reactievertraging is een kernvaardigheid van emotionele regulatie. De 10 seconden pauze activeren de prefrontale cortex en verminderen automatische, reactieve respons.',
    skillTip: 'In die 10 seconden: focus op je ademhaling, niet op zijn gedrag. Dat kalmeer sneller.',
    vermijd: 'Vermijd de pauze gebruiken om je argument op te bouwen. Het is om te kalmeren, niet om te winnen.',
    leerdoel: 'Je oefent reactievertraging als aanwezigheidsvaardigheid bij spanning.',
    bron: 'Siegel, D.J. (2010). Mindsight: The New Science of Personal Transformation.',
  },
  {
    id: 'aanw_1316_16',
    title: 'Oordeel-vrij luisteren',
    skill: 'Aanwezigheid',
    description: 'Vraag je tiener vandaag iets te vertellen zonder dat jij reageert met advies of oordeel. Alleen luisteren. Alleen knikken. Alleen: "Ik hoor je."',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Tieners stoppen met delen als ze voorspellen dat vader advies of kritiek geeft. Oordeel-vrij luisteren heropent communicatiekanalen die al tijden gesloten zijn.',
    skillTip: 'Als je iets wil zeggen: slik het in. Later, als hij klaar is, kun je vragen: "Wil je mijn mening?"',
    vermijd: 'Vermijd gezichtsuitdrukkingen die je oordeel tonen. Neutraal, warm, open.',
    leerdoel: 'Je leert luisteren zonder dat jouw reactie de inhoud bepaalt.',
    bron: 'Rogers, C.R. (1961). On Becoming a Person.',
  },
  {
    id: 'aanw_1316_17',
    title: 'Wees er als hij thuiskomt',
    skill: 'Aanwezigheid',
    description: 'Wees bewust aanwezig als je tiener thuiskomt. Kijk op. Zeg zijn naam. Vraag één vraag – maar geen "hoe was school?" Gebruik iets concreets: "Hoe ging dat ding van vandaag?"',
    duration: '5 min',
    ageGroups: ['13-16'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Het eerste contactmoment na de schooldag is cruciaal. Hoe vader dan reageert bepaalt de toon van de avond en de bereidheid van het kind om te delen.',
    skillTip: 'Vraag naar iets specifieks dat je van tevoren wist: een toets, een vriend, een activiteit.',
    vermijd: 'Vermijd niet opkijken van je scherm of werk. De eerste seconden tellen het meest.',
    leerdoel: 'Je maakt het thuiskomen van je kind een bewust verbindingsmoment.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'aanw_1316_18',
    title: 'Vraag hoe je het doet als vader',
    skill: 'Aanwezigheid',
    description: 'Vraag je tiener eerlijk: "Wat doe ik goed als vader? Wat kan ik beter doen?" Luister zonder je te verdedigen. Bedank hem voor zijn antwoord.',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Vader die feedback vraagt aan zijn kind laat zien dat hij serieus wil leren en groeit. Dit doorbreekt de hiërarchie en vergroot het wederzijds respect.',
    skillTip: 'Schrijf zijn antwoorden op. Laat hem zien dat je het serieus neemt door er later op terug te komen.',
    vermijd: 'Vermijd je verdedigen of uitleggen. Dit is geen debat. Alleen luisteren.',
    leerdoel: 'Je ervaart hoe kwetsbaar feedback vragen jouw aanwezigheid en respect vergroot.',
    bron: 'Hattie, J. (2009). Visible Learning.',
  },
  {
    id: 'aanw_1316_19',
    title: 'Volg zijn tempo in gesprek',
    skill: 'Aanwezigheid',
    description: 'Als je tiener langzaam of met lange pauzes praat: vul die pauzes niet in. Wacht geduldig. Tieners denken terwijl ze praten – stille ruimte is essentieel.',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Onderbrekingen en invullen van zinnen signaleren dat jouw agenda groter is dan zijn verhaal. Geduldig wachten is een actieve aanwezigheidsvaardigheid.',
    skillTip: 'Tel stil tot vijf na zijn laatste woord voor je reageert. Soms komt er dan meer.',
    vermijd: 'Vermijd het ongemak van stilte verdrijven door te praten. Jouw ongemak is jouw werk.',
    leerdoel: 'Je oefent geduldig wachten als actieve luistervaardigheid.',
    bron: 'Gordon, T. (1970). Parent Effectiveness Training.',
  },
  {
    id: 'aanw_1316_20',
    title: 'Einde van de avond: check-in',
    skill: 'Aanwezigheid',
    description: 'Voordat je tiener naar bed gaat: even kort contact. Geen groot gesprek – gewoon: "Goede nacht. Ik houd van je." En meen het.',
    duration: '2 min',
    ageGroups: ['13-16'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Dagelijkse uitingen van liefde – hoe simpel ook – vormen de basis van een veilige hechting voor tieners. Ze hebben het net zo hard nodig als kleine kinderen, maar verwachten het minder.',
    skillTip: 'Zeg het ook als de avond gespannen was. Juist dan is het het krachtigst.',
    vermijd: 'Vermijd het overslaan "omdat het toch niks uitmaakt". Het maakt alles uit.',
    leerdoel: 'Je bouwt een dagelijks afsluiting-ritueel dat liefde als vanzelfsprekend verankert.',
    bron: 'Bowlby, J. (1988). A Secure Base.',
  },
];
