// Grenzen – Ronde 2: 50 nieuwe interactieve taken (5 leeftijdsgroepen × 10)
import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_13: InteractiveTask[] = [

  // ─── 0-2 jaar ────────────────────────────────────────────────
  {
    id: 'gren_02_11',
    title: 'Nee zeggen met warmte',
    skill: 'Grenzen',
    description: 'Oefen vandaag een nee met warmte: als je kind iets niet mag, zeg het rustig, duidelijk, en met zachte stem. "Dat mag niet. Ik weet dat je dat wil." Dan vasthouden.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Grenzen met warmte combineren de twee componenten van veilige hechting: responsiviteit (warmte) en structuur (grens). Kinderen die dit ervaren, zijn veiliger gehecht.',
    skillTip: 'Toon je zacht van toon, maar firm in de grens. Warmte en duidelijkheid zijn niet tegenstrijdig.',
    vermijd: 'Vermijd harde toon of schuld induceren. "Dat mag niet" is genoeg – geen uitleg of straf nodig.',
    leerdoel: 'Je oefent grenzen stellen met warmte als combinatie van liefde en structuur.',
    bron: 'Baumrind, D. (1966). Effects of authoritative parental control on child behavior.',
  },
  {
    id: 'gren_02_12',
    title: 'Consequent zijn bij één grens',
    skill: 'Grenzen',
    description: 'Kies één grens die je consequent wil zijn de komende week (bijv. niet op tafel klimmen). Houd die grens elke keer aan, ook als het makkelijker is om toe te geven.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Inconsistente grenzen zijn verwarrender dan geen grenzen. Consequentie geeft het kind een betrouwbaar wereldmodel en verlaagt de neiging om grenzen te blijven testen.',
    skillTip: 'Kies maar één grens om op te focussen. Meer tegelijk leidt tot inconsistentie.',
    vermijd: 'Vermijd toegeven als hij aandringt. Toegeven na verzet leert hem dat harder aandringen werkt.',
    leerdoel: 'Je ervaart hoe consequentie bij één grens de effectiviteit vergroot.',
    bron: 'Baumrind, D. (1991). The influence of parenting style on adolescent competence and substance use.',
  },
  {
    id: 'gren_02_13',
    title: 'Grens + alternatief bieden',
    skill: 'Grenzen',
    description: 'Als je een grens stelt, bied dan altijd een alternatief aan: "Je mag niet op de tafel klimmen, maar wel op de bank." Of: "Dit mag je niet pakken, maar dit wel."',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Grenzen met alternatieven respecteren de behoefte achter het verboden gedrag. Kinderen zijn eerder bereid een grens te accepteren als hun onderliggende behoefte erkend wordt.',
    skillTip: 'Denk eerst na over de behoefte (klimmen, pakken, bewegen). Dan zoek je het alternatief voor die behoefte.',
    vermijd: 'Vermijd alleen nee zeggen. Altijd: "Niet dit, maar wel dat." Dat is vollediger.',
    leerdoel: 'Je leert grenzen te koppelen aan alternatieven die de onderliggende behoefte respecteren.',
    bron: 'Landreth, G.L. (2012). Play Therapy: The Art of the Relationship.',
  },
  {
    id: 'gren_02_14',
    title: 'Veiligheidsgrens uitleggen op niveau',
    skill: 'Grenzen',
    description: 'Als je een veiligheidsgrens stelt (niet bij het vuur, niet op straat): leg het kort uit op zijn niveau. "Dat is heet – au." Of: "Auto\'s gaan snel – dat is gevaarlijk."',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Korte uitleg bij veiligheidsgrenzen bouwt begrip op, ook als het kind de logica nog niet volledig kan volgen. Het koppelt de grens aan een reden, niet aan willekeur.',
    skillTip: 'Houd de uitleg kort en concreet. Eén woord of één zin is voldoende: "Heet. Au." Eenvoud werkt.',
    vermijd: 'Vermijd lange uitleg. Bij jonge kinderen werkt kort en herhaalbaar beter dan compleet.',
    leerdoel: 'Je koppelt grenzen aan begrijpelijke redenen als basis voor internalisering.',
    bron: 'Kohlberg, L. (1969). Stage and sequence: The cognitive-developmental approach to socialization.',
  },
  {
    id: 'gren_02_15',
    title: 'Emotie erkennen, grens houden',
    skill: 'Grenzen',
    description: 'Als je kind boos is om een grens: erken zijn gevoel eerst, dan herhaal de grens rustig. "Ik zie dat je boos bent. Dat is oké. Maar het antwoord blijft nee."',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Emotie erkennen voor je de grens herhaalt vermindert de weerstand. Het kind voelt zich gehoord, wat zijn bereidheid vergroot om de grens te accepteren.',
    skillTip: 'De volgorde is altijd: eerst gevoel erkennen, dan grens herhalen. Nooit omgekeerd.',
    vermijd: 'Vermijd de grens loslaten alleen om het huilen te stoppen. Dat leert hem dat huilen grenzen opheft.',
    leerdoel: 'Je leert emotie en grens te combineren: beide tegelijk, in de juiste volgorde.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'gren_02_16',
    title: 'Grens met lichaamstaal ondersteunen',
    skill: 'Grenzen',
    description: 'Geef een grens ook met je lichaam: ga op zijn hoogte zitten, maak rustig oogcontact, houd je hand eventueel zacht vast. Woord + lichaam = duidelijker grens.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Jonge kinderen lezen lichaamstaal primair. Een grens die verbaal en non-verbaal consistent is, is begrijpelijker en geloofwaardiger dan alleen woorden.',
    skillTip: 'Zorg dat je stem en lichaam hetzelfde zeggen. Incongruentie verwart.',
    vermijd: 'Vermijd grenzen stellen vanuit een afstand terwijl je iets anders doet. Aanwezig zijn maakt de grens duidelijker.',
    leerdoel: 'Je leert grenzen te versterken via congruente lichaamstaal.',
    bron: 'Mehrabian, A. (1971). Silent Messages.',
  },
  {
    id: 'gren_02_17',
    title: 'Minder grenzen, strenger vasthouden',
    skill: 'Grenzen',
    description: 'Evalueer welke grenzen je nu stelt. Zijn ze allemaal nodig? Kies de drie meest essentiële. Laat de rest los. En houd de drie consequent aan.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Minder grenzen die consequent worden gehanteerd, zijn effectiever dan veel grenzen die inconsistent zijn. Kwaliteit van handhaving is belangrijker dan kwantiteit van regels.',
    skillTip: 'Criteria voor een essentiële grens: veiligheid, gezondheid, of respect. De rest is flexibel.',
    vermijd: 'Vermijd grenzen stellen uit gewoonte of angst. Vraag steeds: is deze grens echt nodig?',
    leerdoel: 'Je vergroot de effectiviteit van grenzen door te focussen op essentiële.',
    bron: 'Baumrind, D. (1991). The influence of parenting style on adolescent competence.',
  },
  {
    id: 'gren_02_18',
    title: 'Grens herhalen zonder escaleren',
    skill: 'Grenzen',
    description: 'Als je kind een grens blijft testen: herhaal dezelfde grens, in dezelfde toon, dezelfde woorden, drie keer. Niet harder, niet meer uitleg. Gewoon herhalen.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'De "broken record" techniek geeft consistentie zonder escalatie. Harder worden of meer uitleg geven geeft het kind het signaal dat de grens onderhandelbaar is.',
    skillTip: 'Gebruik exact dezelfde woorden. Herhaling signaleert: dit is definitief, niet een opening voor discussie.',
    vermijd: 'Vermijd uitbreiden van je uitleg bij herhaling. Meer woorden = meer twijfel aan de grens.',
    leerdoel: 'Je oefent consequente grenshandhaving zonder escalatie via de herhaalstrategie.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2014). No-Drama Discipline.',
  },
  {
    id: 'gren_02_19',
    title: 'Grens na een conflict bevestigen',
    skill: 'Grenzen',
    description: 'Na een conflict over een grens: ga na de storm even bij je kind zitten. Bevestig de verbinding: "Ik hou van jou. En die grens blijft staan." Beide tegelijk.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Herstel na grensconflict bevestigt dat de grens niet de relatie was. Kinderen leren: ik kan boos zijn op de grens, maar vader houdt nog steeds van mij. Dit is de kern van autoritatief ouderschap.',
    skillTip: 'Wacht tot de storm echt voorbij is. Dan pas het herstelmoment. Te vroeg werkt niet.',
    vermijd: 'Vermijd de grens te verzachten in het herstelmoment. Liefde en grens staan naast elkaar.',
    leerdoel: 'Je leert herstel na grensconflict als bevestiging van zowel liefde als grens.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'gren_02_20',
    title: 'Grens stellen voor je partner',
    skill: 'Grenzen',
    description: 'Bespreek met je partner welke grenzen jullie beiden handhaven bij jullie kind. Stem af: zijn jullie het eens? Maak een kort lijstje van gedeelde grenzen.',
    duration: '15 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Consistentie tussen ouders is één van de sterkste voorspellers van effectieve grenzen. Als de ene ouder ja zegt en de andere nee, leren kinderen de tweede ouder te omzeilen.',
    skillTip: 'Stel samen drie essentiële grenzen op die jullie beiden consequent handhaven. Start klein.',
    vermijd: 'Vermijd de grenzen van je partner ondermijnen voor het kind. Bespreek meningsverschillen altijd buiten zijn bijzijn.',
    leerdoel: 'Je vergroot de consistentie van grenzen via afstemming met je partner.',
    bron: 'Baumrind, D. (1991). The influence of parenting style on adolescent competence.',
  },

  // ─── 3-5 jaar ────────────────────────────────────────────────
  {
    id: 'gren_35_11',
    title: 'Grens uitleggen op zijn niveau',
    skill: 'Grenzen',
    description: 'Kies een grens die je kind regelmatig test. Leg hem uit in woorden die hij begrijpt. Vraag daarna: "Snap jij waarom die grens er is?" Luister naar zijn antwoord.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Grenzen die begrepen worden, worden beter geïnternaliseerd. Kinderen die de reden kennen, zijn meer gemotiveerd om de grens te respecteren vanuit intrinsieke motivatie.',
    skillTip: 'Gebruik zijn taal. Als hij de reden niet begrijpt, probeer een andere uitleg. Begrijpen is het doel.',
    vermijd: 'Vermijd "omdat ik het zeg" als enige uitleg. Dat bouwt gehoorzaamheid maar geen begrip.',
    leerdoel: 'Je bevordert begrip van grenzen als stap naar internalisering.',
    bron: 'Kohlberg, L. (1969). Stage and sequence: The cognitive-developmental approach to socialization.',
  },
  {
    id: 'gren_35_12',
    title: 'Keuzevrijheid binnen de grens',
    skill: 'Grenzen',
    description: 'Geef je kind keuze binnen de grens: "Je moet naar bed, maar je kiest zelf: nu of over vijf minuten?" of "Je eet dit, maar jij bepaalt in welke volgorde."',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Keuzevrijheid binnen grenzen vergroot de compliance doordat het kind zich minder gecontroleerd voelt. De grens staat vast, de uitvoering is flexibel – dat is voldoende voor autonomiegevoelen.',
    skillTip: 'Maak de keuze echt. Beide opties zijn voor jou acceptabel. Valse keuze werkt averechts.',
    vermijd: 'Vermijd keuzes geven over de grens zelf. De grens is niet onderhandelbaar, alleen de uitvoering.',
    leerdoel: 'Je integreert autonomie en grens door keuze te bieden binnen de structuur.',
    bron: 'Deci, E.L. & Ryan, R.M. (1985). Intrinsic Motivation and Self-Determination.',
  },
  {
    id: 'gren_35_13',
    title: 'Nee zeggen bij verzoeken van anderen',
    skill: 'Grenzen',
    description: 'Oefen met je kind het nee zeggen bij vriendjes: "Als een vriend iets vraagt wat je niet wil, mag je gewoon nee zeggen. Dat is jouw recht." Doe het samen na.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kinderen leren dat grenzen ook voor henzelf gelden – niet alleen als regels van vader. Nee mogen zeggen tegen leeftijdgenoten is een sleutel voor gezonde sociale grenzen.',
    skillTip: 'Oefen in een rollenspel. Jij bent het vriendje dat vraagt, hij oefent nee zeggen.',
    vermijd: 'Vermijd hem leren dat hij altijd ja moet zeggen om aardig gevonden te worden. Dat is het tegendeel van grens.',
    leerdoel: 'Je vergroot zijn assertiviteit bij sociale grenzen als basis voor gezonde relaties.',
    bron: 'Alberti, R.E. & Emmons, M.L. (1970). Your Perfect Right: A Guide to Assertive Behavior.',
  },
  {
    id: 'gren_35_14',
    title: 'Zijn lichaamsgrenzen respecteren',
    skill: 'Grenzen',
    description: 'Vraag je kind altijd toestemming voor fysiek contact dat hij misschien niet wil: "Mag ik je knuffelen?" Respecteer zijn antwoord, ook als dat nee is.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Lichaamsautonomie leren via vader die toestemming vraagt, geeft het kind het model van hoe grenzen werken. Het leert ook: jouw nee wordt gerespecteerd.',
    skillTip: 'Als hij nee zegt: zeg "Oké, dat snap ik." En respecteer het volledig. Geen druk of teleurstelling tonen.',
    vermijd: 'Vermijd "maar ik wil je toch even knuffelen." Dat leert dat nee niet echt nee is.',
    leerdoel: 'Je leert lichaamsautonomie respecteren als fundamentele grensles.',
    bron: 'Finkelhor, D. (2009). The prevention of childhood sexual abuse.',
  },
  {
    id: 'gren_35_15',
    title: 'Grenzen bij schermen',
    skill: 'Grenzen',
    description: 'Stel samen met je kind een schermtijdgrens in. Laat hem mee bepalen hoeveel en wanneer. Gebruik een visuele timer. Oefen het samen twee dagen.',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Schermtijdgrenzen waarbij het kind mee mag bepalen, worden beter nageleefd dan opgelegde grenzen. Eigenaarschap vergroot de intrinsieke motivatie om de grens te respecteren.',
    skillTip: 'Gebruik een visuele timer die hij zelf kan zien. Dat geeft hem controle over de aftelling.',
    vermijd: 'Vermijd abrupt stoppen zonder aankondiging. Vijf minuten-waarschuwing maakt de overgang veel soepeler.',
    leerdoel: 'Je leert grenzen rond schermen als gedeeld eigenaarschap in te voeren.',
    bron: 'Deci, E.L. & Ryan, R.M. (1985). Intrinsic Motivation and Self-Determination.',
  },
  {
    id: 'gren_35_16',
    title: 'Grens bij vermoeidheid handhaven',
    skill: 'Grenzen',
    description: 'Kies bewust een moment waarop je moe bent en je kind een grens test. Houd de grens toch aan, ook als het makkelijker is om toe te geven. Merk wat het kost en oplevert.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Grenzen handhaven onder vermoeidheid is de grootste uitdaging maar ook de meest waardevolle oefening. Kinderen testen grenzen juist op momenten van lage weerbaarheid van ouders.',
    skillTip: 'Bereid een standaardzin voor die je kunt gebruiken als je te moe bent om na te denken: "[Naam], mijn antwoord is nee en dat verandert niet."',
    vermijd: 'Vermijd toegeven met de redenering "vandaag even niet". Dat maakt morgen moeilijker.',
    leerdoel: 'Je versterkt grenshandhaving onder vermoeidheid als duurzame vaardigheid.',
    bron: 'Baumeister, R.F. et al. (1998). Ego depletion: Is the active self a limited resource?',
  },
  {
    id: 'gren_35_17',
    title: 'Grens met empathie stellen',
    skill: 'Grenzen',
    description: 'Stel een grens, maar begin altijd met erkenning van zijn wens: "Ik snap dat je dit wil. Dat zou ik ook willen. En toch is het antwoord nee, want..."',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Empathische grenzen (eerst erkennen, dan stellen) verminderen de weerstand significant. Het kind voelt zich begrepen voordat de teleurstelling van de grens aankomt.',
    skillTip: 'Oefen de formule: "[Naam], ik snap dat je [wens]. En de grens is [grens]." Twee stappen, altijd in die volgorde.',
    vermijd: 'Vermijd de empathie als manipulatie gebruiken. Het moet oprecht zijn, niet als techniek.',
    leerdoel: 'Je integreert empathie als opening voor grenzen in plaats van als afwending ervan.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'gren_35_18',
    title: 'Wat is een eerlijke grens?',
    skill: 'Grenzen',
    description: 'Vraag je kind na een grensmoment: "Vond jij die grens eerlijk?" Luister naar zijn antwoord zonder te verdedigen. Je hoeft het er niet mee eens te zijn, maar je hoort hem.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kinderen bevragen op hun beleving van grenzen vergroot zijn gevoel van eerlijkheid en gehoordheid, zelfs als de grens blijft staan. Participatie in evaluatie vergroot acceptatie.',
    skillTip: 'Als hij zegt "nee, het was niet eerlijk" – erken dat hij dat zo beleeft. Dan: leg je perspectief uit.',
    vermijd: 'Vermijd het gesprek gebruiken om je gelijk te halen. Luisteren is het doel.',
    leerdoel: 'Je bevordert zijn betrokkenheid bij grenzen via evaluatiegesprekken.',
    bron: 'Thibaut, J.W. & Walker, L. (1975). Procedural Justice: A Psychological Analysis.',
  },
  {
    id: 'gren_35_19',
    title: 'Grens bij anderen verdedigen',
    skill: 'Grenzen',
    description: 'Als iemand anders (opa, oma, vriend) jouw grens voor je kind overschrijdt: verdedig de grens vriendelijk maar duidelijk. "Wij doen dat anders bij ons thuis." Dit voor zijn ogen.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Vader die zijn eigen grenzen verdedigt voor anderen laat het kind zien hoe grenzen werken in sociale contexten. Dit is een krachtig model voor assertiviteit.',
    skillTip: 'Kies je woorden vriendelijk maar zeker: "Wij kiezen ervoor dat... maar dank je." Geen discussie nodig.',
    vermijd: 'Vermijd de grens laten varen uit sociale ongemakkelijkheid. Dat ondermijnt het model dat je wil geven.',
    leerdoel: 'Je modelleert grenshandhaving in sociale situaties als assertiviteitsles.',
    bron: 'Alberti, R.E. & Emmons, M.L. (1970). Your Perfect Right.',
  },
  {
    id: 'gren_35_20',
    title: 'Grens evalueren na een week',
    skill: 'Grenzen',
    description: 'Kijk na een week terug op een grens die je hebt gesteld. Hoe consequent was je? Wat maakt het moeilijk? Wat helpt? Schrijf drie lessen op voor jezelf.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Reflectie op eigen grensgedrag is de snelste weg naar verbetering. Vaders die hun eigen consequentie evalueren, worden aantoonbaar consistenter over tijd.',
    skillTip: 'Wees eerlijk. Als je de grens vijf keer niet hield: schrijf op waarom. Dat is de leerinformatie.',
    vermijd: 'Vermijd jezelf veroordelen. Evaluatie is leren, niet straffen.',
    leerdoel: 'Je vergroot de kwaliteit van grenzen via bewuste zelfevaluatie.',
    bron: 'Schön, D.A. (1983). The Reflective Practitioner.',
  },

  // ─── 6-9 jaar ────────────────────────────────────────────────
  {
    id: 'gren_69_11',
    title: 'Grenzen onderhandelen',
    skill: 'Grenzen',
    description: 'Kies een grens die bespreekbaar is en onderhandel met je kind: "Ik wil X, jij wil Y. Wat kunnen we allebei accepteren?" Zoek samen een oplossing.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Onderhandelbare grenzen leren kinderen conflictresolutievaardigheden. Ze ervaren dat regels niet willekeurig zijn maar gebaseerd op behoeften van beiden.',
    skillTip: 'Maak duidelijk welke grenzen onderhandelbaar zijn en welke niet. Die duidelijkheid vergroot zijn bereidheid te onderhandelen.',
    vermijd: 'Vermijd alle grenzen onderhandelbaar te maken. Sommige zijn vast – die bewaar je ook zo.',
    leerdoel: 'Je leert onderhandelen als een respectvolle manier om grenzen gezamenlijk te bepalen.',
    bron: 'Fisher, R. & Ury, W. (1981). Getting to Yes: Negotiating Agreement Without Giving In.',
  },
  {
    id: 'gren_69_12',
    title: 'Grenzen van vriendjes bespreken',
    skill: 'Grenzen',
    description: 'Bespreek met je kind: "Wat doe jij als een vriend iets doet wat jij niet wil?" Oefen samen wat hij kan zeggen. Maak het concreet en herhaalbaar.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Grenzen stellen bij leeftijdgenoten is voor kinderen van 6-9 een cruciale sociale vaardigheid. Zonder deze skill worden ze eerder gepest of bewegen ze mee met druk.',
    skillTip: 'Geef hem een concrete zin: "Ik wil dit niet." Of: "Dat doe ik niet mee." Eenvoudig en duidelijk.',
    vermijd: 'Vermijd hem leren dat hij altijd uitleggen moet. Nee is een compleet antwoord.',
    leerdoel: 'Je geeft je kind concrete taal voor het stellen van grenzen bij leeftijdgenoten.',
    bron: 'Alberti, R.E. & Emmons, M.L. (1970). Your Perfect Right.',
  },
  {
    id: 'gren_69_13',
    title: 'Grenzen van jou uitleggen',
    skill: 'Grenzen',
    description: 'Deel met je kind een eigen grens: "Voor mij is het belangrijk dat... omdat ik anders..." Laat zien dat ook jij grenzen hebt en dat die respectvol gecommuniceerd worden.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Vader die zijn eigen grenzen communiceert, modelleert assertieve zelfexpressie. Het kind leert dat grenzen voor iedereen gelden en eerlijk gecommuniceerd worden.',
    skillTip: 'Kies een echte grens die hij kent. "Als ik aan het bellen ben, wil ik even niet gestoord worden. Dat is mijn grens."',
    vermijd: 'Vermijd grenzen als macht framen. Grenzen zijn behoeften, geen controle.',
    leerdoel: 'Je modelleert assertieve grensexpressie vanuit behoeften als rolmodel.',
    bron: 'Rosenberg, M.B. (2003). Nonviolent Communication.',
  },
  {
    id: 'gren_69_14',
    title: 'Grens versus voorkeur onderscheiden',
    skill: 'Grenzen',
    description: 'Leg je kind het onderscheid uit: een grens is iets wat niet mag (veiligheid, respect), een voorkeur is iets wat jij liever wil maar flexibel is. Geef voorbeelden van beide.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kinderen die het onderscheid tussen echte grenzen en voorkeuren leren, begrijpen beter wanneer nee echt nee is. Dit vergroot hun begrip van autoriteit en eerlijkheid.',
    skillTip: 'Vraag hem voorbeelden te geven van elk. Dat test zijn begrip en verdiept het.',
    vermijd: 'Vermijd alles een grens noemen. Dat verwatert het concept. Wees precies.',
    leerdoel: 'Je vergroot zijn begrip van het onderscheid tussen grenzen en voorkeuren.',
    bron: 'Baumrind, D. (1991). The influence of parenting style on adolescent competence.',
  },
  {
    id: 'gren_69_15',
    title: 'Grens via spelregel oefenen',
    skill: 'Grenzen',
    description: 'Speel een spel waarbij hij de regels bedenkt en jij je eraan houdt. Daarna wissel je: jij bepaalt de regels. Bespreek: hoe voelt het als regels niet gerespecteerd worden?',
    duration: '20 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Spelregels zijn veilige grenzen. Kinderen die ervaren dat hun regels gerespecteerd worden, ontwikkelen respect voor andermans regels. Wederzijdigheid wordt aangeleerd via spel.',
    skillTip: 'Maak het reëel. Als hij een regel maakt die jij moet volgen, volg die dan echt.',
    vermijd: 'Vermijd spel gebruiken om regels op te leggen. Laat hem echt de regels bepalen.',
    leerdoel: 'Je oefent wederzijds respect voor grenzen via spelregels.',
    bron: 'Piaget, J. (1932). The Moral Judgment of the Child.',
  },
  {
    id: 'gren_69_16',
    title: 'Gevolgen versus straffen uitleggen',
    skill: 'Grenzen',
    description: 'Bespreek het onderscheid: een consequentie volgt logisch uit het gedrag (buiten blijven zonder jas = koud), een straf is willekeurig (geen tv omdat je ruzie maakte). Geef voorbeelden.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Logische consequenties zijn effectiever en eerlijker dan willekeurige straffen. Kinderen begrijpen ze beter en leren meer van de situatie zelf dan van de straf.',
    skillTip: 'Toets elke consequentie: is die logisch verbonden met het gedrag? Zo ja: prima. Zo nee: bedenk iets anders.',
    vermijd: 'Vermijd consequenties die niets met het gedrag te maken hebben. "Geen speeltijd omdat je je kamer niet opruimde" is logischer dan "geen tv".',
    leerdoel: 'Je vergroot de logica en eerlijkheid van grenzen via consequenties in plaats van straffen.',
    bron: 'Dreikurs, R. & Grey, L. (1968). A New Approach to Discipline: Logical Consequences.',
  },
  {
    id: 'gren_69_17',
    title: 'Zijn grens respecteren',
    skill: 'Grenzen',
    description: 'Als je kind een grens aangeeft (wil niet geknuffeld worden, wil even alleen zijn, wil niet meedoen): respecteer die volledig. Zeg: "Oké, ik hoor je."',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Zijn grenzen respecteren leert het kind dat grenzen in beide richtingen werken. Dit is essentieel voor het ontwikkelen van gezonde sociale grenzen en relaties.',
    skillTip: 'Als je teleurgesteld bent: verberg dat niet helemaal, maar leg het niet op hem. "Ik vind het jammer, maar ik begrijp het."',
    vermijd: 'Vermijd puppy-ogen trekken of hem schuldig laten voelen. Zijn grens is zijn grens.',
    leerdoel: 'Je ervaart hoe zijn grenzen respecteren het hele grenzen-concept verdiept.',
    bron: 'Finkelhor, D. (2009). The prevention of childhood sexual abuse.',
  },
  {
    id: 'gren_69_18',
    title: 'Grens stellen via brief',
    skill: 'Grenzen',
    description: 'Als er een grens is die moeilijk te bespreken is: schrijf hem een briefje. "Dit is voor mij een grens omdat... Ik vraag je om..." Geef het hem en bespreek het daarna.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Geschreven communicatie van grenzen geeft het kind tijd om de boodschap te verwerken voor het gesprek begint. Dit verlaagt de emotionele drempel voor moeilijke grensgesprekken.',
    skillTip: 'Gebruik ik-boodschappen in de brief. Geen aanklacht, alleen jouw behoefte en verzoek.',
    vermijd: 'Vermijd de brief als vervanging van het gesprek. Het is een opening, geen afsluiting.',
    leerdoel: 'Je leert grenzen ook schriftelijk te communiceren voor moeilijkere situaties.',
    bron: 'Rosenberg, M.B. (2003). Nonviolent Communication.',
  },
  {
    id: 'gren_69_19',
    title: 'Grens bij schaamte bespreken',
    skill: 'Grenzen',
    description: 'Als je kind iets doet waarvoor hij zich schaamt (kleine leugen, iets stiekem gepakt): stel de grens zonder hem te beschamen. "Dit mag niet. Ik hou nog steeds van je."',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Schaamte-inductie bij grensoverschrijding beschadigt de relatie en stimuleert verbergen, niet leren. Grens stellen zonder schaamte behoudt de relatie én de les.',
    skillTip: 'Gebruik ik-boodschappen: "Ik ben teleurgesteld" is anders dan "jij bent stout." Het eerste is informatie, het tweede is schaamte.',
    vermijd: 'Vermijd: "Hoe kon je?", "Jij bent altijd...", "Schaam jij je niet?" – dit induceert schaamte.',
    leerdoel: 'Je leert grenzen te stellen zonder schaamte te induceren.',
    bron: 'Brown, B. (2012). Daring Greatly.',
  },
  {
    id: 'gren_69_20',
    title: 'Grens als liefde benoemen',
    skill: 'Grenzen',
    description: 'Leg je kind uit dat grenzen een vorm van liefde zijn: "Ik stel grenzen omdat ik van je hou en voor je wil zorgen. Zonder grenzen zou ik je geen richting geven."',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Grenzen als liefde framen verplaatst de beleving van controle naar zorg. Kinderen die dit begrijpen, ervaren grenzen als ondersteuning in plaats van als beperking.',
    skillTip: 'Gebruik concrete voorbeelden: "Ik zeg nee aan snoep voor het eten omdat ik wil dat jij gezond bent. Dat is liefde."',
    vermijd: 'Vermijd dit als manipulatie gebruiken om elke grens goed te praten. Het is een uitleg van het principe, geen vrijbrief.',
    leerdoel: 'Je verbindt grenzen met liefde als fundamenteel begripskader voor je kind.',
    bron: 'Fromm, E. (1956). The Art of Loving.',
  },

  // ─── 10-12 jaar ──────────────────────────────────────────────
  {
    id: 'gren_1012_11',
    title: 'Grensgesprek bij toenemende vrijheid',
    skill: 'Grenzen',
    description: 'Bespreek met je kind van 10-12 hoe vrijheid en verantwoordelijkheid samengaan. "Hoe meer je laat zien dat je verantwoordelijk bent, hoe meer vrijheid ik je kan geven." Maak dat concreet.',
    duration: '20 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Het verbinden van vrijheid aan verantwoordelijkheid is een kernboodschap van autoritatief ouderschap. Kinderen die dit begrijpen, zijn intrinsieker gemotiveerd om verantwoordelijk te zijn.',
    skillTip: 'Maak het meetbaar: "Als je [concreet gedrag] laat zien, geef ik je meer ruimte bij [concreet iets]."',
    vermijd: 'Vermijd het als dreigement framen. Het is een ontwikkelingspad, geen transactie.',
    leerdoel: 'Je verbindt vrijheid en verantwoordelijkheid als complementaire grondbeginselen.',
    bron: 'Baumrind, D. (1991). The influence of parenting style on adolescent competence.',
  },
  {
    id: 'gren_1012_12',
    title: 'Grenzen rondom privéruimte',
    skill: 'Grenzen',
    description: 'Bespreek met je pre-puber zijn behoefte aan privacy: zijn kamer, zijn berichten, zijn dagboek. Maak duidelijke afspraken: wat respecteer jij, wat verwacht je van hem?',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Privacy is een ontwikkelingsrecht dat toeneemt in de pre-puberteit. Vader die privacy respecteert, bouwt vertrouwen. Vader die het schendt, beschadigt de communicatie.',
    skillTip: 'Klop altijd aan. Wacht op antwoord. Ook als de deur open is. Dat toont respect.',
    vermijd: 'Vermijd zijn telefoon of berichten stiekem lezen. Als je zorgen hebt: bespreek die direct.',
    leerdoel: 'Je erkent privacy als ontwikkelingsrecht en maakt duidelijke grenzen rondom wederzijds respect.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'gren_1012_13',
    title: 'Grens bij pestgedrag',
    skill: 'Grenzen',
    description: 'Als je kind gepest wordt of iemand pest: bespreek de grens. "Wat is voor jou een grens in hoe anderen met je omgaan? Hoe stel je die?" Of: "Waarom ga je over iemands grens?"',
    duration: '20 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Pesten is een grensprobleem: de pester overschrijdt grenzen, het slachtoffer mist vaardigheden om grenzen te stellen. Beide perspectieven vragen om grensontwikkeling.',
    skillTip: 'Luister volledig voor je reageert. Begrijp eerst wat er speelt, dan pas praten over grenzen.',
    vermijd: 'Vermijd het bagatelliseren of overdramatiseren. Neem zijn ervaring serieus en werk van daaruit.',
    leerdoel: 'Je adresseert pesten als grensprobleem en helpt hem zijn grenstaal te versterken.',
    bron: 'Olweus, D. (1993). Bullying at School: What We Know and What We Can Do.',
  },
  {
    id: 'gren_1012_14',
    title: 'Online grenzen bespreken',
    skill: 'Grenzen',
    description: 'Bespreek concrete online grenzen: wat deel je niet? Wat doe je als iemand online grensoverschrijdend is? Oefen samen wat hij kan zeggen of doen.',
    duration: '20 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Online grensoverschrijding is een van de meest voorkomende veiligheidsrisico\'s voor kinderen van 10-12. Concrete vaardigheidstraining is effectiever dan alleen het benoemen van gevaren.',
    skillTip: 'Leer hem: blokkeer, rapporteer, vertel het aan een volwassene. In die volgorde. Maak het concreet.',
    vermijd: 'Vermijd alleen de gevaren benoemen zonder vaardigheidstraining. Angst zonder handelen helpt niet.',
    leerdoel: 'Je geeft je kind concrete vaardigheden voor online grenshandhaving.',
    bron: 'Livingstone, S. & Helsper, E. (2008). Parental mediation of children\'s internet use.',
  },
  {
    id: 'gren_1012_15',
    title: 'Grens bij prestatiedruk',
    skill: 'Grenzen',
    description: 'Bespreek met je kind de grens van prestaties: "Hoeveel is genoeg? Wanneer zeg jij tegen jezelf: dit was goed genoeg?" Help hem zijn eigen lat te definiëren.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Interne prestatiegrenzen beschermen tegen perfectionisme en burn-out. Kinderen die hun eigen "goed genoeg" kunnen definiëren, zijn weerbaarder onder druk.',
    skillTip: 'Geef een ander woordkader: niet "goed genoeg" als minpunt, maar als grens van gezonde inspanning.',
    vermijd: 'Vermijd dit gebruiken om zijn ambitie te temperen. Het gaat om een gezonde bovenkant, niet een lagere standaard.',
    leerdoel: 'Je helpt je kind een interne prestatiesgrens definiëren als bescherming tegen perfectionisme.',
    bron: 'Neff, K. (2011). Self-Compassion.',
  },
  {
    id: 'gren_1012_16',
    title: 'Grens stellen aan zichzelf',
    skill: 'Grenzen',
    description: 'Help je kind een zelfgestelde grens formuleren in iets waar hij moeite mee heeft (gamen, snoepen, uitstellen). Vraag hem: "Wat is jouw grens? En hoe weet je dat je hem overschrijdt?"',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Zelfgestelde grenzen zijn de basis van zelfregulatie en intrinsieke motivatie. Kinderen die hun eigen grenzen formuleren, houden ze significant beter aan dan opgelegde regels.',
    skillTip: 'Vraag: "Hoe voel je je als je die grens overschrijdt?" Dat verbindt de grens met zijn eigen waarden.',
    vermijd: 'Vermijd zijn grens voor hem bepalen. Jouw grens is niet zijn grens.',
    leerdoel: 'Je stimuleert zelfgestelde grenzen als kern van intrinsieke zelfregulatie.',
    bron: 'Deci, E.L. & Ryan, R.M. (2000). Self-Determination Theory.',
  },
  {
    id: 'gren_1012_17',
    title: 'Grens bij ruzies in het gezin',
    skill: 'Grenzen',
    description: 'Stel samen met je kind een "ruzie-grens" vast: wat mag en wat mag niet als er ruzie is? (Schreeuwen, deuren slaan, beledigende woorden). Wat zijn jullie gezamenlijke afspraken?',
    duration: '20 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Expliciete afspraken over conflict-grenzen geven kinderen een kader voor emotionele expressie dat zowel vrij als begrensd is. Ze leren: boosheid mag, gedrag heeft grenzen.',
    skillTip: 'Laat hem mee formuleren. Zijn eigen woorden in de afspraak vergroot zijn eigenaarschap.',
    vermijd: 'Vermijd eenzijdige regels opstellen. Maak het wederzijds – ook jij houdt je eraan.',
    leerdoel: 'Je creëert gezamenlijke afspraken over de grenzen van conflictgedrag.',
    bron: 'Gottman, J. (1994). Why Marriages Succeed or Fail.',
  },
  {
    id: 'gren_1012_18',
    title: 'Nee zeggen aan jou oefenen',
    skill: 'Grenzen',
    description: 'Geef je kind expliciete toestemming om nee te zeggen tegen jou als hij iets echt niet wil. Laat zien dat je dat respecteert. Oefen samen een situatie.',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Kinderen die mogen nee zeggen tegen hun ouder (op respectvolle manier) leren dat grenzen voor iedereen gelden en dat jouw liefde niet afhankelijk is van hun gehoorzaamheid.',
    skillTip: 'Maak duidelijk: nee zeggen mag, maar respectvol. "Nee" of "Ik wil dit niet" – geen schreeuwen of belediging.',
    vermijd: 'Vermijd gekwetst reageren als hij nee zegt. Dat is precies wat je wil bereiken.',
    leerdoel: 'Je geeft je kind toestemming om grenzen te stellen naar jou als model voor alle relaties.',
    bron: 'Alberti, R.E. & Emmons, M.L. (1970). Your Perfect Right.',
  },
  {
    id: 'gren_1012_19',
    title: 'Grenzen en vriendschappen',
    skill: 'Grenzen',
    description: 'Bespreek met je kind: "Hoe weet je of een vriend jouw grenzen respecteert? Wat doe je als dat niet zo is?" Help hem criteria voor gezonde vriendschappen te formuleren.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Grenzen in vriendschappen zijn een sleutelcomponent van sociale competentie. Kinderen die dit vroeg leren, kiezen gezondere relaties en zijn minder kwetsbaar voor groepsdruk.',
    skillTip: 'Vraag: "Noem een vriend die jouw grenzen respecteert. Hoe merk je dat?" Positief model is krachtig.',
    vermijd: 'Vermijd zijn vrienden beoordelen. Help hem criteria te formuleren, niet conclusies.',
    leerdoel: 'Je versterkt zijn vermogen om gezonde vriendschappen te herkennen via grenscriteria.',
    bron: 'Rubin, K.H. et al. (2006). Peer interactions, relationships, and groups.',
  },
  {
    id: 'gren_1012_20',
    title: 'Grens via ik-boodschappen',
    skill: 'Grenzen',
    description: 'Leer je kind grenzen te communiceren via ik-boodschappen: "Als jij [gedrag] doet, voel ik mij [gevoel], en ik vraag je [verzoek]." Oefen samen drie situaties.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Ik-boodschappen zijn een bewezen communicatietechniek voor assertieve grensexpressie. Ze verminderen defensiviteit bij de ander en vergroten de kans op gedragsverandering.',
    skillTip: 'Oefen tot hij de formule uit zijn hoofd kent. Dan is het beschikbaar als hij het nodig heeft.',
    vermijd: 'Vermijd jij-boodschappen ("jij doet altijd..."). Die zijn aanklachten, geen grenzen.',
    leerdoel: 'Je geeft je kind de taal voor assertieve, respectvolle grensexpressie.',
    bron: 'Gordon, T. (1970). Parent Effectiveness Training.',
  },

  // ─── 13-16 jaar ──────────────────────────────────────────────
  {
    id: 'gren_1316_11',
    title: 'Grensgesprek over vrijheid',
    skill: 'Grenzen',
    description: 'Bespreek eerlijk met je tiener welke vrijheden hij nu heeft en welke hij wil. Luister echt. Onderbouw jouw grenzen. Zoek samen naar een eerlijk midden.',
    duration: '20 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Tieners die het gevoel hebben dat grenzen eerlijk zijn en dat hun stem telt, accepteren grenzen aanzienlijk beter dan tieners die grenzen als willekeurig ervaren.',
    skillTip: 'Stel de vraag: "Welke grens vind jij onredelijk en waarom?" Luister echt en overweeg zijn punt.',
    vermijd: 'Vermijd "omdat ik het zeg" als enige argument. Dat is gezagsmisbruik, geen grens.',
    leerdoel: 'Je ervaart hoe eerlijkheid in het grensgesprek de acceptatie vergroot.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'gren_1316_12',
    title: 'Grens bij digitale privacy',
    skill: 'Grenzen',
    description: 'Bespreek jullie wederzijdse digitale grenzen: wat verwacht jij van hem (geen nachtelijk schermgebruik), wat verwacht hij van jou (geen stiekem kijken in zijn telefoon)?',
    duration: '20 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Wederzijdse digitale grenzen vergroten het vertrouwen en de bereidheid van tieners om transparant te zijn. Eenzijdige controle zonder vertrouwen leidt tot meer verbergen.',
    skillTip: 'Maak de afspraken schriftelijk. Dat geeft beide partijen een referentiepunt.',
    vermijd: 'Vermijd stiekem monitoren. Als je zorgen hebt over online veiligheid: bespreek het openlijk.',
    leerdoel: 'Je creëert wederzijdse digitale grensafspraken op basis van vertrouwen.',
    bron: 'Twenge, J.M. (2017). iGen.',
  },
  {
    id: 'gren_1316_13',
    title: 'Grens bij riskant gedrag',
    skill: 'Grenzen',
    description: 'Bespreek riskant gedrag (alcohol, roken, sexting, gevaarlijk rijden) eerlijk en zonder moraliseren. Wat zijn jouw grenzen? Wat zijn zijn? Hoe communiceer je die aan vrienden?',
    duration: '20 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Open gesprekken over riskant gedrag zonder moraliseren zijn bewezen effectiever dan verbods-gebaseerde aanpak. Tieners die kunnen praten, zijn beter beschermd.',
    skillTip: 'Begin met vragen, niet met standpunten. "Wat denk jij over...?" geeft meer dan "zo is het."',
    vermijd: 'Vermijd schrikken van zijn antwoorden. Als hij eerlijk is, is dat goed. Waardeer die eerlijkheid.',
    leerdoel: 'Je opent een eerlijk gesprek over risico en grens zonder de verbinding te verliezen.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'gren_1316_14',
    title: 'Zijn grens respecteren bij aanraking',
    skill: 'Grenzen',
    description: 'Vraag altijd toestemming voor fysiek contact met je tiener: "Mag ik je even omhelzen?" Respecteer zijn antwoord. Zorg dat hij voelt dat zijn lichaam van hem is.',
    duration: '5 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Lichaamsautonomie respecteren bij tieners is fundamenteel voor gezonde grenzenontwikkeling. Vader die dit respecteert, leert zijn kind dat zijn lichaam altijd zijn eigen is.',
    skillTip: 'Als hij nee zegt: zeg "Oké" en ga verder. Geen uitleg, geen teleurstelling tonen.',
    vermijd: 'Vermijd "maar je bent mijn kind." Zijn lichaam is van hem, op elke leeftijd.',
    leerdoel: 'Je modelleert lichaamsautonomie als fundamenteel recht voor je tiener.',
    bron: 'Finkelhor, D. (2009). The prevention of childhood sexual abuse.',
  },
  {
    id: 'gren_1316_15',
    title: 'Grenzen in de liefde bespreken',
    skill: 'Grenzen',
    description: 'Bespreek met je tiener wat gezonde grenzen zijn in romantische relaties. Wat mag je van elkaar vragen? Wat is grensoverschrijding? Hoe zeg je nee aan iemand die je leuk vindt?',
    duration: '20 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Grenzen in romantische relaties zijn een van de meest urgente vaardigheidslacunes bij tieners. Vader die dit openlijk bespreekt, geeft zijn kind een beschermende vaardigheid.',
    skillTip: 'Begin met jouw eigen jeugdervaringen. Dat maakt het minder bedreigend en meer verbindend.',
    vermijd: 'Vermijd seksuele ethiek als verbod te behandelen. Bespreek het als vaardigheid en zelfrespect.',
    leerdoel: 'Je bespreekt grenzen in romantische relaties als essentiële vaardigheid.',
    bron: 'Tolman, D.L. (2002). Dilemmas of Desire: Teenage Girls Talk about Sexuality.',
  },
  {
    id: 'gren_1316_16',
    title: 'Grens na grensoverschrijding herstellen',
    skill: 'Grenzen',
    description: 'Als jij een grens van je tiener overschreed (te ver gegaan in een conflict, schreeuwde, iets inzag wat privé was): erken het. Bied echte excuses aan zonder het goed te praten.',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Vader die zijn eigen grensoverschrijding erkent, toont dat grenzen voor iedereen gelden en dat herstel mogelijk is. Dit is het meest krachtige grensmodel dat er is.',
    skillTip: 'Een echt excuus bevat: erkenning van het gedrag, erkenning van de impact, en geen "maar".',
    vermijd: 'Vermijd half-excuus: "Sorry als je je zo voelt." Dat is geen erkenning van grensoverschrijding.',
    leerdoel: 'Je modelleert verantwoordelijkheid na grensoverschrijding als volwassen grensgedrag.',
    bron: 'Brown, B. (2012). Daring Greatly.',
  },
  {
    id: 'gren_1316_17',
    title: 'Grenzen aanpassen naarmate hij ouder wordt',
    skill: 'Grenzen',
    description: 'Bespreek welke grenzen dit jaar anders zijn dan vorig jaar. Wat heeft hij verdiend? Wat heeft hij aangetoond? Maak de evolutie van grenzen expliciet en positief.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Grenzen die groeien met het kind bevestigen dat vertrouwen verdient kan worden. Dit stimuleert verantwoordelijk gedrag sterker dan vaste, onveranderlijke regels.',
    skillTip: 'Benoem concreet: "Vorig jaar was [grens]. Nu vertrouw ik je meer op [gebied] omdat je [gedrag] liet zien."',
    vermijd: 'Vermijd grenzen versoepelen zonder reden. Het moet gekoppeld zijn aan zichtbaar gedrag.',
    leerdoel: 'Je maakt grenzenevolutie expliciet en koppelt vrijheid aan aangetoond vertrouwen.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'gren_1316_18',
    title: 'Grenzen bij conflict met regels',
    skill: 'Grenzen',
    description: 'Als je tiener met regels in conflict komt (thuis, op school): bespreek het. "Wat vind jij oneerlijk? Hoe kun je die grens respecteren ook als je er niet mee eens bent?"',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Leren omgaan met regels die je oneerlijk vindt is een cruciale burgerschapsvaardigheid. Vader die dit serieus bespreekt, leert zijn kind sociaal functioneren en constructief verzet.',
    skillTip: 'Maak onderscheid: regels kunnen aangevochten worden – via gesprek, niet door ze te negeren.',
    vermijd: 'Vermijd altijd partij kiezen voor de regels óf voor hem. Verken het samen.',
    leerdoel: 'Je leert je tiener omgaan met grenzen en regels die hij oneerlijk vindt.',
    bron: 'Kohlberg, L. (1969). Stage and sequence.',
  },
  {
    id: 'gren_1316_19',
    title: 'Grens stellen aan schuldgevoel',
    skill: 'Grenzen',
    description: 'Als je tiener schuldgevoel als instrument gebruikt om grenzen te overschrijden ("als jij van me hield, dan..."): benoem het. "Dat is manipulatie. Ik hou van je én mijn grens blijft."',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Schuldgebaseerde manipulatie is een veelvoorkomend patroon in tienerrelaties. Vader die het benoemt en zijn grens toch houdt, leert zijn kind: liefde en grens kunnen naast elkaar bestaan.',
    skillTip: 'Zeg het rustig en liefdevol. "Ik hoor dat je dit zegt. En mijn grens blijft." Geen conflict, alleen helderheid.',
    vermijd: 'Vermijd het escaleren of aanvallen. Benoem het neutraal en houd de grens warm maar vast.',
    leerdoel: 'Je leert grens houden bij emotionele manipulatie als assertiviteitsles.',
    bron: 'Alberti, R.E. & Emmons, M.L. (1970). Your Perfect Right.',
  },
  {
    id: 'gren_1316_20',
    title: 'Grenzen voor zijn toekomst',
    skill: 'Grenzen',
    description: 'Bespreek met je tiener: als hij straks alleen woont, welke grenzen wil hij dan voor zichzelf instellen? Slaap, geld, relaties, werk. Help hem nadenken over zijn eigen kader.',
    duration: '20 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Proactief nadenken over toekomstige zelfgestelde grenzen vergroot de autonome regulatiecapaciteit. Tieners die dit oefenen, zijn beter voorbereid op zelfstandig leven.',
    skillTip: 'Vraag: "Als jij je eigen baas bent – welke regels geef jij dan aan jezelf?" Maak het zijn verbeelding.',
    vermijd: 'Vermijd je eigen waarden hier opleggen. Zijn toekomstige grenzen zijn van hem.',
    leerdoel: 'Je stimuleert toekomstgerichte zelfregulatiegrenzen als voorbereiding op autonomie.',
    bron: 'Arnett, J.J. (2000). Emerging adulthood.',
  },
];
