import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_3: InteractiveTask[] = [
  // ═══════════════════════════════════════════════════════════════
  // HERSTEL (50 taken: 5 leeftijdsgroepen × 10 taken)
  // ═══════════════════════════════════════════════════════════════

  // ── Herstel · 0-2 jaar ────────────────────────────────────
  {
    id: "hers_02_01",
    title: "Troost na frustratie",
    skill: "Herstel",
    description: "Na een moment van ongeduld, pak je baby op en zeg rustig: 'Sorry schatje, papa was even niet lief.'",
    duration: "2 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Repair attempts na misafstemming versterken de hechtingsrelatie. Het kind leert: ook als het even fout gaat, komt het weer goed.",
    skillTip: "Wacht niet te lang met herstellen — doe het zodra je het merkt.",
    vermijd: "Doen alsof er niets gebeurd is — kinderen voelen spanning.",
    leerdoel: "Je leert om na een fout actief de verbinding te herstellen.",
    bron: "Tronick (2007) - Still Face Experiment & repair sequences",
  },
  {
    id: "hers_02_02",
    title: "Zachte stem na harde toon",
    skill: "Herstel",
    description: "Als je per ongeluk te hard reageerde, ga op ooghoogte van je baby zitten en praat met een warme, zachte stem. Streel over het hoofdje.",
    duration: "3 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "De toon van je stem activeert het autonome zenuwstelsel van je baby. Een zachte toon na stress helpt het kind terug naar een rustige staat.",
    skillTip: "Focus eerst op je eigen ademhaling voordat je naar je baby gaat — je kalmte is besmettelijk.",
    vermijd: "Overdreven vrolijk doen om te compenseren — dat voelt onecht.",
    leerdoel: "Je leert om je stemtoon bewust in te zetten als herstelmiddel.",
    bron: "Porges (2011) - Polyvagal Theory & prosody",
  },
  {
    id: "hers_02_03",
    title: "Lichamelijk herstel na afwezigheid",
    skill: "Herstel",
    description: "Na een periode van afwezigheid (werk, telefoon), pak je baby op en houd het stevig vast. Zeg: 'Papa is er weer, helemaal voor jou.'",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Fysiek contact na afwezigheid heractivateert het hechtingssysteem. Oxytocine komt vrij bij huid-op-huidcontact.",
    skillTip: "Leg je telefoon bewust weg voordat je contact maakt — volledig aanwezig zijn is het herstel.",
    vermijd: "Terugkomen en meteen doorlopen naar de volgende taak.",
    leerdoel: "Je leert om terugkeermomenten bewust te gebruiken als verbindingskans.",
    bron: "Bowlby (1969) - Attachment & separation-reunion cycles",
  },
  {
    id: "hers_02_04",
    title: "Hersteldans",
    skill: "Herstel",
    description: "Na een huilbui die je niet meteen beantwoordde, neem je baby in je armen en wieg zachtjes heen en weer op een rustig ritme.",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Ritmische beweging activeert het vestibulaire systeem en helpt bij co-regulatie. Het kind ervaart: papa helpt mij weer rustig worden.",
    skillTip: "Gebruik een langzaam, voorspelbaar ritme — dit kalmeert het zenuwstelsel het beste.",
    vermijd: "Snel of chaotisch bewegen wanneer je baby al overstuur is.",
    leerdoel: "Je leert om fysieke beweging in te zetten als herstelstrategie bij je baby.",
    bron: "Winnicott (1960) - Holding environment & physical containment",
  },
  {
    id: "hers_02_05",
    title: "Oogcontact herstellen",
    skill: "Herstel",
    description: "Wanneer je merkt dat je baby je vermijdt na een stressvol moment, zoek rustig oogcontact. Glimlach zacht en wacht geduldig.",
    duration: "3 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Oogcontact is de primaire hechtingsroute in het eerste levensjaar. Herstellend oogcontact na stress bouwt vertrouwen opnieuw op.",
    skillTip: "Dwing geen oogcontact af — bied het aan en wacht tot je baby er klaar voor is.",
    vermijd: "Te dicht bij het gezicht van je baby komen als die nog overstuur is.",
    leerdoel: "Je leert geduldig te wachten tot je kind klaar is voor herverbinding.",
    bron: "Stern (1985) - The Interpersonal World of the Infant & affect attunement",
  },
  {
    id: "hers_02_06",
    title: "Troostliedje na spanning",
    skill: "Herstel",
    description: "Zing een vertrouwd slaapliedje of wiegelied na een moment van onrust in huis. Houd je baby dicht bij je borst terwijl je zingt.",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Vertrouwde melodieën activeren het parasympathische zenuwstelsel. De combinatie van stem, ritme en nabijheid biedt drievoudig herstel.",
    skillTip: "Het hoeft niet mooi te klinken — je baby herkent jouw stem en dat is genoeg.",
    vermijd: "Harde of onbekende muziek als herstelpoging — dat kan overprikkelen.",
    leerdoel: "Je leert meerdere zintuigen tegelijk in te zetten voor emotioneel herstel.",
    bron: "Trehub (2001) - Infant-directed singing & emotional regulation",
  },
  {
    id: "hers_02_07",
    title: "Rustig terugkeren na time-out",
    skill: "Herstel",
    description: "Als je even de kamer uit moest om te kalmeren, ga bewust terug naar je baby. Ga zitten, adem rustig en zeg: 'Papa is er weer.'",
    duration: "3 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Zelfregulatie van de ouder is de basis voor co-regulatie met het kind. Terugkeren na zelf-kalmering modelleert gezonde emotieregulatie.",
    skillTip: "Het is oké om even weg te gaan — het gaat erom dat je bewust terugkomt.",
    vermijd: "Terugkomen terwijl je nog geïrriteerd bent — je baby pikt dat feilloos op.",
    leerdoel: "Je leert dat weggaan en terugkomen een legitieme herstelstrategie is.",
    bron: "Siegel & Bryson (2011) - The Whole-Brain Child & parental regulation",
  },
  {
    id: "hers_02_08",
    title: "Huidcontact na ziekenhuisbezoek",
    skill: "Herstel",
    description: "Na een stressvolle ervaring zoals een vaccinatie of doktersbezoek, doe huid-op-huidcontact met je baby. Leg het op je blote borst.",
    duration: "15 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Huid-op-huidcontact (kangaroo care) verlaagt cortisol bij zowel baby als ouder. Het herstelt het gevoel van veiligheid na medische stress.",
    skillTip: "Zorg voor een warme, rustige omgeving — dim het licht en minimaliseer geluid.",
    vermijd: "Je baby meteen in de auto zetten na het bezoek zonder troostmoment.",
    leerdoel: "Je leert om na externe stressoren bewust een herstellend moment te creëren.",
    bron: "Feldman et al. (2010) - Skin-to-skin contact & stress regulation",
  },
  {
    id: "hers_02_09",
    title: "Verbroken routine herstellen",
    skill: "Herstel",
    description: "Als de dagelijkse routine verstoord is geweest, herstel bewust een vertrouwd ritueel — bijvoorbeeld het bekende badtijdritueel of voorlezen voor het slapen.",
    duration: "15 min",
    ageGroups: ["0-2"],
    difficulty: "expert",
    points: 25,
    psychologie: "Voorspelbaarheid is de basis van veilige hechting bij baby's. Het herstellen van bekende routines geeft het kind houvast na chaos.",
    skillTip: "Kies het ritueel waar je baby het sterkst op reageert — dat is jullie ankerpunt.",
    vermijd: "Alles tegelijk willen herstellen — focus op één vertrouwd ritueel.",
    leerdoel: "Je leert om structuur en voorspelbaarheid als herstelmiddel in te zetten.",
    bron: "Ainsworth (1978) - Patterns of Attachment & predictability",
  },
  {
    id: "hers_02_10",
    title: "Reflecteren op je reactie",
    skill: "Herstel",
    description: "Neem na het slapengaan van je baby een moment om terug te kijken op een lastig moment. Schrijf op wat er gebeurde, hoe je reageerde en wat je volgende keer anders wilt doen.",
    duration: "10 min",
    ageGroups: ["0-2"],
    difficulty: "expert",
    points: 25,
    psychologie: "Reflectief functioneren — het vermogen om over je eigen gedrag na te denken — is de sterkste voorspeller van veilige hechting bij je kind.",
    skillTip: "Wees niet te streng voor jezelf — het gaat om bewustwording, niet om perfectie.",
    vermijd: "Jezelf veroordelen — dat blokkeert het leerproces.",
    leerdoel: "Je ontwikkelt het vermogen om te reflecteren op je eigen oudergedrag.",
    bron: "Fonagy et al. (2002) - Reflective Functioning & mentalization",
  },

  // ── Herstel · 3-5 jaar ────────────────────────────────────
  {
    id: "hers_35_01",
    title: "Sorry zeggen met woorden",
    skill: "Herstel",
    description: "Zeg tegen je peuter: 'Het spijt me dat ik zo hard praatte. Dat was niet fijn voor jou. Papa gaat het rustiger doen.'",
    duration: "3 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen van 3-5 begrijpen eenvoudige verbale excuses. Door sorry te zeggen model je dat fouten maken menselijk is en hersteld kan worden.",
    skillTip: "Gebruik korte, concrete zinnen — een peuter kan lange uitleg niet verwerken.",
    vermijd: "Abstracte excuses als 'sorry dat je je zo voelt' — benoem concreet wat JIJ deed.",
    leerdoel: "Je leert om op kindniveau sorry te zeggen met woorden die je kind begrijpt.",
    bron: "Gottman (1997) - Repair attempts in relationships & parenting",
  },
  {
    id: "hers_35_02",
    title: "Tekening als herstel",
    skill: "Herstel",
    description: "Na een ruzie, ga samen zitten en teken samen een plaatje van 'papa en jij die weer blij zijn'. Praat erover terwijl je tekent.",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Creatieve expressie biedt een veilige manier om emoties te verwerken bij peuters en kleuters. Het samen tekenen herstelt de verbinding via parallel spel.",
    skillTip: "Laat je kind de leiding nemen in wat er getekend wordt — volg hun verhaal.",
    vermijd: "Het plaatje sturen of corrigeren — het gaat om het proces, niet het product.",
    leerdoel: "Je leert om creatieve activiteiten in te zetten als herstelmethode.",
    bron: "Malchiodi (2011) - Art therapy with children & emotional processing",
  },
  {
    id: "hers_35_03",
    title: "Knuffel als brug",
    skill: "Herstel",
    description: "Na een boze bui (van jou of je kind), vraag: 'Mag ik je een knuffel geven? Ik vind het niet fijn als we boos op elkaar zijn.'",
    duration: "2 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Fysiek contact na conflict herstelt het oxytocinesysteem. Door toestemming te vragen, respecteer je de autonomie van je kind.",
    skillTip: "Accepteer het als je kind nog niet klaar is voor een knuffel — bied het later opnieuw aan.",
    vermijd: "Een knuffel afdwingen — dat voelt als een inbreuk in plaats van herstel.",
    leerdoel: "Je leert om toestemming te vragen voor fysiek contact bij herstel.",
    bron: "Hughes (2009) - PACE model: Playfulness, Acceptance, Curiosity, Empathy",
  },
  {
    id: "hers_35_04",
    title: "Handpop die sorry zegt",
    skill: "Herstel",
    description: "Gebruik een knuffel of handpop om namens jou sorry te zeggen. Laat de pop zeggen: 'Papa vindt het heel erg dat hij boos werd. Wil je de pop een knuffel geven?'",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Indirect communiceren via een pop verlaagt de emotionele drempel bij peuters. Het kind kan veilig reageren zonder zich bedreigd te voelen.",
    skillTip: "Gebruik een pop die je kind al kent en leuk vindt — dat vergroot de veiligheid.",
    vermijd: "De pop gebruiken om het kind de schuld te geven of een les te leren.",
    leerdoel: "Je leert speels en indirect te communiceren bij gevoelige momenten.",
    bron: "Axline (1947) - Play therapy & indirect communication with children",
  },
  {
    id: "hers_35_05",
    title: "Samen een herstelliedje zingen",
    skill: "Herstel",
    description: "Verzin samen een simpel liedje over 'weer vriendjes zijn'. Bijvoorbeeld op de melodie van een bekend kinderliedje: 'We zijn weer blij, jij en ik, papa houdt van jou!'",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Muziek en ritme verlagen cortisol en bevorderen sociale verbinding. Een gedeeld liedje wordt een ritueel dat bij toekomstige conflicten ingezet kan worden.",
    skillTip: "Houd het simpel en herhaalbaar — je kind gaat het onthouden en zelf aanbieden.",
    vermijd: "Het liedje ironisch of sarcastisch zingen — kinderen nemen het letterlijk.",
    leerdoel: "Je leert een herstelritueel te creëren dat je steeds opnieuw kunt gebruiken.",
    bron: "Trainor & Hannon (2013) - Music cognition in early childhood",
  },
  {
    id: "hers_35_06",
    title: "Eerlijk benoemen wat er misging",
    skill: "Herstel",
    description: "Zeg tegen je kleuter: 'Weet je wat er net gebeurde? Papa was moe en werd boos. Maar dat was niet jouw schuld. Jij deed niks verkeerd.'",
    duration: "3 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen van 3-5 neigen ertoe zichzelf de schuld te geven van conflicten (egocentrisme). Expliciet benoemen dat het niet hun schuld is, voorkomt schuldgevoel.",
    skillTip: "Gebruik de naam van je kind — dat maakt het persoonlijk en direct.",
    vermijd: "De oorzaak bij het kind leggen: 'als jij niet zo vervelend deed...'",
    leerdoel: "Je leert verantwoordelijkheid te nemen zonder schuld bij je kind te leggen.",
    bron: "Piaget (1952) - Egocentrism in preoperational stage & guilt attribution",
  },
  {
    id: "hers_35_07",
    title: "Herstelwandeling",
    skill: "Herstel",
    description: "Na een conflict, stel voor: 'Zullen we even samen naar buiten gaan? Een stukje lopen en naar de vogels kijken?' Gebruik de wandeling om rustig te praten.",
    duration: "15 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Beweging in de natuur verlaagt stresshormonen. Naast elkaar lopen (in plaats van tegenover elkaar) vermindert de confrontatie en vergemakkelijkt open gesprek.",
    skillTip: "Laat je kind het tempo bepalen — stop bij wat hun aandacht trekt.",
    vermijd: "De wandeling gebruiken als straf ('we gaan lopen omdat je stout was').",
    leerdoel: "Je leert omgevingsverandering te gebruiken als katalysator voor herstel.",
    bron: "Bratman et al. (2015) - Nature experience & emotional restoration",
  },
  {
    id: "hers_35_08",
    title: "Verhaal over een beer die sorry zegt",
    skill: "Herstel",
    description: "Vertel een verhaaltje over een papa-beer die boos werd op zijn kleine beertje en daarna sorry kwam zeggen. Vraag: 'Wat denk jij dat het kleine beertje voelde?'",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Narratieve verwerking via verhalen helpt kleuters om complexe emotionele ervaringen te begrijpen. De afstand van het verhaal maakt het veilig om gevoelens te benoemen.",
    skillTip: "Pas het verhaal aan op wat er werkelijk gebeurde — je kind herkent de situatie en voelt zich begrepen.",
    vermijd: "Het verhaal een moraliserende les maken — laat je kind zelf conclusies trekken.",
    leerdoel: "Je leert verhalen te gebruiken als middel voor emotionele verwerking en herstel.",
    bron: "Siegel & Bryson (2012) - Name it to tame it & narrative integration",
  },
  {
    id: "hers_35_09",
    title: "Herstelritueel met plakband",
    skill: "Herstel",
    description: "Knip samen een hartje uit papier en scheur het voorzichtig doormidden. Zeg: 'Kijk, zo voelt het als we ruzie hebben.' Plak het samen weer vast: 'En zo maken we het weer goed.'",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "expert",
    points: 25,
    psychologie: "Concrete visuele metaforen helpen kleuters abstracte concepten als 'herstel' te begrijpen. Het actief samen repareren geeft controle en agency.",
    skillTip: "Bewaar het geplakte hartje als herinnering — je kunt ernaar verwijzen bij toekomstige conflicten.",
    vermijd: "Het hartje gebruiken als dreiging ('als je stout bent, scheur ik het weer').",
    leerdoel: "Je leert abstracte emotionele processen concreet en tastbaar te maken voor je kleuter.",
    bron: "Vygotsky (1978) - Zone of proximal development & concrete operations",
  },
  {
    id: "hers_35_10",
    title: "Gezinsconferentie na een moeilijke dag",
    skill: "Herstel",
    description: "Ga aan het eind van een moeilijke dag samen aan tafel zitten. Vraag je kleuter: 'Wat was vandaag niet leuk? En wat kunnen we morgen beter doen samen?'",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "expert",
    points: 25,
    psychologie: "Een gestructureerd moment van reflectie geeft kinderen het gevoel dat hun ervaring ertoe doet. Het bouwt een patroon van dagelijks herstel op.",
    skillTip: "Begin altijd met iets positiefs voordat je het moeilijke bespreekt.",
    vermijd: "Het kind ondervragen of een kruisverhoor afnemen — het moet een veilig gesprek zijn.",
    leerdoel: "Je leert om regelmatige herstelmomenten in te bouwen in jullie dagelijks leven.",
    bron: "Dreikurs (1964) - Family meetings & democratic parenting",
  },

  // ── Herstel · 6-9 jaar ────────────────────────────────────
  {
    id: "hers_69_01",
    title: "Oprecht sorry zeggen",
    skill: "Herstel",
    description: "Ga naar je kind toe en zeg: 'Ik wil sorry zeggen voor wat er net gebeurde. Ik had niet zo moeten reageren. Hoe voel jij je nu?'",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen van 6-9 herkennen oprechtheid. Een eerlijke verontschuldiging modelleert emotionele volwassenheid en bouwt vertrouwen op.",
    skillTip: "Kijk je kind aan terwijl je sorry zegt — oogcontact versterkt de oprechtheid.",
    vermijd: "Sorry zeggen met een 'maar' erachter ('sorry, maar jij begon').",
    leerdoel: "Je leert een oprechte, onvoorwaardelijke verontschuldiging aan te bieden.",
    bron: "Chapman & Thomas (2006) - The Five Languages of Apology",
  },
  {
    id: "hers_69_02",
    title: "Brief schrijven na ruzie",
    skill: "Herstel",
    description: "Schrijf een kort briefje aan je kind: 'Lieve [naam], het spijt me van onze ruzie. Jij bent belangrijk voor me. Liefs, papa.' Leg het op hun kussen.",
    duration: "10 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Geschreven woorden geven het kind iets tastbaars om vast te houden. Het kind kan het briefje herlezen wanneer het daar behoefte aan heeft.",
    skillTip: "Schrijf het met de hand — dat voelt persoonlijker dan een appje of printje.",
    vermijd: "Het briefje gebruiken om je eigen standpunt nogmaals uit te leggen.",
    leerdoel: "Je leert een alternatieve manier van herstel via geschreven communicatie.",
    bron: "Pennebaker (1997) - Expressive writing & emotional processing",
  },
  {
    id: "hers_69_03",
    title: "Samen iets leuks doen na conflict",
    skill: "Herstel",
    description: "Stel na een ruzie voor: 'Zullen we samen iets leuks doen? Jij mag kiezen — een spelletje, buiten spelen of samen koken.'",
    duration: "30 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Gedeelde positieve ervaringen na conflict herstellen de emotionele bankrekening. Het kind leert: na iets naars kan er weer iets goeds komen.",
    skillTip: "Laat je kind echt kiezen — dat geeft hen een gevoel van controle na het conflict.",
    vermijd: "De activiteit gebruiken als afleiding zonder eerst sorry te zeggen.",
    leerdoel: "Je leert om positieve ervaringen bewust in te zetten als aanvulling op verbaal herstel.",
    bron: "Gottman (1999) - Emotional bank account & positive interactions ratio",
  },
  {
    id: "hers_69_04",
    title: "Fouten normaliseren",
    skill: "Herstel",
    description: "Zeg tegen je kind: 'Weet je, iedereen maakt fouten — ook papa's. Het belangrijkste is dat je het weer goed probeert te maken. Dat is wat ik nu doe.'",
    duration: "3 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen die leren dat fouten normaal zijn, ontwikkelen een growth mindset. De ouder als model van feilbaarheid verlaagt perfectionisme.",
    skillTip: "Deel een eigen voorbeeld uit je jeugd — dat maakt je menselijk en benaderbaar.",
    vermijd: "Fouten bagatelliseren ('het stelde niks voor') — erken de impact.",
    leerdoel: "Je leert om fouten te normaliseren zonder ze te bagatelliseren.",
    bron: "Dweck (2006) - Mindset: Growth mindset & learning from mistakes",
  },
  {
    id: "hers_69_05",
    title: "Luisteren zonder verdediging",
    skill: "Herstel",
    description: "Vraag je kind: 'Wil je me vertellen hoe het voor jou was toen ik boos werd?' Luister zonder jezelf te verdedigen. Zeg alleen: 'Dankjewel dat je dat vertelt.'",
    duration: "10 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Actief luisteren zonder defensiviteit leert kinderen dat hun gevoelens er toe doen. Het versterkt hun emotionele intelligentie en zelfvertrouwen.",
    skillTip: "Slik je eerste reactie in als die defensief is — adem eerst drie keer diep in.",
    vermijd: "Je kind onderbreken om je kant van het verhaal te vertellen.",
    leerdoel: "Je leert om niet-defensief te luisteren naar feedback van je kind.",
    bron: "Rogers (1951) - Client-centered therapy & unconditional positive regard",
  },
  {
    id: "hers_69_06",
    title: "Herstelplan samen maken",
    skill: "Herstel",
    description: "Zeg: 'Ik wil dat we dit samen oplossen. Wat denk jij dat we allebei anders kunnen doen als het de volgende keer zo gaat?' Schrijf jullie plan samen op.",
    duration: "15 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen van 6-9 kunnen beginnen met probleemoplossend denken. Samen een plan maken geeft hen agency en eigenaarschap over het herstelproces.",
    skillTip: "Laat je kind eerst met ideeën komen — vul aan, maar neem niet over.",
    vermijd: "Alle regels zelf bepalen en het een 'plan' noemen — dat is geen samenwerking.",
    leerdoel: "Je leert om je kind actief te betrekken bij het bedenken van oplossingen.",
    bron: "Greene (2001) - Collaborative & Proactive Solutions model",
  },
  {
    id: "hers_69_07",
    title: "Eerlijk zijn over je emoties",
    skill: "Herstel",
    description: "Zeg: 'Ik was boos, maar eigenlijk was ik ook moe en gestrest van mijn werk. Dat is geen excuus, maar ik wil eerlijk zijn over waarom ik zo reageerde.'",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Emotionele transparantie van ouders helpt kinderen om de complexiteit van emoties te begrijpen. Het voorkomt dat het kind denkt dat het de enige oorzaak was.",
    skillTip: "Houd het leeftijdspassend — deel genoeg om eerlijk te zijn, maar belast je kind niet met volwassenzorgen.",
    vermijd: "Te veel detail geven over je stress — je kind is geen therapeut.",
    leerdoel: "Je leert om emotioneel transparant te zijn op een leeftijdspassende manier.",
    bron: "Gottman & DeClaire (1997) - Emotion coaching & meta-emotion philosophy",
  },
  {
    id: "hers_69_08",
    title: "Terugspoelen en opnieuw doen",
    skill: "Herstel",
    description: "Zeg: 'Wacht even, ik wil dat opnieuw doen. *Spoelt terug* Oké, wat ik had willen zeggen is...' Doe de situatie opnieuw, maar dan op de manier die je wél bedoelde.",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Het 'redo' concept laat kinderen zien dat je gedrag kunt corrigeren in het moment. Het introduceert de mogelijkheid van een 'tweede kans' in relaties.",
    skillTip: "Maak er een licht moment van met de 'terugspoelen' — humor verlaagt de spanning.",
    vermijd: "Het kind ook dwingen om het opnieuw te doen — dit gaat over jouw herstel.",
    leerdoel: "Je leert om in het moment te corrigeren met behulp van humor en speelsheid.",
    bron: "Siegel & Bryson (2014) - No-Drama Discipline & the repair redo",
  },
  {
    id: "hers_69_09",
    title: "Conflictdagboek bijhouden",
    skill: "Herstel",
    description: "Begin een schriftje waarin je na elk conflict kort opschrijft: wat gebeurde er, hoe reageerde ik, wat deed mijn kind, en hoe herstelden we? Bekijk patronen na een maand.",
    duration: "10 min",
    ageGroups: ["6-9"],
    difficulty: "expert",
    points: 25,
    psychologie: "Systematische reflectie op conflictpatronen vergroot je zelfbewustzijn en helpt je triggers te herkennen voordat ze escaleren.",
    skillTip: "Schrijf zonder oordeel — het is een observatiedagboek, geen beoordelingsformulier.",
    vermijd: "Het dagboek gebruiken als bewijsmateriaal tegen je kind ('kijk, dit doe je altijd').",
    leerdoel: "Je ontwikkelt het vermogen om patronen te herkennen in je conflictstijl als ouder.",
    bron: "Schön (1983) - Reflective practice & professional development",
  },
  {
    id: "hers_69_10",
    title: "Bespreken wat herhaling voorkomt",
    skill: "Herstel",
    description: "Ga samen met je kind na een conflict in gesprek: 'Wat was het moment dat het misging? Wat had ik anders kunnen doen? En wat had jij misschien anders kunnen doen?' Maak samen een afspraak.",
    duration: "15 min",
    ageGroups: ["6-9"],
    difficulty: "expert",
    points: 25,
    psychologie: "Meta-communicatie — praten over hoe je communiceert — ontwikkelt hogere-ordevaardigheden bij schoolkinderen en versterkt de samenwerking in de relatie.",
    skillTip: "Begin met je eigen aandeel — dat opent de deur voor je kind om ook eerlijk te zijn.",
    vermijd: "Het gesprek laten uitmonden in een nieuw conflict — houd het constructief en kort.",
    leerdoel: "Je leert om met je kind te reflecteren op conflicten en preventieve afspraken te maken.",
    bron: "Watzlawick et al. (1967) - Pragmatics of Human Communication & meta-communication",
  },

  // ── Herstel · 10-12 jaar ──────────────────────────────────
  {
    id: "hers_12_01",
    title: "Erkenning zonder excuses",
    skill: "Herstel",
    description: "Zeg tegen je pre-teen: 'Ik was verkeerd bezig. Ik had je niet zo moeten afsnauwen. Je hebt recht op een vader die respectvol met je praat.'",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Pre-teens hebben een sterk ontwikkeld rechtvaardigheidsgevoel. Een eerlijke erkenning zonder excuses wordt door hen als respectvol ervaren.",
    skillTip: "Gebruik 'ik'-taal in plaats van 'jij'-taal — neem volledige verantwoordelijkheid.",
    vermijd: "Excuses aandragen voor je gedrag — dat ondermijnt de oprechtheid.",
    leerdoel: "Je leert om volledige verantwoordelijkheid te nemen voor je eigen gedrag.",
    bron: "Kohlberg (1981) - Stages of moral development & justice reasoning",
  },
  {
    id: "hers_12_02",
    title: "Ruimte geven voor boosheid",
    skill: "Herstel",
    description: "Wanneer je kind boos is na een conflict, zeg: 'Ik snap dat je boos bent. Je mag boos zijn. Als je klaar bent om te praten, ben ik er.' Geef hen de ruimte.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Pre-teens hebben behoefte aan autonomie in hun emotionele verwerking. Ruimte geven toont respect en vertrouwen in hun vermogen om te reguleren.",
    skillTip: "Ga niet in een andere kamer zitten wachten — blijf beschikbaar maar niet opdringerig.",
    vermijd: "Aandringen op een gesprek wanneer je kind daar nog niet aan toe is.",
    leerdoel: "Je leert om het tempo van je kind te respecteren bij emotioneel herstel.",
    bron: "Ryan & Deci (2000) - Self-Determination Theory & autonomy support",
  },
  {
    id: "hers_12_03",
    title: "Samen wandelen en praten",
    skill: "Herstel",
    description: "Stel voor om samen een stukje te wandelen na een conflict. Wandel naast je kind en begin rustig: 'Ik wil even praten over wat er net gebeurde.'",
    duration: "20 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Naast elkaar lopen verlaagt de confrontatie-intensiteit. De beweging en buitenlucht helpen beiden om emotioneel te reguleren tijdens het gesprek.",
    skillTip: "Begin met lopen en praat pas als de rust er is — forceer het gesprek niet meteen.",
    vermijd: "Het hele gesprek al gepland hebben in je hoofd — laat ruimte voor wat je kind inbrengt.",
    leerdoel: "Je leert om movement en side-by-side contact te gebruiken voor moeilijke gesprekken.",
    bron: "Oppezzo & Schwartz (2014) - Walking & creative/open thinking",
  },
  {
    id: "hers_12_04",
    title: "Erken de impact op je kind",
    skill: "Herstel",
    description: "Zeg: 'Ik realiseer me dat wat ik zei pijn deed. Dat was niet mijn bedoeling, maar de impact was er wel. Het spijt me echt.'",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Het onderscheid tussen intentie en impact is cruciaal bij pre-teens. Het erkennen van de impact — ongeacht je intentie — is de sleutel tot geloofwaardig herstel.",
    skillTip: "Vraag niet meteen om vergiffenis — laat je kind de tijd om te verwerken.",
    vermijd: "Zeggen 'zo bedoelde ik het niet' als verdediging — erken eerst de impact.",
    leerdoel: "Je leert het verschil tussen intentie en impact te erkennen in je communicatie.",
    bron: "Stone, Patton & Heen (1999) - Difficult Conversations: impact vs. intent",
  },
  {
    id: "hers_12_05",
    title: "Gebroken belofte herstellen",
    skill: "Herstel",
    description: "Als je een belofte niet nakwam, zeg: 'Ik had beloofd om [X] te doen en dat heb ik niet gedaan. Dat was niet eerlijk naar jou. Hoe kunnen we dit rechtzetten?'",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Gebroken beloftes raken het vertrouwen bij pre-teens diep. Actief herstellen — niet alleen sorry zeggen maar ook een oplossing bieden — herstelt dat vertrouwen.",
    skillTip: "Maak een concrete nieuwe afspraak en houd je er deze keer aan — woorden alleen zijn niet genoeg.",
    vermijd: "Opnieuw beloven zonder na te denken of je het kunt waarmaken.",
    leerdoel: "Je leert om gebroken beloftes te herstellen met concrete acties, niet alleen woorden.",
    bron: "Erikson (1968) - Identity & trust development in pre-adolescence",
  },
  {
    id: "hers_12_06",
    title: "Emotioneel check-in de volgende dag",
    skill: "Herstel",
    description: "De dag na een conflict, vraag je kind: 'Hé, hoe voel je je nu over gisteren? Is er nog iets dat je dwars zit?' Luister aandachtig.",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Pre-teens verwerken conflicten vaak pas achteraf. Een dag later inchecken laat zien dat het herstel niet vrijblijvend was maar dat je er echt om geeft.",
    skillTip: "Kies een ontspannen moment — niet als je kind bezig is met huiswerk of een game.",
    vermijd: "Zeggen 'we hadden het er toch over gehad?' als je kind nieuwe gevoelens uit.",
    leerdoel: "Je leert om herstel als een doorlopend proces te zien, niet als een eenmalig moment.",
    bron: "Siegel (2012) - The Developing Mind & temporal integration of experience",
  },
  {
    id: "hers_12_07",
    title: "Kwetsbaarheid tonen",
    skill: "Herstel",
    description: "Deel met je kind: 'Ik vind het moeilijk om toe te geven dat ik fout zat. Maar ik wil eerlijk zijn, want onze relatie is belangrijker dan mijn trots.'",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kwetsbaarheid van een ouder modelleert emotionele moed. Pre-teens leren dat sterkte niet betekent dat je altijd gelijk hebt, maar dat je fouten kunt toegeven.",
    skillTip: "Dit hoeft niet perfect te klinken — het feit dat je het probeert is al krachtig.",
    vermijd: "Te veel emotionele last bij je kind leggen — blijf de ouder in de interactie.",
    leerdoel: "Je leert om kwetsbaarheid te tonen als vader zonder de ouderrol te verliezen.",
    bron: "Brown (2012) - Daring Greatly: vulnerability & courage in parenting",
  },
  {
    id: "hers_12_08",
    title: "Samen regels herzien na conflict",
    skill: "Herstel",
    description: "Zeg: 'Het conflict van gisteren laat me denken dat sommige afspraken misschien niet meer passen. Zullen we samen kijken of we iets moeten aanpassen?'",
    duration: "20 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Pre-teens ervaren veel conflicten door regels die niet meegroeien. Regels samen herzien geeft hen invloed en vermindert machtsstrijd.",
    skillTip: "Wees bereid om echt iets aan te passen — anders voelt het als schijnparticipatie.",
    vermijd: "Alles ter discussie stellen — bepaal vooraf welke regels bespreekbaar zijn.",
    leerdoel: "Je leert om conflicten te gebruiken als aanleiding om afspraken gezamenlijk te evalueren.",
    bron: "Baumrind (1991) - Authoritative parenting & negotiation of rules",
  },
  {
    id: "hers_12_09",
    title: "Vergeving vragen zonder druk",
    skill: "Herstel",
    description: "Zeg: 'Ik hoop dat je me kunt vergeven, maar ik begrijp het als dat even duurt. Ik wil je laten weten dat ik aan ons werk.' Accepteer hun antwoord.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 25,
    psychologie: "Vergeving die afgedwongen wordt, is geen echte vergeving. Door ruimte te geven, modelleer je respect voor het emotionele proces van je kind.",
    skillTip: "Zeg het en laat het dan los — niet blijven vragen of ze je al vergeven hebben.",
    vermijd: "Subtiel schuldgevoel creëren ('ik voel me zo erg, vergeef je me alsjeblieft?').",
    leerdoel: "Je leert om vergeving te vragen zonder emotionele druk uit te oefenen.",
    bron: "Worthington (2003) - REACH model of forgiveness & relational repair",
  },
  {
    id: "hers_12_10",
    title: "Patroononderbreking bespreken",
    skill: "Herstel",
    description: "Zeg: 'Ik merk dat we steeds op dezelfde manier ruzie maken. Ik wil dat patroon doorbreken. Herken jij dat ook? Wat denk jij dat we anders kunnen doen?'",
    duration: "15 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 25,
    psychologie: "Meta-cognitie over relatiepatronen is een geavanceerde vaardigheid. Pre-teens kunnen dit beginnen te begrijpen en het geeft hen inzicht in relationele dynamieken.",
    skillTip: "Gebruik een concreet voorbeeld van het patroon — abstract praten helpt niet bij deze leeftijd.",
    vermijd: "Het patroon alleen bij je kind leggen — bespreek jullie beider aandeel.",
    leerdoel: "Je leert om terugkerende conflictpatronen te herkennen en samen te doorbreken.",
    bron: "Minuchin (1974) - Structural family therapy & pattern disruption",
  },

  // ── Herstel · 13-16 jaar ──────────────────────────────────
  {
    id: "hers_16_01",
    title: "Respectvol sorry zeggen",
    skill: "Herstel",
    description: "Benader je tiener rustig en zeg: 'Ik wil mijn excuses aanbieden. Hoe ik reageerde was niet respectvol naar jou. Je verdient beter.'",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Tieners hebben een scherp oog voor respect en eerlijkheid. Een excuus dat respect uitstraalt, bereikt hen beter dan een emotioneel excuus.",
    skillTip: "Kies het juiste moment — niet midden in een groepschat of voor vrienden.",
    vermijd: "Sorry zeggen op een manier die neerbuigend overkomt ('sorry hoor, als je je gekwetst voelt').",
    leerdoel: "Je leert om sorry te zeggen op een manier die past bij de ontwikkelingsfase van je tiener.",
    bron: "Steinberg (2014) - Age of Opportunity: adolescent sensitivity to fairness",
  },
  {
    id: "hers_16_02",
    title: "Bericht sturen na ruzie",
    skill: "Herstel",
    description: "Stuur je tiener een kort berichtje na een conflict: 'Hé, ik vind het vervelend hoe dat net ging. Wil even zeggen dat ik van je houd, ook als we het niet eens zijn.'",
    duration: "2 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Tieners communiceren veel via tekst. Een berichtje op hun medium bereikt hen soms beter dan een face-to-face gesprek, zeker als emoties nog hoog zijn.",
    skillTip: "Houd het kort — geen essay. Eén of twee zinnen zijn genoeg.",
    vermijd: "Een hele uitleg via berichtjes sturen of het conflict via de app voortzetten.",
    leerdoel: "Je leert om het communicatiemedium van je tiener te gebruiken voor herstel.",
    bron: "Turkle (2015) - Reclaiming Conversation & digital communication in families",
  },
  {
    id: "hers_16_03",
    title: "Tijd geven zonder afwijzing",
    skill: "Herstel",
    description: "Als je tiener zich terugtrekt na een conflict, zeg: 'Ik geef je de ruimte. Als je wilt praten, ik ben er. Geen haast.' Loop rustig weg.",
    duration: "2 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Tieners hebben een sterke behoefte aan autonomie. Ruimte geven zonder het als straf te laten voelen, respecteert hun verwerkingsproces.",
    skillTip: "Controleer na een paar uur even kort in — niet als druk, maar als zorg.",
    vermijd: "Boze stilte als straf presenteren ('dan praten we maar niet meer').",
    leerdoel: "Je leert het verschil tussen ruimte geven en emotionele afwijzing.",
    bron: "Laursen & Collins (2009) - Parent-adolescent relationships & autonomy granting",
  },
  {
    id: "hers_16_04",
    title: "Erken dat je uit je rol viel",
    skill: "Herstel",
    description: "Zeg eerlijk: 'Ik viel uit mijn rol als vader. Ik reageerde meer als iemand die gekwetst was dan als iemand die jou moet steunen. Dat spijt me.'",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Tieners respecteren zelfreflectie bij volwassenen. Erkennen dat je uit je rol viel, toont emotioneel bewustzijn en modelleert zelfkritiek.",
    skillTip: "Dit verlaagt het wij-tegen-zij-gevoel dat vaak bij ouder-tienerconflicten hoort.",
    vermijd: "Je te veel verontschuldigen — houd de balans tussen eerlijkheid en stabiliteit.",
    leerdoel: "Je leert om je ouderrol te reflecteren en te erkennen wanneer je daarbuiten treedt.",
    bron: "Satir (1988) - Peoplemaking: congruent communication in families",
  },
  {
    id: "hers_16_05",
    title: "De eerste stap zetten",
    skill: "Herstel",
    description: "Als jullie al een tijdje niet gepraat hebben na een conflict, breek het ijs: 'Ik mis ons gesprek. Ik wil niet dat dit tussen ons in blijft staan.'",
    duration: "3 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "In ouder-tienerrelaties moet de ouder de eerste stap zetten. Wachten tot je tiener het initiatief neemt, kan leiden tot langdurige verwijdering.",
    skillTip: "Het hoeft niet groots te zijn — soms is een kop thee aanbieden al genoeg als opening.",
    vermijd: "Wachten tot je tiener sorry zegt — jij bent de volwassene in de relatie.",
    leerdoel: "Je leert om als vader altijd de verantwoordelijkheid te nemen voor het herstel.",
    bron: "Neufeld & Maté (2004) - Hold On to Your Kids: maintaining attachment with teens",
  },
  {
    id: "hers_16_06",
    title: "Luisteren naar hun perspectief",
    skill: "Herstel",
    description: "Zeg: 'Ik wil graag begrijpen hoe jij het hebt ervaren. Wil je me vertellen wat er voor jou gebeurde?' Luister echt, zonder in de verdediging te schieten.",
    duration: "15 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Perspective-taking is essentieel bij tieners die zich vaak onbegrepen voelen. Echt luisteren — zonder direct te reageren — is een van de krachtigste herstelstrategieën.",
    skillTip: "Vat samen wat je hoort: 'Dus jij voelde dat...' — dat toont dat je echt luistert.",
    vermijd: "Tussenwerpen met 'maar zo was het niet' — laat hun versie eerst volledig landen.",
    leerdoel: "Je leert om het perspectief van je tiener volledig te ontvangen zonder verdediging.",
    bron: "Selman (1980) - Perspective-taking & interpersonal understanding in adolescents",
  },
  {
    id: "hers_16_07",
    title: "Gezamenlijke afspraak maken",
    skill: "Herstel",
    description: "Na het bespreken van een conflict, stel voor: 'Wat als we afspreken dat we allebei [concreet gedrag] doen als het weer escaleert? Eén ding dat we anders doen.'",
    duration: "10 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Concrete gedragsafspraken zijn effectiever dan vage beloftes ('ik zal beter mijn best doen'). Tieners waarderen eerlijke, haalbare commitments.",
    skillTip: "Kies iets kleins en concreets — groot denken leidt tot teleurstelling.",
    vermijd: "Alleen afspraken maken die voor je tiener gelden en niet voor jou.",
    leerdoel: "Je leert om conflict om te zetten in concrete, wederzijdse gedragsafspraken.",
    bron: "Patterson (2002) - Coercion theory & behavioral contracting with adolescents",
  },
  {
    id: "hers_16_08",
    title: "Kwetsbaarheid delen als vader",
    skill: "Herstel",
    description: "Deel eerlijk: 'Ik vind opvoeden soms echt moeilijk. Ik wil het goed doen, maar soms lukt dat niet. Het spijt me als ik je daarmee kwets.'",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Authentieke kwetsbaarheid van een vader doorbreekt het beeld van de 'onbereikbare ouder'. Tieners reageren hier vaak verrassend positief op.",
    skillTip: "Dit werkt het best op een rustig moment — niet in de hitte van een conflict.",
    vermijd: "Je kind tot trooster maken — deel je kwetsbaarheid, niet je volledige emotionele last.",
    leerdoel: "Je leert om authentiek kwetsbaar te zijn zonder de ouder-kindbalans te verstoren.",
    bron: "Brown (2012) - Daring Greatly: vulnerability in parenting adolescents",
  },
  {
    id: "hers_16_09",
    title: "Langdurig conflict doorbreken",
    skill: "Herstel",
    description: "Bij een slepend conflict dat al weken duurt, schrijf een brief aan je tiener: 'Ik merk dat we vastzitten. Ik wil je vertellen wat ik voel, zonder ruzie.' Leg alles eerlijk uit.",
    duration: "30 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 25,
    psychologie: "Langdurige conflicten creëren chronische stress in het gezinssysteem. Een brief doorbreekt het patroon omdat het eenzijdig initiatief toont zonder interactie-escalatie.",
    skillTip: "Laat de brief een nacht liggen en herlees hem — schrap wat beschuldigend klinkt.",
    vermijd: "De brief als ultiem wapen inzetten ('als dit niet werkt, geef ik het op').",
    leerdoel: "Je leert om vastgelopen conflicten te doorbreken via reflectieve geschreven communicatie.",
    bron: "Pennebaker (1997) - Expressive writing & Bowen (1978) - Family Systems Theory",
  },
  {
    id: "hers_16_10",
    title: "Professionele hulp bespreekbaar maken",
    skill: "Herstel",
    description: "Als herstel steeds niet lukt, zeg: 'Ik denk dat het goed zou zijn als we met iemand gaan praten. Niet omdat er iets mis is met jou of mij, maar omdat ik onze relatie belangrijk vind.'",
    duration: "10 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 25,
    psychologie: "Het bespreekbaar maken van professionele hulp normaliseert hulpvragen en toont dat je bereid bent te investeren in de relatie. Het doorbreekt het stigma rond therapie.",
    skillTip: "Presenteer het als iets voor jullie samen — niet als 'jij hebt hulp nodig'.",
    vermijd: "Het als dreigement inzetten ('als je zo doorgaat, stuur ik je naar een psycholoog').",
    leerdoel: "Je leert om professionele hulp op een veilige, niet-stigmatiserende manier te bespreken.",
    bron: "Diamond et al. (2010) - Attachment-Based Family Therapy for adolescents",
  },

  // ═══════════════════════════════════════════════════════════════
  // VERBINDING (50 taken: 5 leeftijdsgroepen × 10 taken)
  // ═══════════════════════════════════════════════════════════════

  // ── Verbinding · 0-2 jaar ─────────────────────────────────
  {
    id: "verb_02_01",
    title: "Huid-op-huidcontact",
    skill: "Verbinding",
    description: "Leg je baby op je blote borst en blijf samen rustig liggen. Voel de hartslag en ademhaling van je kind. Fluister: 'Papa is hier.'",
    duration: "10 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Huid-op-huidcontact stimuleert oxytocineafgifte bij vader en baby. Het synchroniseert hartritme en bevordert hechtingsveiligheid.",
    skillTip: "Doe dit in een warme, rustige ruimte — zorg dat je baby en jij ontspannen zijn.",
    vermijd: "Ondertussen op je telefoon kijken — volledige aanwezigheid is essentieel.",
    leerdoel: "Je leert om fysieke nabijheid bewust in te zetten als verbindingsmiddel.",
    bron: "Feldman et al. (2010) - Paternal skin-to-skin contact & oxytocin release",
  },
  {
    id: "verb_02_02",
    title: "Spiegelen van gezichtsuitdrukkingen",
    skill: "Verbinding",
    description: "Ga recht voor je baby zitten en spiegel alle gezichtsuitdrukkingen die je baby maakt. Als je baby lacht, lach jij. Trekt het een gezicht, doe jij hetzelfde.",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Facial mirroring activeert het spiegelneuronensysteem en vormt de basis voor empathie-ontwikkeling. Het kind ervaart: 'ik word gezien.'",
    skillTip: "Overdrijf je expressies licht — baby's reageren sterk op vergrote gezichtsuitdrukkingen.",
    vermijd: "Afgeleid zijn door andere dingen — dit werkt alleen met volle aandacht.",
    leerdoel: "Je leert om non-verbaal af te stemmen op de emotionele staat van je baby.",
    bron: "Meltzoff & Moore (1977) - Imitation in newborns & mirror neuron development",
  },
  {
    id: "verb_02_03",
    title: "Voorlezen met stemgeluid",
    skill: "Verbinding",
    description: "Pak een kartonnen boekje en lees voor met overdreven intonatie en verschillende stemmetjes. Wijs plaatjes aan en benoem wat je ziet.",
    duration: "10 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Infant-directed speech (verhoogde prosodie) stimuleert taalverwerving en versterkt de emotionele band. Voorlezen is een van de krachtigste verbindingsactiviteiten.",
    skillTip: "Laat je baby de pagina's omslaan — dat vergroot de betrokkenheid.",
    vermijd: "Snel doorlezen alsof het een taakje is — laat het langzaam en ontspannen gaan.",
    leerdoel: "Je leert om voorlezen te gebruiken als dagelijks verbindingsritueel.",
    bron: "Bus, van IJzendoorn & Pellegrini (1995) - Joint book reading & attachment",
  },
  {
    id: "verb_02_04",
    title: "Babymassage",
    skill: "Verbinding",
    description: "Masseer de beentjes en armpjes van je baby met zachte, ritmische bewegingen. Gebruik babyolie en praat zachtjes terwijl je masseert.",
    duration: "10 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Massage verlaagt cortisol en verhoogt oxytocine bij beide. Het tactiele contact versterkt de vader-kindbond en bevordert de lichamelijke ontwikkeling.",
    skillTip: "Volg het ritme van je baby — als die onrustig wordt, pauzeer en probeer het later opnieuw.",
    vermijd: "Te hard drukken of doorgaan als je baby tekenen van onbehagen toont.",
    leerdoel: "Je leert om door aanraking een diepe verbinding op te bouwen met je baby.",
    bron: "Field (2010) - Infant massage therapy & father-infant bonding",
  },
  {
    id: "verb_02_05",
    title: "Ochtendbegroeting",
    skill: "Verbinding",
    description: "Begin elke dag met je baby op te pakken, in de ogen te kijken en te zeggen: 'Goedemorgen lieverd! Papa is zo blij om je te zien!'",
    duration: "2 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Consistente, warme begroetingen creëren voorspelbare positieve momenten. Dit bouwt een veilige hechting op door betrouwbare emotionele beschikbaarheid.",
    skillTip: "Doe dit zelfs als je moe bent — consistentie is belangrijker dan enthousiasme.",
    vermijd: "Eerst je telefoon checken voordat je je baby begroet — laat hen de eerste zijn.",
    leerdoel: "Je leert om dagelijkse rituelen te gebruiken als ankers voor verbinding.",
    bron: "Bowlby (1988) - A Secure Base: consistent availability & greeting rituals",
  },
  {
    id: "verb_02_06",
    title: "Samen in bad",
    skill: "Verbinding",
    description: "Ga samen met je baby in bad. Speel zachtjes met water, blaas belletjes en geniet van het lichamelijke contact in het warme water.",
    duration: "15 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Gedeelde sensorische ervaringen in warm water bevorderen ontspanning en verbinding. Het is een multisensorische bonding-ervaring (warmte, aanraking, geluid).",
    skillTip: "Zorg dat het water de juiste temperatuur heeft (37 graden) en houd je baby altijd stevig vast.",
    vermijd: "Te veel speelgoed — de focus moet op jullie contact liggen, niet op spullen.",
    leerdoel: "Je leert om alledaagse verzorgingsmomenten om te vormen tot verbindingsmomenten.",
    bron: "Winnicott (1960) - The Maturational Processes & facilitating environment",
  },
  {
    id: "verb_02_07",
    title: "Dansen met je baby",
    skill: "Verbinding",
    description: "Zet rustige muziek op, neem je baby in je armen en dans langzaam door de kamer. Neurie mee en voel het ritme samen.",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Ritmische beweging samen stimuleert het vestibulaire systeem en versterkt de fysieke synchronisatie tussen vader en kind.",
    skillTip: "Kies muziek die jij fijn vindt — je ontspanning werkt door op je baby.",
    vermijd: "Wilde of snelle muziek — dat kan overprikkeling veroorzaken.",
    leerdoel: "Je leert om beweging en muziek in te zetten als verbindingsritueel.",
    bron: "Phillips-Silver & Trainor (2005) - Musical rhythm & social bonding in infancy",
  },
  {
    id: "verb_02_08",
    title: "Vertellen wat je doet",
    skill: "Verbinding",
    description: "Vertel je baby precies wat je aan het doen bent: 'Papa pakt nu je rompertje. Kijk, we doen je armpje hier doorheen. Zo, wat ben je mooi!'",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Sportcasting (het verbaliseren van acties) stimuleert taalverwerving en creëert een continue stroom van verbale verbinding. Het kind hoort: papa is bij mij, betrokken.",
    skillTip: "Doe dit ook bij vervelende dingen (luier verschonen, aankleden) — het maakt alles verbindend.",
    vermijd: "Baby-talk overdrijven — praat normaal maar met warmte in je stem.",
    leerdoel: "Je leert om alledaagse verzorgingsmomenten te gebruiken voor taalstimulering en verbinding.",
    bron: "Hart & Risley (1995) - Meaningful differences in everyday experience of young children",
  },
  {
    id: "verb_02_09",
    title: "Avondritueel creëren",
    skill: "Verbinding",
    description: "Creëer een vast avondritueel: dim het licht, zing hetzelfde slaapliedje, geef een kusje op het voorhoofd. Herhaal dit elke avond in dezelfde volgorde.",
    duration: "15 min",
    ageGroups: ["0-2"],
    difficulty: "expert",
    points: 25,
    psychologie: "Consistente rituelen bieden voorspelbaarheid en veiligheid. Een vast slaapritueel versterkt de hechting omdat het kind leert: papa is betrouwbaar, elke dag hetzelfde.",
    skillTip: "Houd het ritueel simpel genoeg om het ook vol te houden als je moe bent.",
    vermijd: "Het ritueel te vaak veranderen — de kracht zit in de herhaling.",
    leerdoel: "Je leert om consistente rituelen te bouwen die de basis vormen van veilige hechting.",
    bron: "Ainsworth et al. (1978) - Patterns of Attachment: predictability & security",
  },
  {
    id: "verb_02_10",
    title: "Solo papa-babydag",
    skill: "Verbinding",
    description: "Plan een hele dag alleen met je baby. Doe alles zelf: voeden, verschonen, spelen, slapen. Ervaar wat het betekent om de primaire verzorger te zijn.",
    duration: "30 min",
    ageGroups: ["0-2"],
    difficulty: "expert",
    points: 25,
    psychologie: "Vaders die solo zorgen ontwikkelen een eigenstandige hechtingsrelatie met hun baby, onafhankelijk van de moeder. Dit versterkt het vaderlijk zelfvertrouwen enorm.",
    skillTip: "Bereid praktisch voor (voeding, luiers), maar sta jezelf toe om je eigen ritme te vinden.",
    vermijd: "Constant je partner bellen voor advies — vertrouw op je eigen instinct.",
    leerdoel: "Je ontwikkelt zelfvertrouwen als zelfstandig zorgende vader.",
    bron: "Lamb (2010) - The Role of the Father in Child Development: primary caregiving",
  },

  // ── Verbinding · 3-5 jaar ────────────────────────────────
  {
    id: "verb_35_01",
    title: "Speciale papa-tijd",
    skill: "Verbinding",
    description: "Plan elke week een vast moment van 30 minuten 'papa-tijd'. Jouw kind mag kiezen wat jullie doen. Geef volledige aandacht zonder telefoon.",
    duration: "30 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Regelmatige, voorspelbare een-op-eentijd versterkt de hechtingsband. Het kind leert: ik ben belangrijk genoeg voor papa's onverdeelde aandacht.",
    skillTip: "Zet een timer zodat je kind ziet dat de tijd echt voor hen is.",
    vermijd: "De tijd inkorten of verplaatsen — betrouwbaarheid is de kern.",
    leerdoel: "Je leert om structureel kwaliteitstijd in te plannen en te beschermen.",
    bron: "Lamb (2004) - The Role of the Father: quality time & engagement",
  },
  {
    id: "verb_35_02",
    title: "Samen koken",
    skill: "Verbinding",
    description: "Laat je kleuter helpen met koken. Laat ze ingrediënten wassen, roeren in de pan, of brood besmeren. Praat over wat je samen maakt.",
    duration: "20 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Samen een taak uitvoeren (collaborative activity) bevordert verbinding door gedeelde doelen. Koken biedt sensorische ervaringen en succeservaringen.",
    skillTip: "Accepteer rommel als onderdeel van het proces — het gaat om het samen zijn, niet het resultaat.",
    vermijd: "Kritiek geven op hoe je kind de taak uitvoert — laat ze experimenteren.",
    leerdoel: "Je leert om dagelijkse taken om te vormen tot samenwerkingsmomenten.",
    bron: "Rogoff (2003) - Guided participation & collaborative learning",
  },
  {
    id: "verb_35_03",
    title: "Geheime handdruk",
    skill: "Verbinding",
    description: "Verzin samen een geheime handdruk of begroeting die alleen jullie tweeën kennen. Gebruik het bij begroeting, afscheid of als geheim signaal.",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Gedeelde geheimen en rituelen creëren een gevoel van exclusieve verbinding. Het kind ervaart: papa en ik hebben iets speciaals samen.",
    skillTip: "Laat je kind meedenken over de handdruk — hun ideeën maken het speciaal.",
    vermijd: "Het vergeten te doen — inconsistentie ondermijnt het ritueel.",
    leerdoel: "Je leert om unieke verbindingsrituelen te creëren die jullie relatie markeren.",
    bron: "Fiese (2006) - Family rituals & child well-being",
  },
  {
    id: "verb_35_04",
    title: "Samen een fort bouwen",
    skill: "Verbinding",
    description: "Bouw samen een fort of hut van kussens, dekens en stoelen. Kruip erin, doe een zaklamp aan en vertel verhalen of lees voor in jullie geheime plek.",
    duration: "30 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Het creëren van een gedeelde ruimte symboliseert veiligheid en exclusieve verbinding. Het fort wordt een fysieke representatie van jullie band.",
    skillTip: "Laat je kind de architect zijn — volg hun ideeën voor de constructie.",
    vermijd: "Het fort perfect willen maken — het samen bouwen is belangrijker dan het resultaat.",
    leerdoel: "Je leert om speels en creatief verbinding te maken via gedeelde projecten.",
    bron: "Panksepp (2004) - Affective Neuroscience: PLAY system & social bonding",
  },
  {
    id: "verb_35_05",
    title: "Dagelijks hoogtepunt delen",
    skill: "Verbinding",
    description: "Vraag elke avond bij het eten: 'Wat was het leukste van je dag?' Deel ook jouw hoogtepunt. Maak er een vast ritueel van.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Het delen van dagelijkse ervaringen bevordert emotionele geletterdheid en versterkt de gewoonte van open communicatie binnen het gezin.",
    skillTip: "Luister met oprechte interesse, ook als het verhaal over iets gaat dat jij niet belangrijk vindt.",
    vermijd: "Het corrigeren of aanvullen van het verhaal van je kind — laat ze het op hun manier vertellen.",
    leerdoel: "Je leert om een dagelijks gespreksritueel op te bouwen dat verbinding versterkt.",
    bron: "Fivush (2011) - Autobiographical memory & parent-child reminiscing",
  },
  {
    id: "verb_35_06",
    title: "Rollenspel samen",
    skill: "Verbinding",
    description: "Speel mee met het fantasiespel van je kleuter. Word de draak, de patiënt, de klant — welke rol ze je ook geven. Ga er volledig in op.",
    duration: "15 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Participeren in fantasiespel op het niveau van je kind toont respect voor hun wereld. Het versterkt de verbinding omdat je je aanpast aan hun belevingswereld.",
    skillTip: "Laat je kind de regie hebben — vraag 'wat moet ik nu doen?' in plaats van het spel te sturen.",
    vermijd: "Het spel overnemen of 'beter' maken — volg het script van je kind.",
    leerdoel: "Je leert om je kind's wereld binnen te treden via verbeeldend spel.",
    bron: "Vygotsky (1978) - Play as leading activity & zone of proximal development",
  },
  {
    id: "verb_35_07",
    title: "Natuur ontdekken samen",
    skill: "Verbinding",
    description: "Ga samen naar buiten en ontdek de natuur. Zoek insecten, bekijk blaadjes, luister naar vogels. Laat je kind leiden en stel vragen: 'Wat zie jij?'",
    duration: "20 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Gedeelde ontdekkingservaringen in de natuur stimuleren wonder en nieuwsgierigheid. De vader als mede-ontdekker versterkt de samenwerkingsband.",
    skillTip: "Geef geen biologielessen — verwonder je samen, zoals je kind dat doet.",
    vermijd: "Haast maken of een route plannen — laat je kind het tempo en de richting bepalen.",
    leerdoel: "Je leert om je te laten leiden door de nieuwsgierigheid van je kind.",
    bron: "Louv (2005) - Last Child in the Woods: nature & parent-child connection",
  },
  {
    id: "verb_35_08",
    title: "Slaapverhaaltje met je kind erin",
    skill: "Verbinding",
    description: "Verzin een slaapverhaaltje waarin je kind de hoofdpersoon is. Verwerk echte gebeurtenissen van die dag in een magisch avontuur.",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Gepersonaliseerde verhalen bevestigen de identiteit van het kind en versterken het gevoel gezien te worden. Het integreert dagelijkse ervaringen via narratief.",
    skillTip: "Vraag je kind om input: 'En wat denk je dat er toen gebeurde?' — maak het interactief.",
    vermijd: "Het verhaal gebruiken om een les te leren — het gaat om verbinding, niet educatie.",
    leerdoel: "Je leert om verhalen te gebruiken als persoonlijk verbindingsmiddel met je kind.",
    bron: "Bruner (1990) - Acts of Meaning: narrative identity & personal storytelling",
  },
  {
    id: "verb_35_09",
    title: "Emotiekaarten spelen",
    skill: "Verbinding",
    description: "Maak samen kaartjes met gezichten die verschillende emoties uitdrukken. Speel een spel: trek een kaart en vertel over een moment dat je je zo voelde. Doe het om de beurt.",
    duration: "15 min",
    ageGroups: ["3-5"],
    difficulty: "expert",
    points: 25,
    psychologie: "Het spel verbindt emotionele geletterdheid met wederzijdse openheid. Vader en kind delen gelijkwaardig, wat de hiërarchie tijdelijk opheft en intimiteit versterkt.",
    skillTip: "Deel ook echte emoties, niet alleen makkelijke — dat modelleert kwetsbaarheid.",
    vermijd: "De emoties van je kind corrigeren ('je hoeft niet bang te zijn') — alle emoties zijn welkom.",
    leerdoel: "Je leert om emotionele openheid te combineren met speelse verbinding.",
    bron: "Denham (1998) - Emotional Development in Young Children & emotion socialization",
  },
  {
    id: "verb_35_10",
    title: "Familiefoto-ritueel",
    skill: "Verbinding",
    description: "Bekijk samen oude familiefoto's. Vertel verhalen bij de foto's: 'Kijk, hier was je nog een baby. Papa droeg je op zijn schouders.' Laat je kind vragen stellen.",
    duration: "15 min",
    ageGroups: ["3-5"],
    difficulty: "expert",
    points: 25,
    psychologie: "Het delen van familieverhalen via foto's bouwt een gevoel van continuïteit en identiteit op. Het kind leert: ik heb een geschiedenis met papa, ik hoor erbij.",
    skillTip: "Kies foto's waar je kind zelf op staat — dat vergroot hun betrokkenheid.",
    vermijd: "Alleen maar foto's laten zien zonder verhaal — het verhaal maakt de verbinding.",
    leerdoel: "Je leert om familiegeschiedenis te gebruiken als bron van verbinding en identiteit.",
    bron: "Fivush, Bohanek & Duke (2008) - Family narratives & adolescent well-being",
  },

  // ── Verbinding · 6-9 jaar ────────────────────────────────
  {
    id: "verb_69_01",
    title: "Een-op-een uitje",
    skill: "Verbinding",
    description: "Plan een uitje met alleen je kind: naar het park, een museum, of gewoon een wandeling met een ijsje. Het gaat om de onverdeelde aandacht.",
    duration: "30 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Exclusieve een-op-eentijd communiceert: jij bent het waard dat papa al het andere laat vallen. Dit is vooral belangrijk voor kinderen met broers of zussen.",
    skillTip: "Laat je kind het uitje kiezen — hun keuze vertelt je veel over wat hen bezighoudt.",
    vermijd: "Het uitje volplannen met activiteiten — laat ruimte voor spontaniteit.",
    leerdoel: "Je leert om regelmatig exclusieve tijd te creëren voor elk kind apart.",
    bron: "Lamb (2010) - Father-child engagement: quality over quantity of time",
  },
  {
    id: "verb_69_02",
    title: "Interesse tonen in hun wereld",
    skill: "Verbinding",
    description: "Vraag je kind om jou iets te leren over hun favoriete onderwerp (Pokémon, dinosaurussen, Minecraft). Luister als een leerling en stel oprechte vragen.",
    duration: "15 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Het rolverwisselen (kind als expert) versterkt het zelfvertrouwen van het kind en toont respect voor hun interesses. Het overbrugt de generatiekloof.",
    skillTip: "Onthoud wat ze je vertellen en verwijs er later naar — dat bewijst dat je echt luisterde.",
    vermijd: "Doen alsof je geïnteresseerd bent terwijl je eigenlijk niet luistert — kinderen merken dat.",
    leerdoel: "Je leert om oprechte interesse te tonen in wat jouw kind bezighoudt.",
    bron: "Csikszentmihalyi (1997) - Flow & intrinsic motivation in parent-child interactions",
  },
  {
    id: "verb_69_03",
    title: "Samen een project starten",
    skill: "Verbinding",
    description: "Begin samen een project: bouw een vogelhuisje, start een moestuin, of maak een stripverhaal. Werk er regelmatig samen aan.",
    duration: "30 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Langlopende gezamenlijke projecten bouwen duurzame verbinding op. Het geeft je kind iets om naar uit te kijken en versterkt het gevoel van samenwerking.",
    skillTip: "Verdeel taken eerlijk — laat je kind echte verantwoordelijkheid dragen.",
    vermijd: "Het project overnemen als het niet perfect gaat — het is van jullie samen.",
    leerdoel: "Je leert om duurzame verbinding te bouwen via gedeelde langetermijnprojecten.",
    bron: "Rogoff (1990) - Apprenticeship in Thinking & guided participation",
  },
  {
    id: "verb_69_04",
    title: "Bedtijdgesprek",
    skill: "Verbinding",
    description: "Ga elke avond vijf minuten op de rand van het bed zitten. Vraag: 'Waar denk je aan?' of 'Zit er iets in je hoofd?' Luister zonder oordeel.",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Het moment voor het slapen is vaak wanneer kinderen het meest open zijn. De duisternis en rust verlagen de drempel om gevoelens te delen.",
    skillTip: "Stel open vragen en laat stiltes vallen — geef je kind de ruimte om na te denken.",
    vermijd: "Het gesprek gebruiken om dingen uit te vragen of problemen op te lossen.",
    leerdoel: "Je leert om het bedtijdmoment in te zetten als veilig gespreksmoment.",
    bron: "Palkovitz (2002) - Involved fathering & transitional moments",
  },
  {
    id: "verb_69_05",
    title: "Samen bewegen",
    skill: "Verbinding",
    description: "Doe samen een fysieke activiteit: voetballen, fietsen, zwemmen of gewoon stoeien op de grond. Lach, beweeg en geniet van elkaars energie.",
    duration: "20 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Fysiek samen spelen activeert het PLAY-systeem in de hersenen en versterkt de sociale band. Vaders zijn van nature geneigd tot rough-and-tumble play, wat uniek bijdraagt.",
    skillTip: "Pas je niveau aan — laat je kind soms winnen, maar daag ook uit.",
    vermijd: "Te competitief zijn — het gaat om samen plezier hebben, niet om winnen.",
    leerdoel: "Je leert om fysieke activiteit te gebruiken als krachtig verbindingsmiddel.",
    bron: "Panksepp (1998) - Affective Neuroscience: PLAY system & father-child rough play",
  },
  {
    id: "verb_69_06",
    title: "Brief aan je kind schrijven",
    skill: "Verbinding",
    description: "Schrijf een brief aan je kind over wat je leuk vindt aan hen. Noem specifieke dingen: 'Ik vind het knap hoe jij...' en 'Ik geniet ervan als wij samen...' Geef het als verrassing.",
    duration: "15 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Geschreven woorden van waardering hebben een blijvende impact. Kinderen bewaren zulke brieven vaak jarenlang als tastbaar bewijs van vaderliefde.",
    skillTip: "Wees specifiek — 'ik vind het leuk hoe je je zusje helpt' raakt meer dan 'je bent lief'.",
    vermijd: "Het een beoordelingsmoment maken ('je bent goed in... maar je moet ook...').",
    leerdoel: "Je leert om waardering uit te drukken via geschreven, blijvende woorden.",
    bron: "Chapman & Campbell (2012) - The Five Love Languages of Children: words of affirmation",
  },
  {
    id: "verb_69_07",
    title: "Familiespelletjesavond",
    skill: "Verbinding",
    description: "Organiseer een vaste avond per week voor bordspellen of kaartspellen als gezin. Wissel wie mag kiezen welk spel er gespeeld wordt.",
    duration: "30 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Regelmatige, gestructureerde gezinsactiviteiten creëren voorspelbare positieve momenten. Het leren omgaan met winnen en verliezen biedt ook emotionele lessen.",
    skillTip: "Model goed verliesgedrag — kinderen leren omgaan met teleurstelling door naar jou te kijken.",
    vermijd: "Je kind altijd laten winnen — dat ondermijnt het leermoment en de echtheid.",
    leerdoel: "Je leert om gestructureerde familierituelen op te zetten die verbinding bevorderen.",
    bron: "Fiese et al. (2002) - Family routines & rituals as protective factors",
  },
  {
    id: "verb_69_08",
    title: "Gedeeld avontuur plannen",
    skill: "Verbinding",
    description: "Plan samen met je kind een mini-avontuur: een tocht door het bos, een speurtocht in de buurt, of een picknick op een nieuwe plek. Plan het samen en voer het uit.",
    duration: "30 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Gedeelde avonturen creëren episodische herinneringen die de relatie versterken. Het samen plannen geeft het kind eigenaarschap en vergroot de anticipatievreugde.",
    skillTip: "Laat je kind meehelpen met de voorbereiding — inpakken, kaart bekijken, eten kiezen.",
    vermijd: "Alles zelf regelen — het samen voorbereiden is een deel van de verbinding.",
    leerdoel: "Je leert om gedeelde ervaringen te creëren die bijzondere herinneringen worden.",
    bron: "Nelson & Fivush (2004) - Autobiographical memory & shared experiences",
  },
  {
    id: "verb_69_09",
    title: "Emotioneel inchecken",
    skill: "Verbinding",
    description: "Introduceer een emotie-thermometer: elke dag vraag je kind een cijfer van 1-10 te geven voor hoe het zich voelt. Vraag bij een laag cijfer: 'Wil je erover praten?'",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "expert",
    points: 25,
    psychologie: "Een dagelijkse emotionele check-in normaliseert het praten over gevoelens en bouwt een gewoonte op van emotionele communicatie binnen de vader-kindrelatie.",
    skillTip: "Geef zelf ook een cijfer — dat modelleert dat iedereen ups en downs heeft.",
    vermijd: "Alarmeren bij een laag cijfer — normaliseer dat het soms een 4 of 5 is.",
    leerdoel: "Je leert om een systeem op te zetten voor dagelijks emotioneel contact.",
    bron: "Gottman (1997) - Emotion coaching: awareness & communication of feelings",
  },
  {
    id: "verb_69_10",
    title: "Traditie starten",
    skill: "Verbinding",
    description: "Start een nieuwe traditie die alleen van jullie is: elke zaterdag pannenkoeken bakken, eerste dag van de maand een brief schrijven, of elk seizoen een boom planten.",
    duration: "30 min",
    ageGroups: ["6-9"],
    difficulty: "expert",
    points: 25,
    psychologie: "Unieke vader-kindtradities creëren een gevoel van continuïteit en bijzonderheid. Het kind draagt deze tradities vaak door naar volwassenheid.",
    skillTip: "Laat je kind mee beslissen over de traditie — dan voelt het als iets van jullie samen.",
    vermijd: "Te veel tradities tegelijk starten — kies er één en houd het vol.",
    leerdoel: "Je leert om duurzame tradities te creëren die jullie band over de jaren versterken.",
    bron: "Wolin & Bennett (1984) - Family rituals & intergenerational transmission",
  },

  // ── Verbinding · 10-12 jaar ──────────────────────────────
  {
    id: "verb_12_01",
    title: "Één-op-één date",
    skill: "Verbinding",
    description: "Plan een maandelijkse 'date' met je kind. Ga samen uit eten, naar de bioscoop, of doe iets dat zij kiezen. Het gaat om exclusieve tijd samen.",
    duration: "30 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Pre-teens beginnen zich meer op leeftijdsgenoten te richten. Regelmatige één-op-één dates houden de ouder-kindband sterk in deze transitiefase.",
    skillTip: "Laat je kind kiezen wat jullie doen — hun keuze geeft je inzicht in hun wereld.",
    vermijd: "De date omvormen tot een 'goed gesprek' — laat het ontspannen zijn.",
    leerdoel: "Je leert om bewust tijd te beschermen voor je pre-teen ondanks drukke schema's.",
    bron: "Steinberg & Silk (2002) - Parenting adolescents: maintaining closeness",
  },
  {
    id: "verb_12_02",
    title: "Interesse in hun hobby",
    skill: "Verbinding",
    description: "Vraag je kind om je mee te nemen in hun hobby. Speel hun favoriete game, luister naar hun muziek, of kijk hun YouTube-video's mee. Oordeel niet, maar wees nieuwsgierig.",
    duration: "20 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Pre-teens voelen zich begrepen wanneer ouders oprechte interesse tonen in hun wereld. Het overbruggen van de culturele kloof versterkt de verbinding.",
    skillTip: "Stel vragen als leerling, niet als controleur: 'Waarom vind je dit leuk? Leg het me uit!'",
    vermijd: "Hun interesses afkraken of vergelijken met 'hoe het vroeger was'.",
    leerdoel: "Je leert om je eigen referentiekader los te laten en de wereld van je kind binnen te stappen.",
    bron: "Larson et al. (1996) - Changes in adolescents' daily interactions with families",
  },
  {
    id: "verb_12_03",
    title: "Samen sporten of bewegen",
    skill: "Verbinding",
    description: "Doe wekelijks samen een sportieve activiteit: hardlopen, basketballen, klimmen, of fietsen. Maak het een vast onderdeel van jullie week.",
    duration: "30 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Fysieke activiteit samen stimuleert endorfines en creëert een non-verbale verbindingscontext. Pre-teens praten vaak makkelijker tijdens beweging.",
    skillTip: "Kies iets wat jullie beiden leuk vinden — of iets nieuws dat jullie samen kunnen leren.",
    vermijd: "Te prestatiegericht zijn — het doel is verbinding, niet prestatie.",
    leerdoel: "Je leert om beweging structureel in te zetten als verbindingsmoment.",
    bron: "Sabo & Veliz (2008) - Go Out and Play: father-child sport participation & bonding",
  },
  {
    id: "verb_12_04",
    title: "Maaltijd samen bereiden",
    skill: "Verbinding",
    description: "Kook samen een maaltijd van begin tot eind. Laat je kind het recept kiezen, samen boodschappen doen en koken. Eet samen wat jullie gemaakt hebben.",
    duration: "30 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Samen koken combineert samenwerking, creativiteit en een tastbaar resultaat. Het biedt een natuurlijke context voor gesprek zonder de druk van face-to-face.",
    skillTip: "Geef echte verantwoordelijkheid — laat ze snijden, bakken, afproeven.",
    vermijd: "Het kookproces overnemen als het niet snel genoeg gaat.",
    leerdoel: "Je leert om dagelijkse activiteiten om te bouwen tot samenwerkings- en verbindingsmomenten.",
    bron: "Eisenberg et al. (2006) - Shared family activities & adolescent development",
  },
  {
    id: "verb_12_05",
    title: "Luisteren naar hun muziek",
    skill: "Verbinding",
    description: "Vraag je kind: 'Zet eens jouw favoriete playlist op.' Luister samen en vraag: 'Wat vind je aan dit nummer? Waar gaat het over?' Deel ook een nummer van jou.",
    duration: "15 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Muziek is voor pre-teens een belangrijk middel voor identiteitsexpressie. Door hun muziek serieus te nemen, erken je hun zich ontwikkelende identiteit.",
    skillTip: "Oordeel niet over de muziek — zelfs als het je niet aanspreekt, toon interesse.",
    vermijd: "Zeggen 'in mijn tijd was muziek beter' — dat creëert afstand.",
    leerdoel: "Je leert om de culturele wereld van je pre-teen als ingang voor verbinding te gebruiken.",
    bron: "North & Hargreaves (2008) - Music & adolescent identity formation",
  },
  {
    id: "verb_12_06",
    title: "Open gesprek over hun leven",
    skill: "Verbinding",
    description: "Kies een rustig moment en vraag oprecht: 'Hoe gaat het eigenlijk met je? Op school, met vrienden, in het algemeen?' Luister zonder te adviseren.",
    duration: "15 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Pre-teens delen minder spontaan dan jongere kinderen. Een bewuste, niet-oordelende uitnodiging tot gesprek houdt de communicatiekanalen open.",
    skillTip: "Stel vervolgvragen in plaats van advies te geven: 'Hoe was dat voor jou?'",
    vermijd: "Het gesprek overnemen met eigen ervaringen of meteen oplossingen aandragen.",
    leerdoel: "Je leert om open gesprekken te voeren die de verbinding verdiepen zonder te adviseren.",
    bron: "Ginott (1965) - Between Parent and Child: reflective listening",
  },
  {
    id: "verb_12_07",
    title: "Gezamenlijk vrijwilligerswerk",
    skill: "Verbinding",
    description: "Doe samen vrijwilligerswerk: help in een buurthuis, ruim zwerfafval op, of help een oudere buurman. Bespreek achteraf wat het met jullie deed.",
    duration: "30 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Samen bijdragen aan de gemeenschap versterkt de band en ontwikkelt empathie en verantwoordelijkheidsgevoel. Het geeft een gedeeld gevoel van zingeving.",
    skillTip: "Kies iets dat bij de interesses van je kind past — dat vergroot de betrokkenheid.",
    vermijd: "Het als verplichting presenteren — laat het voelen als iets dat jullie samen kiezen.",
    leerdoel: "Je leert om verbinding te bouwen door samen bij te dragen aan de wereld om jullie heen.",
    bron: "Youniss & Yates (1997) - Community service & identity development in youth",
  },
  {
    id: "verb_12_08",
    title: "Vader-kind filmavond",
    skill: "Verbinding",
    description: "Organiseer een vaste filmavond: laat je kind om de beurt een film kiezen. Maak popcorn, kruip samen op de bank en bespreek de film achteraf.",
    duration: "30 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Gedeelde media-ervaringen bieden gespreksstof en een venster op elkaars smaak en waarden. De film wordt een gezamenlijk referentiepunt.",
    skillTip: "Kijk de film die je kind kiest echt met aandacht — niet op je telefoon naast de bank.",
    vermijd: "De filmkeuze van je kind afwijzen of steeds jouw keuze doordrukken.",
    leerdoel: "Je leert om media-ervaringen te gebruiken als basis voor verbindende gesprekken.",
    bron: "Coyne et al. (2014) - Media use & parent-child relationship quality",
  },
  {
    id: "verb_12_09",
    title: "Levensverhalen delen",
    skill: "Verbinding",
    description: "Vertel je kind verhalen uit je eigen jeugd: grappige, spannende of kwetsbare momenten. Vraag: 'Wil je weten hoe het was toen papa zo oud was als jij?'",
    duration: "15 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 25,
    psychologie: "Intergenerationele verhalen versterken het gevoel van familiecontinuïteit en identiteit. Het maakt je als vader menselijker en toegankelijker voor je pre-teen.",
    skillTip: "Deel ook verhalen over fouten en onzekerheden — dat normaliseert hun eigen worstelingen.",
    vermijd: "Alleen succesverhalen vertellen — dat creëert onrealistisch druk.",
    leerdoel: "Je leert om je eigen levenservaring in te zetten als bron van verbinding en wijsheid.",
    bron: "McAdams (2001) - The psychology of life stories & narrative identity",
  },
  {
    id: "verb_12_10",
    title: "Toekomstdromen verkennen",
    skill: "Verbinding",
    description: "Vraag je kind: 'Wat zou je later willen doen? Waar droom je van?' Luister zonder te sturen. Vraag door: 'Hoe zou dat eruitzien? Wat spreekt je daarin aan?'",
    duration: "15 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 25,
    psychologie: "Pre-teens beginnen met identiteitsvorming. Serieus luisteren naar hun toekomstdromen bevestigt hun zich ontwikkelende zelfbeeld en versterkt jullie band.",
    skillTip: "Neem elk antwoord serieus, ook als het onrealistisch lijkt — het gaat om hun gevoel gehoord te worden.",
    vermijd: "Corrigeren ('dat wordt moeilijk') of sturen ('misschien is dit beter') — dit is hun moment.",
    leerdoel: "Je leert om een veilige ruimte te bieden voor de toekomstverkenning van je kind.",
    bron: "Erikson (1968) - Identity: Youth and Crisis & identity exploration",
  },

  // ── Verbinding · 13-16 jaar ──────────────────────────────
  {
    id: "verb_16_01",
    title: "Samen een ervaring delen",
    skill: "Verbinding",
    description: "Doe iets nieuws samen: een escape room, een workshop, een concert of een sportwedstrijd bezoeken. Kies iets dat voor jullie beiden nieuw is.",
    duration: "30 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Gedeelde nieuwe ervaringen activeren dopamine en creëren sterke episodische herinneringen. Het 'samen iets voor het eerst doen' versterkt de band uniek.",
    skillTip: "Laat je tiener mee kiezen — hun betrokkenheid bij de keuze vergroot het plezier.",
    vermijd: "Iets kiezen dat alleen jij leuk vindt en je tiener verplichten mee te gaan.",
    leerdoel: "Je leert om nieuwe gedeelde ervaringen op te zoeken als bron van verbinding.",
    bron: "Aron et al. (2000) - Novel experiences & relationship satisfaction",
  },
  {
    id: "verb_16_02",
    title: "Autorit-gesprekken",
    skill: "Verbinding",
    description: "Gebruik autoritten bewust als gespreksmoment. Geen muziek, geen telefoon — vraag hoe het gaat, wat hen bezighoudt, waar ze over nadenken.",
    duration: "15 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Side-by-side settings (naast elkaar in de auto) verlagen de emotionele druk van face-to-face gesprekken. Tieners openen zich vaak beter zonder direct oogcontact.",
    skillTip: "Begin niet meteen met diepe vragen — warm op met lichte onderwerpen.",
    vermijd: "De autorit gebruiken voor kritiek of moeilijke onderwerpen die escalatie kunnen veroorzaken.",
    leerdoel: "Je leert om alledaagse momenten om te vormen tot kansen voor verbinding.",
    bron: "Steinberg (2001) - We Know Some Things: parent-adolescent communication",
  },
  {
    id: "verb_16_03",
    title: "Beschikbaar zijn zonder agenda",
    skill: "Verbinding",
    description: "Wees bewust aanwezig in huis zonder agenda. Zit in de kamer, lees een boek, en wees beschikbaar als je tiener toevallig zin heeft om te praten.",
    duration: "30 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Emotionele beschikbaarheid is de basis van veilige hechting bij tieners. Aanwezigheid zonder druk communiceert: 'Ik ben er als je me nodig hebt.'",
    skillTip: "Leg je telefoon weg zodat je tiener ziet dat je echt beschikbaar bent.",
    vermijd: "Aandacht vragen als je tiener niet wil praten — gewoon er zijn is genoeg.",
    leerdoel: "Je leert dat beschikbaarheid zonder actie een krachtige vorm van verbinding is.",
    bron: "Biringen (2000) - Emotional availability & adolescent attachment security",
  },
  {
    id: "verb_16_04",
    title: "Hun vrienden leren kennen",
    skill: "Verbinding",
    description: "Nodig de vrienden van je tiener thuis uit. Maak eten, wees gastvrij, en toon interesse zonder je op te dringen. Leer hun namen en vraag later hoe het met ze gaat.",
    duration: "30 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Door vrienden welkom te heten, toon je respect voor de sociale wereld van je tiener. Het geeft je ook inzicht in hun leven zonder intrusief te zijn.",
    skillTip: "Wees de 'relaxte vader' — vriendelijk en aanwezig, maar niet te veel op de voorgrond.",
    vermijd: "Proberen cool of grappig te zijn voor hun vrienden — dat is pijnlijk voor tieners.",
    leerdoel: "Je leert om de sociale wereld van je tiener te verwelkomen en te respecteren.",
    bron: "Brown & Bakken (2011) - Parenting and peer relationships in adolescence",
  },
  {
    id: "verb_16_05",
    title: "Ochtend- of avondmoment",
    skill: "Verbinding",
    description: "Creëer een kort dagelijks contactmoment: samen koffie/thee drinken 's ochtends of even kletsen voor het slapengaan. Vijf minuten volledige aandacht.",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kleine, consistente contactmomenten zijn effectiever dan incidentele grote gesprekken. Ze houden de communicatielijn open in de drukke tienerjaren.",
    skillTip: "Pas het moment aan op het ritme van je tiener — niet iedereen is een ochtendmens.",
    vermijd: "Het moment volstoppen met vragen — soms is samen stilzitten ook verbinding.",
    leerdoel: "Je leert om micro-momenten van verbinding te creëren in het dagelijks ritme.",
    bron: "Offer (1969) - The Psychological World of the Teenager: daily rituals",
  },
  {
    id: "verb_16_06",
    title: "Diepgaand gesprek over waarden",
    skill: "Verbinding",
    description: "Bespreek met je tiener een actueel thema vanuit waarden: rechtvaardigheid, eerlijkheid, moed. Vraag: 'Wat vind jij daarvan? Hoe zou jij het aanpakken?'",
    duration: "20 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Tieners zijn bezig met identiteitsvorming en zoeken actief naar waarden. Een vader die op gelijkwaardig niveau meedenkt, wordt een waardevolle gesprekspartner.",
    skillTip: "Deel je eigen mening, maar presenteer het als perspectief, niet als waarheid.",
    vermijd: "Preken of moraliseren — dat sluit tieners af in plaats van ze te openen.",
    leerdoel: "Je leert om op gelijkwaardig niveau met je tiener te spreken over wat ertoe doet.",
    bron: "Erikson (1968) - Identity formation & values exploration in adolescence",
  },
  {
    id: "verb_16_07",
    title: "Samen iets leren",
    skill: "Verbinding",
    description: "Kies iets dat je samen wilt leren: een instrument, een taal, een sportieve vaardigheid. Wees allebei beginner en lach om jullie fouten.",
    duration: "30 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Samen leren als gelijken doorbreekt de ouder-kindhiërarchie. Het toont je tiener dat jij ook feilbaar en leerbaar bent, wat de relatie gelijkwaardiger maakt.",
    skillTip: "Kies echt iets waar je geen ervaring mee hebt — echte kwetsbaarheid is krachtiger.",
    vermijd: "Iets kiezen waar jij al goed in bent en dan 'lesjes geven'.",
    leerdoel: "Je leert om de leerpositie te delen en daarmee de relatie te verdiepen.",
    bron: "Dweck (2006) - Growth mindset in parent-child learning relationships",
  },
  {
    id: "verb_16_08",
    title: "Eerlijk zijn over je eigen jeugd",
    skill: "Verbinding",
    description: "Deel een eerlijk verhaal uit je eigen tienerjaren: een fout die je maakte, een moeilijke periode, een les die je leerde. Wees kwetsbaar en echt.",
    duration: "15 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Authentieke verhalen over eigen jeugdfouten normaliseren de worsteling van de adolescentie. Het verlaagt de afstand en maakt je als vader benaderbaar.",
    skillTip: "Vertel het verhaal zonder moraal eraan te koppelen — laat je tiener zelf de conclusie trekken.",
    vermijd: "Verhalen vertellen om te bewijzen dat je het moeilijker had ('in mijn tijd...').",
    leerdoel: "Je leert om je eigen levenservaring op een authentieke, niet-belerende manier te delen.",
    bron: "McAdams (2001) - Life stories & intergenerational narrative transmission",
  },
  {
    id: "verb_16_09",
    title: "Gezamenlijk jaarlijks ritueel",
    skill: "Verbinding",
    description: "Creëer een jaarlijks vader-kindmoment: een kampeerweekend, een dagtrip naar een speciale plek, of een jaarlijkse uitdaging. Maak het een traditie.",
    duration: "30 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 25,
    psychologie: "Jaarlijkse rituelen bieden ankerpunten in de relatie over de jaren heen. Ze creëren een gevoel van continuïteit en bijzonderheid die de adolescentie overstijgt.",
    skillTip: "Begin klein en bouw het uit — het hoeft niet spectaculair te zijn om betekenisvol te worden.",
    vermijd: "Het ritueel laten vervallen bij drukke agenda's — consistentie maakt het waardevol.",
    leerdoel: "Je leert om langetermijnrituelen te bouwen die jullie band duurzaam versterken.",
    bron: "Wolin & Bennett (1984) - Family rituals & relationship continuity across generations",
  },
  {
    id: "verb_16_10",
    title: "Onvoorwaardelijke acceptatie uitspreken",
    skill: "Verbinding",
    description: "Zeg op een rustig moment tegen je tiener: 'Ik wil dat je weet dat ik van je houd, ongeacht je cijfers, keuzes of fouten. Er is niets wat je kunt doen waardoor dat verandert.'",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 25,
    psychologie: "Onvoorwaardelijke acceptatie is de kern van veilige hechting. In de adolescentie, wanneer tieners experimenteren en grenzen testen, is deze boodschap cruciaal voor hun identiteitsontwikkeling.",
    skillTip: "Zeg het niet als reactie op iets — zeg het spontaan, als er niets aan de hand is.",
    vermijd: "Er een 'maar' achteraan plakken ('ik houd van je, maar je moet wel...').",
    leerdoel: "Je leert om onvoorwaardelijke liefde expliciet en zonder voorwaarden uit te spreken.",
    bron: "Rogers (1961) - On Becoming a Person: unconditional positive regard in parenting",
  },

  // ═══ BATCH 2: Reflectie wordt hier toegevoegd ═══
];
