import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_28: InteractiveTask[] = [
  // ═══════════════════════════════════════════════════════════════
  // AANWEZIGHEID — Bonuskind (10 taken)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "bonus_aanw_01",
    title: "Rustig naast je bonuskind",
    skill: "Aanwezigheid",
    description: "Ga vandaag 10 minuten naast je bonuskind zitten zonder iets te vragen. Wees er gewoon.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Bonuskinderen testen onbewust of je er echt bent zonder voorwaarden. Stilzwijgende aanwezigheid communiceert: 'Ik hoef niets van je, ik ben er gewoon.' Dit verlaagt de waakzaamheid van het kind.",
    skillTip: "Geen vragen stellen, geen activiteit forceren. Pak een boek of doe rustig iets naast het kind. Laat het kind bepalen of er contact komt.",
    vermijd: "Direct vragen 'wat is er?' of activiteiten opleggen. Dat voelt als druk.",
    leerdoel: "Je leert aanwezig te zijn zonder verwachtingen, de basis van vertrouwen opbouwen met een bonuskind.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_aanw_02",
    title: "Begroeting op hun tempo",
    skill: "Aanwezigheid",
    description: "Wanneer je bonuskind binnenkomt na een verblijf bij de andere ouder, begroet kort en warm maar geef ruimte om aan te komen.",
    duration: "5 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "De overgang tussen twee huishoudens is een van de meest stressvolle momenten voor kinderen in samengestelde gezinnen. Ze hebben tijd nodig om zich te heroriënteren zonder overenthousiaste begroetingen.",
    skillTip: "Zeg iets als: 'Fijn dat je er bent.' Laat daarna even ruimte. Het kind bepaalt wanneer het klaar is voor meer contact.",
    vermijd: "Overdreven enthousiasme of meteen vragen stellen over het verblijf bij de andere ouder.",
    leerdoel: "Je leert de overgang tussen twee huizen te respecteren en ruimte te bieden voor het aankomstproces.",
    bron: "Bray & Kelly (1998) - Stepfamilies: Love, Marriage, and Parenting in the First Decade",
    themes: ["bonuskind", "samengesteld_gezin", "co-ouderschap"],
  },
  {
    id: "bonus_aanw_03",
    title: "Meekijken zonder meedoen",
    skill: "Aanwezigheid",
    description: "Kijk 10 minuten met oprechte interesse naar iets waar je bonuskind mee bezig is, zonder je ermee te bemoeien.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen voelen zich gezien wanneer een volwassene oprecht geïnteresseerd kijkt. Voor bonuskinderen is dit extra krachtig omdat het bewijst dat je aandacht niet voorwaardelijk is.",
    skillTip: "Maak af en toe een korte opmerking: 'Dat ziet er gaaf uit' of 'Je bent hier goed in.' Geen advies geven.",
    vermijd: "Het overnemen, verbeteren, of ongevraagd meehelpen. Dat ondermijnt het gevoel van competentie.",
    leerdoel: "Je leert aanwezig te zijn als geïnteresseerde toeschouwer, een zachte manier om verbinding op te bouwen.",
    bron: "Hetherington & Kelly (2002) - For Better or For Worse: Divorce Reconsidered",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_aanw_04",
    title: "Aanwezig bij het slapengaan",
    skill: "Aanwezigheid",
    description: "Bied aan om vanavond bij het slapengaan even langs te komen. Respecteer het als je bonuskind liever de biologische ouder wil.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Het slapengaan is een kwetsbaar moment. Bonuskinderen kiezen vaak de biologische ouder, wat pijnlijk kan voelen. Toch is het aanbod op zich al een investering in de relatie.",
    skillTip: "Zeg: 'Ik kom even welterusten zeggen als je dat fijn vindt.' Accepteer een 'nee' zonder zichtbare teleurstelling.",
    vermijd: "Je afgewezen voelen als het kind de biologische ouder kiest. Dit is normaal en gezond loyaliteitsgedrag.",
    leerdoel: "Je leert aanbieden zonder verwachten, en afwijzing niet persoonlijk te nemen.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_aanw_05",
    title: "Er zijn bij een moeilijk moment",
    skill: "Aanwezigheid",
    description: "Als je bonuskind verdrietig of boos is, blijf in de buurt zonder het op te lossen. Zeg: 'Ik ben hier als je me nodig hebt.'",
    duration: "15 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Bij emotionele stress zoeken kinderen hun primaire hechtingsfiguur. Als bonusouder is het krachtigst om beschikbaar te zijn zonder te concurreren met de biologische ouder.",
    skillTip: "Ga in dezelfde ruimte zitten, op enige afstand. Laat merken dat je er bent zonder aan te dringen. Een glas water neerzetten kan genoeg zijn.",
    vermijd: "Het probleem proberen op te lossen of zeggen 'zo erg is het niet.' Laat de biologische ouder de eerste troost bieden als het kind dat wil.",
    leerdoel: "Je leert emotionele nabijheid bieden zonder de rol van de biologische ouder over te nemen.",
    bron: "Ganong & Coleman (2017) - Stepfamily Relationships: Development, Dynamics, and Interventions",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_aanw_06",
    title: "Een vast moment samen",
    skill: "Aanwezigheid",
    description: "Plan een wekelijks terugkerend moment van 15 minuten met alleen je bonuskind. Laat het kind kiezen wat jullie doen.",
    duration: "15 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Voorspelbaarheid is cruciaal voor bonuskinderen die al veel wisselingen hebben meegemaakt. Een vast ritueel communiceert: 'Jij bent belangrijk genoeg voor mijn vaste aandacht.'",
    skillTip: "Kies een specifiek moment (bijv. zondagochtend) en bescherm dit. Laat het kind de activiteit bepalen, zelfs als het simpel is.",
    vermijd: "Het moment afzeggen of verschuiven. Dat bevestigt het wantrouwen dat bonuskinderen vaak hebben.",
    leerdoel: "Je leert consistentie te bieden als fundament voor een groeiende vertrouwensrelatie.",
    bron: "Bray & Kelly (1998) - Stepfamilies: Love, Marriage, and Parenting in the First Decade",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_aanw_07",
    title: "Aanwezig bij de schoolpoort",
    skill: "Aanwezigheid",
    description: "Haal je bonuskind een keer op van school. Bespreek dit vooraf met je partner en het kind zodat het niet onverwacht komt.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Ophalen van school is een zichtbaar teken van betrokkenheid. Voor bonuskinderen kan dit spannend zijn (klasgenoten zien een 'andere' volwassene), daarom is afstemming vooraf essentieel.",
    skillTip: "Vraag het kind van tevoren: 'Vind je het oké als ik je morgen ophaal?' Respecteer een 'nee' zonder oordeel.",
    vermijd: "Het als verrassing doen. Bonuskinderen hebben behoefte aan voorspelbaarheid bij publieke situaties.",
    leerdoel: "Je leert stapsgewijs aanwezig te zijn in het leven van je bonuskind buiten het huis.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_aanw_08",
    title: "Mee naar een activiteit",
    skill: "Aanwezigheid",
    description: "Ga mee naar een sporttraining of hobby van je bonuskind als toeschouwer. Wees er, zonder de spotlight te zoeken.",
    duration: "20 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Aanwezigheid bij activiteiten toont toewijding. Maar voor bonuskinderen kan een bonusvader langs de lijn ook loyaliteitsconflicten oproepen als de biologische vader er ook is.",
    skillTip: "Check vooraf bij je partner of de biologische vader ook komt. Als dat zo is, overleg of jouw aanwezigheid op prijs wordt gesteld. Wees bescheiden in je rol.",
    vermijd: "Gaan zitten naast de biologische vader als er spanning is, of het kind coachen vanaf de zijlijn.",
    leerdoel: "Je leert aanwezig te zijn op een manier die het kind ondersteunt zonder loyaliteitsspanning te creëren.",
    bron: "Ganong & Coleman (2017) - Stepfamily Relationships: Development, Dynamics, and Interventions",
    themes: ["bonuskind", "samengesteld_gezin", "co-ouderschap"],
  },
  {
    id: "bonus_aanw_09",
    title: "Stille autorit",
    skill: "Aanwezigheid",
    description: "Rijd een keer met je bonuskind in de auto zonder de radio aan te zetten. Laat stilte toe of praat als het kind dat initieert.",
    duration: "15 min",
    ageGroups: ["10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Autorijden creëert een unieke setting: geen oogcontact nodig, gedeelde richting, veilige afstand. Veel kinderen en tieners openen zich juist in de auto wanneer er geen druk is.",
    skillTip: "Zet de radio uit en laat de stilte bestaan. Als het kind praat, luister dan zonder meteen te reageren. Soms is een knikje genoeg.",
    vermijd: "De stilte opvullen met vragen. Laat het kind de ruimte vullen als het daar klaar voor is.",
    leerdoel: "Je leert dat aanwezigheid zonder woorden soms de diepste verbinding faciliteert.",
    bron: "Dunn (2002) - Children's Relationships with their Nonresident Fathers",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_aanw_10",
    title: "Brief aan je bonuskind",
    skill: "Aanwezigheid",
    description: "Schrijf een kort briefje aan je bonuskind waarin je vertelt wat je waardeert aan jullie contact. Leg het op hun kussen of in hun tas.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Geschreven woorden hebben een bijzondere kracht: het kind kan ze herlezen wanneer het wil. Voor bonuskinderen die twijfelen over hun plek, kan een briefje een tastbaar anker zijn.",
    skillTip: "Houd het kort en authentiek. Bijvoorbeeld: 'Ik vind het fijn dat jij in mijn leven bent. Bedankt dat je mij een kans geeft.' Geen verwachtingen uitspreken.",
    vermijd: "Te veel beloven of de relatie groter maken dan die nu is. Eerlijkheid is krachtiger dan overdrijving.",
    leerdoel: "Je leert je waardering uitdrukken op een manier die het kind kan bewaren en herlezen.",
    bron: "Chapman & Campbell (2016) - The 5 Love Languages of Children",
    themes: ["bonuskind", "samengesteld_gezin"],
  },

  // ═══════════════════════════════════════════════════════════════
  // EMOTIECOACHING — Bonuskind (10 taken)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "bonus_emot_01",
    title: "Loyaliteitsverdriet benoemen",
    skill: "Emotiecoaching",
    description: "Als je bonuskind zegt dat het de andere ouder mist, erken dit gevoel zonder het weg te wuiven of je gekwetst te voelen.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Loyaliteitsconflicten zijn het meest voorkomende emotionele probleem bij kinderen in samengestelde gezinnen. Het kind voelt zich verscheurd tussen twee werelden. Erkenning vermindert de innerlijke spanning.",
    skillTip: "Zeg: 'Ik snap dat je mama/papa mist. Dat is heel normaal. Je mag altijd van allebei houden.' Geen competitie aangaan.",
    vermijd: "Zeggen 'maar je hebt het hier toch ook leuk?' of negatief reageren op de vermelding van de andere ouder.",
    leerdoel: "Je leert loyaliteitsverdriet te valideren als een gezonde emotie in plaats van een bedreiging.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind", "co-ouderschap"],
  },
  {
    id: "bonus_emot_02",
    title: "Boosheid als boodschap",
    skill: "Emotiecoaching",
    description: "Wanneer je bonuskind boos op je reageert, probeer de onderliggende emotie te benoemen in plaats van op de boosheid te reageren.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Boosheid bij bonuskinderen maskeert vaak angst, verdriet of machteloosheid. Het kind test of je blijft als het je wegduwt. Achter 'jij bent mijn vader niet!' zit vaak 'ik ben bang dat ik mijn vader verlies.'",
    skillTip: "Reageer niet op de woorden maar op het gevoel: 'Ik merk dat je boos bent. Misschien voel je je ook een beetje verdrietig of onzeker. Dat mag allemaal.'",
    vermijd: "Terug in de aanval gaan, beledigd weglopen, of zeggen 'zo praat je niet tegen mij.'",
    leerdoel: "Je leert boosheid van bonuskinderen te decoderen als communicatie over diepere behoeften.",
    bron: "Gottman & DeClaire (1997) - Raising an Emotionally Intelligent Child",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_emot_03",
    title: "Twee-huizen-gevoelskaart",
    skill: "Emotiecoaching",
    description: "Teken samen twee huizen op papier en vraag je bonuskind om bij elk huis te tekenen hoe het zich daar voelt (blije, verdrietige of boze gezichtjes).",
    duration: "15 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Jonge kinderen kunnen emoties beter uiten via tekenen dan via woorden. De twee-huizen-techniek geeft kinderen toestemming om verschillende gevoelens te hebben bij verschillende plekken.",
    skillTip: "Wees neutraal bij wat het kind tekent. Alle gevoelens zijn oké, ook als er een boos gezicht bij jouw huis staat. Zeg: 'Dank je wel dat je dit laat zien.'",
    vermijd: "Vragen waarom er een negatief gevoel bij jouw huis staat, of het resultaat vergelijken met het andere huis.",
    leerdoel: "Je leert een creatieve manier om emoties bespreekbaar te maken zonder het kind onder druk te zetten.",
    bron: "Bray & Kelly (1998) - Stepfamilies: Love, Marriage, and Parenting in the First Decade",
    themes: ["bonuskind", "co-ouderschap", "samengesteld_gezin"],
  },
  {
    id: "bonus_emot_04",
    title: "Emotie-check na de wissel",
    skill: "Emotiecoaching",
    description: "Doe na elke wisseling tussen huishoudens een korte emotie-check: 'Op een schaal van 1-10, hoe voel je je nu?'",
    duration: "5 min",
    ageGroups: ["10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "De overgang tussen twee huizen is emotioneel belastend. Een simpele schaalvraag geeft het kind een veilige manier om aan te geven hoe het eraan toe is zonder grote gesprekken te hoeven voeren.",
    skillTip: "Gebruik altijd dezelfde vraag zodat het een ritueel wordt. Reageer met: 'Oké, dank je. Als je erover wilt praten, ik ben er.' Niet doorvragen als het kind dat niet wil.",
    vermijd: "De score vergelijken met vorige keren of vragen 'waarom zo laag?' Dat maakt het onveilig.",
    leerdoel: "Je leert een laagdrempelig ritueel te gebruiken om emotionele overgangen te monitoren.",
    bron: "Hetherington & Kelly (2002) - For Better or For Worse: Divorce Reconsidered",
    themes: ["bonuskind", "co-ouderschap"],
  },
  {
    id: "bonus_emot_05",
    title: "Emoties normaliseren bij ruzie",
    skill: "Emotiecoaching",
    description: "Als er ruzie is geweest in het samengesteld gezin, neem een moment om te zeggen: 'Het is normaal dat het soms moeilijk is. Alle gezinnen hebben dat.'",
    duration: "5 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen in samengestelde gezinnen dragen vaak de onuitgesproken angst dat conflict betekent dat dit gezin ook uit elkaar valt. Normaliseren van conflict vermindert deze angst.",
    skillTip: "Gebruik zinnen als: 'Ruzie hoort erbij, ook in ons gezin. Het betekent niet dat er iets mis is met ons.' Wees eerlijk zonder details van volwassenconflicten te delen.",
    vermijd: "De schuld bij het bonuskind leggen, of doen alsof er niets aan de hand was.",
    leerdoel: "Je leert conflict te normaliseren zonder het te bagatelliseren, waardoor kinderen zich veiliger voelen.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_emot_06",
    title: "Jaloeziegevoelens erkennen",
    skill: "Emotiecoaching",
    description: "Als je bonuskind jaloers lijkt op aandacht die je aan je eigen kinderen geeft, benoem dit gevoel zonder het te veroordelen.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Jaloezie in samengestelde gezinnen is onvermijdelijk en wijst op een behoefte aan zekerheid. Het kind wil weten: 'Is er ook plek voor mij?' Benoemen van jaloezie maakt het hanteerbaar.",
    skillTip: "Zeg: 'Ik merk dat het misschien lastig is als ik veel aandacht aan [naam] geef. Jij bent ook heel belangrijk voor mij.' Plan daarna bewust een-op-eentijd.",
    vermijd: "Zeggen 'doe niet zo jaloers' of doen alsof je alle kinderen precies gelijk behandelt — kinderen prikken daar doorheen.",
    leerdoel: "Je leert jaloezie te erkennen als een signaal van behoefte aan verbinding, niet als lastig gedrag.",
    bron: "Ganong & Coleman (2017) - Stepfamily Relationships: Development, Dynamics, and Interventions",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_emot_07",
    title: "Heimwee-toolkit",
    skill: "Emotiecoaching",
    description: "Help je bonuskind een klein tasje samen te stellen met troostobjecten van de andere ouder: een foto, een knuffel, iets dat naar die ouder ruikt.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Transitionele objecten helpen kinderen de emotionele brug te slaan tussen twee huizen. Door hier actief in mee te helpen, laat je zien dat je de band met de andere ouder respecteert.",
    skillTip: "Zeg: 'Zullen we samen iets uitzoeken dat je aan mama/papa doet denken voor als je ze mist?' Dit is een krachtig signaal van veiligheid.",
    vermijd: "Het als onzin wegwuiven of je gekwetst voelen dat het kind de andere ouder mist.",
    leerdoel: "Je leert de band van je bonuskind met de andere ouder actief te ondersteunen.",
    bron: "Winnicott (1971) - Playing and Reality",
    themes: ["bonuskind", "co-ouderschap"],
  },
  {
    id: "bonus_emot_08",
    title: "Gevoelens over het nieuwe gezin",
    skill: "Emotiecoaching",
    description: "Vraag je bonuskind open: 'Hoe is het voor jou om in een samengesteld gezin te wonen? Ik ben benieuwd hoe jij het ervaart.'",
    duration: "15 min",
    ageGroups: ["10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Oudere kinderen en tieners denken veel na over hun gezinssituatie maar worden zelden gevraagd naar hun perspectief. De vraag zelf is al therapeutisch: het communiceert dat hun mening ertoe doet.",
    skillTip: "Luister zonder verdediging. Als het kind kritiek uit, bedank het: 'Fijn dat je zo eerlijk bent. Daar kan ik iets mee.' Ga niet in de verdediging.",
    vermijd: "Je verdedigen, de situatie goedpraten, of zeggen 'maar het gaat toch goed?'",
    leerdoel: "Je leert een open dialoog te voeren over de gezinssituatie waarin het kind zich gehoord voelt.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_emot_09",
    title: "Terug naar de basis bij tranen",
    skill: "Emotiecoaching",
    description: "Als je bonuskind huilt, bied troost aan zonder meteen te willen weten waarom. Zeg: 'Ik zie dat je verdrietig bent. Ik ben hier.'",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Bonuskinderen huilen soms om dingen die ze niet kunnen of durven benoemen — gemis, verwarring, loyaliteitsconflict. De reden is minder belangrijk dan de ervaring van getroost worden door een veilige volwassene.",
    skillTip: "Bied fysiek comfort aan als het kind dat accepteert: een hand op de schouder, een arm om hen heen. Respecteer het als ze afstand willen. Zeg: 'Ik ga niet weg.'",
    vermijd: "Meteen vragen 'wat is er?' of 'is er iets gebeurd bij je moeder/vader?' Dat kan voelen als een verhoor.",
    leerdoel: "Je leert onvoorwaardelijke troost te bieden, ongeacht of je de reden van het verdriet kent.",
    bron: "Siegel & Bryson (2011) - The Whole-Brain Child",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_emot_10",
    title: "Emotioneel dagboek voor twee huizen",
    skill: "Emotiecoaching",
    description: "Geef je bonuskind een schriftje waarin het elke dag met een emoticon of woord kan bijhouden hoe het zich voelt. Bekijk het samen als het kind dat wil.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Expressief schrijven helpt kinderen emoties te verwerken. Een dagboek dat meegaat tussen twee huizen kan een rode draad zijn in een leven dat constant wisselt.",
    skillTip: "Stel voor dat het schriftje van het kind is — niet van jou. Zeg: 'Als je wilt delen wat erin staat, dan luister ik graag. Maar het is van jou.' Respecteer privacy volledig.",
    vermijd: "Stiekem lezen of het kind onder druk zetten om te delen. Het dagboek is van het kind, niet voor jouw geruststelling.",
    leerdoel: "Je leert je bonuskind een veilig hulpmiddel te geven voor emotionele verwerking.",
    bron: "Pennebaker (1997) - Opening Up: The Healing Power of Expressing Emotions",
    themes: ["bonuskind", "co-ouderschap", "samengesteld_gezin"],
  },

  // ═══════════════════════════════════════════════════════════════
  // ZELFREGULATIE — Bonuskind (10 taken)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "bonus_zelfreg_01",
    title: "Pauze bij 'jij bent mijn vader niet'",
    skill: "Zelfregulatie",
    description: "Oefen vandaag mentaal wat je doet als je bonuskind zegt: 'Jij bent mijn vader niet!' Bereid een kalme reactie voor.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Deze zin is een van de pijnlijkste ervaringen voor bonusvaders. Het activeert direct je dreigingssysteem. Door vooraf te oefenen, verklein je de kans op een impulsieve reactie.",
    skillTip: "Bereid deze zin voor: 'Je hebt gelijk, ik ben niet je vader. En ik respecteer je vader. Maar ik geef wel om je.' Oefen dit hardop voor de spiegel.",
    vermijd: "Boos weglopen, terug snauwen, of zeggen 'maar ik doe alles voor je!' Dat escaleert en beschadigt.",
    leerdoel: "Je leert een emotioneel geladen situatie te de-escaleren door vooraf te oefenen.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_zelfreg_02",
    title: "Jouw triggers kennen",
    skill: "Zelfregulatie",
    description: "Schrijf drie situaties op waarin je bonuskind je het meest triggert. Bedenk bij elke trigger wat je eerste impuls is en wat je liever zou doen.",
    duration: "15 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Bonusouderschap activeert unieke triggers: buitengesloten voelen, niet gewaardeerd worden, het gevoel dat je partner het kind voortrekt. Bewustzijn van triggers is de eerste stap naar beheersing.",
    skillTip: "Maak een lijst: (1) Trigger, (2) Mijn automatische reactie, (3) Wat ik eigenlijk wil doen. Bewaar deze lijst op je telefoon voor moeilijke momenten.",
    vermijd: "Jezelf veroordelen om je triggers. Ze zijn menselijk en begrijpelijk. Het gaat om wat je ermee doet.",
    leerdoel: "Je leert je persoonlijke triggerpatronen herkennen zodat je bewuster kunt reageren.",
    bron: "Siegel & Hartzell (2003) - Parenting from the Inside Out",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_zelfreg_03",
    title: "Ademruimte bij afwijzing",
    skill: "Zelfregulatie",
    description: "Oefen de 4-7-8 ademhaling (4 tellen in, 7 vasthouden, 8 uit) voor momenten dat je bonuskind je afwijst of negeert.",
    duration: "5 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Afwijzing door je bonuskind activeert dezelfde hersengebieden als fysieke pijn. De 4-7-8 techniek activeert het parasympathisch zenuwstelsel en voorkomt dat je vanuit pijn reageert.",
    skillTip: "Doe deze oefening nu vijf keer als training. Koppel het mentaal aan het gevoel van afwijzing zodat je brein de link legt. Bij het echte moment gaat het dan automatischer.",
    vermijd: "De ademhaling als vervanging voor het verwerken van het gevoel gebruiken. Het is een pauzeknop, geen ontkenning.",
    leerdoel: "Je leert een fysieke techniek om je zenuwstelsel te kalmeren bij emotionele pijn.",
    bron: "Weil (2015) - Breathing: The Master Key to Self Healing",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_zelfreg_04",
    title: "Niet vergelijken met het biologische kind",
    skill: "Zelfregulatie",
    description: "Let er vandaag bewust op of je jezelf betrapt op het vergelijken van je band met je bonuskind met die met je biologische kinderen. Noteer wat je opvalt.",
    duration: "10 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "De vergelijking is onvermijdelijk maar destructief. De band met een bonuskind ontwikkelt zich fundamenteel anders en langzamer. Vergelijken leidt tot frustratie en schuldgevoel.",
    skillTip: "Als je merkt dat je vergelijkt, zeg tegen jezelf: 'Dit zijn twee verschillende relaties, elk met hun eigen tempo en waarde.' Schrijf op wat wél goed gaat met je bonuskind.",
    vermijd: "Jezelf schuldig voelen over het verschil. Het is biologisch en psychologisch logisch dat de banden anders zijn.",
    leerdoel: "Je leert het vergelijkingspatroon te doorbreken en elke relatie op eigen merites te waarderen.",
    bron: "Hetherington & Kelly (2002) - For Better or For Worse: Divorce Reconsidered",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_zelfreg_05",
    title: "Frustratie parkeren na de wissel",
    skill: "Zelfregulatie",
    description: "Na een moeizame wisseling met de andere ouder, neem 5 minuten voor jezelf voordat je het huis in gaat. Adem, reset, en laat volwassen frustratie buiten.",
    duration: "5 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen zijn uiterst gevoelig voor spanning tussen volwassenen na een wissel. Ze scannen onbewust je gezicht, stem en houding. Vijf minuten reset voorkomt dat jouw frustratie hun aankomst beïnvloedt.",
    skillTip: "Blijf even in de auto zitten. Adem vijf keer diep in en uit. Zeg tegen jezelf: 'Wat er ook tussen de volwassenen speelt, dit kind verdient een rustige thuiskomst.'",
    vermijd: "Je frustratie over de co-ouder uiten waar het kind bij is, ook niet subtiel via gezichtsuitdrukkingen of toon.",
    leerdoel: "Je leert een bewuste buffer te creëren tussen volwassen conflict en het welzijn van het kind.",
    bron: "Emery (2004) - The Truth About Children and Divorce",
    themes: ["bonuskind", "co-ouderschap"],
  },
  {
    id: "bonus_zelfreg_06",
    title: "Geduld met het tempo van de band",
    skill: "Zelfregulatie",
    description: "Schrijf op waar je stond in de relatie met je bonuskind een jaar geleden versus nu. Vier de vooruitgang, hoe klein ook.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Onderzoek toont dat het gemiddeld 4-7 jaar duurt voordat een samengesteld gezin echt samensmelt. Ongeduld is de grootste valkuil voor bonusvaders. Perspectief helpt.",
    skillTip: "Maak twee lijstjes: 'Waar stonden we een jaar geleden' en 'Waar staan we nu.' Denk aan kleine dingen: een spontane knuffel, samen lachen, een gedeeld grapje.",
    vermijd: "Focussen op wat nog niet is. De reis is het doel, niet de bestemming.",
    leerdoel: "Je leert geduld te cultiveren door bewust vooruitgang te erkennen in het bonusouderschap.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_zelfreg_07",
    title: "Grenzen aan je opoffering",
    skill: "Zelfregulatie",
    description: "Check bij jezelf: doe je dingen voor je bonuskind vanuit oprechte zorg, of vanuit de behoefte om geaccepteerd te worden? Wees eerlijk.",
    duration: "10 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Veel bonusvaders overcompenseren om geaccepteerd te worden: te veel cadeaus, te veel ja zeggen, te weinig grenzen. Dit is uitputtend en leidt uiteindelijk tot wrok.",
    skillTip: "Vraag jezelf bij elke ja: 'Zou ik dit ook doen als dit mijn biologische kind was, of probeer ik goedkeuring te verdienen?' Eerlijk antwoorden helpt om gezonde patronen te ontwikkelen.",
    vermijd: "Jezelf veroordelen als het antwoord is: 'Ik doe het voor goedkeuring.' Dat is menselijk. Het bewustzijn is de eerste stap.",
    leerdoel: "Je leert onderscheid te maken tussen authentieke zorg en pleasing-gedrag.",
    bron: "Cloud & Townsend (1992) - Boundaries: When to Say Yes, How to Say No",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_zelfreg_08",
    title: "Je partner is niet de vijand",
    skill: "Zelfregulatie",
    description: "Als je gefrustreerd bent dat je partner het bonuskind 'voorkeur' geeft, pauzeer en schrijf op wat je voelt voordat je het gesprek aangaat.",
    duration: "15 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "In samengestelde gezinnen ontstaat vaak een dynamiek waarin de biologische ouder het kind beschermt tegen de bonusouder. Dit voelt als verraad maar is een beschermingsinstinct. Begrip hiervoor vermindert conflict.",
    skillTip: "Schrijf op: (1) Wat gebeurde er? (2) Wat voelde ik? (3) Wat denk ik dat mijn partner voelde? (4) Wat hebben we allebei nodig? Gebruik dit als basis voor een rustig gesprek.",
    vermijd: "Het gesprek aangaan als je nog boos bent. De kans op verwijten is dan te groot.",
    leerdoel: "Je leert partnerconflicten in samengestelde gezinnen te benaderen met begrip in plaats van verwijt.",
    bron: "Gottman & Silver (1999) - The Seven Principles for Making Marriage Work",
    themes: ["samengesteld_gezin", "bonuskind"],
  },
  {
    id: "bonus_zelfreg_09",
    title: "Zelfzorg zonder schuldgevoel",
    skill: "Zelfregulatie",
    description: "Plan vandaag 20 minuten voor jezelf in. Bonusouderschap is emotioneel zwaar werk — je kunt alleen geven wat je hebt.",
    duration: "20 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Bonusvaders rapporteren hogere stressniveaus dan biologische vaders in intacte gezinnen. Zelfzorg is geen luxe maar noodzaak voor duurzaam ouderschap.",
    skillTip: "Kies iets dat jou oplaadt: wandelen, sporten, muziek luisteren, een vriend bellen. Communiceer naar je partner: 'Ik neem even tijd voor mezelf zodat ik er straks weer helemaal kan zijn.'",
    vermijd: "Schuldgevoel omdat je even 'niet beschikbaar' bent. Een lege batterij kan niets geven.",
    leerdoel: "Je leert dat zelfzorg een voorwaarde is voor goed bonusouderschap, geen teken van zwakte.",
    bron: "Neff (2011) - Self-Compassion: The Proven Power of Being Kind to Yourself",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_zelfreg_10",
    title: "Het grotere plaatje zien",
    skill: "Zelfregulatie",
    description: "Schrijf drie dingen op die je dankbaar bent in je rol als bonusvader. Verschuif de focus van wat moeilijk is naar wat waardevol is.",
    duration: "10 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Gratitude-oefeningen herstructureren letterlijk de neurale paden in je brein. Voor bonusvaders die vaak focussen op afwijzing en frustratie, is dit een krachtige tegenkracht.",
    skillTip: "Wees specifiek: niet 'ik ben dankbaar voor mijn bonuskind' maar 'ik ben dankbaar dat [naam] gisteren spontaan naast me kwam zitten.' Specificiteit versterkt het effect.",
    vermijd: "Toxic positivity — je hoeft niet te doen alsof alles geweldig is. Het gaat om het vinden van lichtpuntjes naast de uitdagingen.",
    leerdoel: "Je leert dankbaarheid te gebruiken als regulatiestrategie voor de uitdagingen van bonusouderschap.",
    bron: "Emmons (2007) - Thanks! How the New Science of Gratitude Can Make You Happier",
    themes: ["bonuskind", "samengesteld_gezin"],
  },

  // ═══════════════════════════════════════════════════════════════
  // GRENZEN — Bonuskind (10 taken)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "bonus_grenz_01",
    title: "Huisregels samen bespreken",
    skill: "Grenzen",
    description: "Bespreek met je partner welke huisregels gelden voor alle kinderen in het samengesteld gezin. Maak ze zichtbaar op een poster.",
    duration: "20 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "In samengestelde gezinnen botsen vaak twee opvoedstijlen. Kinderen hebben baat bij duidelijke, gedeelde regels die voor iedereen gelden — dit voorkomt het gevoel van ongelijke behandeling.",
    skillTip: "Betrek de kinderen erbij: 'We maken samen regels voor ons huis.' Beperk het tot 5-7 regels die iedereen kan onthouden. Hang ze zichtbaar op.",
    vermijd: "Regels opleggen als bonusvader zonder overleg. Dit moet samen met je partner komen, en bij voorkeur met input van de kinderen.",
    leerdoel: "Je leert gezamenlijke grenzen te creëren die voor alle kinderen in het samengesteld gezin gelden.",
    bron: "Bray & Kelly (1998) - Stepfamilies: Love, Marriage, and Parenting in the First Decade",
    themes: ["samengesteld_gezin", "bonuskind"],
  },
  {
    id: "bonus_grenz_02",
    title: "De biologische ouder laten leiden",
    skill: "Grenzen",
    description: "Laat vandaag bewust je partner het voortouw nemen bij een grenssituatie met het bonuskind. Ondersteun vanuit de achtergrond.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "In de eerste jaren is het effectiever als de biologische ouder de primaire disciplineerder is. De bonusvader bouwt eerst aan de relatie. Grenzen stellen zonder relatie leidt tot verzet.",
    skillTip: "Spreek af met je partner: 'Als [naam] over de grens gaat, neem jij het voortouw en ik steun je.' Dit voorkomt het 'twee kapiteins op één schip'-gevoel.",
    vermijd: "Zelf ingrijpen bij het bonuskind als de biologische ouder erbij is, tenzij jullie dit expliciet hebben afgesproken.",
    leerdoel: "Je leert de grenzenrol geleidelijk op te bouwen door eerst je partner te ondersteunen.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_grenz_03",
    title: "Consistentie tussen twee huizen",
    skill: "Grenzen",
    description: "Bespreek met je partner of er regels zijn die in beide huishoudens gelijk kunnen zijn (bijv. bedtijd, schermtijd). Maak een kort lijstje.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen die schakelen tussen huizen hebben baat bij overlap in regels. Totale consistentie is onrealistisch, maar zelfs 2-3 gedeelde regels geven houvast.",
    skillTip: "Focus op regels die het kind helpen (bedtijd, huiswerk) in plaats van regels die de volwassenen helpen. Overleg dit eventueel via je partner met de andere ouder.",
    vermijd: "De andere ouder bekritiseren als die andere regels heeft. Zeg tegen het kind: 'Bij ons doen we het zo, en dat is oké.'",
    leerdoel: "Je leert pragmatisch om te gaan met regelverschillen tussen twee huishoudens.",
    bron: "Emery (2004) - The Truth About Children and Divorce",
    themes: ["co-ouderschap", "samengesteld_gezin", "bonuskind"],
  },
  {
    id: "bonus_grenz_04",
    title: "Nee zeggen met warmte",
    skill: "Grenzen",
    description: "Oefen vandaag een keer 'nee' zeggen tegen je bonuskind op een warme, duidelijke manier. Leg kort uit waarom.",
    duration: "5 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Veel bonusvaders durven geen grenzen te stellen uit angst de relatie te beschadigen. Maar grenzen zijn juist een teken van betrokkenheid. Kinderen voelen zich veiliger met duidelijke grenzen.",
    skillTip: "Zeg: 'Nee, dat gaat nu niet. Ik snap dat je dat vervelend vindt.' Combineer de grens met erkenning van het gevoel. Niet onderhandelen.",
    vermijd: "Grenzen stellen en meteen toegeven als het kind protesteert. Dat leert dat jouw grenzen niet echt zijn.",
    leerdoel: "Je leert dat grenzen stellen geen afwijzing is maar een vorm van zorg en betrokkenheid.",
    bron: "Cloud & Townsend (1992) - Boundaries: When to Say Yes, How to Say No",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_grenz_05",
    title: "Respect als basisregel",
    skill: "Grenzen",
    description: "Stel de regel in dat iedereen in het gezin respectvol met elkaar omgaat. Bespreek samen wat 'respect' betekent.",
    duration: "15 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "In samengestelde gezinnen is 'respect' een gedeelde waarde die boven individuele relaties uitstijgt. Het hoeft niet over liefde te gaan — respect is realistischer en toch krachtig.",
    skillTip: "Zeg: 'We hoeven niet altijd alles leuk te vinden aan elkaar, maar we behandelen iedereen hier met respect. Wat betekent dat voor jullie?' Laat kinderen meedenken.",
    vermijd: "Respect afdwingen met autoriteit. Dat is een contradictie. Modelleer het zelf.",
    leerdoel: "Je leert respect als gedeelde waarde te introduceren die ruimte laat voor verschillende gevoelens.",
    bron: "Ganong & Coleman (2017) - Stepfamily Relationships: Development, Dynamics, and Interventions",
    themes: ["samengesteld_gezin", "bonuskind"],
  },
  {
    id: "bonus_grenz_06",
    title: "Privacy in twee huizen",
    skill: "Grenzen",
    description: "Bespreek met je bonuskind dat ze recht hebben op privacy over wat er in het andere huis gebeurt. Stel geen uithoorkragen.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen worden vaak onbewust als spion ingezet tussen twee huishoudens. Expliciet zeggen dat ze niet hoeven te rapporteren, geeft enorme opluchting en vermindert loyaliteitsconflict.",
    skillTip: "Zeg: 'Wat er bij mama/papa thuis gebeurt, dat hoef je niet te vertellen. Als je wilt delen, luister ik graag. Maar je hoeft niet.' Herhaal dit regelmatig.",
    vermijd: "Subtiele vragen als 'en, hoe was het daar?' of 'was papa's nieuwe vriendin er ook?' Dit is uitvragen, ook als je het niet zo bedoelt.",
    leerdoel: "Je leert de privacy van je bonuskind te respecteren en ze te bevrijden van de spionnenrol.",
    bron: "Emery (2004) - The Truth About Children and Divorce",
    themes: ["bonuskind", "co-ouderschap"],
  },
  {
    id: "bonus_grenz_07",
    title: "Je eigen ruimte bewaken",
    skill: "Grenzen",
    description: "Communiceer vriendelijk maar duidelijk een eigen grens. Bijvoorbeeld: 'Ik vind het fijn als je klopt voordat je mijn werkkamer in komt.'",
    duration: "5 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Bonusvaders vergeten soms dat zij ook grenzen mogen hebben. Door zelf grenzen te modelleren, leert het kind dat grenzen normaal en gezond zijn — niet persoonlijk.",
    skillTip: "Formuleer het als een 'ik'-boodschap: 'Ik heb soms even stilte nodig om goed voor jullie te kunnen zorgen.' Dit normaliseert grenzen voor iedereen.",
    vermijd: "Grenzen stellen alsof het kind iets fout doet. Het gaat om jouw behoefte, niet om hun gedrag.",
    leerdoel: "Je leert dat het modelleren van eigen grenzen een krachtig opvoedkundig voorbeeld is.",
    bron: "Brown (2010) - The Gifts of Imperfection",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_grenz_08",
    title: "Gelijke monniken, gelijke kappen?",
    skill: "Grenzen",
    description: "Reflecteer eerlijk: behandel je je bonuskind en biologische kinderen echt gelijk bij het stellen van grenzen? Schrijf op wat je opvalt.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Eerlijkheid in grenzen is een van de grootste uitdagingen in samengestelde gezinnen. Kinderen zijn scherpe waarnemers van ongelijkheid. Perfekte gelijkheid is onmogelijk, maar bewustzijn is essentieel.",
    skillTip: "Vraag je partner om eerlijke feedback: 'Zie jij verschil in hoe ik grenzen stel bij mijn kinderen versus jouw kinderen?' Luister zonder verdediging.",
    vermijd: "Doen alsof je altijd eerlijk bent. Iedereen heeft blinde vlekken. Het gaat om de bereidheid om te kijken.",
    leerdoel: "Je leert eerlijk te reflecteren op ongelijkheid in grenzen en dit bespreekbaar te maken.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["samengesteld_gezin", "bonuskind"],
  },
  {
    id: "bonus_grenz_09",
    title: "Samen grenzen bespreken na een incident",
    skill: "Grenzen",
    description: "Na een grenssituatie met je bonuskind, bespreek met je partner (zonder het kind erbij) of je samen op één lijn zat.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen in samengestelde gezinnen zijn meester in het vinden van scheuren tussen de volwassenen. Als bonusvader en biologische ouder niet op één lijn zitten, wordt het kind onzeker of gaat splitsen.",
    skillTip: "Bespreek na een incident: 'Hoe vond jij dat het ging? Waren we op één lijn? Wat doen we volgende keer?' Dit is teamwork, geen verwijt.",
    vermijd: "De discussie voeren waar het kind bij is. Kinderen mogen nooit zien dat volwassenen het oneens zijn over hun opvoeding.",
    leerdoel: "Je leert grenssituaties na te bespreken als team en zo je samenwerking te versterken.",
    bron: "Gottman & Silver (1999) - The Seven Principles for Making Marriage Work",
    themes: ["samengesteld_gezin", "bonuskind"],
  },
  {
    id: "bonus_grenz_10",
    title: "Grens op negatieve opmerkingen over de andere ouder",
    skill: "Grenzen",
    description: "Stel een duidelijke grens: in jouw huis worden er geen negatieve dingen gezegd over de andere ouder. Dit geldt voor iedereen, ook voor jou.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Wanneer kinderen negatieve opmerkingen horen over hun andere ouder, ervaren ze dat als een aanval op een deel van zichzelf. Deze grens beschermt het kind op een fundamenteel niveau.",
    skillTip: "Zeg: 'In dit huis praten we respectvol over iedereen die belangrijk is voor jullie, ook mama/papa. Als ik iets wil bespreken, doe ik dat met volwassenen.' Leef dit zelf na.",
    vermijd: "Subtiele sneren, oogcontact met je partner bij vermelding van de ex, of sarcastische opmerkingen. Kinderen pikken alles op.",
    leerdoel: "Je leert een beschermende grens te stellen die het kind bevrijdt van loyaliteitsconflicten.",
    bron: "Emery (2004) - The Truth About Children and Divorce",
    themes: ["co-ouderschap", "bonuskind", "samengesteld_gezin"],
  },

  // ═══════════════════════════════════════════════════════════════
  // AUTONOMIE — Bonuskind (10 taken)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "bonus_auto_01",
    title: "Het kind kiest het tempo",
    skill: "Autonomie",
    description: "Laat je bonuskind vandaag zelf bepalen hoeveel contact het met jou wil. Bied aan, maar dring niet aan.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Bonuskinderen hebben al veel verlies van controle meegemaakt door de scheiding. Hen het tempo laten bepalen herstelt hun gevoel van agency en vermindert weerstand.",
    skillTip: "Zeg: 'Ik ben hier als je zin hebt om samen iets te doen. Je mag ook lekker je eigen ding doen.' Wacht geduldig af.",
    vermijd: "Meerdere keren aanbieden als het kind nee zegt. Eén keer aanbieden is genoeg — meer wordt druk.",
    leerdoel: "Je leert de autonomie van je bonuskind te respecteren als basis voor vrijwillige toenadering.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_auto_02",
    title: "Naamkeuze respecteren",
    skill: "Autonomie",
    description: "Bevestig aan je bonuskind dat het jou mag noemen hoe het wil: bij je voornaam, een bijnaam, of anders. Het hoeft je geen 'papa' te noemen.",
    duration: "5 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "De naam waarmee een kind zijn bonusouder aanspreekt, raakt direct aan loyaliteit naar de biologische vader. Vrijheid in naamgebruik vermindert innerlijk conflict enorm.",
    skillTip: "Zeg: 'Je mag me noemen hoe je wilt. [Voornaam] is prima, of iets anders als je dat fijner vindt. Jij kiest.' Stel geen voorwaarden.",
    vermijd: "Subtiel aansturen op 'papa' of teleurgesteld reageren als het kind je bij je voornaam noemt.",
    leerdoel: "Je leert dat de naam minder belangrijk is dan de relatie erachter.",
    bron: "Ganong & Coleman (2017) - Stepfamily Relationships: Development, Dynamics, and Interventions",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_auto_03",
    title: "Eigen plekje inrichten",
    skill: "Autonomie",
    description: "Laat je bonuskind een eigen hoekje of plank inrichten in jullie huis. Het kind kiest zelf wat daar komt.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Een eigen plek in het huis communiceert: 'Je hoort hier.' Voor kinderen die pendelen tussen twee huizen is fysieke ruimte een anker van belonging.",
    skillTip: "Laat het kind helemaal zelf bepalen wat op hun plek komt, ook als het rommelig of vreemd lijkt. Het gaat om eigenaarschap, niet om esthetiek.",
    vermijd: "Het plekje opruimen als het kind er niet is, of suggesties doen over wat er moet staan.",
    leerdoel: "Je leert fysieke ruimte te gebruiken als symbool van erbij horen.",
    bron: "Bray & Kelly (1998) - Stepfamilies: Love, Marriage, and Parenting in the First Decade",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_auto_04",
    title: "Keuzes bij de wisseldag",
    skill: "Autonomie",
    description: "Geef je bonuskind keuzes rondom de wisseldag: 'Wil je vanavond pizza of pasta? Wil je een film kijken of buiten spelen?'",
    duration: "5 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Op wisseldagen voelen kinderen zich vaak als een pakketje dat wordt overgedragen. Keuzes geven terug wat de wissel afneemt: een gevoel van controle over hun eigen leven.",
    skillTip: "Bied twee of drie concrete opties aan. Te veel keuze overweldigt, te weinig voelt als dwang. Zeg: 'Jij mag kiezen wat we vanavond doen.'",
    vermijd: "Alles invullen zonder te vragen. Ook goedbedoelde verrassingen kunnen overweldigend zijn na een overgang.",
    leerdoel: "Je leert keuzemomenten te creëren die het gevoel van controle herstellen bij de overgang.",
    bron: "Hetherington & Kelly (2002) - For Better or For Worse: Divorce Reconsidered",
    themes: ["bonuskind", "co-ouderschap"],
  },
  {
    id: "bonus_auto_05",
    title: "Eigen contact met de biologische ouder",
    skill: "Autonomie",
    description: "Faciliteer dat je bonuskind zelf contact kan opnemen met de andere ouder wanneer het dat wil, zonder dat jij ertussen zit.",
    duration: "5 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen die zelf contact kunnen opnemen met hun andere ouder, ervaren minder loyaliteitsconflict. Ze hoeven niet te kiezen — ze kunnen verbonden blijven met beide werelden.",
    skillTip: "Zorg dat het kind de biologische ouder kan bellen of appen wanneer het wil. Zeg: 'Als je mama/papa wilt bellen, pak gerust de telefoon.' Laat het kind dit privé doen.",
    vermijd: "Meeluisteren, vragen wat er besproken is, of het contact beperken tenzij er echte zorgen zijn.",
    leerdoel: "Je leert de autonome band van het kind met de andere ouder actief te faciliteren.",
    bron: "Emery (2004) - The Truth About Children and Divorce",
    themes: ["bonuskind", "co-ouderschap"],
  },
  {
    id: "bonus_auto_06",
    title: "Meedenken over gezinsactiviteiten",
    skill: "Autonomie",
    description: "Vraag je bonuskind om mee te denken over een gezinsactiviteit voor het weekend. Neem hun suggestie serieus.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Bonuskinderen voelen zich soms bijkomstig in het nieuwe gezin: de plannen worden gemaakt en zij moeten volgen. Meedenken geeft hen een stem en versterkt het gevoel van erbij horen.",
    skillTip: "Zeg: 'We gaan dit weekend iets leuks doen. Wat zou jij willen? We proberen het in te passen.' Als het echt niet kan, leg eerlijk uit waarom en bied een alternatief.",
    vermijd: "Vragen naar hun mening en het vervolgens negeren. Dat is erger dan niet vragen.",
    leerdoel: "Je leert je bonuskind een actieve stem te geven in het gezinsleven.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_auto_07",
    title: "Ruimte voor twee tradities",
    skill: "Autonomie",
    description: "Vraag je bonuskind welke tradities of gewoontes uit het andere huis ze hier ook zouden willen doen. Probeer er minstens één over te nemen.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen in twee huizen leiden twee levens die zelden met elkaar verbonden worden. Door tradities uit het andere huis te integreren, help je het kind een coherent zelfbeeld te behouden.",
    skillTip: "Zeg: 'Is er iets dat jullie bij mama/papa altijd doen dat je hier ook fijn zou vinden? Zoals een speciaal ontbijt op zondag of een filmavond?' Wees oprecht geïnteresseerd.",
    vermijd: "Competitief reageren of de traditie van de andere ouder beter willen doen. Het gaat om het kind, niet om jou.",
    leerdoel: "Je leert twee leefwerelden te verbinden in plaats van ze te laten concurreren.",
    bron: "Hetherington & Kelly (2002) - For Better or For Worse: Divorce Reconsidered",
    themes: ["bonuskind", "co-ouderschap", "samengesteld_gezin"],
  },
  {
    id: "bonus_auto_08",
    title: "Zelf kiezen wanneer te praten",
    skill: "Autonomie",
    description: "Laat je bonuskind weten: 'Als je ergens over wilt praten, ik luister graag. Maar je hoeft niet te praten als je dat niet wilt.'",
    duration: "5 min",
    ageGroups: ["10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Tieners in samengestelde gezinnen worden vaak bestookt met goedbedoelde vragen over hun gevoelens. De vrijheid om niet te praten is paradoxaal genoeg vaak de opening naar praten.",
    skillTip: "Spreek het uit en laat het dan los. Geen follow-up, geen herinnering. Het aanbod is geplant. Tieners komen terug als ze er klaar voor zijn — soms weken later.",
    vermijd: "Na het aanbod toch vragen stellen of hints geven. Laat het echt los.",
    leerdoel: "Je leert dat de krachtigste uitnodiging tot communicatie een uitnodiging zonder druk is.",
    bron: "Faber & Mazlish (2012) - How to Talk So Teens Will Listen",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_auto_09",
    title: "Eigen tempo bij familiefeesten",
    skill: "Autonomie",
    description: "Bereid je bonuskind voor op een familiefeest bij jouw kant van de familie. Spreek af dat het zich mag terugtrekken als het te veel wordt.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Familiefeesten bij de 'nieuwe' familie zijn potentieel overweldigend: onbekende mensen die het kind als 'bonus-kleinkind' claimen. Een exit-strategie geeft het kind controle.",
    skillTip: "Spreek een geheim signaal af: als het kind aan zijn oor trekt of een codewoord zegt, dan weet je dat het even pauze nodig heeft. Ga dan samen een rondje lopen.",
    vermijd: "Het kind dwingen om iedereen te begroeten of te knuffelen. 'Geef oma eens een kus' is een grensoverschrijding.",
    leerdoel: "Je leert je bonuskind te beschermen in sociale situaties door een veiligheidsnet te bieden.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_auto_10",
    title: "Meebeslissen over regels",
    skill: "Autonomie",
    description: "Nodig je bonuskind (10+) uit om mee te denken over een nieuwe huisregel. Neem hun input serieus en pas de regel aan als hun punt goed is.",
    duration: "15 min",
    ageGroups: ["10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Tieners die inspraak hebben in regels, houden zich er eerder aan. Voor bonuskinderen is dit extra belangrijk: het communiceert dat ze een volwaardig gezinslid zijn, niet een gast die regels opgelegd krijgt.",
    skillTip: "Kies een regel die negotieerbaar is (bijv. schermtijd, bedtijd in het weekend). Zeg: 'Wat vind jij eerlijk? Laten we er samen uitkomen.' Wees bereid om te bewegen.",
    vermijd: "Een schijnvertoning opzetten waar het kind mag 'meedenken' maar de uitkomst al vaststaat.",
    leerdoel: "Je leert autonomie te bevorderen door gedeelde besluitvorming, wat de acceptatie van grenzen vergroot.",
    bron: "Deci & Ryan (2000) - Self-Determination Theory and the Facilitation of Intrinsic Motivation",
    themes: ["bonuskind", "samengesteld_gezin"],
  },

  // ═══════════════════════════════════════════════════════════════
  // HERSTEL — Bonuskind (10 taken)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "bonus_herst_01",
    title: "Sorry na een misstap",
    skill: "Herstel",
    description: "Bied oprecht je excuses aan voor een moment waarop je te streng, ongeduldig of afwezig was naar je bonuskind.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Sorry zeggen als bonusvader is extra krachtig omdat het laat zien: ik neem deze relatie serieus genoeg om mijn fouten toe te geven. Het doorbreekt het patroon dat volwassenen in het leven van dit kind onfeilbaar moeten zijn.",
    skillTip: "Zeg: 'Ik was gisteren te streng/ongeduldig. Dat was niet eerlijk naar jou. Het spijt me.' Geen 'maar' erachteraan.",
    vermijd: "Excuses die eigenlijk een verwijt zijn: 'Sorry, maar als jij niet...' Dat is geen sorry.",
    leerdoel: "Je leert dat oprechte excuses de relatie met je bonuskind versterken in plaats van verzwakken.",
    bron: "Gottman & DeClaire (1997) - Raising an Emotionally Intelligent Child",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_herst_02",
    title: "Herstellen na een loyaliteitsscene",
    skill: "Herstel",
    description: "Na een moment waarop loyaliteitsconflict speelde (bijv. het kind koos openlijk voor de andere ouder), neem de tijd om het met je bonuskind te bespreken.",
    duration: "15 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Na loyaliteitsscenes voelen zowel het kind als de bonusvader zich rot. Het kind kan schuldgevoel ervaren. Door het te bespreken, laat je zien dat de relatie tegen een stootje kan.",
    skillTip: "Zeg: 'Ik begreep gisteren dat je je papa/mama miste. Dat is helemaal oké. Daar hoef je je niet schuldig over te voelen. Ik ben er gewoon als je me nodig hebt.'",
    vermijd: "Doen alsof het niet gebeurd is, of passief-agressief reageren ('Oh, nu wil je wel met mij spelen?').",
    leerdoel: "Je leert loyaliteitsconflicten te repareren zonder schuldgevoel op het kind te leggen.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind", "co-ouderschap"],
  },
  {
    id: "bonus_herst_03",
    title: "Terugkomen op een oneerlijke vergelijking",
    skill: "Herstel",
    description: "Als je per ongeluk je bonuskind en biologisch kind verschillend hebt behandeld, erken dit en herstel het.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Ongelijke behandeling wordt door kinderen feilloos opgepikt. Door het zelf te benoemen voordat het kind het moet aanklagen, bouw je enorm vertrouwen op.",
    skillTip: "Zeg: 'Ik merkte dat ik net strenger was naar jou dan naar [naam]. Dat was niet eerlijk. Sorry.' Het feit dat je het zelf ziet, is krachtiger dan perfectie.",
    vermijd: "Het goedpraten met: 'Ja maar jij deed ook...' Erken simpelweg de ongelijkheid.",
    leerdoel: "Je leert ongelijkheid te herkennen en te repareren voordat het wrok wordt.",
    bron: "Hetherington & Kelly (2002) - For Better or For Worse: Divorce Reconsidered",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_herst_04",
    title: "Herstel na een slechte wisseldag",
    skill: "Herstel",
    description: "Als de wissel tussen huishoudens chaotisch of emotioneel was, neem bewust de tijd om de sfeer te resetten.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Wisseldagen kunnen gepaard gaan met spanning, tranen of boosheid. Een bewust herstellend moment helpt het kind landen in het nieuwe huis zonder de stress van de overgang mee te dragen.",
    skillTip: "Doe iets rustgevends samen: warme chocolademelk, een wandeling, of gewoon samen op de bank zitten. Zeg: 'Het was een rommelig begin, maar nu zijn we hier en het is goed.'",
    vermijd: "De wissel analyseren of de andere ouder bekritiseren. Focus op het nu.",
    leerdoel: "Je leert bewust een nieuwe start te creëren na een stressvolle overgang.",
    bron: "Bray & Kelly (1998) - Stepfamilies: Love, Marriage, and Parenting in the First Decade",
    themes: ["bonuskind", "co-ouderschap", "samengesteld_gezin"],
  },
  {
    id: "bonus_herst_05",
    title: "Terugkeren na emotionele afstand",
    skill: "Herstel",
    description: "Als er een periode van afstand of koelheid was tussen jou en je bonuskind, maak een klein gebaar van toenadering.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Perioden van afstand zijn normaal in bonusrelaties. De kunst is om na zo'n periode de eerste stap te zetten zonder de afstand te benoemen. Een klein gebaar kan de deur weer openen.",
    skillTip: "Maak hun lievelingseten, leg een briefje neer, of stel voor samen iets te doen dat ze leuk vinden. Geen groot gesprek nodig — het gebaar spreekt.",
    vermijd: "Zeggen: 'We hebben het de laatste tijd niet zo gezellig gehad, hè?' Dat legt druk op het kind.",
    leerdoel: "Je leert kleine, drukvrije gebaren te maken om de verbinding te herstellen na afstand.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_herst_06",
    title: "Erkennen dat het moeilijk is",
    skill: "Herstel",
    description: "Zeg tegen je bonuskind: 'Ik weet dat het niet altijd makkelijk is met mij erbij. Ik wil dat je weet dat ik mijn best doe, en dat het oké is als het soms niet lukt.'",
    duration: "5 min",
    ageGroups: ["10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Kwetsbaarheid van een volwassene is voor tieners ontzettend krachtig. Het doorbreekt het beeld dat volwassenen alles onder controle hebben en geeft toestemming om ook zelf imperfect te zijn.",
    skillTip: "Kies een rustig moment, niet na een conflict. Zeg het simpel en kort. Verwacht geen reactie — het kind heeft tijd nodig om dit te verwerken.",
    vermijd: "Dit gebruiken als emotionele manipulatie ('Ik doe zo mijn best en jij waardeert het niet'). Het gaat om kwetsbaarheid, niet om schuldgevoel.",
    leerdoel: "Je leert kwetsbaarheid te tonen als kracht, wat de emotionele veiligheid in de relatie vergroot.",
    bron: "Brown (2012) - Daring Greatly",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_herst_07",
    title: "Samen opnieuw beginnen",
    skill: "Herstel",
    description: "Stel je bonuskind voor om samen een 'reset' te doen: 'Zullen we afspreken dat we vanaf vandaag opnieuw proberen? Geen score meer bijhouden.'",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "In bonusrelaties kan er een onuitgesproken scorebord ontstaan van wederzijdse grieven. Een bewuste reset geeft beide partijen toestemming om het verleden los te laten.",
    skillTip: "Maak het concreet: 'Ik weet dat ik dingen heb gedaan die niet oké waren, en jij misschien ook. Zullen we afspreken dat we vanaf nu opnieuw beginnen?' Wees de eerste die iets loslaat.",
    vermijd: "Een reset voorstellen en vervolgens oude grieven weer oprakelen. Als je reset zegt, moet je het menen.",
    leerdoel: "Je leert het verleden actief los te laten om ruimte te maken voor een nieuwe dynamiek.",
    bron: "Ganong & Coleman (2017) - Stepfamily Relationships: Development, Dynamics, and Interventions",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_herst_08",
    title: "Herstel met je partner over opvoedverschillen",
    skill: "Herstel",
    description: "Bespreek met je partner een recent moment waarop jullie het niet eens waren over de opvoeding van het bonuskind. Zoek samen naar een middenweg.",
    duration: "20 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Opvoedverschillen zijn de grootste bron van conflict in samengestelde gezinnen. Het kind voelt deze spanning, zelfs als het niet direct betrokken is. Herstel tussen de volwassenen herstelt ook de veiligheid voor het kind.",
    skillTip: "Begin met: 'Ik wil begrijpen hoe jij het ziet.' Luister eerst, verdedig later. Zoek naar de gemeenschappelijke zorg: het welzijn van het kind.",
    vermijd: "Gelijk willen hebben. In samengestelde gezinnen zijn er zelden zwart-witte antwoorden.",
    leerdoel: "Je leert opvoedconflicten met je partner te repareren door naar de gedeelde intentie te zoeken.",
    bron: "Gottman & Silver (1999) - The Seven Principles for Making Marriage Work",
    themes: ["samengesteld_gezin", "bonuskind"],
  },
  {
    id: "bonus_herst_09",
    title: "Herstellen na een gemist moment",
    skill: "Herstel",
    description: "Als je een belangrijk moment van je bonuskind hebt gemist (optreden, wedstrijd, schoolfeest), erken dit en maak het goed.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Gemiste momenten raken bonuskinderen extra hard omdat ze bevestigen dat ze 'niet echt' bij het gezin horen. Door het te erkennen en te repareren, laat je het tegenovergestelde zien.",
    skillTip: "Zeg: 'Het spijt me dat ik er niet was bij [moment]. Dat was belangrijk voor jou en ik had er willen zijn. Wil je me erover vertellen?' Vraag details, toon oprechte interesse.",
    vermijd: "Excuses zonder actie. Voeg er een gebaar aan toe: bekijk samen foto's of video's, of plan iets speciaals.",
    leerdoel: "Je leert gemiste momenten te repareren door erkenning en oprechte interesse.",
    bron: "Chapman & Campbell (2016) - The 5 Love Languages of Children",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_herst_10",
    title: "Vergeving als proces",
    skill: "Herstel",
    description: "Reflecteer op iets waarvan je weet dat je bonuskind het je nog kwalijk neemt. Schrijf op hoe je dit zou willen repareren, zonder verwachting van onmiddellijke vergeving.",
    duration: "15 min",
    ageGroups: ["10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Vergeving in bonusrelaties kan niet afgedwongen worden. Sommige wonden hebben maanden of jaren nodig. Door het als proces te zien in plaats van een afvinkoefening, respecteer je het tempo van het kind.",
    skillTip: "Schrijf op: (1) Wat deed ik? (2) Hoe heeft het kind zich daarbij gevoeld? (3) Wat kan ik nu doen? Voer stap 3 uit zonder te zeggen: 'Kun je me vergeven?' Laat het komen.",
    vermijd: "Vergeving afdwingen of zeggen: 'Ik heb toch sorry gezegd?' Dat bagatelliseert het gevoel van het kind.",
    leerdoel: "Je leert vergeving te zien als een geschenk dat het kind geeft, niet als iets dat je kunt eisen.",
    bron: "Worthington (2003) - Forgiving and Reconciling: Bridges to Wholeness and Hope",
    themes: ["bonuskind"],
  },

  // ═══════════════════════════════════════════════════════════════
  // VERBINDING — Bonuskind (10 taken)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "bonus_verb_01",
    title: "Een gedeelde interesse vinden",
    skill: "Verbinding",
    description: "Ontdek iets waar zowel jij als je bonuskind van houdt. Het kan iets kleins zijn: een tv-serie, een sport, een soort eten.",
    duration: "15 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Gedeelde interesses zijn de lijm van bonusrelaties. In tegenstelling tot biologische banden, die onvoorwaardelijk zijn, bouwen bonusrelaties op gedeelde ervaringen en interesses.",
    skillTip: "Observeer wat je bonuskind leuk vindt en probeer er oprecht in geïnteresseerd te raken. Als het kind van gaming houdt, vraag: 'Kun je me laten zien hoe dit spel werkt?'",
    vermijd: "Doen alsof je iets leuk vindt terwijl dat niet zo is. Kinderen prikken daar doorheen. Zoek iets dat echt aansluit.",
    leerdoel: "Je leert verbinding te bouwen via gedeelde interesses als brug tussen twee werelden.",
    bron: "Bray & Kelly (1998) - Stepfamilies: Love, Marriage, and Parenting in the First Decade",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_verb_02",
    title: "Samen koken",
    skill: "Verbinding",
    description: "Kook samen een maaltijd met je bonuskind. Laat het kind kiezen wat jullie maken en geef het een echte taak.",
    duration: "20 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Samen koken combineert meerdere verbindingselementen: een gezamenlijk doel, fysieke nabijheid, samenwerking, en een tastbaar resultaat. Het is laagdrempelig en niet emotioneel beladen.",
    skillTip: "Geef het kind een verantwoordelijkheid die past bij de leeftijd: roeren, groenten wassen, deeg kneden. Zeg: 'Zonder jouw hulp lukt het niet.' Dat geeft belonging.",
    vermijd: "Alles overnemen als het niet perfect gaat. Het gaat om het samen zijn, niet om het resultaat.",
    leerdoel: "Je leert een alledaagse activiteit te gebruiken als verbindingsmoment.",
    bron: "Fiese et al. (2006) - A Review of 50 Years of Research on Family Routines and Rituals",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_verb_03",
    title: "Een eigen ritueel creëren",
    skill: "Verbinding",
    description: "Bedenk samen met je bonuskind een ritueel dat alleen van jullie tweeën is: een speciaal gebaar, een grapje, een handshake.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Rituelen creëren een gedeeld 'wij'-gevoel. In samengestelde gezinnen waar iedereen zijn eigen geschiedenis heeft, kunnen kleine, exclusieve rituelen een krachtige band smeden.",
    skillTip: "Begin klein: een speciale begroeting, een handgebaar, een geheim woord. Laat het kind mee bedenken of laat het organisch ontstaan uit een grappig moment.",
    vermijd: "Het forceren. Als het niet spontaan aanvoelt, probeer het later opnieuw. Rituelen moeten groeien, niet worden opgelegd.",
    leerdoel: "Je leert een uniek verbindingsritueel te ontwikkelen dat de exclusiviteit van jullie band benadrukt.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_verb_04",
    title: "Interesse in hun andere leven",
    skill: "Verbinding",
    description: "Toon oprechte interesse in het leven van je bonuskind bij de andere ouder, zonder uit te vragen. Luister naar wat ze spontaan delen.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Wanneer een bonusvader het andere deel van het leven van het kind erkent en waardeert, voelt het kind zich heel: het hoeft geen delen van zichzelf te verstoppen.",
    skillTip: "Als het kind vertelt over iets leuks bij de andere ouder, reageer positief: 'Wat gaaf! Vertel eens meer.' Dit laat zien dat je niet jaloers of bedreigd bent.",
    vermijd: "Competitief reageren ('Dat kunnen wij ook wel!') of het onderwerp snel veranderen. Dat communiceert onveiligheid.",
    leerdoel: "Je leert het hele leven van je bonuskind te omarmen, inclusief het deel dat niet met jou te maken heeft.",
    bron: "Ganong & Coleman (2017) - Stepfamily Relationships: Development, Dynamics, and Interventions",
    themes: ["bonuskind", "co-ouderschap"],
  },
  {
    id: "bonus_verb_05",
    title: "Samen naar buiten",
    skill: "Verbinding",
    description: "Ga een halfuur met alleen je bonuskind naar buiten: wandelen, fietsen, een balletje trappen. Eenvoudige buitenactiviteiten verlagen drempels.",
    duration: "20 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Buitenactiviteiten verlagen de emotionele intensiteit van face-to-face contact. Side-by-side activiteiten zijn voor bonusrelaties effectiever dan oog-in-oog situaties.",
    skillTip: "Kies iets fysiek en simpel. Niet te ambitieus — het gaat om samen bewegen en er zijn. Geen prestatie, geen competitie.",
    vermijd: "Er een hele uitstap van maken met verwachtingen. Een rondje om het blok kan genoeg zijn.",
    leerdoel: "Je leert laagdrempelige buitenactiviteiten te gebruiken als verbindingstool.",
    bron: "Louv (2005) - Last Child in the Woods",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_verb_06",
    title: "Foto van jullie samen",
    skill: "Verbinding",
    description: "Maak een foto van een leuk moment met je bonuskind en stuur het naar ze (of print het uit). Laat zien dat jullie momenten het bewaren waard zijn.",
    duration: "5 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Foto's zijn tastbaar bewijs dat een relatie bestaat en waardevol is. Voor bonuskinderen die twijfelen over hun plek, kan een foto een krachtig anker zijn.",
    skillTip: "Kies een spontaan, blij moment. Stuur het met een simpel berichtje: 'Dit was leuk vandaag.' Niet te zwaar, niet te sentimenteel.",
    vermijd: "Het kind dwingen te poseren of foto's maken als het kind dat niet wil. Respecteer de grens.",
    leerdoel: "Je leert alledaagse momenten vast te leggen als bouwstenen van jullie gezamenlijke geschiedenis.",
    bron: "Chapman & Campbell (2016) - The 5 Love Languages of Children",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_verb_07",
    title: "Hulp vragen aan je bonuskind",
    skill: "Verbinding",
    description: "Vraag je bonuskind om hulp bij iets waar het goed in is: 'Kun jij me helpen met...?' Dit toont respect en creëert samenwerking.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Hulp vragen keert de machtsverhouding om: het kind is even de expert, jij de leerling. Dit is een subtiele maar krachtige manier om respect te tonen en de band te versterken.",
    skillTip: "Kies iets waar het kind echt goed in is: technologie, een spel, een vaardigheid. Zeg: 'Jij weet hier meer van dan ik, kun je me helpen?' Wees oprecht in je bewondering.",
    vermijd: "Het als trucje gebruiken. Als je hulp vraagt, neem het antwoord dan serieus.",
    leerdoel: "Je leert kwetsbaarheid en respect te combineren door oprecht hulp te vragen aan je bonuskind.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_verb_08",
    title: "Het verhaal van jullie begin",
    skill: "Verbinding",
    description: "Vertel je bonuskind het verhaal van hoe jullie elkaar leerden kennen. Benoem een positieve eerste herinnering.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Elk gezin heeft een oorsprongsverhaal. Samengestelde gezinnen missen dit vaak. Door het ontstaan van jullie relatie te vertellen, geef je het kind een narratief: 'Wij hebben ook een begin.'",
    skillTip: "Vertel eerlijk en met humor: 'Ik was best zenuwachtig toen ik je voor het eerst zag. Ik wilde zo graag dat je me aardig zou vinden.' Kwetsbaarheid verbindt.",
    vermijd: "Het verhaal mooier maken dan het was. Kinderen waarderen eerlijkheid boven perfectie.",
    leerdoel: "Je leert een gedeeld narratief te creëren dat de bonusrelatie een geschiedenis en identiteit geeft.",
    bron: "Fiese et al. (2006) - A Review of 50 Years of Research on Family Routines and Rituals",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_verb_09",
    title: "Brieven heen en weer",
    skill: "Verbinding",
    description: "Leg een notitieboekje neer waarin jij en je bonuskind naar elkaar kunnen schrijven. Berichten, tekeningen, grapjes — alles mag.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Geschreven communicatie biedt een veilige afstand voor kinderen die moeite hebben met directe emotionele gesprekken. Het boekje wordt een gedeeld bezit dat de band symboliseert.",
    skillTip: "Begin zelf met een kort bericht: 'Hé, ik dacht dat het leuk zou zijn om zo naar elkaar te schrijven. Alleen voor ons.' Leg het op een plek waar het kind het vindt. Geen druk om te antwoorden.",
    vermijd: "Teleurgesteld reageren als het kind niet terugschrijft. Het kan weken duren. Geduld is sleutel.",
    leerdoel: "Je leert een alternatief communicatiekanaal te openen voor emoties die moeilijk hardop te zeggen zijn.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_verb_10",
    title: "Een traditie starten",
    skill: "Verbinding",
    description: "Start een traditie die specifiek is voor jullie samengesteld gezin: een speciale maaltijd, een jaarlijkse uitstap, een eigen feestdag.",
    duration: "20 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Nieuwe tradities geven een samengesteld gezin een eigen identiteit naast de tradities die kinderen meebrengen uit hun oorspronkelijke gezin. Het zegt: 'Wij zijn ook iets bijzonders.'",
    skillTip: "Betrek iedereen bij het bedenken: 'Wat zouden wij als gezin altijd samen kunnen doen?' Laat het niet concurreren met tradities uit het andere huis. Kies iets uniek voor jullie.",
    vermijd: "Een traditie kopiëren van het andere huis of iets opdringen. Het moet organisch voelen en door iedereen gewild zijn.",
    leerdoel: "Je leert een gedeelde identiteit op te bouwen door nieuwe tradities die van iedereen in het samengesteld gezin zijn.",
    bron: "Fiese et al. (2006) - A Review of 50 Years of Research on Family Routines and Rituals",
    themes: ["samengesteld_gezin", "bonuskind"],
  },

  // ═══════════════════════════════════════════════════════════════
  // REFLECTIE — Bonuskind (10 taken)
  // ═══════════════════════════════════════════════════════════════
  {
    id: "bonus_refl_01",
    title: "Jouw bonuskind-verhaal",
    skill: "Reflectie",
    description: "Schrijf in 10 minuten het verhaal van hoe je bonusvader bent geworden. Wat had je verwacht? Wat viel mee? Wat viel tegen?",
    duration: "10 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Narratieve reflectie helpt om ervaringen te organiseren en betekenis te geven. Veel bonusvaders hebben nooit bewust stilgestaan bij hun eigen verhaal en de emoties daarin.",
    skillTip: "Schrijf zonder filter. Niemand leest dit. Wees eerlijk over teleurstellingen, boosheid, en ook over mooie momenten. Het gaat om bewustzijn, niet om een mooi verhaal.",
    vermijd: "Alleen de positieve kant beschrijven. Eerlijke reflectie includeert de moeilijke gevoelens.",
    leerdoel: "Je leert je eigen bonusouder-verhaal te verwoorden als basis voor bewuster ouderschap.",
    bron: "Siegel & Hartzell (2003) - Parenting from the Inside Out",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_refl_02",
    title: "Wat het kind meebrengt",
    skill: "Reflectie",
    description: "Reflecteer op wat je bonuskind aan jouw leven heeft toegevoegd. Schrijf drie dingen op die je van dit kind hebt geleerd.",
    duration: "10 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Bonusvaders focussen vaak op wat ze geven. Deze oefening keert het perspectief om: wat ontvang je? Dit verschuift de relatie van plicht naar wederkerigheid.",
    skillTip: "Denk aan concrete momenten: 'Door [naam] heb ik geleerd om geduldiger te zijn / meer naar muziek te luisteren / beter te koken.' Specificiteit maakt het echt.",
    vermijd: "Algemeenheden als 'het heeft me een beter mens gemaakt.' Zoek de concrete, kleine dingen.",
    leerdoel: "Je leert de wederkerigheid in jullie relatie te zien en te waarderen.",
    bron: "Emmons (2007) - Thanks! How the New Science of Gratitude Can Make You Happier",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_refl_03",
    title: "Spiegel van je eigen jeugd",
    skill: "Reflectie",
    description: "Reflecteer op je eigen kindertijd. Was er een volwassene buiten je ouders die belangrijk voor je was? Wat maakte die persoon bijzonder?",
    duration: "15 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Veel bonusvaders onderschatten hun impact omdat ze denken dat alleen biologische ouders ertoe doen. Door te reflecteren op niet-ouder volwassenen in je eigen jeugd, zie je dat extra hechtingsfiguren enorm waardevol zijn.",
    skillTip: "Denk aan een leraar, oom, buurman, of coach die er voor je was. Wat deed die persoon? Waarschijnlijk: aanwezig zijn, luisteren, en je zien. Dat kun jij ook.",
    vermijd: "Concluderen dat je niet belangrijk kunt zijn omdat je 'maar' de bonusvader bent. Dat klopt niet.",
    leerdoel: "Je leert vanuit je eigen ervaring te begrijpen dat niet-ouder volwassenen een levensveranderende rol kunnen spelen.",
    bron: "Siegel & Hartzell (2003) - Parenting from the Inside Out",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_refl_04",
    title: "De rol die bij je past",
    skill: "Reflectie",
    description: "Schrijf op welke rol je het liefst zou vervullen voor je bonuskind: vader, mentor, vriend, beschermer, of iets anders. Waar voel jij je het meest authentiek?",
    duration: "15 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Er is geen vast script voor bonusvaders. De druk om 'vader' te zijn terwijl er al een vader is, leidt tot rolverwarring. Bewust kiezen welke rol past, vermindert stress en verhoogt authenticiteit.",
    skillTip: "Er is geen goed of fout antwoord. Sommige bonusvaders zijn een soort 'coole oom', anderen worden een gelijkwaardige ouder. Wat voelt voor jou én het kind het best?",
    vermijd: "Een rol kiezen die de biologische vader bedreigt of vervangt. Aanvullen is krachtiger dan vervangen.",
    leerdoel: "Je leert een authentieke rol te definiëren die past bij jou, het kind, en de situatie.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_refl_05",
    title: "Gesprek met je partner over jullie visie",
    skill: "Reflectie",
    description: "Bespreek met je partner: hoe zien jullie de rol van jou als bonusvader over vijf jaar? Hebben jullie dezelfde verwachtingen?",
    duration: "20 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Onderzoek toont dat de meeste problemen in samengestelde gezinnen ontstaan door ongelijke verwachtingen tussen de partners. Eén denkt dat de bonusvader een volwaardige ouder wordt, de ander ziet meer een ondersteunende rol.",
    skillTip: "Vraag open: 'Hoe zie jij mijn rol over vijf jaar? Verwacht je dat ik een ouder word, of meer een betrokken volwassene?' Luister zonder oordeel naar het antwoord.",
    vermijd: "Defensief reageren als de visie van je partner verschilt. Verschil in verwachting is normaal — het niet bespreken is het probleem.",
    leerdoel: "Je leert verwachtingen over jouw rol expliciet te bespreken met je partner.",
    bron: "Ganong & Coleman (2017) - Stepfamily Relationships: Development, Dynamics, and Interventions",
    themes: ["samengesteld_gezin", "bonuskind"],
  },
  {
    id: "bonus_refl_06",
    title: "De onzichtbare last herkennen",
    skill: "Reflectie",
    description: "Schrijf eerlijk op welke onzichtbare last je draagt als bonusvader: het gevoel buitengesloten te zijn, niet erkend worden, of altijd de tweede keus zijn.",
    duration: "15 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Bonusvaders dragen een unieke emotionele last die zelden erkend wordt — niet door de maatschappij, niet door het kind, soms niet eens door de partner. Het benoemen van deze last is de eerste stap naar verlichting.",
    skillTip: "Wees radicaal eerlijk: 'Ik voel me soms onzichtbaar / overbodig / buitengesloten.' Deze gevoelens zijn niet een teken van falen maar van betrokkenheid.",
    vermijd: "Je gevoelens wegrationaliseren ('Ik zou hier niet over moeten klagen'). Je gevoelens zijn valide.",
    leerdoel: "Je leert de specifieke emotionele uitdagingen van bonusvaderschap te erkennen en te verwoorden.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
  {
    id: "bonus_refl_07",
    title: "Reflectie op co-ouderschap",
    skill: "Reflectie",
    description: "Reflecteer eerlijk op je houding ten opzichte van de biologische vader van je bonuskind. Draag je bij aan een goede co-ouderschapsrelatie, of stoor je die onbewust?",
    duration: "15 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "De relatie tussen bonusvader en biologische vader is een van de minst besproken maar meest impactvolle dynamieken. Jouw houding beïnvloedt direct hoe veilig het kind zich voelt om van alle volwassenen te houden.",
    skillTip: "Vraag jezelf: 'Ben ik jaloers op de biologische vader? Heb ik respect voor zijn rol? Praat ik respectvol over hem?' Wees eerlijk — dit is voor jou, niet voor publiek.",
    vermijd: "Jezelf veroordelen voor negatieve gevoelens. Het is menselijk om te worstelen met deze dynamiek.",
    leerdoel: "Je leert je eigen rol in de co-ouderschapsdynamiek eerlijk te evalueren.",
    bron: "Emery (2004) - The Truth About Children and Divorce",
    themes: ["co-ouderschap", "bonuskind"],
  },
  {
    id: "bonus_refl_08",
    title: "Wat zou je bonuskind zeggen?",
    skill: "Reflectie",
    description: "Stel je voor dat je bonuskind als volwassene terugkijkt op jullie relatie. Wat zou het over jou zeggen? Wat wil je dat het zegt?",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Toekomstgerichte reflectie helpt om dagelijkse frustraties in perspectief te plaatsen. Het verschuift de focus van 'dit gaat niet goed' naar 'waar wil ik naartoe?'",
    skillTip: "Schrijf twee versies: (1) Wat het kind nu zou zeggen, en (2) Wat je hoopt dat het over 20 jaar zegt. Het verschil daartussen is jouw kompas.",
    vermijd: "Onrealistische verwachtingen. Het hoeft niet 'hij was als een echte vader' te zijn. 'Hij was er voor me' is al prachtig.",
    leerdoel: "Je leert een langetermijnvisie te ontwikkelen die richting geeft aan je dagelijkse bonusouderschap.",
    bron: "Covey (1989) - The 7 Habits of Highly Effective People",
    themes: ["bonuskind"],
  },
  {
    id: "bonus_refl_09",
    title: "Reflectie op jouw gezinsbeeld",
    skill: "Reflectie",
    description: "Schrijf op hoe jouw beeld van een 'normaal gezin' eruitziet. Hoe verschilt dat van je werkelijke samengesteld gezin? Waar zit de spanning?",
    duration: "15 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Veel frustratie in samengestelde gezinnen komt voort uit het vergelijken met een kerngezin-ideaal dat niet bij de werkelijkheid past. Bewustzijn van dit beeld is bevrijdend.",
    skillTip: "Wees eerlijk: 'Ik had verwacht dat...' en vergelijk met: 'De werkelijkheid is...' Het verschil daartussen verklaart veel van je frustratie. Kun je het ideaalbeeld bijstellen?",
    vermijd: "Jezelf veroordelen voor het ideaalbeeld. Iedereen heeft het. Het gaat om bewustzijn.",
    leerdoel: "Je leert je onbewuste gezinsideaal te onderzoeken en aan te passen aan de werkelijkheid van een samengesteld gezin.",
    bron: "Papernow (2013) - Surviving and Thriving in Stepfamily Relationships",
    themes: ["samengesteld_gezin", "bonuskind"],
  },
  {
    id: "bonus_refl_10",
    title: "Brief aan jezelf over een jaar",
    skill: "Reflectie",
    description: "Schrijf een brief aan jezelf die je over een jaar opent. Beschrijf waar je nu staat als bonusvader, wat je hoopt, en wat je wilt laten gaan.",
    duration: "15 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Toekomstbrieven activeren het langetermijndenken en helpen om de dagelijkse uitdagingen in perspectief te plaatsen. Over een jaar terugkijken geeft inzicht in groei die je anders niet zou opmerken.",
    skillTip: "Schrijf over: (1) Hoe je relatie met je bonuskind nu is, (2) Wat je graag zou willen bereiken, (3) Wat je bereid bent los te laten. Stop de brief in een envelop met datum. Open hem precies over een jaar.",
    vermijd: "Alleen doelen opschrijven. Beschrijf ook je gevoelens en twijfels. Dat maakt de brief over een jaar waardevol.",
    leerdoel: "Je leert reflectie te verbinden met toekomstperspectief en groei zichtbaar te maken.",
    bron: "Wilson & Ross (2001) - From Chump to Champ: People's Appraisals of Their Earlier and Present Selves",
    themes: ["bonuskind", "samengesteld_gezin"],
  },
];
