import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_1: InteractiveTask[] = [
  // ═══════════════════════════════════════════════════════════════
  // AANWEZIGHEID (50 taken: 5 leeftijdsgroepen × 10 taken)
  // ═══════════════════════════════════════════════════════════════

  // ── Aanwezigheid · 0-2 jaar ────────────────────────────────────
  {
    id: "aanw_02_01",
    title: "Telefoon in de la",
    skill: "Aanwezigheid",
    description: "Leg je telefoon 20 minuten in een la terwijl je met je baby speelt. Geen uitzonderingen.",
    duration: "20 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Onderzoek toont aan dat ouders die hun telefoon gebruiken tijdens spel gemiddeld 50% minder responsief reageren op signalen van hun kind.",
    skillTip: "Zet je telefoon op stil en leg hem fysiek buiten bereik — uit het zicht = uit je gedachten.",
    vermijd: "Snel tussendoor checken — je baby merkt elke keer dat je aandacht verschuift.",
    leerdoel: "Je leert ononderbroken aandacht te geven aan je baby.",
    bron: "Radesky et al. (2014) - Patterns of Mobile Device Use by Caregivers and Children",
  },
  {
    id: "aanw_02_02",
    title: "Oogcontact bij de fles",
    skill: "Aanwezigheid",
    description: "Maak tijdens de volgende voeding bewust oogcontact met je baby. Kijk niet naar een scherm.",
    duration: "10 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Oogcontact tijdens voeding activeert het oxytocinesysteem bij zowel vader als baby, wat de hechtingsband versterkt.",
    skillTip: "Praat zachtjes tegen je baby terwijl je voeding geeft — vertel over je dag of zing een liedje.",
    vermijd: "TV of telefoon erbij — het devalueert een van de meest intieme momenten.",
    leerdoel: "Je leert voedingsmomenten te gebruiken als hechtingsmomenten.",
    bron: "Feldman (2012) - Oxytocin and social affiliation in humans",
  },
  {
    id: "aanw_02_03",
    title: "Vloertijd",
    skill: "Aanwezigheid",
    description: "Ga 15 minuten op de grond zitten bij je baby. Volg wat je kind doet in plaats van te sturen.",
    duration: "15 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Child-led play versterkt het gevoel van autonomie en competentie bij het kind, zelfs al op babyleeftijd.",
    skillTip: "Weersta de neiging om speelgoed aan te bieden — observeer eerst wat je baby zelf pakt.",
    vermijd: "Het spel overnemen of constant nieuw speelgoed aanbieden.",
    leerdoel: "Je leert je kind te volgen in plaats van te leiden.",
    bron: "Greenspan & Wieder (2006) - Floortime / DIR Model",
  },
  {
    id: "aanw_02_04",
    title: "Reactie op huilen",
    skill: "Aanwezigheid",
    description: "Als je baby huilt, reageer binnen 30 seconden. Pak op, maak oogcontact, zeg 'papa is er'.",
    duration: "2 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Snelle en consistente respons op huilen bouwt een veilige hechting op. Dit maakt kinderen later juist zelfstandiger.",
    skillTip: "Je hoeft het huilen niet te stoppen — je nabijheid is al genoeg.",
    vermijd: "Zeggen 'het is niks' of het huilen negeren om je kind te leren 'zelfredzaam' te zijn.",
    leerdoel: "Je leert responsief te reageren op de behoeften van je baby.",
    bron: "Ainsworth et al. (1978) - Patterns of Attachment",
  },
  {
    id: "aanw_02_05",
    title: "Narrate je handelingen",
    skill: "Aanwezigheid",
    description: "Vertel hardop wat je doet als je voor je baby zorgt: 'Papa doet nu je luier om, zo, lekker schoon.'",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Sportcasting — het benoemen van wat je doet — stimuleert taalontwikkeling en geeft je baby voorspelbaarheid.",
    skillTip: "Gebruik korte, eenvoudige zinnen en een warme toon. Benoem ook de gevoelens: 'Dat was koud hè!'",
    vermijd: "Zwijgend de verzorging doen alsof het een lopende-bandklus is.",
    leerdoel: "Je leert alledaagse verzorging om te zetten in verbindingsmomenten.",
    bron: "Hart & Risley (1995) - Meaningful Differences in the Everyday Experience of Young Children",
  },
  {
    id: "aanw_02_06",
    title: "Huid-op-huid moment",
    skill: "Aanwezigheid",
    description: "Houd je baby 10 minuten huid-op-huid tegen je borst. Adem rustig en wees stil.",
    duration: "10 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Huid-op-huid contact (kangaroo care) reguleert de hartslag en ademhaling van de baby en verlaagt cortisol bij vader.",
    skillTip: "Doe dit na het bad of voor het slapengaan — het wordt een rustgevend ritueel.",
    vermijd: "Ondertussen praten of bewegen — het gaat om stilte en nabijheid.",
    leerdoel: "Je leert non-verbale verbinding te maken met je baby.",
    bron: "Feldman et al. (2014) - Maternal and paternal kangaroo care",
  },
  {
    id: "aanw_02_07",
    title: "Welkomstritueel",
    skill: "Aanwezigheid",
    description: "Als je thuiskomt van werk: ga eerst naar je baby, til op, maak oogcontact en zeg 'papa is er!'",
    duration: "2 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Een consistent begroetingsritueel geeft je kind het signaal dat het prioriteit heeft boven werk, telefoon of post.",
    skillTip: "Leg eerst je tas neer, doe je jas uit — zodat je handen vrij zijn voor je kind.",
    vermijd: "Eerst je telefoon checken of naar de koelkast lopen voor je je kind begroet.",
    leerdoel: "Je leert een bewuste overgang te maken van werk naar vaderschap.",
    bron: "Gottman (1999) - The Seven Principles for Making Marriage Work (connection rituals)",
  },
  {
    id: "aanw_02_08",
    title: "Spiegel je baby",
    skill: "Aanwezigheid",
    description: "Zit 5 minuten tegenover je baby en spiegel de gezichtsuitdrukkingen. Lach als je baby lacht, kijk verbaasd als je baby verbaasd kijkt.",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Mirroring activeert spiegelneuronen en helpt je baby emoties te herkennen. Het is de basis van empathie-ontwikkeling.",
    skillTip: "Overdrijf je gezichtsuitdrukkingen licht — baby's reageren beter op duidelijke expressies.",
    vermijd: "Een blanco gezicht houden (het still-face experiment toont hoe stressvol dat is voor baby's).",
    leerdoel: "Je leert emotionele afstemming (attunement) met je baby.",
    bron: "Tronick (2007) - The Still Face Experiment",
  },
  {
    id: "aanw_02_09",
    title: "Nachtelijke aanwezigheid",
    skill: "Aanwezigheid",
    description: "Sta vannacht op als je baby huilt (in plaats van je partner). Pak op, sus, en blijf tot je baby rustig is.",
    duration: "15 min",
    ageGroups: ["0-2"],
    difficulty: "expert",
    points: 20,
    psychologie: "Vaders die ook 's nachts beschikbaar zijn, bouwen een even sterke hechtingsrelatie op als moeders. De nacht is geen 'moederdomein'.",
    skillTip: "Bereid je voor: leg een shirt dat je gedragen hebt bij de wieg — je geur stelt gerust.",
    vermijd: "Halverwege opgeven en je partner roepen — je baby leert dan dat papa het niet aankan.",
    leerdoel: "Je leert ook in moeilijke momenten beschikbaar te zijn als vader.",
    bron: "Abraham et al. (2014) - Father's brain is sensitive to childcare experiences",
  },
  {
    id: "aanw_02_10",
    title: "Solo-dag met baby",
    skill: "Aanwezigheid",
    description: "Plan een dagdeel (min. 3 uur) alleen met je baby. Geen hulp inschakelen. Jij doet alles: voeden, verschonen, spelen, slapen.",
    duration: "15 min",
    ageGroups: ["0-2"],
    difficulty: "expert",
    points: 20,
    psychologie: "Vaders die regelmatig alleen zorgen ontwikkelen dezelfde neurale patronen als primaire verzorgers. Het verandert letterlijk je brein.",
    skillTip: "Plan het als een 'date met je baby' — niet als oppassen. Jij bent ouder, niet babysitter.",
    vermijd: "Je partner bellen bij het eerste probleem — vertrouw op je eigen instinct.",
    leerdoel: "Je leert dat je een volledig competente ouder bent, ook zonder je partner.",
    bron: "Abraham et al. (2014) - Father's brain is sensitive to childcare experiences",
  },

  // ── Aanwezigheid · 3-5 jaar ────────────────────────────────────
  {
    id: "aanw_35_01",
    title: "Speciaal speelkwartier",
    skill: "Aanwezigheid",
    description: "Geef je kind 15 minuten onverdeelde aandacht. Het kind kiest de activiteit, jij volgt. Geen telefoon.",
    duration: "15 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Special Time (child-directed play) is de meest bewezen interventie voor het versterken van de ouder-kindrelatie.",
    skillTip: "Zeg letterlijk: 'Dit is jouw speciaal speelkwartier. Jij kiest wat we doen.'",
    vermijd: "Vragen stellen ('Wat is dat?'), corrigeren, of het spel sturen.",
    leerdoel: "Je leert de regie los te laten en je kind de leiding te geven.",
    bron: "Eyberg (1988) - Parent-Child Interaction Therapy (PCIT)",
  },
  {
    id: "aanw_35_02",
    title: "Voorleesmoment met stemmen",
    skill: "Aanwezigheid",
    description: "Lees een prentenboek voor en doe alle stemmen na. Maak het een theater-ervaring.",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Interactief voorlezen (dialogic reading) stimuleert taalontwikkeling 4x effectiever dan gewoon voorlezen.",
    skillTip: "Laat je kind de bladzijden omslaan en vraag: 'Wat denk jij dat er nu gebeurt?'",
    vermijd: "Snel doorlezen omdat het al laat is — kwaliteit boven kwantiteit.",
    leerdoel: "Je leert voorlezen om te zetten naar een interactief verbindingsmoment.",
    bron: "Whitehurst et al. (1988) - Dialogic Reading",
  },
  {
    id: "aanw_35_03",
    title: "Papa-date plannen",
    skill: "Aanwezigheid",
    description: "Plan deze week een activiteit met alleen jij en je kind. Laat je kind kiezen uit 2 opties.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Voorspelbare een-op-een tijd geeft kinderen een gevoel van zekerheid en belangrijkheid.",
    skillTip: "Schrijf het op de kalender zodat je kind het kan zien. Het vooruitkijken is deel van de vreugde.",
    vermijd: "Beloven en dan afzeggen — dat beschadigt vertrouwen meer dan nooit beloven.",
    leerdoel: "Je leert bewust vader-kind tijd in te plannen als prioriteit.",
    bron: "Lamb (2010) - The Role of the Father in Child Development",
  },
  {
    id: "aanw_35_04",
    title: "Spelen zonder 'goed zo'",
    skill: "Aanwezigheid",
    description: "Speel 10 minuten met je kind zonder één keer 'goed zo' of 'knap' te zeggen. Beschrijf in plaats daarvan wat je ziet.",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Beschrijvende feedback ('Ik zie dat je de blauwe blokken op de rode stapelt') stimuleert intrinsieke motivatie meer dan evaluatieve lof.",
    skillTip: "Zeg: 'Ik zie dat je...' of 'Je hebt gekozen om...' — beschrijf, oordeel niet.",
    vermijd: "Constant evalueren — het kind leert dan voor jouw goedkeuring te spelen in plaats van eigen plezier.",
    leerdoel: "Je leert het verschil tussen beschrijvende en evaluatieve feedback.",
    bron: "Kohn (2001) - Unconditional Parenting",
  },
  {
    id: "aanw_35_05",
    title: "Buitenspel zonder agenda",
    skill: "Aanwezigheid",
    description: "Ga naar buiten met je kind zonder plan. Volg de nieuwsgierigheid van je kind: een steen bekijken, een slak volgen, in plassen springen.",
    duration: "15 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Ongestructureerd buitenspel verlaagt cortisolniveaus bij kinderen en versterkt de ouder-kindband door gedeelde ontdekking.",
    skillTip: "Laat je kind het tempo bepalen. Als het 10 minuten naar een mier wil kijken, kijk je mee.",
    vermijd: "Haast maken of zeggen 'kom, we gaan verder' — het draait om het proces, niet de bestemming.",
    leerdoel: "Je leert aanwezig te zijn zonder doel of productiviteit.",
    bron: "Louv (2005) - Last Child in the Woods",
  },
  {
    id: "aanw_35_06",
    title: "Thuiskomst-ritueel uitbreiden",
    skill: "Aanwezigheid",
    description: "Maak een vast ritueel als je thuiskomt: geheime handshake, knuffel, en vraag 'wat was het leukste van vandaag?'",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Rituals of connection zorgen voor voorspelbaarheid en versterken de band. Kinderen van 3-5 bloeien op bij herhaling.",
    skillTip: "Laat je kind meebedenken aan het ritueel — dan voelt het als 'van ons'.",
    vermijd: "Het ritueel overslaan als je moe bent — juist dan heeft je kind het nodig.",
    leerdoel: "Je leert een bewuste overgang te maken van werkdag naar gezinstijd.",
    bron: "Fiese (2006) - Family Routines and Rituals",
  },
  {
    id: "aanw_35_07",
    title: "Meedoen met fantasiespel",
    skill: "Aanwezigheid",
    description: "Als je kind een fantasiespel speelt (doktertje, winkeltje, superhelden), stap volledig in de rol. Geen halve inzet.",
    duration: "15 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Wanneer vaders meedoen in fantasiespel, leren kinderen dat hun binnenwereld waardevol is. Het versterkt verbeeldingskracht en emotioneel vertrouwen.",
    skillTip: "Vraag: 'Wie ben ik in jouw verhaal?' en accepteer de rol die je krijgt — ook als je de zieke hond bent.",
    vermijd: "Het spel 'realistischer' maken of zeggen 'dat kan niet echt' — fantasie is de taal van het kind.",
    leerdoel: "Je leert de fantasiewereld van je kind serieus te nemen.",
    bron: "Singer & Singer (1990) - The House of Make-Believe",
  },
  {
    id: "aanw_35_08",
    title: "Samen koken",
    skill: "Aanwezigheid",
    description: "Betrek je kind bij het avondeten maken. Laat roeren, groente wassen, of deeg kneden. Het resultaat doet er niet toe.",
    duration: "15 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Samen een dagelijkse taak doen geeft kinderen het gevoel dat ze bijdragen aan het gezin. Dit bouwt competentie en verbondenheid.",
    skillTip: "Geef een echt klusje, niet een nep-taakje. Kinderen voelen het verschil.",
    vermijd: "Overnemen als het niet perfect gaat — het gaat om het samen doen, niet om het resultaat.",
    leerdoel: "Je leert alledaagse momenten te benutten voor verbinding.",
    bron: "Montessori (1967) - The Absorbent Mind (praktische levensvaardigheden)",
  },
  {
    id: "aanw_35_09",
    title: "Emotiecheck bij het slapengaan",
    skill: "Aanwezigheid",
    description: "Ga 5 minuten op de rand van het bed zitten voor het slapen. Vraag: 'Hoe voelde je je vandaag?' Luister zonder te adviseren.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "expert",
    points: 20,
    psychologie: "Het slapengaan is het moment waarop kinderen het meest open zijn. De combinatie van vermoeidheid en veiligheid maakt diepe gesprekken mogelijk.",
    skillTip: "Reageer met 'vertel eens meer' in plaats van oplossingen te geven.",
    vermijd: "Haast hebben om het licht uit te doen — deze 5 minuten zijn goud waard.",
    leerdoel: "Je leert een veilige ruimte te creëren voor emotionele openheid.",
    bron: "Siegel & Bryson (2011) - The Whole-Brain Child",
  },
  {
    id: "aanw_35_10",
    title: "Hele dag telefoonvrij",
    skill: "Aanwezigheid",
    description: "Kies een halve dag in het weekend en gebruik je telefoon helemaal niet waar je kind bij is. Leg uit waarom.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "expert",
    points: 20,
    psychologie: "Kinderen van 3-5 internaliseren het voorbeeld van hun vader. Een vader die zijn telefoon weglegt zegt impliciet: 'jij bent belangrijker dan dit scherm.'",
    skillTip: "Vertel je kind: 'Vandaag heb ik geen telefoon nodig, want ik wil bij jou zijn.'",
    vermijd: "Stiekem checken op de wc — kinderen merken het altijd.",
    leerdoel: "Je leert dat volledige aanwezigheid een bewuste keuze is die je kunt oefenen.",
    bron: "Turkle (2015) - Reclaiming Conversation",
  },

  // ── Aanwezigheid · 6-9 jaar ────────────────────────────────────
  {
    id: "aanw_69_01",
    title: "Huiswerkmaatje",
    skill: "Aanwezigheid",
    description: "Zit naast je kind tijdens huiswerk. Niet helpen tenzij gevraagd — alleen aanwezig zijn.",
    duration: "15 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "De nabijheid van een ouder verlaagt de stress die kinderen bij huiswerk ervaren, zonder dat je inhoudelijk hoeft te helpen.",
    skillTip: "Doe zelf ook iets 'stils' — lees een boek of schrijf. Model het gedrag dat je wilt zien.",
    vermijd: "Constant over de schouder meekijken of fouten aanwijzen — dat verhoogt de druk.",
    leerdoel: "Je leert aanwezig te zijn zonder het over te nemen.",
    bron: "Pomerantz et al. (2007) - The How, Whom, and Why of Parents' Involvement in Children's Academic Lives",
  },
  {
    id: "aanw_69_02",
    title: "Lopend naar school",
    skill: "Aanwezigheid",
    description: "Loop of fiets met je kind naar school. Geen oortjes in, geen haast. Praat over wat je ziet onderweg.",
    duration: "15 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Side-by-side activiteiten (naast elkaar lopen) zijn voor kinderen vaak makkelijker voor praten dan face-to-face gesprekken.",
    skillTip: "Begin niet met vragen over school. Wijs iets aan: 'Kijk, die boom heeft bloesem!' Gesprek volgt vanzelf.",
    vermijd: "De hele weg instructies geven over wat ze vandaag moeten doen.",
    leerdoel: "Je leert looptijd te gebruiken als connectietijd.",
    bron: "Kindlon & Thompson (2000) - Raising Cain",
  },
  {
    id: "aanw_69_03",
    title: "Interesse tonen in hun wereld",
    skill: "Aanwezigheid",
    description: "Vraag je kind om je iets te leren over hun hobby (Minecraft, Pokémon, turnen). Luister 10 minuten zonder oordeel.",
    duration: "10 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Wanneer je oprechte interesse toont in wat je kind bezighoudt, geef je het bericht: 'Wat voor jou belangrijk is, is voor mij ook belangrijk.'",
    skillTip: "Stel doorvragen: 'Hoe werkt dat dan?' — laat je kind de expert zijn.",
    vermijd: "Doen alsof je luistert terwijl je aan iets anders denkt — kinderen voelen onechtheid feilloos aan.",
    leerdoel: "Je leert je in de leefwereld van je kind te verdiepen.",
    bron: "Gottman (1997) - Raising An Emotionally Intelligent Child",
  },
  {
    id: "aanw_69_04",
    title: "Wekelijks vader-kind uitje",
    skill: "Aanwezigheid",
    description: "Plan elke week een vast moment voor jou en je kind. Het hoeft niet spectaculair: samen boodschappen doen telt ook.",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Voorspelbare een-op-een tijd geeft kinderen iets om naar uit te kijken en communiceert dat ze prioriteit zijn.",
    skillTip: "Zet het in je agenda als een afspraak die niet verschoven wordt — net als een werkvergadering.",
    vermijd: "Het altijd afhankelijk maken van 'als ik tijd heb' — dat is voor een kind een code voor 'niet belangrijk'.",
    leerdoel: "Je leert structurele vader-kindtijd in te bouwen in je week.",
    bron: "Lamb (2010) - The Role of the Father in Child Development",
  },
  {
    id: "aanw_69_05",
    title: "Samen sporten",
    skill: "Aanwezigheid",
    description: "Doe een sportactiviteit samen: voetballen, fietsen, zwemmen. Focus op plezier, niet op presteren.",
    duration: "15 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Fysieke activiteit samen verlaagt cortisol en verhoogt endorfine bij beide. De gedeelde ervaring creëert hechtingsmomenten.",
    skillTip: "Laat je kind winnen zonder dat het nep voelt. Pas je niveau aan zodat het uitdagend maar haalbaar is.",
    vermijd: "Wedstrijdelementen benadrukken of teleurgesteld reageren bij fouten.",
    leerdoel: "Je leert lichamelijke activiteit als verbindingsmoment te gebruiken.",
    bron: "Panksepp (2004) - Affective Neuroscience (PLAY-systeem)",
  },
  {
    id: "aanw_69_06",
    title: "Schooldag-gesprek upgraden",
    skill: "Aanwezigheid",
    description: "Vervang 'Hoe was het op school?' (antwoord: 'goed') door specifieke vragen: 'Wat was het grappigste vandaag?' of 'Met wie heb je gespeeld?'",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Specifieke vragen activeren het episodisch geheugen en helpen kinderen hun dag te verwerken. Open vragen nodigen uit tot nadenken.",
    skillTip: "Probeer: 'Was er iets moeilijks vandaag?' en 'Wat was het beste moment?'",
    vermijd: "Doorvragen als je kind niet wil praten — soms is 'nu niet' oké. Probeer het later opnieuw.",
    leerdoel: "Je leert betere vragen te stellen die echte gesprekken opleveren.",
    bron: "Siegel & Bryson (2011) - The Whole-Brain Child",
  },
  {
    id: "aanw_69_07",
    title: "Aanwezig bij een optreden",
    skill: "Aanwezigheid",
    description: "Ga naar het schooloptreden, de zwemles of voetbalwedstrijd van je kind. Wees er op tijd en kijk echt.",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen scannen het publiek op zoek naar hun ouders. Die ene blik van herkenning is krachtiger dan elk compliment achteraf.",
    skillTip: "Zoek oogcontact met je kind en steek je duim op — die seconde onthouden ze jaren.",
    vermijd: "Het hele optreden door je telefoon filmen — kijk met je ogen, niet door een scherm.",
    leerdoel: "Je leert dat aanwezigheid bij belangrijke momenten meer zegt dan woorden.",
    bron: "Bronfenbrenner (1979) - The Ecology of Human Development",
  },
  {
    id: "aanw_69_08",
    title: "Autorit-gesprekken",
    skill: "Aanwezigheid",
    description: "Gebruik een autorit samen als praatmoment. Zet de radio uit en vraag je kind iets waar het over na wil denken.",
    duration: "10 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "In de auto kijken jullie allebei vooruit — geen oogcontact. Dit verlaagt de druk en maakt het makkelijker om over moeilijke dingen te praten.",
    skillTip: "Probeer vragen als: 'Als je één ding kon veranderen op school, wat zou het zijn?'",
    vermijd: "De radio aanzetten als het stil wordt — stilte is prima, het hoeft niet altijd gevuld te worden.",
    leerdoel: "Je leert alledaagse momenten om te zetten in verbindingstijd.",
    bron: "Kindlon & Thompson (2000) - Raising Cain",
  },
  {
    id: "aanw_69_09",
    title: "Gedeelde hobby starten",
    skill: "Aanwezigheid",
    description: "Start een hobby samen met je kind waar jullie beiden nieuw in zijn. Samen beginnen maakt je gelijkwaardig.",
    duration: "15 min",
    ageGroups: ["6-9"],
    difficulty: "expert",
    points: 20,
    psychologie: "Wanneer vader en kind allebei beginner zijn, vervalt de hiërarchie. Dit creëert een uniek soort verbinding gebaseerd op gelijkwaardigheid.",
    skillTip: "Kies iets waar je allebei slecht in bent: schaken, origami, skateboarden. Lachen om elkaars fouten verbindt.",
    vermijd: "Iets kiezen waar jij al goed in bent — dan word je leraar in plaats van maatje.",
    leerdoel: "Je leert een relatie op te bouwen gebaseerd op gedeelde kwetsbaarheid.",
    bron: "Csikszentmihalyi (1990) - Flow (gedeelde flow-ervaringen)",
  },
  {
    id: "aanw_69_10",
    title: "Brief aan je kind",
    skill: "Aanwezigheid",
    description: "Schrijf een kort briefje aan je kind en leg het in de broodtrommel of onder het kussen: 'Ik denk aan je. Papa.'",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "expert",
    points: 20,
    psychologie: "Een geschreven boodschap is tastbaar en kan herlezen worden. Het geeft een gevoel van veiligheid ook als papa niet fysiek aanwezig is.",
    skillTip: "Houd het simpel — één zin is genoeg. 'Ik vind het knap hoe je gisteren...' werkt sterk.",
    vermijd: "Er een gewoonte van maken die je niet kunt volhouden — eenmalig is ook waardevol.",
    leerdoel: "Je leert je aanwezigheid voelbaar te maken, ook als je er niet bent.",
    bron: "Chapman (2015) - The 5 Love Languages of Children",
  },

  // ── Aanwezigheid · 10-12 jaar ──────────────────────────────────
  {
    id: "aanw_1012_01",
    title: "Tech-vrije zone",
    skill: "Aanwezigheid",
    description: "Stel voor om samen 30 minuten alle schermen uit te doen. Doe een kaartspel, puzzel, of praat gewoon.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Pre-teens zijn bezig een digitale identiteit te ontwikkelen. Door tech-vrije momenten te modelen, leer je ze dat offline-connectie waardevol is.",
    skillTip: "Maak er geen straf van. Zeg: 'Ik wil ook mijn telefoon even weg — zullen we samen iets doen?'",
    vermijd: "Alleen je kind vragen om schermen weg te leggen terwijl jij de jouwe houdt.",
    leerdoel: "Je leert schermvrije tijd te normaliseren als gedeelde keuze.",
    bron: "Turkle (2015) - Reclaiming Conversation",
  },
  {
    id: "aanw_1012_02",
    title: "Lunch-date op school",
    skill: "Aanwezigheid",
    description: "Verras je kind door een keer lunch te brengen op school (als het mag). Of plan een lunch samen in het weekend.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Op deze leeftijd beginnen kinderen zich los te maken van ouders. Kleine verrassingen tonen dat je nog steeds bewust aanwezig bent.",
    skillTip: "Vraag eerst of je kind dit oké vindt — sommige 10-12 jarigen vinden het gênant, respecteer dat.",
    vermijd: "Het doen zonder te checken — respect voor hun sociale wereld is op deze leeftijd essentieel.",
    leerdoel: "Je leert aanwezigheid aan te passen aan de groeiende autonomie van je kind.",
    bron: "Steinberg (2001) - We Know Some Things: Parent–Adolescent Relationships",
  },
  {
    id: "aanw_1012_03",
    title: "Interesse in hun muziek",
    skill: "Aanwezigheid",
    description: "Vraag je kind om je hun favoriete nummers te laten horen. Luister echt — zonder commentaar op de teksten.",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Muziek is voor pre-teens een manier om identiteit te verkennen. Door te luisteren zonder oordeel, laat je zien dat je hun zelf-ontdekking respecteert.",
    skillTip: "Vraag: 'Waarom vind je dit nummer mooi?' — de reden vertelt meer dan het nummer.",
    vermijd: "Zeggen 'in mijn tijd was de muziek beter' — dat sluit de deur dicht.",
    leerdoel: "Je leert je in de culturele wereld van je kind te begeven.",
    bron: "Ginott (1965) - Between Parent and Child",
  },
  {
    id: "aanw_1012_04",
    title: "Samen een project doen",
    skill: "Aanwezigheid",
    description: "Start een gezamenlijk project: een vogelhuisje bouwen, een app leren, een recept uitproberen. Iets met een duidelijk resultaat.",
    duration: "15 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Op deze leeftijd willen kinderen competentie voelen. Een project samen doen geeft ze een gevoel van vaardigheid én verbinding.",
    skillTip: "Verdeel de taken eerlijk — geef je kind de verantwoordelijkheid voor een echt onderdeel.",
    vermijd: "Het project overnemen als het niet snel genoeg gaat — het gaat om samen doen.",
    leerdoel: "Je leert samenwerking als verbindingsmiddel in te zetten.",
    bron: "Erikson (1963) - Childhood and Society (Industry vs. Inferiority)",
  },
  {
    id: "aanw_1012_05",
    title: "Meelopen met hun activiteit",
    skill: "Aanwezigheid",
    description: "Bied aan om een keer mee te gaan naar de sporttraining, muziekles of scouting van je kind. Niet om te controleren, maar om te zien wat ze doen.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen voelen zich gezien als hun vader moeite doet om hun wereld buiten huis te kennen. Het vergroot hun gevoel van belang.",
    skillTip: "Zeg achteraf: 'Ik vond het mooi om te zien hoe je...' — benoem iets specifieks.",
    vermijd: "Ongewenst advies geven na afloop of de coach/leraar aanspreken.",
    leerdoel: "Je leert de buitenwereld van je kind te leren kennen zonder in te grijpen.",
    bron: "Lamb (2010) - The Role of the Father in Child Development",
  },
  {
    id: "aanw_1012_06",
    title: "Avondwandeling samen",
    skill: "Aanwezigheid",
    description: "Ga na het eten een rondje wandelen met je kind. Geen doel, geen route. Gewoon lopen en praten.",
    duration: "15 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Wandelen verlaagt cortisol en de side-by-side opstelling verlaagt de druk van directe confrontatie, wat pre-teens helpt opener te zijn.",
    skillTip: "Begin over jezelf — vertel iets over je eigen dag. Kwetsbaarheid opent de deur voor wederkerigheid.",
    vermijd: "Het een verhoor maken: 'Hoe is het met school? En je cijfers? En die toets?'",
    leerdoel: "Je leert dat wandelen een krachtig middel is voor diepere gesprekken.",
    bron: "Oppezzo & Schwartz (2014) - Give Your Ideas Some Legs (Stanford walking study)",
  },
  {
    id: "aanw_1012_07",
    title: "Ontbijt voor je kind maken",
    skill: "Aanwezigheid",
    description: "Sta morgen 10 minuten eerder op en maak ontbijt klaar voor je kind. Ga erbij zitten en eet samen.",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Ochtendmomenten zetten de toon voor de hele dag. Een vader die 's ochtends investeert stuurt een krachtig signaal van zorg.",
    skillTip: "Maak iets speciaals: pannenkoeken op dinsdag, een smoothie — het hoeft niet dagelijks, eenmalig is al krachtig.",
    vermijd: "Ondertussen e-mails checken — als je het doet, doe het helemaal.",
    leerdoel: "Je leert kleine daden van zorg als aanwezigheidssignaal in te zetten.",
    bron: "Chapman (2015) - The 5 Love Languages of Children (Acts of Service)",
  },
  {
    id: "aanw_1012_08",
    title: "Game samen spelen",
    skill: "Aanwezigheid",
    description: "Speel een videogame samen met je kind — op hun voorwaarden. Laat je kind je leren hoe het werkt.",
    duration: "15 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Door je kind de rol van expert te geven, keer je de machtsverhouding om. Dit versterkt hun zelfvertrouwen en jullie band.",
    skillTip: "Wees oprecht nieuwsgierig: 'Hoe doe je dat dan?' 'Waarom koos je die strategie?'",
    vermijd: "Moraliseren over schermtijd terwijl je samen speelt — dat ondermijnt het moment.",
    leerdoel: "Je leert de digitale wereld van je kind als verbindingsruimte te betreden.",
    bron: "Przybylski & Weinstein (2017) - Digital Screen Time Guidelines",
  },
  {
    id: "aanw_1012_09",
    title: "Dieper gesprek initiëren",
    skill: "Aanwezigheid",
    description: "Stel een diepere vraag dan normaal: 'Waar maak jij je soms zorgen over?' of 'Wat zou je willen veranderen aan ons gezin?'",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Pre-teens beginnen abstract te denken. Diepere vragen helpen hen nadenken over zichzelf en tonen dat je hun mening serieus neemt.",
    skillTip: "Stel de vraag op een rustig moment — niet tijdens het eten met het hele gezin erbij.",
    vermijd: "Schrikken van het antwoord of meteen in oplossingsmodus gaan — luister alleen.",
    leerdoel: "Je leert gesprekken op een dieper niveau te voeren met je kind.",
    bron: "Siegel (2013) - Brainstorm: The Power and Purpose of the Teenage Brain",
  },
  {
    id: "aanw_1012_10",
    title: "Overnachting-avontuur",
    skill: "Aanwezigheid",
    description: "Plan een bijzondere overnachting met je kind: kamperen in de tuin, een nacht in een hotel, of in de woonkamer slapen.",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Gedeelde avonturen buiten de routine creëren 'flashbulb memories' — herinneringen die een leven lang meegaan en de band definiëren.",
    skillTip: "Maak er een traditie van: één keer per kwartaal een mini-avontuur. Het hoeft geen geld te kosten.",
    vermijd: "Het te groots opzetten — het gaat om samen zijn, niet om de locatie.",
    leerdoel: "Je leert dat gedeelde ervaringen de sterkste herinneringen bouwen.",
    bron: "Kahneman (2011) - Thinking, Fast and Slow (peak-end rule)",
  },

  // ── Aanwezigheid · 13-16 jaar ──────────────────────────────────
  {
    id: "aanw_1316_01",
    title: "Beschikbaar zijn zonder te pushen",
    skill: "Aanwezigheid",
    description: "Zeg tegen je tiener: 'Ik ben in de woonkamer als je wilt praten of gewoon wilt zitten.' Ga er zitten en wacht — zonder verwachting.",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Tieners hebben ouders nodig die beschikbaar zijn zonder opdringerig te zijn. Dit heet 'launching pad parenting' — een veilige thuisbasis.",
    skillTip: "Verwacht niet dat ze komen. Het feit dat je er bent is het signaal, niet het gesprek.",
    vermijd: "Boos of teleurgesteld reageren als ze niet komen — dat bevestigt hun angst voor jouw verwachtingen.",
    leerdoel: "Je leert beschikbaarheid te bieden zonder voorwaarden.",
    bron: "Steinberg (2001) - We Know Some Things: Parent–Adolescent Relationships",
  },
  {
    id: "aanw_1316_02",
    title: "Ritje naar hun activiteit",
    skill: "Aanwezigheid",
    description: "Bied aan je tiener ergens naartoe te rijden. Gebruik de autorit als praatmoment — of geniet van gedeelde stilte.",
    duration: "10 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "De auto is voor tieners een van de weinige plekken waar ze samen met hun vader zijn zonder dat het 'een gesprek' is. Side-by-side verlaagt de druk.",
    skillTip: "Zet de radio op hun zender. Of vraag: 'Mag ik jouw playlist horen?' Het is een klein gebaar met grote impact.",
    vermijd: "De autorit gebruiken om te preken over cijfers of gedrag — dat maakt het een val.",
    leerdoel: "Je leert autorijden te gebruiken als ongedwongen verbindingsmoment.",
    bron: "Kindlon & Thompson (2000) - Raising Cain",
  },
  {
    id: "aanw_1316_03",
    title: "Hun sociale media begrijpen",
    skill: "Aanwezigheid",
    description: "Vraag je tiener om je hun favoriete social media platform te laten zien en uit te leggen. Luister zonder oordeel.",
    duration: "10 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "De digitale wereld van tieners IS hun sociale wereld. Door interesse te tonen zonder te veroordelen, houd je de communicatielijn open.",
    skillTip: "Stel vragen als: 'Wat vind je leuk aan deze app?' en 'Zijn er dingen die je irriteren online?'",
    vermijd: "Meteen waarschuwen voor gevaren — dat doe je een ander moment. Nu gaat het om luisteren.",
    leerdoel: "Je leert de digitale leefwereld van je tiener te betreden als geïnteresseerde vader.",
    bron: "boyd (2014) - It's Complicated: The Social Lives of Networked Teens",
  },
  {
    id: "aanw_1316_04",
    title: "Late-night beschikbaarheid",
    skill: "Aanwezigheid",
    description: "Zeg tegen je tiener: 'Als je 's avonds laat ergens mee zit, mag je altijd bij me komen. Geen oordeel, geen straf.'",
    duration: "2 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "'s Avonds laat zijn tieners het kwetsbaarst. Weten dat papa een veilige haven is — ook om 23:00 — kan het verschil maken in een crisis.",
    skillTip: "Houd je aan deze belofte, zelfs als het ongemakkelijk is. Eén keer oordelen en de deur gaat dicht.",
    vermijd: "De volgende dag alsnog straffen of moraliseren over wat ze verteld hebben.",
    leerdoel: "Je leert onvoorwaardelijke beschikbaarheid te bieden aan je tiener.",
    bron: "Ginott (1969) - Between Parent and Teenager",
  },
  {
    id: "aanw_1316_05",
    title: "Gedeelde ervaring zoeken",
    skill: "Aanwezigheid",
    description: "Zoek iets dat jullie allebei leuk vinden en doe het samen: een serie kijken, koken, naar een wedstrijd gaan.",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Tieners verzetten zich tegen 'quality time' dat als opgelegd voelt. Gedeelde interesses voelen natuurlijk en niet geforceerd.",
    skillTip: "Laat je tiener het voorstel doen: 'Is er iets dat je samen wilt doen dit weekend?'",
    vermijd: "Activiteiten uit hun kindertijd voorstellen — ze willen als bijna-volwassenen behandeld worden.",
    leerdoel: "Je leert verbinding te zoeken op een manier die bij de leeftijd past.",
    bron: "Steinberg (2001) - We Know Some Things: Parent–Adolescent Relationships",
  },
  {
    id: "aanw_1316_06",
    title: "Vraag om hun mening",
    skill: "Aanwezigheid",
    description: "Vraag je tiener advies over iets uit jouw leven: een werkdilemma, een aankoop, een plan. Neem hun antwoord serieus.",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Door advies te vragen keer je de relatie even om. Je tiener voelt zich serieus genomen en gezien als gelijkwaardiger persoon.",
    skillTip: "Kies iets waarvan je echt hun input kunt gebruiken — ze prikken door nep-consultering heen.",
    vermijd: "Hun advies negeren of belachelijk maken — dat bevestigt hun gevoel 'toch niet serieus genomen te worden'.",
    leerdoel: "Je leert je tiener als gesprekspartner te behandelen.",
    bron: "Deci & Ryan (2000) - Self-Determination Theory (autonomie-ondersteuning)",
  },
  {
    id: "aanw_1316_07",
    title: "Wachten op het juiste moment",
    skill: "Aanwezigheid",
    description: "Als je merkt dat je tiener ergens mee zit, dring niet aan. Zeg: 'Ik merk dat er iets is. Ik ben er als je wilt praten.' Wacht.",
    duration: "2 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Tieners openen zich op hun eigen tempo. Druk om te praten sluit de deur, geduld opent hem.",
    skillTip: "Het 'juiste moment' komt vaak onverwacht — bij het afruimen, in de auto, laat op de avond. Wees dan klaar.",
    vermijd: "Zeggen 'je kunt me alles vertellen' en dan schrikken of boos worden bij wat ze zeggen.",
    leerdoel: "Je leert geduldig te wachten tot je tiener zelf de deur opent.",
    bron: "Faber & Mazlish (2012) - How to Talk So Teens Will Listen",
  },
  {
    id: "aanw_1316_08",
    title: "Deel je eigen verhaal",
    skill: "Aanwezigheid",
    description: "Vertel je tiener een eerlijk verhaal uit je eigen tienertijd. Een blunder, een les, een moeilijk moment. Wees kwetsbaar.",
    duration: "10 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kwetsbaarheid van een vader doorbreekt het beeld van de 'onaantastbare ouder' en maakt diepere verbinding mogelijk.",
    skillTip: "Kies een verhaal dat relevant is voor iets wat je kind meemaakt — maar maak het niet een les. Vertel, preek niet.",
    vermijd: "Zeggen 'en wij hadden het veel moeilijker' — dat minimaliseert hun ervaring.",
    leerdoel: "Je leert kwetsbaarheid te gebruiken als verbindingsmiddel.",
    bron: "Brown (2012) - Daring Greatly",
  },
  {
    id: "aanw_1316_09",
    title: "Fysieke aanwezigheid respecteren",
    skill: "Aanwezigheid",
    description: "Klop altijd op de deur van je tiener voor je binnenkomt. Wacht op antwoord. Respecteer hun ruimte.",
    duration: "2 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Privacy respecteren communiceert vertrouwen. Tieners die zich gerespecteerd voelen in hun privacy zijn paradoxaal genoeg meer open naar hun ouders.",
    skillTip: "Zeg het expliciet: 'Jouw kamer is jouw ruimte. Ik klop altijd.' En houd je eraan.",
    vermijd: "Stiekem controleren of de deur open laten staan als 'huisregel' — dat zegt: ik vertrouw je niet.",
    leerdoel: "Je leert dat privacy respecteren een vorm van aanwezigheid is.",
    bron: "Smetana (2011) - Adolescents, Families, and Social Development",
  },
  {
    id: "aanw_1316_10",
    title: "Aanwezig blijven bij conflict",
    skill: "Aanwezigheid",
    description: "Na een ruzie met je tiener: geef ruimte, maar zeg voor je weggaat: 'Ik ben boos, maar ik hou van je. We praten hier later over.'",
    duration: "2 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Tieners testen of de relatie conflictbestendig is. Een vader die na ruzie bevestigt 'ik blijf er voor je' bouwt diepe veiligheid.",
    skillTip: "Kom altijd terug op de ruzie — laat het niet onuitgesproken. Maar kies een rustiger moment.",
    vermijd: "Dagenlang niet praten als straf — de stille behandeling is destructiever dan schreeuwen.",
    leerdoel: "Je leert dat aanwezigheid ook betekent: er zijn na het conflict.",
    bron: "Gottman (1997) - Raising An Emotionally Intelligent Child (repair attempts)",
  },
];