import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_22: InteractiveTask[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // LEEFTIJD 0-2 — Sensory bonding, non-verbale communicatie, ritme & routine
  // ═══════════════════════════════════════════════════════════════════════

  {
    id: 'aanw_02_150',
    skill: 'Aanwezigheid',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Ademhaling synchroniseren',
    description: 'Stem je ademhaling af op die van je baby tijdens een rustig moment.',
    instructions: [
      'Houd je baby tegen je borst in een rustige ruimte zonder afleiding.',
      'Voel het ademritme van je baby en probeer je eigen ademhaling daarop af te stemmen.',
      'Blijf minstens twee minuten in dit ritme ademen zonder te praten.',
      'Merk op hoe je baby reageert – ontspant het lichaampje, verandert de ademhaling?',
    ],
    reflection: 'Door je ademhaling te synchroniseren creëer je een fysieke verbinding die woorden niet kunnen bieden. Dit is aanwezigheid in de puurste vorm.',
    scienceNote: 'Fysiologische synchronisatie tussen ouder en kind versterkt de hechtingsband en reguleert het stresssysteem van de baby (Feldman, 2012).',
    durationMin: 5,
  },
  {
    id: 'emco_02_151',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Emotiespiegel met gezicht',
    description: 'Spiegel de gezichtsuitdrukkingen van je baby om emotionele afstemming te oefenen.',
    instructions: [
      'Ga op ooghoogte van je baby zitten als die wakker en alert is.',
      'Wacht tot je baby een gezichtsuitdrukking maakt (lach, fronsje, verbazing).',
      'Spiegel die uitdrukking met je eigen gezicht en voeg er een zacht geluid aan toe.',
      'Herhaal dit spiegelspel vijf keer en let op hoe je baby reageert op de herkenning.',
    ],
    reflection: 'Spiegelen leert je baby dat emoties gezien en begrepen worden – de basis van emotioneel vertrouwen.',
    scienceNote: 'Affect mirroring door de ouder is essentieel voor de ontwikkeling van emotieregulatie bij het jonge kind (Gergely & Watson, 1996).',
    durationMin: 5,
  },
  {
    id: 'zelr_02_152',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Rustsignalen herkennen',
    description: 'Leer de subtiele signalen van je baby herkennen die aangeven dat het genoeg prikkels heeft gehad.',
    instructions: [
      'Observeer je baby tien minuten lang tijdens een speelmoment en let op wegkijken, geeuwen of friemelen.',
      'Schrijf op welke signalen je baby geeft als de prikkels te veel worden.',
      'Zodra je een rustsignaal opmerkt, verminder dan direct de prikkels (zachter praten, minder bewegen).',
      'Reflecteer vanavond: welke signalen herken je nu die je eerder miste?',
    ],
    reflection: 'Jouw zelfregulatie begint bij het lezen van je baby. Hoe beter je afstemt, hoe minder je baby hoeft te huilen om gehoord te worden.',
    scienceNote: 'Sensitief reageren op stress-signalen van de baby bevordert veilige hechting en betere zelfregulatie op latere leeftijd (Ainsworth et al., 1978).',
    durationMin: 15,
  },
  {
    id: 'gren_02_153',
    skill: 'Grenzen',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Liefdevolle routinegrens',
    description: 'Oefen met het vasthouden van een vaste bedtijdroutine, ook als je baby protesteert.',
    instructions: [
      'Kies een vaste volgorde voor het slapengaan (bijv. bad, boekje, liedje, bedje).',
      'Voer de routine vanavond stap voor stap uit, op dezelfde tijd als gisteren.',
      'Als je baby protesteert, blijf dan rustig en troostend maar wijk niet af van de volgorde.',
      'Na het in bed leggen: merk op hoe het voelde om de grens vast te houden ondanks het huilen.',
    ],
    reflection: 'Grenzen stellen bij een baby voelt soms wreed, maar voorspelbaarheid geeft je kind juist veiligheid.',
    scienceNote: 'Consistente routines verlagen het cortisolniveau bij peuters en bevorderen betere slaappatronen (Mindell et al., 2015).',
    durationMin: 15,
  },
  {
    id: 'auto_02_154',
    skill: 'Autonomie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Vrij ontdekken zonder ingrijpen',
    description: 'Geef je peuter ruimte om zelfstandig een speelomgeving te verkennen zonder dat jij stuurt.',
    instructions: [
      'Maak een veilige speelruimte klaar met drie tot vier verschillende materialen (blokken, doek, bal, beker).',
      'Zet je baby of peuter neer en ga op de grond zitten, maar pak zelf niets op.',
      'Wacht geduldig. Volg met je ogen wat je kind doet zonder iets te benoemen of voor te doen.',
      'Grijp alleen in bij gevaar. Merk op hoe je kind zelf keuzes maakt en problemen oplost.',
    ],
    reflection: 'De neiging om te helpen of te sturen is sterk. Maar door te wachten geef je je kind de boodschap: ik vertrouw op jou.',
    scienceNote: 'Vrij spel zonder volwassen sturing stimuleert probleemoplossend vermogen en intrinsieke motivatie (Pikler, 1969; Deci & Ryan, 2000).',
    durationMin: 10,
  },
  {
    id: 'hers_02_155',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Herstel na een geïrriteerd moment',
    description: 'Herstel de verbinding nadat je geïrriteerd reageerde op het huilen van je baby.',
    instructions: [
      'Denk terug aan een moment vandaag waarop je geïrriteerd raakte door het huilen of zeuren.',
      'Neem je baby op en houd het dicht tegen je aan met een zachte stem.',
      'Zeg hardop (ook al begrijpt je baby de woorden niet): "Het spijt me, papa was even moe. Ik ben er voor je."',
      'Geef extra lichamelijk contact de komende tien minuten: aaien, wiegen, samen liggen.',
    ],
    reflection: 'Je baby begrijpt je woorden nog niet, maar voelt je toon en aanraking. Herstel na een breuk is belangrijker dan perfectie.',
    scienceNote: 'Repair-interacties na momenten van mismatch versterken de hechtingsrelatie meer dan continue afstemming (Tronick, 2007).',
    durationMin: 10,
  },
  {
    id: 'verb_02_156',
    skill: 'Verbinding',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Ritmisch contact door zingen',
    description: 'Gebruik een eenvoudig liedje als dagelijks verbindingsritueel met je baby.',
    instructions: [
      'Kies een kort, eenvoudig liedje dat je elke dag gaat zingen (bijv. bij het verschonen of aankleden).',
      'Zing het liedje vandaag drie keer op vaste momenten met oogcontact.',
      'Let op of je baby na een paar keer het liedje begint te herkennen (stilte, lach, beweging).',
      'Maak er een vast ritueel van – altijd hetzelfde liedje op hetzelfde moment.',
    ],
    reflection: 'Ritme en herhaling zijn de taal van een baby. Een liedje wordt een anker van voorspelbaarheid en veiligheid.',
    scienceNote: 'Ritmische ouder-kindinteracties zoals zingen bevorderen neurale synchronisatie en sociale bonding (Cirelli et al., 2014).',
    durationMin: 5,
  },
  {
    id: 'refl_02_157',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Dagboek van non-verbale signalen',
    description: 'Houd een week lang bij welke non-verbale signalen je baby geeft en wat ze betekenen.',
    instructions: [
      'Pak een notitieboekje of je telefoon en maak vandaag drie aantekeningen van non-verbale signalen van je baby.',
      'Noteer per signaal: wat deed je baby, wat was de context, hoe reageerde jij, wat had je baby nodig?',
      'Vergelijk je aantekeningen aan het eind van de dag – zie je patronen?',
      'Deel je observaties met je partner of een vertrouwd persoon en bespreek wat je hebt geleerd.',
    ],
    reflection: 'Reflectie op non-verbale communicatie maakt je een betere lezer van je kind, lang voordat woorden komen.',
    scienceNote: 'Reflectief functioneren van ouders – het vermogen om mentale toestanden achter gedrag te zien – is een sterke voorspeller van veilige hechting (Slade, 2005).',
    durationMin: 15,
  },
  {
    id: 'emco_02_158',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Troosten zonder afleiden',
    description: 'Oefen met het troosten van je huilende baby door er volledig bij te zijn, zonder af te leiden met speelgoed of geluid.',
    instructions: [
      'Wanneer je baby huilt, pak het op zonder direct een speen, speeltje of geluid aan te bieden.',
      'Houd je baby stevig vast, wieg zachtjes en zeg alleen: "Ik ben hier, ik voel dat het moeilijk is."',
      'Verdraag de onrust – het doel is niet dat het huilen stopt maar dat je baby voelt dat je er bent.',
      'Merk op hoelang het duurt voordat je baby tot rust komt met alleen jouw aanwezigheid.',
    ],
    reflection: 'Afleiden is makkelijker dan verdragen. Maar door het ongemak samen uit te houden leer je je baby dat emoties veilig zijn.',
    scienceNote: 'Co-regulatie zonder afleidingsstrategieën bevordert de ontwikkeling van interne emotieregulatievaardigheden (Sroufe, 1996).',
    durationMin: 10,
  },
  {
    id: 'refl_02_159',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Eigen hechtingsgeschiedenis verkennen',
    description: 'Onderzoek hoe jouw eigen ervaring als kind je huidige ouderschap beïnvloedt.',
    instructions: [
      'Neem tien minuten voor jezelf en schrijf op: hoe werd ik getroost als baby/peuter? Wat vertelden mijn ouders hierover?',
      'Schrijf daarna op: welk patroon herken ik bij mezelf als mijn baby huilt? (wegduwen, overnemen, bevriezen, troosten)',
      'Benoem een verschil dat je wilt maken ten opzichte van hoe jij bent opgegroeid.',
      'Formuleer een voornemen in één zin: "Als mijn baby huilt, wil ik..."',
    ],
    reflection: 'Je eigen hechtingsgeschiedenis hoeft niet je lot te zijn. Bewustwording is de eerste stap naar een nieuwe generatie.',
    scienceNote: 'Ouders die hun eigen hechtingsgeschiedenis coherent kunnen vertellen, hebben vaker veilig gehechte kinderen (Main & Goldwyn, 1998; van IJzendoorn, 1995).',
    durationMin: 15,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // LEEFTIJD 3-5 — Verbeeldingsspel, emoties benoemen via verhalen, eerste zelfstandigheid
  // ═══════════════════════════════════════════════════════════════════════

  {
    id: 'verb_35_160',
    skill: 'Verbinding',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Verhaaltje met emotieknuffel',
    description: 'Verzin samen een kort verhaal waarin een knuffel dezelfde emotie meemaakt als je kind vandaag voelde.',
    instructions: [
      'Vraag je kind: "Hoe voelde je je vandaag?" en kies samen een knuffel die dat ook voelde.',
      'Begin een verhaal: "Beer was vandaag ook een beetje [emotie], want..."',
      'Laat je kind het verhaal aanvullen – wat overkwam de knuffel, en hoe ging het verder?',
      'Eindig het verhaal samen met een oplossing of troostend moment voor de knuffel.',
    ],
    reflection: 'Via een knuffel als tussenpersoon durft je kind emoties te uiten die het direct misschien nog niet kan benoemen.',
    scienceNote: 'Narratief spel met emotionele thema\'s bevordert emotioneel begrip en empathie bij kleuters (Nicolopoulou & Richner, 2007).',
    durationMin: 10,
  },
  {
    id: 'aanw_35_161',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Vijf minuten onverdeelde aandacht',
    description: 'Geef je kind vijf minuten volledige aandacht zonder telefoon, zonder multi-tasken.',
    instructions: [
      'Zet je telefoon in een andere kamer en ga op de grond bij je kind zitten.',
      'Zeg: "Ik heb vijf minuten helemaal voor jou. Wat wil je doen?"',
      'Volg het initiatief van je kind volledig – jij bepaalt niets.',
      'Als de vijf minuten om zijn, benoem wat je leuk vond: "Ik vond het fijn om samen... te doen."',
    ],
    reflection: 'Vijf minuten echte aandacht is meer waard dan een uur half aanwezigheid. Je kind voelt het verschil.',
    scienceNote: 'Child-directed interaction met volledige ouderlijke aandacht versterkt de ouder-kindrelatie en vermindert gedragsproblemen (Eyberg et al., 2001).',
    durationMin: 5,
  },
  {
    id: 'emco_35_162',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Emotiekaarten maken',
    description: 'Maak samen eenvoudige kaarten met gezichten die verschillende emoties tonen.',
    instructions: [
      'Teken samen op vijf kaartjes elk een gezicht: blij, boos, bang, verdrietig, verrast.',
      'Laat je kind de gezichten inkleuren en benoem elke emotie duidelijk.',
      'Speel een spelletje: "Hoe voelde jij je toen...?" en laat je kind een kaartje kiezen.',
      'Vraag door: "Wat maakte je [emotie]? Waar voelde je dat in je lijf?"',
    ],
    reflection: 'Emoties een naam en een gezicht geven maakt ze minder overweldigend en beter hanteerbaar.',
    scienceNote: 'Het labelen van emoties (affect labeling) vermindert de amygdala-activatie en helpt kinderen emoties te reguleren (Lieberman et al., 2007).',
    durationMin: 15,
  },
  {
    id: 'zelr_35_163',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'De schildpad-techniek oefenen',
    description: 'Leer je kind de schildpadtechniek: stoppen, in je schulp kruipen, rustig worden, en dan pas reageren.',
    instructions: [
      'Vertel het verhaal van de kleine schildpad die leerde om even in zijn schulp te kruipen als hij boos werd.',
      'Oefen samen: armen om je heen slaan, hoofd naar beneden, drie keer diep ademen.',
      'Speel drie situaties na (bijv. speelgoed wordt afgepakt) en oefen telkens de schildpadreactie.',
      'Spreek een codewoord af: als jij "schildpad!" zegt, weet je kind wat het kan doen.',
    ],
    reflection: 'Zelfregulatie is geen aangeboren talent maar een vaardigheid die je oefent – net als fietsen.',
    scienceNote: 'De schildpadtechniek is effectief bewezen bij impulscontrole bij kleuters en verlaagt agressief gedrag (Robin et al., 1976; Webster-Stratton, 2011).',
    durationMin: 10,
  },
  {
    id: 'gren_35_164',
    skill: 'Grenzen',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Grens met empathie stellen',
    description: 'Oefen met het stellen van een grens terwijl je de emotie van je kind erkent.',
    instructions: [
      'Wacht op een moment dat je kind iets wil dat niet mag (bijv. snoep voor het eten).',
      'Kniel op ooghoogte en zeg: "Ik snap dat je dat heel graag wilt. Dat is een vervelend gevoel."',
      'Stel de grens kort en duidelijk: "En het antwoord is nee, want we gaan zo eten."',
      'Als je kind boos reageert: blijf kalm, herhaal je begrip, en houd de grens vast zonder uitleg toe te voegen.',
    ],
    reflection: 'Empathie en grenzen sluiten elkaar niet uit. Je kind mag boos zijn op de grens – jouw taak is standvastig én liefdevol te blijven.',
    scienceNote: 'Grenzen stellen met warmte (authoritative parenting) leidt tot betere emotieregulatie en minder externaliserende problemen (Baumrind, 1991).',
    durationMin: 5,
  },
  {
    id: 'auto_35_165',
    skill: 'Autonomie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Zelf aankleden met keuzehulp',
    description: 'Laat je kind zelf kleren kiezen uit twee opties die jij klaarlegt.',
    instructions: [
      'Leg de avond ervoor twee complete outfits klaar die allebei geschikt zijn voor het weer.',
      'Zeg \'s ochtends: "Welke kleren wil jij vandaag aan? De blauwe of de rode?"',
      'Laat je kind zelf aankleden, ook als het trui achterstevoren gaat – help alleen als gevraagd.',
      'Geef een specifiek compliment: "Jij hebt helemaal zelf gekozen en aangekleed, knap!"',
    ],
    reflection: 'Autonomie geven in kleine dingen bouwt groot zelfvertrouwen. De trui achterstevoren is niet het punt – het zelf doen wel.',
    scienceNote: 'Autonomie-ondersteuning in dagelijkse routines bevordert het gevoel van competentie en zelfstandigheid bij peuters (Erikson, 1963; Deci & Ryan, 2000).',
    durationMin: 10,
  },
  {
    id: 'hers_35_166',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Sorry zeggen als vader',
    description: 'Bied oprecht je excuses aan na een moment waarop je te streng of ongeduldig was.',
    instructions: [
      'Denk terug aan een recent moment waarop je te hard reageerde op je kind.',
      'Ga op ooghoogte zitten en zeg: "Weet je nog toen papa [situatie]? Dat was niet lief van papa."',
      'Leg uit wat je anders had willen doen: "Papa had beter [alternatief] kunnen doen."',
      'Vraag: "Hoe voelde jij je toen?" en luister zonder jezelf te verdedigen.',
    ],
    reflection: 'Sorry zeggen als volwassene tegen een klein kind is niet zwak – het is een van de krachtigste lessen die je kunt geven.',
    scienceNote: 'Ouderlijke reparatie na conflict modelleert emotionele verantwoordelijkheid en versterkt de hechtingsrelatie (Gottman & DeClaire, 1997).',
    durationMin: 10,
  },
  {
    id: 'verb_35_167',
    skill: 'Verbinding',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Rollenspel met poppen',
    description: 'Speel een dagelijks sociaal scenario na met poppen om je kind sociale vaardigheden te leren.',
    instructions: [
      'Kies een situatie die je kind lastig vindt (bijv. delen, wachten op beurt, afscheid nemen).',
      'Pak twee poppen of knuffels en speel het scenario na – jij speelt de ene, je kind de andere.',
      'Laat het eerst "fout" gaan en vraag: "Wat zou [pop] beter kunnen doen?"',
      'Speel het scenario opnieuw met de betere aanpak en geef de pop een compliment.',
    ],
    reflection: 'Via spel oefent je kind veilig met moeilijke situaties. Fouten maken mag – het is maar een pop.',
    scienceNote: 'Sociodramatisch spel bevordert sociaal begrip, perspectief nemen en emotieregulatie bij kleuters (Vygotsky, 1978; Singer & Singer, 1990).',
    durationMin: 15,
  },
  {
    id: 'refl_35_168',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Drie-momentenreflectie',
    description: 'Reflecteer op drie momenten van de dag: een mooi moment, een lastig moment, en een leermoment.',
    instructions: [
      'Doe dit vanavond na het slapengaan van je kind. Pak pen en papier of je telefoon.',
      'Schrijf op: het mooiste moment van vandaag met je kind – wat maakte het bijzonder?',
      'Schrijf op: het lastigste moment – wat triggerde jou, en wat had je kind nodig?',
      'Schrijf op: wat heb je vandaag geleerd over je kind of over jezelf als vader?',
    ],
    reflection: 'Dagelijkse reflectie maakt het verschil tussen jaren ouderervaring en één jaar ervaring dat zich herhaalt.',
    scienceNote: 'Ouderlijke zelf-reflectie is geassocieerd met hogere opvoedkwaliteit en betere afstemming op het kind (Slade et al., 2005).',
    durationMin: 10,
  },
  {
    id: 'zelr_35_169',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Emotie-thermometer invoeren',
    description: 'Maak samen een emotie-thermometer en gebruik die om de intensiteit van gevoelens te bespreken.',
    instructions: [
      'Teken samen een grote thermometer op papier met niveaus 1 (rustig) tot 5 (ontploffen).',
      'Bespreek bij elk niveau: hoe voelt dat in je lijf? Wat doe je dan? Geef voorbeelden.',
      'Hang de thermometer op een zichtbare plek (koelkast, kinderkamer).',
      'Gebruik de thermometer vandaag minstens twee keer: "Waar sta jij nu op de thermometer?" – en benoem ook je eigen niveau.',
    ],
    reflection: 'Een gedeelde taal voor emotie-intensiteit helpt jullie allebei om eerder in te grijpen voordat het escaleert.',
    scienceNote: 'Visuele hulpmiddelen voor emotieherkenning vergroten het emotioneel bewustzijn en de regulatievaardigheid bij jonge kinderen (Greenberg et al., 1995).',
    durationMin: 15,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // LEEFTIJD 6-9 — Schooltransities, vriendschapscoaching, growth mindset
  // ═══════════════════════════════════════════════════════════════════════

  {
    id: 'aanw_69_170',
    skill: 'Aanwezigheid',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Schooldag-check-in',
    description: 'Voer een dagelijkse check-in in na school met één simpele vraag die verder gaat dan "Hoe was het?"',
    instructions: [
      'Bedenk een specifieke vraag voor vandaag, bijv.: "Wat was het grappigste dat er vandaag gebeurde?"',
      'Stel de vraag tijdens een rustig moment (niet direct bij het ophalen maar bijv. tijdens een snack).',
      'Luister zonder te onderbreken of advies te geven – stel alleen doorvragen.',
      'Deel ook iets van je eigen dag: "Wil je weten wat mij vandaag overkwam?"',
    ],
    reflection: 'De juiste vraag opent een deur. "Hoe was het op school?" sluit die deur vaak direct weer.',
    scienceNote: 'Open vragen die specifiek en positief zijn geformuleerd lokken meer uitgebreide verhalen uit bij schoolkinderen (Fivush et al., 2006).',
    durationMin: 10,
  },
  {
    id: 'emco_69_171',
    skill: 'Emotiecoaching',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Vriendschapsverdriet begeleiden',
    description: 'Help je kind omgaan met uitsluiting of een ruzie met een vriendje op school.',
    instructions: [
      'Als je kind vertelt over een sociaal probleem, reageer eerst met erkenning: "Dat klinkt echt vervelend."',
      'Vraag: "Hoe voelde dat van binnen?" en help je kind het gevoel precies te benoemen (teleurstelling, boosheid, schaamte).',
      'Vraag pas daarna: "Wat denk je dat [vriendje] voelde?" om perspectief te verbreden.',
      'Sluit af met: "Wat zou je morgen willen proberen?" zonder zelf een oplossing te geven.',
    ],
    reflection: 'De verleiding is groot om het op te lossen of te bagatelliseren. Maar eerst voelen, dan denken – die volgorde is cruciaal.',
    scienceNote: 'Emotion coaching bij sociale pijn helpt kinderen betere copingstrategieën te ontwikkelen en versterkt de sociale competentie (Gottman et al., 1996).',
    durationMin: 10,
  },
  {
    id: 'zelr_69_172',
    skill: 'Zelfregulatie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Frustratie bij huiswerk verdragen',
    description: 'Begeleid je kind om bij huiswerkfrustratie even te pauzeren in plaats van op te geven of te ontploffen.',
    instructions: [
      'Spreek vooraf af: als het huiswerk frustrerend wordt, zeg je samen "pauzeknop".',
      'Bij frustratie: stop het huiswerk, doe samen iets fysieks (tien jumping jacks, kort naar buiten lopen).',
      'Kom terug en laat je kind zelf benoemen wat er lastig was: "Welk stukje zat je dwars?"',
      'Help alleen met het concrete struikelblok en laat de rest bij je kind.',
    ],
    reflection: 'Frustratie verdragen is een spier die je traint. De pauzeknop is geen opgeven – het is slim omgaan met je energie.',
    scienceNote: 'Het leren verdragen van frustratie (distress tolerance) is een kerncomponent van executief functioneren dat sterk samenhangt met schoolsucces (Diamond, 2013).',
    durationMin: 15,
  },
  {
    id: 'gren_69_173',
    skill: 'Grenzen',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Schermtijd-afspraak samen maken',
    description: 'Maak samen een heldere schermtijdafspraak waar je kind invloed op heeft.',
    instructions: [
      'Ga samen aan tafel zitten en zeg: "We gaan samen een schermtijdafspraak maken."',
      'Stel je kader: "Op schooldagen maximaal [X] minuten, in het weekend [Y] minuten."',
      'Vraag je kind: "Wanneer wil jij het liefst je schermtijd gebruiken?" en geef ruimte voor inbreng.',
      'Schrijf de afspraak samen op, laat je kind tekenen, en hang het op een zichtbare plek.',
    ],
    reflection: 'Een afspraak waar je kind invloed op had, wordt beter nageleefd dan een opgelegde regel.',
    scienceNote: 'Participatief grenzen stellen verhoogt de intrinsieke motivatie om regels na te leven bij schoolgaande kinderen (Grolnick & Pomerantz, 2009).',
    durationMin: 10,
  },
  {
    id: 'auto_69_174',
    skill: 'Autonomie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Growth mindset compliment geven',
    description: 'Vervang een prestatie-compliment door een proces-compliment om een growth mindset te bevorderen.',
    instructions: [
      'Let vandaag op momenten waarop je normaal zou zeggen: "Wat ben je slim!" of "Goed gedaan!"',
      'Vervang het door een procesopmerking: "Ik zag dat je bleef proberen, ook toen het moeilijk was."',
      'Doe dit minstens drie keer vandaag bij verschillende situaties.',
      'Merk op hoe je kind reageert – is er een verschil met hoe het op "Knap!" reageert?',
    ],
    reflection: 'Slim zijn is een eigenschap waar je kind niets aan kan doen. Doorzetten is een keuze – en die verdient het echte compliment.',
    scienceNote: 'Proces-gerichte complimenten bevorderen een growth mindset en grotere veerkracht bij tegenslag (Dweck, 2006; Mueller & Dweck, 1998).',
    durationMin: 5,
  },
  {
    id: 'hers_69_175',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Samen een ruzie evalueren',
    description: 'Evalueer samen een eerdere ruzie met je kind om er allebei van te leren.',
    instructions: [
      'Kies een rustig moment (niet direct na het conflict) en zeg: "Ik wil even terugkomen op wat er eerder gebeurde."',
      'Vertel eerst jouw kant: "Ik werd boos omdat... en toen deed ik... Dat was niet goed van mij."',
      'Vraag: "Hoe was het voor jou? Wat voelde jij?" – luister zonder te corrigeren.',
      'Maak samen een afspraak: "Volgende keer proberen we allebei om..."',
    ],
    reflection: 'Een ruzie evalueren is geen zwakte tonen. Het is je kind leren dat relaties sterker worden van eerlijke gesprekken.',
    scienceNote: 'Gezamenlijke evaluatie van conflicten leert kinderen meta-cognitieve vaardigheden en versterkt de relatie na een breuk (Siegel & Bryson, 2011).',
    durationMin: 15,
  },
  {
    id: 'verb_69_176',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Wekelijks vader-kind uitje',
    description: 'Plan een kort wekelijks uitje dat alleen van jullie tweeën is.',
    instructions: [
      'Vraag je kind: "Als wij samen iets zouden doen dit weekend, alleen wij tweeën, wat zou je willen?"',
      'Kies samen iets haalbaars (wandeling, ijsje halen, naar de speeltuin, samen koken).',
      'Voer het plan uit zonder telefoon en zonder andere gezinsleden.',
      'Benoem aan het eind: "Dit was ons momentje. Volgende week weer?"',
    ],
    reflection: 'Eén-op-één-tijd is de valuta van verbinding. Het hoeft niet bijzonder te zijn, als het maar regelmatig is.',
    scienceNote: 'Regelmatige exclusieve ouder-kind-activiteiten zijn geassocieerd met hogere relatiekwaliteit en minder gedragsproblemen (Eisenberg et al., 2005).',
    durationMin: 10,
  },
  {
    id: 'refl_69_177',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Jouw schoolherinneringen onderzoeken',
    description: 'Onderzoek hoe jouw eigen schoolervaringen je reactie op de schoolprestaties van je kind beïnvloeden.',
    instructions: [
      'Schrijf drie herinneringen op aan je eigen basisschooltijd: een positieve, een negatieve, en een over prestaties.',
      'Vraag jezelf af: welke boodschappen kreeg ik over leren? Over fouten maken? Over slim zijn?',
      'Schrijf op: herken ik deze boodschappen in hoe ik op de prestaties van mijn kind reageer?',
      'Formuleer één ding dat je bewust anders wilt doen dan je ouders deden rondom school.',
    ],
    reflection: 'We ouderen onbewust vanuit onze eigen schoolervaringen. Bewustwording doorbreekt de automatische piloot.',
    scienceNote: 'Intergenerationele overdracht van opvoedpatronen kan doorbroken worden door reflectieve verwerking van eigen jeugdervaringen (Fraiberg et al., 1975; Fonagy et al., 2002).',
    durationMin: 15,
  },
  {
    id: 'emco_69_178',
    skill: 'Emotiecoaching',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Faalangst bespreekbaar maken',
    description: 'Help je kind faalangst herkennen en er woorden aan geven.',
    instructions: [
      'Kies een rustig moment en vertel over iets waar jij als kind bang voor was om te falen.',
      'Vraag: "Ken jij dat gevoel ook? Dat je iets niet durft omdat je bang bent dat het mislukt?"',
      'Normaliseer: "Iedereen heeft dat soms. Het heet faalangst en het is heel normaal."',
      'Bedenk samen een mantra voor spannende momenten, bijv.: "Fouten maken hoort erbij, daar leer ik van."',
    ],
    reflection: 'Faalangst bloeit in stilte. Door het te benoemen en te normaliseren geef je je kind toestemming om imperfect te zijn.',
    scienceNote: 'Het bespreken en normaliseren van faalangst vermindert prestatieangst en vergroot de leermotivatie bij basisschoolkinderen (Seligman et al., 2007).',
    durationMin: 10,
  },
  {
    id: 'zelr_69_179',
    skill: 'Zelfregulatie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Boosheidsplan samen maken',
    description: 'Maak met je kind een persoonlijk plan voor wat het kan doen als het boos wordt.',
    instructions: [
      'Vraag: "Wat gebeurt er in je lichaam als je boos wordt?" (warm worden, vuisten ballen, hart bonkt).',
      'Brainstorm samen vijf dingen die helpen bij boosheid (ademhalen, naar buiten gaan, kussen slaan, tekenen, muziek).',
      'Laat je kind de top drie kiezen en teken of schrijf ze op een kaart.',
      'Oefen één strategie nu samen: bijv. drie keer diep inademen door de neus, uit door de mond.',
    ],
    reflection: 'Een boosheidsplan maak je als het rustig is. In het moment herinneren jullie elkaar eraan – zonder oordeel.',
    scienceNote: 'Vooraf geplande copingstrategieën (implementation intentions) zijn effectiever dan in-het-moment regulatie bij kinderen (Gollwitzer & Sheeran, 2006).',
    durationMin: 10,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // LEEFTIJD 10-12 — Pre-puberteit, digitale wereld, moreel redeneren
  // ═══════════════════════════════════════════════════════════════════════

  {
    id: 'aanw_1012_180',
    skill: 'Aanwezigheid',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Autorit-gesprekken',
    description: 'Gebruik autoritten als natuurlijk moment voor diepere gesprekken met je pre-puber.',
    instructions: [
      'Kies een autorit van minstens tien minuten en zet de radio zachter.',
      'Begin met een open, laagdrempelige vraag: "Wat houdt je de laatste tijd bezig?" of "Waar kijk je naar uit?"',
      'Reageer met interesse maar zonder te oordelen – schouderophalend "hmm" en "vertel" werken het best.',
      'Deel ook iets kwetsbaars van jezelf: "Ik maak me soms zorgen over..." – model openheid.',
    ],
    reflection: 'In de auto hoef je elkaar niet aan te kijken. Dat maakt het veiliger om dingen te zeggen die je face-to-face niet durft.',
    scienceNote: 'Side-by-side activiteiten zonder oogcontact verlagen de sociale druk en bevorderen open communicatie bij pre-adolescenten (Steinberg & Morris, 2001).',
    durationMin: 10,
  },
  {
    id: 'emco_1012_181',
    skill: 'Emotiecoaching',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Puberteit-emoties normaliseren',
    description: 'Bespreek met je kind dat wisselende emoties bij de puberteit horen en normaal zijn.',
    instructions: [
      'Kies een rustig moment en begin: "Ik merk dat je de laatste tijd soms ineens boos of verdrietig bent. Dat is heel normaal."',
      'Leg kort en eerlijk uit: "Je hersenen en je lichaam veranderen nu. Dat maakt emoties soms heftiger."',
      'Deel een eigen herinnering: "Toen ik zo oud was als jij, voelde ik..."',
      'Bied een open deur: "Je hoeft er niet over te praten, maar als je wilt, ben ik er altijd."',
    ],
    reflection: 'Kinderen in de pre-puberteit schrikken soms van hun eigen emoties. Normaliseren geeft rust.',
    scienceNote: 'Psycho-educatie over puberteitsontwikkeling vermindert angst en vergroot het welzijn bij pre-adolescenten (Petersen & Taylor, 1980; Siegel, 2013).',
    durationMin: 10,
  },
  {
    id: 'zelr_1012_182',
    skill: 'Zelfregulatie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Gedachten uitdagen oefenen',
    description: 'Leer je kind om negatieve automatische gedachten te herkennen en te bevragen.',
    instructions: [
      'Leg uit: "Soms vertelt ons hoofd ons dingen die niet helemaal kloppen. Dat noemen we gedachten-valkuilen."',
      'Geef voorbeelden: "Ik kan niks" (alles-of-niets), "Iedereen vindt me stom" (gedachten lezen).',
      'Vraag: "Ken jij zo\'n stemmetje? Wat zegt het soms tegen jou?"',
      'Oefen samen: "Is dat echt waar? Wat is het bewijs? Wat zou je tegen een vriend zeggen die dit denkt?"',
    ],
    reflection: 'Gedachten zijn geen feiten. Dit vroeg leren maakt je kind weerbaarder tegen zelfkritiek en piekeren.',
    scienceNote: 'Cognitieve herstructurering is effectief bij het voorkomen van depressieve symptomen bij kinderen van 10-12 jaar (Gillham et al., 2007; Seligman et al., 2009).',
    durationMin: 15,
  },
  {
    id: 'gren_1012_183',
    skill: 'Grenzen',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Online grenzen samen bepalen',
    description: 'Stel samen richtlijnen op voor online gedrag en sociale media.',
    instructions: [
      'Begin het gesprek zonder oordeel: "Ik wil het met je hebben over internet en social media. Niet om te verbieden, maar om samen afspraken te maken."',
      'Bespreek drie onderwerpen: wat deel je wel/niet online, hoeveel tijd per dag, en wat doe je bij nare berichten.',
      'Laat je kind meedenken over de regels en neem suggesties serieus.',
      'Schrijf samen de afspraken op en plan een evaluatiemoment over een maand.',
    ],
    reflection: 'De digitale wereld verbieden werkt niet. Samen navigeren en vertrouwen opbouwen is de enige duurzame strategie.',
    scienceNote: 'Actieve mediation (samen bespreken) is effectiever dan restrictieve mediation (verbieden) voor online veiligheid van kinderen (Livingstone & Helsper, 2008).',
    durationMin: 15,
  },
  {
    id: 'auto_1012_184',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Eigen planning maken',
    description: 'Laat je kind zelf een weekplanning maken voor huiswerk en vrije tijd.',
    instructions: [
      'Geef je kind een leeg weekschema (op papier of digitaal).',
      'Benoem de vaste punten: schooltijden, sportclub, etenstijd.',
      'Vraag: "Wanneer wil jij je huiswerk doen en wanneer is je vrije tijd? Plan het zelf in."',
      'Bekijk het plan samen, stel vragen bij onrealistische keuzes, maar verander niets zonder toestemming van je kind.',
    ],
    reflection: 'Een eigen planning leren maken is een van de belangrijkste vaardigheden voor de middelbare school – begin nu.',
    scienceNote: 'Zelfregulatie en planningsvaardigheid bij 10-12-jarigen voorspellen schoolsucces in de adolescentie sterker dan IQ (Moffitt et al., 2011).',
    durationMin: 10,
  },
  {
    id: 'hers_1012_185',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Herstellen na schending van vertrouwen',
    description: 'Herstel het vertrouwen nadat je kind iets stiekems deed of jij een belofte brak.',
    instructions: [
      'Benoem wat er is gebeurd zonder verwijten: "Er is iets gebeurd dat het vertrouwen tussen ons heeft beschadigd."',
      'Deel hoe je je voelt (teleurstelling, bezorgdheid) zonder te beschuldigen: "Ik voel me..."',
      'Vraag je kind om zijn/haar kant: "Help me begrijpen waarom je dit deed." Luister echt.',
      'Maak samen een afspraak over hoe jullie het vertrouwen stap voor stap weer opbouwen.',
    ],
    reflection: 'Vertrouwen is niet binair. Het kan beschadigen en herstellen – en het herstelproces maakt de band uiteindelijk sterker.',
    scienceNote: 'Vertrouwensherstel door open communicatie is cruciaal in de pre-adolescentie wanneer kinderen meer geheimen gaan hebben (Kerr & Stattin, 2000).',
    durationMin: 15,
  },
  {
    id: 'verb_1012_186',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Interesse tonen in hun wereld',
    description: 'Duik oprecht in een hobby of interesse van je kind, ook als het je niet aanspreekt.',
    instructions: [
      'Vraag je kind: "Kun je me uitleggen wat je zo leuk vindt aan [game/serie/hobby]?"',
      'Luister met oprechte nieuwsgierigheid – stel minstens vijf doorvragen.',
      'Probeer het zelf: speel een potje mee, kijk een aflevering samen, of lees erover.',
      'Benoem wat je er interessant aan vindt – zoek een echt compliment, geen nep-enthousiasme.',
    ],
    reflection: 'Je hoeft hun hobby niet leuk te vinden. Maar je interesse in hun wereld is een brug naar hun hart.',
    scienceNote: 'Ouderlijke betrokkenheid bij de interesses van het kind is een beschermende factor tegen emotionele afstandelijkheid in de pre-puberteit (Collins & Steinberg, 2006).',
    durationMin: 15,
  },
  {
    id: 'refl_1012_187',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Moreel dilemma bespreken',
    description: 'Bespreek een moreel dilemma met je kind om het ethisch redeneren te ontwikkelen.',
    instructions: [
      'Kies een dilemma dat past bij de leefwereld van je kind, bijv.: "Je beste vriend spiekt bij een toets. Zeg je er iets van?"',
      'Vraag: "Wat zou jij doen?" en laat je kind uitleggen waarom.',
      'Stel een tegenvraag: "En wat als het andersom was?" of "Wat als iedereen dat deed?"',
      'Deel jouw perspectief pas als laatste en benadruk: "Er is niet één goed antwoord, maar erover nadenken maakt je wijzer."',
    ],
    reflection: 'Moreel redeneren leer je niet door regels op te leggen, maar door samen te denken over lastige keuzes.',
    scienceNote: 'Kohlbergs theorie van morele ontwikkeling toont dat het bespreken van morele dilemma\'s de overgang naar hogere morele rederneringsstadia bevordert (Kohlberg, 1984).',
    durationMin: 10,
  },
  {
    id: 'emco_1012_188',
    skill: 'Emotiecoaching',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Vergelijkingsdrang bespreken',
    description: 'Help je kind om te gaan met de neiging zichzelf te vergelijken met leeftijdsgenoten.',
    instructions: [
      'Begin vanuit een observatie: "Ik merk dat je soms zegt dat [naam] beter is in... Klopt dat?"',
      'Erken het gevoel: "Het is heel normaal om jezelf te vergelijken. Volwassenen doen het ook."',
      'Stel de vraag: "Als je jezelf met [naam] vergelijkt, hoe voel je je dan? En helpt dat vergelijken je?"',
      'Introduceer het concept: "Je enige eerlijke vergelijking is met jezelf van gisteren. Wat kun jij nu dat je vorig jaar nog niet kon?"',
    ],
    reflection: 'Vergelijken is menselijk, maar de meetlat van een ander legt altijd een te hoge lat. Help je kind een eigen maat te vinden.',
    scienceNote: 'Sociale vergelijking neemt sterk toe rond 10-12 jaar en is geassocieerd met lagere zelfwaarde tenzij ouders actief begeleiden (Dijkstra et al., 2008).',
    durationMin: 10,
  },
  {
    id: 'zelr_1012_189',
    skill: 'Zelfregulatie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Stress-signalen herkennen bij jezelf',
    description: 'Leer je kind de eigen fysieke en emotionele stresssignalen herkennen.',
    instructions: [
      'Teken samen een lichaamsilhouet op een groot vel papier.',
      'Vraag: "Als je stress hebt, waar voel je dat in je lichaam?" Laat je kind het intekenen (buikpijn, hoofdpijn, spanning).',
      'Bespreek ook emotionele signalen: prikkelbaarheid, geen zin meer, slecht slapen.',
      'Maak samen een "stressprotocol": drie dingen die je kind kan doen bij elk signaal.',
    ],
    reflection: 'Stressbewustzijn is de eerste stap naar stressmanagement. Wie zijn signalen kent, kan eerder ingrijpen.',
    scienceNote: 'Interoceptief bewustzijn (het herkennen van lichamelijke stresssignalen) is een kerncomponent van emotieregulatie (Nummenmaa et al., 2014; Siegel, 2012).',
    durationMin: 15,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // LEEFTIJD 13-16 — Identiteit, autonomie-onderhandeling, groepsdruk
  // ═══════════════════════════════════════════════════════════════════════

  {
    id: 'aanw_1316_190',
    skill: 'Aanwezigheid',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Beschikbaar zijn zonder te dringen',
    description: 'Laat je tiener weten dat je er bent, zonder een gesprek af te dwingen.',
    instructions: [
      'Wees vanavond fysiek aanwezig in dezelfde ruimte als je tiener (keuken, woonkamer).',
      'Doe iets eigens (lezen, koken) zonder een gesprek te starten of vragen te stellen.',
      'Als je tiener iets zegt, reageer warm maar kort. Ga niet door met vragen stellen.',
      'Zeg bij het weggaan iets als: "Ik vond het gezellig. Ik ben er als je wilt praten."',
    ],
    reflection: 'Tieners willen weten dat de deur open staat, maar willen zelf kiezen wanneer ze binnenkomen.',
    scienceNote: 'Ouderlijke beschikbaarheid zonder opdringerigheid is geassocieerd met hogere zelfrapportage van vertrouwen bij adolescenten (Allen & Land, 1999).',
    durationMin: 15,
  },
  {
    id: 'emco_1316_191',
    skill: 'Emotiecoaching',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Valideren zonder het eens te zijn',
    description: 'Oefen met het erkennen van de emotie van je tiener, ook als je het niet eens bent met de situatie.',
    instructions: [
      'Wacht op een moment dat je tiener klaagt over iets waar jij anders over denkt (oneerlijke docent, ruzie met vriend).',
      'Reageer eerst met validatie: "Ik snap dat je je [emotie] voelt. Dat is begrijpelijk in die situatie."',
      'Weersta de neiging om te corrigeren, te relativeren of advies te geven.',
      'Pas als je tiener zich gehoord voelt (je merkt het aan ontspanning), vraag je: "Wil je dat ik meedenk of wil je alleen dat ik luister?"',
    ],
    reflection: 'Valideren is niet hetzelfde als goedkeuren. Je kunt de emotie erkennen zonder het eens te zijn met de conclusie.',
    scienceNote: 'Emotionele validatie door ouders is geassocieerd met betere emotieregulatie en minder internaliserende problemen bij adolescenten (Linehan, 1993; Yap et al., 2014).',
    durationMin: 10,
  },
  {
    id: 'zelr_1316_192',
    skill: 'Zelfregulatie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Mindful pauzeren bij conflict',
    description: 'Oefen met het bewust pauzeren als een discussie met je tiener escaleert.',
    instructions: [
      'Spreek vooraf af: "Als een van ons merkt dat het escaleert, mag diegene zeggen: pauze. Dan stoppen we allebei vijf minuten."',
      'Bij de eerstvolgende escalatie: gebruik het woord "pauze" zelf als eerste.',
      'Loop weg, adem drie keer diep in en uit, en vraag jezelf: "Wat voel ik nu? Wat wil ik eigenlijk bereiken?"',
      'Kom na vijf minuten terug en begin met: "Laten we het opnieuw proberen. Ik wil je begrijpen."',
    ],
    reflection: 'De pauze is niet weglopen – het is de ruimte nemen om je volwassen brein in te schakelen.',
    scienceNote: 'Een bewuste pauze bij emotionele escalatie activeert de prefrontale cortex en vermindert reactieve agressie (Siegel, 2012; Davidson & Begley, 2012).',
    durationMin: 5,
  },
  {
    id: 'gren_1316_193',
    skill: 'Grenzen',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Onderhandelen over uitgaanstijden',
    description: 'Oefen met het onderhandelen over afspraken in plaats van eenzijdig regels op te leggen.',
    instructions: [
      'Begin het gesprek: "Ik wil het hebben over hoe laat je thuis bent. Vertel eerst: hoe laat vind jij redelijk en waarom?"',
      'Luister serieus naar de argumenten van je tiener zonder direct te reageren.',
      'Deel je eigen zorgen zonder te preken: "Mijn zorg is... Hoe kunnen we daar allebei rekening mee houden?"',
      'Kom samen tot een afspraak met een proefperiode: "We proberen dit vier weken, dan evalueren we."',
    ],
    reflection: 'Onderhandelen is geen zwakte. Het leert je tiener om respectvol te communiceren en verantwoordelijkheid te nemen.',
    scienceNote: 'Ouders die ruimte geven voor autonomie binnen duidelijke grenzen zien minder risicogedrag bij adolescenten (Baumrind, 1991; Steinberg, 2001).',
    durationMin: 10,
  },
  {
    id: 'auto_1316_194',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Eigen geld beheren',
    description: 'Geef je tiener verantwoordelijkheid over een deel van het eigen budget.',
    instructions: [
      'Bepaal een vast bedrag per maand dat je tiener zelf mag beheren (kleedgeld, uitgaansgeld).',
      'Bespreek samen: "Dit is jouw geld voor [categorie]. Als het op is, is het op tot volgende maand."',
      'Weersta de neiging om bij te springen als het geld op is – dat is het leerpunt.',
      'Evalueer na een maand samen: "Hoe ging het? Zou je iets anders doen?"',
    ],
    reflection: 'Financiële autonomie is een veilige oefenruimte voor grotere verantwoordelijkheden die later komen.',
    scienceNote: 'Het geven van financiële verantwoordelijkheid aan adolescenten bevordert executieve functies en toekomstgericht denken (Shim et al., 2010).',
    durationMin: 10,
  },
  {
    id: 'hers_1316_195',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Herverbinden na emotionele afstand',
    description: 'Zoek weer toenadering nadat je tiener zich een tijd heeft teruggetrokken.',
    instructions: [
      'Schrijf een kort briefje of stuur een bericht: "Ik merk dat er afstand is tussen ons. Dat vind ik moeilijk. Ik wil je laten weten dat ik er ben."',
      'Geef je tiener de tijd om te reageren – dring niet aan.',
      'Plan een laagdrempelige activiteit samen (eten halen, wandeling) zonder de afstand te bespreken.',
      'Als het contact er weer is, benoem kort: "Ik ben blij dat we weer praten. Ik wil begrijpen wat je nodig hebt."',
    ],
    reflection: 'Afstand is soms bescherming. De eerste stap zetten als vader toont dat jouw liefde niet afhankelijk is van hun gedrag.',
    scienceNote: 'Ouderlijke initiatie van herstelcontact na conflictvermijding is geassocieerd met betere relatieherstel en veilige hechting bij adolescenten (Kobak et al., 1993).',
    durationMin: 15,
  },
  {
    id: 'verb_1316_196',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen iets nieuws proberen',
    description: 'Doe samen een activiteit die voor jullie allebei nieuw is, zodat jullie samen beginners zijn.',
    instructions: [
      'Stel voor: "Laten we samen iets doen dat geen van ons eerder heeft gedaan. Wat kies jij?"',
      'Accepteer de suggestie (koken van een nieuw gerecht, sport, escape room, workshop).',
      'Wees tijdens de activiteit bereid om fouten te maken en erom te lachen.',
      'Bespreek na afloop: "Wat vonden we allebei? Wanneer doen we weer zoiets?"',
    ],
    reflection: 'Als je samen beginner bent, verdwijnt de ouder-kindverhouding even. Dan zijn jullie gewoon twee mensen die samen leren.',
    scienceNote: 'Gezamenlijke nieuwe ervaringen stimuleren dopamine-afgifte en versterken sociale bonding, ook in ouder-tienerrelaties (Aron et al., 2000).',
    durationMin: 15,
  },
  {
    id: 'refl_1316_197',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Groepsdruk samen analyseren',
    description: 'Bespreek met je tiener hoe groepsdruk werkt en hoe je er bewust mee om kunt gaan.',
    instructions: [
      'Vraag: "Heb je weleens iets gedaan omdat iedereen het deed, terwijl je het eigenlijk niet wilde?" Deel ook je eigen ervaring.',
      'Bespreek: "Wat maakt het zo moeilijk om nee te zeggen tegen je groep?"',
      'Oefen samen letterlijke zinnen: "Nee, niet mijn ding", "Ik ga dit keer passen", "Doe jij maar, ik hoef niet."',
      'Spreek af: "Als je ooit in een situatie zit waar je niet weet hoe je nee moet zeggen, app me een codewoord en ik bel je."',
    ],
    reflection: 'Groepsdruk bespreken is makkelijker dan groepsdruk weerstaan. Maar het gesprek nu maakt het weerstaan straks iets minder moeilijk.',
    scienceNote: 'Vooraf besproken weigeringsstrategieën (resistance skills training) verminderen risico op meegaan met riskant groepsgedrag bij adolescenten (Botvin et al., 2001).',
    durationMin: 15,
  },
  {
    id: 'emco_1316_198',
    skill: 'Emotiecoaching',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Identiteitsverkenning ondersteunen',
    description: 'Ondersteun je tiener bij het verkennen van wie hij of zij is, zonder jouw verwachtingen op te leggen.',
    instructions: [
      'Merk op wanneer je tiener experimenteert met stijl, muziek, ideeën of vrienden die anders zijn dan jij verwacht.',
      'Reageer met nieuwsgierigheid in plaats van afkeuring: "Vertel eens, wat spreekt je aan in [nieuw interesse]?"',
      'Weersta de neiging om te corrigeren of je zorgen uit te spreken – parkeer dat voor een ander moment.',
      'Deel een herinnering aan je eigen zoektocht: "Toen ik zo oud was als jij, probeerde ik ook van alles uit."',
    ],
    reflection: 'Identiteit vormen is het belangrijkste werk van de adolescentie. Je kind heeft jouw ruimte nodig, niet jouw blauwdruk.',
    scienceNote: 'Ouders die identiteitsexploratie ondersteunen zonder druk bevorderen een gezonde identiteitsontwikkeling volgens Erikson (Erikson, 1968; Marcia, 1980).',
    durationMin: 10,
  },
  {
    id: 'gren_1316_199',
    skill: 'Grenzen',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Grens stellen bij respectloos gedrag',
    description: 'Reageer kalm maar duidelijk wanneer je tiener respectloos communiceert.',
    instructions: [
      'Als je tiener schreeuwt, vloekt of respectloos praat, pauzeer even en adem diep in.',
      'Zeg rustig en zonder volume te verhogen: "Ik wil naar je luisteren, maar niet op deze manier. Laten we even pauzeren."',
      'Geef vijf minuten ruimte, kom dan terug: "Ik respecteer jou en ik verwacht dat ook van jou naar mij."',
      'Luister daarna naar de inhoud van wat je tiener wilde zeggen – de emotie erachter verdient aandacht.',
    ],
    reflection: 'De grens gaat niet over de woorden maar over de omgangsvorm. Je kunt boos zijn, maar niet alles is acceptabel. Dat onderscheid is de les.',
    scienceNote: 'Consistente grenzen bij respectloos gedrag, gecombineerd met warmte, voorspellen betere sociale vaardigheden bij adolescenten (Lamborn et al., 1991).',
    durationMin: 5,
  },
];
