import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_17: InteractiveTask[] = [
  // Herstel ronde 2 – leeftijd 0-2
  {
    id: 'hers_02_11',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Na de nacht terug verbinden',
    description: 'Herstel de verbinding met je baby na een slechte nacht voor jullie allebei.',
    instructions: [
      'Neem na een moeilijke nacht een moment als je baby wakker en rustig is.',
      'Pak je baby op en houd hem/haar rustig vast.',
      'Praat zacht en kijk je baby aan.',
      'Laat de stress van de nacht los en begin opnieuw.',
    ],
    reflection: 'Een nieuwe ochtend is altijd een herstelkans. Baby\'s onthouden niet, maar vaders kunnen opnieuw beginnen.',
    scienceNote: 'Repair-cyclussen zijn normaal en gezond – zelfs gevoelige moeders en vaders zijn maar 30% van de tijd "in sync" (Tronick, 2007).',
    durationMin: 5,
  },
  {
    id: 'hers_02_12',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Kalmeer jezelf eerst',
    description: 'Oefen het eerst kalmeren van jezelf voordat je naar je huilende baby terugkeert.',
    instructions: [
      'Als je baby huilt en jij voelt je overweldigd, leg je baby veilig neer.',
      'Doe drie langzame uitademingen in de aangrenzende kamer.',
      'Zeg tegen jezelf: "Ik kan dit. Mijn baby heeft mij nodig."',
      'Ga terug en reageer vanuit rust.',
    ],
    reflection: 'Een vader die zichzelf eerst kalmeert reageert sensitiever dan een vader die overweldigd reageert.',
    scienceNote: 'Co-regulatie van vaders begint bij zelfregulatie – vaders moeten zichzelf reguleren voor ze hun baby kunnen kalmeren (Porges, 2011).',
    durationMin: 5,
  },
  {
    id: 'hers_02_13',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Excuses aan je partner',
    description: 'Herstel de relatie met je partner na een conflict veroorzaakt door slaaptekort of stress.',
    instructions: [
      'Denk aan een recent moment waarop je kortaf, geïrriteerd of onaardig was tegen je partner.',
      'Neem verantwoordelijkheid zonder te rechtvaardigen: "Ik was kortaf en dat was niet oké."',
      'Vraag: "Hoe heeft dat voor jou gevoeld?"',
      'Sluit af met: "Wat heb jij nu nodig van mij?"',
    ],
    reflection: 'Herstel met je partner is ook herstel voor je kind – het gezinsklimaat bepaalt de veiligheid van je baby.',
    scienceNote: 'Ouderlijk conflict beïnvloedt de stressrespons van baby\'s via het autonoom zenuwstelsel (Davies & Cummings, 1994).',
    durationMin: 15,
  },
  {
    id: 'hers_02_14',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Herstel na een uitbarsting',
    description: 'Reflecteer op wat je kunt doen na een moment van overreactie bij je baby.',
    instructions: [
      'Herinner je een moment waarop je te hard reageerde (schreeuwde, de kamer uitliep, te heftig optilde).',
      'Beschrijf wat er intern gebeurde: wat voelde je, wat dacht je?',
      'Wat had je nodig in dat moment wat je niet had?',
      'Maak een persoonlijk noodplan voor de volgende keer dat je zo\'n moment voelt aankomen.',
    ],
    reflection: 'Een noodplan maken is geen zwakte – het is een bewijs van verantwoordelijkheid als vader.',
    scienceNote: 'Proactieve copingstrategieën verminderen ouderstress en verbeteren reacties in stressvolle momenten (Lazarus & Folkman, 1984).',
    durationMin: 15,
  },
  {
    id: 'hers_02_15',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Steun vragen',
    description: 'Oefen het vragen van steun als jij het moeilijk hebt als vader van een baby.',
    instructions: [
      'Erken eerlijk: op welk gebied heb jij als vader van een baby of peuter nu ondersteuning nodig?',
      'Wie in jouw omgeving kan die steun bieden?',
      'Stuur vandaag één bericht of maak één telefoontje om die steun te vragen.',
      'Reflecteer daarna: hoe voelde het om steun te vragen?',
    ],
    reflection: 'Steun vragen is een daad van kracht, niet van zwakte. Vaders die steun vragen zijn veerkrachtiger.',
    scienceNote: 'Sociale steun is de sterkste buffer tegen ouderstress (Crnic & Greenberg, 1990).',
    durationMin: 10,
  },
  {
    id: 'hers_02_16',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Trauma en vaderschap',
    description: 'Onderzoek of eigen traumatische ervaringen invloed hebben op hoe jij reageert als vader van een baby.',
    instructions: [
      'Denk aan momenten waarop je als vader reageerde op een manier die je later verraste (overreactie, dissociatie, vermijding).',
      'Kun je die reactie linken aan ervaringen uit je eigen verleden?',
      'Bespreek dit met een partner, vriend of professional.',
      'Overweeg of professionele ondersteuning (therapie, coaching) nuttig zou zijn.',
    ],
    reflection: 'Onverwerkt trauma beïnvloedt onbewust ons ouderschap. Erkenning is de eerste stap naar verandering.',
    scienceNote: 'Onverwerkt trauma verhoogt de kans op gedesorganiseerde gehechtheid bij kinderen (Lyons-Ruth & Jacobvitz, 1999).',
    durationMin: 20,
  },
  {
    id: 'hers_02_17',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Zelfcompassie als vader',
    description: 'Oefen zelfcompassie na een moeilijk moment in je vaderschap.',
    instructions: [
      'Herinner je een recent moment waarbij je als vader tekortschoot.',
      'Leg je hand op je hart en zeg hardop: "Dit was moeilijk. Ik doe mijn best."',
      'Stel je voor wat je zou zeggen tegen een goede vriend in dezelfde situatie.',
      'Zeg datzelfde nu tegen jezelf.',
    ],
    reflection: 'Zelfcompassie is niet soft – het is wetenschappelijk aangetoond effectiever dan zelfkritiek voor gedragsverandering.',
    scienceNote: 'Zelfcompassie vergroot veerkracht en motivatie tot gedragsverandering (Neff, 2011).',
    durationMin: 10,
  },
  {
    id: 'hers_02_18',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Herstelplan voor de week',
    description: 'Maak een concrete herstelplan voor de komende week als vader van een baby of peuter.',
    instructions: [
      'Identificeer de grootste belasting in jouw vaderschap van de afgelopen week.',
      'Bedenk drie kleine herstelacties (bijv. eerder slapen, een moment alleen, bewegen).',
      'Plan die drie acties in je agenda voor komende week.',
      'Bespreek je herstelplan met je partner of iemand die je ondersteunt.',
    ],
    reflection: 'Herstel plannen is een proactieve vaardigheid die burnout als vader voorkomt.',
    scienceNote: 'Ouderlijke uitputting is een serieus risico dat preventief aangepakt kan worden (Mikolajczak et al., 2018).',
    durationMin: 15,
  },
  {
    id: 'hers_02_19',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Opnieuw proberen',
    description: 'Na een minder goede interactie: probeer het opnieuw met je baby of peuter.',
    instructions: [
      'Als een interactie fout liep (te weinig geduld, te weinig aandacht), wacht dan een korte pauze.',
      'Ga terug naar je kind met een rustige en warme intentie.',
      'Begin de interactie opnieuw: speel, pak op, praat, glimlach.',
      'Merk op: je kind reageert op jouw nieuwe energie.',
    ],
    reflection: 'Herstel hoeft niet groot te zijn. Soms is terugkomen voldoende.',
    scienceNote: 'Baby\'s en peuters herstellen snel als de vader terugkeert met warmte (Tronick & Cohn, 1989).',
    durationMin: 5,
  },
  {
    id: 'hers_02_20',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Iets goeds voor jezelf',
    description: 'Doe bewust iets goeds voor jezelf vandaag – als investering in je vaderschap.',
    instructions: [
      'Kies één ding dat jou energie geeft of ontspant (sporten, muziek, wandelen, slapen, iets lekkers eten).',
      'Plan het vandaag in – ook al is het maar 15 minuten.',
      'Doe het zonder schuldgevoel: "Dit doe ik voor mezelf, zodat ik een betere vader kan zijn."',
      'Merk daarna op of je aanweziger bent bij je kind.',
    ],
    reflection: 'Goed voor jezelf zorgen maakt je een betere vader. Dat is geen egoïsme – dat is wijsheid.',
    scienceNote: 'Ouderlijk zelfzorg vermindert stress en verhoogt responsiviteit (Mikolajczak & Roskam, 2018).',
    durationMin: 15,
  },

  // Herstel ronde 2 – leeftijd 3-5
  {
    id: 'hers_35_11',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Sorry zeggen aan een kleuter',
    description: 'Oefen het oprecht excuses maken aan je kind van 3-5 jaar.',
    instructions: [
      'Denk aan een moment de afgelopen week dat je te hard was, schreeuwde, of oneerlijk was.',
      'Ga naast je kind zitten op ooghoogte.',
      'Zeg: "Ik was te [boos/streng/kortaf]. Dat was niet aardig. Sorry."',
      'Knuffel je kind daarna als het daar behoefte aan heeft.',
    ],
    reflection: 'Sorry zeggen aan een kind leert het dat fouten maken mag én dat herstellen belangrijk is.',
    scienceNote: 'Ouderlijk herstelgedrag modelleert herstelvaardigheden bij kinderen en versterkt de gehechtheid (Siegel & Bryson, 2011).',
    durationMin: 5,
  },
  {
    id: 'hers_35_12',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Na de driftbui',
    description: 'Herstel de verbinding met je kleuter na een driftaanval.',
    instructions: [
      'Wacht tot je kind gekalmeerd is (niet tijdens de bui).',
      'Ga naar je kind, knielvoor hem/haar en zeg: "Ik zie dat het moeilijk was."',
      'Bied een knuffel of aanraking aan – wacht op zijn/haar antwoord.',
      'Neem daarna samen een glas water of doe iets rustigs samen.',
    ],
    reflection: 'Hoe jij reageert na een driftbui bepaalt of je kind je als veilige haven ervaart.',
    scienceNote: 'Ouderlijk herstelgedrag na driftbuien versterkt de veilige gehechtheid en vermindert toekomstige intensiteit van driftbuien (Kopp, 1989).',
    durationMin: 10,
  },
  {
    id: 'hers_35_13',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'De herstelroutine bouwen',
    description: 'Creëer een vaste herstelroutine die je na conflicten met je kleuter toepast.',
    instructions: [
      'Bedenk een persoonlijke herstelroutine na conflicten: bijv. (1) kalmeer jezelf, (2) ga terug naar kind, (3) erken, (4) knuffel.',
      'Schrijf die routine op.',
      'Oefen hem de komende week bij elk klein conflict.',
      'Evalueer na een week: werkt dit? Wat wil je aanpassen?',
    ],
    reflection: 'Een routine voor herstel maakt het minder afhankelijk van hoe je je voelt – het wordt automatisch.',
    scienceNote: 'Herstelgedrag dat geroutineerd is, is betrouwbaarder dan ad-hoc herstel en bouwt veiliger gehechtheid (Bowlby, 1988).',
    durationMin: 15,
  },
  {
    id: 'hers_35_14',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Gezamenlijk repareren',
    description: 'Herstel samen met je kleuter na een ruzie of conflict.',
    instructions: [
      'Ga naast je kind zitten nadat jullie allebei gekalmeerd zijn.',
      'Vertel wat er gebeurde: "We hadden ruzie omdat..."',
      'Vraag: "Hoe voelde jij je? Hoe voelde ik me?"',
      'Sluit af: "Wat kunnen we de volgende keer beter doen?"',
    ],
    reflection: 'Conflicten samen verwerken leert kleuters dat relaties repareerbaar zijn – een van de meest waardevolle lessen.',
    scienceNote: 'Gezamenlijke conflictverwerking vergroot emotionele geletterdheid en probleemoplossing bij kleuters (Eisenberg et al., 1998).',
    durationMin: 10,
  },
  {
    id: 'hers_35_15',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Vergeven en vergeten?',
    description: 'Reflecteer op je vermogen om conflicten los te laten en opnieuw te beginnen met je kleuter.',
    instructions: [
      'Denk aan een conflict van gisteren of eerder deze week met je kind.',
      'Draag je dat conflict nog mee (irritatie, afstand, spanning)?',
      'Wat heb jij nodig om het los te laten?',
      'Sluit het conflict bewust af door iets leuks samen te doen.',
    ],
    reflection: 'Kleuters vergeven snel. Als jij het conflict blijft vasthouden, voel zij dat ook.',
    scienceNote: 'Vergeven in relaties met kinderen verlaagt stress bij zowel ouder als kind (Witvliet et al., 2001).',
    durationMin: 10,
  },
  {
    id: 'hers_35_16',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Schaamte en schuldgevoel als vader',
    description: 'Onderzoek het verschil tussen schuldgevoel en schaamte in jouw vaderschap.',
    instructions: [
      'Herinner je een moment waarbij je als vader faalde. Hoe voelde je daarna?',
      'Was het schuldgevoel ("Ik deed iets fout") of schaamte ("Ik ben slecht")?',
      'Schuldgevoel motiveert tot herstel. Schaamte verlamt. Welke overweegt bij jou?',
      'Als schaamte overweegt: zoek steun bij een professional of vertrouwenspersoon.',
    ],
    reflection: 'Schaamte is de vijand van goed vaderschap. Schuld is de motor van groei.',
    scienceNote: 'Schaamte bij ouders correleert met minder herstelgedrag en meer vermijding (Brown, 2010; Tangney et al., 2007).',
    durationMin: 20,
  },
  {
    id: 'hers_35_17',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Herstel na een grote fout',
    description: 'Verwerk een grote fout die je als vader maakte met je kleuter.',
    instructions: [
      'Noem de fout zonder jezelf te veroordelen: wat deed je precies?',
      'Welk effect had het op je kind?',
      'Welke stap van herstel heb je al gezet? Welke nog niet?',
      'Maak een plan voor volledig herstel: erkenning, excuses, gedragsverandering.',
    ],
    reflection: 'Grote fouten vragen groot herstel. Maar groot herstel bouwt ook groot vertrouwen.',
    scienceNote: 'Kwaliteit van herstel na schendingen bepaalt de mate van vertrouwen in de relatie (Gottman, 1994).',
    durationMin: 20,
  },
  {
    id: 'hers_35_18',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Een nieuwe start',
    description: 'Maak bewust een nieuwe start in je vaderschap – sluit een moeilijke periode af.',
    instructions: [
      'Denk aan een periode de afgelopen maanden die je zwaar vond als vader.',
      'Erken: wat was er moeilijk? Wat heb je geleerd?',
      'Schrijf een intentie voor de volgende periode: "Vanaf nu wil ik als vader..."',
      'Vertel je partner of iemand die je vertrouwt over je nieuwe intentie.',
    ],
    reflection: 'Bewuste nieuwe starts geven richting en motivatie. Ze maken groei zichtbaar.',
    scienceNote: 'Intentie-stellingen activeren de prefrontale cortex en verhogen de kans op gedragsverandering (Gollwitzer, 1999).',
    durationMin: 20,
  },
  {
    id: 'hers_35_19',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Een herstelmoment plannen',
    description: 'Plan een bewust herstelmoment voor jou en je kleuter na een drukke of gespannen periode.',
    instructions: [
      'Kies een activiteit die jullie allebei leuk vinden (park, lego, tekenen, koken).',
      'Plan het bewust in – dit weekend of morgen.',
      'Ga met een vrije en aanwezige houding – geen telefoon, geen taken.',
      'Merk op hoe je kind reageert op jouw aanwezige energie.',
    ],
    reflection: 'Na een moeilijke periode heeft de relatie een positieve oplaadbeurt nodig.',
    scienceNote: 'Positieve interacties na conflict herstellen de relatie sneller dan verbale excuses alleen (Gottman, 1997).',
    durationMin: 30,
  },
  {
    id: 'hers_35_20',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'De knuffelherstarter',
    description: 'Gebruik een knuffel bewust als herstelgebaar naar je kleuter.',
    instructions: [
      'Na een kleine ruzie of gespannen moment: vraag je kind: "Wil jij een knuffel?"',
      'Als ja: geef een langdurige, warme knuffel (20 seconden).',
      'Fluister: "Ik hou van jou, ook als het moeilijk is."',
      'Laat daarna los en ga samen iets leuks doen.',
    ],
    reflection: 'Een knuffel na een conflict communiceert: "Jij bent veilig. Wij zijn oké."',
    scienceNote: 'Fysiek contact na conflict verlaagt cortisol bij kleuters en herstelt het gevoel van veiligheid (Field, 2010).',
    durationMin: 5,
  },

  // Herstel ronde 2 – leeftijd 6-9
  {
    id: 'hers_69_11',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Schuld erkennen tegenover je kind',
    description: 'Leer je kind van 6-9 jaar dat jij fouten kunt erkennen.',
    instructions: [
      'Denk aan een fout die je recent maakte als vader.',
      'Ga naar je kind en zeg: "Ik heb nagedacht en ik vind dat ik... niet goed deed. Sorry."',
      'Vraag: "Hoe voelde jij je daarna?"',
      'Luister en erken het gevoel van je kind.',
    ],
    reflection: 'Vader die fouten erkent leert zijn kind dat fouten maken menselijk is én dat herstel mogelijk is.',
    scienceNote: 'Ouderlijk herstelgedrag modelleert verantwoordelijkheidsgevoel en empathie bij schoolkinderen (Eisenberg et al., 2001).',
    durationMin: 10,
  },
  {
    id: 'hers_69_12',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Herstellen van een beloofd plan',
    description: 'Herstel de verbroken belofte aan je kind van 6-9 jaar.',
    instructions: [
      'Denk aan een belofte die je niet nakwam (activiteit, afspraak, tijd samen).',
      'Erken dit aan je kind: "Ik had beloofd X en dat is niet gelukt. Dat vind ik niet oké."',
      'Maak een concrete nieuwe afspraak: "Ik wil dit inhalen door..."',
      'Houd de nieuwe afspraak – koste wat het kost.',
    ],
    reflection: 'Verbroken beloftes beschadigen vertrouwen. Herstel ervan bouwt vertrouwen juist op.',
    scienceNote: 'Consistent nakomen van beloftes is een van de sterkste voorspellers van kindvertrouwen in de vader (Lamb, 2004).',
    durationMin: 10,
  },
  {
    id: 'hers_69_13',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het gesprek dat jij vermeed',
    description: 'Voer het herstelgesprek dat je al een tijdje uitstelt met je kind van 6-9.',
    instructions: [
      'Is er een spanning, conflict of misverstand dat je al een tijdje laat hangen?',
      'Plan een rustig moment om het te bespreken.',
      'Begin met: "Ik heb nagedacht over wat er is gebeurd en ik wil het uitpraten."',
      'Luister eerst, reageer daarna.',
    ],
    reflection: 'Uitstelgedrag in herstel maakt de kloof groter. De eerste stap zetten is altijd de moeilijkste.',
    scienceNote: 'Hoe langer herstel wordt uitgesteld, hoe meer de gehechtheidsband erodeert (Gottman, 1994).',
    durationMin: 20,
  },
  {
    id: 'hers_69_14',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Samen probleemoplossen na conflict',
    description: 'Los een herhaald conflict samen op met je kind van 6-9 jaar.',
    instructions: [
      'Kies een terugkerend conflict (bijv. over schermtijd, huiswerk, bedtijd).',
      'Ga samen zitten en vraag: "Hoe kunnen we dit samen beter aanpakken?"',
      'Luister naar de ideeën van je kind.',
      'Maak samen een kleine afspraak en schrijf die op.',
    ],
    reflection: 'Kinderen van 6-9 zijn oud genoeg om mee te denken over oplossingen. Dat vergroot hun betrokkenheid.',
    scienceNote: 'Collaboratief probleemoplossen met kinderen verlaagt conflict en vergroot compliancegedrag (Greene, 2014).',
    durationMin: 20,
  },
  {
    id: 'hers_69_15',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Herstellen van afstandelijkheid',
    description: 'Breng bewust warmte en nabijheid terug na een periode van afstand met je kind.',
    instructions: [
      'Herken eerlijk: zijn er periodes dat je afstandelijk of onbereikbaar was voor je kind?',
      'Wat was de oorzaak (werk, stress, eigen problemen)?',
      'Plan drie momenten van actieve verbinding komende week (spel, gesprek, samen eten).',
      'Merk hoe je kind reageert naarmate je meer aanwezig bent.',
    ],
    reflection: 'Kinderen vergeven afstandelijkheid als er consistente warmte op volgt.',
    scienceNote: 'Vaders die periodes van afstandelijkheid bewust herstellen, behouden veilige gehechtheid (Lamb, 2010).',
    durationMin: 15,
  },
  {
    id: 'hers_69_16',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Invloed van mijn werk op mijn kind',
    description: 'Analyseer hoe jouw werkdruk of stress thuis doorwerkt op je kind van 6-9.',
    instructions: [
      'Denk eerlijk: hoe beïnvloedt jouw werkstress het klimaat thuis?',
      'Wat ziet je kind van die stress? (kortaf zijn, niet aanwezig zijn, overcompenseren?)',
      'Wat is de impact op je kind?',
      'Bedenk één grens die je stelt om werkstress thuis te verminderen.',
    ],
    reflection: 'Werk-privé overloop is een van de meest onderschatte veroorzakers van spanningen in het gezin.',
    scienceNote: 'Werkgerelateerde stress van vaders beïnvloedt direct het gedrag van kinderen via gezinsklimaat (Repetti, 1994).',
    durationMin: 20,
  },
  {
    id: 'hers_69_17',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Herstellen van schreeuwen',
    description: 'Verwerk een moment waarbij je schreeuwde naar je kind van 6-9 jaar.',
    instructions: [
      'Herinner je een moment dat je schreeuwde. Beschrijf wat er was voorafgaand.',
      'Hoe reageerde je kind?',
      'Ga naar je kind toe en maak het goed: erken wat je deed, verontschuldig je, verklaar (niet rechtvaardigen).',
      'Stel jezelf een grens: wat doe je de volgende keer als je die intensiteit voelt opkomen?',
    ],
    reflection: 'Schreeuwen is menselijk. Maar er daarna goed mee omgaan is vaderkunst.',
    scienceNote: 'Ouderlijk schreeuwen heeft significante negatieve effecten op het zelfrespect van kinderen – maar herstel dempt die effecten sterk (Wang & Kenny, 2014).',
    durationMin: 20,
  },
  {
    id: 'hers_69_18',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Vaders onderling',
    description: 'Deel een moeilijk moment als vader met een andere vader en zoek samen naar herstelstrategieën.',
    instructions: [
      'Neem contact op met een bevriende vader of collega-vader.',
      'Deel één moeilijk moment van de afgelopen maand zonder te verdoezelen.',
      'Luister naar zijn ervaringen.',
      'Vraag: "Hoe herstel jij als het fout gaat?"',
    ],
    reflection: 'Vaders die met andere vaders praten, voelen minder schaamte en meer motivatie.',
    scienceNote: 'Peer-ondersteuning bij vaders vergroot competentiegevoel en vermindert isolement (Genesoni & Tallandini, 2009).',
    durationMin: 30,
  },
  {
    id: 'hers_69_19',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Een verrassingsdaad',
    description: 'Doe een onverwachte, positieve daad voor je kind als herstelgebaar na een moeilijke week.',
    instructions: [
      'Denk aan iets wat je kind leuk zou vinden (een verrassingsplek, een spelletje, een traktatie).',
      'Organiseer het zonder aankondiging.',
      'Geniet er samen van.',
      'Je hoeft geen excuses te maken – de daad spreekt voor zichzelf.',
    ],
    reflection: 'Positieve verrassingen zijn krachtige herstelgebaren die de relatie versterken.',
    scienceNote: 'Positieve en onverwachte ervaringen activeren het beloningssysteem en versterken de emotionele band (Aron et al., 2000).',
    durationMin: 60,
  },
  {
    id: 'hers_69_20',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Rustig opnieuw beginnen',
    description: 'Begin een nieuwe dag bewust en kalm na een gespannen dag of avond.',
    instructions: [
      'Begin de ochtend met een warme begroeting van je kind: naam, oogcontact, glimlach.',
      'Laat de spanning van gisteren los – begin fris.',
      'Vraag: "Hoe heb je geslapen?" en luister echt.',
      'Creëer een rustige, positieve toon voor de dag.',
    ],
    reflection: 'Elke nieuwe dag is een nieuwe kans. Een warme start zet de toon voor de rest.',
    scienceNote: 'Positieve ochtendinteracties verminderen stressrespons bij kinderen gedurende de schooldag (Adam et al., 2007).',
    durationMin: 10,
  },

  // Herstel ronde 2 – leeftijd 10-12
  {
    id: 'hers_1012_11',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Eerlijk excuses maken aan een preteen',
    description: 'Oefen het maken van oprechte excuses aan je kind van 10-12 jaar.',
    instructions: [
      'Herinner je een moment de afgelopen maand waarop je oneerlijk, onredelijk of te streng was.',
      'Zoek je kind op en zeg: "Ik heb nagedacht over [situatie]. Ik deed dat niet goed. Sorry."',
      'Vraag: "Hoe voelde jij je daarna?"',
      'Wacht, luister, en erken hun gevoel zonder je te verdedigen.',
    ],
    reflection: 'Een vader die excuses maakt aan een preteen toont authenticiteit en legt de basis voor een eerlijke relatie.',
    scienceNote: 'Authentieke ouderlijke excuses verhogen het vertrouwen bij preteens significant (Ohbuchi et al., 1989).',
    durationMin: 10,
  },
  {
    id: 'hers_1012_12',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Na een grote ruzie',
    description: 'Herstel de relatie na een hevige ruzie met je kind van 10-12.',
    instructions: [
      'Wacht tot jullie allebei gekalmeerd zijn (minimaal een uur).',
      'Initieer het gesprek: "Kunnen we praten over wat er is gebeurd?"',
      'Deel jouw perspectief, luister naar het hunne.',
      'Sluit af met een herstelgebaar: samen iets doen, een knuffel als dat past, of een positieve afspraak.',
    ],
    reflection: 'Na grote ruzies is initiatief nemen als vader een teken van kracht, niet van zwakte.',
    scienceNote: 'Ouders die initiatief nemen tot herstel, behouden sterkere band met preteens na conflicten (Laursen & Collins, 1994).',
    durationMin: 30,
  },
  {
    id: 'hers_1012_13',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Herstel na langdurige afstand',
    description: 'Bouw bewust de band opnieuw op na een periode van emotionele afstand met je preteen.',
    instructions: [
      'Erken aan jezelf: er was een periode van afstand. Wat was de oorzaak?',
      'Plan een activiteit die jullie allebei leuk vinden – laagdrempelig en ontspannen.',
      'Forceer geen gesprekken: laat verbinding organisch groeien.',
      'Herhaal dit wekelijks tot je merkt dat de sfeer verandert.',
    ],
    reflection: 'Verbinding met een preteen herstel je niet in één gesprek maar in vele kleine, consistente momenten.',
    scienceNote: 'Consistente, positieve interacties herstellen gehechtheid effectiever dan sporadische intense pogingen (Waters et al., 2000).',
    durationMin: 60,
  },
  {
    id: 'hers_1012_14',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Grenzen herzien na conflict',
    description: 'Evalueer of een grens of regel die conflict veroorzaakte eerlijk en passend is.',
    instructions: [
      'Denk aan een regel of grens die vaak tot conflict leidt.',
      'Vraag jezelf: is deze grens nog passend bij de leeftijd van mijn kind?',
      'Bespreek het met je kind: "Ik wil met je praten over de regel voor..."',
      'Pas de grens aan als dat passend is – en leg uit waarom.',
    ],
    reflection: 'Grenzen aanpassen aan de groei van je kind is geen zwakte – het is bewust ouderschap.',
    scienceNote: 'Rigide grenzen die niet meegroeien met het kind leiden tot onnodige conflicten in de preteen-fase (Steinberg, 2001).',
    durationMin: 20,
  },
  {
    id: 'hers_1012_15',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Vertrouwen terugwinnen',
    description: 'Werk bewust aan het terugwinnen van vertrouwen als je kind dat heeft verloren in jou.',
    instructions: [
      'Erken eerlijk: heeft jouw kind reden om minder vertrouwen in jou te hebben?',
      'Benoem één concreet gedrag dat je verandert.',
      'Wees consistent gedurende minimaal twee weken.',
      'Vraag na die periode aan je kind: "Merk jij een verschil?"',
    ],
    reflection: 'Vertrouwen wordt niet teruggewonnen met woorden maar met gedrag over tijd.',
    scienceNote: 'Vertrouwen in ouders herstelt bij kinderen via consistent en voorspelbaar gedrag (Erikson, 1950; revisited Sroufe, 1990).',
    durationMin: 20,
  },
  {
    id: 'hers_1012_16',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Herstel na een grote fout',
    description: 'Verwerk en herstel een moment waarbij je als vader ernstig tekortschoot.',
    instructions: [
      'Beschrijf eerlijk wat er is gebeurd en wat het effect was op je kind.',
      'Neem volledige verantwoordelijkheid: geen "maar", geen excuses.',
      'Maak het goed: zeg sorry, luister naar je kind, bied compensatie aan als gepast.',
      'Maak een plan om herhaling te voorkomen.',
    ],
    reflection: 'Hoe je omgaat met grote fouten bepaalt de kwaliteit van jouw vaderschap meer dan de fouten zelf.',
    scienceNote: 'Volledig herstel na serieuze schendingen versterkt de gehechtheid sterker dan als de schending nooit had plaatsgevonden (Ruppert & Kernberg, 2009).',
    durationMin: 30,
  },
  {
    id: 'hers_1012_17',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Gezin als herstelomgeving',
    description: 'Maak van jullie gezin een plek waar fouten en herstel normaal zijn.',
    instructions: [
      'Bespreek met je gezin: hoe gaan wij om met fouten en herstel?',
      'Stel een gezinsafspraak voor: "Wij zeggen sorry. Wij geven tweede kansen."',
      'Modelleer dit zelf consequent.',
      'Vier momenten van goed herstel: "Ik vind het mooi hoe jij dat oploste."',
    ],
    reflection: 'Gezinnen die herstel normaliseren zijn veerkrachtiger en gelukkiger.',
    scienceNote: 'Gezinscultuur rondom herstel en vergiffenis correleert met betere mentale gezondheid van kinderen (McCullough et al., 2000).',
    durationMin: 30,
  },
  {
    id: 'hers_1012_18',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Wat wij nodig hebben als gezin',
    description: 'Evalueer samen als gezin wat jullie nodig hebben om beter voor elkaar te zorgen.',
    instructions: [
      'Plan een gezinsmoment – geen vergadering maar een ontspannen gesprek.',
      'Vraag elk gezinslid: "Wat heb jij nodig van ons gezin dat er nu onvoldoende is?"',
      'Luister zonder te oordelen.',
      'Kies samen één actie voor de komende maand.',
    ],
    reflection: 'Gezinnen die regelmatig evalueren en bijsturen zijn adaptatiever en gelukkiger.',
    scienceNote: 'Gezinsoverleg vergroot cohesie en het gevoel van gehoord worden bij kinderen (Gottman & DeClaire, 1997).',
    durationMin: 30,
  },
  {
    id: 'hers_1012_19',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Nieuwe kansen geven',
    description: 'Geef je kind van 10-12 jaar bewust een nieuwe kans na een fout of conflict.',
    instructions: [
      'Denk aan iets waarvoor je kind gestraft of gecorrigeerd werd.',
      'Vraag jezelf: heeft mijn kind de kans gekregen om het beter te doen?',
      'Creëer die kans: geef een vergelijkbare situatie en laat je kind het anders aanpakken.',
      'Erken wanneer hij/zij het beter doet: "Ik zie dat je het nu anders aanpakt. Mooi."',
    ],
    reflection: 'Nieuwe kansen geven is een teken van vertrouwen in je kind.',
    scienceNote: 'Kinderen wiens vaders hen tweede kansen geven, ontwikkelen meer intern gemotiveerd gedrag (Deci & Ryan, 2000).',
    durationMin: 10,
  },
  {
    id: 'hers_1012_20',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Opbouwend afsluiten van de week',
    description: 'Sluit de week positief af met je kind van 10-12 jaar en kijk vooruit.',
    instructions: [
      'Ga samen zitten aan het einde van de week.',
      'Vraag: "Wat ging er goed deze week? Wat was moeilijk?"',
      'Sluit af met: "Wat gaan we volgende week anders doen?"',
      'Eindig met iets positiefs: compliment of een moment om naar uit te kijken.',
    ],
    reflection: 'Bewust afsluiten van de week is een krachtig gezinsritueel dat herstel en groei verankert.',
    scienceNote: 'Gezinsrituelen aan het eind van de week bevorderen cohesie en toekomstgerichtheid (Fiese, 2006).',
    durationMin: 15,
  },

  // Herstel ronde 2 – leeftijd 13-16
  {
    id: 'hers_1316_11',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Sorry zeggen aan je tiener',
    description: 'Maak oprechte excuses aan je tiener voor iets wat je fout deed.',
    instructions: [
      'Kies een recent moment waarbij je als vader tekortschoot.',
      'Ga naar je tiener en zeg: "Ik moet je iets zeggen. Ik deed X niet goed. Dat spijt me."',
      'Leg geen oorzaken aan – neem gewoon verantwoordelijkheid.',
      'Vraag of ze erover willen praten of dat ze tijd nodig hebben.',
    ],
    reflection: 'Een vader die sorry zegt, leert zijn tiener dat verantwoordelijkheid nemen kracht is.',
    scienceNote: 'Authentieke ouderlijke excuses verhogen het zelfrespect van tieners en verdiepen de band (Darby & Schlenker, 1982).',
    durationMin: 10,
  },
  {
    id: 'hers_1316_12',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Na een hevige ruzie de stilte doorbreken',
    description: 'Neem initiatief om de stilte na een grote ruzie met je tiener te doorbreken.',
    instructions: [
      'Na een hevige ruzie waarbij jullie beiden zijn gestopt met praten: neem de eerste stap.',
      'Stuur een berichtje of klop aan de deur: "Ik wil praten als jij er klaar voor bent."',
      'Maak geen eisen. Wacht op de respons.',
      'Als ze reageren: luister eerst voordat je spreekt.',
    ],
    reflection: 'De eerste stap zetten na een ruzie met een tiener is moeilijk. Maar het modelt moed.',
    scienceNote: 'Ouders die de stilte doorbreken na conflicten met tieners bouwen sterkere band dan ouders die wachten (Laursen et al., 1998).',
    durationMin: 15,
  },
  {
    id: 'hers_1316_13',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Herstel na vertrouwensbreuk',
    description: 'Werk aan het herstellen van vertrouwen na een moment waarbij je je tiener teleurstelde.',
    instructions: [
      'Erken de vertrouwensbreuk: wat deed je dat het vertrouwen beschadigde?',
      'Bespreek het met je tiener: "Ik begrijp dat ik jouw vertrouwen heb beschadigd door..."',
      'Vraag: "Wat heb jij nodig om mij weer te kunnen vertrouwen?"',
      'Kom de afspraken na – zwijgend en consistent.',
    ],
    reflection: 'Vertrouwen herstellen bij een tiener vraagt geduld en consistentie over weken of maanden.',
    scienceNote: 'Tieners die vertrouwen in ouders herstelden gaan beter om met latere relatieproblemen (Ruhl et al., 2015).',
    durationMin: 20,
  },
  {
    id: 'hers_1316_14',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Jouw eigen emoties na een conflict',
    description: 'Verwerk jouw eigen emoties na een heftig conflict met je tiener.',
    instructions: [
      'Na een conflict: ga even alleen. Noteer wat je voelde (boosheid, pijn, schaamte, angst).',
      'Vraag jezelf: welke van die gevoelens zijn over mijn kind, welke zijn over mezelf?',
      'Welke onvervulde behoefte zit er onder jouw reactie?',
      'Als je dat weet: ga het gesprek aan vanuit die behoefte, niet vanuit de boosheid.',
    ],
    reflection: 'Je eigen emoties eerst verwerken maakt je een effectievere hersteller van conflicten.',
    scienceNote: 'Emotionele verwerking voor herstelgesprekken verhoogt de kwaliteit en het succes van dat herstel (Gottman, 1994).',
    durationMin: 15,
  },
  {
    id: 'hers_1316_15',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Nieuwe afspraken maken na een patroon van conflict',
    description: 'Breek een herhaald conflictpatroon door samen nieuwe afspraken te maken.',
    instructions: [
      'Identificeer een terugkerend conflict (bijv. over vrijheid, schermtijd, huiswerk).',
      'Vraag je tiener: "Hoe kunnen wij samen dit conflict voorkomen?"',
      'Luister serieus naar hun voorstellen.',
      'Maak samen drie concrete afspraken en schrijf ze op.',
    ],
    reflection: 'Herhalende conflicten stoppen niet vanzelf. Ze vragen bewuste afspraken van beide kanten.',
    scienceNote: 'Collaboratieve conflictresolutie bij tieners verhoogt autonomiegevoel en verlaagt conflictfrequentie (Smetana et al., 2006).',
    durationMin: 20,
  },
  {
    id: 'hers_1316_16',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'De relatie opnieuw uitvinden',
    description: 'Ontdek samen met je tiener hoe jullie relatie eruit kan zien nu hij/zij ouder wordt.',
    instructions: [
      'Plan een activiteit die jullie allebei leuk vinden maar die jullie al een tijdje niet deden.',
      'Observeer: hoe is de dynamiek veranderd nu je tiener ouder is?',
      'Vraag: "Hoe wil jij dat wij omgaan met elkaar als je ouder wordt?"',
      'Deins niet terug voor eerlijkheid – ook als het antwoord moeilijk is.',
    ],
    reflection: 'De vader-tiener relatie vraagt continue uitvinding naarmate het kind groeit.',
    scienceNote: 'Vaderrelaties die actief worden bijgesteld aan de groeiende tiener zijn veerkrachtiger en positiever (Laursen & Collins, 2009).',
    durationMin: 60,
  },
  {
    id: 'hers_1316_17',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Thuis als veilige haven herstellen',
    description: 'Maak thuis opnieuw tot een veilige plek voor je tiener als dat verloren is gegaan.',
    instructions: [
      'Vraag jezelf eerlijk: voelt mijn tiener zich thuis veilig en welkom?',
      'Als het antwoord twijfelachtig is: wat draagt bij aan onveiligheid?',
      'Bedenk drie concrete acties om de sfeer thuis te verbeteren.',
      'Voer die acties uit en vraag na een maand aan je tiener: "Hoe voelt het thuis voor jou?"',
    ],
    reflection: 'Thuis moet de veiligste plek ter wereld zijn voor je tiener. Als dat niet zo is, vraagt het actie.',
    scienceNote: 'Thuisveiligheid is de sterkste buffer voor tieners tegen depressie, angst en risicovol gedrag (Resnick et al., 1997).',
    durationMin: 30,
  },
  {
    id: 'hers_1316_18',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Herstel van afwezigheid',
    description: 'Als je een periode fysiek of emotioneel afwezig was: bouw bewust aan herstel.',
    instructions: [
      'Erken eerlijk: was ik er de afgelopen maanden voor mijn tiener?',
      'Bespreek de afwezigheid met je tiener: "Ik heb me gerealiseerd dat ik er niet genoeg voor je was."',
      'Vraag: "Hoe heeft dat voor jou gevoeld?"',
      'Maak een concreet plan om aanweziger te zijn – en houdt het vol.',
    ],
    reflection: 'Afwezigheid erkennen en herstellen is moediger dan doen alsof er niets is.',
    scienceNote: 'Vaders die afwezigheid benoemen en herstellen, versterken de gehechtheid meer dan vaders die er niets over zeggen (Lamb, 2010).',
    durationMin: 30,
  },
  {
    id: 'hers_1316_19',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Een positief einde van de dag',
    description: 'Eindig de dag positief met je tiener, ook na een moeizame dag.',
    instructions: [
      'Zoek je tiener op voor het slapengaan (ook al trekt hij/zij zich terug).',
      'Zeg een simpele, warme zin: "Welterusten. Ik hou van je."',
      'Forceer geen gesprek. Aanwezigheid is genoeg.',
      'Doe dit elke avond, ook na moeilijke dagen.',
    ],
    reflection: 'Zelfs na een ruzie: een warm welterusten houdt de deur open.',
    scienceNote: 'Dagelijkse positieve contact-momenten zijn cruciaal voor tieners om zich geliefd te voelen – ook tijdens conflict (Steinberg, 2001).',
    durationMin: 5,
  },
  {
    id: 'hers_1316_20',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Wat heeft mijn tiener nodig om te herstellen?',
    description: 'Vraag je tiener wat hij/zij nodig heeft na een conflict of moeilijke periode.',
    instructions: [
      'Ga naar je tiener toe op een rustig moment.',
      'Vraag: "Wat heb jij nodig om dit achter ons te laten?"',
      'Luister zonder te onderbreken of te oordelen.',
      'Geef wat gevraagd wordt als dat mogelijk is.',
    ],
    reflection: 'Tieners weten vaak wat ze nodig hebben. Vragen en luisteren is het moedigste wat een vader kan doen.',
    scienceNote: 'Tieners wiens behoeften na conflict erkend worden, herstellen sneller en vertrouwen hun ouders meer (Smetana, 2011).',
    durationMin: 15,
  },
];
