import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_20: InteractiveTask[] = [
  // ═══════════════════════════════════════════════════════════════
  // AUTONOMIE – 25 taken
  // ═══════════════════════════════════════════════════════════════

  // ── Autonomie 6-9 (5 taken: 2 basis, 2 gevorderd, 1 expert) ──

  {
    id: 'auto_69_51',
    skill: 'Autonomie',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Zelf de schooltas inpakken',
    description: 'Help je kind om zelfstandig zijn of haar schooltas klaar te maken voor de volgende dag.',
    instructions: [
      'Maak samen een checklist van wat er elke dag in de tas moet (boeken, etui, brood, drinken).',
      'Hang de checklist op een zichtbare plek bij de schooltas.',
      'Laat je kind vanavond de tas zelf inpakken met de checklist erbij.',
      'Controleer samen achteraf en geef een compliment over wat goed ging.',
    ],
    reflection: 'Door een hulpmiddel (checklist) te geven in plaats van het over te nemen, leer je je kind dat het zelf competent is.',
    scienceNote: 'Autonomie-ondersteunend ouderschap vergroot het gevoel van competentie en intrinsieke motivatie bij kinderen (Deci & Ryan, 2000).',
    durationMin: 10,
  },
  {
    id: 'auto_69_52',
    skill: 'Autonomie',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Keuzemenu voor het avondeten',
    description: 'Geef je kind de kans om mee te beslissen over het avondeten door een keuze te bieden.',
    instructions: [
      'Bedenk twee of drie opties voor het avondeten die je allebei prima vindt.',
      'Presenteer de keuzes aan je kind: "Wil je vanavond pasta, rijst of pannenkoeken?"',
      'Accepteer de keuze zonder commentaar of sturing.',
      'Betrek je kind bij de voorbereiding van het gekozen gerecht.',
    ],
    reflection: 'Keuzevrijheid binnen veilige grenzen geeft kinderen het gevoel dat hun mening ertoe doet.',
    scienceNote: 'Beperkte keuzemogelijkheden bieden past bij de cognitieve ontwikkeling van 6-9-jarigen en voorkomt keuzestress (Iyengar & Lepper, 2000).',
    durationMin: 5,
  },
  {
    id: 'auto_69_53',
    skill: 'Autonomie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Huiswerk zonder hulp starten',
    description: 'Oefen met je kind om zelfstandig aan het huiswerk te beginnen, zonder dat jij het initiatief neemt.',
    instructions: [
      'Spreek samen een vast huiswerktijdstip af (bijv. na het fruit eten).',
      'Zeg bij het tijdstip alleen: "Het is huiswerktijd" – geef geen verdere instructies.',
      'Ga zelf iets anders doen in dezelfde ruimte (lezen, administratie).',
      'Wacht tot je kind zelf begint. Help pas als je kind er expliciet om vraagt.',
    ],
    reflection: 'Het is verleidelijk om te sturen, maar wachten leert je kind zelf verantwoordelijkheid te nemen voor schoolwerk.',
    scienceNote: 'Ouderlijke controle over huiswerk is geassocieerd met lagere intrinsieke motivatie en prestaties (Pomerantz, Moorman & Litwack, 2007).',
    durationMin: 15,
  },
  {
    id: 'auto_69_54',
    skill: 'Autonomie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Eigen conflict oplossen',
    description: 'Begeleid je kind om een ruzie met een vriend(je) zelf op te lossen in plaats van in te grijpen.',
    instructions: [
      'Als je kind vertelt over een conflict met een vriendje, luister dan eerst volledig zonder advies.',
      'Vraag: "Wat zou jij kunnen doen om het op te lossen?"',
      'Laat je kind minstens twee eigen oplossingen bedenken.',
      'Moedig je kind aan om morgen een van die oplossingen te proberen, en bespreek later hoe het ging.',
    ],
    reflection: 'Door niet direct in te grijpen geef je je kind het vertrouwen dat het sociale problemen zelf aankan.',
    scienceNote: 'Kinderen die zelf conflictoplossingsstrategieën oefenen ontwikkelen sterkere sociale competenties (Shure & Spivack, 1982).',
    durationMin: 10,
  },
  {
    id: 'auto_69_55',
    skill: 'Autonomie',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Een ochtend zonder aanwijzingen',
    description: 'Laat je kind een complete ochtend zelfstandig doorlopen zonder dat jij stappen benoemt.',
    instructions: [
      'Maak de avond ervoor samen een visueel ochtendroutinebord (tekeningen of foto\'s van elke stap).',
      'Sta de volgende ochtend bewust op de achtergrond – geef geen verbale aanwijzingen.',
      'Observeer waar je kind vastloopt en noteer dit voor jezelf.',
      'Bespreek na school hoe de ochtend ging en pas het bord samen aan als dat nodig is.',
    ],
    reflection: 'Loslaten van de ochtendregie is moeilijk, maar het leert je kind zelfstandig zijn dag te starten.',
    scienceNote: 'Visuele routineschema\'s ondersteunen executieve functies en zelfregulerend gedrag bij basisschoolkinderen (Dawson & Guare, 2010).',
    durationMin: 20,
  },

  // ── Autonomie 10-12 (10 taken: 4 basis, 4 gevorderd, 2 expert) ──

  {
    id: 'auto_1012_51',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Eigen weekplanning maken',
    description: 'Laat je kind zelf een weekplanning maken voor school, sport en vrije tijd.',
    instructions: [
      'Geef je kind een leeg weekoverzicht (papier of digitaal).',
      'Laat het zelf invullen: schooltijden, huiswerk, sport, afspraken en vrije tijd.',
      'Bekijk de planning samen en stel alleen vragen, geen correcties.',
      'Evalueer aan het einde van de week samen wat goed ging en wat beter kan.',
    ],
    reflection: 'Een eigen planning leren maken is een vaardigheid die je kind zijn hele leven nodig zal hebben.',
    scienceNote: 'Zelfregulatie en planningsvaardigheden ontwikkelen zich sterk tussen 10 en 12 jaar door rijping van de prefrontale cortex (Diamond, 2013).',
    durationMin: 15,
  },
  {
    id: 'auto_1012_52',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Zelf boodschappen doen',
    description: 'Laat je kind een klein boodschappenlijstje zelfstandig afhandelen in de supermarkt.',
    instructions: [
      'Maak samen een kort boodschappenlijstje (5-7 producten).',
      'Geef je kind het juiste bedrag of een pinpas en leg de verwachting uit.',
      'Laat je kind zelfstandig de boodschappen zoeken en afrekenen – wacht buiten of bij de ingang.',
      'Bespreek achteraf hoe het ging en wat je kind ervan vond.',
    ],
    reflection: 'Vertrouwen geven in alledaagse taken laat je kind ervaren dat het de wereld aankan.',
    scienceNote: 'Geleidelijke blootstelling aan zelfstandige taken buiten het gezin versterkt het gevoel van "industry" in Eriksons ontwikkelingsfase (Erikson, 1963).',
    durationMin: 15,
  },
  {
    id: 'auto_1012_53',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Eigen kleding kiezen',
    description: 'Laat je kind een volledige week zelf bepalen wat het aantrekt, zonder jouw commentaar.',
    instructions: [
      'Kondig aan dat je kind deze week zelf mag kiezen wat het draagt.',
      'Geef alleen de randvoorwaarden: schoon, passend bij het weer, geschikt voor school.',
      'Houd je commentaar in als de combinatie niet jouw smaak is.',
      'Geef aan het einde van de week een compliment over de zelfstandigheid.',
    ],
    reflection: 'Kledingkeuze lijkt klein, maar het is voor kinderen een belangrijke manier om identiteit te verkennen.',
    scienceNote: 'Autonomie in dagelijkse keuzes draagt bij aan identiteitsontwikkeling in de pre-puberteit (Nucci, 2001).',
    durationMin: 5,
  },
  {
    id: 'auto_1012_54',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Zelf een afspraak maken',
    description: 'Laat je kind zelf bellen of mailen om een afspraak te maken (tandarts, kapper of speelafspraak).',
    instructions: [
      'Kies samen een geschikte afspraak die je kind zelf kan regelen.',
      'Oefen vooraf wat je kind kan zeggen – maak eventueel een kort script.',
      'Laat je kind zelf bellen of het berichtje sturen.',
      'Bespreek achteraf hoe het voelde en wat goed ging.',
    ],
    reflection: 'Zelf een telefoontje plegen is voor veel kinderen spannend, maar het geeft enorm veel zelfvertrouwen.',
    scienceNote: 'Het oefenen van sociale vaardigheden in gestructureerde situaties versterkt zelfeffectiviteit (Bandura, 1997).',
    durationMin: 10,
  },
  {
    id: 'auto_1012_55',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Eigen geld beheren',
    description: 'Help je kind om een eenvoudig systeem op te zetten voor het beheren van zakgeld.',
    instructions: [
      'Bespreek samen hoeveel zakgeld je kind krijgt en wanneer.',
      'Introduceer drie potjes: uitgeven, sparen en weggeven.',
      'Laat je kind zelf beslissen hoe het geld wordt verdeeld.',
      'Check na twee weken samen hoe het gaat – zonder oordeel over de keuzes.',
    ],
    reflection: 'Fouten maken met geld op jonge leeftijd is veel goedkoper en leerzamer dan op latere leeftijd.',
    scienceNote: 'Financiële geletterdheid op jonge leeftijd ontwikkelt zich het best door eigen ervaring en reflectie (Lusardi, 2015).',
    durationMin: 15,
  },
  {
    id: 'auto_1012_56',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Omgaan met een slecht cijfer',
    description: 'Begeleid je kind om zelf een plan te maken na een teleurstellend schoolresultaat.',
    instructions: [
      'Als je kind thuiskomt met een slecht cijfer, reageer eerst met empathie: "Dat is balen."',
      'Vraag: "Hoe komt het denk je?" – luister zonder te corrigeren.',
      'Vraag: "Wat zou je de volgende keer anders kunnen doen?"',
      'Laat je kind zelf een verbeterplan bedenken en schrijf het samen op.',
    ],
    reflection: 'Een vader die niet straft bij een slecht cijfer maar coacht bij het oplossingsproces, bouwt veerkracht.',
    scienceNote: 'Een growth mindset wordt versterkt wanneer ouders het proces benadrukken in plaats van het resultaat (Dweck, 2006).',
    durationMin: 10,
  },
  {
    id: 'auto_1012_57',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Zelf de weg vinden',
    description: 'Laat je kind op een bekende route zelfstandig de weg wijzen of navigeren.',
    instructions: [
      'Kies een bekende route (naar school, sportclub of opa en oma).',
      'Geef je kind de rol van navigator – het bepaalt waar je heen gaat.',
      'Grijp niet in, ook als het een omweg maakt.',
      'Bespreek achteraf: "Hoe wist je de weg? Wat deed je toen je twijfelde?"',
    ],
    reflection: 'Ruimtelijke onafhankelijkheid is een belangrijk onderdeel van groeiend zelfvertrouwen op deze leeftijd.',
    scienceNote: 'Zelfstandige mobiliteit bij kinderen is geassocieerd met hogere niveaus van fysieke activiteit en onafhankelijkheid (Schoeppe et al., 2013).',
    durationMin: 15,
  },
  {
    id: 'auto_1012_58',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Verantwoordelijkheid voor een huisdier',
    description: 'Geef je kind een week lang de volledige verantwoordelijkheid voor de verzorging van het huisdier.',
    instructions: [
      'Bespreek samen welke taken erbij horen: voeren, water geven, uitlaten of kooi schoonmaken.',
      'Maak een schema en hang het op een zichtbare plek.',
      'Herinner niet actief – laat je kind zelf onthouden.',
      'Evalueer aan het eind van de week samen en bespreek wat je kind heeft geleerd over verantwoordelijkheid.',
    ],
    reflection: 'Een levend wezen verzorgen leert je kind dat verantwoordelijkheid niet stopt als het niet leuk meer is.',
    scienceNote: 'Zorgtaken voor dieren bevorderen empathie en verantwoordelijkheidsgevoel bij kinderen in de latentieperiode (Melson, 2003).',
    durationMin: 10,
  },
  {
    id: 'auto_1012_59',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Een eigen project opzetten',
    description: 'Begeleid je kind bij het bedenken, plannen en uitvoeren van een eigen project.',
    instructions: [
      'Vraag je kind: "Als je iets mocht maken, organiseren of uitzoeken, wat zou het zijn?"',
      'Help met het structureren in stappen: wat, wanneer, wat heb je nodig?',
      'Laat je kind het project zelfstandig uitvoeren over meerdere dagen – bied alleen hulp als daarom gevraagd wordt.',
      'Vier het eindresultaat samen, ongeacht de kwaliteit – het gaat om het proces.',
    ],
    reflection: 'Een eigen project van begin tot eind doorlopen leert doorzettingsvermogen en planvaardigheden die geen schoolopdracht kan evenaren.',
    scienceNote: 'Projectmatig leren bevordert intrinsieke motivatie, probleemoplossend vermogen en executieve functies (Hmelo-Silver, 2004).',
    durationMin: 20,
  },
  {
    id: 'auto_1012_60',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Loslaten van het schoolrapport',
    description: 'Oefen met het niet-reageren op het schoolrapport en laat je kind zelf reflecteren.',
    instructions: [
      'Wanneer je kind het rapport meebrengt, zeg alleen: "Vertel eens, hoe vind je het zelf?"',
      'Luister naar de zelfreflectie zonder eigen oordeel of vergelijking toe te voegen.',
      'Vraag: "Waar ben je trots op? Wat wil je verbeteren?"',
      'Sluit af met: "Ik ben trots op wie je bent, niet alleen op je cijfers."',
    ],
    reflection: 'Het rapport is van je kind, niet van jou. Door los te laten geef je de boodschap dat prestaties niet de waarde van je kind bepalen.',
    scienceNote: 'Onvoorwaardelijke positieve aandacht van ouders beschermt het zelfbeeld bij academische tegenslagen (Rogers, 1961; Harter, 1999).',
    durationMin: 10,
  },

  // ── Autonomie 13-16 (10 taken: 4 basis, 4 gevorderd, 2 expert) ──

  {
    id: 'auto_1316_51',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Privacy respecteren',
    description: 'Oefen met het respecteren van de privéruimte van je tiener zonder controledrang.',
    instructions: [
      'Klop voortaan altijd op de deur van je tieners kamer voordat je binnengaat.',
      'Wacht op een reactie voordat je de deur opent.',
      'Vraag niet door als je tiener zegt "niks" wanneer je vraagt wat hij/zij doet.',
      'Bespreek aan het eind van de week hoe je tiener het ervaren heeft.',
    ],
    reflection: 'Privacy respecteren is geen afstand nemen – het is laten zien dat je je tiener vertrouwt.',
    scienceNote: 'Respect voor privacy in de adolescentie is geassocieerd met een betere ouder-kindrelatie en minder geheimhouding (Hawk et al., 2009).',
    durationMin: 5,
  },
  {
    id: 'auto_1316_52',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Eigen bedtijd bepalen',
    description: 'Geef je tiener de vrijheid om zelf een passende bedtijd te kiezen, binnen afgesproken grenzen.',
    instructions: [
      'Bespreek samen waarom slaap belangrijk is – deel feiten, geen regels.',
      'Vraag: "Welke bedtijd denk je dat goed voor je is op schooldagen?"',
      'Accepteer het voorstel als het redelijk is – onderhandel alleen bij extreme keuzes.',
      'Evalueer na twee weken: "Hoe voel je je bij deze bedtijd? Ben je uitgerust genoeg?"',
    ],
    reflection: 'Door mee te laten beslissen over bedtijd leert je tiener luisteren naar zijn eigen lichaam in plaats van te rebelleren tegen jouw regels.',
    scienceNote: 'Autonomie-ondersteunende slaapregulatie leidt tot betere slaaphygiëne bij adolescenten dan rigide controle (Meijer et al., 2010).',
    durationMin: 10,
  },
  {
    id: 'auto_1316_53',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Zelf een probleem met school oplossen',
    description: 'Laat je tiener zelf het initiatief nemen bij een schoolprobleem in plaats van het over te nemen.',
    instructions: [
      'Als je tiener klaagt over een leraar, cijfer of situatie op school, luister dan eerst empathisch.',
      'Vraag: "Wat denk je dat je zelf zou kunnen doen?"',
      'Bied aan om te sparren, maar laat de actie bij je tiener.',
      'Vraag de volgende dag hoe het is gegaan – zonder druk.',
    ],
    reflection: 'Niet ingrijpen wanneer je kind het zelf kan is een van de moeilijkste maar belangrijkste vaardigheden van een vader.',
    scienceNote: 'Helikopterouderschap bij adolescenten ondermijnt zelfeffectiviteit en probleemoplossend vermogen (Schiffrin et al., 2014).',
    durationMin: 10,
  },
  {
    id: 'auto_1316_54',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Mening zonder oordeel aanhoren',
    description: 'Oefen met het aanhoren van een mening van je tiener waarmee je het oneens bent, zonder te corrigeren.',
    instructions: [
      'Kies een geschikt moment en vraag je tiener naar zijn/haar mening over een actueel onderwerp.',
      'Luister zonder te onderbreken, ook als je het er niet mee eens bent.',
      'Stel verdiepende vragen: "Hoe kom je daarbij? Wat vind je het belangrijkst?"',
      'Sluit af met: "Ik vind het knap dat je daar zo over nadenkt" – ook als je mening anders is.',
    ],
    reflection: 'Een tiener die merkt dat papa luistert zonder te oordelen, zal vaker zijn gedachten durven delen.',
    scienceNote: 'Psychologische controle (het afwijzen van de mening van adolescenten) is geassocieerd met depressieve symptomen en lager welzijn (Barber, 1996).',
    durationMin: 10,
  },
  {
    id: 'auto_1316_55',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Schermtijdafspraken onderhandelen',
    description: 'Onderhandel samen met je tiener over schermtijdregels in plaats van ze eenzijdig op te leggen.',
    instructions: [
      'Begin het gesprek met: "Ik wil samen met jou afspraken maken over schermtijd die voor ons allebei werken."',
      'Luister naar het perspectief van je tiener: waarom is het scherm belangrijk voor hem/haar?',
      'Zoek samen een compromis: welke tijden zijn oké, wanneer niet?',
      'Leg de afspraken vast en evalueer na een maand samen of ze werken.',
    ],
    reflection: 'Regels die samen zijn gemaakt worden beter nageleefd dan regels die zijn opgelegd.',
    scienceNote: 'Gezamenlijke regelvorming verhoogt de naleving en acceptatie van regels bij adolescenten (Smetana, 2011).',
    durationMin: 15,
  },
  {
    id: 'auto_1316_56',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Fouten laten maken',
    description: 'Oefen bewust met het toestaan dat je tiener een voorspelbare fout maakt, zodat het kan leren.',
    instructions: [
      'Identificeer een situatie waarin je tiener een keuze maakt waarvan jij denkt dat het niet goed afloopt (geen gevaarlijke situatie).',
      'Deel je bezorgdheid kort: "Ik denk dat dit misschien niet gaat werken, maar het is jouw keuze."',
      'Laat je tiener de keuze maken en de gevolgen ervaren.',
      'Bespreek achteraf zonder "ik had het toch gezegd": "Wat heb je ervan geleerd?"',
    ],
    reflection: 'De beste lessen komen uit eigen ervaringen. "Ik had het toch gezegd" is de meest nutteloze zin in het ouderschap.',
    scienceNote: 'Ervaringsleren door natuurlijke consequenties is effectiever dan straffen of waarschuwen voor gedragsverandering bij tieners (Dreikurs & Soltz, 1964).',
    durationMin: 10,
  },
  {
    id: 'auto_1316_57',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Eigen sociale keuzes vertrouwen',
    description: 'Laat je tiener zelf kiezen met wie hij/zij omgaat, ook als je twijfels hebt over een vriendschap.',
    instructions: [
      'Merk op wanneer je een oordeel hebt over een vriend(in) van je tiener.',
      'Stel open vragen in plaats van te waarschuwen: "Wat vind je leuk aan die vriendschap?"',
      'Deel je observatie als een ik-boodschap: "Ik merk dat ik me soms zorgen maak – mag ik vertellen waarom?"',
      'Respecteer het antwoord van je tiener, ook als het niet overeenkomt met jouw wens.',
    ],
    reflection: 'Vriendschappen verbieden maakt ze aantrekkelijker. Vertrouwen geven maakt je tiener kritischer in eigen keuzes.',
    scienceNote: 'Ouderlijke afkeuring van vriendschappen kan het "Romeo en Julia-effect" versterken bij adolescenten (Driscoll, Davis & Lipetz, 1972).',
    durationMin: 10,
  },
  {
    id: 'auto_1316_58',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Toekomstplannen verkennen',
    description: 'Ondersteun je tiener bij het verkennen van toekomstplannen zonder je eigen ambities te projecteren.',
    instructions: [
      'Vraag op een ontspannen moment: "Waar droom je weleens over als het gaat om later?"',
      'Luister zonder te sturen richting jouw idee van een goede toekomst.',
      'Stel verdiepende vragen: "Wat trekt je daarin aan? Hoe zou dat eruitzien?"',
      'Sluit af met: "Ik vind het gaaf dat je daar zo over nadenkt. Ik ondersteun je daarin."',
    ],
    reflection: 'De toekomst van je kind is van je kind. Jouw rol is aanmoedigen, niet sturen.',
    scienceNote: 'Identiteitsexploratie met ouderlijke ondersteuning leidt tot een volgroeide identiteitsstatus en hoger welzijn (Marcia, 1966; Luyckx et al., 2008).',
    durationMin: 15,
  },
  {
    id: 'auto_1316_59',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Je eigen controledrang onderzoeken',
    description: 'Reflecteer eerlijk op momenten waarop jouw behoefte aan controle de autonomie van je tiener in de weg staat.',
    instructions: [
      'Schrijf drie situaties op waarin je de afgelopen week controle uitoefende over je tiener (kleding, huiswerk, vrienden, schermtijd).',
      'Vraag jezelf bij elke situatie: "Was dit werkelijk nodig, of was dit mijn angst?"',
      'Kies één situatie waarin je morgen bewust loslaat.',
      'Observeer wat er gebeurt als je loslaat – schrijf je bevindingen op.',
    ],
    reflection: 'Controle voelt als veiligheid, maar voor je tiener voelt het als wantrouwen. Loslaten begint bij jezelf.',
    scienceNote: 'Ouderlijke psychologische controle is een van de sterkste voorspellers van internaliserende problemen bij adolescenten (Soenens & Vansteenkiste, 2010).',
    durationMin: 15,
  },
  {
    id: 'auto_1316_60',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Een moeilijk gesprek door je tiener laten leiden',
    description: 'Laat je tiener een lastig familiegesprek leiden over een onderwerp dat hem/haar raakt.',
    instructions: [
      'Vraag je tiener of er een onderwerp is dat hij/zij graag wil bespreken met het gezin.',
      'Laat je tiener het gesprek voorbereiden: wanneer, met wie, en wat wil hij/zij zeggen?',
      'Neem tijdens het gesprek een ondersteunende maar niet-leidende rol aan.',
      'Reflecteer samen achteraf: "Hoe voelde het om dit te leiden? Wat heb je geleerd over jezelf?"',
    ],
    reflection: 'Een tiener die ervaart dat zijn stem gehoord wordt in het gezin, leert dat assertiviteit werkt.',
    scienceNote: 'Participatie in gezinsbeslissingen bevordert de ontwikkeling van prosociaal gedrag en democratische waarden bij adolescenten (Yates & Youniss, 1996).',
    durationMin: 20,
  },

  // ═══════════════════════════════════════════════════════════════
  // VERBINDING – 25 taken
  // ═══════════════════════════════════════════════════════════════

  // ── Verbinding 6-9 (9 taken: 3 basis, 3 gevorderd, 3 expert) ──

  {
    id: 'verb_69_51',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Vijf minuten onverdeelde aandacht',
    description: 'Geef je kind vijf minuten volledig onverdeelde aandacht zonder afleiding.',
    instructions: [
      'Leg je telefoon weg, zet de TV uit en ga op ooghoogte bij je kind zitten.',
      'Zeg: "Ik heb vijf minuten helemaal voor jou. Wat wil je doen?"',
      'Doe wat je kind voorstelt – volg volledig de leiding van je kind.',
      'Sluit af met: "Ik vond dit fijn. Wat vond jij het leukst?"',
    ],
    reflection: 'Vijf minuten echte aandacht is meer waard dan een uur halfbakken aanwezigheid.',
    scienceNote: 'Dagelijkse momenten van onverdeelde aandacht versterken de hechtingsband en het gevoel van veiligheid bij kinderen (Gottman, 1997).',
    durationMin: 5,
  },
  {
    id: 'verb_69_52',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen een verhaal bedenken',
    description: 'Verzin samen met je kind een verhaal voordat het gaat slapen.',
    instructions: [
      'Vraag je kind: "Over wie zal ons verhaal vanavond gaan?"',
      'Begin het verhaal met één zin en laat je kind de volgende zin bedenken.',
      'Wissel om de beurt af en bouw samen het verhaal op.',
      'Eindig met: "En toen leefden ze nog lang en gelukkig – einde!" en geef een knuffel.',
    ],
    reflection: 'Samen verhalen bedenken creëert een gedeelde wereld die alleen van jullie tweeën is.',
    scienceNote: 'Gezamenlijk narratief spel versterkt de ouder-kindband en stimuleert de taalontwikkeling (Fivush et al., 2006).',
    durationMin: 10,
  },
  {
    id: 'verb_69_53',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Het hoog-laag-spel bij het avondeten',
    description: 'Deel samen de hoogtepunten en dieptepunten van jullie dag tijdens het eten.',
    instructions: [
      'Stel bij het avondeten de vraag: "Wat was het leukste van je dag?"',
      'Vraag daarna: "Was er ook iets dat minder leuk was?"',
      'Deel zelf ook jouw hoogte- en dieptepunt – wees eerlijk en kwetsbaar op kindniveau.',
      'Sluit af met: "Bedankt dat je het met me deelde."',
    ],
    reflection: 'Door zelf ook kwetsbaar te zijn laat je je kind zien dat het delen van gevoelens normaal is.',
    scienceNote: 'Gezamenlijke dagelijkse rituelen zoals het delen van ervaringen versterken de emotionele verbinding en het welzijn van kinderen (Fiese et al., 2002).',
    durationMin: 10,
  },
  {
    id: 'verb_69_54',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Papa-kind date',
    description: 'Plan een speciaal één-op-één uitje met je kind dat volledig draait om jullie verbinding.',
    instructions: [
      'Vraag je kind een paar dagen van tevoren: "Als wij samen iets leuks zouden doen, wat zou jij willen?"',
      'Plan het uitje samen – laat je kind zoveel mogelijk meebeslissen.',
      'Tijdens het uitje: geen telefoon, geen haast, volledige aanwezigheid.',
      'Maak er een traditie van: spreek de volgende date al af.',
    ],
    reflection: 'Eén-op-één tijd communiceert iets wat woorden niet kunnen: "Jij bent het waard om apart tijd voor vrij te maken."',
    scienceNote: 'Individuele vader-kindtijd is een unieke voorspeller van emotionele veiligheid, onafhankelijk van de totale tijd samen (Pleck, 2010).',
    durationMin: 15,
  },
  {
    id: 'verb_69_55',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Emoties raden',
    description: 'Speel een spel waarbij jullie samen emoties herkennen en benoemen.',
    instructions: [
      'Zeg: "Ik ga een emotie voordoen met mijn gezicht – raad welke het is!"',
      'Doe een duidelijke emotie voor (blij, boos, bang, verdrietig, verrast).',
      'Wissel van rol: laat je kind emoties voordoen die jij moet raden.',
      'Bespreek: "Wanneer voelde jij je vandaag zo? En ik?"',
    ],
    reflection: 'Emoties herkennen is de eerste stap naar emoties begrijpen – bij jezelf en bij anderen.',
    scienceNote: 'Emotiecoaching door vaders versterkt de emotionele intelligentie en sociale vaardigheden van kinderen (Gottman, Katz & Hooven, 1996).',
    durationMin: 10,
  },
  {
    id: 'verb_69_56',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Samen iets repareren',
    description: 'Zoek iets in huis dat gerepareerd moet worden en doe het samen met je kind.',
    instructions: [
      'Loop samen door het huis en zoek iets dat gerepareerd of verbeterd kan worden.',
      'Leg uit wat je gaat doen en waarom – gebruik eenvoudige taal.',
      'Geef je kind een taak: iets vasthouden, gereedschap aangeven, meten.',
      'Bewonder samen het resultaat: "Dit hebben wij samen gedaan!"',
    ],
    reflection: 'Samen werken aan iets tastbaars schept een band die praten alleen niet kan bereiken.',
    scienceNote: 'Gezamenlijke doelgerichte activiteiten versterken de vaderband en het gevoel van competentie bij kinderen (Lamb, 2010).',
    durationMin: 15,
  },
  {
    id: 'verb_69_57',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Brief aan je kind',
    description: 'Schrijf een persoonlijke brief aan je kind over wat je bewondert en leg hem onder het kussen.',
    instructions: [
      'Pak pen en papier en schrijf een korte brief aan je kind.',
      'Benoem drie specifieke dingen die je bewondert: een karaktereigenschap, iets wat het deed, en iets grappigs.',
      'Leg de brief onder het kussen of in de schooltas.',
      'Als je kind erover begint, luister dan en geniet – leg uit dat je dit soms zult doen.',
    ],
    reflection: 'Een geschreven boodschap is een tastbaar bewijs van liefde dat je kind kan herlezen wanneer het dat nodig heeft.',
    scienceNote: 'Geschreven uitingen van affectie activeren het beloningssysteem en worden langer onthouden dan verbale uitingen (Schaefer & Emerson, 1964).',
    durationMin: 15,
  },
  {
    id: 'verb_69_58',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Je kind interviewen',
    description: 'Interview je kind als een journalist en stel vragen die je normaal niet zou stellen.',
    instructions: [
      'Pak een "microfoon" (lepel, banaan, afstandsbediening) en kondig aan: "Ik ga je interviewen!"',
      'Stel onverwachte vragen: "Als je één superpower had, welke?", "Wat maakt papa soms een beetje gek?"',
      'Luister aandachtig en stel doorvragen – lach samen.',
      'Schrijf de leukste antwoorden op en bewaar ze.',
    ],
    reflection: 'Speelse nieuwsgierigheid opent deuren die serieuze gesprekken gesloten houden.',
    scienceNote: 'Speelse interacties tussen vader en kind zijn uniek verbindend en bevorderen communicatieve openheid (Paquette, 2004).',
    durationMin: 15,
  },
  {
    id: 'verb_69_59',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Gedeeld geheim ritueel',
    description: 'Bedenk samen een geheim ritueel dat alleen van jullie tweeën is.',
    instructions: [
      'Zeg: "Zullen we iets bedenken dat alleen van ons is? Een geheim teken of ritueel?"',
      'Bedenk samen een speciaal handgebaar, codewoord of ritueel (bijv. een speciale handshake).',
      'Oefen het een paar keer samen tot het perfect is.',
      'Gebruik het vanaf nu bij begroeting, afscheid of als geheim teken in het openbaar.',
    ],
    reflection: 'Een gedeeld geheim creëert een onzichtbare draad tussen jullie die niemand anders kan zien.',
    scienceNote: 'Unieke ouder-kind rituelen versterken het gevoel van "belonging" en emotionele veiligheid (Spagnola & Fiese, 2007).',
    durationMin: 10,
  },

  // ── Verbinding 10-12 (8 taken: 3 basis, 3 gevorderd, 2 expert) ──

  {
    id: 'verb_1012_51',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen wandelen zonder doel',
    description: 'Ga samen een wandeling maken zonder bestemming of agenda – gewoon samen lopen.',
    instructions: [
      'Stel voor: "Zullen we een rondje lopen? Nergens naartoe, gewoon samen."',
      'Loop naast elkaar en laat het gesprek vanzelf komen – forceer niets.',
      'Als het stil is, geniet dan van de stilte – dat hoort erbij.',
      'Maak er een wekelijks moment van als het goed bevalt.',
    ],
    reflection: 'De beste gesprekken met kinderen van deze leeftijd ontstaan schouder aan schouder, niet oog in oog.',
    scienceNote: 'Zij-aan-zij activiteiten verlagen de drempel voor open communicatie bij pre-adolescenten, vooral met vaders (Palkovitz, 2002).',
    durationMin: 15,
  },
  {
    id: 'verb_1012_52',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Interesse tonen in hun wereld',
    description: 'Verdiep je oprecht in iets waar je kind enthousiast over is, ook als het jou niet interesseert.',
    instructions: [
      'Vraag je kind: "Vertel eens, wat vind je zo leuk aan [hun hobby/game/serie]?"',
      'Luister echt en stel doorvragen – doe alsof je er een artikel over moet schrijven.',
      'Probeer het zelf een keer: speel het spel mee, kijk een aflevering, of lees erover.',
      'Deel je ervaring: "Nu snap ik beter waarom je het zo leuk vindt."',
    ],
    reflection: 'Je hoeft niet alles leuk te vinden wat je kind leuk vindt – maar interesse tonen zegt: "Jij bent belangrijk voor mij."',
    scienceNote: 'Ouderlijke betrokkenheid bij de interesses van het kind is geassocieerd met hogere relationele tevredenheid en zelfwaardering (Grolnick & Slowiaczek, 1994).',
    durationMin: 15,
  },
  {
    id: 'verb_1012_53',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen koken',
    description: 'Kook samen een maaltijd van begin tot eind als gelijkwaardige partners.',
    instructions: [
      'Kies samen een recept dat jullie allebei lekker vinden.',
      'Verdeel de taken eerlijk: jij snijdt, je kind roert – of andersom.',
      'Praat tijdens het koken over van alles – het gesprek is belangrijker dan het eten.',
      'Eet samen op en bespreek: "Wat was het lekkerst? Wat maken we de volgende keer?"',
    ],
    reflection: 'Samen koken combineert samenwerking, gesprek en een tastbaar resultaat – een perfecte verbindingsactiviteit.',
    scienceNote: 'Gezamenlijke huishoudelijke activiteiten bevorderen prosociaal gedrag en versterken de ouder-kindrelatie (White & Dahl, 2006).',
    durationMin: 20,
  },
  {
    id: 'verb_1012_54',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Een jeugdherinnering delen',
    description: 'Deel een persoonlijke herinnering uit je eigen jeugd die relevant is voor wat je kind meemaakt.',
    instructions: [
      'Wacht op een natuurlijk moment waarin je kind iets deelt over school, vrienden of gevoelens.',
      'Zeg: "Weet je, toen ik zo oud was als jij, had ik ook zoiets..."',
      'Deel eerlijk – inclusief wat moeilijk was en hoe je je voelde.',
      'Vraag: "Herken je dat? Of is het bij jou anders?"',
    ],
    reflection: 'Door kwetsbaar te zijn over je eigen jeugd laat je je kind zien dat moeilijke gevoelens normaal zijn en voorbijgaan.',
    scienceNote: 'Ouderlijke zelfonthulling op leeftijdspassend niveau versterkt de emotionele band en normaliseert gevoelens (Buhrmester & Prager, 1995).',
    durationMin: 10,
  },
  {
    id: 'verb_1012_55',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Complimentendouche',
    description: 'Geef je kind in één gesprek vijf specifieke, eerlijke complimenten over wie het is.',
    instructions: [
      'Kies een rustig moment en zeg: "Ik wil je iets vertellen wat ik aan je bewonder."',
      'Geef vijf specifieke complimenten over karakter, niet over prestaties: "Ik bewonder hoe eerlijk je bent."',
      'Kijk je kind aan bij elk compliment.',
      'Vraag: "Welk compliment verraste je het meest?" en luister naar het antwoord.',
    ],
    reflection: 'Kinderen op deze leeftijd beginnen aan zichzelf te twijfelen. Een vader die zegt wat hij ziet, geeft een anker.',
    scienceNote: 'Specifieke karaktercomplimenten van vaders zijn sterker geassocieerd met een positief zelfbeeld dan generieke lof (Henderlong & Lepper, 2002).',
    durationMin: 10,
  },
  {
    id: 'verb_1012_56',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Film kijken en nabespreken',
    description: 'Kijk samen een film met een dieper thema en bespreek deze na.',
    instructions: [
      'Kies samen een film met een thema dat past bij de leeftijd (vriendschap, moed, verlies, eerlijkheid).',
      'Kijk de film samen – geen telefoons, samen op de bank.',
      'Bespreek na afloop: "Welk personage leek het meest op jou? Waarom?"',
      'Vraag: "Was er iets in de film dat je deed denken aan je eigen leven?"',
    ],
    reflection: 'Een film is een veilige omweg om over moeilijke thema\'s te praten zonder dat het te persoonlijk voelt.',
    scienceNote: 'Narratieve media bieden een veilig kader voor emotionele verwerking en gesprek, ook wel "narrative transportation" genoemd (Green & Brock, 2000).',
    durationMin: 15,
  },
  {
    id: 'verb_1012_57',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Emotionele check-in invoeren',
    description: 'Introduceer een wekelijks emotioneel check-in moment tussen jou en je kind.',
    instructions: [
      'Kies een vast moment in de week (bijv. zondagavond) voor jullie check-in.',
      'Gebruik drie vragen: "Hoe gaat het echt?", "Waar maak je je zorgen over?", "Wat heb je van mij nodig?"',
      'Deel ook jouw eigen antwoorden op deze vragen.',
      'Maak het tot een vaste gewoonte – consequentie is hier de sleutel.',
    ],
    reflection: 'Een vast moment voor echte gesprekken leert je kind dat emoties bespreekbaar zijn en dat papa altijd beschikbaar is.',
    scienceNote: 'Regelmatige emotionele check-ins bevorderen emotionele openheid en zijn beschermend tegen internaliserende problemen (Sameroff, 2009).',
    durationMin: 15,
  },
  {
    id: 'verb_1012_58',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Gezamenlijk dagboek',
    description: 'Start een gezamenlijk dagboek waarin jij en je kind om de beurt schrijven.',
    instructions: [
      'Koop een speciaal schrift en schrijf op de eerste pagina: "Dit is van ons. Hier schrijven we voor elkaar."',
      'Schrijf de eerste entry: een vraag, een herinnering, of iets wat je wilt delen.',
      'Leg het op een afgesproken plek – je kind schrijft terug wanneer het wil.',
      'Reageer altijd op wat je kind schrijft – laat het nooit onbeantwoord.',
    ],
    reflection: 'Sommige dingen zijn makkelijker op te schrijven dan hardop te zeggen. Dit dagboek wordt een schat.',
    scienceNote: 'Schriftelijke communicatie tussen ouder en kind biedt een veilig kanaal voor emotionele expressie, vooral voor kinderen die moeite hebben met verbale uitdrukking (Pennebaker, 1997).',
    durationMin: 15,
  },

  // ── Verbinding 13-16 (8 taken: 3 basis, 3 gevorderd, 2 expert) ──

  {
    id: 'verb_1316_51',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen autorijden',
    description: 'Gebruik autorijden als verbindingsmoment – de auto is een veilige plek voor gesprekken met tieners.',
    instructions: [
      'Bied aan om je tiener ergens naartoe te brengen in plaats van het openbaar vervoer.',
      'Zet de muziek zacht en begin met een luchtig onderwerp.',
      'Stel een open vraag: "Wat houdt je deze week bezig?"',
      'Luister meer dan je praat – de auto nodigt uit tot openheid omdat er geen oogcontact nodig is.',
    ],
    reflection: 'In de auto kijken jullie dezelfde kant op – letterlijk en figuurlijk. Dat maakt het veiliger om te praten.',
    scienceNote: 'Zij-aan-zij settings zoals autorijden verlagen de sociale druk en bevorderen open communicatie met adolescenten (Palkovitz, 2002).',
    durationMin: 10,
  },
  {
    id: 'verb_1316_52',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Belangstelling zonder agenda',
    description: 'Toon oprechte interesse in het leven van je tiener zonder een pedagogisch doel.',
    instructions: [
      'Stel vandaag drie vragen aan je tiener die niets met school of verplichtingen te maken hebben.',
      'Voorbeelden: "Welk nummer luister je veel?", "Wat is er grappig op social media?", "Waar lach je om met je vrienden?"',
      'Luister zonder oordeel of advies – lach mee, wees nieuwsgierig.',
      'Sluit af met: "Leuk om te horen" – zonder les te trekken.',
    ],
    reflection: 'Interesse zonder agenda laat je tiener merken dat je om hem/haar geeft als persoon, niet alleen als project.',
    scienceNote: 'Niet-intrusieve ouderlijke betrokkenheid is geassocieerd met meer vrijwillige zelfonthulling door adolescenten (Kerr & Stattin, 2000).',
    durationMin: 5,
  },
  {
    id: 'verb_1316_53',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Fysiek contact behouden',
    description: 'Zoek manieren om passend fysiek contact te behouden met je tiener, ook als die afstandelijker wordt.',
    instructions: [
      'Observeer welke vormen van fysiek contact je tiener nog accepteert (schouderklop, high five, arm om schouder).',
      'Gebruik die vorm vandaag bewust één keer.',
      'Respecteer het als je tiener zich terugtrekt – forceer niets.',
      'Bedenk een alternatief als aanraking lastig is: een vuistje, een knipoog, een "fist bump" bij de deur.',
    ],
    reflection: 'Tieners hebben nog steeds fysieke nabijheid nodig, maar op hun eigen voorwaarden. Jouw taak is beschikbaar blijven.',
    scienceNote: 'Passend fysiek contact van vaders blijft een belangrijke bron van emotionele regulatie in de adolescentie (Field, 2014).',
    durationMin: 5,
  },
  {
    id: 'verb_1316_54',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Kwetsbaarheid tonen als vader',
    description: 'Deel een moment van onzekerheid of kwetsbaarheid met je tiener op een passende manier.',
    instructions: [
      'Kies een geschikt moment en deel iets waar je mee worstelt (werk, een beslissing, een onzekerheid).',
      'Gebruik ik-taal: "Ik vond dat best spannend" of "Ik wist even niet wat ik moest doen."',
      'Vraag: "Herken je dat? Heb jij dat ook weleens?"',
      'Bedank je tiener als die reageert: "Fijn dat ik dit met je kan delen."',
    ],
    reflection: 'Een vader die kwetsbaar durft te zijn, leert zijn tiener dat kracht niet hetzelfde is als alles alleen doen.',
    scienceNote: 'Vaderkwetsbaarheid op passend niveau bevordert emotionele intimiteit en modelleert gezonde mannelijkheid voor adolescenten (Levant & Kopecky, 1995).',
    durationMin: 10,
  },
  {
    id: 'verb_1316_55',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Samen een uitdaging aangaan',
    description: 'Doe samen iets wat voor jullie allebei nieuw of spannend is.',
    instructions: [
      'Bedenk samen een activiteit die jullie allebei nog nooit hebben gedaan (klimmen, een nieuwe sport, een escape room, een gerecht uit een ander land koken).',
      'Plan het samen en voer het uit als gelijkwaardige partners – jij bent ook beginner.',
      'Lach om elkaars fouten en moedig elkaar aan.',
      'Bespreek achteraf: "Wat vond je het spannendst? Zullen we vaker iets nieuws proberen?"',
    ],
    reflection: 'Samen iets nieuws doen doorbreekt de ouder-kindrol en maakt jullie gelijkwaardige avonturiers.',
    scienceNote: 'Gedeelde nieuwe ervaringen activeren het dopaminesysteem en versterken sociale banden (Aron et al., 2000).',
    durationMin: 20,
  },
  {
    id: 'verb_1316_56',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Erkennen en valideren bij stress',
    description: 'Oefen met het valideren van de gevoelens van je tiener zonder het probleem te bagatelliseren of op te lossen.',
    instructions: [
      'Wacht op een moment dat je tiener stress, frustratie of verdriet toont.',
      'Zeg: "Dat klinkt echt zwaar" of "Ik snap dat je daar boos over bent."',
      'Vraag niet meteen "Wat kan ik doen?" – wacht of je tiener daar zelf om vraagt.',
      'Als je tiener niet om hulp vraagt, zeg dan: "Ik ben er als je me nodig hebt."',
    ],
    reflection: 'Soms wil je tiener geen oplossing maar erkenning. Dat onderscheid leren maken is cruciale vadervaardigheid.',
    scienceNote: 'Emotionele validatie door ouders is een beschermende factor tegen depressie en angst bij adolescenten (Linehan, 1993; Gottman, 1997).',
    durationMin: 5,
  },
  {
    id: 'verb_1316_57',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Herstellen na een conflict',
    description: 'Neem het initiatief om de verbinding te herstellen na een conflict met je tiener.',
    instructions: [
      'Wacht tot de emoties zijn gezakt (minstens een uur, maximaal een dag).',
      'Ga naar je tiener en zeg: "Ik wil het hebben over wat er eerder gebeurde."',
      'Neem verantwoordelijkheid voor jouw aandeel: "Het spijt me dat ik... Dat was niet oké."',
      'Vraag: "Hoe was dat voor jou? Wat heb je nodig van mij?"',
    ],
    reflection: 'Altijd als eerste herstellen is geen zwakte – het is leiderschap. Je tiener leert hiervan hoe relaties werken.',
    scienceNote: 'Herstelbewegingen na conflicten zijn de sterkste voorspeller van relatiekwaliteit, ook in ouder-kindrelaties (Gottman & Silver, 1999).',
    durationMin: 15,
  },
  {
    id: 'verb_1316_58',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Een brief aan je toekomstige tiener',
    description: 'Schrijf een brief aan je tiener die hij/zij pas over vijf jaar mag openen.',
    instructions: [
      'Schrijf een persoonlijke brief aan je tiener gericht aan zijn/haar toekomstige zelf (18, 19 of 21 jaar).',
      'Beschrijf wie je tiener nu is: eigenschappen, dromen, grappige gewoontes, en wat je bewondert.',
      'Deel wat je hoopt voor de toekomst – zonder verwachtingen, met liefde.',
      'Geef de brief in een gesloten envelop met de datum waarop die geopend mag worden.',
    ],
    reflection: 'Deze brief is een tijdcapsule van liefde. Over vijf jaar zal je tiener lezen hoe goed jij hem/haar kende.',
    scienceNote: 'Toekomstgerichte ouderlijke expressies van liefde en erkenning versterken de gehechtheidsrepresentatie en het zelfbeeld op lange termijn (Bowlby, 1988).',
    durationMin: 20,
  },
];
