import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_6: InteractiveTask[] = [
  // ═══════════════════════════════════════════════════════════════
  // GRENZEN (50 taken: 5 leeftijdsgroepen × 10 taken)
  // ═══════════════════════════════════════════════════════════════

  // ── Grenzen · 0-2 jaar ────────────────────────────────────────
  {
    id: "gren_02_01",
    title: "Nee zeggen zonder uitleg",
    skill: "Grenzen",
    description: "Zeg vandaag één keer 'nee' tegen je baby op een rustige, heldere toon — zonder uitgebreide uitleg. Kort, warm, duidelijk.",
    duration: "1 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Baby's van 8-18 maanden beginnen te begrijpen dat ouders grenzen stellen. Een kalme, consequente 'nee' is informatief en veilig. Lange uitleg verwarrt op deze leeftijd.",
    skillTip: "Gebruik dezelfde toon als altijd — niet streng, niet boos. Gewoon kalm en helder.",
    vermijd: "Een nee omzetten in een ja als je baby blijft huilen. Dat leert je kind dat volhouden werkt.",
    leerdoel: "Je leert een grens stellen zonder je te verantwoorden.",
    bron: "Mahler et al. (1975) - The Psychological Birth of the Human Infant — boundary formation",
  },
  {
    id: "gren_02_02",
    title: "Gevaarlijk = stoppen",
    skill: "Grenzen",
    description: "Als je baby iets doet dat gevaarlijk is (bijv. naar een stopcontact kruipt): zeg 'stop' op een neutrale toon, haal hem weg en bied een alternatief aan.",
    duration: "2 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Fysieke veiligheid is de eerste grens. Door 'stop' te koppelen aan een alternatief leer je je kind niet alleen wat niet mag, maar ook wat wél kan — dat is effectiever dan alleen verbieden.",
    skillTip: "Zorg dat het alternatief klaarstaat: een speeltje, een ander object. Omleiden werkt beter dan alleen weghalen.",
    vermijd: "Schreeuwen of je baby schrikken — dat associeert 'stop' met gevaar en angst.",
    leerdoel: "Je leert grenzen stellen met een positief alternatief.",
    bron: "Brazelton & Sparrow (2006) - Touchpoints Birth to Three — redirection strategies",
  },
  {
    id: "gren_02_03",
    title: "Consequent zijn bij bedtijd",
    skill: "Grenzen",
    description: "Houd vanavond je bedtidroutine consequent aan, ook als je baby protesteert. Wees warm maar standvastig: het ritueel is hetzelfde elke avond.",
    duration: "20 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Voorspelbaarheid is voor baby's een primaire veiligheidsbehoefte. Consistente grenzen rond slaap verlagen angst en geven structuur aan het dag-nachtritme.",
    skillTip: "Vier de bedtidroutine altijd in dezelfde volgorde: bad, voeding, lied, weg. De volgorde is de grens.",
    vermijd: "Afwijken 'omdat het vanwege één keer toch niet uitmaakt.' Consistentie heeft kracht door herhaling.",
    leerdoel: "Je leert dat grenzen kracht krijgen door consequentie, niet door hardheid.",
    bron: "Ferber (1985) - Solve Your Child's Sleep Problems — predictability & sleep boundaries",
  },
  {
    id: "gren_02_04",
    title: "Rustig blijven bij protest",
    skill: "Grenzen",
    description: "Als je baby protesteert na een grens (bijv. speeltje afpakken): blijf rustig, zeg 'ik weet het, dat is niet leuk', maar verander de grens niet.",
    duration: "3 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Protest bij grenzen is normaal en gezond — het betekent dat je baby zijn behoeften communiceert. Jij kunt de emotie erkennen zonder de grens te veranderen.",
    skillTip: "Erkenning + consistentie tegelijk: 'Dat snap ik, en het antwoord is toch nee.'",
    vermijd: "Denken dat protest betekent dat je het fout doet. Het is een teken dat je kind leert.",
    leerdoel: "Je leert onderscheid te maken tussen het erkennen van een emotie en het wijzigen van een grens.",
    bron: "Lansbury (2014) - No Bad Kids — respectful boundaries with infants",
  },
  {
    id: "gren_02_05",
    title: "Één grens per dag bewust oefenen",
    skill: "Grenzen",
    description: "Kies vandaag één moment om bewust een grens te stellen die je normaal laat glippen — bijv. schermtijd voor je kind, mee-eten aan tafel of slaaproutine.",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Grenzen die wankelen geven baby's een ambivalent signaal: soms geldt de regel, soms niet. Dat verhoogt testen van grenzen. Consistentie verlaagt het.",
    skillTip: "Kies de grens die jou het meest energie kost. Dat is de grens die het meest oefening nodig heeft.",
    vermijd: "Te veel grenzen tegelijk aanpakken. Één bewuste grens per dag levert meer op dan tien halfslachtige.",
    leerdoel: "Je leert welke grenzen jij moeilijk vasthoudt en oefent die gericht.",
    bron: "Baumrind (1966) - Effects of authoritative parental control on child behavior",
  },
  {
    id: "gren_02_06",
    title: "Grens met warmte",
    skill: "Grenzen",
    description: "Combineer vandaag een grens altijd met een moment van warmte. Na het 'nee': knuffel, oogcontact, of een zachte stem. Grens én verbinding tegelijk.",
    duration: "2 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Autoritatief opvoeden — de combinatie van warmte én structuur — is het meest bevorderlijk voor veilige hechting en gezonde ontwikkeling. Grenzen zonder warmte creëren angst.",
    skillTip: "Denk aan: grens met één hand, verbinding met de andere. Je kunt beide tegelijk geven.",
    vermijd: "Na een grens afstand nemen of boos blijven. De verbinding is net zo belangrijk als de grens zelf.",
    leerdoel: "Je leert grenzen te stellen vanuit verbinding, niet vanuit controle.",
    bron: "Baumrind (1991) - The influence of parenting style on adolescent competence — warmth & structure",
  },
  {
    id: "gren_02_07",
    title: "Eigen grens met partner bespreken",
    skill: "Grenzen",
    description: "Bespreek met je partner: welke grenzen stellen we aan onze baby en hoe? Kies één onderwerp (slaap, voeding, schermen) en maak een gezamenlijke afspraak.",
    duration: "10 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Consistentie tussen ouders versterkt de effectiviteit van grenzen. Baby's en kinderen testen vaker grenzen als ze merken dat ouders verschillend reageren.",
    skillTip: "Bespreek het buiten het moment. Niet als je baby net protesteert, maar rustig op een avond.",
    vermijd: "Elkaars aanpak bekritiseren in het bijzijn van je kind. Dat ondermijnt het gezag van allebei.",
    leerdoel: "Je leert grenzen als team te stellen en te bewaken.",
    bron: "Cowan & Cowan (1992) - When Partners Become Parents — co-parenting alignment",
  },
  {
    id: "gren_02_08",
    title: "Grens zonder schuldgevoel",
    skill: "Grenzen",
    description: "Stel vandaag een grens en merk je schuldgevoel op als dat opkomt. Schrijf de zin op: 'Een grens stellen is een daad van liefde, geen afwijzing.'",
    duration: "3 min",
    ageGroups: ["0-2"],
    difficulty: "expert",
    points: 20,
    psychologie: "Schuldgevoel bij het stellen van grenzen is een van de meest voorkomende obstakels voor consequent ouderschap. Het voelt als afwijzing maar is juist structuur en veiligheid.",
    skillTip: "Herhaal de zin elke keer als het schuldgevoel opkomt. Cognitieve herhaling vermindert de lading.",
    vermijd: "Het schuldgevoel wegduwen. Erken het, benoem het, en kies dan toch voor de grens.",
    leerdoel: "Je leert grenzen stellen ondanks schuldgevoel.",
    bron: "Brown (2010) - The Gifts of Imperfection — guilt vs. shame in parenting",
  },
  {
    id: "gren_02_09",
    title: "Veilige omgeving als grens",
    skill: "Grenzen",
    description: "Maak één ruimte in huis echt veilig voor je baby zodat je minder 'nee' hoeft te zeggen. Ruim gevaarlijke dingen op. Dat is ook een grens — een proactieve.",
    duration: "15 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Omgevingsaanpassing vermindert de hoeveelheid grensmomenten en dus de frustratie bij zowel kind als ouder. Minder 'nee' nodig = meer ruimte voor 'ja'.",
    skillTip: "Ga op handen en knieën door de kamer — vanuit het perspectief van je baby zie je wat gevaarlijk is.",
    vermijd: "Denken dat je met baby-proofing te veel toegeeft. Je creëert vrijheid binnen veilige grenzen.",
    leerdoel: "Je leert grenzen ook proactief en preventief in te stellen.",
    bron: "Gonzalez-Mena & Eyer (2012) - Infants, Toddlers, and Caregivers — environment as curriculum",
  },
  {
    id: "gren_02_10",
    title: "Grens bij jezelf",
    skill: "Grenzen",
    description: "Stel vandaag een grens bij jezelf: stop met scrollen als je bij je baby zit. Zeg hardop: 'Nu ben ik er voor jou.' Leg de telefoon weg.",
    duration: "20 min",
    ageGroups: ["0-2"],
    difficulty: "expert",
    points: 20,
    psychologie: "De grens die je het moeilijkst kunt stellen is soms de grens bij jezelf. Modeling van zelfdiscipline begint hier — voor je kind maar ook voor jezelf.",
    skillTip: "Gebruik een fysieke actie: telefoon in een la, op stil, in een andere kamer. Uit het zicht = uit je gedachten.",
    vermijd: "Denken 'ik check alleen even'. Halve aanwezigheid is voor een baby voelbaar.",
    leerdoel: "Je leert grenzen stellen bij je eigen gedrag als fundament voor grenzen bij je kind.",
    bron: "Radesky et al. (2014) - Patterns of Mobile Device Use by Caregivers and Children",
  },

  // ── Grenzen · 3-5 jaar ────────────────────────────────────────
  {
    id: "gren_35_01",
    title: "Korte grens, warme toon",
    skill: "Grenzen",
    description: "Oefen deze formule: een korte, heldere grens + warme toon. Niet: 'Hou op, ik heb je al honderd keer gezegd...' maar: 'Dat doen we niet. Kom, we doen dit.'",
    duration: "2 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Lange uitleg bij een grens werkt averechts bij kleuters: ze raken het begin kwijt en focussen op de emotie van de ouder. Kort + warm is het meest effectief.",
    skillTip: "Oefenzin: [Grens] + [Alternatief]. 'Slaan doen we niet. Je kunt boos zijn met woorden.'",
    vermijd: "Ellenlange verklaringen. Een kleuter van 4 verwerkt maximaal één instructie tegelijk.",
    leerdoel: "Je leert grenzen korter en helderder te formuleren.",
    bron: "Siegel & Bryson (2014) - No-Drama Discipline — connect then redirect",
  },
  {
    id: "gren_35_02",
    title: "Grens herhalen zonder irritatie",
    skill: "Grenzen",
    description: "Als je kind een grens negeert: herhaal dezelfde korte zin drie keer, rustig, zonder je stem te verhogen of je toon te veranderen.",
    duration: "3 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kleuters testen grenzen gemiddeld 3-5 keer voor ze toegeven. Dit is neurologisch normaal — hun executieve functies zijn nog volop in ontwikkeling. Kalmte bij herhaling toont dat de grens echt is.",
    skillTip: "Tel de herhalingen voor jezelf. Als je weet dat er 3 komen, kost de 2e veel minder energie.",
    vermijd: "Bij de tweede herhaling al strenger worden. Dat leert je kind dat ze moeten wachten tot je boos bent.",
    leerdoel: "Je leert grenzen consistent te herhalen zonder escalatie.",
    bron: "Ross Greene (2010) - The Explosive Child — expectation & frustration",
  },
  {
    id: "gren_35_03",
    title: "Als-dan consequentie",
    skill: "Grenzen",
    description: "Koppel vandaag een grens aan een consequentie: 'Als je het speelgoed niet opruimt, kunnen we straks niet naar het park.' Zeg het rustig en voer het uit.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Logische consequenties — gerelateerd aan het gedrag — zijn effectiever dan willekeurige straffen. Ze leren kinderen oorzaak-gevolg verbanden in plaats van angst voor straf.",
    skillTip: "Kies consequenties die je ook echt uitvoert. Een lege dreiging ondermijnt alle toekomstige grenzen.",
    vermijd: "Onuitvoerbare consequenties: 'Dan gaan we nooit meer naar oma.' Dat geloof je zelf niet.",
    leerdoel: "Je leert grenzen te verbinden aan realistische, logische consequenties.",
    bron: "Dreikurs & Soltz (1964) - Children: The Challenge — natural & logical consequences",
  },
  {
    id: "gren_35_04",
    title: "Grenzen uitleggen op kindniveau",
    skill: "Grenzen",
    description: "Leg één grens vandaag kort uit op kindniveau: 'We eten geen snoep voor het eten, want dan heb je geen honger meer.' Één simpele zin is genoeg.",
    duration: "2 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen die begrijpen waarom een grens er is, accepteren hem makkelijker. Maar de uitleg moet kort en concreet zijn — abstract redeneren is nog niet mogelijk voor kleuters.",
    skillTip: "Test je uitleg: kan een 4-jarige het begrijpen? Zo niet, maak het simpeler.",
    vermijd: "Moreel redeneren: 'Dat is niet netjes.' Kleuters begrijpen concrete gevolgen beter dan abstracte normen.",
    leerdoel: "Je leert grenzen zo uit te leggen dat je kind ze begrijpt.",
    bron: "Piaget (1932) - The Moral Judgment of the Child — preoperational reasoning",
  },
  {
    id: "gren_35_05",
    title: "Grens bij schermtijd instellen",
    skill: "Grenzen",
    description: "Stel vandaag een vaste grens rondom schermtijd: hoeveel minuten, wanneer, en hoe stopt het. Gebruik een timer zodat jij niet de 'slechterik' bent — de timer is het.",
    duration: "10 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Externe tijdsbegrenzing vermindert de machtsstrijd. De timer stelt de grens, niet jij persoonlijk — dat verplaatst het conflict van de relatie naar de regel.",
    skillTip: "Gebruik een zichtbare timer (zandloper of kookwekker). Iets wat je kind zelf kan zien geeft meer autonomie.",
    vermijd: "De timer negeren als je kind protesteert. Dan was de timer nooit de grens.",
    leerdoel: "Je leert externe hulpmiddelen te gebruiken om grenzen te objectiveren.",
    bron: "Christakis (2009) - The effects of infant media usage — screen time & development",
  },
  {
    id: "gren_35_06",
    title: "Grens bij agressief gedrag",
    skill: "Grenzen",
    description: "Als je kind slaat, bijt of schopt: ga op ooghoogte, zeg rustig 'slaan doen we niet', en verwijder het kind kort uit de situatie. Daarna verbinding herstellen.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Agressief gedrag bij kleuters is emotionele overbelasting die nog niet in taal kan. De grens 'slaan doen we niet' moet onmiddellijk en consistent zijn, gevolgd door herstel van verbinding.",
    skillTip: "Na de grens: zoek de emotie eronder. 'Je was heel boos. Dat begrijp ik. En slaan doen we niet.'",
    vermijd: "Terugslaan of het kind hard aanpakken. Dat modelleert precies het gedrag dat je wil stoppen.",
    leerdoel: "Je leert de grens bij agressie consistent en zonder escalatie te stellen.",
    bron: "Tremblay (2000) - The development of aggressive behaviour — early intervention",
  },
  {
    id: "gren_35_07",
    title: "Grens houden bij verleidelijk smeekgedrag",
    skill: "Grenzen",
    description: "Als je kind smeekt, jankt of 'maar papa pleeeeease' zegt: blijf bij je grens. Zeg: 'Ik hoor dat je het heel graag wil. Het antwoord blijft nee.'",
    duration: "2 min",
    ageGroups: ["3-5"],
    difficulty: "expert",
    points: 20,
    psychologie: "Smeekgedrag werkt als ouders er ooit op toegegeven hebben. Een consequente grens, zonder boosheid, leert je kind dat smeekgedrag geen nuttige strategie is.",
    skillTip: "Gebruik de zin letterlijk: 'Ik hoor je. Het antwoord blijft nee.' Erkenning + consistentie in één.",
    vermijd: "Langdurig uitleggen waarom het nee is. Hoe meer je praat, hoe meer opening je geeft voor onderhandeling.",
    leerdoel: "Je leert je grens te houden ondanks emotionele druk van je kind.",
    bron: "Lansbury (2014) - No Bad Kids — boundaries under pressure",
  },
  {
    id: "gren_35_08",
    title: "Keuze binnen de grens",
    skill: "Grenzen",
    description: "Geef je kind vandaag een keuze bínnen een grens: niet 'ga nu slapen' maar 'wil je eerst een verhaaltje of eerst tanden poetsen?' De grens (bedtijd) staat vast.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Autonomiebehoefte is een kernbehoefte bij kinderen. Door keuze te geven binnen de grens, bevredigen ze die behoefte zonder de grens zelf aan te tasten.",
    skillTip: "Maximaal twee keuzes. Meer opties zorgen voor keuzestress bij kleuters.",
    vermijd: "Een keuze geven die de grens zelf onderhandelt: 'Wil je naar bed of nog even opblijven?' Dat is geen keuze binnen een grens.",
    leerdoel: "Je leert grenzen te combineren met autonomie door keuze binnen de kaders te geven.",
    bron: "Deci & Ryan (2000) - Self-Determination Theory — autonomy within structure",
  },
  {
    id: "gren_35_09",
    title: "Proactief grens aankondigen",
    skill: "Grenzen",
    description: "Kondig een aankomende grens 5 minuten van tevoren aan: 'Nog 5 minuten spelen, dan gaan we eten.' Gebruik een timer. Geen verrassingsgrens.",
    duration: "2 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Overgangen zijn moeilijk voor kleuters omdat hun tijdsbesef en executieve functies nog beperkt zijn. Een waarschuwing van tevoren geeft het brein tijd om te schakelen.",
    skillTip: "Combineer met een visuele timer zodat je kind zelf kan zien hoeveel tijd er nog is.",
    vermijd: "Zeggen 'nog even' zonder concreet tijdstip. 'Even' is voor een kleuter ondefinieerbaar.",
    leerdoel: "Je leert overgangen voor te bereiden om grensmomenten soepeler te laten verlopen.",
    bron: "Gilliam et al. (2016) - Transitions & executive function in early childhood",
  },
  {
    id: "gren_35_10",
    title: "Eigen grens benoemen als model",
    skill: "Grenzen",
    description: "Zeg vandaag tegen je kind: 'Papa heeft nu even rust nodig. Dat is mijn grens.' Laat zien dat grenzen voor iedereen gelden, ook voor papa.",
    duration: "2 min",
    ageGroups: ["3-5"],
    difficulty: "expert",
    points: 20,
    psychologie: "Modeling van grenzen door ouders leert kinderen dat grenzen normaal en respectwaardig zijn — voor iedereen. Dit is de basis voor het leren stellen van eigen grenzen later.",
    skillTip: "Wees concreet en eerlijk. 'Papa is moe en heeft 10 minuten stilte nodig' is geloofwaardiger dan een vage verklaring.",
    vermijd: "Je grens laten vervallen als je kind protesteert. Dan leert het kind dat jouw grenzen niet echt zijn.",
    leerdoel: "Je leert je eigen grenzen te benoemen als model voor je kind.",
    bron: "Covey (1997) - The 7 Habits of Highly Effective Families — modeling",
  },

  // ── Grenzen · 6-9 jaar ────────────────────────────────────────
  {
    id: "gren_69_01",
    title: "Grens uitleggen met redenering",
    skill: "Grenzen",
    description: "Leg vandaag een grens uit met een korte redenering die je kind begrijpt: 'Je gaat om 9 uur naar bed omdat je lichaam slaap nodig heeft om te groeien.'",
    duration: "3 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen van 6-9 kunnen logisch redeneren en accepteren grenzen beter als ze de reden begrijpen. Maar de uitleg mag niet leiden tot eindeloze onderhandeling.",
    skillTip: "Geef de uitleg één keer, duidelijk. Daarna: 'Ik heb het uitgelegd, het antwoord is nee.' Herhaling is niet nodig.",
    vermijd: "Blijven redeneren als je kind tegenwerpingen heeft. Dan wordt de grens een debat.",
    leerdoel: "Je leert grenzen te onderbouwen zonder ze ter discussie te stellen.",
    bron: "Kohlberg (1969) - Stage theory of moral development — conventional reasoning",
  },
  {
    id: "gren_69_02",
    title: "Grenzen rond vriendjes",
    skill: "Grenzen",
    description: "Als je kind iets wil doen 'omdat alle andere kinderen het ook mogen': erken de sociale druk en houd toch je grens. 'Ik begrijp dat je dat wil. Bij ons gaat het anders.'",
    duration: "3 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Sociale vergelijking wordt sterker vanaf 6 jaar. Kinderen testen grenzen met 'iedereen doet het'. Een ouder die zijn eigen waarden bewaakt zonder anderen te veroordelen, biedt zekerheid.",
    skillTip: "Zeg niet 'die ouders doen het fout'. Zeg: 'Bij ons gelden onze regels. Die zijn er om jou te beschermen.'",
    vermijd: "Toegeven onder sociale druk. Dat leert je kind dat vergelijkingsargumenten werken.",
    leerdoel: "Je leert je gezinswaarden te bewaken tegenover sociale druk.",
    bron: "Harris (1995) - Where is the child's environment? — peer influence vs. parental limits",
  },
  {
    id: "gren_69_03",
    title: "Grens samen formuleren",
    skill: "Grenzen",
    description: "Maak één huisregel samen met je kind. Laat hem/haar meedenken: 'Wanneer denk jij dat het logisch is om schermen weg te doen?' Stel de grens samen vast.",
    duration: "10 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Participatie in regelvorming vergroot de naleving. Kinderen die meedenken over grenzen voelen eigenaarschap en zijn minder geneigd om ze te testen.",
    skillTip: "Accepteer het als je kind een strengere grens voorstelt dan jij. Dat is goud waard.",
    vermijd: "De uitkomst van tevoren bepalen en doen alsof je kind inspraak heeft. Dat prikken kinderen van 6+ direct door.",
    leerdoel: "Je leert grenzen te stellen via participatie voor sterkere naleving.",
    bron: "Baumrind (1991) - The influence of parenting style — democratic parenting & rule-following",
  },
  {
    id: "gren_69_04",
    title: "Consequentie duidelijk verbinden",
    skill: "Grenzen",
    description: "Koppel een grens aan een consequentie die je echt uitvoert: 'Als het speelgoed op de grond blijft, ruim ik het op en ligt het een dag weg.' Doe het als het nodig is.",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "expert",
    points: 20,
    psychologie: "Consistentie tussen aangekondigde consequentie en uitvoering is de kern van geloofwaardig gezag. Elke keer dat een dreiging leeg blijkt, verliest de grens zijn kracht.",
    skillTip: "Kies consequenties die je kunt volhouden ook als je moe bent. Kleine, haalbare consequenties zijn beter dan grote die je niet uitvoert.",
    vermijd: "Consequenties aankondigen die je kind niet gelooft. Dat ondermijnt alles.",
    leerdoel: "Je leert grenzen geloofwaardig te maken door consequenties consistent uit te voeren.",
    bron: "Patterson (1982) - Coercive Family Process — ineffective discipline & escalation",
  },
  {
    id: "gren_69_05",
    title: "Grenzen bij ruzie met vriendjes",
    skill: "Grenzen",
    description: "Als je kind ruzie heeft met een vriendje en jij wordt erbij betrokken: stel een grens aan het gewenste gedrag maar los het conflict niet voor ze op.",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Ouders die conflicten voor kinderen oplossen, ontnemen hen de kans om sociale probleemoplossingsvaardigheden te ontwikkelen. Een grens stellen + laten oplossen is de balans.",
    skillTip: "Zeg: 'Schreeuwen doen we niet. Jullie lossen dit zelf op. Als jullie er niet uitkomen, kom je naar mij.'",
    vermijd: "Partij kiezen voor je eigen kind. Dat leert hem/haar dat winnen het doel is, niet oplossen.",
    leerdoel: "Je leert grenzen te stellen zonder het conflict over te nemen.",
    bron: "Eisenberg & Fabes (1998) - Prosocial development — peer conflict & parental involvement",
  },
  {
    id: "gren_69_06",
    title: "Grens bij gevaarlijk gedrag van anderen",
    skill: "Grenzen",
    description: "Bespreek met je kind: wat doe je als een ander kind jou vraagt iets gevaarlijks of verkeerds te doen? Oefen samen hoe je 'nee' kunt zeggen.",
    duration: "10 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen die thuis grenzen ervaren en zien, leren ook hun eigen grenzen te stellen. Rollenspel vergroot de kans dat ze in een echte situatie daadwerkelijk nee kunnen zeggen.",
    skillTip: "Doe het als rollenspel. Jij speelt het kind dat vraagt, je kind oefent de 'nee'. Wissel dan van rol.",
    vermijd: "Angst aanwakkeren. Het gaat om empowerment, niet om angst voor gevaar.",
    leerdoel: "Je leert je kind om grenzen te stellen bij anderen.",
    bron: "Olweus (1993) - Bullying at School — assertiveness training & boundary-setting",
  },
  {
    id: "gren_69_07",
    title: "Grens bij gamen",
    skill: "Grenzen",
    description: "Maak een concreet gameplan voor gaming: hoelang, wanneer, welke games, en hoe stop je. Schrijf het op en plak het bij de console of computer.",
    duration: "10 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Schriftelijke grenzen externaliseren de regel van de ouder. Het hangt er gewoon. Discussie wordt zo minder persoonlijk — het gaat niet om jou, maar om de afspraak.",
    skillTip: "Laat je kind de afspraak zelf opschrijven of tekenen. Eigenaarschap verhoogt naleving.",
    vermijd: "De afspraak veranderen als je kind onderhandelt. Als de afspraak er hangt, geldt die.",
    leerdoel: "Je leert schriftelijke grenzen te gebruiken als objectieve referentie.",
    bron: "Gentile et al. (2011) - The effects of violent video game habits — parental limits & outcomes",
  },
  {
    id: "gren_69_08",
    title: "Nee zeggen zonder verantwoording",
    skill: "Grenzen",
    description: "Oefen vandaag één keer nee te zeggen zonder uitgebreide uitleg. 'Nee, dat doen we niet.' Als je kind vraagt waarom: 'Omdat ik het zo beslist heb.'",
    duration: "2 min",
    ageGroups: ["6-9"],
    difficulty: "expert",
    points: 20,
    psychologie: "Ouders hoeven niet altijd te verantwoorden. Kinderen die leren dat ouders soms gezag uitoefenen zonder debat, ontwikkelen respect voor autoriteit — mits dit de uitzondering is, niet de regel.",
    skillTip: "Reserveer dit voor situaties waarbij je al eerder uitleg hebt gegeven. Het is geen eerste stap, maar een eindstap.",
    vermijd: "Dit als standaardstrategie gebruiken. Dan voelt het autoritair, niet autoritatief.",
    leerdoel: "Je leert dat jij als ouder niet altijd hoeft te verantwoorden.",
    bron: "Baumrind (1966) - Authoritative vs. authoritarian parenting — the role of explanation",
  },
  {
    id: "gren_69_09",
    title: "Grens bij schreeuwen in huis",
    skill: "Grenzen",
    description: "Stel een duidelijke grens over schreeuwen in huis: 'In dit huis schreeuwen we niet als we boos zijn. Je mag boos zijn. Je mag het zeggen met woorden.'",
    duration: "3 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Huisregels over communicatie helpen kinderen om alternatieve gedragsstrategieën te internaliseren. De grens bij schreeuwen verwijst altijd naar een alternatief.",
    skillTip: "Geldt ook voor jezelf. Als jij schreeuwt, ondergraaf je de grens. Model wat je vraagt.",
    vermijd: "De grens alleen stellen als het al te laat is. Bespreek het in een rustig moment.",
    leerdoel: "Je leert een huisgrens te stellen over emotionele communicatie.",
    bron: "Gottman & Silver (1999) - The Seven Principles for Making Marriage Work — contempt & communication",
  },
  {
    id: "gren_69_10",
    title: "Grens vieren als het werkt",
    skill: "Grenzen",
    description: "Als je kind zich aan een grens houdt die eerder moeilijk was: benoem het positief. 'Ik zag dat je je scherm uitdeed toen de timer afging. Dat vond ik goed.'",
    duration: "2 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Positieve bekrachtiging van gewenst gedrag is effectiever dan bestraffen van ongewenst gedrag. Specifieke erkenning vertelt je kind precies wat goed was.",
    skillTip: "Wees specifiek. Niet: 'Goed gedaan!' maar: 'Ik zag dat je deed wat we hadden afgesproken.' Dat is informatief.",
    vermijd: "Overdreven lof ('wat ben jij geweldig!'). Dat werkt averechts en voelt onecht.",
    leerdoel: "Je leert grensnaleving positief te bekrachtigen.",
    bron: "Skinner (1938) - Behavior of Organisms — positive reinforcement & operant conditioning",
  },

  // ── Grenzen · 10-12 jaar ─────────────────────────────────────
  {
    id: "gren_1012_01",
    title: "Grenzen negotiëren, niet opgeven",
    skill: "Grenzen",
    description: "Als je kind onderhandelt over een grens: luister naar het argument, overweeg het eerlijk, en beslis dan. Soms kun je de grens bijstellen — maar vanuit jouw overweging, niet onder druk.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Pre-adolescenten zijn klaar voor meer nuance in grensstelling. Luisteren naar hun argument en soms bijstellen versterkt de relatie — mits jij de beslissing neemt, niet de druk.",
    skillTip: "Onderscheid: toegeven onder druk (slecht) vs. bijstellen na nadenken (goed). Het verschil zit in wie beslist.",
    vermijd: "Altijd 'nee' zeggen om je gezag te bewijzen. Dat is rigiditeit, geen autoriteit.",
    leerdoel: "Je leert het verschil tussen buigen onder druk en weloverwogen bijstellen.",
    bron: "Steinberg (2001) - Parenting adolescents — autonomy granting & boundary negotiation",
  },
  {
    id: "gren_1012_02",
    title: "Grens bij vriendschappen",
    skill: "Grenzen",
    description: "Bespreek: zijn er vrienden van je kind waarbij jij een ongemakkelijk gevoel hebt? Stel een grens die jij kunt verdedigen: 'Jullie mogen hier spelen maar niet bij hem thuis.'",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Vriendschapsbeïnvloeding wordt sterker rond 10-12. Ouders mogen grenzen stellen rondom vriendschappen mits ze de reden uitleggen en de relatie met hun kind bewaken.",
    skillTip: "Leg uit vanuit zorg, niet vanuit oordeel over het andere kind. 'Ik maak me zorgen, niet over hem, maar over de situatie.'",
    vermijd: "Het andere kind veroordelen. Dat drijft je eigen kind juist meer naar hem toe.",
    leerdoel: "Je leert grenzen te stellen rondom vriendschappen vanuit zorg in plaats van controle.",
    bron: "Brown (2004) - Adolescents' relationships with peers — peer influence & parental monitoring",
  },
  {
    id: "gren_1012_03",
    title: "Digitale grenzen herzien",
    skill: "Grenzen",
    description: "Bekijk samen de digitale afspraken: zijn de grenzen van 2 jaar geleden nog passend? Pas ze aan waar nodig. Geef meer vrijheid waar je kind het verdiend heeft.",
    duration: "15 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Grenzen die niet meegroeien met het kind worden als oneerlijk ervaren en worden vaker getest. Het herzien van grenzen op basis van vertrouwen versterkt de relatie.",
    skillTip: "Begin met: 'Waar heb jij het gevoel dat je meer vrijheid verdient?' Stel de vraag eerlijk.",
    vermijd: "Grenzen herzien als beloning na conflict. Doe het in een rustig moment als beloning voor vertrouwen.",
    leerdoel: "Je leert grenzen te evalueren en bij te stellen naarmate je kind groeit.",
    bron: "Smetana (2008) - Adolescents, families, and social development — renegotiating boundaries",
  },
  {
    id: "gren_1012_04",
    title: "Grens bij privacy",
    skill: "Grenzen",
    description: "Bespreek de grenzen rondom privacy in huis: kloppen voor de slaapkamerdeur, berichten niet lezen, dagboeken niet doorzoeken. Spreek uit welke grenzen jij respecteert.",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Respect voor de privacy van je kind bouwt vertrouwen. Kinderen die hun privacy gerespecteerd zien, zijn paradoxaal genoeg opener met ouders.",
    skillTip: "Maak het wederzijds: 'Dit zijn jouw grenzen, dit zijn mijn grenzen.' Grenzen gaan twee kanten op.",
    vermijd: "Privacygrenzen schenden 'voor de veiligheid' zonder dat te bespreken. Transparantie is beter dan heimelijk controleren.",
    leerdoel: "Je leert privacygrenzen te respecteren als fundament voor vertrouwen.",
    bron: "Petronio (2002) - Boundaries of Privacy — communication privacy management",
  },
  {
    id: "gren_1012_05",
    title: "Grens bij zichzelf overschrijden",
    skill: "Grenzen",
    description: "Als je kind iets doet wat schadelijk is voor zichzelf (te weinig slaap, ongezond eten, zichzelf isoleren): stel een grens vanuit zorg, niet vanuit controle.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Grenzen die vanuit zorg worden gesteld worden beter geaccepteerd dan grenzen die vanuit controle komen. Het verschil zit in de intentie én de formulering.",
    skillTip: "Formuleer vanuit jij: 'Ik maak me zorgen om jouw slaap omdat ik zie dat je moe bent.' Niet: 'Je moet om 10 uur naar bed.'",
    vermijd: "Micro-managen van kleine keuzes. Kies je grenzen zorgvuldig — niet alles is de moeite waard.",
    leerdoel: "Je leert grenzen te stellen vanuit zorg voor welzijn, niet vanuit controle.",
    bron: "Ryan & Deci (2000) - Self-Determination Theory — autonomy-supportive vs. controlling parenting",
  },
  {
    id: "gren_1012_06",
    title: "Consequentie laten voelen",
    skill: "Grenzen",
    description: "Laat je kind de natuurlijke consequentie van zijn keuze voelen — zonder te redden. Als hij zijn lunch vergeet, laat hem honger hebben (als het veilig is).",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Natuurlijke consequenties zijn de meest effectieve leermeesters. Ouders die altijd redden, ontnemen hun kind de kans om oorzaak-gevolg in het echte leven te leren.",
    skillTip: "Vraag jezelf: 'Is deze consequentie gevaarlijk, vernederend of niet-leerzaam?' Zo niet, laat hem voelen.",
    vermijd: "Redden en dan een preek houden. De consequentie is de les — de preek erna doet af aan het leereffect.",
    leerdoel: "Je leert te vertrouwen op natuurlijke consequenties in plaats van te redden.",
    bron: "Dreikurs & Soltz (1964) - Children: The Challenge — natural consequences as teachers",
  },
  {
    id: "gren_1012_07",
    title: "Grenzen bij overgang naar puberheid",
    skill: "Grenzen",
    description: "Bespreek met je kind: nu je ouder wordt, krijg je meer vrijheid. En daarmee ook meer verantwoordelijkheid. Maak één concreet voorbeeld: wat mag meer, wat wordt van je verwacht?",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "De overgang naar adolescentie vereist aanpassing van grenzen. Te veel grenzen leiden tot rebellie; te weinig tot onveiligheid. Het gesprek erover is al een grenstelling.",
    skillTip: "Frame het positief: 'Jij groeit en dus groeien onze afspraken ook.' Dat geeft richting en motivatie.",
    vermijd: "Het gesprek uitstellen tot er al een conflict is. Praat erover voor dat nodig is.",
    leerdoel: "Je leert grenzen proactief aan te passen aan de leeftijd van je kind.",
    bron: "Steinberg (1990) - Autonomy, conflict, and harmony in the family relationship — adolescent individuation",
  },
  {
    id: "gren_1012_08",
    title: "Grens bij oneerlijkheid",
    skill: "Grenzen",
    description: "Als je kind liegt of iets verzwijgt: reageer kalm. Zeg: 'Ik weet dat dit niet klopt. We praten erover als je klaar bent voor eerlijkheid.' Geef ruimte maar houd de grens.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Liegen bij kinderen van 10-12 is vaak zelfbescherming. Een grens stellen aan oneerlijkheid werkt beter als je de veiligheid vergroot (minder angst voor straf) dan als je harder straft.",
    skillTip: "Zeg erbij: 'Als je eerlijk bent, ook al is het moeilijk, dan waardeer ik dat.' Maak eerlijkheid de veiligste optie.",
    vermijd: "Liegen bestraffen op een manier die de angst voor eerlijkheid vergroot.",
    leerdoel: "Je leert grenzen te stellen bij oneerlijkheid op een manier die eerlijkheid uitnodigt.",
    bron: "Talwar & Lee (2008) - Social and cognitive correlates of children's lying behavior",
  },
  {
    id: "gren_1012_09",
    title: "Grens bij schermverslaving",
    skill: "Grenzen",
    description: "Als je merkt dat je kind niet meer kan stoppen met gamen of scrollen: bespreek het zonder oordeel. Maak samen een plan: wat zijn de signalen dat het te veel wordt?",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Zelfregulatie bij schermen is een vaardigheid die aangeleerd moet worden. Ouders die samenwerken met het kind aan het probleem zijn effectiever dan ouders die gewoon verbieden.",
    skillTip: "Bespreek: 'Hoe voel je je als je lang gespeeld hebt?' Bewustwording is de eerste stap naar zelfregulatie.",
    vermijd: "Schermen plotseling totaal verbieden. Dat escaleert en lost niets op.",
    leerdoel: "Je leert digitale grenzen samen te stellen vanuit bewustwording.",
    bron: "Przybylski & Weinstein (2017) - A large-scale test of the Goldilocks hypothesis — screen time",
  },
  {
    id: "gren_1012_10",
    title: "Grens bij jezelf als vader",
    skill: "Grenzen",
    description: "Benoem één persoonlijke grens als vader die je deze week wil respecteren: 'Ik ga niet schreeuwen als ik gefrustreerd ben' of 'Ik ga niet straffen vanuit boosheid.'",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "De krachtigste grenzen die je kunt stellen zijn die bij jezelf. Kinderen respecteren ouders die ook hun eigen gedrag begrenzen. Het modelleert integriteit.",
    skillTip: "Schrijf je grens op en zet hem ergens waar je hem ziet. Accountability verhoogt de kans op naleving.",
    vermijd: "Te makkelijke grenzen kiezen. Kies iets dat je echt uitdaagt.",
    leerdoel: "Je leert grenzen bij jezelf als fundament voor geloofwaardig ouderschap.",
    bron: "Siegel (2010) - Mindsight — self-awareness & parenting integrity",
  },

  // ── Grenzen · 13-16 jaar ─────────────────────────────────────
  {
    id: "gren_1316_01",
    title: "Grens met respect, niet met macht",
    skill: "Grenzen",
    description: "Als je een grens stelt bij je tiener: doe het vanuit respect, niet vanuit macht. Niet 'omdat ik het zeg' maar 'dit is mijn grens en hier is waarom.'",
    duration: "3 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Tieners reageren veel sterker op macht dan op respect. Grenzen die vanuit respect worden gesteld activeren minder weerstand en meer internaliserend gedrag.",
    skillTip: "Vraag jezelf: 'Stel ik deze grens vanuit mijn waarden of vanuit mijn ego?' Het eerste is gezond, het tweede niet.",
    vermijd: "Zeggen 'zolang je bij mij woont, doe je wat ik zeg.' Dat is macht die de relatie beschadigt.",
    leerdoel: "Je leert grenzen te stellen vanuit waarden en respect, niet vanuit macht.",
    bron: "Baumrind (1991) - The influence of parenting style — warmth, structure & autonomy granting",
  },
  {
    id: "gren_1316_02",
    title: "Grens bij thuistijd",
    skill: "Grenzen",
    description: "Bespreek een thuistijd die jullie allebei realistisch vinden. Leg uit waarom: niet 'omdat ik het zeg' maar 'omdat ik me zorgen maak als ik niet weet waar je bent.'",
    duration: "10 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Monitoring — weten waar je tiener is — is een van de sterkste beschermende factoren tegen risicogedrag. Maar monitoring via vertrouwen werkt beter dan monitoring via controle.",
    skillTip: "Onderhandel over de thuistijd op basis van vertrouwen: hoe beter het track record, hoe later de tijd.",
    vermijd: "Een thuistijd opleggen zonder overleg. Dat leidt tot ontwijking en heimelijkheid.",
    leerdoel: "Je leert thuistijden te verbinden aan vertrouwen in plaats van controle.",
    bron: "Kerr & Stattin (2000) - What parents know, how they know it, and several forms of adolescent adjustment",
  },
  {
    id: "gren_1316_03",
    title: "Niet-onderhandelbaren benoemen",
    skill: "Grenzen",
    description: "Benoem één grens die voor jou absoluut niet onderhandelbaar is — en leg eerlijk uit waarom. 'Alcohol en drugs: daar zet ik een harde grens. Hier is waarom.'",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Tieners respecteren absolute grenzen meer als ze begrijpen waarom die er zijn. Een eerlijke uitleg — ook over angst — is krachtiger dan een verbod zonder uitleg.",
    skillTip: "Wees ook kwetsbaar: 'Ik ben bang voor je veiligheid. Dat is waarom ik hier absoluut sta.'",
    vermijd: "Te veel niet-onderhandelbaren. Als alles absoluut is, is niets het.",
    leerdoel: "Je leert het onderscheid te maken tussen harde en zachte grenzen.",
    bron: "Darling & Steinberg (1993) - Parenting style as context — non-negotiables & adolescent safety",
  },
  {
    id: "gren_1316_04",
    title: "Grens bij schending van vertrouwen",
    skill: "Grenzen",
    description: "Als je tiener een vertrouwensgrens heeft geschonden: bespreek het kalm. 'Dit was een grens. Die is geschonden. Dit is wat ik nu doe, en dit is hoe je vertrouwen terugwint.'",
    duration: "10 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Vertrouwen herstel bij tieners vereist duidelijkheid: wat is er precies gebeurd, wat zijn de gevolgen, en hoe ziet het herstelpad eruit. Onduidelijkheid voedt onzekerheid aan beide kanten.",
    skillTip: "Maak het herstelpad concreet en tijdsgebonden: 'Als je de komende 2 weken je afspraken nakomt, kijken we opnieuw.'",
    vermijd: "Straffen zonder perspectief. Zorg dat je tiener weet hoe het vertrouwen terug te verdienen.",
    leerdoel: "Je leert grenzen te herstellen na schending via een concreet herstelpad.",
    bron: "Metts (1994) - Relational transgressions — betrayal, repair & trust restoration",
  },
  {
    id: "gren_1316_05",
    title: "Grens bij gevaarlijke vrienden",
    skill: "Grenzen",
    description: "Als je je zorgen maakt over de vriendenkring van je tiener: bespreek het openlijk. Verbied niet meteen, maar stel een grens aan de situatie: waar, wanneer, hoe laat.",
    duration: "10 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Totaalverboden op vriendschappen versterken de band met die vrienden (reactance theory). Situationele grenzen zijn effectiever dan persoonlijke verboden.",
    skillTip: "Zeg niet 'ik wil dat je niet meer met X omgaat' maar 'ik wil niet dat jullie 's avonds laat ergens rondhangen zonder toezicht'.",
    vermijd: "Vrienden veroordelen in bijzijn van je tiener. Dat is de snelste manier om ze dichter bij die vrienden te duwen.",
    leerdoel: "Je leert situationele grenzen te stellen zonder relaties te verbieden.",
    bron: "Brehm (1966) - A Theory of Psychological Reactance — forbidden fruit effect",
  },
  {
    id: "gren_1316_06",
    title: "Grens bij seksualiteit en relaties",
    skill: "Grenzen",
    description: "Bespreek de grenzen rondom relaties en seksualiteit op een open, niet-beoordelende manier. Maak duidelijk wat jouw verwachtingen zijn en waarom.",
    duration: "10 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Ouders die open praten over seksualiteit en grenzen stellen op een niet-beschamende manier, hebben tieners die vaker veilig gedrag vertonen en eerder om hulp vragen.",
    skillTip: "Begin met: 'Ik wil dat we hier open over kunnen praten. Ik ben niet hier om te oordelen, maar om je te beschermen.'",
    vermijd: "Het gesprek vermijden uit ongemak. Jouw ongemak is minder erg dan de gevolgen van geen gesprek.",
    leerdoel: "Je leert open grensgesprekken te voeren over gevoelige onderwerpen.",
    bron: "Jaccard et al. (1998) - Parent-adolescent communication about sex — protective factors",
  },
  {
    id: "gren_1316_07",
    title: "Grenzen respecteren als ze testen",
    skill: "Grenzen",
    description: "Als je tiener je grenzen test (laat thuiskomen, afspraken vergeten): houd de grens kalm en consistent zonder te escaleren. De test is ook een verzoek om structuur.",
    duration: "3 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Grenzen testen is een neurobiologisch gedreven gedrag bij tieners. Het is geen bewuste opstand maar een zoektocht naar structuur en veiligheid — ook als het er niet zo uitziet.",
    skillTip: "Herinner jezelf: 'Hij test mijn grens omdat hij wil weten of die echt is. Ik laat hem zien van wel.'",
    vermijd: "Toegeven op de grens omdat je de rust wil bewaren. Rust koop je niet met grensverlies.",
    leerdoel: "Je leert grenzen te bewaken ook als ze worden getest.",
    bron: "Casey et al. (2008) - The adolescent brain — risk-taking & boundary testing",
  },
  {
    id: "gren_1316_08",
    title: "Grens bij eigen onmacht",
    skill: "Grenzen",
    description: "Als je tiener iets doet waar je geen controle meer over hebt: accepteer je eigen grenzen als ouder. Je kunt niet alles controleren. Wat kún je nog wel doen?",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Controleverliessensaties bij ouders van tieners leiden tot overreactie of opgeven. Het accepteren van de eigen grenzen als ouder is paradoxaal genoeg de meest effectieve positie.",
    skillTip: "Schrijf op: wat kan ik nog wél doen? Zorg dat je relatie intact blijft — dat is je grootste invloed.",
    vermijd: "Alles proberen te controleren als controle verloren is. Dat verwoest de relatie die je overhoudt.",
    leerdoel: "Je leert de grenzen van je eigen invloed als ouder van een tiener te accepteren.",
    bron: "Covey (1989) - The 7 Habits — circle of influence vs. circle of concern",
  },
  {
    id: "gren_1316_09",
    title: "Grens en consequentie bij 16+",
    skill: "Grenzen",
    description: "Bespreek welke consequenties jij als ouder nog kunt inzetten bij een 15-16 jarige — en welke niet meer werken. Pas je aanpak aan op de leeftijd.",
    duration: "10 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Consequenties voor tieners werken alleen als ze relevant zijn voor hun leven. Vroeg-kinderlijke consequenties (geen scherm, vroeg naar bed) verliezen hun kracht. Vrijheid intrekken werkt beter.",
    skillTip: "Vraag jezelf: 'Wat is voor hem/haar op dit moment het meest waardevol?' Dat is het hefboommoment.",
    vermijd: "Consequenties gebruiken die je kind niet meer raken. Dan verlies je geloofwaardigheid.",
    leerdoel: "Je leert grenzen en consequenties aan te passen aan de leeftijd en rijpheid van je tiener.",
    bron: "Steinberg (2001) - We Know Some Things — effective discipline in adolescence",
  },
  {
    id: "gren_1316_10",
    title: "Grens met liefde uitleggen",
    skill: "Grenzen",
    description: "Leg één grens uit met: 'Ik stel deze grens omdat ik van je houd en me zorgen maak, niet omdat ik je wantrouw.' Koppel de grens aan liefde, niet aan controle.",
    duration: "3 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "De intentie achter een grens bepaalt hoe die wordt ontvangen. Grenzen vanuit liefde worden anders verwerkt dan grenzen vanuit wantrouwen of angst — ook als de grens zelf hetzelfde is.",
    skillTip: "Zeg het letterlijk. Tieners horen graag dat grenzen vanuit liefde komen, ook als ze het op het moment niet laten zien.",
    vermijd: "Ervan uitgaan dat je tiener weet dat grenzen uit liefde komen. Zeg het expliciet.",
    leerdoel: "Je leert grenzen expliciet te verbinden aan liefde en zorg.",
    bron: "Baumrind (1991) - Effective parenting during the early adolescent transition — warmth & limits",
  },
];
