import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_29: InteractiveTask[] = [
  // ============================================================
  // AANWEZIGHEID (10 taken)
  // ============================================================
  {
    id: "gedrag_aanw_01",
    title: "De prikkelradar",
    skill: "Aanwezigheid",
    description: "Let vandaag bewust op momenten dat je kind overweldigd raakt door prikkels. Observeer zonder in te grijpen.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Hooggevoelige kinderen raken sneller overprikkeld door geluid, licht, drukte of onverwachte veranderingen. Door eerst te observeren leer je de unieke prikkelgevoeligheid van jouw kind kennen, wat de basis is voor effectieve ondersteuning.",
    skillTip: "Let op subtiele signalen: oren bedekken, terugtrekken, juist heel druk worden, ogen afwenden of aan kleding plukken. Noteer wat je opvalt in je telefoon.",
    vermijd: "Zeggen 'stel je niet aan' of de prikkels bagatelliseren. Grijp niet meteen in — observeer eerst.",
    leerdoel: "Je leert de unieke overprikkelsignalen van jouw kind herkennen voordat het escaleert.",
    bron: "Aron (2002) - The Highly Sensitive Child",
    themes: ["hooggevoelig", "prikkelverwerking"],
  },
  {
    id: "gedrag_aanw_02",
    title: "ADHD-bril opzetten",
    skill: "Aanwezigheid",
    description: "Probeer 15 minuten de wereld door de ogen van je kind met ADHD te zien. Let op hoeveel prikkels er tegelijk binnenkomen.",
    duration: "15 min",
    ageGroups: ["6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen met ADHD hebben een brein dat anders filtert: het laat meer prikkels tegelijk binnen. Wat voor jou achtergrondgeluid is, kan voor je kind een overweldigende muur van geluid zijn. Perspectief nemen vergroot je empathie en begrip.",
    skillTip: "Zet tijdens het huiswerk de TV, radio en je eigen telefoon aan tegelijk. Probeer je dan te concentreren op één taak. Voel hoe moeilijk dat is — dát is wat je kind elke dag ervaart.",
    vermijd: "Denken 'hij moet gewoon beter zijn best doen'. ADHD is geen kwestie van wilskracht maar van neurologische filtering.",
    leerdoel: "Je ervaart zelf hoe overweldigend het is wanneer je brein prikkels niet goed kan filteren.",
    bron: "Barkley (2015) - Attention-Deficit Hyperactivity Disorder: A Handbook for Diagnosis and Treatment",
    themes: ["adhd", "prikkelverwerking"],
  },
  {
    id: "gedrag_aanw_03",
    title: "Stille nabijheid",
    skill: "Aanwezigheid",
    description: "Ga bij je kind zitten zonder iets te zeggen of te doen wanneer het gefrustreerd of boos is. Wees er simpelweg.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen met gedragsproblemen krijgen vaak veel corrigerende aandacht. Stille nabijheid communiceert: 'Ik ben er voor je, ook als het lastig is.' Dit activeert het hechtingssysteem en helpt het kind sneller te kalmeren.",
    skillTip: "Ga op dezelfde hoogte zitten als je kind. Geen oogcontact forceren, geen vragen stellen. Adem rustig. Je aanwezigheid is genoeg.",
    vermijd: "Zeggen 'wat is er nou?' of 'kom op, het valt wel mee'. Probeer ook niet het probleem meteen op te lossen.",
    leerdoel: "Je leert dat aanwezigheid zonder woorden soms krachtiger is dan welk advies ook.",
    bron: "Siegel & Bryson (2011) - The Whole-Brain Child",
    themes: ["gedragsproblemen"],
  },
  {
    id: "gedrag_aanw_04",
    title: "De overgangswaarnemer",
    skill: "Aanwezigheid",
    description: "Observeer hoe je kind reageert op overgangsmomenten (van spelen naar eten, van thuis naar school). Noteer wat je ziet.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Veel kinderen met ADHD of prikkelgevoeligheid hebben enorme moeite met transities. Hun brein heeft meer tijd nodig om van de ene activiteit naar de andere te schakelen. Door dit te observeren kun je beter anticiperen.",
    skillTip: "Let specifiek op: wordt je kind boos, angstig of juist heel sloom bij overgangen? Hoeveel tijd heeft het nodig? Welke overgangen gaan wél goed?",
    vermijd: "Het kind opjagen met 'schiet eens op' of 'we moeten nu echt gaan'. Dit verhoogt de stress bij transitiemomenten.",
    leerdoel: "Je identificeert welke overgangen lastig zijn en welke aanpak bij jouw kind werkt.",
    bron: "Greene (2014) - The Explosive Child",
    themes: ["adhd", "gedragsproblemen"],
  },
  {
    id: "gedrag_aanw_05",
    title: "Het energiedagboek",
    skill: "Aanwezigheid",
    description: "Houd vandaag bij wanneer je kind energie heeft en wanneer niet. Zoek het patroon achter het 'lastige' gedrag.",
    duration: "20 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Gedragsproblemen zijn vaak erger op momenten van lage energie, honger of overprikkeling. Door patronen te herkennen kun je proactief inspelen op moeilijke momenten in plaats van alleen reactief te corrigeren.",
    skillTip: "Noteer elk uur kort: energieniveau (1-5), stemming, wat er net gebeurde, en of er 'lastig gedrag' was. Zoek aan het eind van de dag het patroon.",
    vermijd: "Het dagboek als bewijs gebruiken tegen je kind ('zie je wel, je bent altijd lastig na school'). Het is een hulpmiddel voor jou.",
    leerdoel: "Je ontdekt de verborgen triggers achter het gedrag van je kind.",
    bron: "Kazdin (2008) - The Kazdin Method for Parenting the Defiant Child",
    themes: ["gedragsproblemen", "adhd"],
  },
  {
    id: "gedrag_aanw_06",
    title: "Sensorische safari",
    skill: "Aanwezigheid",
    description: "Ga samen met je kind op 'safari' door het huis en ontdek welke geluiden, geuren en texturen jullie opvallen.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Door samen zintuiglijke ervaringen te verkennen leer je hoe jouw kind prikkels verwerkt. Wat voor jou normaal is, kan voor een prikkelgevoelig kind overweldigend of juist heerlijk zijn.",
    skillTip: "Maak er een spel van: 'Wat hoor jij nu? Wat ruik je? Hoe voelt dit kussen?' Luister zonder oordeel naar de antwoorden. Je kind is de expert van zijn eigen ervaring.",
    vermijd: "Reacties als 'dat is toch niet erg' of 'dat geluid is heel zacht'. Respecteer de sensorische ervaring van je kind.",
    leerdoel: "Je krijgt inzicht in het sensorische profiel van je kind via een speelse, verbindende activiteit.",
    bron: "Dunn (2007) - Supporting Children with Sensory Processing Differences",
    themes: ["prikkelverwerking", "hooggevoelig"],
  },
  {
    id: "gedrag_aanw_07",
    title: "Het stille kwartier",
    skill: "Aanwezigheid",
    description: "Creëer een dagelijks 'stil kwartier' waarbij je samen met je kind in rust bent — geen schermen, geen praten, gewoon zijn.",
    duration: "15 min",
    ageGroups: ["6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen die de hele dag moeten presteren op school hebben dringend behoefte aan 'down time'. Vooral kinderen met ADHD of hooggevoeligheid hebben stilte nodig om hun zenuwstelsel te laten herstellen.",
    skillTip: "Doe dit samen — lees allebei een boek, teken, of kijk uit het raam. Het gaat om gedeelde rust, niet om afzondering. Begin met 5 minuten als 15 te veel is.",
    vermijd: "Schermen aanbieden als alternatief — die geven juist meer prikkels. Maak er ook geen straf van.",
    leerdoel: "Je leert samen met je kind het zenuwstelsel te laten ontspannen door gedeelde stilte.",
    bron: "Shanker (2016) - Self-Reg: How to Help Your Child (and You) Break the Stress Cycle",
    themes: ["hooggevoelig", "adhd"],
  },
  {
    id: "gedrag_aanw_08",
    title: "Trigger-detective",
    skill: "Aanwezigheid",
    description: "Speel 'detective' en onderzoek samen met je kind wat een recente driftbui of meltdown veroorzaakte.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen met gedragsproblemen weten vaak zelf niet waarom ze zo reageren. Door samen op onderzoek te gaan — zonder oordeel — help je je kind zelfkennis te ontwikkelen en voelt het zich begrepen in plaats van veroordeeld.",
    skillTip: "Gebruik een neutraal moment (niet tijdens de bui zelf). Vraag: 'Wat denk je dat ervoor zorgde dat het zo lastig werd?' Luister, vul niet in.",
    vermijd: "Dit gesprek voeren als je kind nog boos of overstuur is. Wacht minimaal een uur na het incident.",
    leerdoel: "Je helpt je kind om zelfbewustzijn te ontwikkelen rondom triggers van moeilijk gedrag.",
    bron: "Greene (2014) - The Explosive Child",
    themes: ["gedragsproblemen"],
  },
  {
    id: "gedrag_aanw_09",
    title: "Lichaamstaal lezen",
    skill: "Aanwezigheid",
    description: "Let vandaag extra op de lichaamstaal van je kind. Wat vertelt het lichaam dat woorden niet zeggen?",
    duration: "10 min",
    ageGroups: ["0-2", "3-5", "6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Veel kinderen met sensorische verwerkingsproblemen of hooggevoeligheid uiten hun ongemak eerder via lichaamstaal dan via woorden. Schouders optrekken, vuisten ballen, of juist heel stil worden zijn belangrijke signalen.",
    skillTip: "Kijk naar handen (ballen of friemelen), schouders (optrekken), ademhaling (snel of oppervlakkig), en ogen (wegkijken of groot worden). Noteer drie signalen die je opvallen.",
    vermijd: "Je kind confronteren met je observaties op het moment zelf ('ik zie dat je gespannen bent!'). Bewaar het voor later.",
    leerdoel: "Je scherpt je waarneming aan zodat je eerder kunt inspelen op de behoeften van je kind.",
    bron: "Porges (2011) - The Polyvagal Theory",
    themes: ["hooggevoelig", "prikkelverwerking"],
  },
  {
    id: "gedrag_aanw_10",
    title: "De schooldagcheck",
    skill: "Aanwezigheid",
    description: "Neem na school bewust 5 minuten om zonder vragen te observeren hoe je kind binnenkomt. Let op energie, stemming en lichaamshouding.",
    duration: "5 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Kinderen met ADHD of gedragsproblemen hebben op school vaak een hele dag hun best gedaan om zich aan te passen. Na school 'ontploft' het soms — niet omdat ze lastig zijn, maar omdat ze uitgeput zijn van het onderdrukken. Dit heet het 'after-school restraint collapse'.",
    skillTip: "Stel géén vragen over school in de eerste 15 minuten. Bied een snack, een knuffel of gewoon ruimte aan. Observeer: is je kind uitgeput, opgefokt, of teruggetrokken?",
    vermijd: "Meteen vragen 'hoe was het op school?' of 'heb je je gedragen vandaag?'. Dit voelt als een verhoor na een lange dag.",
    leerdoel: "Je herkent het 'after-school restraint collapse' en leert je kind de ruimte te geven om te landen.",
    bron: "Shanker (2016) - Self-Reg: How to Help Your Child Break the Stress Cycle",
    themes: ["adhd", "gedragsproblemen"],
  },

  // ============================================================
  // EMOTIECOACHING (10 taken)
  // ============================================================
  {
    id: "gedrag_emot_01",
    title: "Emotie benoemen bij weerstand",
    skill: "Emotiecoaching",
    description: "Wanneer je kind vandaag 'nee' zegt of zich verzet, benoem dan eerst de emotie die je achter het verzet vermoedt.",
    duration: "5 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Achter weerstand zit altijd een emotie — angst, frustratie, overprikkeling of het gevoel niet begrepen te worden. Door de emotie te benoemen voelt je kind zich gezien, waardoor de weerstand vaak afneemt.",
    skillTip: "Zeg: 'Ik denk dat je boos bent omdat...' of 'Het lijkt alsof je het moeilijk vindt om...' Wacht even af en kijk of je kind reageert.",
    vermijd: "De emotie invullen als waarheid ('jij bent gewoon moe'). Gebruik 'ik denk' of 'het lijkt alsof' — laat ruimte voor correctie.",
    leerdoel: "Je leert de emotie achter het gedrag te herkennen en te benoemen.",
    bron: "Gottman (1997) - Raising an Emotionally Intelligent Child",
    themes: ["gedragsproblemen"],
  },
  {
    id: "gedrag_emot_02",
    title: "Het gevoelsweerbericht",
    skill: "Emotiecoaching",
    description: "Doe samen met je kind een 'gevoelsweerbericht': welk weer past bij hoe jullie je nu voelen?",
    duration: "5 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen met ADHD of hooggevoeligheid hebben soms moeite om hun emoties in woorden te vatten. Een metafoor als het weer maakt het concreet en speels, en geeft taal aan wat ze van binnen voelen.",
    skillTip: "Begin zelf: 'Papa voelt zich vandaag een beetje bewolkt met af en toe zon.' Vraag dan: 'En bij jou? Regent het, schijnt de zon, of is het storm?' Alles mag.",
    vermijd: "Zeggen 'maar het is toch mooi weer, je hoeft niet boos te zijn'. Elk weerbericht is oké — geen goed of fout.",
    leerdoel: "Je geeft je kind een creatief hulpmiddel om emoties te uiten, ook als woorden moeilijk zijn.",
    bron: "Sunderland (2006) - The Science of Parenting",
    themes: ["adhd", "hooggevoelig"],
  },
  {
    id: "gedrag_emot_03",
    title: "De frustratiethermometer",
    skill: "Emotiecoaching",
    description: "Maak samen met je kind een 'frustratiethermometer' van 1 tot 10 en bespreek wat er bij elk niveau helpt.",
    duration: "15 min",
    ageGroups: ["6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen met ADHD ervaren emoties intenser en schakelen sneller van 0 naar 100. Een visueel hulpmiddel helpt hen om gradaties te leren herkennen vóórdat het escaleert.",
    skillTip: "Teken samen een thermometer. Laat je kind bij elk niveau een kleur, gezicht en voorbeeld bedenken. Bespreek: 'Wat kan papa doen bij een 4? En wat bij een 8?'",
    vermijd: "De thermometer gebruiken als controle-instrument ('je zit nu op een 7, gedraag je!'). Het is een hulpmiddel, geen meetlat.",
    leerdoel: "Je kind leert gradaties in emoties te herkennen en signaleert wanneer het hulp nodig heeft.",
    bron: "Huebner (2005) - What to Do When Your Temper Flares",
    themes: ["adhd", "gedragsproblemen"],
  },
  {
    id: "gedrag_emot_04",
    title: "Valideren zonder oplossen",
    skill: "Emotiecoaching",
    description: "Wanneer je kind vandaag vertelt over iets moeilijks, oefen dan om alleen te luisteren en te valideren — zonder advies of oplossing.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Vaders hebben vaak de neiging om problemen op te willen lossen. Maar een kind dat zich overweldigd voelt, heeft eerst erkenning nodig. Validatie kalmeert het zenuwstelsel en opent de deur naar oplossingen.",
    skillTip: "Gebruik zinnen als: 'Dat klinkt echt moeilijk', 'Ik snap dat je daar boos van wordt', 'Wat zwaar voor je'. Tel in gedachten tot 10 voordat je een oplossing aanbiedt.",
    vermijd: "Meteen zeggen 'maar je had ook...' of 'volgende keer moet je...' Oplossingen komen later — eerst voelen.",
    leerdoel: "Je oefent het onderscheid tussen luisteren en oplossen, en ontdekt hoe krachtig validatie is.",
    bron: "Gottman & DeClaire (1997) - The Heart of Parenting",
    themes: ["hooggevoelig", "gedragsproblemen"],
  },
  {
    id: "gedrag_emot_05",
    title: "De boosheidskaart",
    skill: "Emotiecoaching",
    description: "Teken samen met je kind een 'landkaart van boosheid': waar in het lichaam voelt het kind boosheid en hoe ziet het eruit?",
    duration: "15 min",
    ageGroups: ["6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Boosheid heeft altijd een fysieke component — spierspanning, warmte, een bonkend hart. Door boosheid te 'mappen' in het lichaam leren kinderen vroege signalen herkennen, wat hen meer controle geeft.",
    skillTip: "Teken samen een lichaamscontour. Laat je kind met kleuren aangeven: 'Waar voel je boosheid? Is het rood, heet, koud, trillerig?' Doe het ook voor jezelf als voorbeeld.",
    vermijd: "Boosheid als negatief bestempelen ('je moet niet zo boos worden'). Boosheid is een normale emotie — het gaat om hoe je ermee omgaat.",
    leerdoel: "Je kind leert boosheid als een fysiek signaal herkennen in plaats van er door overspoeld te worden.",
    bron: "Van der Kolk (2014) - The Body Keeps the Score",
    themes: ["gedragsproblemen", "prikkelverwerking"],
  },
  {
    id: "gedrag_emot_06",
    title: "Emotie-coaching na een meltdown",
    skill: "Emotiecoaching",
    description: "Oefen na een meltdown van je kind het gesprek in drie stappen: erkennen, benoemen, verbinden.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Een meltdown is geen bewuste keuze maar een overbelasting van het zenuwstelsel. Na de storm is er een venster waarin je kind ontvankelijk is voor emotionele verbinding en leren — mits je niet veroordeelt.",
    skillTip: "Wacht tot je kind weer rustig is. Stap 1: 'Dat was heel heftig voor je.' Stap 2: 'Je was echt boos/verdrietig/overweldigd.' Stap 3: 'Ik ben er voor je, ook als het moeilijk is.'",
    vermijd: "Direct na de meltdown een les willen trekken of straf geven. Het brein van je kind is dan nog niet in staat tot logisch denken.",
    leerdoel: "Je leert het juiste moment en de juiste woorden te kiezen om na een meltdown weer te verbinden.",
    bron: "Siegel & Bryson (2014) - No-Drama Discipline",
    themes: ["adhd", "gedragsproblemen", "prikkelverwerking"],
  },
  {
    id: "gedrag_emot_07",
    title: "Het emotiedagboek",
    skill: "Emotiecoaching",
    description: "Start met je kind (of voor jongere kinderen: voor je kind) een simpel emotiedagboek met drie smileys per dag.",
    duration: "5 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen met hooggevoeligheid of ADHD ervaren veel emoties in korte tijd maar kunnen ze moeilijk onderscheiden. Een dagelijks ritueel van emoties vastleggen helpt patronen te herkennen en emotioneel vocabulaire op te bouwen.",
    skillTip: "Gebruik drie momenten: ochtend, middag, avond. Laat je kind een smiley kiezen of tekenen. Vraag kort: 'Waarom die smiley?' Noteer het samen.",
    vermijd: "Het dagboek verplicht maken of als huiswerk presenteren. Het moet leuk en vrijwillig voelen.",
    leerdoel: "Je bouwt samen een gewoonte op waardoor je kind emoties leert herkennen en benoemen.",
    bron: "Brackett (2019) - Permission to Feel",
    themes: ["hooggevoelig", "adhd"],
  },
  {
    id: "gedrag_emot_08",
    title: "Achter de woede kijken",
    skill: "Emotiecoaching",
    description: "Oefen vandaag om bij elke uiting van boosheid van je kind te zoeken naar de emotie eronder: angst, verdriet, schaamte of frustratie.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Boosheid is bijna altijd een secundaire emotie. Eronder zit vaak angst ('ik kan dit niet'), schaamte ('ik deug niet') of verdriet ('niemand begrijpt me'). Door de primaire emotie te bereiken, bereik je ook je kind.",
    skillTip: "Vraag jezelf bij elke boze reactie af: 'Wat zou hij of zij écht voelen?' Probeer dit hardop te checken: 'Ik vraag me af of je eigenlijk een beetje bang of verdrietig bent.'",
    vermijd: "Je eigen interpretatie als waarheid presenteren. Soms zit er iets anders achter dan je denkt — laat je kind de expert zijn van zijn eigen gevoel.",
    leerdoel: "Je ontwikkelt het vermogen om voorbij het zichtbare gedrag naar de onderliggende emotie te kijken.",
    bron: "Tsabary (2010) - The Conscious Parent",
    themes: ["gedragsproblemen"],
  },
  {
    id: "gedrag_emot_09",
    title: "Sensorische emotiekaart",
    skill: "Emotiecoaching",
    description: "Help je kind om te verwoorden hoe zintuiglijke prikkels emoties oproepen: 'Als het te hard is voel ik me...'",
    duration: "10 min",
    ageGroups: ["6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen met prikkelverwerking-uitdagingen reageren emotioneel op sensorische input zonder te begrijpen waarom. Door de link tussen prikkel en emotie expliciet te maken, krijgen ze meer grip op hun reacties.",
    skillTip: "Gebruik voorbeelden: 'Als het te licht is in de klas, voel ik me...' of 'Als iemand me onverwacht aanraakt, word ik...' Laat je kind de zinnen aanvullen.",
    vermijd: "De antwoorden corrigeren of bagatelliseren. Elke sensorische ervaring is valide, ook als jij het niet zo ervaart.",
    leerdoel: "Je kind leert de verbinding leggen tussen zintuiglijke prikkels en emotionele reacties.",
    bron: "Miller et al. (2007) - Sensational Kids: Hope and Help for Children with SPD",
    themes: ["prikkelverwerking", "hooggevoelig"],
  },
  {
    id: "gedrag_emot_10",
    title: "De emotiegrens herkennen",
    skill: "Emotiecoaching",
    description: "Help je tiener om het verschil te herkennen tussen 'ik ben gefrustreerd' en 'ik ben aan het ontploffen' — en wat hij nodig heeft bij elk niveau.",
    duration: "15 min",
    ageGroups: ["10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Tieners met ADHD of gedragsproblemen hebben moeite met het herkennen van de overgang van mild ongemak naar volledige ontregeling. Door dit samen te verkennen geef je hen een instrument voor zelfregulatie.",
    skillTip: "Bespreek dit op een rustig moment. Vraag: 'Op een schaal van 1-10, wanneer merk je dat je niet meer helder kunt denken? Wat is het eerste signaal?' Maak samen een plan voor dat kantelpunt.",
    vermijd: "Dit gesprek voeren als je tiener al boos of ontregeld is. Kies een ontspannen moment, bijvoorbeeld tijdens een wandeling of autorit.",
    leerdoel: "Je tiener ontwikkelt een persoonlijk waarschuwingssysteem voor emotionele overbelasting.",
    bron: "Ramsay & Rostain (2015) - The Adult ADHD Tool Kit",
    themes: ["adhd", "gedragsproblemen"],
  },

  // ============================================================
  // ZELFREGULATIE (10 taken)
  // ============================================================
  {
    id: "gedrag_zelfreg_01",
    title: "De STOP-techniek",
    skill: "Zelfregulatie",
    description: "Leer je kind de STOP-techniek: Stop, Tel tot 5, Ontspan je schouders, Pak het opnieuw aan.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen met ADHD en impulsiviteitsproblemen handelen vaak voordat ze nadenken. De STOP-techniek creëert een kunstmatige pauze die de prefrontale cortex de kans geeft om de amygdala-reactie te temperen.",
    skillTip: "Oefen de STOP-techniek eerst op rustige momenten als een spel. Gebruik een echt stopbord-gebaar. Hoe vaker je oefent als het goed gaat, hoe beter het werkt als het spannend wordt.",
    vermijd: "De techniek als straf gebruiken ('doe nou STOP!'). Het moet een hulpmiddel voelen, niet een bevel. Oefen het ook voor jezelf als voorbeeld.",
    leerdoel: "Je kind leert een concrete, herhaalbare strategie om impulsief gedrag te onderbreken.",
    bron: "Barkley (2013) - Taking Charge of ADHD",
    themes: ["adhd", "gedragsproblemen"],
  },
  {
    id: "gedrag_zelfreg_02",
    title: "Ademanker",
    skill: "Zelfregulatie",
    description: "Oefen samen met je kind de 4-7-8 ademhaling: 4 tellen inademen, 7 tellen vasthouden, 8 tellen uitademen.",
    duration: "5 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Langzaam uitademen activeert het parasympathische zenuwstelsel en kalmeert de 'vecht-of-vlucht'-reactie. Voor kinderen die snel overprikkeld raken is dit een van de meest effectieve zelfregulatie-instrumenten.",
    skillTip: "Maak het visueel: laat je kind een denkbeeldige ballon opblazen of een kaars 'bijna' uitblazen. Doe het minstens drie rondes samen. Begin zelf en laat je kind volgen.",
    vermijd: "Zeggen 'adem nou eens rustig' midden in een crisis. Oefen op rustige momenten zodat het een automatisme wordt.",
    leerdoel: "Je kind krijgt een altijd beschikbaar hulpmiddel om het zenuwstelsel te kalmeren.",
    bron: "Weil (2015) - Breathing: The Master Key to Self Healing",
    themes: ["prikkelverwerking", "hooggevoelig"],
  },
  {
    id: "gedrag_zelfreg_03",
    title: "De pauzeknop",
    skill: "Zelfregulatie",
    description: "Spreek met je kind af dat jullie allebei een 'pauzeknop' mogen gebruiken als een situatie te intens wordt. Oefen hoe dat eruitziet.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Een afgesproken pauze-mechanisme voorkomt escalatie. Het is géén time-out als straf, maar een wederzijds hulpmiddel. Doordat beide partijen het mogen gebruiken, voelt het gelijkwaardig en respectvol.",
    skillTip: "Maak een fysiek gebaar af (hand omhoog, of een codewoord). Spreek af: na de pauze komen jullie altijd terug om het af te maken. De pauze is 5-10 minuten, op een veilige plek.",
    vermijd: "De pauze gebruiken om je kind te isoleren of als strafmaatregel. Het is een gezamenlijke afspraak, niet eenzijdig.",
    leerdoel: "Je creëert een veilige uitweg uit escalatie die jullie allebei mogen inzetten.",
    bron: "Greene (2014) - The Explosive Child",
    themes: ["gedragsproblemen", "adhd"],
  },
  {
    id: "gedrag_zelfreg_04",
    title: "Bewegingspauze",
    skill: "Zelfregulatie",
    description: "Bouw vandaag drie korte bewegingspauzes in op momenten dat je kind onrustig wordt.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Het ADHD-brein heeft meer dopamine nodig om te functioneren. Fysieke beweging is een van de snelste manieren om dopamine aan te maken. Na bewegen kunnen kinderen zich vaak beter concentreren en is er minder impulsief gedrag.",
    skillTip: "Plan de pauzes proactief in, niet pas als het misgaat. Bijvoorbeeld: na 20 minuten huiswerk een bewegingsbreak. Doe mee — samen bewegen is leuker én effectiever.",
    vermijd: "Beweging als straf inzetten ('ga maar rondjes rennen als je je niet gedraagt'). Beweging moet positief en preventief zijn.",
    leerdoel: "Je integreert beweging als positief regulatiemiddel in het dagritme van je kind.",
    bron: "Ratey (2008) - Spark: The Revolutionary New Science of Exercise and the Brain",
    themes: ["adhd"],
  },
  {
    id: "gedrag_zelfreg_05",
    title: "Het rusthoekje",
    skill: "Zelfregulatie",
    description: "Richt samen met je kind een 'rusthoekje' in huis in — een plek waar het naartoe kan als het even te veel wordt.",
    duration: "20 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Een vaste, veilige plek om tot rust te komen geeft het kind een concreet alternatief voor escalatie. Het verschilt fundamenteel van een 'strafhoek' — het is een hulpmiddel dat het kind zélf kiest te gebruiken.",
    skillTip: "Laat je kind meedenken: welke plek, welke kleuren, wat erin? Denk aan: zachte kussens, een knuffel, koptelefoon met muziek, een squishy. Noem het een 'chillplek' of 'ruststation'.",
    vermijd: "Het een 'time-out hoek' noemen of je kind ernaar sturen als straf. Het kind moet er vrijwillig naartoe willen gaan.",
    leerdoel: "Je creëert samen een fysieke plek die je kind helpt om zelfregulatie te oefenen.",
    bron: "Shanker (2016) - Self-Reg: How to Help Your Child Break the Stress Cycle",
    themes: ["prikkelverwerking", "hooggevoelig", "adhd"],
  },
  {
    id: "gedrag_zelfreg_06",
    title: "Jouw eigen regulatie-check",
    skill: "Zelfregulatie",
    description: "Monitor vandaag je eigen stressreacties op het gedrag van je kind. Waar zit jouw kantelpunt?",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Als vader ben je het regulatievoorbeeld voor je kind. Als jij ontregeld raakt door hun gedrag, escaleert de situatie altijd. Door je eigen triggers te kennen, kun je bewust de-escaleren voordat je reageert vanuit frustratie.",
    skillTip: "Noteer drie momenten vandaag waarop je merkte dat je geduld opraakte. Wat was de trigger? Wat voelde je in je lichaam? Wat deed je — en wat had je anders willen doen?",
    vermijd: "Jezelf veroordelen als je minder goed reageerde. Dit gaat over bewustwording, niet over perfectie. Elke vader heeft een grens.",
    leerdoel: "Je krijgt inzicht in je eigen regulatiepatronen en leert eerder in te grijpen bij jezelf.",
    bron: "Siegel & Hartzell (2003) - Parenting from the Inside Out",
    themes: ["gedragsproblemen"],
  },
  {
    id: "gedrag_zelfreg_07",
    title: "Zintuiglijk kalmeren",
    skill: "Zelfregulatie",
    description: "Ontdek samen met je kind welke zintuiglijke input kalmerend werkt: druk, beweging, geluid of aanraking.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Elk kind heeft een uniek sensorisch profiel. Sommige kinderen kalmeren door diepe druk (gewichtsdeken, stevige knuffel), anderen door ritmische beweging of zachte muziek. Door te ontdekken wat werkt, geef je je kind een persoonlijk kalmeringsmiddel.",
    skillTip: "Probeer vandaag drie dingen uit: een stevige knuffel (10 seconden), schommelen of wiegen, en rustige muziek. Vraag of laat merken welke het meest kalmerend werkt.",
    vermijd: "Aanraking forceren als je kind dat niet wil. Respecteer de sensorische voorkeuren — ook 'niet aanraken' is een geldige behoefte.",
    leerdoel: "Je ontdekt het sensorische kalmeringsprofiel van je kind en kunt dit preventief inzetten.",
    bron: "Kranowitz (2005) - The Out-of-Sync Child",
    themes: ["prikkelverwerking", "hooggevoelig"],
  },
  {
    id: "gedrag_zelfreg_08",
    title: "Timer als bondgenoot",
    skill: "Zelfregulatie",
    description: "Gebruik vandaag een visuele timer om je kind te helpen bij overgangen en taakvolharding. Laat het kind de timer zelf instellen.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen met ADHD hebben een verstoord tijdsbesef — 5 minuten kan aanvoelen als een uur. Een visuele timer maakt de tijd concreet en voorspelbaar, wat angst en weerstand vermindert bij overgangen.",
    skillTip: "Gebruik een timer waarbij je de tijd ziet afnemen (bijv. een zandloper of Time Timer-app). Laat je kind zelf de tijd instellen. Zeg: 'Over 5 minuten gaan we eten — jij mag de timer zetten.'",
    vermijd: "De timer als dreiging gebruiken ('als de timer afgaat en je bent niet klaar...'). De timer is een helper, geen scheidsrechter.",
    leerdoel: "Je kind ervaart meer controle over tijdsovergangen en ontwikkelt een beter tijdsbesef.",
    bron: "Barkley (2015) - Attention-Deficit Hyperactivity Disorder: A Handbook",
    themes: ["adhd"],
  },
  {
    id: "gedrag_zelfreg_09",
    title: "Grounding bij overprikkeling",
    skill: "Zelfregulatie",
    description: "Leer je kind de 5-4-3-2-1 grounding-techniek: 5 dingen zien, 4 horen, 3 voelen, 2 ruiken, 1 proeven.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Bij overprikkeling raakt het brein 'vast' in de stressreactie. De 5-4-3-2-1 techniek brengt de aandacht terug naar het hier en nu door alle zintuigen te activeren, waardoor de prefrontale cortex weer online komt.",
    skillTip: "Oefen het eerst als spel op een rustig moment: 'Noem 5 dingen die je ziet!' Maak het leuk. Zodra je kind de stappen kent, kun je het inzetten bij overprikkeling: 'Zullen we het zintuigenspel doen?'",
    vermijd: "De techniek afdwingen als je kind in volle paniek is. Begin dan met ademhaling en wacht tot het iets gezakt is.",
    leerdoel: "Je kind leert een concrete techniek om zichzelf te gronden bij zintuiglijke overbelasting.",
    bron: "Tolin (2012) - Face Your Fears: A Proven Plan to Beat Anxiety",
    themes: ["prikkelverwerking", "hooggevoelig"],
  },
  {
    id: "gedrag_zelfreg_10",
    title: "Het nee-moment vertragen",
    skill: "Zelfregulatie",
    description: "Oefen vandaag om bij impulsief 'nee' of verzet van je kind vijf seconden te wachten voordat je reageert.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Impulsief verzet triggert vaak een impulsieve reactie bij de vader. Door zelf 5 seconden pauze in te lassen, onderbreek je de actie-reactieketen. Die kleine vertraging geeft jouw brein én dat van je kind de kans om na te denken.",
    skillTip: "Tel in stilte tot 5, adem daarbij uit. Vraag je dan af: 'Is dit een machtsstrijd waard? Wat heeft mijn kind nu nodig?' Vaak is het antwoord: begrip, niet correctie.",
    vermijd: "De 5 seconden gebruiken om een 'betere straf' te bedenken. Het doel is de-escalatie, niet strategisch straffen.",
    leerdoel: "Je doorbreekt de automatische actie-reactiecyclus en modelleert zelfbeheersing voor je kind.",
    bron: "Kabat-Zinn & Kabat-Zinn (1997) - Everyday Blessings: The Inner Work of Mindful Parenting",
    themes: ["gedragsproblemen", "adhd"],
  },

  // ============================================================
  // GRENZEN (10 taken)
  // ============================================================
  {
    id: "gedrag_grenz_01",
    title: "Structuur zonder straf",
    skill: "Grenzen",
    description: "Vervang vandaag één strafdreiging door een duidelijke, rustige grens met een logisch gevolg.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Straf werkt op korte termijn via angst, maar ondermijnt op lange termijn de relatie en het zelfbeeld van het kind. Logische gevolgen leren het kind het verband tussen gedrag en uitkomst, zonder de relatie te beschadigen.",
    skillTip: "In plaats van 'als je niet opruimt, geen TV', probeer: 'Eerst opruimen, dan TV. Wat wil je eerst opruimen?' Geef keuze binnen de grens.",
    vermijd: "Lege dreigingen die je niet waarmaakt, of straffen die geen logisch verband hebben met het gedrag.",
    leerdoel: "Je leert grenzen te stellen die je kind iets leren in plaats van alleen te straffen.",
    bron: "Nelsen (2006) - Positive Discipline",
    themes: ["gedragsproblemen"],
  },
  {
    id: "gedrag_grenz_02",
    title: "De voorspelbaarheidslijst",
    skill: "Grenzen",
    description: "Maak samen een visueel dagschema dat je kind kan volgen. Hang het op een vaste plek.",
    duration: "20 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen met ADHD en gedragsproblemen hebben baat bij voorspelbaarheid. Visuele structuur vermindert onzekerheid en daarmee angst en oppositie. Het kind weet wat er komt, waardoor het minder weerstand hoeft te bieden.",
    skillTip: "Gebruik plaatjes of pictogrammen voor jongere kinderen. Laat je kind helpen met maken en ophangen. Bouw ruimte in voor keuzes: 'Na het eten mag jij kiezen: eerst tanden poetsen of eerst pyjama aan?'",
    vermijd: "Het schema rigide hanteren zonder flexibiliteit. Een schema is een leidraad, geen gevangenis. Onverwachte veranderingen kun je samen bespreken.",
    leerdoel: "Je creëert voorspelbaarheid die het aantal conflictmomenten vermindert.",
    bron: "Barkley (2013) - Taking Charge of ADHD",
    themes: ["adhd", "gedragsproblemen"],
  },
  {
    id: "gedrag_grenz_03",
    title: "Grenzen met warmte",
    skill: "Grenzen",
    description: "Oefen vandaag om elke grens die je stelt te combineren met een warme erkenning van wat je kind wil of voelt.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Een grens zonder warmte voelt als afwijzing. Een grens mét warmte voelt als veiligheid. Door te erkennen wat je kind wil én tegelijk de grens vast te houden, leer je je kind dat grenzen en liefde samengaan.",
    skillTip: "Formule: 'Ik snap dat je [wens van kind], EN toch is het nu tijd voor [grens].' Bijvoorbeeld: 'Ik snap dat je nog wil spelen, en het is nu bedtijd.'",
    vermijd: "Gebruik 'maar' niet na de erkenning ('ik snap het, MAAR...'). Gebruik 'en' — dat voelt gelijkwaardiger en minder als een afwijzing.",
    leerdoel: "Je combineert empathie en grenzen, waardoor je kind zich begrepen voelt zelfs bij een 'nee'.",
    bron: "Siegel & Bryson (2014) - No-Drama Discipline",
    themes: ["gedragsproblemen", "hooggevoelig"],
  },
  {
    id: "gedrag_grenz_04",
    title: "Keuze binnen kaders",
    skill: "Grenzen",
    description: "Bied je kind vandaag bij elk verzoek of grens twee acceptabele opties aan in plaats van één bevel.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen die veel weerstand vertonen, strijden vaak om controle. Door twee opties te geven geef je het gevoel van autonomie binnen veilige kaders. Het kind ervaart keuzevrijheid terwijl jij de kaders bepaalt.",
    skillTip: "Zeg: 'Wil je eerst je schoenen of eerst je jas aan?' in plaats van 'Doe je schoenen aan!' Beide opties zijn voor jou prima — het kind kiest welke het beste voelt.",
    vermijd: "Een open vraag stellen als er geen echte keuze is ('Wil je nu naar bed?' als dat geen optie is). Bied alleen echte keuzes.",
    leerdoel: "Je vermindert machtsstrijd door autonomie te bieden binnen duidelijke grenzen.",
    bron: "Faber & Mazlish (2012) - How to Talk So Kids Will Listen",
    themes: ["gedragsproblemen", "adhd"],
  },
  {
    id: "gedrag_grenz_05",
    title: "De sensorische grens",
    skill: "Grenzen",
    description: "Help je prikkelgevoelige kind om zijn eigen grenzen te leren kennen en communiceren: 'Dit is te veel voor mij.'",
    duration: "15 min",
    ageGroups: ["6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen met sensorische verwerkingsproblemen weten vaak niet dat ze grenzen mogen stellen aan prikkels. Door hen te leren dat 'het is te veel' een geaccepteerde boodschap is, geef je hen regie over hun eigen welzijn.",
    skillTip: "Oefen zinnen: 'Het is te hard voor mij', 'Ik heb even pauze nodig', 'Mag het zachter?' Spreek af dat deze zinnen altijd serieus worden genomen, ook door anderen in het gezin.",
    vermijd: "De grenzen van je kind overschrijven met 'het valt best mee' of 'doe niet zo moeilijk'. Sensorische grenzen zijn net zo reëel als fysieke grenzen.",
    leerdoel: "Je kind leert zijn eigen sensorische grenzen herkennen, communiceren en gerespecteerd zien.",
    bron: "Dunn (2007) - Living Sensationally",
    themes: ["prikkelverwerking", "hooggevoelig"],
  },
  {
    id: "gedrag_grenz_06",
    title: "Consequent zonder rigide",
    skill: "Grenzen",
    description: "Reflecteer op een recente situatie waarin je te streng of te toegeeflijk was. Zoek de middenweg.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Bij kinderen met uitdagend gedrag schieten vaders vaak door naar óf te autoritair (uit frustratie) óf te permissief (uit schuldgevoel). De kunst is autoritatief opvoeden: warm én consequent. Dit vraagt zelfkennis over je eigen patronen.",
    skillTip: "Denk aan een recent conflict. Score jezelf op twee schalen: warmte (1-10) en consequentheid (1-10). Het ideaal is hoog op beide. Waar zit je nu, en wat kun je bijstellen?",
    vermijd: "Jezelf veroordelen als je doorschoot. Opvoeden is een continu leerproces. Het feit dat je reflecteert, is al een overwinning.",
    leerdoel: "Je vindt de balans tussen warm en consequent die past bij jouw kind en jouw situatie.",
    bron: "Baumrind (1991) - The Influence of Parenting Style on Adolescent Competence",
    themes: ["gedragsproblemen"],
  },
  {
    id: "gedrag_grenz_07",
    title: "Huisregels helder maken",
    skill: "Grenzen",
    description: "Maak samen met je kind een kort lijstje van 3-5 huisregels. Formuleer ze positief ('we doen...' in plaats van 'je mag niet...').",
    duration: "15 min",
    ageGroups: ["6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen met ADHD en gedragsproblemen hebben baat bij heldere, weinig en positief geformuleerde regels. Negatieve regels ('niet rennen') activeren het stresssysteem. Positieve regels ('we lopen binnen') geven richting.",
    skillTip: "Maximaal 5 regels. Laat je kind meedenken. Formuleer ze als 'we'-regels: 'We praten rustig', 'We ruimen op als we klaar zijn.' Hang ze op een zichtbare plek.",
    vermijd: "Een waslijst aan regels die niemand kan onthouden. Minder regels betekent meer kans dat ze worden nageleefd.",
    leerdoel: "Je creëert een gezamenlijk kader van verwachtingen dat helder en haalbaar is voor je kind.",
    bron: "Webster-Stratton (2006) - The Incredible Years",
    themes: ["gedragsproblemen", "adhd"],
  },
  {
    id: "gedrag_grenz_08",
    title: "De overgangsaankondiging",
    skill: "Grenzen",
    description: "Kondig vandaag elke overgang minstens 5 minuten van tevoren aan. Geef een waarschuwing bij 5, 2 en 1 minuut.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Het ADHD-brein is 'hyperfocused' bezig en kan niet zomaar switchen. Een plotselinge overgang voelt als een gewelddadige onderbreking. Aankondigingen geven het brein tijd om af te ronden en zich voor te bereiden.",
    skillTip: "Gebruik een vaste formule: 'Over 5 minuten gaan we eten.' Bij 2 minuten: 'Nog 2 minuutjes, begin met afronden.' Bij 1 minuut: 'Laatste minuut!' Wees kalm en voorspelbaar.",
    vermijd: "Plotseling zeggen 'we gaan nu, kom!' zonder waarschuwing. Dit triggert vrijwel altijd verzet bij kinderen die moeite hebben met overgangen.",
    leerdoel: "Je voorkomt onnodige conflicten door overgangen voorspelbaar en geleidelijk te maken.",
    bron: "Barkley (2013) - Taking Charge of ADHD",
    themes: ["adhd"],
  },
  {
    id: "gedrag_grenz_09",
    title: "Prikkelgrens in de supermarkt",
    skill: "Grenzen",
    description: "Bereid je kind voor op een prikkelrijke situatie (supermarkt, winkelcentrum) door samen een plan te maken.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Supermarkten zijn een explosie van prikkels: licht, geluid, mensen, geuren, producten. Voor prikkelgevoelige kinderen is dit een recept voor een meltdown. Voorbereiding en een plan geven het kind houvast.",
    skillTip: "Bespreek vooraf: 'We gaan naar de supermarkt. Het kan druk zijn. Als het te veel wordt, mag je mijn hand pakken of zeggen: pauze. We halen 5 dingen en dan gaan we.' Geef je kind een taak (boodschappenlijstje bijhouden).",
    vermijd: "Boos worden als je kind in de winkel toch ontregeld raakt. Het plan is géén garantie — het is een hulpmiddel.",
    leerdoel: "Je leert prikkelrijke situaties samen voor te bereiden, waardoor je kind meer controle ervaart.",
    bron: "Kranowitz (2005) - The Out-of-Sync Child",
    themes: ["prikkelverwerking", "hooggevoelig"],
  },
  {
    id: "gedrag_grenz_10",
    title: "Grens herhalen zonder escaleren",
    skill: "Grenzen",
    description: "Oefen vandaag de 'gebroken plaat'-techniek: herhaal je grens maximaal drie keer, rustig en met dezelfde woorden, zonder volume te verhogen.",
    duration: "5 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Bij kinderen die testen en duwen is het verleidelijk om steeds luider of strenger te worden. Dit escaleert de situatie. Door kalm dezelfde boodschap te herhalen (maximaal 3x), communiceer je: de grens staat vast, en ik blijf rustig.",
    skillTip: "Kies korte, heldere woorden. Herhaal exact dezelfde zin. Na 3 keer: handel — help je kind fysiek (bijv. jas aandoen) of geef het logische gevolg. Niet blijven herhalen.",
    vermijd: "Eindeloos blijven herhalen (dat wordt zeuren) of bij de derde keer schreeuwen. Na 3 keer: actie, geen woorden meer.",
    leerdoel: "Je leert standvastig te zijn zonder te escaleren, en weet wanneer woorden plaatsmaken voor handelen.",
    bron: "Patterson (1982) - Coercive Family Process",
    themes: ["gedragsproblemen"],
  },

  // ============================================================
  // AUTONOMIE (10 taken)
  // ============================================================
  {
    id: "gedrag_auto_01",
    title: "De kleine baas",
    skill: "Autonomie",
    description: "Laat je kind vandaag één beslissing nemen die normaal voor hem wordt genomen: welke kleren, welk eten, welke route.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen die vaak gecorrigeerd worden door gedragsproblemen of ADHD verliezen het gevoel van competentie. Door hen keuzes te geven in het dagelijks leven herbouw je het gevoel 'ik kan iets, ik mag iets'.",
    skillTip: "Bied een keuze aan die echt telt. Niet 'rood of blauw shirt' maar iets dat het kind als betekenisvol ervaart. Respecteer de keuze ook als je het er niet mee eens bent.",
    vermijd: "De keuze terugdraaien als het kind iets 'geks' kiest (een winterjas in de lente). Laat natuurlijke gevolgen het werk doen waar het veilig is.",
    leerdoel: "Je versterkt het gevoel van eigenwaarde en competentie bij een kind dat veel correctie ervaart.",
    bron: "Deci & Ryan (2000) - Self-Determination Theory",
    themes: ["gedragsproblemen", "adhd"],
  },
  {
    id: "gedrag_auto_02",
    title: "Huiswerk op zijn manier",
    skill: "Autonomie",
    description: "Laat je kind vandaag zelf bepalen hoe het zijn huiswerk aanpakt: volgorde, plek, met of zonder muziek. Observeer wat werkt.",
    duration: "15 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Het ADHD-brein werkt anders — sommige kinderen concentreren zich beter met achtergrondgeluid of terwijl ze bewegen. Door je kind de regie te geven over de aanpak, ontdek je wat écht werkt in plaats van te forceren wat 'hoort'.",
    skillTip: "Zeg: 'Vandaag mag jij bepalen hoe je je huiswerk doet. Ik kijk wat er gebeurt.' Laat het kind experimenteren. Sta toe dat het staand werkt, op de grond zit, of met muziek op. Kijk naar het resultaat.",
    vermijd: "Na 5 minuten al ingrijpen omdat het er 'niet normaal' uitziet. Geef het een eerlijke kans. Beoordeel op resultaat, niet op methode.",
    leerdoel: "Je ontdekt welke werkomgeving bij het unieke brein van jouw kind past.",
    bron: "Hallowell & Ratey (2011) - Driven to Distraction",
    themes: ["adhd"],
  },
  {
    id: "gedrag_auto_03",
    title: "Probleemoplossing samen",
    skill: "Autonomie",
    description: "Betrek je kind actief bij het oplossen van een terugkerend probleem (bijv. ochtendchaos, ruzie bij bedtijd).",
    duration: "15 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Kinderen die betrokken worden bij het oplossen van problemen voelen zich gerespecteerd en competent. De oplossingen die ze zelf meebedenken worden beter nageleefd dan opgelegde regels.",
    skillTip: "Gebruik het CPS-model (Collaborative Problem Solving): 1) Benoem het probleem vanuit je kind, 2) Benoem jouw zorg, 3) Bedenk samen oplossingen. Laat het kind als eerste ideeën noemen.",
    vermijd: "Alleen de oplossingen accepteren die jij al in gedachten had. Sta open voor creatieve en onverwachte ideeën van je kind.",
    leerdoel: "Je kind ervaart dat het serieus wordt genomen en ontwikkelt probleemoplossend vermogen.",
    bron: "Greene (2014) - The Explosive Child",
    themes: ["gedragsproblemen", "adhd"],
  },
  {
    id: "gedrag_auto_04",
    title: "Het expertmoment",
    skill: "Autonomie",
    description: "Vraag je kind om jou iets te leren waar het goed in is. Laat het de leiding nemen.",
    duration: "15 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen met gedragsproblemen horen vaak wat ze fout doen. Door je kind als expert te positioneren in iets waar het goed in is, verschuif je het narratief van 'probleemkind' naar 'competent persoon'.",
    skillTip: "Het maakt niet uit wat: een game, een sport, een tekentechniek, iets over dieren. Luister echt, stel vragen, geef complimenten. Laat je kind stralen in zijn kracht.",
    vermijd: "Het overnemen, verbeteren of half opletten. Dit moment gaat volledig over het kind als de expert en jij als leerling.",
    leerdoel: "Je versterkt het zelfbeeld van je kind door het als kennisbron en expert te behandelen.",
    bron: "Dweck (2006) - Mindset: The New Psychology of Success",
    themes: ["gedragsproblemen"],
  },
  {
    id: "gedrag_auto_05",
    title: "Eigen rustplan maken",
    skill: "Autonomie",
    description: "Help je hooggevoelige kind om een persoonlijk 'rustplan' te maken voor momenten dat het overweldigd raakt.",
    duration: "15 min",
    ageGroups: ["6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Door het kind zelf te laten bepalen wat helpt bij overprikkeling geef je het regie over zijn eigen welzijn. Een zelfgekozen plan werkt beter dan een opgelegd plan, en versterkt het gevoel van autonomie.",
    skillTip: "Vraag: 'Wat helpt jou als het te druk wordt? Waar wil je naartoe? Wat wil je dan doen?' Schrijf het op een kaartje dat je kind bij zich kan dragen. Laat het kind het versieren.",
    vermijd: "Het plan voor je kind invullen. Stel vragen, maar laat de antwoorden van je kind leidend zijn — ook als jij andere dingen effectiever vindt.",
    leerdoel: "Je kind ontwikkelt een persoonlijke toolkit voor zelfregulatie dat bij hem of haar past.",
    bron: "Aron (2002) - The Highly Sensitive Child",
    themes: ["hooggevoelig", "prikkelverwerking"],
  },
  {
    id: "gedrag_auto_06",
    title: "Sterkepuntenjacht",
    skill: "Autonomie",
    description: "Schrijf vandaag samen met je kind vijf dingen op waar het goed in is. Hang de lijst op een prominente plek.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen met ADHD of gedragsproblemen krijgen disproportioneel veel negatieve feedback. Dit tast hun zelfbeeld aan. Door bewust sterke punten te benoemen en zichtbaar te maken, bouw je een tegenwicht op.",
    skillTip: "Begin zelf met twee sterke punten die je in je kind ziet. Vraag dan: 'Wat vind jij dat je goed kunt?' Wees concreet: niet 'je bent lief' maar 'je bent heel creatief met LEGO' of 'je kunt goed voor de hond zorgen'.",
    vermijd: "Sterke punten noemen die eigenlijk verkapte kritiek zijn ('je kunt goed stil zijn als je wilt'). Wees oprecht positief.",
    leerdoel: "Je verschuift de focus van problemen naar krachten, voor zowel jou als je kind.",
    bron: "Seligman (2011) - Flourish: A Visionary New Understanding of Happiness",
    themes: ["gedragsproblemen", "adhd"],
  },
  {
    id: "gedrag_auto_07",
    title: "De eigen-tempo ochtend",
    skill: "Autonomie",
    description: "Geef je kind morgenochtend 10 minuten extra en laat het zelf bepalen in welke volgorde het de ochtendroutine doet.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Ochtenden zijn een veelvoorkomend conflictmoment bij gezinnen met ADHD-kinderen. Door extra tijd en keuzevrijheid in te bouwen, verminder je de druk en geef je het kind eigenaarschap over het proces.",
    skillTip: "Maak een visueel lijstje van wat er moet gebeuren (aankleden, ontbijten, tanden poetsen). Zeg: 'Al deze dingen moeten voor [tijd] klaar zijn. Jij bepaalt de volgorde.' Vier succes.",
    vermijd: "Ongeduldig worden als het kind een 'inefficiënte' volgorde kiest. Het gaat om het eindresultaat, niet om de route ernaartoe.",
    leerdoel: "Je vermindert ochtendstress door autonomie en eigenaarschap te bieden binnen een helder tijdskader.",
    bron: "Dawson & Guare (2009) - Smart but Scattered",
    themes: ["adhd"],
  },
  {
    id: "gedrag_auto_08",
    title: "Sensorisch paspoort",
    skill: "Autonomie",
    description: "Laat je kind een 'sensorisch paspoort' maken: welke prikkels vindt het fijn, welke niet, en hoe kan het dat aan anderen uitleggen?",
    duration: "20 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Zelfkennis over sensorische voorkeuren geeft kinderen met prikkelgevoeligheid het vermogen om voor zichzelf op te komen. Een 'sensorisch paspoort' maakt het bespreekbaar — ook met leerkrachten of andere volwassenen.",
    skillTip: "Maak categorieën: geluid, licht, aanraking, geuren, smaken, drukte. Laat je kind bij elk aangeven: 'Dit vind ik fijn / Dit is te veel / Dit kan ik niet hebben.' Schrijf het op als een echt paspoort.",
    vermijd: "Oordelen over de voorkeuren ('iedereen vindt dat toch normaal?'). Het sensorische profiel van je kind is uniek en valide.",
    leerdoel: "Je kind ontwikkelt een taal en een hulpmiddel om sensorische behoeften te communiceren aan de wereld om hem heen.",
    bron: "Miller et al. (2007) - Sensational Kids",
    themes: ["prikkelverwerking", "hooggevoelig"],
  },
  {
    id: "gedrag_auto_09",
    title: "Laat het mislukken",
    skill: "Autonomie",
    description: "Sta vandaag bewust toe dat je kind iets probeert dat waarschijnlijk mislukt — en wees er voor het kind als het misgaat.",
    duration: "15 min",
    ageGroups: ["6-9", "10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Kinderen met ADHD of hooggevoeligheid worden vaak teveel beschermd tegen mislukking. Maar leren omgaan met falen is essentieel voor veerkracht. De kunst is: niet beschermen tegen de teleurstelling, maar er samen doorheen gaan.",
    skillTip: "Zie het mislukken aankomen? Laat het gebeuren (mits veilig). Troost zonder 'ik had het je toch gezegd'. Zeg: 'Balen hè. Wat heb je ervan geleerd? Wil je het opnieuw proberen?'",
    vermijd: "Zeggen 'zie je wel' of het kind beschermen tegen elk ongemak. Falen is geen ramp als papa er is om het op te vangen.",
    leerdoel: "Je kind ervaart dat falen mag, en dat jij er bent om samen te reflecteren en opnieuw te proberen.",
    bron: "Lahey (2015) - The Gift of Failure",
    themes: ["hooggevoelig", "gedragsproblemen"],
  },
  {
    id: "gedrag_auto_10",
    title: "De verantwoordelijkheidstrap",
    skill: "Autonomie",
    description: "Geef je kind één nieuwe verantwoordelijkheid die past bij zijn leeftijd en capaciteiten. Coach vanuit de zijlijn.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen met gedragsproblemen worden vaak gezien als 'niet verantwoordelijk genoeg'. Door hen bewust verantwoordelijkheid te geven — en te coachen in plaats van te controleren — bouw je competentie en zelfvertrouwen op.",
    skillTip: "Kies iets dat haalbaar is: tafel dekken, de hond voeren, boodschappenlijstje schrijven. Leg uit waarom het belangrijk is. Controleer niet elke stap — check het resultaat en geef positieve feedback.",
    vermijd: "Te snel overnemen als het niet perfect gaat. Het gaat om het proces van verantwoordelijkheid, niet om het perfecte resultaat.",
    leerdoel: "Je versterkt het competentiegevoel van je kind door vertrouwen te tonen in zijn capaciteiten.",
    bron: "Nelsen (2006) - Positive Discipline",
    themes: ["gedragsproblemen", "adhd"],
  },

  // ============================================================
  // HERSTEL (10 taken)
  // ============================================================
  {
    id: "gedrag_herst_01",
    title: "Sorry zeggen als vader",
    skill: "Herstel",
    description: "Bied je kind een oprechte verontschuldiging aan voor een moment waarop je te streng, ongeduldig of oneerlijk reageerde.",
    duration: "5 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen met gedragsproblemen horen vaak dat zíj sorry moeten zeggen. Als een vader dat zelf doet, modelleert hij dat fouten maken menselijk is en dat herstellen kracht toont, niet zwakte.",
    skillTip: "Wees specifiek: 'Sorry dat ik gisteren zo schreeuwde toen je je schoenen niet kon vinden. Dat was niet oké. Jij verdient het dat ik rustig blijf.' Geen 'maar' erachter.",
    vermijd: "Een 'sorry, maar...'-excuus dat eigenlijk een verwijt is. Een echte sorry heeft geen staart.",
    leerdoel: "Je modelleert herstelgedrag en laat je kind zien dat ook grote mensen fouten maken en herstellen.",
    bron: "Gottman (1999) - The Seven Principles for Making Marriage Work (applied to parenting)",
    themes: ["gedragsproblemen"],
  },
  {
    id: "gedrag_herst_02",
    title: "Na de storm",
    skill: "Herstel",
    description: "Zoek na een conflict of meltdown bewust het gesprek op om te verbinden en samen te bespreken wat er gebeurde.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Na een conflict is er een herstelvenster: een periode waarin het kind ontvankelijk is voor verbinding en leren. Hoe sneller je herstelt, hoe minder schade aan de relatie en het vertrouwen.",
    skillTip: "Wacht tot jullie beiden rustig zijn. Begin met: 'Dat was heftig hè, voor ons allebei.' Vraag: 'Wat had jij nodig op dat moment? Wat had ik anders kunnen doen?' Deel ook wat jij voelde.",
    vermijd: "Het gesprek als verhoor gebruiken ('waarom deed je dat?'). Herstel gaat over verbinden, niet over schuldvraag.",
    leerdoel: "Je leert herstelmomenten te benutten om de relatie te versterken na conflict.",
    bron: "Tronick (2007) - The Neurobehavioral and Social-Emotional Development of Infants and Children",
    themes: ["gedragsproblemen", "adhd"],
  },
  {
    id: "gedrag_herst_03",
    title: "Schoolrapport-debrief",
    skill: "Herstel",
    description: "Bespreek een negatief schoolbericht of rapport met je kind op een manier die het kind niet breekt maar opbouwt.",
    duration: "15 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Kinderen met ADHD of gedragsproblemen krijgen regelmatig negatieve berichten van school. Hoe jij als vader hierop reageert bepaalt of je kind zich gesteund of veroordeeld voelt. Je kunt de buffer zijn tussen school en je kind.",
    skillTip: "Begin met: 'Ik heb een bericht van school gelezen. Hoe was het voor jou vandaag?' Luister eerst. Erken de moeilijkheid. Zoek samen naar wat beter kan, zonder te straffen voor wat er fout ging.",
    vermijd: "Zeggen 'de juf zegt dat je weer...'. Ga naast je kind staan, niet tegenover hem. Jullie zijn een team, niet tegenstanders.",
    leerdoel: "Je leert het brugfiguur te zijn tussen school en kind, en voorkomt dat negatieve berichten het zelfbeeld beschadigen.",
    bron: "Rief (2005) - How to Reach and Teach Children with ADD/ADHD",
    themes: ["adhd", "gedragsproblemen"],
  },
  {
    id: "gedrag_herst_04",
    title: "Het herstelritueel",
    skill: "Herstel",
    description: "Bedenk samen met je kind een vast ritueel na een ruzie: een geheim handgebaar, een knuffel, of een codewoord dat zegt 'het is weer goed'.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Een vast herstelritueel verlaagt de drempel om na een conflict weer naar elkaar toe te gaan. Het creëert veiligheid: hoe heftig het ook was, er is altijd een weg terug naar verbinding.",
    skillTip: "Laat je kind meedenken: 'Hoe weten wij dat het na een ruzie weer goed is? Zullen we iets afspreken?' Misschien is het een vuistje, een knuffel van 10 seconden, of een woord als 'reset'.",
    vermijd: "Het ritueel afdwingen als het kind er nog niet aan toe is. Het ritueel markeert het einde van herstel, het vervangt het niet.",
    leerdoel: "Je creëert een veilig en voorspelbaar herstelpatroon dat jullie allebei kennen en kunnen initiëren.",
    bron: "Hughes (2009) - Attachment-Focused Parenting",
    themes: ["gedragsproblemen"],
  },
  {
    id: "gedrag_herst_05",
    title: "Prikkel-excuus",
    skill: "Herstel",
    description: "Erken naar je kind dat een overprikkelde reactie van jullie allebei niet ging over 'stout zijn' maar over 'te veel prikkels'.",
    duration: "5 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Na een meltdown door overprikkeling voelen kinderen zich vaak beschaamd. Door expliciet te benoemen dat het om prikkels ging en niet om slecht gedrag, bescherm je het zelfbeeld van je kind en normaliseer je de ervaring.",
    skillTip: "Zeg: 'Het was heel druk in die winkel hè. Jouw hoofd kreeg te veel prikkels tegelijk. Dat is niet jouw schuld — je brein had even pauze nodig.' Gebruik taal die externaliseert: het brein, niet het kind.",
    vermijd: "Zeggen 'je had gewoon rustig moeten blijven'. Overprikkeling is geen keuze — het is een reactie van het zenuwstelsel.",
    leerdoel: "Je leert overprikkeling te normaliseren en te scheiden van het karakter of de wil van je kind.",
    bron: "Shanker (2016) - Self-Reg",
    themes: ["prikkelverwerking", "hooggevoelig"],
  },
  {
    id: "gedrag_herst_06",
    title: "Breuk en herstel journaal",
    skill: "Herstel",
    description: "Schrijf voor jezelf op wat er vandaag goed ging en wat er misging in de omgang met je kind. Zonder oordeel.",
    duration: "10 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Reflecteren op breuken en herstelmomenten is de kern van groei als ouder. Onderzoek toont dat niet de afwezigheid van conflicten, maar het vermogen tot herstel de kwaliteit van de ouder-kindrelatie bepaalt.",
    skillTip: "Schrijf drie dingen op: 1) Een moment dat goed ging en waarom, 2) Een moment dat misging en wat je triggerde, 3) Hoe je het morgen anders zou aanpakken. Kort en eerlijk.",
    vermijd: "Alleen focussen op wat er fout ging. Breuk en herstel horen bij elkaar — vier ook je herstelmomenten.",
    leerdoel: "Je ontwikkelt het vermogen om met mildheid naar jezelf en je ouderschap te kijken.",
    bron: "Tronick (2007) - The Neurobehavioral Development of Infants and Children",
    themes: ["gedragsproblemen"],
  },
  {
    id: "gedrag_herst_07",
    title: "Terugkeer na afzondering",
    skill: "Herstel",
    description: "Als je kind zich na een conflict heeft teruggetrokken, oefen dan om op het juiste moment weer toenadering te zoeken.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Hooggevoelige kinderen trekken zich na conflict vaak terug om te verwerken. Ze hebben die tijd nodig, maar ook het signaal dat jij terugkomt. De kunst is wachten tot het kind er klaar voor is, en dan met warmte terugkeren.",
    skillTip: "Geef ruimte (5-15 minuten). Klop dan zachtjes op de deur of ga in de buurt zitten. Zeg: 'Ik ben er als je er klaar voor bent.' Forceer geen gesprek — soms is een kop chocolademelk genoeg.",
    vermijd: "Het kind te lang alleen laten als 'les' of 'straf'. Terugtrekken na conflict is verwerking, niet opstandigheid.",
    leerdoel: "Je leert het verschil tussen ruimte geven en verwaarlozen, en kiest het juiste moment voor toenadering.",
    bron: "Aron (2002) - The Highly Sensitive Child",
    themes: ["hooggevoelig"],
  },
  {
    id: "gedrag_herst_08",
    title: "De herstart",
    skill: "Herstel",
    description: "Gebruik het concept 'herstart' na een moeilijke ochtend: 'We beginnen opnieuw. Deze middag is een nieuw begin.'",
    duration: "5 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen met ADHD of gedragsproblemen hebben een korter werkgeheugen voor emoties — ze zijn vaak sneller 'over' een conflict dan volwassenen. Door een herstart aan te bieden, sluit je aan bij hun tempo in plaats van vast te houden aan jouw frustratie.",
    skillTip: "Zeg op een luchtige toon: 'Weet je wat, die ochtend was niet top. Herstart! Vanaf nu is het een nieuwe dag.' Een high five of handdruk maakt het tastbaar.",
    vermijd: "De herstart gebruiken om het conflict onder het tapijt te vegen. Erken eerst kort wat er gebeurde, en bied dan de herstart aan.",
    leerdoel: "Je leert loslaten na conflict en geeft je kind de ervaring dat elke dag een nieuwe kans is.",
    bron: "Phelan (2010) - 1-2-3 Magic",
    themes: ["adhd", "gedragsproblemen"],
  },
  {
    id: "gedrag_herst_09",
    title: "Herstel met de leerkracht",
    skill: "Herstel",
    description: "Neem contact op met de leerkracht van je kind — niet om te klagen, maar om samen te zoeken naar wat je kind nodig heeft.",
    duration: "20 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Ouders van kinderen met ADHD of gedragsproblemen hebben soms een gespannen relatie met school. Door proactief en samenwerkend contact te zoeken — vanuit het perspectief van het kind — bouw je een steunnetwerk dat je kind ten goede komt.",
    skillTip: "Begin het gesprek met: 'Ik wil graag samen kijken wat [naam] nodig heeft om het goed te doen op school. Wat valt u op? Wat werkt wél?' Vermijd een klachtgesprek of verdediging.",
    vermijd: "In de verdediging schieten ('mijn kind doet thuis prima!'). School en thuis zijn verschillende contexten — beide ervaringen zijn valide.",
    leerdoel: "Je bouwt een samenwerkingsrelatie op met school die je kind steunt in plaats van onder druk zet.",
    bron: "DuPaul & Stoner (2014) - ADHD in the Schools",
    themes: ["adhd", "gedragsproblemen"],
  },
  {
    id: "gedrag_herst_10",
    title: "Vergeven en loslaten",
    skill: "Herstel",
    description: "Reflecteer op een moment waarop je boos bleef op je kind langer dan nodig. Oefen bewust loslaten.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Vaders van kinderen met uitdagend gedrag kunnen onbewust wrok opbouwen. Dit vergiftigt de relatie langzaam. Bewust loslaten — niet het gedrag goedkeuren, maar de boosheid laten gaan — is essentieel voor een gezonde band.",
    skillTip: "Denk aan een recent moment waarop je langer boos bleef dan nodig. Vraag jezelf: 'Waar gaat mijn boosheid écht over? Is het dit ene incident of een opgestapelde frustratie?' Schrijf het op en scheur het papier op.",
    vermijd: "Loslaten verwarren met alles accepteren. Je mag grenzen stellen én tegelijk loslaten. Het gaat om de emotionele last, niet om de gedragsverwachtingen.",
    leerdoel: "Je leert onderscheid te maken tussen gezonde grenzen en ongezonde wrok, en oefent bewust loslaten.",
    bron: "Kabat-Zinn (2013) - Full Catastrophe Living",
    themes: ["gedragsproblemen"],
  },

  // ============================================================
  // VERBINDING (10 taken)
  // ============================================================
  {
    id: "gedrag_verb_01",
    title: "Speciaal samen-moment",
    skill: "Verbinding",
    description: "Plan vandaag 15 minuten onverdeelde aandacht met je kind. Geen correctie, geen les — alleen plezier.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen met gedragsproblemen ontvangen gemiddeld veel meer negatieve dan positieve aandacht. Door bewust plezierige, corrigeervrije tijd in te plannen, vul je de 'emotionele bankrekening' aan waarop je later kunt teren.",
    skillTip: "Laat je kind kiezen wat jullie doen. Volg het kind — geef geen aanwijzingen, verbeter niets, stel geen regels. Zeg: 'Dit kwartier is van jou. Wat wil je doen?'",
    vermijd: "Stiekem toch correctie of opvoeding inbouwen ('dat kun je beter zo doen'). Dit is puur speeltijd, zonder agenda.",
    leerdoel: "Je bouwt een positief tegenwicht op tegen de dagelijkse correcties die je kind ervaart.",
    bron: "Landreth (2012) - Play Therapy: The Art of the Relationship",
    themes: ["gedragsproblemen", "adhd"],
  },
  {
    id: "gedrag_verb_02",
    title: "Verbinding door beweging",
    skill: "Verbinding",
    description: "Doe samen een fysieke activiteit die je kind leuk vindt: voetballen, dansen, stoeien, fietsen.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Fysiek samen bezig zijn produceert oxytocine en endorfine bij zowel vader als kind. Voor kinderen met ADHD is bewegen bovendien de beste manier om dopamine vrij te maken — dus je combineert verbinding met regulatie.",
    skillTip: "Kies iets actief en niet-competitief. Samen rennen, een dansje maken in de keuken, of stoeien op het bed. Lach samen. Lichamelijk contact en lachen zijn de snelste weg naar verbinding.",
    vermijd: "Er een les of prestatie van maken ('je moet beter mikken'). Het gaat om samen plezier hebben, niet om presteren.",
    leerdoel: "Je combineert verbinding en beweging, twee fundamentele behoeften van je kind.",
    bron: "Ratey (2008) - Spark: The Revolutionary New Science of Exercise and the Brain",
    themes: ["adhd"],
  },
  {
    id: "gedrag_verb_03",
    title: "Het positieve logboek",
    skill: "Verbinding",
    description: "Schrijf vanavond drie dingen op die je kind vandaag goed deed. Vertel minstens één ervan aan je kind.",
    duration: "5 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Uit onderzoek blijkt dat kinderen met gedragsproblemen tot 10 keer meer negatieve dan positieve opmerkingen per dag horen. Een bewuste focus op het positieve herstelt de balans en versterkt gewenst gedrag effectiever dan straf.",
    skillTip: "Zoek naar kleine dingen: even rustig wachten, iets delen, geduld hebben. Zeg: 'Ik zag vandaag dat je [concreet gedrag]. Dat vond ik echt knap.' Wees specifiek, niet generiek.",
    vermijd: "Alleen grote successen benoemen. Het gaat juist om de kleine momenten die je kind normaal niet hoort.",
    leerdoel: "Je traint je brein om het positieve te zien in plaats van automatisch op het negatieve te focussen.",
    bron: "Webster-Stratton (2006) - The Incredible Years",
    themes: ["gedragsproblemen"],
  },
  {
    id: "gedrag_verb_04",
    title: "Samen in de natuur",
    skill: "Verbinding",
    description: "Maak een wandeling met je kind in de natuur. Geen doel, geen haast — alleen samen buiten zijn.",
    duration: "20 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Natuur heeft een bewezen kalmerend effect op het zenuwstelsel — bij kinderen met ADHD vermindert 20 minuten in het groen al de symptomen. Gecombineerd met vader-kindverbinding is dit een van de krachtigste interventies.",
    skillTip: "Laat het kind het tempo bepalen. Sta stil bij alles wat aandacht trekt: een kever, een steen, een plas. Stel open vragen: 'Wat zie je?' Dit is wandelen als mindfulness, niet als sport.",
    vermijd: "Het een prestatie maken ('we gaan 5 kilometer lopen'). Het doel is ontspanning en verbinding, niet afstand of tempo.",
    leerdoel: "Je gebruikt de kalmerende kracht van natuur om te verbinden op een manier die het zenuwstelsel van je kind ondersteunt.",
    bron: "Kuo & Taylor (2004) - A Potential Natural Treatment for ADHD",
    themes: ["adhd", "hooggevoelig"],
  },
  {
    id: "gedrag_verb_05",
    title: "Het aanrakingsritme",
    skill: "Verbinding",
    description: "Ontdek welke vorm van fysiek contact je kind prettig vindt en bouw dit bewust in gedurende de dag.",
    duration: "10 min",
    ageGroups: ["0-2", "3-5", "6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Sommige prikkelgevoelige kinderen vermijden aanraking, terwijl anderen juist diepe druk zoeken. Door te ontdekken welke aanraking kalmerend werkt, heb je een krachtig verbindings- en regulatie-instrument.",
    skillTip: "Experimenteer: een aai over het hoofd, een stevige knuffel, rugkrabben, hand vasthouden. Let op de reactie van je kind — welke wordt opgezocht, welke wordt vermeden? Respecteer de grenzen.",
    vermijd: "Aanraking forceren omdat je denkt dat het 'goed voor de band' is. Voor een tactiel gevoelig kind kan ongewenste aanraking juist stress veroorzaken.",
    leerdoel: "Je kent de aanrakingsvoorkeuren van je kind en kunt dit inzetten voor verbinding en kalmering.",
    bron: "Field (2014) - Touch Therapy",
    themes: ["prikkelverwerking", "hooggevoelig"],
  },
  {
    id: "gedrag_verb_06",
    title: "Interesse tonen in de obsessie",
    skill: "Verbinding",
    description: "Vraag je kind vandaag om je alles te vertellen over zijn huidige 'obsessie' — een game, serie, hobby of onderwerp. Luister oprecht.",
    duration: "15 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kinderen met ADHD hebben vaak intense, wisselende interesses (hyperfocus). Door oprechte interesse te tonen in wat hen fascineert, communiceer je: 'Jij bent belangrijk voor mij, inclusief de dingen die jou boeien.'",
    skillTip: "Stel echte vragen: 'Hoe werkt dat? Waarom vind je dat zo leuk? Kun je me meer vertellen?' Probeer niet te oordelen, ook niet als het onderwerp jou niet boeit. Het gaat om de verbinding.",
    vermijd: "Na 2 minuten afhaken of het onderwerp afkappen ('ja ja, dat weet ik wel'). Je kind merkt of je echt luistert.",
    leerdoel: "Je versterkt de band door oprechte interesse te tonen in de passies van je kind.",
    bron: "Hallowell & Ratey (2011) - Driven to Distraction",
    themes: ["adhd"],
  },
  {
    id: "gedrag_verb_07",
    title: "Het bedtijdgesprek",
    skill: "Verbinding",
    description: "Bouw een vast bedtijdritueel in van 5 minuten: drie vragen — het leukste, het moeilijkste, en wat je kind morgen wil doen.",
    duration: "5 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Bedtijd is voor veel gezinnen een conflictmoment. Door een positief gespreksritueel toe te voegen, wordt het een moment van verbinding. Kinderen die de dag op een warme manier afsluiten slapen beter en voelen zich veiliger.",
    skillTip: "Maak het kort en voorspelbaar. Vraag elke avond dezelfde drie vragen. Deel ook jouw antwoorden. Eindig met iets fysieks: een knuffel, aai over het hoofd, of 'geheime handdruk'.",
    vermijd: "Het bedtijdgesprek gebruiken om het gedrag van de dag te evalueren. Dit is een warm moment, geen functioneringsgesprek.",
    leerdoel: "Je creëert een dagelijks verbindingsmoment dat veiligheid en vertrouwen opbouwt.",
    bron: "Sunderland (2006) - The Science of Parenting",
    themes: ["gedragsproblemen", "hooggevoelig"],
  },
  {
    id: "gedrag_verb_08",
    title: "Verbinding vóór correctie",
    skill: "Verbinding",
    description: "Oefen vandaag het principe 'connect before you correct': maak eerst verbinding voordat je een grens stelt of corrigeert.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Een kind dat zich verbonden voelt met de ouder is ontvankelijker voor correctie. Door eerst op emotioneel niveau in te checken ('ik zie dat het moeilijk is'), open je de deur naar samenwerking in plaats van verzet.",
    skillTip: "Bij elke correctie: begin met oogcontact en een korte erkenning. 'Ik zie dat je het lastig vindt. We gaan het samen oplossen.' Pas dan de grens of instructie.",
    vermijd: "Meteen 'nee!' of 'stop daarmee!' roepen. Eén seconde extra voor verbinding bespaart minuten escalatie.",
    leerdoel: "Je leert dat verbinding de effectiviteit van grenzen versterkt in plaats van ondermijnt.",
    bron: "Siegel & Bryson (2011) - The Whole-Brain Child",
    themes: ["gedragsproblemen", "adhd"],
  },
  {
    id: "gedrag_verb_09",
    title: "De stilte-wandeling",
    skill: "Verbinding",
    description: "Maak met je hooggevoelige kind een 'stilte-wandeling': 5 minuten samen wandelen zonder te praten, enkel luisterend naar de omgeving.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Hooggevoelige kinderen ervaren verbinding niet alleen door praten, maar juist ook door gedeelde stilte. Een stilte-wandeling biedt de rustgevende combinatie van beweging, natuur en nabijheid zonder sensorische druk.",
    skillTip: "Spreek vooraf af: 'We gaan 5 minuten wandelen zonder te praten. We luisteren alleen.' Na afloop kun je kort delen wat jullie hoorden. Dit is bijzonder krachtig voor kinderen die overprikkeld zijn van een drukke dag.",
    vermijd: "De stilte opvullen als het ongemakkelijk voelt. Vertrouw op het proces — stilte is voor veel hooggevoelige kinderen een cadeau.",
    leerdoel: "Je ontdekt dat verbinding ook in stilte kan bestaan en leert je kind dat aanwezigheid niet altijd woorden nodig heeft.",
    bron: "Aron (2002) - The Highly Sensitive Child",
    themes: ["hooggevoelig"],
  },
  {
    id: "gedrag_verb_10",
    title: "Het teamgevoel",
    skill: "Verbinding",
    description: "Creëer een 'wij tegen het probleem'-gevoel door het lastige gedrag als iets te bespreken dat jullie samen aanpakken.",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Externaliseren — het probleem buiten het kind plaatsen — is een krachtige techniek uit de narratieve therapie. In plaats van 'jij bent lastig' wordt het 'samen hebben wij last van die boosheid'. Dit beschermt het zelfbeeld en versterkt de samenwerking.",
    skillTip: "Geef het probleem een naam: 'de driftmonster', 'het druk-beestje', 'de prikkelstorm'. Zeg: 'Wanneer die driftmonster langskomt, hoe kunnen wij hem dan samen verslaan?' Maak er een gezamenlijke missie van.",
    vermijd: "Het kind zelf het probleem noemen. Het verschil tussen 'jij bent boos' en 'die boosheid pakt je weer' is enorm voor het zelfbeeld van een kind.",
    leerdoel: "Je externaliseert het probleem zodat je kind en jij samen een team vormen tegen het lastige gedrag.",
    bron: "White & Epston (1990) - Narrative Means to Therapeutic Ends",
    themes: ["gedragsproblemen", "adhd"],
  },

  // ============================================================
  // REFLECTIE (10 taken)
  // ============================================================
  {
    id: "gedrag_refl_01",
    title: "Jouw eigen ADHD-spiegel",
    skill: "Reflectie",
    description: "Reflecteer eerlijk: herken je kenmerken van ADHD, hooggevoeligheid of impulsiviteit bij jezelf? Hoe beïnvloedt dat je ouderschap?",
    duration: "10 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "ADHD en hooggevoeligheid zijn sterk erfelijk. Veel vaders herkennen de uitdagingen van hun kind in zichzelf. Dit kan troost bieden ('ik begrijp je') maar ook een trigger zijn ('ik wil niet dat jij dezelfde fouten maakt'). Bewustwording is de eerste stap.",
    skillTip: "Stel jezelf deze vragen: Was ik als kind ook zo? Welke eigenschappen van mijn kind herken ik in mezelf? Reageer ik soms op mijn kind vanuit mijn eigen onverwerkte ervaringen?",
    vermijd: "Dit als excuus gebruiken ('ik ben ook zo, ik kan er niets aan doen') of als last ('mijn kind heeft het ook van mij, het is mijn schuld').",
    leerdoel: "Je herkent hoe jouw eigen neurodiversiteit je opvoedstijl beïnvloedt — zowel positief als negatief.",
    bron: "Siegel & Hartzell (2003) - Parenting from the Inside Out",
    themes: ["adhd", "hooggevoelig"],
  },
  {
    id: "gedrag_refl_02",
    title: "Het stigma ontrafelen",
    skill: "Reflectie",
    description: "Denk na over welke oordelen of labels over ADHD en gedragsproblemen je onbewust hebt overgenomen. Zijn ze waar?",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Veel vaders zijn opgegroeid met ideeën als 'ADHD bestaat niet, het is slechte opvoeding' of 'hij moet gewoon luisteren'. Deze overtuigingen — vaak onbewust — kleuren hoe je naar je kind kijkt en kunnen empathie blokkeren.",
    skillTip: "Schrijf drie dingen op die je als kind hoorde over druk of 'moeilijk' gedrag. Klopt dat met wat je nu weet? Welke overtuigingen wil je bewust loslaten?",
    vermijd: "Jezelf of je ouders veroordelen voor die overtuigingen. Ze kwamen voort uit de kennis van die tijd. Het gaat erom wat je nu kiest te geloven.",
    leerdoel: "Je identificeert en onderzoekt onbewuste overtuigingen die je opvoeding beïnvloeden.",
    bron: "Hinshaw (2005) - The Mark of Shame: Stigma of Mental Illness",
    themes: ["adhd", "gedragsproblemen"],
  },
  {
    id: "gedrag_refl_03",
    title: "De vader die je had vs. de vader die je bent",
    skill: "Reflectie",
    description: "Hoe ging jouw vader om met jouw 'lastige' gedrag als kind? Wat neem je over, en wat doe je bewust anders?",
    duration: "15 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "We opvoeden vaak op de automatische piloot vanuit wat we zelf als kind meemaakten. Door bewust te reflecteren op je eigen opvoeding kun je kiezen welke patronen je wilt behouden en welke je wilt doorbreken.",
    skillTip: "Herinner je een moment waarop je als kind 'lastig' was. Hoe reageerde je vader? Wat had je toen nodig? Hoe reageer jij nu op je eigen kind in vergelijkbare situaties? Wat wil je anders doen?",
    vermijd: "Je vader veroordelen — hij deed wat hij kon met de kennis die hij had. Het gaat om jouw bewuste keuze voor de toekomst.",
    leerdoel: "Je herkent intergenerationele patronen en maakt een bewuste keuze welke vader je wilt zijn.",
    bron: "Fraiberg (1975) - Ghosts in the Nursery",
    themes: ["gedragsproblemen"],
  },
  {
    id: "gedrag_refl_04",
    title: "Het ideaalbeeld loslaten",
    skill: "Reflectie",
    description: "Onderzoek eerlijk: welk beeld had je van je kind voordat de diagnose of het gedrag begon? Wat rouw je?",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Veel vaders rouwen onbewust om het 'ideale kind' dat ze hadden verwacht. Dit is een normaal en menselijk proces. Pas als je deze rouw erkent, kun je volledig aanwezig zijn voor het kind dat je hebt — met al zijn unieke kwaliteiten.",
    skillTip: "Stel jezelf deze eerlijke vragen: Hoe had ik me mijn kind voorgesteld? Wat voelde ik bij de eerste signalen of diagnose? Wat mis ik, en wat heb ik erbij gekregen dat ik niet had verwacht?",
    vermijd: "Schuldgevoel over deze gevoelens. Rouwen om verwachtingen is normaal en maakt je niet tot een slechte vader. Het maakt je menselijk.",
    leerdoel: "Je erkent en verwerkt onuitgesproken rouw zodat je met een open hart aanwezig kunt zijn voor je kind.",
    bron: "Huber et al. (2018) - Parental Adjustment to a Child's ADHD Diagnosis",
    themes: ["adhd", "gedragsproblemen", "hooggevoelig"],
  },
  {
    id: "gedrag_refl_05",
    title: "Kracht in de uitdaging",
    skill: "Reflectie",
    description: "Bedenk drie manieren waarop het opvoeden van je kind je tot een betere vader (en mens) heeft gemaakt.",
    duration: "10 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Post-traumatische groei — groei door moeilijkheden — is een goed gedocumenteerd fenomeen. Vaders van kinderen met uitdagingen ontwikkelen vaak meer empathie, geduld en veerkracht dan ze ooit hadden verwacht.",
    skillTip: "Denk aan specifieke situaties. Misschien ben je geduldiger geworden, beter in luisteren, of heb je vooroordelen losgelaten. Schrijf het op en lees het als het zwaar wordt.",
    vermijd: "Dit als toxic positivity gebruiken ('het is allemaal een zegen'). Het is oké om het moeilijk te vinden én tegelijk te groeien.",
    leerdoel: "Je herkent je eigen groei als vader en put hier kracht uit in moeilijke momenten.",
    bron: "Tedeschi & Calhoun (2004) - Posttraumatic Growth",
    themes: ["gedragsproblemen", "adhd"],
  },
  {
    id: "gedrag_refl_06",
    title: "De gevoeligheidsdialoog",
    skill: "Reflectie",
    description: "Sta stil bij hoe jij als man hebt geleerd om te gaan met gevoeligheid. Hoe beïnvloedt dat hoe je naar je hooggevoelige kind kijkt?",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Veel mannen zijn opgegroeid met de boodschap dat gevoeligheid zwakte is. Als je dan een hooggevoelig kind hebt, kan dit innerlijk conflict opleveren. Door je eigen verhouding met gevoeligheid te onderzoeken, kun je je kind beter begeleiden.",
    skillTip: "Vraag jezelf: Mocht ik gevoelig zijn als jongen? Wat gebeurde er als ik kwetsbaar was? Zie ik de gevoeligheid van mijn kind soms als een probleem in plaats van een kracht?",
    vermijd: "Schaamte over je eigen gevoeligheid of het ontkennen ervan. Gevoeligheid is een kracht — ook bij mannen.",
    leerdoel: "Je onderzoekt je eigen relatie met gevoeligheid zodat je dit niet onbewust projecteert op je kind.",
    bron: "Aron (2002) - The Highly Sensitive Child; Levant (1995) - Masculinity Reconstructed",
    themes: ["hooggevoelig"],
  },
  {
    id: "gedrag_refl_07",
    title: "De diagnose-reflectie",
    skill: "Reflectie",
    description: "Als je kind een diagnose heeft (ADHD, HSP): wat betekent die diagnose voor jou? Wat veranderde er nadat je het wist?",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Een diagnose kan opluchting brengen ('er is een verklaring') maar ook angst ('wat betekent dit voor zijn toekomst?'). Door je gevoelens rond de diagnose te verkennen, kun je bewuster omgaan met hoe je het bespreekt met je kind en met anderen.",
    skillTip: "Schrijf op: Wat voelde ik toen ik het hoorde? Wat was mijn eerste gedachte? Hoe kijk ik er nu naar? Is er iets veranderd in hoe ik naar mijn kind kijk?",
    vermijd: "De diagnose als de volledige identiteit van je kind zien. Je kind IS niet ADHD — je kind HEEFT ADHD. Het is één aspect, niet het hele verhaal.",
    leerdoel: "Je verwerkt je eigen gevoelens rond de diagnose zodat je vrij bent om je kind onbelast te begeleiden.",
    bron: "Barkley (2015) - Attention-Deficit Hyperactivity Disorder: A Handbook",
    themes: ["adhd"],
  },
  {
    id: "gedrag_refl_08",
    title: "Wat het je kind kost",
    skill: "Reflectie",
    description: "Stel je voor hoe het is om je kind te zijn. Elke dag de moeite, de correcties, het gevoel 'anders' te zijn. Wat heeft je kind nodig?",
    duration: "10 min",
    ageGroups: ["6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Perspectief nemen — echt proberen te voelen wat je kind voelt — is een van de krachtigste vormen van empathie. Kinderen met ADHD, hooggevoeligheid of gedragsproblemen strijden elke dag met een wereld die niet voor hen is ingericht.",
    skillTip: "Sluit je ogen en stel je een dag voor als je kind: de drukte van school, de constante prikkels, de correcties van volwassenen, het gevoel dat je je best doet maar het nooit genoeg is. Wat heb je nodig aan het einde van die dag?",
    vermijd: "Dit gebruiken om medelijden te voelen (dat is passief). Gebruik het om empathisch handelen te voeden (dat is actief).",
    leerdoel: "Je verdiept je empathie door de wereld echt door de ogen van je kind te zien.",
    bron: "Siegel & Bryson (2011) - The Whole-Brain Child",
    themes: ["adhd", "hooggevoelig", "gedragsproblemen"],
  },
  {
    id: "gedrag_refl_09",
    title: "Het energielek",
    skill: "Reflectie",
    description: "Waar lekt jouw energie als vader van een kind met uitdagend gedrag? En waar vul je weer bij? Breng het in kaart.",
    duration: "10 min",
    ageGroups: ["0-2", "3-5", "6-9", "10-12", "13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Ouders van kinderen met ADHD of gedragsproblemen lopen een verhoogd risico op burn-out. Door bewust in kaart te brengen wat je energie kost en wat het oplevert, kun je beter voor jezelf zorgen — en dus beter voor je kind.",
    skillTip: "Maak twee kolommen: 'Kost energie' en 'Geeft energie'. Wees eerlijk. Wat kun je minimaliseren in de eerste kolom? Wat kun je vaker doen uit de tweede?",
    vermijd: "Schuldgevoel over het feit dat je kind in de kolom 'kost energie' staat. Dat is normaal en eerlijk. Erkenning is de eerste stap naar oplossingen.",
    leerdoel: "Je krijgt inzicht in je eigen energiehuishouding en leert beter voor jezelf te zorgen.",
    bron: "Bögels et al. (2010) - Mindful Parenting in Mental Health Care",
    themes: ["gedragsproblemen", "adhd"],
  },
  {
    id: "gedrag_refl_10",
    title: "Brief aan je kind",
    skill: "Reflectie",
    description: "Schrijf een korte brief aan je kind (die je niet hoeft te geven) over wat je bewondert, wat je moeilijk vindt, en wat je belooft.",
    duration: "15 min",
    ageGroups: ["3-5", "6-9", "10-12", "13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Schrijven activeert andere hersengebieden dan praten of denken. Een brief aan je kind dwingt je om je gevoelens te ordenen en te verwoorden. Het resultaat is vaak verrassend eerlijk en helend — voor jou als vader.",
    skillTip: "Begin met: 'Lieve [naam], wat ik het meest bewonder aan jou is...' Schrijf dan: 'Wat ik soms moeilijk vind is...' En eindig met: 'Wat ik je beloof is...' Er zijn geen regels — schrijf vanuit je hart.",
    vermijd: "De brief per se geven aan je kind. Dit is voor jou. Als je het wilt delen, mooi. Maar het is geen opdracht aan je kind, het is een reflectie-oefening voor jou.",
    leerdoel: "Je ordent je gevoelens als vader en maakt een bewuste belofte aan het kind dat jij het allerbeste gunt.",
    bron: "Pennebaker (1997) - Opening Up: The Healing Power of Expressing Emotions",
    themes: ["gedragsproblemen", "hooggevoelig", "adhd"],
  },
];
