import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_25: InteractiveTask[] = [
  // =====================================================================
  // AGE GROUP 0-2 (10 tasks)
  // =====================================================================
  {
    id: 'aanw_0-2_300',
    skill: 'Aanwezigheid',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Spiegelen van emoties',
    description: 'Spiegel de gezichtsuitdrukkingen van je baby om emotionele afstemming te oefenen.',
    instructions: [
      'Ga op ooghoogte zitten zodat je baby je gezicht goed kan zien.',
      'Wacht tot je baby een emotie toont — een glimlach, fronsen of verbazing.',
      'Spiegel diezelfde uitdrukking terug met een warme stem: "Oh, jij bent blij!"',
      'Houd het contact minstens 30 seconden vast en volg het ritme van je baby.',
    ],
    reflection: 'Merkte je hoe je baby reageerde toen je zijn of haar emotie spiegelde? Wat deed dat met jullie verbinding?',
    scienceNote: 'Spiegeling activeert het spiegelneuronensysteem en bevordert emotionele afstemming — een kerncomponent van veilige hechting (Winnicott, 1971; Meltzoff & Moore, 1977).',
    durationMin: 5,
  },
  {
    id: 'emco_0-2_301',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Emoties benoemen bij huilen',
    description: 'Geef woorden aan het huilen van je baby om emotioneel vocabulaire op te bouwen.',
    instructions: [
      'Als je baby huilt, neem hem of haar op en maak oogcontact.',
      'Benoem de mogelijke emotie: "Je bent verdrietig" of "Je schrikt ervan, hè?"',
      'Gebruik een rustige, warme stemtoon die de emotie erkent zonder te bagatelliseren.',
      'Combineer de woorden met troostend lichamelijk contact zoals wiegen of aaien.',
    ],
    reflection: 'Viel het je op dat je baby rustiger werd toen je de emotie benoemde? Hoe voelde het om woorden te geven aan het gevoel?',
    scienceNote: 'Het benoemen van emoties bij preverbare kinderen legt de basis voor emotieregulatie en affectlabeling (Gottman, Katz & Hooven, 1997).',
    durationMin: 5,
  },
  {
    id: 'zelr_0-2_302',
    skill: 'Zelfregulatie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Co-regulatie bij frustratie',
    description: 'Help je peuter met frustratie door samen rustig te worden.',
    instructions: [
      'Wanneer je peuter gefrustreerd raakt (bijv. een toren valt om), ga op zijn of haar niveau zitten.',
      'Haal zelf hoorbaar langzaam adem en zeg: "Oef, dat is balen."',
      'Leg een hand op de rug van je kind en wacht even — geef ruimte voor de emotie.',
      'Bied pas een oplossing aan als je kind weer rustiger is: "Zullen we het opnieuw proberen?"',
    ],
    reflection: 'Lukte het je om eerst te wachten en de frustratie te erkennen voordat je ging helpen? Wat was het effect?',
    scienceNote: 'Co-regulatie is de voorloper van zelfregulatie; de prefrontale cortex van een peuter is nog onvoldoende ontwikkeld voor zelfstandige emotieregulatie (Schore, 2001; Tronick, 1989).',
    durationMin: 10,
  },
  {
    id: 'verb_0-2_303',
    skill: 'Verbinding',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Emotioneel verstoppertje',
    description: 'Speel kiekeboe met emotionele variaties om sociale wederkerigheid te oefenen.',
    instructions: [
      'Begin een spelletje kiekeboe met je baby of peuter.',
      'Varieer je gezichtsuitdrukking bij elk "kiekeboe" — blij, verbaasd, een beetje gek.',
      'Pauzeer na elke onthulling en laat je kind reageren; wacht op een lach of geluidje.',
      'Speel minstens 5 rondjes en let op welke uitdrukking de meeste reactie oproept.',
    ],
    reflection: 'Welke emotie-uitdrukking vond je kind het leukst? Wat vertelt dat je over zijn of haar sociale ontwikkeling?',
    scienceNote: 'Kiekeboespellen bevorderen objectpermanentie en sociale reciprociteit, kernelementen in de sensomotorische fase (Piaget, 1954; Bruner & Sherwood, 1976).',
    durationMin: 5,
  },
  {
    id: 'gren_0-2_304',
    skill: 'Grenzen',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Zacht "nee" met alternatief',
    description: 'Oefen grenzen stellen met empathie door altijd een alternatief te bieden.',
    instructions: [
      'Wanneer je peuter iets onveiligs doet, ga naar hem of haar toe in plaats van op afstand "nee" te roepen.',
      'Zeg op warme toon: "Dat mag niet, want het is gevaarlijk" — benoem kort de reden.',
      'Bied meteen een alternatief: "Je mag hier wél mee spelen" en geef het vervangende voorwerp.',
      'Bevestig het gewenste gedrag: "Goed zo, dat is veilig spelen!"',
    ],
    reflection: 'Hoe reageerde je peuter op het krijgen van een alternatief? Was het makkelijker dan alleen "nee" zeggen?',
    scienceNote: 'Grenzen stellen met warmte en alternatieven bevordert gehoorzaamheid zonder de hechtingsrelatie te schaden (Kochanska, 2002; Hoffman, 2000).',
    durationMin: 5,
  },
  {
    id: 'hers_0-2_305',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Herstel na een boze reactie',
    description: 'Herstel de verbinding met je baby of peuter nadat je te snel of te hard reageerde.',
    instructions: [
      'Herken het moment dat je te scherp reageerde — misschien door vermoeidheid of stress.',
      'Ga naar je kind toe, maak oogcontact en zeg op zachte toon: "Sorry, papa was even boos. Dat was niet fijn."',
      'Bied fysiek troost aan: een knuffel, wiegen, of streeltjes over het hoofd.',
      'Observeer of je kind weer ontspant en zoek samen een rustig moment.',
    ],
    reflection: 'Hoe voelde het om sorry te zeggen tegen je kleine kind? Merkte je dat de verbinding herstelde?',
    scienceNote: 'Herstel na interactiebreuken ("rupture and repair") is cruciaal voor veilige hechting en leert kinderen dat relaties hersteld kunnen worden (Tronick, 2007; Bowlby, 1969).',
    durationMin: 5,
  },
  {
    id: 'auto_0-2_306',
    skill: 'Autonomie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Zelf kiezen bij het eten',
    description: 'Geef je peuter twee opties om keuzevrijheid en zelfvertrouwen te stimuleren.',
    instructions: [
      'Bereid twee gezonde snacks voor en zet ze allebei voor je peuter neer.',
      'Vraag: "Wil je de banaan of de cracker?" en wacht geduldig op een keuze.',
      'Respecteer de keuze, ook als die je verrast — zeg: "Goed gekozen!"',
      'Herhaal bij de volgende maaltijd en observeer of je peuter sneller kiest.',
    ],
    reflection: 'Hoe reageerde je peuter op het zelf mogen kiezen? Merkte je trots of plezier?',
    scienceNote: 'Keuzemogelijkheden bieden binnen veilige grenzen ondersteunt de autonomieontwikkeling in Eriksons fase "autonomie vs. schaamte en twijfel" (Erikson, 1950).',
    durationMin: 10,
  },
  {
    id: 'refl_0-2_307',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Dagboek van verbinding',
    description: 'Schrijf elke avond drie momenten op waarop je je emotioneel verbonden voelde met je baby.',
    instructions: [
      'Pak een notitieboekje of je telefoon vlak voor het slapengaan.',
      'Schrijf drie specifieke momenten op van vandaag waarop je een verbinding voelde met je kind.',
      'Beschrijf bij elk moment: wat deed je kind, wat deed jij, en wat voelde je daarbij?',
      'Lees na een week je notities terug en zoek patronen in jullie beste momenten.',
    ],
    reflection: 'Welke patronen zie je in de momenten van verbinding? Wat zegt dat over wat jij en je kind nodig hebben?',
    scienceNote: 'Reflectief ouderschap vergroot de mentalisatiecapaciteit, wat direct bijdraagt aan de hechtingskwaliteit (Fonagy et al., 2002; Slade, 2005).',
    durationMin: 10,
  },
  {
    id: 'emco_0-2_308',
    skill: 'Emotiecoaching',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Emotiegezichten lezen',
    description: 'Gebruik een prentenboek om samen emoties te herkennen en benoemen.',
    instructions: [
      'Kies een prentenboek met duidelijke gezichtsuitdrukkingen (bijv. Nijntje of Dikkie Dik).',
      'Wijs bij elke pagina naar het gezicht van het personage en benoem de emotie: "Kijk, hij is verdrietig."',
      'Vraag aan je peuter (ook als die nog niet praat): "Hoe voelt hij zich?" en wacht even.',
      'Koppel de emotie aan het leven van je kind: "Jij was ook verdrietig toen je beer kwijt was."',
    ],
    reflection: 'Reageerde je kind op de emotiewoorden? Wees je ervan verrast hoe veel je peuter al begrijpt?',
    scienceNote: 'Prentenboeken lezen met emotielabels vergroot het emotioneel vocabulaire al vanaf 18 maanden (Ruffman et al., 2006; Drummond et al., 2014).',
    durationMin: 10,
  },
  {
    id: 'aanw_0-2_309',
    skill: 'Aanwezigheid',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Vijf minuten vloertijd',
    description: 'Ga vijf minuten volledig aanwezig op de grond zitten en volg het spel van je kind.',
    instructions: [
      'Leg je telefoon weg, zet de tv uit en ga op de grond bij je kind zitten.',
      'Volg het initiatief van je kind — pak op wat hij of zij oppakt, kijk waar hij of zij kijkt.',
      'Geef sportverslagcommentaar: "Je pakt de rode blokken... je stapelt ze op!"',
      'Vermijd sturen of corrigeren; jouw enige taak is aanwezig zijn en volgen.',
    ],
    reflection: 'Hoe voelde het om vijf minuten alleen maar te volgen? Was het moeilijk om niet te sturen?',
    scienceNote: 'Kindgeleid spel versterkt de veilige hechting en het gevoel van competentie bij het kind (Landreth, 2012; Axline, 1947).',
    durationMin: 5,
  },

  // =====================================================================
  // AGE GROUP 3-5 (10 tasks)
  // =====================================================================
  {
    id: 'emco_3-5_310',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Emotie-thermometer',
    description: 'Maak samen een emotie-thermometer om de intensiteit van gevoelens te leren herkennen.',
    instructions: [
      'Teken samen een grote thermometer op papier met onderin "een beetje" en bovenin "heel veel".',
      'Kies een emotie, bijvoorbeeld boos, en vraag: "Hoe boos was je toen je zus je blokken afpakte?"',
      'Laat je kind aanwijzen op de thermometer hoe intens het gevoel was.',
      'Bespreek samen: "Bij een beetje boos kun je diep ademhalen. Bij heel veel boos mag je even stampen."',
    ],
    reflection: 'Kon je kind onderscheid maken tussen een beetje en heel veel van een emotie? Hoe hielp de thermometer daarbij?',
    scienceNote: 'Het differentiëren van emotie-intensiteit is een kernaspect van emotionele granulariteit, wat betere regulatie voorspelt (Barrett, 2017; Gottman et al., 1997).',
    durationMin: 15,
  },
  {
    id: 'verb_3-5_311',
    skill: 'Verbinding',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Dankbaarheidscirkel',
    description: 'Deel samen drie dingen waar jullie dankbaar voor zijn om prosociaal denken te stimuleren.',
    instructions: [
      'Ga samen aan tafel zitten, bijvoorbeeld bij het avondeten.',
      'Begin zelf: "Ik ben vandaag dankbaar voor... jouw knuffel vanochtend."',
      'Vraag je kind: "Waar ben jij blij mee vandaag?" en geef alle tijd om na te denken.',
      'Maak het een ritueel door het elke dag op hetzelfde moment te doen.',
    ],
    reflection: 'Wat noemde je kind? Viel je iets op aan de dingen waarvoor hij of zij dankbaar is?',
    scienceNote: 'Dagelijkse dankbaarheidspraktijken verhogen het welzijn en prosociaal gedrag bij kinderen (Froh et al., 2008; Seligman, 2011 — PERMA-model).',
    durationMin: 5,
  },
  {
    id: 'zelr_3-5_312',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'De schildpadtechniek',
    description: 'Leer je kind de schildpadtechniek om bij boosheid eerst te stoppen en na te denken.',
    instructions: [
      'Vertel het verhaal van de kleine schildpad die leerde om in zijn schild te kruipen als hij boos was.',
      'Oefen samen: armen om je lijf, hoofd naar beneden, drie keer diep ademhalen.',
      'Speel een rollenspel: "Je vriendje pakt je schep af in de zandbak — wat doe je?"',
      'Oefen de schildpadtechniek minstens drie keer in een rustig moment, zodat het beschikbaar is bij echte boosheid.',
    ],
    reflection: 'Kon je kind de stappen onthouden? Wat hielp het meest: het verhaal, het oefenen, of het rollenspel?',
    scienceNote: 'De schildpadtechniek is een evidence-based methode uit het PATHS-curriculum die impulscontrole bevordert bij kleuters (Greenberg & Kusché, 1993).',
    durationMin: 15,
  },
  {
    id: 'gren_3-5_313',
    skill: 'Grenzen',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Grenzen bij speelafspraken',
    description: 'Bereid je kind voor op een speelafspraak door grenzen en verwachtingen te bespreken.',
    instructions: [
      'Bespreek vóór de speelafspraak: "Welke speeltjes wil je delen en welke niet?"',
      'Help je kind een grens te oefenen: "Je mag zeggen: ik wil dit speelgoed nu zelf houden."',
      'Bespreek ook de grens van de ander: "Als je vriendje nee zegt, respecteer je dat."',
      'Evalueer na de speelafspraak: "Hoe ging het met delen? Was er een moment dat je je grens aangaf?"',
    ],
    reflection: 'Lukte het je kind om grenzen aan te geven én die van een ander te respecteren? Wat was lastig?',
    scienceNote: 'Het oefenen van grenzen in sociale contexten bevordert sociale competentie en vermindert agressief gedrag (Ladd, 2005; Denham et al., 2003).',
    durationMin: 10,
  },
  {
    id: 'aanw_3-5_314',
    skill: 'Aanwezigheid',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Emotie-detectivespel',
    description: 'Ga samen op pad en zoek emoties bij anderen om empathie te oefenen.',
    instructions: [
      'Ga samen wandelen of naar een speeltuin en zeg: "We gaan emoties zoeken bij andere mensen."',
      'Wijs subtiel naar iemand en vraag: "Hoe zou die mevrouw zich voelen? Waarom denk je dat?"',
      'Help je kind verder: "Kijk naar haar mond, haar ogen — wat vertellen die?"',
      'Bespreek samen dat je niet altijd kunt weten hoe iemand zich voelt, maar dat kijken en nadenken een goede start is.',
    ],
    reflection: 'Welke emotie herkende je kind het beste? Was er een emotie die moeilijk te raden was?',
    scienceNote: 'Perspectiefneming begint zich te ontwikkelen rond het vierde levensjaar met de theory of mind (Wellman, 2014; Baron-Cohen, 1995).',
    durationMin: 15,
  },
  {
    id: 'hers_3-5_315',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Sorry zeggen met betekenis',
    description: 'Leer je kind een oprecht excuus te maken na een conflict met een broertje, zusje of vriendje.',
    instructions: [
      'Wacht tot het conflict is afgekoeld en je kind weer rustig is.',
      'Bespreek samen wat er gebeurde: "Wat deed jij? Hoe denk je dat je zusje zich daardoor voelde?"',
      'Help een oprecht excuus te formuleren: "Het spijt me dat ik je duwde. Dat deed vast pijn."',
      'Bespreek hoe het de volgende keer anders kan: "Wat kun je doen als je boos bent in plaats van duwen?"',
    ],
    reflection: 'Begreep je kind waarom het excuus belangrijk was? Kon hij of zij zich inleven in de ander?',
    scienceNote: 'Oprechte excuses met perspectiefneming bevorderen empathische ontwikkeling en herstelgedrag bij jonge kinderen (Eisenberg, 2000; Thompson, 2006).',
    durationMin: 10,
  },
  {
    id: 'auto_3-5_316',
    skill: 'Autonomie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Conflictoplossing zelf bedenken',
    description: 'Laat je kind zelf een oplossing bedenken voor een ruzie in plaats van het voor te kauwen.',
    instructions: [
      'Wanneer je kind klaagt over een conflict ("Hij pakte mijn auto!"), luister eerst zonder oordeel.',
      'Vraag: "Dat klinkt vervelend. Wat zou jij kunnen doen om het op te lossen?"',
      'Als je kind vastloopt, bied opties: "Je kunt vragen of je hem terug mag, of om de beurt spelen."',
      'Laat je kind kiezen en uitvoeren — stap pas in als het escaleert.',
    ],
    reflection: 'Welke oplossing bedacht je kind zelf? Was je verrast door het probleemoplossend vermogen?',
    scienceNote: 'Kinderen die geoefend worden in zelfstandig conflicten oplossen ontwikkelen sterkere executieve functies en sociale vaardigheden (Shure & Spivack, 1982).',
    durationMin: 10,
  },
  {
    id: 'refl_3-5_317',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Emotie van de dag tekenen',
    description: 'Laat je kind elke dag een emotie tekenen om zelfbewustzijn te versterken.',
    instructions: [
      'Geef je kind een vel papier en kleurpotloden.',
      'Vraag: "Welk gevoel had je het meest vandaag? Kun je dat tekenen?"',
      'Stel geen eisen aan de tekening — het gaat om het proces, niet het resultaat.',
      'Bespreek de tekening: "Vertel eens, wat zie ik hier? Wanneer voelde je dit?"',
    ],
    reflection: 'Wat tekende je kind? Verraste het gevoel je, of had je het al opgemerkt vandaag?',
    scienceNote: 'Expressieve kunstactiviteiten helpen jonge kinderen emoties te verwerken en te communiceren (Malchiodi, 2012; Denham, 1998).',
    durationMin: 10,
  },
  {
    id: 'emco_3-5_318',
    skill: 'Emotiecoaching',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Twee gevoelens tegelijk',
    description: 'Help je kind begrijpen dat je twee gevoelens tegelijk kunt hebben.',
    instructions: [
      'Wacht op een moment waarop je kind gemengde gevoelens heeft, bijv. blij om naar opa te gaan maar verdrietig om jou te missen.',
      'Benoem beide gevoelens: "Je bent blij dat je naar opa gaat, EN je vindt het jammer dat papa niet meegaat."',
      'Leg uit: "Je mag twee gevoelens tegelijk hebben. Dat is normaal en heel knap dat je dat voelt."',
      'Vraag: "Welk gevoel is het grootst? En welk gevoel is er ook nog?"',
    ],
    reflection: 'Kon je kind de twee gevoelens herkennen? Hoe reageerde hij of zij op de validatie?',
    scienceNote: 'Het begrijpen van ambivalente emoties is een mijlpaal in de emotionele ontwikkeling die rond het vijfde jaar begint (Harris, 1989; Harter & Buddin, 1987).',
    durationMin: 5,
  },
  {
    id: 'zelr_3-5_319',
    skill: 'Zelfregulatie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Rustig worden met ademmaatjes',
    description: 'Oefen ademhalingsoefeningen met een knuffel op de buik om zelfregulatie aan te leren.',
    instructions: [
      'Laat je kind op de rug liggen en leg een knuffeldier op zijn of haar buik.',
      'Zeg: "We gaan je knuffel een ritje geven. Adem in door je neus — je knuffel gaat omhoog!"',
      'Adem uit door de mond: "Je knuffel gaat weer omlaag. Langzaam, zodat hij niet valt."',
      'Herhaal vijf keer en bespreek: "Hoe voel je je nu? Rustiger dan daarvoor?"',
    ],
    reflection: 'Lukte het je kind om de ademhaling te vertragen? Merkte je verschil in het energieniveau?',
    scienceNote: 'Diepe buikademhaling activeert het parasympathische zenuwstelsel en vermindert cortisolniveaus, ook bij jonge kinderen (Porges, 2011; Kabat-Zinn, 2003).',
    durationMin: 5,
  },

  // =====================================================================
  // AGE GROUP 6-9 (10 tasks)
  // =====================================================================
  {
    id: 'verb_6-9_320',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Complimentenronde',
    description: 'Geef elkaar om de beurt een specifiek compliment om waardering te oefenen.',
    instructions: [
      'Ga samen zitten en leg uit: "We gaan complimenten geven die echt specifiek zijn."',
      'Geef het voorbeeld: "Ik vond het lief dat je je zusje hielp met haar jas aantrekken."',
      'Vraag je kind: "Kun jij iemand in ons gezin een compliment geven over iets specifieks?"',
      'Doe minstens twee rondes zodat iedereen aan bod komt en bespreek hoe het voelde.',
    ],
    reflection: 'Vond je kind het makkelijker om een compliment te geven of te ontvangen? Wat zegt dat?',
    scienceNote: 'Specifieke complimenten versterken prosociaal gedrag effectiever dan algemene lof en bouwen een positief zelfbeeld op (Henderlong & Lepper, 2002; Dweck, 2006).',
    durationMin: 10,
  },
  {
    id: 'emco_6-9_321',
    skill: 'Emotiecoaching',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Emotiewoordenboek maken',
    description: 'Maak samen een persoonlijk emotiewoordenboek met woorden voorbij "blij, boos, verdrietig".',
    instructions: [
      'Pak een schriftje en schrijf bovenaan: "Mijn Emotiewoordenboek".',
      'Brainstorm samen emotiewoorden voorbij de basis: teleurgesteld, trots, jaloers, opgelucht, gespannen.',
      'Schrijf bij elk woord een situatie: "Teleurgesteld = toen mijn vriendje niet kon spelen."',
      'Voeg elke week een nieuw woord toe wanneer je kind een onbekend gevoel ervaart.',
    ],
    reflection: 'Welke emotiewoorden waren nieuw voor je kind? Merkte je dat hij of zij ze daarna ook gebruikte?',
    scienceNote: 'Een groter emotioneel vocabulaire correleert met betere emotieregulatie en minder externaliserende gedragsproblemen (Lindquist & Barrett, 2008; Izard et al., 2001).',
    durationMin: 15,
  },
  {
    id: 'aanw_6-9_322',
    skill: 'Aanwezigheid',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Luisteren zonder oplossing',
    description: 'Oefen vijf minuten aandachtig luisteren naar je kind zonder advies te geven.',
    instructions: [
      'Vraag je kind: "Vertel eens over je dag — ik ga alleen maar luisteren."',
      'Luister actief: knik, zeg "hmm" en "oh ja?", maar geef geen advies of oordeel.',
      'Als je de neiging voelt om iets op te lossen, haal adem en stel in plaats daarvan een vraag: "Hoe was dat voor je?"',
      'Sluit af met: "Dankjewel dat je dit met me deelde. Dat vind ik fijn."',
    ],
    reflection: 'Hoe moeilijk was het om niet meteen een oplossing te geven? Merkte je dat je kind meer vertelde?',
    scienceNote: 'Actief luisteren zonder onmiddellijke probleemoplossing versterkt het gevoel gehoord te worden en bevordert emotionele openheid (Rogers, 1951; Gottman, 1997).',
    durationMin: 5,
  },
  {
    id: 'hers_6-9_323',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Herstelgesprek na een ruzie',
    description: 'Voer een gestructureerd herstelgesprek na een conflict tussen broers of zussen.',
    instructions: [
      'Wacht tot beide kinderen rustig zijn. Ga met hen aan tafel zitten.',
      'Laat elk kind vertellen wat er gebeurde vanuit zijn of haar perspectief — de ander luistert zonder onderbreken.',
      'Vraag aan elk kind: "Hoe voelde jij je? En hoe denk je dat je broer/zus zich voelde?"',
      'Zoek samen een oplossing: "Wat kunnen we afspreken zodat dit de volgende keer anders gaat?"',
    ],
    reflection: 'Konden de kinderen elkaars perspectief zien? Wat was het moeilijkste onderdeel van het gesprek?',
    scienceNote: 'Gestructureerde conflictresolutiemethoden verbeteren de sibling-relatie en bevorderen perspectiefneming (Kennedy & Kramer, 2008; Selman, 1980).',
    durationMin: 15,
  },
  {
    id: 'zelr_6-9_324',
    skill: 'Zelfregulatie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Boosheidstrappetje',
    description: 'Maak een stappenplan voor als je kind boos wordt, van lichte irritatie tot razernij.',
    instructions: [
      'Teken samen een trap met vijf treden: een beetje geïrriteerd onderaan, razend bovenaan.',
      'Bedenk voor elke trede een strategie: trede 1 = diep ademhalen, trede 3 = even weglopen, trede 5 = papa roepen.',
      'Oefen met een echt voorbeeld: "Gisteren bij het voetballen — op welke trede was je?"',
      'Hang het trappetje op in de kamer van je kind als geheugensteun.',
    ],
    reflection: 'Herkende je kind de verschillende niveaus van boosheid? Welke strategie sprak het meest aan?',
    scienceNote: 'Het herkennen van escalatieniveaus en het koppelen aan specifieke copingstrategieën is een kerncomponent van cognitieve gedragstherapie voor kinderen (Lochman et al., 2008).',
    durationMin: 15,
  },
  {
    id: 'gren_6-9_325',
    skill: 'Grenzen',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Nee zeggen tegen vriendjes',
    description: 'Oefen met je kind om assertief nee te zeggen wanneer een vriendje iets vervelends voorstelt.',
    instructions: [
      'Bespreek: "Soms stellen vrienden iets voor waar je geen zin in hebt. Dan mag je nee zeggen."',
      'Oefen drie scenario\'s in rollenspelvorm: iemand wil snoep stelen, iemand pest een ander kind, iemand wil te lang gamen.',
      'Help met zinnen: "Nee, daar doe ik niet aan mee" of "Ik vind dat niet oké, laten we iets anders doen."',
      'Bespreek: "Wat kan er gebeuren als je nee zegt? En wat als je meedoet terwijl je dat niet wilt?"',
    ],
    reflection: 'Welk scenario vond je kind het moeilijkst? Wat maakt nee zeggen tegen vrienden zo lastig?',
    scienceNote: 'Assertiviteitstraining bij schoolgaande kinderen vermindert meelopergedrag en vergroot de weerstand tegen groepsdruk (Baumrind, 1991; Rubin et al., 2006).',
    durationMin: 15,
  },
  {
    id: 'auto_6-9_326',
    skill: 'Autonomie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Eigen hulpplan bedenken',
    description: 'Laat je kind zelf een plan maken voor een sociaal probleem op school.',
    instructions: [
      'Vraag je kind om een sociaal probleem te noemen waar het mee zit, bijvoorbeeld buitengesloten worden bij een spelletje.',
      'Vraag: "Wat zou je allemaal kunnen doen?" en schrijf alle ideeën op, ook de gekke.',
      'Bespreek elk idee: "Wat zou er gebeuren als je dit doet?" — help voor- en nadelen te zien.',
      'Laat je kind één plan kiezen en spreek af om er morgen op terug te komen.',
    ],
    reflection: 'Welk plan koos je kind? Vertrouw je erop dat het kan werken, of wil je bijsturen?',
    scienceNote: 'Sociale probleemoplossingsvaardigheden zijn een sterke voorspeller van sociale aanpassing bij schoolgaande kinderen (Dodge et al., 1986; Shure, 1992).',
    durationMin: 10,
  },
  {
    id: 'refl_6-9_327',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Vriendschap-mindmap',
    description: 'Maak samen een mindmap over wat een goede vriend zijn betekent.',
    instructions: [
      'Pak een groot vel papier en schrijf in het midden: "Een goede vriend".',
      'Vraag je kind om eigenschappen te noemen en schrijf die in takken eromheen: eerlijk, grappig, helpt je, enz.',
      'Bespreek per eigenschap: "Doe jij dit ook voor je vrienden? Wanneer wel, wanneer niet?"',
      'Voeg een tak toe: "Wat vind je moeilijk in vriendschap?" en bespreek dit eerlijk samen.',
    ],
    reflection: 'Wat ziet je kind als de belangrijkste eigenschap? Hoe verhoudt zich dat tot wat jij belangrijk vindt?',
    scienceNote: 'Reflectie op vriendschapskwaliteiten bevordert sociaal-cognitieve ontwikkeling en wederzijdse relaties (Selman, 1980; Sullivan, 1953).',
    durationMin: 15,
  },
  {
    id: 'verb_6-9_328',
    skill: 'Verbinding',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Gezamenlijk dankbaarheidspotje',
    description: 'Start een dankbaarheidspotje waarin het gezin dagelijks briefjes stopt.',
    instructions: [
      'Pak een lege glazen pot en versier die samen met je kind.',
      'Leg uit: "Elke dag schrijven we iets op waar we dankbaar voor zijn en stoppen het in de pot."',
      'Schrijf vandaag samen de eerste briefjes — lees ze hardop voor als je ze erin doet.',
      'Spreek af om de pot aan het einde van de maand samen te openen en alles voor te lezen.',
    ],
    reflection: 'Waar was je kind dankbaar voor? Verschilt dat van wat jij opschreef?',
    scienceNote: 'Dankbaarheidsintenties vergroten het subjectief welzijn en versterken sociale banden, ook bij kinderen (Emmons & McCullough, 2003; Froh et al., 2008).',
    durationMin: 10,
  },
  {
    id: 'hers_6-9_329',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Brief schrijven na een ruzie',
    description: 'Help je kind een brief te schrijven aan iemand waarmee het een conflict had.',
    instructions: [
      'Bespreek het conflict en vraag: "Hoe denk je dat de ander zich nu voelt?"',
      'Help je kind een korte brief te schrijven met drie delen: wat er gebeurde, hoe je je voelt, wat je wilt.',
      'Lees de brief samen door en vraag: "Zou jij je beter voelen als je deze brief kreeg?"',
      'Beslis samen of de brief verstuurd wordt of dat het schrijven zelf al genoeg was.',
    ],
    reflection: 'Hoe was het schrijfproces voor je kind? Hielp het om de gevoelens te ordenen?',
    scienceNote: 'Expressief schrijven over emotionele ervaringen verbetert de emotionele verwerking en sociale relaties (Pennebaker, 1997; Lepore & Smyth, 2002).',
    durationMin: 15,
  },

  // =====================================================================
  // AGE GROUP 10-12 (10 tasks)
  // =====================================================================
  {
    id: 'emco_10-12_330',
    skill: 'Emotiecoaching',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Lichaamsscan voor emoties',
    description: 'Leer je kind emoties te herkennen via lichamelijke signalen.',
    instructions: [
      'Teken samen een silhouet van een lichaam op een groot vel papier.',
      'Vraag: "Waar voel jij boosheid in je lichaam? En spanning? En verdriet?"',
      'Laat je kind die plekken inkleuren met verschillende kleuren per emotie.',
      'Bespreek: "Als je merkt dat je buik samenknijpt, weet je nu dat dat spanning kan zijn."',
    ],
    reflection: 'Was je kind verbaasd over waar emoties in het lichaam zitten? Herken je de patronen?',
    scienceNote: 'Interoceptief bewustzijn — het waarnemen van lichamelijke signalen — is gekoppeld aan betere emotieregulatie (Nummenmaa et al., 2014; Damasio, 1994).',
    durationMin: 15,
  },
  {
    id: 'zelr_10-12_331',
    skill: 'Zelfregulatie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Gedachtenstop bij piekeren',
    description: 'Leer je kind de gedachtenstop-techniek bij negatief piekeren over sociale situaties.',
    instructions: [
      'Vraag: "Heb je weleens dat je steeds aan iets vervelends blijft denken, zoals een ruzie op school?"',
      'Leg de techniek uit: "Als je merkt dat je piekert, zeg je in je hoofd STOP en stel je je een stoplicht voor."',
      'Vervang de gedachte door iets concreets: "Noem vijf dingen die je ziet in de kamer."',
      'Oefen drie keer samen met een voorbeeld en bespreek wanneer dit in het echt zou helpen.',
    ],
    reflection: 'Herkende je kind het piekeren? Lukte het om de techniek toe te passen bij het oefenen?',
    scienceNote: 'Cognitieve herstructurering en gedachtenstoptechnieken verminderen ruminatie bij kinderen in de pre-adolescentie (Nolen-Hoeksema et al., 2008; Meichenbaum, 1977).',
    durationMin: 10,
  },
  {
    id: 'aanw_10-12_332',
    skill: 'Aanwezigheid',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Aandachtig gesprek zonder telefoon',
    description: 'Voer een gesprek van tien minuten waarbij alle telefoons in een andere kamer liggen.',
    instructions: [
      'Leg samen alle telefoons in een andere kamer — maak er een bewust ritueel van.',
      'Kies een gespreksonderwerp dat je kind bezighoudt: een vriendschap, een droom, een zorg.',
      'Luister actief, stel doorvragen en deel ook iets van jezelf.',
      'Sluit af met: "Dit vond ik fijn. Zullen we dit vaker doen?"',
    ],
    reflection: 'Was het gesprek anders zonder telefoons erbij? Wat deelde je kind dat het normaal misschien niet zou zeggen?',
    scienceNote: 'De aanwezigheid van smartphones vermindert de kwaliteit van face-to-face gesprekken, zelfs als ze niet worden gebruikt (Przybylski & Weinstein, 2013).',
    durationMin: 10,
  },
  {
    id: 'verb_10-12_333',
    skill: 'Verbinding',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Gedeeld positief moment creëren',
    description: 'Plan bewust een activiteit die jullie allebei leuk vinden om de verbinding te versterken.',
    instructions: [
      'Vraag je kind: "Als we samen één ding mochten doen dit weekend, wat zou jij kiezen?"',
      'Kies samen iets dat voor allebei leuk is — een wandeling, samen koken, een bordspel.',
      'Zorg dat je tijdens de activiteit volledig aanwezig bent: geen telefoon, geen multitasking.',
      'Benoem achteraf het positieve: "Ik vond het echt leuk om samen te... Jij ook?"',
    ],
    reflection: 'Wat koos je kind? Was de activiteit anders dan wat jij verwacht had?',
    scienceNote: 'Gedeelde positieve ervaringen versterken de ouder-kindrelatie en bouwen aan het "emotionele bankrekening"-kapitaal (Gottman, 2011; Fredrickson, 2001).',
    durationMin: 15,
  },
  {
    id: 'gren_10-12_334',
    skill: 'Grenzen',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Digitale grenzen bespreken',
    description: 'Bespreek samen eerlijk welke grenzen er gelden voor online gedrag en social media.',
    instructions: [
      'Begin met: "Ik wil samen praten over telefoon en internet — niet om te verbieden, maar om samen regels te maken."',
      'Vraag: "Wat vind jij zelf slimme regels? En waar maak jij je soms zorgen over online?"',
      'Deel je eigen zorgen eerlijk en luister naar de reactie zonder te oordelen.',
      'Maak samen drie tot vijf afspraken die jullie allebei eerlijk vinden en schrijf ze op.',
    ],
    reflection: 'Voelde het gesprek als samenwerken of als opleggen? Hoe kun je dat de volgende keer verbeteren?',
    scienceNote: 'Gezamenlijke besluitvorming over mediagebruik vergroot naleving en bevordert digitale geletterdheid (Valkenburg & Piotrowski, 2017; Livingstone & Helsper, 2008).',
    durationMin: 15,
  },
  {
    id: 'auto_10-12_335',
    skill: 'Autonomie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Eigen waarden ontdekken',
    description: 'Help je kind zijn of haar kernwaarden te ontdekken via een keuze-oefening.',
    instructions: [
      'Schrijf twintig waarden op kaartjes: eerlijkheid, vriendschap, humor, rechtvaardigheid, avontuur, enz.',
      'Vraag je kind om de kaartjes te sorteren in drie stapels: heel belangrijk, een beetje, niet zo.',
      'Bespreek de top vijf: "Waarom is eerlijkheid belangrijk voor jou? Kun je een voorbeeld noemen?"',
      'Vraag: "Leef je deze waarde al? Of zou je er meer aan willen doen?"',
    ],
    reflection: 'Welke waarden koos je kind? Overlappen ze met jouw waarden, of zijn ze verrassend anders?',
    scienceNote: 'Het ontdekken van persoonlijke waarden in de pre-adolescentie ondersteunt identiteitsvorming in Eriksons fase "vlijt vs. minderwaardigheid" (Erikson, 1968; Damon, 2008).',
    durationMin: 15,
  },
  {
    id: 'hers_10-12_336',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Foutenverhalen delen',
    description: 'Deel een eigen fout uit je jeugd om te normaliseren dat iedereen fouten maakt.',
    instructions: [
      'Vertel je kind over een fout die je maakte toen je zelf jong was — iets dat je beschaamd over was.',
      'Beschrijf wat je voelde, wat je deed, en wat je ervan leerde.',
      'Vraag: "Heb jij weleens zoiets meegemaakt? Hoe voelde dat?"',
      'Sluit af: "Fouten horen bij groeien. Het gaat erom wat je daarna doet."',
    ],
    reflection: 'Deelde je kind ook iets terug? Hoe veranderde jouw kwetsbaarheid het gesprek?',
    scienceNote: 'Zelfopenbaring door ouders normaliseert falen en bevordert een groeimindset bij kinderen (Dweck, 2006; Brown, 2012).',
    durationMin: 10,
  },
  {
    id: 'refl_10-12_337',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Empathie-interview',
    description: 'Interview je kind over een keer dat het zich in iemand anders verplaatste.',
    instructions: [
      'Vraag: "Kun je me vertellen over een keer dat je begreep hoe iemand anders zich voelde?"',
      'Stel doorvragen: "Wat dacht je toen? Wat deed je? Hoe reageerde de ander?"',
      'Vraag: "Was er ook een keer dat iemand jou begreep? Hoe voelde dat?"',
      'Reflecteer samen: "Wat maakt het moeilijk om je in iemand te verplaatsen? En wat maakt het makkelijker?"',
    ],
    reflection: 'Hoe diep kon je kind reflecteren? Welke empathievaardigheden zijn al sterk ontwikkeld?',
    scienceNote: 'Geleide reflectie op empathische ervaringen versterkt de empathische nauwkeurigheid en het prosociale gedrag (Decety & Jackson, 2004; Hoffman, 2000).',
    durationMin: 15,
  },
  {
    id: 'zelr_10-12_338',
    skill: 'Zelfregulatie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Emotielogboek bijhouden',
    description: 'Laat je kind een week lang dagelijks emoties bijhouden in een simpel logboek.',
    instructions: [
      'Maak samen een simpel schema: datum, situatie, emotie, intensiteit (1-10), wat ik deed.',
      'Laat je kind elke avond invullen — help de eerste twee dagen mee.',
      'Bespreek na een week samen de patronen: "Wanneer scoor je hoog? Wat helpt om lager te scoren?"',
      'Zoek samen naar triggers en strategieën die al werken.',
    ],
    reflection: 'Welke patronen ontdekte je kind? Was er een verrassende trigger of een onverwachte copingstrategie?',
    scienceNote: 'Zelfmonitoring van emoties verhoogt het metacognitief bewustzijn en is een effectieve regulatiestrategie (Gross, 2015; Southam-Gerow & Kendall, 2002).',
    durationMin: 10,
  },
  {
    id: 'emco_10-12_339',
    skill: 'Emotiecoaching',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Perspectief wisselen bij een conflict',
    description: 'Oefen perspectiefneming door je kind de situatie vanuit de ander te laten vertellen.',
    instructions: [
      'Als je kind vertelt over een conflict, luister eerst volledig zonder onderbreken.',
      'Vraag: "Kun je het verhaal nu opnieuw vertellen, maar dan vanuit het perspectief van de ander?"',
      'Help waar nodig: "Wat zou die persoon gedacht hebben? Wat voelde hij of zij misschien?"',
      'Bespreek: "Verandert dit iets aan hoe jij het ziet? Wat zou je nu anders willen doen?"',
    ],
    reflection: 'Kon je kind het perspectief van de ander innemen? Veranderde het iets aan het oordeel?',
    scienceNote: 'Actieve perspectiefneming vermindert vijandige attributiebias en bevordert constructieve conflictoplossing (Dodge, 1980; Selman, 1980).',
    durationMin: 10,
  },

  // =====================================================================
  // AGE GROUP 13-16 (10 tasks)
  // =====================================================================
  {
    id: 'aanw_13-16_340',
    skill: 'Aanwezigheid',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Beschikbaar zijn zonder te pushen',
    description: 'Oefen aanwezig zijn voor je tiener zonder een gesprek te forceren.',
    instructions: [
      'Zoek een moment waarop je tiener thuis is en iets rustigs doet.',
      'Ga in dezelfde ruimte zitten zonder een gesprek te starten — lees, drink koffie, wees gewoon aanwezig.',
      'Als je tiener iets zegt, reageer warm maar kort. Stel geen doorvragen tenzij het wordt uitgenodigd.',
      'Herhaal dit meerdere keren deze week en let op of je tiener vanzelf meer deelt.',
    ],
    reflection: 'Hoe voelde het om beschikbaar te zijn zonder iets te forceren? Merkte je een verschil in hoeveel je tiener deelde?',
    scienceNote: 'Adolescenten hebben behoefte aan autonomie maar ook aan beschikbare ouders; passieve beschikbaarheid verlaagt weerstand en vergroot openheid (Laursen & Collins, 2009; Allen & Land, 1999).',
    durationMin: 15,
  },
  {
    id: 'emco_13-16_341',
    skill: 'Emotiecoaching',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Valideren zonder het eens te zijn',
    description: 'Oefen het valideren van de emoties van je tiener, ook als je het niet eens bent met de situatie.',
    instructions: [
      'Wacht op een moment dat je tiener klaagt of gefrustreerd is over iets waar jij anders over denkt.',
      'Erken de emotie eerst: "Ik snap dat je daar boos over bent. Dat klinkt echt vervelend."',
      'Weersta de neiging om te corrigeren of te relativeren — houd het bij de emotie.',
      'Pas daarna, als de emotie gezakt is, kun je voorzichtig je eigen perspectief delen.',
    ],
    reflection: 'Lukte het om te valideren zonder het eens te zijn? Hoe reageerde je tiener anders dan wanneer je meteen je mening geeft?',
    scienceNote: 'Emotionele validatie vermindert emotionele arousal en vergroot de bereidheid tot probleemoplossing bij adolescenten (Linehan, 1993; Gottman, 1997).',
    durationMin: 10,
  },
  {
    id: 'zelr_13-16_342',
    skill: 'Zelfregulatie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Stressmanagementplan maken',
    description: 'Help je tiener een persoonlijk stressmanagementplan te ontwikkelen voor drukke periodes.',
    instructions: [
      'Bespreek: "Wanneer voel je de meeste stress? Wat zijn je grootste stressbronnen op dit moment?"',
      'Inventariseer samen wat al helpt: sporten, muziek luisteren, met vrienden praten, alleen zijn.',
      'Maak een concreet plan met drie strategieën die je tiener kan inzetten bij toetsweken of sociale stress.',
      'Schrijf het plan op en hang het op een plek waar je tiener het ziet.',
    ],
    reflection: 'Wist je tiener al wat werkt bij stress? Hoe kun je dit plan ondersteunen zonder het over te nemen?',
    scienceNote: 'Proactieve copingplanning vermindert de impact van stress op het welzijn van adolescenten (Compas et al., 2001; Lazarus & Folkman, 1984).',
    durationMin: 15,
  },
  {
    id: 'gren_13-16_343',
    skill: 'Grenzen',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Grenzen onderhandelen',
    description: 'Onderhandel samen over een huisregel waar je tiener meer vrijheid in wil.',
    instructions: [
      'Vraag: "Is er een regel waar je het niet mee eens bent of waar je meer vrijheid in wilt?"',
      'Luister naar het argument en neem het serieus — ook als je het er niet mee eens bent.',
      'Zoek samen een compromis: "Wat als we het zo doen... zou dat voor jou werken?"',
      'Spreek een proefperiode af: "We proberen het een maand en evalueren dan samen."',
    ],
    reflection: 'Hoe was het om te onderhandelen in plaats van op te leggen? Voelde het als een gelijkwaardiger gesprek?',
    scienceNote: 'Gezamenlijke besluitvorming over regels vergroot de naleving en het gevoel van autonomie bij adolescenten (Smetana, 2011; Deci & Ryan, 2000).',
    durationMin: 15,
  },
  {
    id: 'verb_13-16_344',
    skill: 'Verbinding',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Kwetsbaarheid tonen als vader',
    description: 'Deel een eigen emotionele ervaring om je tiener te laten zien dat ook vaders kwetsbaar mogen zijn.',
    instructions: [
      'Kies een geschikt moment en deel iets waar je zelf mee zit: werkstress, onzekerheid, een lastige keuze.',
      'Wees eerlijk maar leeftijdsgeschikt — het doel is verbinding, niet belasting.',
      'Vertel ook wat je eraan doet of hoe je ermee omgaat.',
      'Vraag je tiener: "Herken jij dat gevoel? Hoe ga jij daarmee om?"',
    ],
    reflection: 'Hoe reageerde je tiener op jouw kwetsbaarheid? Opende het een deur naar dieper contact?',
    scienceNote: 'Ouderlijke zelfopenbaring die leeftijdsgeschikt is, bevordert intimitiet en emotionele openheid in de ouder-adolescentrelatie (Baumrind, 1991; Steinberg, 2001).',
    durationMin: 10,
  },
  {
    id: 'hers_13-16_345',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Verantwoordelijkheid nemen bij een fout',
    description: 'Neem als vader verantwoordelijkheid voor een fout tegenover je tiener en model herstelvermogen.',
    instructions: [
      'Identificeer een recente situatie waarin je onrechtvaardig, ongeduldig of niet-begrijpend was.',
      'Zoek je tiener op en zeg: "Ik wil even terugkomen op [situatie]. Ik had dat anders moeten doen."',
      'Wees specifiek: benoem wat je deed, waarom het niet oké was, en wat je voortaan anders wilt doen.',
      'Vraag: "Hoe was dat voor jou? Is er iets wat je nog wilt zeggen?"',
    ],
    reflection: 'Hoe reageerde je tiener? Was het moeilijk om als ouder verantwoordelijkheid te nemen? Wat leverde het op?',
    scienceNote: 'Ouders die fouten erkennen en herstellen modellen emotionele intelligentie en versterken het vertrouwen in de relatie (Siegel & Bryson, 2014; Gottman, 2011).',
    durationMin: 10,
  },
  {
    id: 'auto_13-16_346',
    skill: 'Autonomie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Moreel dilemma bespreken',
    description: 'Bespreek samen een moreel dilemma om ethisch denken en eigenstandig redeneren te stimuleren.',
    instructions: [
      'Kies een dilemma: "Je beste vriend spiekt bij een toets. Zeg je er iets van?"',
      'Laat je tiener eerst nadenken en zijn of haar standpunt uitleggen.',
      'Stel Socratische vragen: "Wat als het andersom was? Wat is het eerlijkst voor iedereen?"',
      'Deel ook jouw perspectief, maar presenteer het als één mogelijke visie, niet als het juiste antwoord.',
    ],
    reflection: 'Hoe redeneerde je tiener? Zag je tekenen van eigenstandig moreel denken?',
    scienceNote: 'Discussie over morele dilemma\'s stimuleert de ontwikkeling naar hogere stadia van moreel redeneren (Kohlberg, 1984; Walker & Taylor, 1991).',
    durationMin: 15,
  },
  {
    id: 'refl_13-16_347',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Wie wil ik zijn-gesprek',
    description: 'Voer een open gesprek met je tiener over identiteit en de persoon die hij of zij wil worden.',
    instructions: [
      'Kies een rustig moment en vraag: "Als je aan jezelf over vijf jaar denkt, wie wil je dan zijn?"',
      'Luister aandachtig en stel doorvragen: "Wat voor vriend? Wat voor student? Wat voor persoon?"',
      'Deel ook iets over jezelf op die leeftijd: "Toen ik zo oud was als jij, wilde ik..."',
      'Sluit af: "Ik ben benieuwd hoe dat gaat worden. Ik sta achter je, whatever."',
    ],
    reflection: 'Wat vertelde je tiener over de toekomst? Hoe verhoudt dat beeld zich tot wie je tiener nu is?',
    scienceNote: 'Identiteitsexploratie is de kernuitdaging van de adolescentie in Eriksons stadium "identiteit vs. rolverwarring" (Erikson, 1968; Marcia, 1966).',
    durationMin: 10,
  },
  {
    id: 'emco_13-16_348',
    skill: 'Emotiecoaching',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Emotionele intelligentie bij vriendschapsconflicten',
    description: 'Coach je tiener door een complex vriendschapsconflict met aandacht voor alle perspectieven.',
    instructions: [
      'Wanneer je tiener vertelt over een vriendschapsconflict, luister eerst volledig uit.',
      'Vraag: "Hoe voel je je daarbij? Welke emoties zitten er allemaal in?"',
      'Help alle perspectieven te zien: "Hoe zou [naam] het ervaren hebben? En wat speelt er misschien op de achtergrond?"',
      'Begeleid naar een eigen beslissing: "Wat zou je willen dat er gebeurt? En wat kun jij daaraan bijdragen?"',
    ],
    reflection: 'Kon je tiener meerdere perspectieven zien? Hoe zelfstandig kwam hij of zij tot een plan?',
    scienceNote: 'Adolescenten die gecoacht worden in emotionele intelligentie bij sociale conflicten ontwikkelen sterkere relationele vaardigheden (Mayer & Salovey, 1997; Lopes et al., 2004).',
    durationMin: 15,
  },
  {
    id: 'refl_13-16_349',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Wat heb ik van jou geleerd',
    description: 'Vertel je tiener concreet wat jij van hem of haar hebt geleerd als vader.',
    instructions: [
      'Kies een rustig moment en zeg: "Ik wil je iets vertellen. Ik leer ook van jou."',
      'Noem drie specifieke dingen: "Van jou heb ik geleerd om geduldiger te zijn / om dingen vanuit een ander perspectief te zien / om minder snel te oordelen."',
      'Leg bij elk punt uit hoe: "Toen jij laatst zei dat... liet me dat nadenken over..."',
      'Vraag je tiener: "Is er iets dat jij van mij hebt geleerd?"',
    ],
    reflection: 'Hoe reageerde je tiener? Wat deed het met de relatie om als vader kwetsbaar en dankbaar te zijn?',
    scienceNote: 'Wederkerige erkenning in de ouder-kindrelatie bevordert het gevoel van competentie en de relatiekwaliteit in de adolescentie (Steinberg & Silk, 2002; Ryan & Deci, 2000).',
    durationMin: 10,
  },
];
