// Autonomie – Ronde 2: 50 nieuwe interactieve taken (5 leeftijdsgroepen × 10)
import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_14: InteractiveTask[] = [

  // ─── 0-2 jaar ────────────────────────────────────────────────
  {
    id: 'auto_02_11',
    title: 'Laat hem kiezen wat hij aantrekt',
    skill: 'Autonomie',
    description: 'Leg twee outfits neer die allebei oké zijn. Laat je peuter kiezen welke hij aantrekt, ook als het niet jouw voorkeur is. Aanvaard zijn keuze volledig.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Kleine keuzes geven peuters een gevoel van controle over hun wereld. Dit vermindert verzet bij verplichte activiteiten en bouwt het fundament voor zelfstandigheid.',
    skillTip: 'Bied altijd twee opties, niet meer. Te veel keuze overweldigt op deze leeftijd.',
    vermijd: 'Vermijd zijn keuze corrigeren of "beter" maken. Beiden passen – dat is genoeg.',
    leerdoel: 'Je geeft je kind vroege autonomie-ervaringen via betekenisvolle kleine keuzes.',
    bron: 'Deci, E.L. & Ryan, R.M. (1985). Intrinsic Motivation and Self-Determination in Human Behavior.',
  },
  {
    id: 'auto_02_12',
    title: 'Spel volgen, niet leiden',
    skill: 'Autonomie',
    description: 'Speel 10 minuten mee met je kind, maar laat hij alles bepalen: wat jullie spelen, hoe, wanneer het stopt. Jij bent de assistent, hij is de directeur.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Kind-geleid spel vergroot het gevoel van competentie en autonomie. Vader die volgt signaleert: "Jouw ideeën zijn goed genoeg om te volgen."',
    skillTip: 'Als hij stopt: wacht. Als hij iets nieuws start: volg. Jij hebt geen agenda.',
    vermijd: 'Vermijd subtiel sturen door "interessante" dingen te laten zien. Echt volgen betekent zijn tempo en zijn richting.',
    leerdoel: 'Je ervaart volgend spelen als actieve ondersteuning van zijn autonomieontwikkeling.',
    bron: 'Landreth, G.L. (2012). Play Therapy: The Art of the Relationship.',
  },
  {
    id: 'auto_02_13',
    title: 'Zelf proberen voor je helpt',
    skill: 'Autonomie',
    description: 'Als je kind iets probeert (schoen aantrekken, blok stapelen): wacht eerst. Laat hem het proberen. Help pas als hij echt vastloopt of echt om hulp vraagt.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'De zone van naaste ontwikkeling (Vygotsky) suggereert dat uitdaging net boven het huidige niveau de meeste groei geeft. Te vroeg helpen ontneemt die groeikans.',
    skillTip: 'Tel intern tot 15 voor je ingrijpt. Dat is langer dan je denkt – maar minder lang dan hij nodig heeft.',
    vermijd: 'Vermijd overnemen als het tergend langzaam gaat. Zijn tempo is zijn leermoment.',
    leerdoel: 'Je leert wachten als actieve bijdrage aan zijn autonomieontwikkeling.',
    bron: 'Vygotsky, L.S. (1978). Mind in Society: The Development of Higher Psychological Processes.',
  },
  {
    id: 'auto_02_14',
    title: 'Zijn nee respecteren bij voedsel',
    skill: 'Autonomie',
    description: 'Als je peuter zijn mond dicht houdt of zijn hoofd wegdraait bij eten: respecteer dat. Geen lepel aandringen. "Oké, je wil dit niet." En laat het.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kinderen zijn van nature goede honger-regulatoren. Forceren bij eten beschadigt het interoceptieve bewustzijn en kan leiden tot eetproblemen later. Autonomie bij eten is essentieel.',
    skillTip: 'Vertrouw zijn honger- en verzadigingssignalen. Ze weten beter dan jij wanneer ze genoeg hebben.',
    vermijd: 'Vermijd "nog één hapje" aandringen. Dat doorbreekt de eetautonomie.',
    leerdoel: 'Je respecteert zijn lichamelijke autonomie bij eten als fundament voor gezonde eetgewoonten.',
    bron: 'Satter, E. (2000). Child of Mine: Feeding with Love and Good Sense.',
  },
  {
    id: 'auto_02_15',
    title: 'Eigen tempo bij aankleden',
    skill: 'Autonomie',
    description: 'Plan extra tijd voor het aankleden. Laat je peuter zoveel mogelijk zelf doen: sokken aantrekken, knopen proberen, jas pakken. Jij assisteert alleen waar echt nodig.',
    duration: '15 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Zelfstandig aankleden vergroot de motorische competentie en het gevoel van autonomie tegelijk. Kinderen die dit leren, zijn trotser en zelfstandiger in andere domeinen ook.',
    skillTip: 'Zeg: "Probeer jij het eerst." Wacht. Dan: "Wil je dat ik help?" Vraag altijd toestemming voor je helpt.',
    vermijd: 'Vermijd het overnemen omdat het sneller gaat. Zijn leerproces is het doel, niet de snelheid.',
    leerdoel: 'Je bevordert motorische zelfstandigheid door zijn tempo te respecteren en hem te laten proberen.',
    bron: 'Montessori, M. (1912). The Montessori Method.',
  },
  {
    id: 'auto_02_16',
    title: 'Enthousiasme erkennen bij initiatieven',
    skill: 'Autonomie',
    description: 'Als je kind spontaan iets initieert (een spelletje, contact zoeken, een geluid): reageer enthousiast. "Ja! Jij begon dat zelf!" Bevestig zijn initiatief.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Bevestiging van initiatief vergroot de kans dat het kind vaker initiatief neemt. Dit is de basis van intrinsieke motivatie en autonomiegericht gedrag.',
    skillTip: 'Reageer direct. De reactiesnelheid communiceert hoe belangrijk zijn initiatief is.',
    vermijd: 'Vermijd zijn initiatief negeren of overnemen. Volg zijn lead.',
    leerdoel: 'Je versterkt de neiging tot initiatiefname als kern van autonomieontwikkeling.',
    bron: 'White, R.W. (1959). Motivation reconsidered: The concept of competence.',
  },
  {
    id: 'auto_02_17',
    title: 'Probleemoplossing zelf laten proberen',
    skill: 'Autonomie',
    description: 'Als je peuter vast zit (puzzelstuk past niet, deur gaat niet open): laat hem eerst zelf oplossingen proberen. Observeer. Moedig aan. Geef geen hint tenzij hij echt vastzit.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Probleemoplossing leren vereist frustratie-tolerantie. Vader die te snel helpt, ontneemt het kind de kans om zijn probleemoplossend vermogen te ontwikkelen.',
    skillTip: 'Zeg: "Hmm, hoe zou dat kunnen?" in plaats van het antwoord te geven. Dat activeert zijn denken zonder te helpen.',
    vermijd: 'Vermijd het probleem voor hem oplossen. Wees aanwezig maar niet interveniërend.',
    leerdoel: 'Je stimuleert probleemoplossend denken door te wachten en te laten proberen.',
    bron: 'Piaget, J. (1952). The Origins of Intelligence in Children.',
  },
  {
    id: 'auto_02_18',
    title: 'Zelfstandige verkenning faciliteren',
    skill: 'Autonomie',
    description: 'Creëer een veilige ruimte en laat je baby of peuter vrij verkennen. Jij zit in de buurt als veilige basis maar bemoeit je niet met wat hij ontdekt.',
    duration: '15 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Verkenning vanuit een veilige basis is het basispatroon van gezonde hechting én autonomieontwikkeling. De aanwezigheid van vader maakt veilig verkennen mogelijk.',
    skillTip: 'Maak de ruimte veilig van tevoren zodat je niet hoeft in te grijpen. Dan kun je echt laten verkennen.',
    vermijd: 'Vermijd constant waarschuwen of achter hem aanlopen. Vertrouw de veilige ruimte die je creëerde.',
    leerdoel: 'Je fungeert als veilige basis waarvanuit je kind vrij kan verkennen.',
    bron: 'Ainsworth, M.D.S. et al. (1978). Patterns of Attachment.',
  },
  {
    id: 'auto_02_19',
    title: 'Zijn keuze voor speelgoed respecteren',
    skill: 'Autonomie',
    description: 'Als je kind steeds voor hetzelfde speelgoed kiest (ook als jij vindt dat iets anders leuker of leerrijker is): respecteer zijn keuze. Volg zijn interesse.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Speelgoedkeuzes volgen de intrinsieke interesse van het kind. Interesse-gedreven spel is het meest effectieve leermedium. Zijn keuze is zijn leerstijl.',
    skillTip: 'Observeer waarom hij steeds dat speelgoed kiest. Wat fascineert hem eraan? Dat is informatie.',
    vermijd: 'Vermijd "maar dit is leuker" of afwisseling forceren. Herhaling is ook leren.',
    leerdoel: 'Je leert de intrinsieke interesse van je kind te respecteren als leerdrijver.',
    bron: 'Csikszentmihalyi, M. (1990). Flow: The Psychology of Optimal Experience.',
  },
  {
    id: 'auto_02_20',
    title: 'Trots benoemen bij zelfstandig doen',
    skill: 'Autonomie',
    description: 'Als je kind iets zelfstandig lukt: benoem zijn trots in plaats van jouw trots. "Jij deed dat zelf! Hoe voelt dat?" Maak de prestatie van hem, niet van jou.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Zelftrots is krachtiger dan externe trots voor het ontwikkelen van intrinsieke motivatie. Vader die het kind zijn eigen succes laat voelen, versterkt de autonomie-ontwikkeling.',
    skillTip: 'Gebruik "jij" in plaats van "ik": "Jij deed het!" niet "Ik ben trots op je." Maak het zijn moment.',
    vermijd: 'Vermijd de prestatie overnemen: "Zie je wel, ik wist dat je het kon." Dat maakt het over jou.',
    leerdoel: 'Je vergroot zijn gevoel van zelfcompetentie door zijn successen van hem te maken.',
    bron: 'Deci, E.L. & Ryan, R.M. (1985). Intrinsic Motivation and Self-Determination.',
  },

  // ─── 3-5 jaar ────────────────────────────────────────────────
  {
    id: 'auto_35_11',
    title: 'Zijn eigen dag plannen',
    skill: 'Autonomie',
    description: 'Vraag je kind op een vrije dag: "Wat wil jij vandaag doen?" Maak een plan samen op basis van zijn wensen. Voer het uit.',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Zelf een dag plannen vergroot het gevoel van controle en eigenaarschap. Kinderen die hun dag mogen bepalen zijn meer gemotiveerd en coöperatiever bij de verplichte delen.',
    skillTip: 'Schrijf zijn plan op (of teken het). Dat maakt het concreet en geeft hem het gevoel dat het serieus genomen wordt.',
    vermijd: 'Vermijd zijn plan bijstellen of praktische bezwaren insluipen. Duik in zijn wereld.',
    leerdoel: 'Je geeft je kind ervaring met dagplanning als vroege autonomievaardigheid.',
    bron: 'Deci, E.L. & Ryan, R.M. (2000). Self-Determination Theory.',
  },
  {
    id: 'auto_35_12',
    title: 'Zijn regel in het spel accepteren',
    skill: 'Autonomie',
    description: 'Laat je kind een spel uitvinden of de regels van een bestaand spel aanpassen. Speel mee volgens zijn regels, ook als ze "verkeerd" zijn of onlogisch voor jou.',
    duration: '20 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Regels mogen bepalen geeft kinderen de ervaring van regelgeving en sociale controle vanuit autonomie. Dit is een vroege vorm van morele en sociale ontwikkeling.',
    skillTip: 'Vraag: "Wat is de regel als...?" en volg dan echt zijn antwoord op. Zijn logica is zijn logica.',
    vermijd: 'Vermijd correcties of "eigenlijk is het zo". Laat zijn versie bestaan.',
    leerdoel: 'Je ervaart hoe autonomie in spel creativiteit en zelfvertrouwen stimuleert.',
    bron: 'Piaget, J. (1932). The Moral Judgment of the Child.',
  },
  {
    id: 'auto_35_13',
    title: 'Fout laten maken om van te leren',
    skill: 'Autonomie',
    description: 'Als je kind een keuze maakt die waarschijnlijk niet goed uitpakt (te weinig kleding, slechte volgorde): laat het. Bespreek daarna samen wat er gebeurde.',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Veilige fouten maken is de krachtigste leerschool voor autonomie. Kinderen die consequenties van hun eigen keuzes ervaren, leren beter en zijn intrinsiek gemotiveerder.',
    skillTip: 'Kies veilige situaties voor dit experiment. Niet bij gevaar of gezondheid, maar bij sociale of praktische keuzes.',
    vermijd: 'Vermijd "zie je wel, ik zei het toch" na de fout. Dat verandert de les in een triomf van jou.',
    leerdoel: 'Je geeft je kind de leerschool van veilig falen als autonomie-instrument.',
    bron: 'Dweck, C. (2006). Mindset: The New Psychology of Success.',
  },
  {
    id: 'auto_35_14',
    title: 'Verantwoordelijkheid geven bij klusjes',
    skill: 'Autonomie',
    description: 'Geef je kind een echt klusje in het huishouden dat van hem is: de planten water geven, de post ophalen, de dierenvoederbak vullen. Echt verantwoordelijk, niet helpen.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Echte verantwoordelijkheid (niet neppretje) vergroot het gevoel van bijdragen aan het gezin. Dit stimuleert de prosociale motivatie en het gevoel van competentie.',
    skillTip: 'Laat het echt zijn. Als de planten niet water krijgen – dat is zijn taak, niet jouw back-up. Het maakt de verantwoordelijkheid echt.',
    vermijd: 'Vermijd het klusje overnemen als hij het vergeet. Vraag het hem te doen.',
    leerdoel: 'Je bevordert zijn gevoel van bijdrage en competentie via echte verantwoordelijkheid.',
    bron: 'Erikson, E.H. (1950). Childhood and Society.',
  },
  {
    id: 'auto_35_15',
    title: 'Zijn mening vragen bij beslissingen',
    skill: 'Autonomie',
    description: 'Bij een beslissing die hem raakt: vraag zijn mening echt. "Wat vind jij dat we moeten doen?" Luister. Verwerk zijn input in de beslissing, ook al is het maar een klein deel.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Mening gevraagd worden vergroot het gevoel van autonomie en sociale participatie. Kinderen die weten dat hun mening telt, zijn actiever in het uitdrukken ervan.',
    skillTip: 'Benoem achteraf hoe zijn input meespeelde: "Ik heb jouw idee meegenomen." Dat bevestigt zijn invloed.',
    vermijd: 'Vermijd vragen stellen zonder zijn input te gebruiken. Vals participeren is erger dan niet vragen.',
    leerdoel: 'Je vergroot zijn gevoel van participatie en invloed via echte meningsvraag.',
    bron: 'Thibaut, J.W. & Walker, L. (1975). Procedural Justice.',
  },
  {
    id: 'auto_35_16',
    title: 'Zijn verdriet zelf laten verwerken',
    skill: 'Autonomie',
    description: 'Als je kind verdrietig is om een kleine teleurstelling: laat hem even zelf dat gevoel hebben. Zeg: "Ik zie dat je verdrietig bent. Ik ben er." Maar grijp niet meteen in.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kinderen die leren dat ze hun eigen verdriet kunnen overleven, bouwen emotionele veerkracht op. Te snel troosten ontneemt die kans. Aanwezigheid zonder interventie is de sleutel.',
    skillTip: 'Wacht 2 minuten voor je troost geeft. Die twee minuten zijn zijn ruimte om zijn eigen veerkracht te vinden.',
    vermijd: 'Vermijd het probleem oplossen of de teleurstelling minimaliseren. Zijn gevoel is zijn leermoment.',
    leerdoel: 'Je leert de grens tussen ondersteuning bieden en zijn emotionele autonomie respecteren.',
    bron: 'Neff, K. (2011). Self-Compassion.',
  },
  {
    id: 'auto_35_17',
    title: 'Zelf opruimen – zijn manier',
    skill: 'Autonomie',
    description: 'Vraag je kind zijn speelkamer of speelhoek op te ruimen. Zeg niet hoe. Aanvaard hoe hij het doet, ook als het niet perfect of niet jouw manier is.',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Autonomie in de uitvoering van taken vergroot de motivatie om ze te doen. Kinderen die hun eigen methode mogen bepalen, ervaren eigenaarschap over het resultaat.',
    skillTip: 'Criteria voor succes: is het "goed genoeg"? Dan is het goed. Perfectie is niet het doel.',
    vermijd: 'Vermijd herrangschikken of verbeteren na afloop. Dat ondermijnt zijn eigenaarschap.',
    leerdoel: 'Je leert eigenaarschap bij taken te bevorderen door de uitvoeringsautonomie te respecteren.',
    bron: 'Montessori, M. (1912). The Montessori Method.',
  },
  {
    id: 'auto_35_18',
    title: 'Nieuwe dingen zelf proberen laten',
    skill: 'Autonomie',
    description: 'Bij een nieuwe vaardigheid (schommelen, klimmen, fietsen): laat hem het eerst zelf proberen voor je demonstreert. Observeer zijn aanpak. Bied daarna wat aanvulling.',
    duration: '15 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Eerst zelf proberen voor er instructie is, vergroot de motivatie voor de instructie. Het kind is dan intrinsiek geïnteresseerd in wat beter kan. Instructie na experimenteren werkt het best.',
    skillTip: 'Houd je eerste commentaar positief en observerend: "Ik zie dat je dit probeerde. Wil je een tip?"',
    vermijd: 'Vermijd direct demonstreren hoe het "moet". Eerst zijn initiatief, dan aanvulling.',
    leerdoel: 'Je leert leerproces te beginnen vanuit zijn initiatief in plaats van jouw instructie.',
    bron: 'Vygotsky, L.S. (1978). Mind in Society.',
  },
  {
    id: 'auto_35_19',
    title: 'Conflict zelf laten oplossen',
    skill: 'Autonomie',
    description: 'Als je kinderen (of je kind en een vriendje) ruzie hebben: wacht af. Laat ze eerst zelf proberen het op te lossen. Grijp pas in als het uit de hand loopt.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Conflictoplossing is een sociale vaardigheid die oefening vereist. Te snel ingrijpen ontneemt die oefening. Kinderen die zelf conflicten leren oplossen, zijn sociaal competenter.',
    skillTip: 'Wees aanwezig als observator. Zeg niets tenzij de veiligheid in gevaar is. Dan pas.',
    vermijd: 'Vermijd partij kiezen of te snel oplossen. Geef ze de kans voor jij ingrijpt.',
    leerdoel: 'Je stimuleert sociale autonomie door conflictoplossing zelf te laten proberen.',
    bron: 'Rubin, K.H. et al. (2006). Peer interactions, relationships, and groups.',
  },
  {
    id: 'auto_35_20',
    title: 'Zijn tempo bij leren accepteren',
    skill: 'Autonomie',
    description: 'Als je kind iets leert (lezen, fietsen, zwemmen) in zijn eigen tempo: accepteer dat tempo volledig. Vergelijk niet met anderen. Vertrouw zijn curve.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Elk kind heeft een unieke ontwikkelingscurve. Druk om sneller te gaan vergroot angst en vermindert de intrinsieke motivatie. Vertrouwen in zijn tempo is de grootste steun.',
    skillTip: 'Noteer vooruitgang in vergelijking met zichzelf, niet met anderen: "Twee weken geleden kon je nog niet..."',
    vermijd: 'Vermijd "maar [ander kind] kan het al." Vergelijking is de moordenaar van intrinsieke motivatie.',
    leerdoel: 'Je leert zijn individuele leercurve te vertrouwen en te respecteren.',
    bron: 'Dweck, C. (2006). Mindset: The New Psychology of Success.',
  },

  // ─── 6-9 jaar ────────────────────────────────────────────────
  {
    id: 'auto_69_11',
    title: 'Zijn eigen route kiezen',
    skill: 'Autonomie',
    description: 'Laat je kind de route bepalen naar een bekende bestemming: school, supermarkt, speeltuin. Hij gaat voor. Jij volgt. Geef geen aanwijzingen tenzij echt nodig.',
    duration: '20 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Routeautonomie vergroot het gevoel van ruimtelijke zelfstandigheid. Kinderen die hun eigen weg mogen bepalen, ontwikkelen sneller ruimtelijk inzicht en zelfvertrouwen.',
    skillTip: 'Als hij de verkeerde kant op gaat: laat het even. Soms is een omweg zijn eigen ontdekkingsreis.',
    vermijd: 'Vermijd corrigeren tenzij jullie echt verdwalen op een onveilige manier.',
    leerdoel: 'Je vergroot zijn ruimtelijke autonomie en navigatievertrouwen via echte routevrijheid.',
    bron: 'Guldberg, H. (2009). Reclaiming Childhood: Freedom and Play in an Age of Fear.',
  },
  {
    id: 'auto_69_12',
    title: 'Zijn eigen onderzoek doen',
    skill: 'Autonomie',
    description: 'Als je kind een vraag stelt: zeg in plaats van het antwoord geven: "Goede vraag. Hoe zou jij dat uitzoeken?" Laat hem het onderzoeksproces zelf initiëren.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Zelf antwoorden zoeken vergroot de intellectuele autonomie en de intrinsieke nieuwsgierigheid. Kinderen die leren hoe ze leren, worden levenslang betere leerders.',
    skillTip: 'Doe mee met het onderzoek, maar laat hem leiden. "Waar zoeken we eerst?" is een goede samenwerkvraag.',
    vermijd: 'Vermijd het antwoord geven als hij het zelf kan vinden. Het proces is waardevoller dan het antwoord.',
    leerdoel: 'Je stimuleert intellectuele autonomie door hem zijn eigen onderzoeksweg te laten vinden.',
    bron: 'Piaget, J. (1952). The Origins of Intelligence in Children.',
  },
  {
    id: 'auto_69_13',
    title: 'Zelfstandig naar vriendjes gaan',
    skill: 'Autonomie',
    description: 'Laat je kind (als veilig in jullie omgeving) zelfstandig naar een vriendje lopen of fietsen. Bied hulp bij het plannen maar niet bij het uitvoeren.',
    duration: '20 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Zelfstandige verplaatsing vergroot het gevoel van competentie en vergroot tegelijk de sociale netwerken van het kind. Het is ook een oefening in verantwoordelijkheid nemen.',
    skillTip: 'Bespreek van tevoren de route en afspraken (wanneer thuis, wat te doen als er iets is). Voorbereiding maakt echte zelfstandigheid mogelijk.',
    vermijd: 'Vermijd stiekem meelopen of constant bellen. Vertrouwen is de boodschap die je wil geven.',
    leerdoel: 'Je geeft je kind echte zelfstandigheid in sociale verplaatsing als autonomiemijlpaal.',
    bron: 'Skenazy, L. (2009). Free-Range Kids: Giving Our Children the Freedom We Had Without Going Nuts with Worry.',
  },
  {
    id: 'auto_69_14',
    title: 'Zijn project begeleiden zonder sturen',
    skill: 'Autonomie',
    description: 'Als je kind een project heeft (tekening, bouwwerk, verhaal): vraag hoe je kunt helpen zonder de leiding over te nemen. Jij bent assistent, hij is directeur.',
    duration: '20 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Eigenaarschap over creatieve projecten is essentieel voor intrinsieke motivatie en artistieke identiteitsontwikkeling. Vader die volgt in plaats van leidt, respecteert zijn creatieve autonomie.',
    skillTip: 'Vraag: "Wat heb je nodig van mij?" in plaats van te beginnen met helpen. Dat zet zijn agenda centraal.',
    vermijd: 'Vermijd "wat als je dit zo deed" of het toevoegen van jouw ideeën. Dit is zijn project.',
    leerdoel: 'Je ervaart hoe assistent-zijn in zijn project zijn creatieve autonomie versterkt.',
    bron: 'Amabile, T.M. (1996). Creativity in Context.',
  },
  {
    id: 'auto_69_15',
    title: 'Geld leren beheren',
    skill: 'Autonomie',
    description: 'Geef je kind een klein bedrag zakgeld en laat hem zelf beslissen hoe hij het uitgeeft of spaart. Geen advies tenzij gevraagd. Laat hem zijn eigen financiële keuzes maken.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Financiële autonomie in het klein vergroot de besluitvaardigheid en het leren van consequenties van keuzes. Kinderen die vroeg leren omgaan met geld, zijn financieel competenter.',
    skillTip: 'Als hij direct alles uitgeeft en dan spijt heeft: laat die spijt er zijn. Het is zijn beste les.',
    vermijd: 'Vermijd hem adviseren "dat je beter kunt sparen". Zijn keuze, zijn consequentie.',
    leerdoel: 'Je introduceert financiële autonomie als leerschool voor besluitvorming en consequentie.',
    bron: 'Levine, M. (2006). The Price of Privilege.',
  },
  {
    id: 'auto_69_16',
    title: 'Huiswerk zelf plannen',
    skill: 'Autonomie',
    description: 'Laat je kind zelf bepalen wanneer en hoe hij zijn huiswerk doet (binnen redelijke kaders). Grijp alleen in als hij echt in de problemen komt. Geef hem de kans te leren plannen.',
    duration: '15 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Zelfregulatie bij leren is een van de sterkste voorspellers van academisch succes. Kinderen die leren hun eigen leerproces te plannen, presteren beter dan kinderen wiens ouders dat doen.',
    skillTip: 'Bied aan: "Wil je dat ik je herinner?" Dan is de keuze bij hem, niet de controle bij jou.',
    vermijd: 'Vermijd constant checken of het gedaan wordt. Geef hem de ruimte en de consequentie.',
    leerdoel: 'Je stimuleert zelfgestuurde leerplanning als kerncomponent van academische autonomie.',
    bron: 'Zimmerman, B.J. (1990). Self-Regulated Learning and Academic Achievement.',
  },
  {
    id: 'auto_69_17',
    title: 'Zijn eigen beslissing evalueren',
    skill: 'Autonomie',
    description: 'Na een keuze die hij maakte: vraag hem achteraf: "Wat vind je zelf van die beslissing? Zou je het nog een keer zo doen? Waarom wel of niet?"',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Beslissingsevaluatie vergroot het metacognitieve bewustzijn. Kinderen die leren nadenken over hun keuzes, worden bewustere beslissers.',
    skillTip: 'Stel open vragen. Geen oordeel geven. Hij evalueert – jij luistert en vraagt eventueel door.',
    vermijd: 'Vermijd zijn evaluatie sturen naar het "juiste" oordeel. Zijn eigen beoordeling is het doel.',
    leerdoel: 'Je vergroot zijn metacognitieve vaardigheid via systematische beslissingsevaluatie.',
    bron: 'Flavell, J.H. (1979). Metacognition and cognitive monitoring.',
  },
  {
    id: 'auto_69_18',
    title: 'Zijn interesse serieus nemen',
    skill: 'Autonomie',
    description: 'Wat zijn kind op dit moment fascineert (dino\'s, ruimtevaart, Minecraft, tekenen): ga er echt in mee. Zoek samen meer informatie. Verdiep zijn interesse zonder te sturen.',
    duration: '20 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Diepe interesses zijn motors van intrinsieke motivatie en identiteitsvorming. Vader die zijn interesse serieus neemt, versterkt zijn identiteitsautonomie en zijn zelfvertrouwen.',
    skillTip: 'Laat zijn interesse jou echt iets leren. Stel vragen die jij echt wil weten. Dat toont echte interesse.',
    vermijd: 'Vermijd zijn interesse ombuigen naar iets wat jij interessanter vindt. Zijn interesse is zijn kompas.',
    leerdoel: 'Je versterkt zijn identiteitsautonomie door zijn passie serieus te nemen.',
    bron: 'Csikszentmihalyi, M. (1990). Flow: The Psychology of Optimal Experience.',
  },
  {
    id: 'auto_69_19',
    title: 'Zelf vragen om hulp leren',
    skill: 'Autonomie',
    description: 'Bespreek met je kind wanneer het slim is om hulp te vragen. Niet voor alles – maar ook niet alles alleen. Leer hem de tussenpositie: "Eerst probeer ik, dan vraag ik."',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Weten wanneer je hulp nodig hebt en dat kunnen vragen is een metavaardigheid. Kinderen die dit leren, zijn zowel autonomer als sociaal effectiever.',
    skillTip: 'Vraag: "Hoe lang heb je het al geprobeerd? Is dit het moment om hulp te vragen?" Maak het een bewuste keuze.',
    vermijd: 'Vermijd hem altijd pas te helpen als hij vraagt (te extreem) of altijd direct aanbieden (te voorkomend). De midden-positie is het doel.',
    leerdoel: 'Je leert je kind de balans tussen zelfstandigheid en hulp vragen als autonomievaardigheid.',
    bron: 'Vygotsky, L.S. (1978). Mind in Society.',
  },
  {
    id: 'auto_69_20',
    title: 'Zijn fout erkennen zonder te helpen',
    skill: 'Autonomie',
    description: 'Als je kind een fout maakt: laat hem de fout zien zonder het te repareren. Vraag: "Wat zou je anders doen?" Laat hem zijn eigen herstelplan maken.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Eigenaarschap over fouten en herstelplannen vergroot de intrinsieke motivatie om beter te doen. Vader die het herstel overneemt, ontneemt het kind de krachtigste leerervaring.',
    skillTip: 'Vraag: "Wat denk jij dat er beter kon?" in plaats van het uit te leggen. Zijn antwoord first.',
    vermijd: 'Vermijd directe foutcorrectie zonder hem eerst te vragen wat hij zelf ziet.',
    leerdoel: 'Je vergroot zijn eigenaarschap over fouten en herstel als kern van groei-georiënteerde autonomie.',
    bron: 'Dweck, C. (2006). Mindset: The New Psychology of Success.',
  },

  // ─── 10-12 jaar ──────────────────────────────────────────────
  {
    id: 'auto_1012_11',
    title: 'Zijn eigen mening verdedigen',
    skill: 'Autonomie',
    description: 'Daag je kind vriendelijk uit zijn mening te onderbouwen. Vraag door. Stel tegenvragen. Niet om hem te verslaan – maar om zijn argumentatievermogen te trainen.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Intellectuele autonomie vereist het kunnen verdedigen van een standpunt. Vader die vriendelijk uitdaagt en niet beoordeelt, traint kritisch denken in veilige context.',
    skillTip: 'Zeg na afloop: "Ik ben het er misschien niet mee eens, maar ik zie hoe je denkt." Dat bevestigt zijn autonomie.',
    vermijd: 'Vermijd winnen als doel. Het gaat om zijn denkvermogen, niet jouw gelijk.',
    leerdoel: 'Je traint zijn intellectuele autonomie en argumentatievermogen via vriendelijke uitdaging.',
    bron: 'Socrates (via Plato). Theaetetus.',
  },
  {
    id: 'auto_1012_12',
    title: 'Keuze bij activiteiten buitenshuis',
    skill: 'Autonomie',
    description: 'Laat je kind dit jaar één activiteit volledig zelf kiezen: sport, hobby, club. Jij faciliteert, hij kiest. Geen invloed op de keuze uitoefenen.',
    duration: '20 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Activiteitskeuze is sterk gelinkt aan identiteitsontwikkeling. Kinderen die hun eigen activiteiten kiezen, zijn meer gemotiveerd, presteren beter en blijven langer vol.',
    skillTip: 'Als zijn keuze je verrast of niet je voorkeur is: verberg dat. Zijn keuze is zijn keuze.',
    vermijd: 'Vermijd subtiel sturen naar jouw voorkeur via "wat denk je van...?" Echt laten kiezen is het doel.',
    leerdoel: 'Je ervaart hoe vrije activiteitskeuze zijn motivatie en identiteitsontwikkeling versterkt.',
    bron: 'Csikszentmihalyi, M. (1990). Flow.',
  },
  {
    id: 'auto_1012_13',
    title: 'Zijn sociale keuzes laten zijn',
    skill: 'Autonomie',
    description: 'Accepteer dat je kind vrienden kiest die je misschien niet je eerste keuze waren. Laat die vriendschappen groeien zonder te beoordelen, tenzij er echte zorgpunten zijn.',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Sociale keuzes zijn cruciale identiteitsuitdrukkingen in de pre-puberteit. Vader die die keuzes respecteert (tenzij gevaarlijk), bevordert de sociale autonomie.',
    skillTip: 'Als je zorgen hebt: stel vragen, geen oordelen. "Vertel me eens over [naam]" in plaats van "die vind ik geen goede invloed".',
    vermijd: 'Vermijd sociale keuzes te beoordelen op basis van oppervlakkige kenmerken (kleding, stijl, school).',
    leerdoel: 'Je respecteert zijn sociale autonomie als deel van zijn identiteitsontwikkeling.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'auto_1012_14',
    title: 'Zelfstandig informatie zoeken',
    skill: 'Autonomie',
    description: 'Als je kind een vraag heeft over iets in zijn leven (gezondheid, seksualiteit, geld): moedig hem aan zelf informatie te zoeken. Help hem de kwaliteit van bronnen beoordelen.',
    duration: '20 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Informatie-autonomie is cruciaal in het digitale tijdperk. Kinderen die leren zelf betrouwbare informatie te vinden, zijn sterker dan kinderen die alles van één bron ontvangen.',
    skillTip: 'Leer hem twee vragen bij elke bron: "Wie schreef dit en waarom?" en "Wat zeggen andere bronnen?" Dat is mediawijsheid.',
    vermijd: 'Vermijd al zijn vragen direct beantwoorden. Laat hem ook zelf zoeken.',
    leerdoel: 'Je stimuleert informatie-autonomie en mediawijsheid als 21e-eeuwse vaardigheden.',
    bron: 'Livingstone, S. (2009). Children and the Internet.',
  },
  {
    id: 'auto_1012_15',
    title: 'Zijn faalangst als autonomie-uitdaging',
    skill: 'Autonomie',
    description: 'Als je kind iets vermijdt uit angst om te falen: help hem onderscheid te maken tussen "ik wil dit niet" (autonomie) en "ik durf dit niet" (angst). Bespreek wat hij echt wil.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Faalangst is een autonomiebelemmering: het kind doet of niet-doet vanuit angst in plaats van vanuit eigenwaarden. Bewust maken van dit verschil vergroot echte autonomie.',
    skillTip: 'Vraag: "Als je wist dat je niet kon falen, zou je het dan willen?" Dat toont of het verlangen er is.',
    vermijd: 'Vermijd "durf gewoon" zeggen. Angst is reëel. Verken hem samen.',
    leerdoel: 'Je vergroot zijn onderscheid tussen angst-gedreven en waarden-gedreven keuzes.',
    bron: 'Hayes, S.C. et al. (1999). Acceptance and Commitment Therapy.',
  },
  {
    id: 'auto_1012_16',
    title: 'Zijn eigen leerproces evalueren',
    skill: 'Autonomie',
    description: 'Na een toets of prestatie: vraag hem hoe hij vond dat zijn voorbereiding was – niet het resultaat. Wat werkte? Wat niet? Wat zou hij anders doen? Zijn analyse staat centraal.',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Proces-evaluatie (hoe leerde ik) in plaats van resultaat-evaluatie (wat scoorde ik) vergroot de leerautonomie en de intrinsieke motivatie voor verbetering.',
    skillTip: 'Vraag: "Wat leerde je over hoe jij het beste leert?" Dat is de diepste evaluatievraag.',
    vermijd: 'Vermijd direct beginnen over het cijfer. Begin altijd bij het leerproces.',
    leerdoel: 'Je verschuift focus van resultaat naar leerproces als kern van autonome leerontwikkeling.',
    bron: 'Zimmerman, B.J. (1990). Self-Regulated Learning and Academic Achievement.',
  },
  {
    id: 'auto_1012_17',
    title: 'Zelf problemen oplossen voor advies',
    skill: 'Autonomie',
    description: 'Als je kind een probleem deelt: vraag eerst: "Wat heb je zelf al geprobeerd? Wat denk je dat zou helpen?" Pas als hij echt vastloopt: bied dan een idee aan.',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Probleemoplossende autonomie vergroot de self-efficacy. Kinderen die leren dat ze zelf oplossingen kunnen vinden, zijn resilientier en creatiever in nieuwe situaties.',
    skillTip: 'Vraag: "Wat denk jij dat een oplossing zou zijn?" en wacht dan echt op zijn antwoord. Geef tijd.',
    vermijd: 'Vermijd meteen in oplossingsmodus schieten. Zijn probleemoplossing gaat voor de jouwe.',
    leerdoel: 'Je stimuleert probleemoplossende autonomie door zijn proces voor jouw advies te laten gaan.',
    bron: 'Bandura, A. (1977). Self-efficacy: Toward a unifying theory of behavioral change.',
  },
  {
    id: 'auto_1012_18',
    title: 'Zijn leerstijl ontdekken',
    skill: 'Autonomie',
    description: 'Bespreek met je kind hoe hij het beste leert: visueel, via doen, via lezen, via uitleggen aan anderen. Help hem zijn eigen leerstijl te ontdekken en te benutten.',
    duration: '20 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kennis van de eigen leerstijl is een metacognitieve vaardigheid die de leerprestaties verhoogt. Kinderen die weten hoe ze leren, kunnen zelfstandiger en effectiever studeren.',
    skillTip: 'Probeer samen een kleine oefening in twee stijlen. Dan kan hij zelf vergelijken wat beter werkt.',
    vermijd: 'Vermijd een leerstijl als "de juiste" aanwijzen. Ze zijn alle persoonlijk en context-afhankelijk.',
    leerdoel: 'Je vergroot zijn metacognitieve zelfkennis als basis voor autonome leerontwikkeling.',
    bron: 'Flavell, J.H. (1979). Metacognition and cognitive monitoring.',
  },
  {
    id: 'auto_1012_19',
    title: 'Bijdrage aan gezinsbeslissingen',
    skill: 'Autonomie',
    description: 'Betrek je kind bij een echte gezinsbeslissing: vakantiebestemming, aanschaf, activiteit. Laat zijn mening echt meewegen. Vertel hoe zijn input de beslissing beïnvloedde.',
    duration: '20 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Participatie in gezinsbeslissingen vergroot het gevoel van sociale autonomie en behorend-zijn. Kinderen die echt meebeslissen, identificeren meer met het gezin.',
    skillTip: 'Maak de impact van zijn input zichtbaar: "Jij bracht [idee] in, en we gaan dat doen." Dat maakt participatie reëel.',
    vermijd: 'Vermijd schijnparticipatie waarbij de beslissing al vaststaat. Dat is erger dan niet vragen.',
    leerdoel: 'Je vergroot zijn sociale autonomie en gezinsidentificatie via echte participatie.',
    bron: 'Thibaut, J.W. & Walker, L. (1975). Procedural Justice.',
  },
  {
    id: 'auto_1012_20',
    title: 'Zelf doelen stellen',
    skill: 'Autonomie',
    description: 'Help je kind zijn eigen doelen formuleren voor de komende maand: in school, sport, sociaal. Schrijf ze op. Evalueer na een maand samen: hoe ging het?',
    duration: '20 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Zelfgestelde doelen zijn significant effectiever dan opgelegde doelen. Kinderen die hun eigen doelen formuleren, zijn meer gemotiveerd en persistenter.',
    skillTip: 'Gebruik SMART-criteria licht: Specifiek, Meetbaar, Haalbaar. Drie criteria zijn genoeg voor zijn leeftijd.',
    vermijd: 'Vermijd zijn doelen corrigeren of bijsturen. Zijn doelen zijn van hem.',
    leerdoel: 'Je introduceert zelfsturing via autonome doelformulering en -evaluatie.',
    bron: 'Locke, E.A. & Latham, G.P. (1990). A Theory of Goal Setting and Task Performance.',
  },

  // ─── 13-16 jaar ──────────────────────────────────────────────
  {
    id: 'auto_1316_11',
    title: 'Zijn politieke of maatschappelijke mening',
    skill: 'Autonomie',
    description: 'Vraag je tiener naar zijn mening over een maatschappelijk thema. Luister volledig. Deel jouw mening pas daarna, als hij vraagt. Debatteer niet – verken.',
    duration: '20 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Maatschappelijke opinionvorming is een kernonderdeel van identiteitsontwikkeling bij tieners. Vader die zijn mening hoort zonder direct te corrigeren, bevordert autonome waardeontwikkeling.',
    skillTip: 'Vraag: "Hoe ben jij tot die mening gekomen?" – dat vergroot zijn reflectie zonder zijn mening te beïnvloeden.',
    vermijd: 'Vermijd zijn mening corrigeren naar de jouwe. Zijn eigen maatschappelijk denken staat centraal.',
    leerdoel: 'Je bevordert autonome waardeontwikkeling via respectvolle meningsuitwisseling.',
    bron: 'Marcia, J.E. (1966). Development and validation of ego-identity status.',
  },
  {
    id: 'auto_1316_12',
    title: 'Zijn carrièrevisie verkennen',
    skill: 'Autonomie',
    description: 'Vraag je tiener wat hij later wil doen – niet als verwachting maar als verkenning. Luister volledig. Stel nieuwsgierige vragen. Geen beoordeling van haalbaarheid.',
    duration: '20 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Beroepsidentiteit is een van de centrale identiteitsthema\'s voor tieners. Vader die zonder oordeel luistert en nieuwsgierig is, behoudt een open kanaal voor deze cruciale gesprekken.',
    skillTip: 'Vraag: "Wat trekt je daarin aan?" en "Hoe zou je dag eruitzien?" – verdiep zijn eigen visie.',
    vermijd: 'Vermijd vragen over inkomen, zekerheid of haalbaarheid. Dat zijn jouw zorgen, niet zijn droom.',
    leerdoel: 'Je bevordert autonome beroepsidentiteitsontwikkeling via nieuwsgierige verkenning.',
    bron: 'Arnett, J.J. (2000). Emerging adulthood.',
  },
  {
    id: 'auto_1316_13',
    title: 'Zijn eigen herstelplan na fout',
    skill: 'Autonomie',
    description: 'Na een fout of conflict: vraag je tiener zelf een herstelplan te maken. "Wat ga jij doen om dit te herstellen?" Volg zijn plan, tenzij het onverantwoord is.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Eigenaarschap over herstel vergroot de morele autonomie en de betrokkenheid bij het herstelproces. Herstelplannen die tieners zelf maken zijn effectiever dan oplegde maatregelen.',
    skillTip: 'Vraag: "Wat is jouw plan om dit goed te maken?" en accepteer zijn antwoord als het redelijk is.',
    vermijd: 'Vermijd zijn herstelplan overnemen of "verbeteren". Zijn plan is zijn verantwoordelijkheid.',
    leerdoel: 'Je stimuleert morele autonomie via eigenaarschap over herstel na fouten.',
    bron: 'Kohlberg, L. (1969). Stage and sequence.',
  },
  {
    id: 'auto_1316_14',
    title: 'Zijn eigen lifestyle respecteren',
    skill: 'Autonomie',
    description: 'Accepteer keuzes in zijn lifestyle die jij anders zou doen: muziek, kleding, slaaptijden (binnen redelijke grenzen). Benoem wat je respecteert, ook als je het zelf niet zou kiezen.',
    duration: '5 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Lifestyle-autonomie is een kernonderdeel van identiteitsvorming bij tieners. Vader die kleine lifestyle-keuzes accepteert, behoudt een sterkere invloed op de grotere keuzes.',
    skillTip: 'Zeg actief: "Dat is niet mijn stijl, maar ik respecteer dat het de jouwe is." Dat is verbaal respect voor zijn autonomie.',
    vermijd: 'Vermijd commentaar op kleding, haar, muziek tenzij het een echte veiligheidszorg is.',
    leerdoel: 'Je bevordert identiteitsautonomie door lifestyle-keuzes actief te respecteren.',
    bron: 'Marcia, J.E. (1966). Development and validation of ego-identity status.',
  },
  {
    id: 'auto_1316_15',
    title: 'Zijn perspectief op de toekomst',
    skill: 'Autonomie',
    description: 'Vraag je tiener: "Hoe zie jij jouw leven over 10 jaar?" Luister volledig – geen correcties, geen realiteitschecks. Zijn visie staat centraal.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Toekomstoriëntatie is een beschermende factor bij tieners. Het ontwikkelen van een eigen toekomstvisie vergroot de motivatie en de identiteitssamenhang.',
    skillTip: 'Vraag door met: "Wie zijn er in dat leven?" en "Hoe voel je je dan?" – verdiep zijn visie zonder te sturen.',
    vermijd: 'Vermijd "maar hoe ga je dat dan financieren" of andere praktische afremming. Dit is droomsessie, geen plan.',
    leerdoel: 'Je bevordert autonome toekomstoriëntatie als beschermende identiteitsvaardigheid.',
    bron: 'Arnett, J.J. (2000). Emerging adulthood.',
  },
  {
    id: 'auto_1316_16',
    title: 'Hem laten leren van zijn keuzes',
    skill: 'Autonomie',
    description: 'Als je tiener een keuze maakt die niet uitpakt zoals hij hoopte (geen grote gevaren): laat hem de consequentie voelen. Bied steun, maar los het niet voor hem op.',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Echte consequenties van eigen keuzes zijn de krachtigste leerervaring. Vader die consequenties wegneemt, berooft zijn kind van de groeikans van falen.',
    skillTip: 'Zeg: "Dat is moeilijk. Wat ga jij eraan doen?" Steun de persoon, maar laat het probleem bij hem.',
    vermijd: 'Vermijd het probleem voor hem oplossen als hij er zelf uit kan komen. Hoe moeilijk dat ook is.',
    leerdoel: 'Je leert je tiener door consequenties van zijn eigen keuzes te laten leren als autonomie-versterker.',
    bron: 'Dreikurs, R. & Grey, L. (1968). A New Approach to Discipline: Logical Consequences.',
  },
  {
    id: 'auto_1316_17',
    title: 'Zijn idealen serieus nemen',
    skill: 'Autonomie',
    description: 'Als je tiener sterke idealen heeft (duurzaamheid, rechtvaardigheid, veganisme): neem ze volledig serieus. Vraag hoe hij ze wil leven. Steun hem ook als ze anders zijn dan de jouwe.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Idealen zijn cruciale bouwstenen van de tieneridentiteit. Vader die ze serieus neemt, vergroot de morele autonomie en de integriteit van zijn kind.',
    skillTip: 'Vraag: "Hoe wil jij dit leven in de praktijk?" – dat stimuleert concrete autonomie in plaats van alleen idealen.',
    vermijd: 'Vermijd het reduceren van zijn idealen tot naïviteit. Ze zijn serieus – ook als onuitvoerbaar op dat moment.',
    leerdoel: 'Je bevordert morele autonomie door zijn idealen als serieuze identiteitsuitdrukking te behandelen.',
    bron: 'Kohlberg, L. (1969). Stage and sequence.',
  },
  {
    id: 'auto_1316_18',
    title: 'Hem laten beslissen bij zijn eigen lichaam',
    skill: 'Autonomie',
    description: 'Bij keuzes over zijn lichaam (kapper, oor piercing, kleding, sportactiviteiten): laat hem beslissen. Bied je mening als gevraagd, maar de beslissing is van hem.',
    duration: '5 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Lichaamsautonomie is een fundamenteel recht dat toeneemt in de adolescentie. Vader die dit respecteert, bevordert gezonde grenzen en eigenheid.',
    skillTip: 'Zeg actief: "Jij gaat over je eigen lichaam." Dat is een krachtige boodschap die zijn autonomie bevestigt.',
    vermijd: 'Vermijd mening geven tenzij hij ernaar vraagt. Zijn lichaam is van hem.',
    leerdoel: 'Je bevestigt lichaamsautonomie als fundamenteel recht van je tiener.',
    bron: 'Finkelhor, D. (2009). The prevention of childhood sexual abuse.',
  },
  {
    id: 'auto_1316_19',
    title: 'Zijn eigen therapie- of hulpkeuze',
    skill: 'Autonomie',
    description: 'Als je tiener mentale of emotionele ondersteuning nodig lijkt te hebben: bied opties aan, maar laat hem kiezen of en hoe. Forceer geen hulp – maar bied het actief aan.',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Gedwongen hulp werkt zelden bij tieners. Autonomie in de keuze voor hulp vergroot de motivatie en effectiviteit ervan aanzienlijk. Aanbieden is de juiste rol voor vader.',
    skillTip: 'Zeg: "Er zijn mensen die hiermee helpen. Wil je meer weten? Jij beslist of je gaat." Dat is de juiste framing.',
    vermijd: 'Vermijd hem dwingen te praten, naar therapie te gaan of iets te doen met zijn gevoelens. Aanbieden is voldoende.',
    leerdoel: 'Je respecteert zijn autonomie bij het zoeken van hulp als beschermende betrokkenheid.',
    bron: 'Deci, E.L. & Ryan, R.M. (2000). Self-Determination Theory.',
  },
  {
    id: 'auto_1316_20',
    title: 'Zijn transitie naar volwassenheid bespreken',
    skill: 'Autonomie',
    description: 'Bespreek met je tiener hoe hij de komende jaren steeds meer verantwoordelijkheid krijgt. Vraag: "Wat vind jij spannend aan volwassen worden? Wat is eng?" Verken samen.',
    duration: '20 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'De transitie naar volwassenheid is een centrale ontwikkelingstaak. Bewust voorbereiden op groeiende autonomie vermindert angst en vergroot de bereidheid tot verantwoordelijkheid.',
    skillTip: 'Deel ook jouw herinneringen aan die transitie. Dat normaliseert de gemengde gevoelens.',
    vermijd: 'Vermijd alleen de positieve kant bespreken. Spanningen en angsten zijn ook welkom in dit gesprek.',
    leerdoel: 'Je bereidt je tiener bewust voor op de groeiende autonomie van de volwassenheid.',
    bron: 'Arnett, J.J. (2000). Emerging adulthood: A theory of development.',
  },
];
