import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_5: InteractiveTask[] = [
  // ═══════════════════════════════════════════════════════════════
  // ZELFREGULATIE (50 taken: 5 leeftijdsgroepen × 10 taken)
  // ═══════════════════════════════════════════════════════════════

  // ── Zelfregulatie · 0-2 jaar ────────────────────────────────────
  {
    id: "zelf_02_01",
    title: "Pauze-protocol",
    skill: "Zelfregulatie",
    description: "Als je spanning voelt opbouwen terwijl je baby huilt: zeg hardop 'ik neem een pauze', leg je baby veilig neer en stap 2 minuten de kamer uit.",
    duration: "2 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Een baby die kort alleen ligt is veilig. Een vader die explodeert van stress is dat minder. Het bewust nemen van een pauze doorbreekt de escalatiecyclus voordat die gevaarlijk wordt.",
    skillTip: "Zeg het hardop — ook als er niemand luistert. De stem maakt de intentie concreet en activeert je bewuste brein.",
    vermijd: "Wegstormen zonder iets te zeggen. Dat voelt als abandonment, ook voor een baby.",
    leerdoel: "Je leert dat weglopen soms de meest verantwoorde keuze is als vader.",
    bron: "Gross (2015) - Emotion Regulation: Current Status and Future Prospects",
  },
  {
    id: "zelf_02_02",
    title: "Ademhaling synchroniseren",
    skill: "Zelfregulatie",
    description: "Terwijl je je baby vasthoudt, adem bewust langzaam: 4 tellen in, 6 tellen uit. Doe dit 5 keer achter elkaar.",
    duration: "3 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Verlengde uitademing activeert het parasympathische zenuwstelsel en verlaagt je hartslag. Je baby voelt jouw fysiologische toestand via aanraking en beweging.",
    skillTip: "Leg je hand op je borst terwijl je ademt. Dat maakt de ademhaling voelbaar en houdt je gefocust.",
    vermijd: "Snel in- en uitademen — dat is hyperventileren en maakt je juist gespannener.",
    leerdoel: "Je leert ademhaling te gebruiken als direct regulatiemiddel.",
    bron: "Porges (2011) - The Polyvagal Theory — vagal brake & breathing",
  },
  {
    id: "zelf_02_03",
    title: "Trigger herkennen",
    skill: "Zelfregulatie",
    description: "Schrijf vanavond op: welk moment vandaag zorgde voor de meeste spanning? Was het het huilen, de vermoeidheid, of iets anders?",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Triggerherkenning is de eerste stap van zelfregulatie. Wie zijn triggers kent, kan anticiperen in plaats van reageren. Bewustwording voorkomt automatische patronen.",
    skillTip: "Wees specifiek: niet 'het huilen' maar 'het huilen om 03:00 na 4 uur slaap'. Detail helpt bij herkenning.",
    vermijd: "Jezelf veroordelen om de trigger. Het gaat om herkennen, niet om falen.",
    leerdoel: "Je leert je persoonlijke stresstriggers als vader te identificeren.",
    bron: "Siegel (2010) - Mindsight: The New Science of Personal Transformation",
  },
  {
    id: "zelf_02_04",
    title: "Kalmte modelen bij huilen",
    skill: "Zelfregulatie",
    description: "Als je baby langdurig huilt en je gespannen raakt: fluister in plaats van normaal te praten. Doe dit bewust als tegenhanger van je innerlijke onrust.",
    duration: "3 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Fluisteren dwingt je eigen stemgeluid omlaag, wat je autonome zenuwstelsel kalmeert. Het werkt als een biofeedbackloop: rustige stem → rustiger gevoel.",
    skillTip: "Zeg iets simpels in een fluistertoon: 'Papa is er. Het komt goed.' Herhaal het als een mantra.",
    vermijd: "Je stem verhogen als je baby niet stopt — dat escaleert de situatie voor jullie allebei.",
    leerdoel: "Je leert je stemtoon bewust in te zetten als zelfregulatiemiddel.",
    bron: "Porges (2011) - Polyvagal Theory & prosodic voice",
  },
  {
    id: "zelf_02_05",
    title: "Grond jezelf fysiek",
    skill: "Zelfregulatie",
    description: "Als je spanning voelt: zet bewust beide voeten plat op de grond. Voel het contact. Pers je voetzolen 5 seconden in de vloer. Doe dit terwijl je je baby vasthoudt.",
    duration: "1 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Grounding-technieken richten de aandacht op lichamelijke sensaties in het heden, wat de vlucht-vecht-respons tempert. Het brengt je terug in je lichaam en uit je hoofd.",
    skillTip: "Koppel het aan een vast moment — bijvoorbeeld elke keer als je baby begint te huilen. Zo wordt het automatisch.",
    vermijd: "Proberen te denken over het probleem terwijl je groundet. Het is een lichaamsgerichte techniek.",
    leerdoel: "Je leert een directe lichamelijke techniek om jezelf te kalmeren.",
    bron: "Van der Kolk (2014) - The Body Keeps the Score — grounding techniques",
  },
  {
    id: "zelf_02_06",
    title: "Slaapgebrek-plan maken",
    skill: "Zelfregulatie",
    description: "Maak vandaag een concreet plan voor de komende week: wie doet welke nacht? Hoe zorg jij voor minimaal één aaneengesloten slaapblok van 4 uur?",
    duration: "10 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Slaapgebrek is de grootste aanslag op zelfregulatie. Hoe minder slaap, hoe actiever de amygdala en hoe minder controle de prefrontale cortex heeft. Planning is preventie.",
    skillTip: "Maak het concreet: schrijf het op en deel het met je partner. Vage plannen worden niet uitgevoerd.",
    vermijd: "Denken dat je het 'wel redt'. Slaapgebrek bouw je op en de gevolgen komen altijd op het kind neer.",
    leerdoel: "Je leert zelfregulatie te ondersteunen door proactief te plannen.",
    bron: "Walker (2017) - Why We Sleep — sleep deprivation & emotional regulation",
  },
  {
    id: "zelf_02_07",
    title: "Stop-adem-reageer",
    skill: "Zelfregulatie",
    description: "Oefen vandaag de 3-stap methode: bij élke stressreactie — Stop (beweeg niet), Adem (één diepe ademhaling), Reageer (dan pas). Doe het bewust 3 keer.",
    duration: "2 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "De Stop-Adem-Reageer methode doorbreekt de automatische reactieketen. De 0,5 seconde pauze is genoeg om de prefrontale cortex te activeren voordat de amygdala het overneemt.",
    skillTip: "Drie keer bewust oefenen op een dag verankert de gewoonte sneller dan één keer nadenken over de theorie.",
    vermijd: "Wachten op een 'echt' stressmoment om te oefenen. Oefen ook op kleine irritaties.",
    leerdoel: "Je leert een micro-pauze in te bouwen tussen stimulus en respons.",
    bron: "Siegel & Bryson (2011) - The Whole-Brain Child — pause & respond",
  },
  {
    id: "zelf_02_08",
    title: "Acceptatie van oncontroleerbaarheid",
    skill: "Zelfregulatie",
    description: "Zeg vandaag één keer hardop tegen jezelf: 'Ik kan niet bepalen wanneer mijn baby stopt met huilen. Ik kan alleen bepalen hoe ik erop reageer.'",
    duration: "2 min",
    ageGroups: ["0-2"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Controlebehoefte is een grote stressbron bij nieuwe ouders. Accepteren wat je niet kunt controleren verlaagt frustratie en bevrijdt energie voor wat je wél kunt doen.",
    skillTip: "Schrijf de zin op een post-it en plak hem op een plek die je vaak ziet — de wieg of de koelkast.",
    vermijd: "De zin als passieve overgave zien. Het gaat om actieve acceptatie, niet om opgeven.",
    leerdoel: "Je leert het onderscheid te maken tussen wat in jouw controle ligt en wat niet.",
    bron: "Hayes et al. (2006) - Acceptance and Commitment Therapy — psychological flexibility",
  },
  {
    id: "zelf_02_09",
    title: "Nacht-mantra",
    skill: "Zelfregulatie",
    description: "Kies één korte zin als nacht-mantra voor als je moe en gespannen bent: 'Dit gaat voorbij', 'Mijn baby heeft me nodig', of 'Ik ben genoeg.' Herhaal het vannacht.",
    duration: "2 min",
    ageGroups: ["0-2"],
    difficulty: "basis",
    points: 10,
    psychologie: "Zelfcompassie-zinnen activeren het zorgsysteem van het brein en dempen de stressrespons. Ze werken als cognitieve herkadering in momenten van extreme vermoeidheid.",
    skillTip: "Kies een zin die écht voor jou werkt — niet wat je denkt dat je zou moeten zeggen. Oprechtheid telt.",
    vermijd: "Te lange of ingewikkelde zinnen. In uitputting werken alleen simpele woorden.",
    leerdoel: "Je leert zelfcompassie in te zetten als regulatiestrategie.",
    bron: "Neff (2011) - Self-Compassion: The Proven Power of Being Kind to Yourself",
  },
  {
    id: "zelf_02_10",
    title: "Dagelijkse reset",
    skill: "Zelfregulatie",
    description: "Plan elke dag één moment van 5 minuten voor jezelf: koffie drinken zonder telefoon, 5 minuten buiten staan, of muziek luisteren. Zet het als afspraak in je agenda.",
    duration: "5 min",
    ageGroups: ["0-2"],
    difficulty: "expert",
    points: 20,
    psychologie: "Micro-herstelperiodes vullen de cognitieve reserves aan die zelfregulatie vereisen. Zonder herstel raakt het systeem uitgeput en nemen automatische reacties het over.",
    skillTip: "Bescherm dit moment actief. Communiceer het aan je partner: 'Dit zijn mijn 5 minuten.' Geen schuldgevoel.",
    vermijd: "Het moment gebruiken om op je telefoon te kijken. Echt herstel vereist echte ontkoppeling.",
    leerdoel: "Je leert dagelijkse herstelperiodes in te bouwen als fundament voor zelfregulatie.",
    bron: "Baumeister & Tierney (2011) - Willpower — ego depletion & recovery",
  },

  // ── Zelfregulatie · 3-5 jaar ────────────────────────────────────
  {
    id: "zelf_35_01",
    title: "Fluister als tegengif",
    skill: "Zelfregulatie",
    description: "Als je kind schreeuwt of driftig is en jij merkt dat je stem omhoog gaat: schakel bewust over naar fluisteren. Kijk hoe je kind reageert.",
    duration: "3 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Stemvolume is besmettelijk — zowel omhoog als omlaag. Door te fluisteren dwing je je kind onbewust om stiller te worden om je te kunnen horen. Jouw kalmte is het instrument.",
    skillTip: "Ga ook op ooghoogte zitten. Laag volume + ooghoogte = maximaal kalmerende combinatie.",
    vermijd: "Wachten tot je kind kalm is om zelf te kalmeren. Jij gaat eerst.",
    leerdoel: "Je leert je stemtoon bewust te gebruiken als de-escalatietool.",
    bron: "Siegel & Bryson (2014) - No-Drama Discipline",
  },
  {
    id: "zelf_35_02",
    title: "5-tellen voor je reageert",
    skill: "Zelfregulatie",
    description: "Bij de volgende uitdagende situatie met je kind: tel stil tot 5 voordat je iets zegt of doet. Zeg daarna pas wat je wilt zeggen.",
    duration: "1 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Een pauze van 5 seconden is voldoende om de prefrontale cortex te activeren na een amygdala-activatie. Dit is de neurobiologische basis van 'ik tel tot tien'.",
    skillTip: "Oefen het op kleine irritaties zodat het beschikbaar is bij grote. Maak het een automatisme.",
    vermijd: "De vijf seconden gebruiken om te bedenken wat je straks gaat zeggen. Gewoon tellen.",
    leerdoel: "Je leert een micro-pauze in te bouwen als regulatiestrategie.",
    bron: "Gross (1998) - The emerging field of emotion regulation — response modulation",
  },
  {
    id: "zelf_35_03",
    title: "Eigen driftbui analyseren",
    skill: "Zelfregulatie",
    description: "Schrijf vanavond een moment op van vandaag waarop jij je stem verhief of je geduld verloor. Wat was de aanleiding? Wat zat er onder de boosheid?",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Retrospectieve reflectie helpt om patronen te herkennen en doorbreken. Boosheid heeft bijna altijd een onderliggende emotie: vermoeidheid, machteloosheid, angst.",
    skillTip: "Vraag jezelf: 'Was ik hongerig, moe, gestrest?' Die basisbehoefte is vaak de echte trigger.",
    vermijd: "Jezelf beschuldigen. Dit is een leer-oefening, geen zelfkastijding.",
    leerdoel: "Je leert de laag onder je boosheid te zien.",
    bron: "Gottman (1994) - What Predicts Divorce — secondary emotions",
  },
  {
    id: "zelf_35_04",
    title: "Kalmte-ritueel voor bedtijd",
    skill: "Zelfregulatie",
    description: "Maak van de bedtijdroutine een kalmte-oefening voor jezelf. Adem bij elke stap langzamer: bad, pyjama, verhaaltje. Laat de dag los.",
    duration: "15 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Bedtijdrituelen structureren het zenuwstelsel van zowel kind als ouder. Door bewust aandacht te geven aan kalm worden, herstel jij terwijl je je kind helpt.",
    skillTip: "Zet je telefoon al 30 minuten voor bedtijd op een andere plek. Schermen activeren het brein op het verkeerde moment.",
    vermijd: "Haast maken omdat je wil dat je kind snel slaapt. Haast is besmettelijk.",
    leerdoel: "Je leert bedtijdroutines te gebruiken als wederzijds kalmtemoment.",
    bron: "Mindell et al. (2009) - A nightly bedtime routine — sleep & calming effects",
  },
  {
    id: "zelf_35_05",
    title: "Time-in voor jezelf",
    skill: "Zelfregulatie",
    description: "Als je merkt dat je snel geïrriteerd raakt: maak een time-in voor jezelf. Ga even zitten, sluit je ogen 30 seconden en scan je lichaam. Wat voel je?",
    duration: "2 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Een mini-bodyscan activates interoceptief bewustzijn en pauzeert automatisch gedrag. 30 seconden is genoeg om een ander perspectief te activeren.",
    skillTip: "Je hoeft dit niet perfect te doen. Zelfs een halve bodyscan werkt beter dan geen pauze.",
    vermijd: "Wachten tot je 'echt toe bent' aan een pauze. Dan is het al te laat.",
    leerdoel: "Je leert vroegtijdig signalen van overbelasting te herkennen en erop te reageren.",
    bron: "Kabat-Zinn (1990) - Full Catastrophe Living — mindfulness-based stress reduction",
  },
  {
    id: "zelf_35_06",
    title: "Het verhaal herschrijven",
    skill: "Zelfregulatie",
    description: "Als je kind iets doet dat je irriteert, verander het verhaal in je hoofd. In plaats van 'hij doet het met opzet', probeer: 'hij is moe en kan dit nog niet reguleren.'",
    duration: "2 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Cognitieve herkadering verandert de emotionele lading van een situatie. Het is bewezen een van de meest effectieve emotieregulatiestrategieën.",
    skillTip: "Vraag jezelf: 'Wat is de meest welwillende verklaring voor dit gedrag?' Kies die versie.",
    vermijd: "Het verhaal herschrijven terwijl je nog midden in de boosheid zit. Kader pas her als je iets ruimte hebt.",
    leerdoel: "Je leert cognitieve herkadering toe te passen op opvoedmomenten.",
    bron: "Gross & John (2003) - Individual differences in two emotion regulation processes — cognitive reappraisal",
  },
  {
    id: "zelf_35_07",
    title: "Spanning in je lichaam benoemen",
    skill: "Zelfregulatie",
    description: "Zeg vandaag één keer hardop (of in gedachten): 'Ik merk dat mijn schouders gespannen zijn' of 'Mijn kaak staat strak.' Benoem wat je voelt.",
    duration: "1 min",
    ageGroups: ["3-5"],
    difficulty: "basis",
    points: 10,
    psychologie: "Affect labeling — emoties en lichaamssensaties benoemen — vermindert de activiteit in de amygdala. Zelfs één zin werkt als een mini-regulatie.",
    skillTip: "Doe het in het moment, niet achteraf. 'Ik merk nu...' is krachtiger dan 'ik merkte eerder...'",
    vermijd: "Denken dat je er niets mee hoeft te doen. Benoemen is op zich al genoeg.",
    leerdoel: "Je leert lichaamssignalen van stress direct te benoemen.",
    bron: "Lieberman et al. (2007) - Putting feelings into words — affect labeling",
  },
  {
    id: "zelf_35_08",
    title: "Reactiepatroon doorbreken",
    skill: "Zelfregulatie",
    description: "Kies één terugkerend moment waarop je standaard reageert (bijv. als je kind niet wil eten). Doe het vandaag bewust anders — ook als je niet weet hoe. Elk alternatief telt.",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "expert",
    points: 20,
    psychologie: "Automatische reactiepatronen zijn ingesleten neurologische paden. Ze doorbreken vereist bewuste keuze — het patroon moet worden onderbroken voordat een nieuw kan worden gevormd.",
    skillTip: "Je hoeft het niet perfect te doen. Zelfs een kleine afwijking van het patroon is een overwinning.",
    vermijd: "Te grote veranderingen tegelijk proberen. Kies één specifiek moment en doe dat anders.",
    leerdoel: "Je leert bestaande reactiepatronen bewust te doorbreken.",
    bron: "Siegel (2010) - Mindsight — neuroplasticity & pattern interruption",
  },
  {
    id: "zelf_35_09",
    title: "Boosheid als signaal",
    skill: "Zelfregulatie",
    description: "De volgende keer dat je boos wordt: behandel het als een alarmsignaal in plaats van een probleem. Vraag jezelf: 'Wat heeft mijn brein net gezien als bedreiging?'",
    duration: "3 min",
    ageGroups: ["3-5"],
    difficulty: "expert",
    points: 20,
    psychologie: "Boosheid is altijd een beschermingsreactie. Het brein heeft iets gezien als bedreiging — van jouw waarden, autoriteit of eigenwaarde. Begrijpen wat dat is, ontlaadt de boosheid.",
    skillTip: "Stel de vraag pas als de eerste piek voorbij is. Niet in het heetst van de strijd.",
    vermijd: "Boosheid wegstoppen of ontkennen. Het signaal verdwijnt niet, maar het uiten wordt verdrongen.",
    leerdoel: "Je leert boosheid te lezen als informatief signaal in plaats van als probleem.",
    bron: "Gottman (1994) - Why Marriages Succeed or Fail — anger as signal",
  },
  {
    id: "zelf_35_10",
    title: "Verwachtingen bijstellen",
    skill: "Zelfregulatie",
    description: "Schrijf op: welke verwachtingen had je vandaag van je kind die niet uitkwamen? Zijn die verwachtingen realistisch voor zijn/haar leeftijd?",
    duration: "5 min",
    ageGroups: ["3-5"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Veel frustratie bij ouders komt voort uit onrealistische verwachtingen. Een 4-jarige kan zijn impulsen biologisch gezien nog niet goed controleren. Kennis van ontwikkeling = meer geduld.",
    skillTip: "Zoek één ontwikkelingsfeit op over de leeftijd van je kind. Kennis verandert perspectief.",
    vermijd: "Je verwachtingen volledig loslaten. Het gaat om bijstellen, niet om geen verwachtingen meer te hebben.",
    leerdoel: "Je leert je verwachtingen te koppelen aan ontwikkelingskennis.",
    bron: "Siegel & Bryson (2011) - The Whole-Brain Child — developmental expectations",
  },

  // ── Zelfregulatie · 6-9 jaar ────────────────────────────────────
  {
    id: "zelf_69_01",
    title: "Samen diep ademhalen",
    skill: "Zelfregulatie",
    description: "Introduceer bij je kind de 'box breathing': 4 tellen in, 4 houden, 4 uit, 4 houden. Doe het samen als het gespannen is — of gewoon voor het slapengaan.",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Box breathing activeert het parasympathische zenuwstelsel bij zowel kind als vader. Door het samen te doen model je de strategie en oefen je zelf tegelijk.",
    skillTip: "Teken een vierkant in de lucht terwijl je telt — dat maakt het visueel en helpt kinderen de stappen te onthouden.",
    vermijd: "Het alleen aanbieden op het moment van stress. Oefen het ook als alles rustig is.",
    leerdoel: "Je leert zelfregulatie te modelen én te oefenen tegelijk met je kind.",
    bron: "Jerath et al. (2015) - Self-regulation of breathing as a primary treatment for anxiety",
  },
  {
    id: "zelf_69_02",
    title: "Kalm blijven bij slechte cijfers",
    skill: "Zelfregulatie",
    description: "Je kind heeft een slecht cijfer of slechte beoordeling. Pauzeer 10 seconden voor je reageert. Zeg als eerste: 'Vertel me er eens over.'",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "De eerste reactie van een ouder op falen bepaalt of het kind een groei- of vermijdingsmentaliteit ontwikkelt. Nieuwsgierigheid als eerste reactie opent, oordeel sluit.",
    skillTip: "Verberg je eigen teleurstelling even. Jouw emotie is echt, maar dit moment gaat over je kind.",
    vermijd: "Meteen vragen: 'Heb je wel geleerd?' Dat is een verwijt verpakt als vraag.",
    leerdoel: "Je leert je eigen teleurstelling te reguleren zodat je je kind kunt steunen.",
    bron: "Dweck (2006) - Mindset — parental response to failure & growth mindset",
  },
  {
    id: "zelf_69_03",
    title: "Scherm-trigger aanpakken",
    skill: "Zelfregulatie",
    description: "Als het uitzetten van schermen altijd een conflict geeft: maak vandaag een concreet plan mét je kind. Wanneer gaat het scherm uit? Wie beslist? Hoe gaat de overgang?",
    duration: "10 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Proactief plannen voorkomt reactief reageren. Conflicten rondom schermen komen vaak door onduidelijkheid — structuur vervangt de machtsstrijd.",
    skillTip: "Laat je kind meedenken over de regel. Regels die kinderen zelf hebben helpen maken, worden beter nageleefd.",
    vermijd: "Regels opleggen zonder overleg. Dat schept weerstand en escaleert de volgende keer.",
    leerdoel: "Je leert proactief te plannen om reactief reageren te voorkomen.",
    bron: "Ross Greene (2010) - The Explosive Child — collaborative problem solving",
  },
  {
    id: "zelf_69_04",
    title: "Frustratie hardop benoemen",
    skill: "Zelfregulatie",
    description: "Zeg vandaag één keer eerlijk tegen je kind: 'Ik merk dat ik nu gefrustreerd ben. Ik neem even een moment.' Doe dit als alternatief voor uitbarsten.",
    duration: "2 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Ouders die hun emoties benoemen modelen emotioneel bewustzijn en tonen dat gevoelens beheerst kunnen worden. Kinderen leren hierdoor dat frustratie normaal is en niet gevaarlijk.",
    skillTip: "Gebruik 'ik merk dat ik' in plaats van 'jij maakt me'. De eerste is observatie, de tweede is beschuldiging.",
    vermijd: "De emotie te groot maken of dramatiseren. Kalm benoemen is krachtig genoeg.",
    leerdoel: "Je leert emotioneel zelfbewustzijn te modelen voor je kind.",
    bron: "Gottman (1997) - Meta-Emotion Philosophy — parental emotion coaching",
  },
  {
    id: "zelf_69_05",
    title: "Prikkeldrempel kennen",
    skill: "Zelfregulatie",
    description: "Denk na: in welke omstandigheden heb jij de laagste prikkeldrempel? Na werk? Bij honger? Bij weinig slaap? Maak een top-3 en deel die met je partner.",
    duration: "5 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Kennis van je eigen prikkeldrempel is zelfkennis die actief zelfregulatie ondersteunt. Je kunt preventief ingrijpen als je weet wanneer je kwetsbaar bent.",
    skillTip: "Gebruik het acroniem HALT: ben je Hongerig, Angstig (Angry), Lonely (Eenzaam) of Tired? Dat zijn de gevaarlijkste momenten.",
    vermijd: "De kennis bij jezelf houden. Deel het, zodat je omgeving je kan ondersteunen.",
    leerdoel: "Je leert je eigen prikkeldrempel in kaart te brengen.",
    bron: "Baumeister et al. (1998) - Ego depletion — self-regulatory resource model",
  },
  {
    id: "zelf_69_06",
    title: "Repair na botsing",
    skill: "Zelfregulatie",
    description: "Na een conflict met je kind waarbij jij te ver ging: ga terug en zeg: 'Ik had dat anders moeten doen. Mijn reactie was te groot voor de situatie. Sorry.'",
    duration: "3 min",
    ageGroups: ["6-9"],
    difficulty: "expert",
    points: 20,
    psychologie: "Herstelgedrag van ouders na escalatie is een krachtige les in zelfregulatie. Het toont dat je fouten kunt erkennen en dat relaties veerkrachtig zijn.",
    skillTip: "Houd de excuses concreet: benoem wat je deed en waarom het niet oké was. Vage excuses voelen niet oprecht.",
    vermijd: "De excuses verpakken met 'maar jij ook...'. Dat ondermijnt de erkenning.",
    leerdoel: "Je leert herstel te gebruiken als onderdeel van je zelfregulatiestrategie.",
    bron: "Gottman (1999) - The Marriage Clinic — repair attempts",
  },
  {
    id: "zelf_69_07",
    title: "Kalmte als keuze zien",
    skill: "Zelfregulatie",
    description: "Schrijf op een post-it: 'Kalmte is geen gevoel, het is een keuze.' Plak het op een plek die je ziet als je gespannen bent. Lees het hardop als het nodig is.",
    duration: "2 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "De overtuiging dat emoties je overkomen maakt je passief. De overtuiging dat je een keuze hebt in je reactie — ook als de emotie er al is — is een kernovertuiging van zelfregulatie.",
    skillTip: "Schrijf de zin in je eigen woorden. Wat klinkt voor jou als een echte keuze?",
    vermijd: "Het als een cliché afdoen. Simpele zinnen hebben grote neuropsychologische effecten als je ze gelooft.",
    leerdoel: "Je leert kalmte te zien als actieve keuze in plaats van passieve toestand.",
    bron: "Frankl (1946) - Man's Search for Meaning — response choice between stimulus and response",
  },
  {
    id: "zelf_69_08",
    title: "Beweging als ventiel",
    skill: "Zelfregulatie",
    description: "Als je spanning voelt opbouwen: doe 10 jumping jacks, een snelle wandeling om het blok, of 20 seconden op de plek trappelen. Doe het voordat je je kind opzoekt.",
    duration: "2 min",
    ageGroups: ["6-9"],
    difficulty: "basis",
    points: 10,
    psychologie: "Fysieke beweging verlaagt cortisol en adrenaline. Het geeft het lichaam een uitweg voor de stresshormonen die anders via gedrag naar buiten komen.",
    skillTip: "Combineer het met buiten zijn als dat kan. Natuur en beweging versterken elkaar.",
    vermijd: "Agressieve beweging als boksen of hard slaan. Dat activeert de stressrespons verder.",
    leerdoel: "Je leert fysieke beweging te gebruiken als directe stressregulatie.",
    bron: "Ratey (2008) - Spark: The Revolutionary New Science of Exercise and the Brain",
  },
  {
    id: "zelf_69_09",
    title: "Verwachtingen voor de dag",
    skill: "Zelfregulatie",
    description: "Begin de dag met het schrijven van één realistisch doel als vader: niet 'een perfecte dag' maar 'ik ga drie keer bewust reageren in plaats van reageren.'",
    duration: "3 min",
    ageGroups: ["6-9"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Intentie-setting verhoogt de kans op gewenst gedrag door het te activeren in het werkgeheugen. Kleine, concrete doelen werken beter dan vage grootse idealen.",
    skillTip: "Schrijf het op. Onderzoek toont dat geschreven intenties 2-3x vaker worden uitgevoerd dan alleen gedachte.",
    vermijd: "Te veel doelen tegelijk stellen. Één concreet doel per dag is genoeg.",
    leerdoel: "Je leert dagelijkse intenties te zetten als basis voor zelfregulatie.",
    bron: "Gollwitzer (1999) - Implementation intentions — when, where, how of goal striving",
  },
  {
    id: "zelf_69_10",
    title: "Stress-check om 17:00",
    skill: "Zelfregulatie",
    description: "Stel een dagelijkse reminder in op je telefoon: 17:00 uur. Vraag jezelf dan: 'Op een schaal van 1-10, hoe gespannen ben ik nu?' Als je boven de 6 zit: doe iets om te ontspannen voor je thuis bent.",
    duration: "3 min",
    ageGroups: ["6-9"],
    difficulty: "expert",
    points: 20,
    psychologie: "De overgang van werk naar thuis is een kritisch moment. Hoge stressniveaus bij thuiskomst zijn een van de sterkste voorspellers van negatieve ouder-kind interacties die avond.",
    skillTip: "Rijdt je met de auto? Gebruik de laatste 5 minuten van de rit als bewuste decompressie: geen muziek, geen podcast. Alleen adem.",
    vermijd: "De check-in overslaan als je druk bent. Juist dan is hij het meest nodig.",
    leerdoel: "Je leert je stressniveau proactief te managen voor je je kinderen ziet.",
    bron: "Repetti (1994) - Short-term and long-term processes linking job stressors to father-child interaction",
  },

  // ── Zelfregulatie · 10-12 jaar ──────────────────────────────────
  {
    id: "zelf_1012_01",
    title: "Eigen escalatiepatroon kennen",
    skill: "Zelfregulatie",
    description: "Beschrijf je eigen escalatiepatroon in 3 stappen: wat is het eerste teken (bijv. stem verhogen), het tweede (bijv. sarcasme), het derde (bijv. uitbarsten). Ken je eigen escalatieladder.",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Metacognitieve kennis over eigen emotieregulatiepatronen is een sterk beschermende factor. Wie zijn eigen escalatieladder kent, kan eerder ingrijpen.",
    skillTip: "Vraag je partner of je kind ook te beschrijven wat zij zien als jij escaleert. Dat geeft een buitenperspectief.",
    vermijd: "De kennis alleen theoretisch houden. Schrijf concrete vroege signalen op zodat je ze herkent in het moment.",
    leerdoel: "Je leert je eigen escalatiepatroon te kennen als basis voor vroege interventie.",
    bron: "Siegel (2010) - Mindsight — pattern recognition & self-awareness",
  },
  {
    id: "zelf_1012_02",
    title: "Rustig reageren op puberale uitdaging",
    skill: "Zelfregulatie",
    description: "Als je kind je uitdaagt of tegenspreekt: pauzeer. Zeg: 'Ik hoor wat je zegt. Geef me even.' Loop letterlijk een kamer verder en kom terug als je rustig bent.",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Pre-adolescenten testen grenzen als onderdeel van identiteitsontwikkeling. Een ouder die kalm blijft onder druk, biedt veiligheid én een krachtig model voor emotieregulatie.",
    skillTip: "De zin 'Geef me even' is krachtiger dan 'ik moet even nadenken'. Het is kort, helder en niet-defensief.",
    vermijd: "Je defensief voelen als je kind je tegenspreekt. Het is ontwikkeling, geen aanval.",
    leerdoel: "Je leert kalm te blijven als je kind je uitdaagt.",
    bron: "Steinberg (2001) - We Know Some Things — adolescent challenge & parental regulation",
  },
  {
    id: "zelf_1012_03",
    title: "Zelfcompassie na een slechte dag",
    skill: "Zelfregulatie",
    description: "Na een dag waarop je niet de vader was die je wilde zijn: schrijf drie zinnen op vanuit compassie, niet vanuit oordeel. Wat had je nodig vandaag? Wat was moeilijk?",
    duration: "5 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Zelfkritiek na mislukkingen vergroot schaamte en vermindert de kans op verandering. Zelfcompassie verhoogt juist de motivatie om het morgen beter te doen.",
    skillTip: "Schrijf vanuit de 'vriendelijke vriend'-perspectief: wat zou je zeggen tegen een goede vriend in dezelfde situatie?",
    vermijd: "De compassie gebruiken als excuus: 'het is ook moeilijk dus het maakt niet uit.' Compassie staat naast verantwoordelijkheid.",
    leerdoel: "Je leert zelfcompassie als fundament voor duurzame verbetering.",
    bron: "Neff (2011) - Self-Compassion — self-criticism vs. self-compassion as motivator",
  },
  {
    id: "zelf_1012_04",
    title: "Proactief de week plannen",
    skill: "Zelfregulatie",
    description: "Plan deze week: welke momenten zijn het meest uitdagend voor je (drukke werkdag + huiswerk begeleiding)? Plan daar bewust een buffer of herstelmomenten omheen.",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Proactieve planning is een hogere vorm van zelfregulatie dan reactief omgaan. Door risicomomenten van tevoren te identificeren, kun je resources inzetten voordat de stress piek bereikt.",
    skillTip: "Kijk naar de week en markeer drie 'gevaarlijke' momenten. Bedenk voor elk één concrete buffer-strategie.",
    vermijd: "Plannen zonder te reserveren voor jezelf. Jij bent ook een onderdeel van de planning.",
    leerdoel: "Je leert proactief te plannen rondom stressmomenten.",
    bron: "Gollwitzer & Sheeran (2006) - Implementation intentions & goal achievement",
  },
  {
    id: "zelf_1012_05",
    title: "Machtsstrijd herkennen en stoppen",
    skill: "Zelfregulatie",
    description: "Bij de volgende machtsstrijd met je kind: herken het moment waarop jij je ego erbij haalt. Vraag jezelf: 'Gaat dit om het welzijn van mijn kind of om mijn gelijk?'",
    duration: "3 min",
    ageGroups: ["10-12"],
    difficulty: "expert",
    points: 20,
    psychologie: "Machtsstrijden zijn symmetrische escalaties waarbij de inhoud irrelevant wordt. De vader die als eerste de machtsstrijd herkent en verlaat, wint — ook al voelt dat zo niet.",
    skillTip: "Je kunt de machtsstrijd verlaten door te zeggen: 'We praten hier later over als we allebei rustig zijn.' Dat is geen zwakte.",
    vermijd: "Denken dat toegeven gelijkstaat aan gezagsverlies. Strategisch terugtrekken is leadership.",
    leerdoel: "Je leert machtsstrijden te herkennen en te de-escaleren.",
    bron: "Ross Greene (2010) - The Explosive Child — Plan B & collaborative problem solving",
  },
  {
    id: "zelf_1012_06",
    title: "Mindful moment voor je reageert",
    skill: "Zelfregulatie",
    description: "Kies één dagelijks terugkerend moment van irritatie (bijv. als je kind zijn kamer niet opruimt). Oefen deze week om bij dat moment drie bewuste ademhalingen te nemen voor je reageert.",
    duration: "2 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Mindfulness-gebaseerde interventies verminderen aantoonbaar reactieve agressie bij ouders. De kracht zit in herhaling op specifieke trigger-momenten.",
    skillTip: "Koppel het aan de trigger zelf als cue. Zodra je kind dit specifieke ding doet → drie ademhalingen. Automatisme komt door specificiteit.",
    vermijd: "Te veel momenten tegelijk willen aanpakken. Focus op één trigger tot het automatisch wordt.",
    leerdoel: "Je leert mindful reageren op terugkerende triggers.",
    bron: "Bögels et al. (2010) - Mindful Parenting — parent-focused mindfulness training",
  },
  {
    id: "zelf_1012_07",
    title: "Weekreflectie als vader",
    skill: "Zelfregulatie",
    description: "Neem elke zondag 10 minuten om je week als vader te evalueren. Wat ging goed? Wanneer verloor je je geduld? Wat wil je volgende week anders doen?",
    duration: "10 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Regelmatige reflectie versterkt zelfbewustzijn en voorkomt dat patronen sluipend ingesleten raken. Het is een vorm van cognitieve zelfregulatie op langere termijn.",
    skillTip: "Gebruik dezelfde drie vragen elke week. Consistentie maakt vergelijking over tijd mogelijk.",
    vermijd: "De reflectie overslaan als het een goede week was. Juist dan is er wat te vieren én te leren.",
    leerdoel: "Je leert structurele zelfreflectie te integreren als onderdeel van je vaderschap.",
    bron: "Schön (1983) - The Reflective Practitioner — reflection-in-action",
  },
  {
    id: "zelf_1012_08",
    title: "Positieve zelfgesprekken",
    skill: "Zelfregulatie",
    description: "Vang jezelf de volgende keer dat je een negatieve gedachte over jezelf als vader hebt ('ik ben te streng', 'ik doe het fout'). Vervang die door een eerlijke maar mildere versie.",
    duration: "3 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Negatieve self-talk activeert de stressrespons en vermindert zelfregulatie. Realistisch positieve self-talk verhoogt emotionele veerkracht.",
    skillTip: "De vervanging hoeft niet positief te zijn — alleen eerlijker. Van 'ik ben een slechte vader' naar 'ik had een moeilijk moment' is genoeg.",
    vermijd: "Valse positiviteit: 'ik doe alles perfect.' Dat gelooft je brein niet en werkt dus niet.",
    leerdoel: "Je leert negatieve gedachtenpatronen over je vaderschap bij te sturen.",
    bron: "Beck (1979) - Cognitive Therapy of Depression — cognitive distortions",
  },
  {
    id: "zelf_1012_09",
    title: "Grenzen stellen zonder escaleren",
    skill: "Zelfregulatie",
    description: "Oefen een grens stellen in een rustige toon, ook als je kind doorduwt. Herhaal dezelfde zin rustig drie keer zonder je volume of toon te verhogen.",
    duration: "3 min",
    ageGroups: ["10-12"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Het broken record-principe (rustig herhalen) is effectiever dan escaleren. Je kind test of de grens echt standhoudt — een kalme herhaling bewijst dat.",
    skillTip: "Kies een korte, heldere zin: 'Het scherm gaat nu uit.' Herhaal letterlijk. Geen uitleg, geen discussie.",
    vermijd: "Je toon verhogen bij de tweede of derde herhaling. Dan wint je kind de machtsstrijd al.",
    leerdoel: "Je leert grenzen consistent te houden zonder te escaleren.",
    bron: "Smith (1975) - When I Say No, I Feel Guilty — broken record technique",
  },
  {
    id: "zelf_1012_10",
    title: "Je eigen HALT-moment herkennen",
    skill: "Zelfregulatie",
    description: "Als je geïrriteerd bent: check eerst HALT. Ben je Hongerig? Angstig/boos (Angry)? Lonely/moe? Tired? Identificeer het en los het eerst op voordat je met je kind praat.",
    duration: "3 min",
    ageGroups: ["10-12"],
    difficulty: "basis",
    points: 10,
    psychologie: "Basale fysiologische behoeften (eten, slaap, verbinding) zijn direct gekoppeld aan de regulatiecapaciteit. Als die behoeften niet bevredigd zijn, is zelfregulatie exponentieel moeilijker.",
    skillTip: "Maak een HALT-kaartje voor jezelf in je portemonnee of op je telefoon. Gebruik het als checklist.",
    vermijd: "Denken dat je 'boven' je basale behoeften staat. Niemand is dat.",
    leerdoel: "Je leert basale behoeften te controleren voordat je in interactie gaat.",
    bron: "Baumeister et al. (1998) - Ego depletion — glucose, sleep & self-regulation",
  },

  // ── Zelfregulatie · 13-16 jaar ──────────────────────────────────
  {
    id: "zelf_1316_01",
    title: "Niet reageren op de provocatie",
    skill: "Zelfregulatie",
    description: "Als je tiener iets zegt dat je raakt of beledigt: reageer niet meteen. Zeg alleen: 'Ik hoor je.' Loop weg als dat nodig is. Kom later terug.",
    duration: "2 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Pubers testen de emotionele stabiliteit van ouders. Een ouder die niet reageert op provocatie toont dat de relatie sterker is dan het conflict — en ontneemt de escalatie zijn brandstof.",
    skillTip: "Provocaties zijn een test, geen aanval. De juiste reactie is geen reactie — op het moment zelf.",
    vermijd: "Sarcasme of passief-agressief gedrag als 'reactie-light'. Dat escaleert net zo hard.",
    leerdoel: "Je leert niet te reageren op provocatie als de krachtigste zelfregulatiestrategie.",
    bron: "Steinberg (2005) - Cognitive and affective development in adolescence",
  },
  {
    id: "zelf_1316_02",
    title: "Tiener-stress niet persoonlijk nemen",
    skill: "Zelfregulatie",
    description: "Als je tiener kortaf, chagrijnig of gesloten is: zeg bij jezelf: 'Dit gaat niet over mij.' Geef ruimte en wacht zonder het persoonlijk te nemen.",
    duration: "2 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Tieners externaliseren stress op de meest veilige persoon — hun ouder. Dat is paradoxaal een teken van veilige hechting. Begrijpen hiervan vermindert de stressreactie bij ouders.",
    skillTip: "Vraag jezelf: 'Had ik dit als tiener ook?' Herkenning creëert empathie in plaats van reactie.",
    vermijd: "Zeggen: 'Doe normaal.' Dat invalideert de puberale stress en escaleert het conflict.",
    leerdoel: "Je leert tiener-gedrag te ontkoppelen van je eigen eigenwaarde.",
    bron: "Laursen & Collins (2009) - Parent-Child Relationships During Adolescence",
  },
  {
    id: "zelf_1316_03",
    title: "Kalm blijven bij leugens",
    skill: "Zelfregulatie",
    description: "Als je ontdekt dat je tiener heeft gelogen: pauzeer je reactie. Schrijf op wat je voelt (verraad? angst? boosheid?) voordat je het gesprek aangaat.",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Leugens bij tieners activeren verraadgevoelens die de reactie vergroten. Scheiden van de emotionele reactie en het gesprek zelf verbetert de uitkomst enorm.",
    skillTip: "Vraag jezelf: 'Wil ik straf uitdelen of de relatie bewaken?' Beide zijn geldig, maar je kunt er maar één tegelijk prioriteren.",
    vermijd: "Het gesprek beginnen vanuit verraad en boosheid. Dat maakt je tiener defensief en minder eerlijk.",
    leerdoel: "Je leert je emotionele reactie te scheiden van je ouderlijk handelen.",
    bron: "Darling & Steinberg (1993) - Parenting style as context — authoritative parenting & honesty",
  },
  {
    id: "zelf_1316_04",
    title: "Eigen onmacht erkennen",
    skill: "Zelfregulatie",
    description: "Als je het gevoel hebt dat je geen grip meer hebt op je tiener: schrijf op wat je wél nog kunt doen en wat buiten je controle ligt. Focus alleen op het eerste.",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Controleverlies activeert angst en frustratie die zich uiten in overcontrole of machteloosheid. Door te focussen op de eigen invloedssfeer herstel je gevoel van effectiviteit.",
    skillTip: "De vraag is niet: 'Hoe zorg ik dat mijn tiener dit doet?' maar 'Hoe ben ik de vader die ik wil zijn, ongeacht wat hij/zij doet?'",
    vermijd: "Proberen alles te controleren. Dat drijft tieners juist verder weg.",
    leerdoel: "Je leert je energie te richten op wat binnen jouw controle ligt.",
    bron: "Covey (1989) - The 7 Habits of Highly Effective People — circle of influence",
  },
  {
    id: "zelf_1316_05",
    title: "Stilte als keuze",
    skill: "Zelfregulatie",
    description: "Oefen bewuste stilte in een gesprek met je tiener. Stel een vraag en wacht dan — ook als het oncomfortabel wordt. Tel 10 seconden voor je de stilte vult.",
    duration: "3 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Tieners verwerken langzamer in sociale context dan volwassenen verwachten. Stilte laten bestaan geeft ze ruimte om te antwoorden zonder druk. Ouders die stilte vullen, geven het gesprek nooit de kans.",
    skillTip: "Stilte voelt voor jou langer dan het is. 10 seconden is kort maar krachtig.",
    vermijd: "De stilte invullen met jouw eigen antwoord of een nieuwe vraag. Dat sluit de ruimte af.",
    leerdoel: "Je leert stilte te gebruiken als communicatietool in gesprekken met je tiener.",
    bron: "Nichols (2009) - The Lost Art of Listening — listening & silence",
  },
  {
    id: "zelf_1316_06",
    title: "Afstand nemen na conflict",
    skill: "Zelfregulatie",
    description: "Na een fel conflict met je tiener: ga 20 minuten iets doen dat jou helpt reguleren (wandelen, muziek, sporten) voor je het gesprek hervat.",
    duration: "20 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Na een conflict duurt het gemiddeld 20 minuten voor het stresshormoonpeil terugkeert naar baseline. Gesprekken die eerder worden hervat, hebben meer kans op re-escalatie.",
    skillTip: "Zeg expliciet tegen je tiener: 'Ik ga 20 minuten iets doen. Dan praten we verder.' Dat normaliseert de pauze.",
    vermijd: "De pauze gebruiken om het conflict in je hoofd te herhalen en te versterken. Doe iets fysieks.",
    leerdoel: "Je leert de biologische herstelperiode te respecteren na een conflict.",
    bron: "Gottman (1994) - What Predicts Divorce — flooding & physiological soothing",
  },
  {
    id: "zelf_1316_07",
    title: "Humor als regulatiemiddel",
    skill: "Zelfregulatie",
    description: "Zoek vandaag bewust één moment van lichte humor met je tiener — een grappige meme, een inside joke, iets dat jullie allebei laat lachen. Zonder agenda.",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "basis",
    points: 10,
    psychologie: "Gedeeld lachen verlaagt cortisol en verhoogt oxytocine bij beide partijen. Het herstelt de relatie op een laagdrempelige manier na spanningen.",
    skillTip: "Lach met je tiener, niet om je tiener. Het verschil is groot.",
    vermijd: "Humor gebruiken om een moeilijk gesprek te vermijden. Dit is voor na een spannend moment, niet als vervanging.",
    leerdoel: "Je leert humor bewust in te zetten als verbindings- en regulatiemiddel.",
    bron: "Fredrickson (2001) - The role of positive emotions in positive psychology — broaden-and-build theory",
  },
  {
    id: "zelf_1316_08",
    title: "Je 'waarom' herinneren",
    skill: "Zelfregulatie",
    description: "Op een moeilijk moment met je tiener: herinner jezelf aan waarom je betrokken wilt blijven. Schrijf één zin op die je op moeilijke momenten kunt teruglezen.",
    duration: "3 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Values clarification — verbinding met je diepere waarden — is een effectieve cognitieve regulatiestrategie. Het herschikt prioriteiten in het moment.",
    skillTip: "Maak de zin persoonlijk en concreet: niet 'ik wil een goede vader zijn' maar 'ik wil er zijn als hij me ooit echt nodig heeft.'",
    vermijd: "De zin te vaag te houden zodat hij je in het moment niet raakt.",
    leerdoel: "Je leert je verbinden aan je diepere waarden als regulatiestrategie.",
    bron: "Hayes et al. (2006) - ACT — values clarification as regulation strategy",
  },
  {
    id: "zelf_1316_09",
    title: "Angst onder de boosheid zien",
    skill: "Zelfregulatie",
    description: "Bij je volgende botsing met je tiener: vraag jezelf achteraf — was er ook angst onder de boosheid? Angst voor het kwijtraken van contact? Voor zijn/haar toekomst?",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "expert",
    points: 20,
    psychologie: "Boosheid bij ouders richting tieners heeft bijna altijd een angstlaag. Boosheid is de beschermende laag; angst is de kwetsbare kern. Wie de angst ziet, kan er anders op reageren.",
    skillTip: "Schrijf de angst op. Concreet maken maakt het hanteerbaar: 'Ik ben bang dat hij de verkeerde vrienden kiest.'",
    vermijd: "De angst wegwuiven als onzin. Angst als ouder is normaal en informatief.",
    leerdoel: "Je leert de angstlaag onder je boosheid te herkennen.",
    bron: "Gottman (1994) - Secondary emotions — anger as protection for vulnerable feelings",
  },
  {
    id: "zelf_1316_10",
    title: "De lange termijn vasthouden",
    skill: "Zelfregulatie",
    description: "Als het moeilijk is: schrijf op hoe je hoopt dat je tiener later terugkijkt op deze periode. Welke vader wil je zijn geweest? Gebruik dat als kompas voor je volgende actie.",
    duration: "5 min",
    ageGroups: ["13-16"],
    difficulty: "gevorderd",
    points: 15,
    psychologie: "Future-self continuity — verbinding met je toekomstige zelf — activeert langetermijndenken en remt impulsieve kortetermijnreacties. Het verschuift de focus van nu naar later.",
    skillTip: "Wees concreet: 'Ik wil dat hij weet dat ik er altijd was, ook als het moeilijk was.' Die zin begeleidt je gedrag nu.",
    vermijd: "Alleen aan de korte termijn denken: 'Ik wil nu gehoord worden.' Dat is het ego, niet de vader.",
    leerdoel: "Je leert langetermijnperspectief te gebruiken als regulatiemiddel in moeilijke momenten.",
    bron: "Hershfield (2011) - Future self-continuity — psychological connection to future self",
  },
];
