// Reflectie – 50 interactieve taken (5 leeftijdsgroepen × 10)
import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_9: InteractiveTask[] = [

  // ─── 0-2 jaar ────────────────────────────────────────────────
  {
    id: 'refl_02_01',
    title: 'Wat zag ik vandaag in mijn kind?',
    skill: 'Reflectie',
    description: 'Schrijf of denk na aan het einde van de dag: wat deed je baby of peuter dat je raakte? Beschrijf het zo concreet mogelijk. Wat zegt dit over hem?',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Reflectie na het ouderschap verbetert de kwaliteit van hechtingsrelaties. Vaders die bewust nadenken over hun kind, zijn responsiever in hun dagelijkse interacties.',
    skillTip: 'Schrijf op, ook als het niet perfect is geformuleerd. Het gaat om de gewoonte van reflecteren, niet om de kwaliteit van de tekst.',
    vermijd: 'Vermijd alleen grote mijlpalen opschrijven. Juist de kleine, gewone momenten zijn rijkst.',
    leerdoel: 'Je ontwikkelt de gewoonte van dagelijkse bewuste reflectie op je kind.',
    bron: 'Siegel, D.J. & Hartzell, M. (2003). Parenting from the Inside Out.',
  },
  {
    id: 'refl_02_02',
    title: 'Hoe reageerde ik vandaag?',
    skill: 'Reflectie',
    description: 'Denk terug aan een moment van vandaag waarop je kind huilde, boos was of lastig deed. Hoe reageerde jij? Wat voelde je? Wat deed je goed? Wat zou je anders doen?',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Zelfreflectie na uitdagende oudermoment versterkt het vermogen om in de toekomst bewuster te reageren. Dit doorbreekt automatische patronen.',
    skillTip: 'Geen zelfkritiek – alleen observatie. "Ik merkte dat ik..." is een neutrale startopzet.',
    vermijd: 'Vermijd jezelf veroordelen. Reflectie is geen straf maar een leerproces.',
    leerdoel: 'Je leert jouw reactiepatronen in uitdagende situaties te herkennen.',
    bron: 'Schön, D.A. (1983). The Reflective Practitioner.',
  },
  {
    id: 'refl_02_03',
    title: 'Wat had ik nodig als kind?',
    skill: 'Reflectie',
    description: 'Denk aan jouw eigen kindertijd, rond de leeftijd van je baby. Wat had jij nodig van jouw vader? Wat kreeg je wel? Wat niet? Hoe wil jij dat anders doen?',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Intergenerationeel bewustzijn is de krachtigste voorspeller van positieve hechtingspatronen. Vaders die hun eigen jeugd verwerken, herhalen negatieve patronen minder.',
    skillTip: 'Dit kan emoties oproepen. Dat is normaal. Schrijf ze op of praat erover met iemand die je vertrouwt.',
    vermijd: 'Vermijd het idealiseren of dramatiseren van je eigen jeugd. Probeer eerlijk te zijn.',
    leerdoel: 'Je doorbreekt onbewuste intergenerationele patronen door ze bewust te maken.',
    bron: 'Main, M. & Goldwyn, R. (1984). Adult attachment scoring and classification system.',
  },
  {
    id: 'refl_02_04',
    title: 'Brief aan mijn kind van 18',
    skill: 'Reflectie',
    description: 'Schrijf een korte brief aan jouw kind van 18 jaar oud. Wat wil je dat hij weet over deze periode? Wat hoop je voor hem? Wat wil je hem meegeven?',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Toekomstgericht denken over je kind helpt bij het formuleren van je waarden als vader. Dit geeft richting aan je dagelijkse keuzes in het ouderschap.',
    skillTip: 'Bewaar de brief. Over 18 jaar kun je hem geven. Of gewoon voor jezelf houden.',
    vermijd: 'Vermijd alleen over verwachtingen schrijven. Schrijf ook over wat je nu al ziet in hem.',
    leerdoel: 'Je formuleert jouw diepste wensen en waarden als vader.',
    bron: 'McAdams, D.P. (2001). The psychology of life stories.',
  },
  {
    id: 'refl_02_05',
    title: 'Wat maakt dit vaderschap?',
    skill: 'Reflectie',
    description: 'Neem 5 minuten om te denken: wat maakt het vaderschap voor jou bijzonder? Niet wat je moet doen, maar wat je raakt, verrast of raakt in het vaderschap.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Reflectie op de betekenis van vaderschap vergroot de intrinsieke motivatie. Vaders die bewust zijn van de waarde van hun rol, presteren consistenter beter.',
    skillTip: 'Begin met "Vaderschap is voor mij..." en schrijf 5 minuten door zonder stoppen.',
    vermijd: 'Vermijd clichéantwoorden. Ga voorbij aan de makkelijke. Wat is het écht voor jou?',
    leerdoel: 'Je verdiept je persoonlijke betekenis van vaderschap.',
    bron: 'Deci, E.L. & Ryan, R.M. (2000). Self-Determination Theory.',
  },
  {
    id: 'refl_02_06',
    title: 'Drie dingen die goed gingen',
    skill: 'Reflectie',
    description: 'Schrijf aan het einde van de dag drie dingen op die goed gingen in je vaderschap vandaag. Klein of groot. Wees specifiek.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Positieve reflectie activeert het beloningssysteem en vergroot veerkracht. Vaders die bewust succesmomenten registreren, blijven gemotiveerd ook op moeilijke dagen.',
    skillTip: 'De drie dingen hoeven niet spectaculair te zijn. "Ik bleef rustig toen hij huilde" is meer dan genoeg.',
    vermijd: 'Vermijd het afzwakken van je successen. "Dat is niets bijzonders" – het is wél bijzonder.',
    leerdoel: 'Je traint een positief, realistisch zelfbeeld als vader.',
    bron: 'Seligman, M.E.P. (2011). Flourish: A Visionary New Understanding of Happiness and Well-Being.',
  },
  {
    id: 'refl_02_07',
    title: 'Mijn grootste vrees als vader',
    skill: 'Reflectie',
    description: 'Schrijf op: wat vind jij het allerengste aan het vaderschap? Niet de praktische dingen – maar de diepste angst. Wat zit er achter die angst?',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Onbewuste angsten in het ouderschap beïnvloeden gedrag. Ze bewust maken vermindert hun macht. Dit is het begin van bewust ouderschap.',
    skillTip: 'Schrijf zonder te censureren. Wat er ook opkomt – schrijf het op. Geen beoordelingscriteria.',
    vermijd: 'Vermijd jezelf geruststellen. Laat de angst even bestaan zonder meteen op te lossen.',
    leerdoel: 'Je maakt onbewuste angsten bewust, waardoor ze minder sturend worden.',
    bron: 'Winnicott, D.W. (1960). The theory of the parent-infant relationship.',
  },
  {
    id: 'refl_02_08',
    title: 'Wat leerde ik van mijn kind?',
    skill: 'Reflectie',
    description: 'Vraag jezelf: wat heeft mijn kind mij geleerd de afgelopen week? Over mezelf, over het leven, over aanwezigheid? Schrijf het op.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kinderen zijn krachtige leraren voor ouders. Het bewust erkennen hiervan vergroot wederzijds respect en verdiept de relatie voorbij de zorgrol.',
    skillTip: 'Wees niet bescheiden. Kinderen leren ons diepe dingen. Neem het serieus.',
    vermijd: 'Vermijd alleen schrijven over grappige of schattige momenten. Zoek de echte les.',
    leerdoel: 'Je erkent je kind als leermeester en verdiept daarmee de relatie.',
    bron: 'Siegel, D.J. & Bryson, T.P. (2011). The Whole-Brain Child.',
  },
  {
    id: 'refl_02_09',
    title: 'Mijn vadermodel herzien',
    skill: 'Reflectie',
    description: 'Denk aan de vader die je voor jezelf had als kind. Welke eigenschappen wil je overnemen? Welke eigenschappen wil je juist anders doen? Schrijf beide lijstjes op.',
    duration: '10 min',
    ageGroups: ['0-2'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Het bewust verwerken van het vader-model dat je meekreeg is essentieel voor intergenerationele verandering. Je kiest bewust wat je doorgeeft.',
    skillTip: 'Wees eerlijk in beide lijsten. Jouw vader had ongetwijfeld ook goede kanten – erken die ook.',
    vermijd: 'Vermijd alleen negatieve dingen benoemen. Een evenwichtig beeld is ook eerlijker.',
    leerdoel: 'Je trekt bewust grenzen tussen het verleden en je eigen vaderschap.',
    bron: 'Bowlby, J. (1988). A Secure Base.',
  },
  {
    id: 'refl_02_10',
    title: 'Eén moment vasthouden',
    skill: 'Reflectie',
    description: 'Kies één moment van vandaag met je kind dat je wilt vasthouden. Beschrijf het zo gedetailleerd mogelijk: geur, geluid, gevoel, wat er precies gebeurde.',
    duration: '5 min',
    ageGroups: ['0-2'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Bewust positieve momenten vastleggen in geheugen vergroot het welzijn van ouders. Het traint het brein om waardevolle momenten op te slaan in plaats van te verliezen.',
    skillTip: 'Sluit je ogen en speel het moment terug als een film. Dan beschrijven.',
    vermijd: 'Vermijd een "samenvatting" van de dag. Eén concreet moment, zo gedetailleerd als mogelijk.',
    leerdoel: 'Je leert bewust herinneringen te creëren en te bewaren.',
    bron: 'Kabat-Zinn, J. (1994). Wherever You Go, There You Are.',
  },

  // ─── 3-5 jaar ────────────────────────────────────────────────
  {
    id: 'refl_35_01',
    title: 'Wat liep er vandaag mis?',
    skill: 'Reflectie',
    description: 'Kies één moment van vandaag waar je niet trots op was: een te harde reactie, ongeduld, afgeleid zijn. Schrijf op wat er gebeurde en wat er in jou speelde.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Zelfreflectie op uitdagende momenten is de krachtigste weg naar gedragsverandering. Vaders die reflecteren op mislukte momenten, groeien sneller dan vaders die ze negeren.',
    skillTip: 'Gebruik de "ik merkte dat ik..." formule. Beschrijf gedrag, dan gevoel, dan oorzaak.',
    vermijd: 'Vermijd jezelf wegzetten als "slechte vader". Eén moment is nooit het hele verhaal.',
    leerdoel: 'Je leert eerlijk te kijken naar jouw aandeel in moeilijke momenten.',
    bron: 'Schön, D.A. (1983). The Reflective Practitioner.',
  },
  {
    id: 'refl_35_02',
    title: 'Wat trigger jou in je kind?',
    skill: 'Reflectie',
    description: 'Bedenk welk gedrag van je kind jou het meest triggert. Schrijf op: wat doet het kind? Wat voel jij? Waar komt dat gevoel vandaan in jouzelf?',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Triggers zijn bijna altijd verbonden met onverwerkte ervaringen uit de eigen jeugd. Ze bewust maken is de eerste stap naar het doorbreken van reactieve patronen.',
    skillTip: 'Vraag jezelf: "Wanneer heb ik dit eerder gevoeld – als kind?" Dat is de sleutel.',
    vermijd: 'Vermijd het kind verantwoordelijk maken voor jouw trigger. Die ligt in jou, niet in hem.',
    leerdoel: 'Je herkent jouw persoonlijke triggers en begrijpt hun oorsprong.',
    bron: 'Siegel, D.J. & Hartzell, M. (2003). Parenting from the Inside Out.',
  },
  {
    id: 'refl_35_03',
    title: 'Wie wil ik zijn als vader?',
    skill: 'Reflectie',
    description: 'Schrijf vijf eigenschappen op die je wil belichamen als vader. Denk dan na: in hoeverre leef je die al? Kies één eigenschap om op te focussen deze week.',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Waarden-gebaseerd ouderschap is consistent verbonden met beter welbevinden voor zowel ouder als kind. Bewust waarden formuleren geeft gedrag richting.',
    skillTip: 'Gebruik actieve woorden: niet "geduldig" maar "rustig blijven onder druk". Concreter is beter.',
    vermijd: 'Vermijd onhaalbare standaarden. Vijf reële, eerlijke eigenschappen zijn sterker dan vijf perfecte.',
    leerdoel: 'Je formuleert jouw vaderschapwaarden als kompas voor dagelijkse keuzes.',
    bron: 'Hayes, S.C. et al. (1999). Acceptance and Commitment Therapy.',
  },
  {
    id: 'refl_35_04',
    title: 'Wanneer ben ik echt aanwezig?',
    skill: 'Reflectie',
    description: 'Denk na: wanneer in de dag ben je echt, volledig aanwezig bij je kind? En wanneer ben je er fysiek maar mentaal niet? Wat maakt het verschil?',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Kwantiteit van tijd is minder belangrijk dan kwaliteit van aanwezigheid. Bewustzijn van jouw eigen aanwezigheidspatronen helpt bij het optimaliseren.',
    skillTip: 'Eerlijk zijn is hier de sleutel. Er is geen goed antwoord – alleen jouw waarheid.',
    vermijd: 'Vermijd je vergelijken met een ideale vader. Vergelijk jou met jou gisteren.',
    leerdoel: 'Je herkent jouw aanwezigheidspatronen en kunt er bewust op sturen.',
    bron: 'Kabat-Zinn, J. (1994). Wherever You Go, There You Are.',
  },
  {
    id: 'refl_35_05',
    title: 'Grappig moment herdopen',
    skill: 'Reflectie',
    description: 'Denk terug aan een moment deze week met je kind dat achteraf grappig was maar op dat moment frustrerend. Schrijf op hoe je het nu ziet versus hoe je het toen zag.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Cognitieve reappraisal – het herherlabelen van ervaringen – is een effectieve methode om negatieve emotionele reacties te reguleren en veerkracht te ontwikkelen.',
    skillTip: 'Probeer het door de ogen van een vriendelijke observator te zien. Wat zou die zien?',
    vermijd: 'Vermijd het minimaliseren van de echte frustratie van toen. Die was reëel – en nu kan het grappig zijn.',
    leerdoel: 'Je oefent het herherlabelen van ervaringen als instrument voor emotionele regulatie.',
    bron: 'Gross, J.J. (1998). Antecedent- and response-focused emotion regulation.',
  },
  {
    id: 'refl_35_06',
    title: 'Mijn kind in drie woorden',
    skill: 'Reflectie',
    description: 'Beschrijf je kind in exact drie woorden. Waarom koos je die drie? Wat zeggen ze over hem – en wat zeggen ze over hoe jij naar hem kijkt?',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'De manier waarop je een kind beschrijft, weerspiegelt jouw interne representatie van dat kind. Bewust zijn van die representatie helpt bij responsief ouderschap.',
    skillTip: 'Kies je woorden met zorg. Probeer daarna drie andere woorden te bedenken – zijn er betere?',
    vermijd: 'Vermijd alleen positieve of alleen negatieve woorden. Probeer eerlijk en driedimensionaal te zijn.',
    leerdoel: 'Je vergroot je bewustzijn van hoe je jouw kind ziet en benadert.',
    bron: 'Stern, D. (1985). The Interpersonal World of the Infant.',
  },
  {
    id: 'refl_35_07',
    title: 'Waar schoot ik tekort – en dat is oké',
    skill: 'Reflectie',
    description: 'Schrijf eerlijk op: waar schoot je vandaag tekort als vader? Erken het. Schrijf dan op: wat maakt jou ook een goed vader, ondanks dit tekort?',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Zelfcompassie – eerlijk zijn over tekortkomingen en toch zichzelf waarderen – is een sterkere voorspeller van gedragsverandering dan zelfkritiek.',
    skillTip: 'Sluit af met "Ik doe mijn best" – en meen het. Het is geen excuus maar een feit.',
    vermijd: 'Vermijd de tekortkomingen wegwuiven OF alleen daarin blijven hangen. Beide kanten tellen.',
    leerdoel: 'Je ontwikkelt een zelfcompassievolle blik op je vaderschap.',
    bron: 'Neff, K. (2011). Self-Compassion: The Proven Power of Being Kind to Yourself.',
  },
  {
    id: 'refl_35_08',
    title: 'Wat geeft mij energie als vader?',
    skill: 'Reflectie',
    description: 'Denk na: welke momenten met je kind geven je energie? Welke kosten je energie? Schrijf beide lijstjes. Wat valt je op?',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Bewustzijn van energiebalans helpt vaders burn-out te voorkomen en meer kwaliteitstijd te creëren. Je kunt dan bewust kiezen meer energie-gevende momenten te scheppen.',
    skillTip: 'Wees eerlijk – ook als energievreters iets zijn wat je zou moeten genieten. Eerlijkheid gaat voor sociaal wenselijk.',
    vermijd: 'Vermijd je schamen voor wat jou energie kost. Alle vaders hebben energievreters.',
    leerdoel: 'Je krijgt inzicht in jouw vaderschap-energiebalans en kunt er bewuster mee omgaan.',
    bron: 'Seligman, M.E.P. (2011). Flourish.',
  },
  {
    id: 'refl_35_09',
    title: 'Wat zegt mijn lichaam?',
    skill: 'Reflectie',
    description: 'Denk aan een uitdagend moment van vandaag met je kind. Wat voelde je in je lichaam op dat moment? Spanning, warmte, knoop in maag? Schrijf het op.',
    duration: '5 min',
    ageGroups: ['3-5'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Lichamelijke sensaties zijn vroege signalen van emotie. Ze leren herkennen vergroot emotionele zelfkennis en helpt bij het voorkomen van overreageren.',
    skillTip: 'Gebruik lichaamstaal: "In mijn borst voelde ik...", "Mijn kaken spanden..." etc.',
    vermijd: 'Vermijd alleen denken over de situatie. Richt je specifiek op het lichaam.',
    leerdoel: 'Je leert lichamelijke signalen van emoties herkennen als eerste stap in regulatie.',
    bron: 'Damasio, A. (1994). Descartes\' Error: Emotion, Reason, and the Human Brain.',
  },
  {
    id: 'refl_35_10',
    title: 'Brief aan mijn vorige-week-ik',
    skill: 'Reflectie',
    description: 'Schrijf een korte brief aan jezelf van vorige week. Wat weet jij nu dat je toen niet wist? Wat heb je geleerd? Wat wil je jezelf meegeven?',
    duration: '10 min',
    ageGroups: ['3-5'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Retrospectieve zelfbrieven activeren leerprocessen en continuïteitsgevoel. Ze verankeren groei in een persoonlijk narratief – krachtig voor motivatie.',
    skillTip: 'Schrijf in de "je"-vorm, alsof je echt met iemand praat. Dat maakt het persoonlijker.',
    vermijd: 'Vermijd alleen prestatiegericht schrijven. Schrijf ook over houding, gevoel en inzicht.',
    leerdoel: 'Je verankert je groei als vader in een bewust persoonlijk narratief.',
    bron: 'McAdams, D.P. (2001). The psychology of life stories.',
  },

  // ─── 6-9 jaar ────────────────────────────────────────────────
  {
    id: 'refl_69_01',
    title: 'Wat zag ik in mijn kind dat ik herken?',
    skill: 'Reflectie',
    description: 'Denk terug aan een moment van vandaag of deze week. Wat deed of zei je kind dat jou aan jezelf deed denken? Schrijf op wat je herkende en wat dat in jou deed.',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Herkenning in je kind activeert empathie maar kan ook triggers veroorzaken. Bewust zijn van dit mechanisme vergroot jouw responsiviteit en vermindert projectie.',
    skillTip: 'Maak onderscheid: is de herkenning fijn of ongemakkelijk? Beide zijn informatief.',
    vermijd: 'Vermijd je kind te behandelen alsof hij jou is. Hij is zichzelf – met zijn eigen pad.',
    leerdoel: 'Je herkent projectie en herkenning, en leert onderscheid te maken.',
    bron: 'Siegel, D.J. & Hartzell, M. (2003). Parenting from the Inside Out.',
  },
  {
    id: 'refl_69_02',
    title: 'Zijn dag door zijn ogen zien',
    skill: 'Reflectie',
    description: 'Stel je voor dat jij je kind bent, op deze leeftijd. Hoe was zijn dag vandaag vanuit zijn perspectief? Wat ervoer hij? Wat was moeilijk? Wat was fijn?',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Perspectief nemen (theory of mind) is de kern van empathie. Bewust oefenen met het innemen van het perspectief van je kind vergroot je responsiviteit aanzienlijk.',
    skillTip: 'Schrijf in de ik-vorm, alsof jij het kind bent. Dat verdiept de oefening.',
    vermijd: 'Vermijd aannames als feiten behandelen. Het is een oefening – geen diagnose van zijn dag.',
    leerdoel: 'Je oefent bewust perspectief nemen als empathiespier.',
    bron: 'Premack, D. & Woodruff, G. (1978). Does the chimpanzee have a theory of mind?',
  },
  {
    id: 'refl_69_03',
    title: 'Mijn toon vandaag',
    skill: 'Reflectie',
    description: 'Denk terug aan hoe jij vandaag communiceerde met je kind. Wat was de toon? Geduldig? Haastig? Geërgerd? Warm? Schrijf eerlijk op wat je hoorde in jezelf.',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Toon van stem heeft meer impact op kinderen dan de inhoud van woorden. Bewust worden van jouw habituele toon is een krachtige stap naar beter communiceren.',
    skillTip: 'Probeer je stem letterlijk voor te stellen. Was het de stem die jij als kind had gewild?',
    vermijd: 'Vermijd defensief zijn. Dit is zelfonderzoek, geen zelfveroordeling.',
    leerdoel: 'Je vergroot bewustzijn van jouw communicatietoon als regelaar van de relatie.',
    bron: 'Mehrabian, A. (1971). Silent Messages.',
  },
  {
    id: 'refl_69_04',
    title: 'Wanneer ben ik trots op mezelf?',
    skill: 'Reflectie',
    description: 'Denk terug aan een moment de afgelopen maand waarop je trots was op jezelf als vader. Niet op je kind – op jézelf. Schrijf het op. Wat maakte het bijzonder?',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Bewust positieve zelfbeoordeling (self-pride) versterkt zelfeffectiviteit als ouder. Vaders die hun eigen groei herkennen, blijven investeren in hun vaderschap.',
    skillTip: 'Kies een eerlijk moment – niet het grootste succesverhaal maar een echt moment.',
    vermijd: 'Vermijd kiezen voor het moment je kind trots maakte. Jouw moment als vader staat centraal.',
    leerdoel: 'Je versterkt je zelfeffectiviteitsgevoel als vader.',
    bron: 'Bandura, A. (1977). Self-efficacy: Toward a unifying theory of behavioral change.',
  },
  {
    id: 'refl_69_05',
    title: 'Wat ik niet weet over mijn kind',
    skill: 'Reflectie',
    description: 'Schrijf vijf dingen op die je niet weet over je kind: wat denkt hij als hij alleen is? Wat zijn zijn angsten? Wat hoopt hij? Denk na over hoe je dat te weten kunt komen.',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Bewust worden van hiaten in je kennis van je kind vergroot de bereidheid om te luisteren en te vragen. Nieuwsgierigheid is de motor van verbinding.',
    skillTip: 'Wees eerlijk – wat weet je echt niet? Soms denken we meer te weten dan we doen.',
    vermijd: 'Vermijd het aannemen dat je jouw kind volledig kent. Kinderen veranderen snel.',
    leerdoel: 'Je vergroot jouw nieuwsgierigheid naar je kind als individu.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'refl_69_06',
    title: 'Hoe hanteer ik conflicten?',
    skill: 'Reflectie',
    description: 'Denk aan de laatste keer dat je een conflict had met je kind. Hoe loste je het op? Wie gaf toe, waarom? Wat zou een betere manier geweest zijn?',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Conflicthanteringsstijl van ouders is een sterke voorspeller van de sociale vaardigheidsontwikkeling van kinderen. Bewuste reflectie leidt tot bewuster kiezen.',
    skillTip: 'Gebruik de lens van: wie had gelijk, en wie had wat nodig? Beide vragen zijn relevant.',
    vermijd: 'Vermijd alleen kijken naar wie fout was. Kijk naar wat elk nodig had.',
    leerdoel: 'Je vergroot je bewustzijn van jouw conflictpatroon en zijn alternatieven.',
    bron: 'Thomas, K.W. & Kilmann, R.H. (1974). Thomas-Kilmann Conflict Mode Instrument.',
  },
  {
    id: 'refl_69_07',
    title: 'Mijn rol buiten het gezin',
    skill: 'Reflectie',
    description: 'Denk na: hoe beïnvloedt jouw leven buiten het gezin (werk, vrienden, stress) jouw vaderschap? Wat neem je mee naar huis? Wat kun je daar aan doen?',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Spillover – de overdracht van stress of emotie van werk naar gezin – is één van de sterkst gedocumenteerde vaderschap-uitdagingen. Bewustwording is de eerste stap.',
    skillTip: 'Denk aan een overgangsritueel: een moment tussen werk en thuis. Wandeling, muziek, 5 ademhalingen.',
    vermijd: 'Vermijd je buitenleven als excuus gebruiken. Het is context, geen verklaring.',
    leerdoel: 'Je herkent spillover-effecten en ontwikkelt een overgangsritueel.',
    bron: 'Repetti, R.L. (1994). Short-term and long-term processes linking job stressors to father-child interaction.',
  },
  {
    id: 'refl_69_08',
    title: 'Wat herinner ik van deze maand?',
    skill: 'Reflectie',
    description: 'Denk terug aan de afgelopen vier weken. Wat zijn de momenten met je kind die je bijbleven? Schrijf er drie op. Wat maakt dat ze in je geheugen zaten?',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'Geheugen is selectief en emotioneel gekleurd. Wat we onthouden, vertelt ons iets over wat ons echt raakt. Dit is waardevolle zelfkennis.',
    skillTip: 'Selecteer eerlijk – ook als het pijnlijke of beschamende momenten zijn. Die zijn het meest informatief.',
    vermijd: 'Vermijd alleen de leuke momenten opschrijven. Het gehele spectrum is informatief.',
    leerdoel: 'Je krijgt inzicht in wat jou écht raakt in het vaderschap.',
    bron: 'Conway, M.A. & Pleydell-Pearce, C.W. (2000). The construction of autobiographical memories in the self-memory system.',
  },
  {
    id: 'refl_69_09',
    title: 'Wat verander ik komende week?',
    skill: 'Reflectie',
    description: 'Kies na reflectie één concreet gedrag dat je aankomende week wil veranderen als vader. Schrijf het zo specifiek mogelijk op: wanneer, wat, hoe.',
    duration: '5 min',
    ageGroups: ['6-9'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Implementatie-intenties – concrete "als-dan" plannen – verdrievoudigen de kans op gedragsverandering ten opzichte van vage intenties.',
    skillTip: 'Formuleer als: "Als ik [situatie], dan doe ik [actie]." Concreet en specifiek.',
    vermijd: 'Vermijd te veel veranderingen tegelijk kiezen. Één focus werkt veel beter dan vijf.',
    leerdoel: 'Je zet reflectie om in concrete actie via implementatie-intenties.',
    bron: 'Gollwitzer, P.M. (1999). Implementation intentions: Strong effects of simple plans.',
  },
  {
    id: 'refl_69_10',
    title: 'Mijn grootste groeipunt',
    skill: 'Reflectie',
    description: 'Vraag jezelf eerlijk: wat is jouw grootste groeipunt als vader dit moment? Wat maakt dit zo moeilijk? Wat heb je nodig om hierin te groeien?',
    duration: '10 min',
    ageGroups: ['6-9'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Bewust benoemen van groeipunten (zonder zelfkritiek) is de krachtigste motor voor ontwikkeling. Het schept richting en vermindert het gevoel van willekeur.',
    skillTip: 'Maak het zo specifiek mogelijk. "Geduld" is vaag. "Rustig blijven als hij voor de derde keer vraagt" is concreet.',
    vermijd: 'Vermijd jezelf wegzetten als incompetent. Een groeipunt is bewijs van zelfinzicht – niet van falen.',
    leerdoel: 'Je identificeert jouw meest urgente groeipunt als kader voor ontwikkeling.',
    bron: 'Dweck, C. (2006). Mindset: The New Psychology of Success.',
  },

  // ─── 10-12 jaar ──────────────────────────────────────────────
  {
    id: 'refl_1012_01',
    title: 'Mijn vaderschap in perspectief',
    skill: 'Reflectie',
    description: 'Denk na: als je terugkijkt op de afgelopen 5 jaar vaderschap – wat ben je het meest trots op? Wat verbaast je over jezelf? Wat heeft je veranderd?',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Longitudinale zelfbeoordeling vergroot het gevoel van groei en continuïteit. Dit versterkt de identiteit als vader en de motivatie om te blijven investeren.',
    skillTip: 'Wees concreet – vermijd abstracte antwoorden. Denk aan specifieke momenten.',
    vermijd: 'Vermijd alleen negatief terugkijken. Erken ook groei en positieve verandering.',
    leerdoel: 'Je reflecteert op jouw vaderschapsreis vanuit een langetermijnperspectief.',
    bron: 'McAdams, D.P. (2001). The psychology of life stories.',
  },
  {
    id: 'refl_1012_02',
    title: 'Hoe ziet mijn kind mij?',
    skill: 'Reflectie',
    description: 'Stel je voor dat jouw kind van 10-12 zijn beste vriend beschrijft hoe zijn vader is. Wat zou hij zeggen? Schrijf het op – eerlijk, niet ideaal.',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Het innemen van het perspectief van je kind over jou is een krachtige spiegeling. Dit activeert empathie en eerlijke zelfbeoordeling tegelijk.',
    skillTip: 'Probeer echt eerlijk te zijn, niet te positief of negatief. Wat zou hij écht zeggen?',
    vermijd: 'Vermijd het ideaalplaatje schetsen. Die helpt je niet. De eerlijke versie wél.',
    leerdoel: 'Je vergroot inzicht in hoe je overkomt op je kind door zijn perspectief in te nemen.',
    bron: 'Hattie, J. (2009). Visible Learning: A Synthesis of Over 800 Meta-Analyses Relating to Achievement.',
  },
  {
    id: 'refl_1012_03',
    title: 'Mijn reactie op zijn puberbegin',
    skill: 'Reflectie',
    description: 'Schrijf op: hoe reageer jij op de eerste tekenen van puberteit bij je kind (terugtrekken, moodiness, weigeren)? Wat roept dat in jou op? Wat is jouw patroon?',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'De overgang naar de puberteit vraagt ook een aanpassing van vaders. Bewust zijn van jouw reacties op verandering helpt bij het handhaven van verbinding.',
    skillTip: 'Schrijf over je gevoel, niet alleen je gedrag. Wat doet het terugtrekken van je kind met jou?',
    vermijd: 'Vermijd het normaliseren zonder te voelen. "Dat is gewoon puberteit" is een verdediging, geen reflectie.',
    leerdoel: 'Je erkent je eigen reacties op de veranderende behoefte van je kind.',
    bron: 'Steinberg, L. (2011). Adolescence.',
  },
  {
    id: 'refl_1012_04',
    title: 'Wat wil ik hem meegeven?',
    skill: 'Reflectie',
    description: 'Stel je voor dat je maar vijf lessen mee kunt geven aan je kind voor de rest van zijn leven. Welke vijf zijn het? Waarom juist deze?',
    duration: '15 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Het formuleren van kernwaarden voor je kind helpt bij het bepalen van prioriteiten in je dagelijks vaderschap. Het geeft richting aan keuzes en gesprekken.',
    skillTip: 'Kies waarden, niet feiten. Niet "ga naar de universiteit" maar "geloof in jezelf ook als je faalt."',
    vermijd: 'Vermijd prestatie-gerichte lessen. De diepste lessen zijn over karakter en zijn.',
    leerdoel: 'Je formuleert jouw kernvaderschapswaarden als leidraad voor zijn opvoeding.',
    bron: 'Hayes, S.C. et al. (1999). Acceptance and Commitment Therapy.',
  },
  {
    id: 'refl_1012_05',
    title: 'Wat deed mijn vader goed?',
    skill: 'Reflectie',
    description: 'Schrijf drie dingen op die jouw vader goed deed. Niet clichés – concrete momenten. Welk effect hadden die op jou? Doe je dat nu ook bij je eigen kind?',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Bewust erkennen wat goed was in je opvoeding vergroot de kans op overdracht van positieve patronen. Het gaat niet alleen om doorbreken – ook om bewust doorgeven.',
    skillTip: 'Wees eerlijk: ook als je vader moeilijk was, had hij waarschijnlijk dingen die goed waren.',
    vermijd: 'Vermijd het idealiseren van je vader. Concrete, eerlijke momenten zijn waardevoller dan mythes.',
    leerdoel: 'Je identificeert positieve patronen uit jouw eigen opvoeding die je bewust wil doorgeven.',
    bron: 'Bowlby, J. (1988). A Secure Base.',
  },
  {
    id: 'refl_1012_06',
    title: 'De "goed genoeg" vader',
    skill: 'Reflectie',
    description: 'Het concept van "goed genoeg ouderschap" stelt dat perfectie schadelijk is en dat fouten maken normaal is. Denk na: ben jij een "goed genoeg" vader? Wat maakt dat zo?',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Winnicotts "good enough parent" concept toont dat kinderen schade ondervinden van perfecte ouders (geen ruimte voor eigen ontwikkeling) én van onvoldoende ouders. Het midden is het doel.',
    skillTip: 'Goed genoeg betekent niet middelmatig – het betekent reëel, herstelbaar, liefdevol.',
    vermijd: 'Vermijd "goed genoeg" als excuus voor onvoldoende inzet. Het is geen vrijbrief.',
    leerdoel: 'Je omarmt het concept van reëel, imperfect maar liefdevol vaderschap.',
    bron: 'Winnicott, D.W. (1953). Transitional objects and transitional phenomena.',
  },
  {
    id: 'refl_1012_07',
    title: 'Hoe gebruik ik mijn vrije tijd?',
    skill: 'Reflectie',
    description: 'Denk aan de afgelopen week: hoe gebruikte je jouw persoonlijke vrije tijd? Laadde je op? Besteedde je het aan verbinding met je kind? Wat zou je willen veranderen?',
    duration: '5 min',
    ageGroups: ['10-12'],
    difficulty: 'basis',
    points: 10,
    psychologie: 'De kwaliteit van vaderschap hangt deels af van de energiereserves van de vader. Bewust zijn van vrije-tijdspatronen helpt bij duurzame investering in het vaderschap.',
    skillTip: 'Wees eerlijk. Scrollen is anders dan opladen. Wat deed je echt?',
    vermijd: 'Vermijd jezelf veroordelen. Dit is een informatievraag, geen schuldvraag.',
    leerdoel: 'Je krijgt inzicht in je energiebeheer als vader en hoe dat je vaderschap beïnvloedt.',
    bron: 'Ryan, R.M. & Deci, E.L. (2001). On happiness and human potentials.',
  },
  {
    id: 'refl_1012_08',
    title: 'Wat wil ik echt voor hem?',
    skill: 'Reflectie',
    description: 'Stel jezelf de vraag: diep van binnen, wat wil jij echt voor je kind – niet wat de maatschappij verwacht, niet wat jij had gewild – maar wat hij nodig heeft om gelukkig te zijn?',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Onderscheid maken tussen jouw projectie en zijn werkelijke behoeften is een cruciaal onderdeel van bewust ouderschap. Kinderen voelen wanneer ouders voor hen kiezen in plaats van voor zichzelf.',
    skillTip: 'Begin met: "Als ik helemaal eerlijk ben, wil ik voor hem..." en schrijf door zonder censuur.',
    vermijd: 'Vermijd maatschappelijk gewenste antwoorden. Ga naar wat je echt voelt.',
    leerdoel: 'Je trekt een heldere grens tussen jouw behoeften en de behoeften van je kind.',
    bron: 'Deci, E.L. & Ryan, R.M. (2000). Self-Determination Theory.',
  },
  {
    id: 'refl_1012_09',
    title: 'Een gesprek dat ik had moeten voeren',
    skill: 'Reflectie',
    description: 'Denk aan een gesprek met je kind dat je had moeten voeren maar niet deed – uit angst, ongemak, of tijdgebrek. Schrijf op waarom je het uitstelde. Wat zou er nodig zijn om het te starten?',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Vermijdingsgedrag in communicatie is een van de meest voorkomende vaderschap-uitdagingen. Bewust worden van de reden van vermijding is de eerste stap naar actie.',
    skillTip: 'Schrijf ook op: wat zou het mij kosten als ik dit gesprek voerde? En wat kost het me als ik het niet voer?',
    vermijd: 'Vermijd jezelf excuseren of het gesprek minimaliseren. Als het je aanraakt, is het belangrijk.',
    leerdoel: 'Je herkent vermijdingspatronen in je communicatie en verlaagt de drempel om ze te doorbreken.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'refl_1012_10',
    title: 'Wat wil ik dat hij onthoudt?',
    skill: 'Reflectie',
    description: 'Stel je voor: over 20 jaar vertelt jouw kind aan zijn eigen kind over zijn vader. Wat wil jij dat hij zegt? Schrijf het op. Leef je al op die manier?',
    duration: '10 min',
    ageGroups: ['10-12'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Toekomstgerichte reflectie (anticipatory reflection) activeert waarden en geeft richting aan huidig gedrag. Een krachtige methode voor betekenisvol vaderschap.',
    skillTip: 'Wees concreet in zijn woorden. Stel je de zin letterlijk voor die hij zou zeggen.',
    vermijd: 'Vermijd de ideale versie. Schrijf de eerlijke versie die je wil – en die je echt wil waarmaken.',
    leerdoel: 'Je verankert je vaderschapsdoel in een toekomstnarratie.',
    bron: 'McAdams, D.P. (2001). The psychology of life stories.',
  },

  // ─── 13-16 jaar ──────────────────────────────────────────────
  {
    id: 'refl_1316_01',
    title: 'Laat ik hem gaan?',
    skill: 'Reflectie',
    description: 'Denk eerlijk na: hoe makkelijk vind je het om jouw tiener meer vrijheid te geven? Wat maakt loslaten moeilijk voor jou? Wat is jouw grootste angst daarin?',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Loslaten is één van de moeilijkste taken voor ouders van tieners. Bewust worden van de angst achter controle helpt bij het maken van bewustere keuzes.',
    skillTip: 'Onderscheid: bescherm ik hem – of bescherm ik mijzelf? Beide kunnen waar zijn tegelijk.',
    vermijd: 'Vermijd je angst rationaliseren als zorg. Kijk eerlijk naar de ware bron.',
    leerdoel: 'Je herkent de spanning tussen beschermen en loslaten en maakt bewuster keuzes.',
    bron: 'Bowlby, J. (1988). A Secure Base.',
  },
  {
    id: 'refl_1316_02',
    title: 'Wanneer schreeuwde ik – en waarom?',
    skill: 'Reflectie',
    description: 'Denk aan de laatste keer dat je jouw stem verhief of scherp reageerde op je tiener. Wat ging eraan vooraf in jou? Wat had je nodig? Wat was de diepere oorzaak?',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Woede-uitbarstingen zijn zelden over het oppervlakkige probleem. Achter schreeuwen zit vaak eigen stress, machteloosheid, of onverwerkte emotie. Bewustzijn is de eerste stap.',
    skillTip: 'Werk achteruit: gedrag → gevoel → gedachte → onderliggende behoefte. Elke stap geeft informatie.',
    vermijd: 'Vermijd jezelf alleen maar veroordelen. Zoek begrip – dat helpt meer dan schuld.',
    leerdoel: 'Je begrijpt de ketens die leiden tot jouw scherpste reacties.',
    bron: 'Siegel, D.J. & Hartzell, M. (2003). Parenting from the Inside Out.',
  },
  {
    id: 'refl_1316_03',
    title: 'Welke vader ben ik in crisis?',
    skill: 'Reflectie',
    description: 'Denk aan de laatste echte stressvolle periode (ziekte, ruzie, drukte). Wie was jij als vader in die periode? Wat zegt dat over jouw baseline als vader?',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Gedrag onder stress onthult meer over iemands werkelijke patronen dan gedrag in normale omstandigheden. Dit inzicht helpt bij het versterken van kwetsbare punten.',
    skillTip: 'Kijk zonder oordeel. Crisis-gedrag is begrijpelijk – maar ook informatief.',
    vermijd: 'Vermijd de situatie als excuus gebruiken. Zoek wat je kunt leren, niet wat je kan verklaren.',
    leerdoel: 'Je herkent jouw stress-vaderschap en vindt aanknopingspunten voor versterking.',
    bron: 'Porges, S.W. (2011). The Polyvagal Theory.',
  },
  {
    id: 'refl_1316_04',
    title: 'Wat heb ik nodig om beter te zijn?',
    skill: 'Reflectie',
    description: 'Eerlijk en concreet: wat heb jij nodig om een betere vader te zijn? Meer slaap? Ondersteuning? Minder werk? Meer verbinding? Schrijf het op en bespreek het met iemand.',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Vaderschap is niet duurzaam zonder zelfzorg. Vaders die hun eigen behoeften kennen en communiceren, zijn consistent betere ouders dan vaders die zichzelf wegcijferen.',
    skillTip: 'Gebruik de formule: "Om een goede vader te zijn, heb ik nodig..." en schrijf vijf dingen op.',
    vermijd: 'Vermijd alleen anderen de schuld geven voor ontbrekende behoeften. Zoek ook eigen actie.',
    leerdoel: 'Je erkent jouw behoeften als vader en neemt verantwoordelijkheid voor het invullen ervan.',
    bron: 'Maslow, A. (1943). A Theory of Human Motivation.',
  },
  {
    id: 'refl_1316_05',
    title: 'Wat verwacht ik van hem?',
    skill: 'Reflectie',
    description: 'Schrijf eerlijk op: welke verwachtingen heb je van je tiener op dit moment? Zijn die eerlijk en reëel? Welke verwachting zit er achter jouw frustratie als hij die niet waarmaakt?',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Onrealistische of onuitgesproken verwachtingen zijn een van de grootste bronnen van conflict in vader-tienerrelaties. Bewust worden hiervan ontlast de relatie.',
    skillTip: 'Vraag jezelf: "Is dit mijn verwachting of de verwachting van de maatschappij?" Dat maakt het helder.',
    vermijd: 'Vermijd je verwachtingen als objectief omschrijven. Ze zijn altijd subjectief.',
    leerdoel: 'Je maakt jouw verwachtingen bewust en toetst of ze eerlijk en reëel zijn.',
    bron: 'Gottman, J. (1997). Raising an Emotionally Intelligent Child.',
  },
  {
    id: 'refl_1316_06',
    title: 'Wie ben ik buiten het vaderschap?',
    skill: 'Reflectie',
    description: 'Denk na: wie ben jij als persoon, buiten je rol als vader? Wat geeft jou zin en energie? Hoe zorgt jij voor jouw eigen groei als mens?',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Vaders die een rijke identiteit hebben buiten het ouderschap, zijn consistenter aanwezig en minder afhankelijk van het gedrag van hun kind voor hun eigenwaarde.',
    skillTip: 'Schrijf op wie je was vóór je vader werd. Welke delen van die persoon zijn er nog?',
    vermijd: 'Vermijd het vaderschap opofferen aan je eigen identiteit – maar ook omgekeerd.',
    leerdoel: 'Je herwint zicht op jouw volle identiteit als mens en vader.',
    bron: 'Ryan, R.M. & Deci, E.L. (2001). On happiness and human potentials.',
  },
  {
    id: 'refl_1316_07',
    title: 'Wat zou ik anders doen?',
    skill: 'Reflectie',
    description: 'Als je een jaar terug kon gaan in jouw vaderschap: wat zou je anders aanpakken? Niet uit schuldgevoel – maar als leerles voor nu.',
    duration: '10 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Counterfactual thinking – nadenken over alternatieven – activeert leerprocessen en vergroot toekomstige flexibiliteit. Constructief gehanteerd is dit een krachtig groei-instrument.',
    skillTip: 'Koppel je antwoord aan de toekomst: "Dat betekent dat ik nu..." Zo maak je het actief.',
    vermijd: 'Vermijd langdurig in het verleden blijven hangen. De les is voor nu.',
    leerdoel: 'Je zet historische inzichten om in toekomstige verbeteringen.',
    bron: 'Roese, N.J. (1997). Counterfactual thinking. Psychological Bulletin.',
  },
  {
    id: 'refl_1316_08',
    title: 'Welke waarden leven we echt?',
    skill: 'Reflectie',
    description: 'Schrijf de vijf kernwaarden op die jullie gezin zou moeten uitstralen. Schrijf daarna eerlijk op welke waarden jullie echt uitstralen in gedrag. Wat is het verschil?',
    duration: '15 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Congruentie tussen beleden waarden en zichtbaar gedrag is cruciaal voor geloofwaardigheid bij tieners. Ze zien het verschil – altijd.',
    skillTip: 'Vraag jezelf: "Als een camera ons gezin een week filmde, welke waarden zou die zien?"',
    vermijd: 'Vermijd alleen de "goede" waarden opschrijven. Kijk naar wat er werkelijk leeft.',
    leerdoel: 'Je identificeert de kloof tussen jouw beleden en geleefde waarden.',
    bron: 'Covey, S.R. (1989). The 7 Habits of Highly Effective People.',
  },
  {
    id: 'refl_1316_09',
    title: 'Brief aan hem als hij 30 is',
    skill: 'Reflectie',
    description: 'Schrijf een brief aan jouw kind als hij 30 is. Wat wil je dat hij weet over deze periode in zijn leven? Over jou? Over wat jij in hem zag? Over wat je hoopt voor hem?',
    duration: '20 min',
    ageGroups: ['13-16'],
    difficulty: 'expert',
    points: 20,
    psychologie: 'Brieven aan toekomstige versies van je kind activeren langetermijn-empathie en benoemen wat je echt waardevol vindt in de relatie. Diep reflectief en verbindend.',
    skillTip: 'Bewaar de brief en geef hem echt op zijn 30e verjaardag – of zijn afstuderen.',
    vermijd: 'Vermijd advies geven. Schrijf over liefde, inzicht en hoop – niet instructies.',
    leerdoel: 'Je verankert jouw diepste vaderschapsintenties in een blijvend document.',
    bron: 'McAdams, D.P. (2001). The psychology of life stories.',
  },
  {
    id: 'refl_1316_10',
    title: 'Wat zou een wijze vader nu doen?',
    skill: 'Reflectie',
    description: 'Denk aan een uitdagende situatie met je tiener nu. Stel je voor: een vader die je bewondert, of de meest liefdevolle, wijze versie van jezelf – wat zou die nu doen?',
    duration: '5 min',
    ageGroups: ['13-16'],
    difficulty: 'gevorderd',
    points: 15,
    psychologie: 'Het activeren van een intern "wijze vader"-model biedt een alternatief voor reactief gedrag. Compassiegerichte psychologie gebruikt dit als krachtige interventietechniek.',
    skillTip: 'Maak de figuur concreet: geef hem een naam, een gezicht. Stel je hem echt voor.',
    vermijd: 'Vermijd de figuur perfectie geven. Wijs en liefdevol is al meer dan genoeg.',
    leerdoel: 'Je activeert een intern compassievol leiderschap-model als leidraad voor je gedrag.',
    bron: 'Gilbert, P. (2010). The Compassionate Mind: A New Approach to Life\'s Challenges.',
  },
];
