import type { InteractiveTask } from './types';

export const INTERACTIVE_TASKS_18: InteractiveTask[] = [
  // =====================================================================
  // HERSTEL – 25 taken (5 per leeftijdsgroep)
  // =====================================================================

  // --- Herstel · 0-2 jaar ---
  {
    id: 'hers_02_51',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Huid-op-huid na onrust',
    description: 'Gebruik huid-op-huidcontact om de verbinding te herstellen na een onrustige periode.',
    instructions: [
      'Kies een rustig moment nadat je baby onrustig is geweest en jij gespannen reageerde.',
      'Trek je shirt uit en leg je baby op je blote borst.',
      'Adem langzaam en diep terwijl je je baby vasthoudt.',
      'Blijf minstens vijf minuten zo liggen en voel hoe jullie beide rustiger worden.',
    ],
    reflection: 'Huid-op-huidcontact is de meest directe manier om een verstoorde verbinding fysiek te herstellen.',
    scienceNote: 'Huid-op-huidcontact verlaagt cortisol en verhoogt oxytocine bij zowel vader als baby (Feldman et al., 2010).',
    durationMin: 5,
  },
  {
    id: 'hers_02_52',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Zachte stem na harde reactie',
    description: 'Herstel door bewust een zachte, warme stem te gebruiken nadat je te scherp hebt gereageerd.',
    instructions: [
      'Denk terug aan een moment vandaag waarop je stem te luid of te scherp was richting je baby.',
      'Ga naar je baby toe en ga op ooghoogte zitten.',
      'Praat met een bewust zachte, warme stem: "Papa is er. Alles is goed."',
      'Streel je baby over het hoofd of de rug terwijl je praat.',
    ],
    reflection: 'Baby\'s verstaan geen woorden, maar voelen toon en aanraking. Een zachte stem na een harde reactie is al herstel.',
    scienceNote: 'De prosodie (toonhoogte en ritme) van de ouderlijke stem reguleert het stresssysteem van zuigelingen (Fernald, 1989).',
    durationMin: 5,
  },
  {
    id: 'hers_02_53',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Herstelritueel na een moeilijke dag',
    description: 'Creëer een vast herstelritueel dat je inzet aan het einde van een moeilijke dag met je baby.',
    instructions: [
      'Kies een vast moment aan het einde van de dag, bijvoorbeeld voor het slapengaan.',
      'Houd je baby vast en zeg hardop: "Vandaag was moeilijk, maar ik ben er voor jou."',
      'Zing een kort slaapliedje of neurie een melodie die jullie allebei kalmeert.',
      'Geef je baby een kus en leg hem/haar rustig neer.',
    ],
    reflection: 'Een ritueel maakt herstel voorspelbaar. Als je baby opgroeit, wordt dit een herkenbaar anker van veiligheid.',
    scienceNote: 'Voorspelbare bedtijdrituelen bevorderen veilige gehechtheid en reguleren het stresssysteem (Mindell et al., 2015).',
    durationMin: 10,
  },
  {
    id: 'hers_02_54',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Brief aan je toekomstige kind',
    description: 'Schrijf een korte brief aan je baby over een moment waarop je het moeilijk had, als oefening in herstel.',
    instructions: [
      'Pak pen en papier en schrijf een korte brief aan je baby.',
      'Beschrijf eerlijk een moment waarop je overweldigd was of niet de vader was die je wilde zijn.',
      'Schrijf op wat je ervan geleerd hebt en wat je de volgende keer anders wilt doen.',
      'Bewaar de brief – dit wordt een krachtig document als je kind ouder is.',
    ],
    reflection: 'Opschrijven maakt een onzichtbaar gevoel zichtbaar. Het is herstel met jezelf én met je toekomstige relatie.',
    scienceNote: 'Expressief schrijven vermindert intrusieve gedachten en verbetert emotionele verwerking (Pennebaker, 1997).',
    durationMin: 15,
  },
  {
    id: 'hers_02_55',
    skill: 'Herstel',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Patronen herkennen in je reacties',
    description: 'Analyseer terugkerende patronen in je overreacties bij je baby en maak een persoonlijk actieplan.',
    instructions: [
      'Schrijf drie recente momenten op waarop je te heftig reageerde op je baby.',
      'Zoek het patroon: was het altijd hetzelfde tijdstip, dezelfde trigger, dezelfde emotie?',
      'Identificeer de onderliggende behoefte (slaap, erkenning, controle, rust).',
      'Formuleer één concrete afspraak met jezelf: "Wanneer ik [trigger] voel, doe ik eerst [actie]."',
    ],
    reflection: 'Patronen doorbreken begint met ze zien. Een vader die zijn triggers kent, kan kiezen in plaats van reageren.',
    scienceNote: 'Metacognitieve reflectie op eigen triggers vermindert automatische stressreacties bij ouders (Fonagy & Target, 1997).',
    durationMin: 15,
  },

  // --- Herstel · 3-5 jaar ---
  {
    id: 'hers_35_51',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Sorry zeggen op kindniveau',
    description: 'Oefen met het aanbieden van oprechte excuses aan je kleuter na een conflict.',
    instructions: [
      'Ga na een conflict op je hurken zitten zodat je op ooghoogte bent met je kind.',
      'Zeg eerlijk: "Het spijt me dat papa boos werd. Dat was niet leuk voor jou."',
      'Vraag: "Hoe voelde dat voor jou?" en luister naar het antwoord.',
      'Geef een knuffel als je kind dat wil, of bied een high-five aan.',
    ],
    reflection: 'Een vader die sorry zegt leert zijn kind dat fouten maken menselijk is en dat relaties gerepareerd kunnen worden.',
    scienceNote: 'Kinderen die ouderlijke excuses ervaren ontwikkelen sterkere morele ontwikkeling en empathie (Darby & Schlenker, 1982).',
    durationMin: 5,
  },
  {
    id: 'hers_35_52',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen een tekening maken',
    description: 'Gebruik samen tekenen als manier om opnieuw te verbinden na een ruzie of een boos moment.',
    instructions: [
      'Pak papier en kleurpotloden en ga naast je kind zitten.',
      'Zeg: "Zullen we samen iets leuks tekenen? Ik wil weer leuk met je doen."',
      'Teken samen – laat je kind het onderwerp kiezen.',
      'Schrijf samen een hartje of een kort zinnetje op de tekening.',
    ],
    reflection: 'Kleuters verwerken emoties niet via praten, maar via spel en creatie. Samen tekenen is samen herstellen.',
    scienceNote: 'Creatief samenspelen activeert het sociale-beloningssysteem en herstelt de hechtingsrelatie (Malchiodi, 2011).',
    durationMin: 10,
  },
  {
    id: 'hers_35_53',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het hersteigesprek met handpop',
    description: 'Gebruik een knuffel of handpop om via spel een conflict te bespreken en te herstellen.',
    instructions: [
      'Pak een knuffel of pop die je kind leuk vindt.',
      'Laat de pop vertellen: "Ik werd een keer boos op mijn vriendje, en toen voelde ik me verdrietig."',
      'Vraag je kind: "Wat denk jij dat de pop kan doen om het goed te maken?"',
      'Laat het gesprek terugvloeien naar jullie eigen situatie: "Papa voelde dat ook."',
    ],
    reflection: 'Via een derde (pop) kunnen kleuters veilig praten over moeilijke gevoelens zonder zich aangevallen te voelen.',
    scienceNote: 'Projective play helpt kinderen emoties te externaliseren en verwerken in een veilige context (Axline, 1947).',
    durationMin: 10,
  },
  {
    id: 'hers_35_54',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Het "opnieuw doen" spel',
    description: 'Speel een conflictsituatie opnieuw na, maar dan op een betere manier, als oefening in herstel.',
    instructions: [
      'Denk aan een recent conflict met je kleuter (bijv. schreeuwen over rommel).',
      'Zeg: "Weet je wat? Laten we dat momentje opnieuw doen, maar dan leuker."',
      'Speel de situatie opnieuw, maar nu met humor, geduld en een rustige stem.',
      'Eindig met: "Zo had papa het eigenlijk willen doen. Sorry voor de eerste keer."',
    ],
    reflection: 'Herstel wordt een speels leermoment als je het opnieuw mag doen. Je kind leert dat fouten geen eindpunt zijn.',
    scienceNote: 'Do-overs helpen kinderen alternatief gedrag te internaliseren via ervaringsgericht leren (Siegel & Bryson, 2014).',
    durationMin: 10,
  },
  {
    id: 'hers_35_55',
    skill: 'Herstel',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Emotiekaart na een conflict',
    description: 'Maak samen een emotiekaart om te begrijpen wat jullie allebei voelden tijdens en na een conflict.',
    instructions: [
      'Teken een groot hart op een vel papier en verdeel het in twee helften: "Papa" en "[naam kind]".',
      'Vraag je kind welke gevoelens hij/zij had: "Was je boos? Verdrietig? Bang?" en teken of schrijf dit op.',
      'Vul jouw helft eerlijk in: "Papa was ook boos, en daarna voelde papa zich verdrietig."',
      'Bespreek samen: "Wat kunnen we de volgende keer doen zodat ons hart minder pijn doet?"',
    ],
    reflection: 'Een emotiekaart maakt onzichtbare gevoelens zichtbaar. Het leert je kind dat papa ook gevoelens heeft.',
    scienceNote: 'Emotielabeling verlaagt amygdala-activatie en helpt zowel kinderen als volwassenen bij emotieregulatie (Lieberman et al., 2007).',
    durationMin: 15,
  },

  // --- Herstel · 6-9 jaar ---
  {
    id: 'hers_69_51',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'De eerste stap zetten',
    description: 'Neem als vader de eerste stap naar herstel, ook als je kind "begonnen is" met het conflict.',
    instructions: [
      'Wacht tot de emoties zijn gezakt (minstens 15 minuten na het conflict).',
      'Ga naar je kind en zeg: "Ik wil het graag goedmaken. Mag ik naast je zitten?"',
      'Luister eerst naar je kind zonder te verdedigen of uit te leggen.',
      'Zeg: "Ik begrijp dat het vervelend was. Ik had het anders moeten aanpakken."',
    ],
    reflection: 'De eerste stap zetten is geen zwakte – het is leiderschap. Je kind leert dat de sterkste als eerste herstelt.',
    scienceNote: 'Ouders die als eerste herstellen modelleren emotionele moed en versterken de veilige basis (Gottman, 2011).',
    durationMin: 10,
  },
  {
    id: 'hers_69_52',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Samen iets leuks doen na een ruzie',
    description: 'Plan bewust een leuke activiteit samen om de verbinding te herstellen na een conflict.',
    instructions: [
      'Kies na een ruzie of conflict een activiteit die je kind leuk vindt (samen voetballen, koekjes bakken, een wandeling).',
      'Zeg: "Ik vond het niet fijn hoe het ging. Zullen we samen iets leuks doen?"',
      'Doe de activiteit zonder het conflict opnieuw te bespreken – laat de verbinding het werk doen.',
      'Geniet bewust van het samen-zijn en benoem dat: "Dit vind ik fijn, samen met jou."',
    ],
    reflection: 'Soms is samen iets doen krachtiger dan erover praten. Gedeelde positieve ervaringen herstellen de band.',
    scienceNote: 'Gedeelde positieve activiteiten verhogen de ratio positieve vs. negatieve interacties die cruciaal is voor relatieherstel (Gottman, 1994).',
    durationMin: 10,
  },
  {
    id: 'hers_69_53',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'De herstelbrief',
    description: 'Schrijf een kort briefje aan je kind na een conflict waarin je verantwoordelijkheid neemt.',
    instructions: [
      'Pak een vel papier of een kaartje en schrijf je kind een persoonlijke brief.',
      'Begin met: "Lieve [naam], ik wil je iets vertellen over wat er gebeurde."',
      'Neem verantwoordelijkheid voor jouw aandeel: "Ik had niet moeten schreeuwen / te streng zijn."',
      'Eindig met iets positiefs: "Ik ben trots op je en ik hou van je, ook na een ruzie."',
    ],
    reflection: 'Een brief geeft je kind iets tastbaars. Het kan worden herlezen en wordt een bewijs dat papa altijd terugkomt.',
    scienceNote: 'Geschreven excuses worden als oprechter ervaren en hebben een langduriger effect dan verbale excuses (Schlenker & Darby, 1981).',
    durationMin: 15,
  },
  {
    id: 'hers_69_54',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Benoem je eigen fout hardop',
    description: 'Oefen met het hardop benoemen van je eigen fout tegenover je kind, zonder excuses of verklaringen.',
    instructions: [
      'Kies een recent moment waarop je oneerlijk, te streng of ongeduldig was.',
      'Ga naar je kind en zeg: "Ik wil eerlijk zijn. Ik heb een fout gemaakt."',
      'Beschrijf specifiek wat je deed zonder het te bagatelliseren of te verklaren.',
      'Vraag: "Wat zou jij fijn vinden dat ik de volgende keer doe?"',
    ],
    reflection: 'Kinderen van 6-9 ontwikkelen een sterk gevoel voor rechtvaardigheid. Een eerlijke vader wint respect.',
    scienceNote: 'In de concrete-operationele fase (Piaget) ontwikkelen kinderen moreel redeneren en waarderen ze eerlijkheid en rechtvaardigheid (Piaget, 1932).',
    durationMin: 10,
  },
  {
    id: 'hers_69_55',
    skill: 'Herstel',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het familievergadermoment',
    description: 'Organiseer een kort familiemoment om samen regels te bespreken voor hoe jullie omgaan met conflicten.',
    instructions: [
      'Plan een kort overleg (10 minuten) aan de keukentafel met je kind (en eventueel partner).',
      'Start met: "Ik wil dat we samen afspraken maken voor als we boos worden op elkaar."',
      'Laat je kind meedenken: "Wat zou jij willen dat papa doet als hij boos wordt?"',
      'Schrijf samen drie afspraken op en hang ze op een zichtbare plek.',
    ],
    reflection: 'Kinderen die meedenken over regels voelen zich gerespecteerd en houden zich er eerder aan.',
    scienceNote: 'Democratische opvoedingsstijlen waarbij kinderen mee mogen beslissen leiden tot betere zelfregulatie en samenwerking (Baumrind, 1991).',
    durationMin: 15,
  },

  // --- Herstel · 10-12 jaar ---
  {
    id: 'hers_1012_51',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Check-in na een botsing',
    description: 'Doe een korte check-in met je pre-puber nadat jullie een aanvaring hebben gehad.',
    instructions: [
      'Wacht minstens een half uur na het conflict totdat de emoties zijn afgezakt.',
      'Klop op de deur van je kind en vraag: "Mag ik even binnenkomen?"',
      'Zeg: "Ik wil even checken hoe het met je gaat na wat er gebeurde."',
      'Luister zonder te corrigeren en sluit af met: "Dank je dat je het met me deelt."',
    ],
    reflection: 'Een check-in is geen preek. Het is laten zien dat je kind belangrijk genoeg is om naar terug te komen.',
    scienceNote: 'Emotionele beschikbaarheid van vaders voorspelt psychosociaal welzijn van pre-pubers sterker dan die van moeders (Lamb, 2010).',
    durationMin: 10,
  },
  {
    id: 'hers_1012_52',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Geef ruimte en kom dan terug',
    description: 'Leer de balans tussen ruimte geven en terugkomen na een conflict met je pre-puber.',
    instructions: [
      'Na een conflict, respecteer als je kind zich terugtrekt op de kamer.',
      'Zeg: "Ik geef je even rust. Ik kom over een half uur terug."',
      'Kom na het beloofde half uur terug – houd je woord.',
      'Bied een klein gebaar aan: een glas drinken, een snack, of vraag of je kind zin heeft om samen iets te doen.',
    ],
    reflection: 'Pre-pubers hebben ruimte nodig maar ook de zekerheid dat je terugkomt. Beide zijn herstel.',
    scienceNote: 'Autonomie-ondersteuning gecombineerd met betrouwbare beschikbaarheid bevordert gezonde hechtingsontwikkeling bij pre-adolescenten (Allen & Land, 1999).',
    durationMin: 5,
  },
  {
    id: 'hers_1012_53',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Eerlijk gesprek over jouw aandeel',
    description: 'Voer een open gesprek waarin je je eigen aandeel in het conflict benoemt en bespreekt.',
    instructions: [
      'Nodig je kind uit voor een gesprek op een neutraal moment (bijv. tijdens een wandeling).',
      'Begin met: "Ik heb nagedacht over onze ruzie en ik wil eerlijk zijn over wat ik fout deed."',
      'Benoem concreet jouw aandeel: niet luisteren, te snel oordelen, te luid praten.',
      'Vraag: "Hoe kan ik dat de volgende keer beter doen, denk je?"',
    ],
    reflection: 'Een vader die eerlijk reflecteert modelleert groei. Je kind leert dat volwassenen ook fouten erkennen.',
    scienceNote: 'Ouderlijke zelfonthulling versterkt vertrouwen en intimiteit in de ouder-kindrelatie bij pre-adolescenten (Buhrmester & Prager, 1995).',
    durationMin: 15,
  },
  {
    id: 'hers_1012_54',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Samen een afkoelplan maken',
    description: 'Maak samen met je kind een afkoelplan voor de volgende keer dat jullie boos worden op elkaar.',
    instructions: [
      'Ga met je kind aan tafel zitten en zeg: "Ik wil dat we een plan maken voor als we allebei boos worden."',
      'Brainstorm samen drie dingen die jullie allebei kunnen doen om af te koelen (bijv. naar andere kamers gaan, muziek luisteren).',
      'Spreek een tijdlimiet af: "Na 20 minuten komen we weer bij elkaar."',
      'Schrijf het plan op en geef jullie allebei een kopie.',
    ],
    reflection: 'Een afkoelplan is preventief herstel. Je kind leert dat boosheid oké is als je er verantwoordelijk mee omgaat.',
    scienceNote: 'Gezamenlijke probleemoplossing bevordert de zelfregulatievaardigheden van pre-pubers en versterkt de ouder-kindrelatie (Greene, 2014).',
    durationMin: 15,
  },
  {
    id: 'hers_1012_55',
    skill: 'Herstel',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Reflectie op je eigen opvoedgeschiedenis',
    description: 'Deel met je kind hoe je eigen vader omging met conflicten en wat je anders wilt doen.',
    instructions: [
      'Kies een rustig moment en begin: "Ik wil je iets vertellen over hoe het bij mij thuis was toen ik zo oud was als jij."',
      'Vertel eerlijk maar leeftijdsgeschikt hoe je eigen ouders met conflicten omgingen.',
      'Benoem wat je daarvan geleerd hebt: "Ik miste dat mijn vader sorry zei. Daarom wil ik dat wél doen."',
      'Vraag: "Wat zou jij willen dat ik altijd blijf doen, zelfs als we ruzie hebben?"',
    ],
    reflection: 'Door je eigen geschiedenis te delen maak je jezelf menselijk. Je kind begrijpt dat je bewust een andere keuze maakt.',
    scienceNote: 'Ouders met een coherent hechtingsnarratief (verwerkt verleden) hebben vaker veilig gehechte kinderen (Main et al., 1985).',
    durationMin: 15,
  },

  // --- Herstel · 13-16 jaar ---
  {
    id: 'hers_1316_51',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Het korte sms-bericht',
    description: 'Stuur je tiener een kort berichtje om de verbinding te herstellen als face-to-face te moeilijk is.',
    instructions: [
      'Na een conflict waarbij je tiener zich heeft teruggetrokken, pak je telefoon.',
      'Stuur een kort bericht: "Hey, ik vond het niet fijn hoe het ging. Ik hou van je, ook als we het oneens zijn."',
      'Voeg geen verwijten, uitleg of voorwaarden toe – houd het puur.',
      'Geef je tiener de tijd om te reageren zonder aandringen.',
    ],
    reflection: 'Tieners communiceren digitaal. Een eerlijk berichtje is voor hen soms makkelijker te ontvangen dan een gesprek.',
    scienceNote: 'Digitale communicatie kan een brug vormen voor emotioneel herstel bij adolescenten die face-to-face contact vermijden (Valkenburg & Peter, 2011).',
    durationMin: 5,
  },
  {
    id: 'hers_1316_52',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Erken de tiener-ervaring',
    description: 'Herstel door expliciet te erkennen dat het voor je tiener anders voelde dan voor jou.',
    instructions: [
      'Zoek een geschikt moment na het conflict (niet dezelfde avond als de emoties hoog zijn).',
      'Begin met: "Ik heb erover nagedacht en ik denk dat het voor jou heel anders voelde dan voor mij."',
      'Vraag: "Wil je me vertellen hoe jij het hebt ervaren?"',
      'Luister zonder te onderbreken, vat samen wat je hoort, en bedank je tiener.',
    ],
    reflection: 'Tieners willen bovenal gehoord worden. Erkenning is vaak belangrijker dan een oplossing.',
    scienceNote: 'Perspectief nemen door ouders is de sterkste voorspeller van adolescent welzijn en relatietevredenheid (Soenens et al., 2007).',
    durationMin: 10,
  },
  {
    id: 'hers_1316_53',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Kwetsbaar zijn zonder controle',
    description: 'Deel je eigen kwetsbaarheid met je tiener als een manier om vertrouwen te herstellen na een conflict.',
    instructions: [
      'Kies een moment waarop je alleen bent met je tiener (bijv. in de auto).',
      'Zeg: "Ik wil eerlijk tegen je zijn. Ik voel me soms onzeker over hoe ik reageer als vader."',
      'Deel een specifiek voorbeeld zonder je te verdedigen: "Toen ik schreeuwde, schaamde ik me achteraf."',
      'Eindig niet met een les maar met een vraag: "Hoe kunnen we dit samen beter doen?"',
    ],
    reflection: 'Kwetsbaarheid van een vader is geen zwakte – het is de meest krachtige manier om vertrouwen te winnen bij een tiener.',
    scienceNote: 'Ouderlijke authenticiteit en zelfonthulling bevorderen hechtingsveiligheid en verminderen adolescent verzet (Kernis & Goldman, 2006).',
    durationMin: 15,
  },
  {
    id: 'hers_1316_54',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Grenzen herstellen zonder machtstrijd',
    description: 'Leer hoe je na een conflict opnieuw grenzen kunt stellen zonder in een machtsstrijd te vervallen.',
    instructions: [
      'Wacht tot de emoties gezakt zijn en nodig je tiener uit voor een gesprek.',
      'Start met herstel: "Het spijt me dat ik schreeuwde. Dat was niet oké van mij."',
      'Herbevestig de grens rustig: "De regel blijft staan, maar ik had die op een betere manier moeten communiceren."',
      'Vraag: "Hoe zou jij het fijn vinden als ik zoiets de volgende keer bespreek?"',
    ],
    reflection: 'Herstel en grenzen stellen sluiten elkaar niet uit. Je kunt sorry zeggen én consequent zijn.',
    scienceNote: 'Autoritatief opvoeden combineert warmte met structuur en leidt tot de beste uitkomsten bij adolescenten (Steinberg, 2001).',
    durationMin: 10,
  },
  {
    id: 'hers_1316_55',
    skill: 'Herstel',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Het diepe herstelgesprek',
    description: 'Voer een uitgebreid, eerlijk gesprek over een terugkerend conflictpatroon tussen jou en je tiener.',
    instructions: [
      'Plan bewust een moment (niet spontaan) en zeg: "Ik wil met je praten over iets dat ik merk in hoe wij met elkaar omgaan."',
      'Beschrijf het patroon dat je ziet zonder te beschuldigen: "Ik merk dat we vaak botsen over [onderwerp] en dan allebei dichklappen."',
      'Deel jouw aandeel eerlijk: "Ik denk dat ik [gedrag] doe omdat ik [gevoel/angst] heb."',
      'Vraag je tiener hetzelfde te doen en werk samen aan één concrete verandering die jullie allebei willen proberen.',
    ],
    reflection: 'Een diep herstelgesprek verandert de dynamiek. Het verschuift van machtsstrijd naar samenwerking.',
    scienceNote: 'Collaboratieve conflictresolutie tussen ouders en adolescenten voorspelt betere psychologische aanpassing en relatiekwaliteit (Laursen & Collins, 2009).',
    durationMin: 15,
  },

  // =====================================================================
  // REFLECTIE – 25 taken (5 per leeftijdsgroep)
  // =====================================================================

  // --- Reflectie · 0-2 jaar ---
  {
    id: 'refl_02_51',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Eén ding dat goed ging vandaag',
    description: 'Reflecteer elke avond kort op één ding dat je goed deed als vader vandaag.',
    instructions: [
      'Neem voor het slapengaan één minuut de tijd om stil te staan bij je dag als vader.',
      'Benoem één concreet moment waarop je goed reageerde op je baby.',
      'Schrijf het op in je telefoon of een notitieboekje: "Vandaag deed ik goed: [moment]."',
      'Laat het positieve gevoel even toe – je verdient die erkenning.',
    ],
    reflection: 'Vaders zijn vaak streng voor zichzelf. Bewust het goede zien is een essentiële reflectievaardigheid.',
    scienceNote: 'Positieve zelfreflectie verhoogt self-efficacy bij ouders en vermindert ouderstress (Bandura, 1997).',
    durationMin: 5,
  },
  {
    id: 'refl_02_52',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Wat voelde ik echt?',
    description: 'Reflecteer op een moment vandaag waarop je een sterke emotie voelde als vader en benoem die emotie.',
    instructions: [
      'Denk terug aan een moment vandaag waarop je iets sterks voelde (frustratie, ontroering, vermoeidheid).',
      'Probeer de exacte emotie te benoemen: niet "boos" maar misschien "machteloos" of "overweldigd".',
      'Stel jezelf de vraag: "Waar in mijn lichaam voelde ik dit?"',
      'Schrijf de emotie en de situatie kort op.',
    ],
    reflection: 'Emoties benoemen is de eerste stap naar ze begrijpen. Een vader die zijn gevoelens kent, reageert bewuster.',
    scienceNote: 'Affect labeling vermindert de intensiteit van emotionele reacties via prefrontale cortex-regulatie (Lieberman et al., 2007).',
    durationMin: 5,
  },
  {
    id: 'refl_02_53',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Mijn verwachtingen onder de loep',
    description: 'Onderzoek of je verwachtingen van je baby realistisch zijn voor de leeftijdsfase.',
    instructions: [
      'Schrijf drie dingen op waarvan je verwacht dat je baby ze kan of zou moeten doen.',
      'Zoek per verwachting op of dit past bij de ontwikkelingsfase van je baby.',
      'Markeer welke verwachtingen realistisch zijn en welke te hoog gegrepen.',
      'Reflecteer: "Hoe beïnvloeden mijn onrealistische verwachtingen mijn geduld?"',
    ],
    reflection: 'Veel frustratie komt voort uit verwachtingen die niet passen bij de leeftijd. Kennis vermindert ongeduld.',
    scienceNote: 'Onrealistische ontwikkelingsverwachtingen van ouders zijn een risicofactor voor negatief opvoedgedrag (Azar & Rohrbeck, 1986).',
    durationMin: 10,
  },
  {
    id: 'refl_02_54',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Hoe werd ik zelf vastgehouden?',
    description: 'Reflecteer op hoe je eigen ouders je als baby troostten en hoe dat je vaderschap beïnvloedt.',
    instructions: [
      'Ga rustig zitten en denk na over wat je weet over hoe je eigen ouders met je omgingen als baby.',
      'Vraag jezelf af: "Wat vertelden mijn ouders over hoe ze mij troostten? Of juist niet?"',
      'Schrijf op welke patronen je herkent in hoe jij nu met je eigen baby omgaat.',
      'Reflecteer: "Wat wil ik bewust anders doen, en wat wil ik behouden?"',
    ],
    reflection: 'Hoe je zelf bent vastgehouden bepaalt onbewust hoe je je eigen kind vasthoudt. Bewustzijn is de sleutel tot verandering.',
    scienceNote: 'Het Adult Attachment Interview toont aan dat de verwerking van eigen hechtingservaringen bepalend is voor hechtingsoverdracht (Main & Hesse, 1990).',
    durationMin: 15,
  },
  {
    id: 'refl_02_55',
    skill: 'Reflectie',
    ageGroup: '0-2',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Mijn vaderidentiteit in kaart',
    description: 'Breng je vaderidentiteit in kaart: wie ben je als vader, wie wil je zijn, en wat staat er in de weg?',
    instructions: [
      'Schrijf op: "Als vader ben ik iemand die..." en maak de zin vijf keer af met eerlijke antwoorden.',
      'Schrijf daarna: "Als vader wil ik iemand zijn die..." en maak ook die zin vijf keer af.',
      'Vergelijk de twee lijsten en markeer de grootste verschillen.',
      'Kies één verschil en formuleer een concrete eerste stap om daar naartoe te bewegen.',
    ],
    reflection: 'De kloof tussen wie je bent en wie je wilt zijn is niet iets om je voor te schamen – het is je groeipotentieel.',
    scienceNote: 'Discrepantie tussen het actuele en ideale zelf motiveert gedragsverandering wanneer het bewust wordt gemaakt (Higgins, 1987).',
    durationMin: 15,
  },

  // --- Reflectie · 3-5 jaar ---
  {
    id: 'refl_35_51',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Het speelmoment terugkijken',
    description: 'Reflecteer kort op het laatste speelmoment met je kleuter: was je echt aanwezig?',
    instructions: [
      'Denk terug aan het laatste moment dat je met je kleuter speelde.',
      'Stel jezelf eerlijk de vraag: "Was ik echt bij het spel, of was ik met mijn hoofd ergens anders?"',
      'Scoor jezelf op een schaal van 1-10 voor aanwezigheid.',
      'Schrijf één ding op dat je de volgende keer kunt doen om meer aanwezig te zijn.',
    ],
    reflection: 'Kleuters merken feilloos of je er echt bent. Reflectie op aanwezigheid is de eerste stap naar verbetering.',
    scienceNote: 'Mindful parenting – bewuste aanwezigheid bij het kind – verlaagt ouderstress en verhoogt opvoedkwaliteit (Duncan et al., 2009).',
    durationMin: 5,
  },
  {
    id: 'refl_35_52',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Mijn top-3 vadermomenten',
    description: 'Schrijf je drie mooiste vadermomenten van de afgelopen week op en reflecteer op wat ze gemeen hebben.',
    instructions: [
      'Neem vijf minuten en schrijf drie momenten op van de afgelopen week waarop je je een goede vader voelde.',
      'Beschrijf per moment kort wat er gebeurde en wat je voelde.',
      'Zoek het gemeenschappelijke: was het steeds een soortgelijke situatie, emotie of activiteit?',
      'Reflecteer: "Hoe kan ik meer van dit soort momenten creëren?"',
    ],
    reflection: 'Je sterke momenten kennen is net zo belangrijk als je zwakke plekken kennen. Bouw voort op wat al werkt.',
    scienceNote: 'Strengths-based reflectie verhoogt self-efficacy en positief opvoedgedrag effectiever dan focussen op tekorten (Seligman, 2011).',
    durationMin: 5,
  },
  {
    id: 'refl_35_53',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Mijn automatische reactie ontleden',
    description: 'Analyseer een automatische reactie die je had op je kleuter en onderzoek waar die vandaan komt.',
    instructions: [
      'Denk aan een moment deze week waarop je automatisch reageerde (schreeuwde, dreigde, afkapte).',
      'Schrijf de situatie op: wat deed je kind, wat voelde jij, hoe reageerde je?',
      'Stel de vraag: "Waar heb ik deze reactie geleerd? Van mijn ouders? School? Cultuur?"',
      'Formuleer een alternatieve reactie die past bij de vader die je wilt zijn.',
    ],
    reflection: 'Automatische reacties zijn aangeleerd, niet aangeboren. Wat is aangeleerd kan worden omgeleerd.',
    scienceNote: 'Intergenerationele overdracht van opvoedpatronen kan worden doorbroken door reflectief functioneren (Slade, 2005).',
    durationMin: 10,
  },
  {
    id: 'refl_35_54',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Wat zou mijn kind zeggen?',
    description: 'Probeer je voor te stellen hoe je kleuter jou als vader zou beschrijven en reflecteer daarop.',
    instructions: [
      'Stel je voor dat iemand aan je kleuter vraagt: "Hoe is jouw papa?"',
      'Schrijf op wat je denkt dat je kind zou zeggen – wees eerlijk, niet idealistisch.',
      'Markeer de dingen die je trots maken en de dingen die je ongemakkelijk maken.',
      'Kies één aspect dat je wilt verbeteren en schrijf een micro-doel op voor deze week.',
    ],
    reflection: 'Het perspectief van je kind innemen is krachtige reflectie. Het verschuift de focus van jouw intentie naar jouw impact.',
    scienceNote: 'Perspectief nemen vanuit het kind verbetert ouderlijke sensitiviteit en responsiviteit (Oppenheim & Koren-Karie, 2013).',
    durationMin: 10,
  },
  {
    id: 'refl_35_55',
    skill: 'Reflectie',
    ageGroup: '3-5',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Mijn opvoedwaarden definiëren',
    description: 'Definieer je drie kernwaarden als vader en toets of je dagelijks handelen daarmee in lijn is.',
    instructions: [
      'Schrijf een lijst van tien waarden die je belangrijk vindt als vader (bijv. geduld, eerlijkheid, plezier, veiligheid).',
      'Kies de drie belangrijkste – dit zijn je kernwaarden.',
      'Geef per waarde een eerlijk cijfer (1-10): in hoeverre leef je deze waarde dagelijks na?',
      'Kies de waarde met de laagste score en bedenk drie kleine, concrete acties om deze week meer naar die waarde te leven.',
    ],
    reflection: 'Waarden zijn kompas, geen eindbestemming. Weten waar je staat maakt bewust navigeren mogelijk.',
    scienceNote: 'Waardengedreven opvoeding leidt tot meer consistentie en minder reactief ouderschap (Hayes et al., 2006 – ACT-model).',
    durationMin: 15,
  },

  // --- Reflectie · 6-9 jaar ---
  {
    id: 'refl_69_51',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Het eindrapport voor mezelf',
    description: 'Geef jezelf aan het einde van de week een kort vaderrapport: wat ging goed en wat kan beter?',
    instructions: [
      'Neem vijf minuten op vrijdag- of zondagavond.',
      'Schrijf op: "Deze week als vader ging goed: [...]" en noem minstens twee dingen.',
      'Schrijf op: "Deze week als vader kan beter: [...]" en noem één ding.',
      'Eindig met: "Volgende week ga ik proberen om: [één concreet voornemen]."',
    ],
    reflection: 'Een wekelijks rapport is geen zelfkritiek – het is zelfleiderschap. Reflectieve vaders groeien sneller.',
    scienceNote: 'Regelmatige zelfreflectie bevordert gedragsverandering via het zelfregulerend leermechanisme (Zimmerman, 2002).',
    durationMin: 5,
  },
  {
    id: 'refl_69_52',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Welk gevoel overheerste vandaag?',
    description: 'Reflecteer op de dominante emotie die je voelde in je rol als vader vandaag.',
    instructions: [
      'Denk terug aan je interacties met je kind vandaag.',
      'Kies het gevoel dat het sterkst aanwezig was: trots, frustratie, vermoeidheid, vreugde, schuld?',
      'Schrijf op wat dit gevoel triggerde en hoe het je gedrag beïnvloedde.',
      'Stel jezelf de vraag: "Is dit gevoel een signaal dat ik iets moet veranderen?"',
    ],
    reflection: 'Je dominante emotie als vader is een thermometer. Het vertelt je hoe het écht gaat, voorbij de dagelijkse drukte.',
    scienceNote: 'Emotionele zelfmonitoring verbetert affectregulatie en verlaagt reactief ouderschap (Gottman & DeClaire, 1997).',
    durationMin: 5,
  },
  {
    id: 'refl_69_53',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'De stille boodschap achter gedrag',
    description: 'Reflecteer op lastig gedrag van je kind en probeer de onderliggende behoefte te ontdekken.',
    instructions: [
      'Denk aan een recent moment waarop je kind lastig gedrag vertoonde (zeuren, liegen, brutaal zijn).',
      'Schrijf het gedrag op en daarnaast: "Wat zou mijn kind hiermee eigenlijk willen zeggen?"',
      'Brainstorm mogelijke onderliggende behoeften: aandacht, autonomie, verbinding, controle, rust.',
      'Reflecteer: "Hoe kan ik de volgende keer reageren op de behoefte in plaats van op het gedrag?"',
    ],
    reflection: 'Achter elk lastig gedrag zit een onvervulde behoefte. Reflectie verschuift je blik van probleem naar oplossing.',
    scienceNote: 'De Circle of Security benadering leert ouders om te kijken naar de behoefte achter gedrag (Powell et al., 2013).',
    durationMin: 10,
  },
  {
    id: 'refl_69_54',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Mijn triggerdagboek',
    description: 'Houd een week lang een kort triggerdagboek bij om patronen in je frustratie te ontdekken.',
    instructions: [
      'Maak een notitiepagina met drie kolommen: Situatie | Mijn reactie | Wat ik voelde.',
      'Schrijf elke dag minstens één moment op waarop je gefrustreerd raakte door je kind.',
      'Na vijf dagen: lees alles terug en zoek naar patronen (tijdstip, type situatie, emotie).',
      'Formuleer één inzicht: "Ik merk dat ik vooral getriggerd word door [...]."',
    ],
    reflection: 'Een triggerdagboek is geen bewijs van falen, maar van moed. Je triggers kennen is de eerste stap naar ze beheersen.',
    scienceNote: 'Zelfmonitoringtechnieken verhogen bewustzijn en verminderen automatische stressreacties bij ouders (Bögels et al., 2010).',
    durationMin: 10,
  },
  {
    id: 'refl_69_55',
    skill: 'Reflectie',
    ageGroup: '6-9',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Brief van mijn toekomstige kind',
    description: 'Schrijf een brief vanuit het perspectief van je kind als volwassene over wat het van jou als vader heeft geleerd.',
    instructions: [
      'Stel je voor dat je kind 25 jaar is en je een brief schrijft over jullie relatie.',
      'Schrijf die brief vanuit je kind: "Lieve papa, wat ik het meest waardeer aan jou als vader is..."',
      'Schrijf ook: "Wat ik soms lastig vond was..." – wees eerlijk, niet idealistisch.',
      'Lees de brief terug en reflecteer: welke vader wil je zijn zodat deze brief werkelijkheid wordt?',
    ],
    reflection: 'Deze brief is je kompas. Het verbindt wie je nu bent met wie je wilt worden in de ogen van je kind.',
    scienceNote: 'Toekomstig-zelf visualisatie motiveert gedragsverandering en verhoogt doelgerichtheid (Hershfield, 2011).',
    durationMin: 15,
  },

  // --- Reflectie · 10-12 jaar ---
  {
    id: 'refl_1012_51',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Hoe was ik zelf op die leeftijd?',
    description: 'Reflecteer op je eigen ervaringen als 10-12-jarige en hoe dat je blik op je kind beïnvloedt.',
    instructions: [
      'Neem vijf minuten en denk terug aan jezelf op de leeftijd van je kind.',
      'Schrijf op: wat vond je leuk, wat was moeilijk, wat had je nodig van je vader?',
      'Vergelijk dit met je eigen kind: welke overeenkomsten en verschillen zie je?',
      'Reflecteer: "In hoeverre projecteer ik mijn eigen ervaringen op mijn kind?"',
    ],
    reflection: 'Je eigen verleden kleurt hoe je naar je kind kijkt. Bewustzijn voorkomt dat je je eigen verhaal op je kind plakt.',
    scienceNote: 'Projectie-identificatie is een onbewust mechanisme waarbij ouders eigen onverwerkte ervaringen overdragen op hun kind (Fraiberg et al., 1975).',
    durationMin: 5,
  },
  {
    id: 'refl_1012_52',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Eén vraag aan mezelf',
    description: 'Stel jezelf elke avond één reflectievraag over je vaderschap en beantwoord die eerlijk.',
    instructions: [
      'Kies vanavond één vraag: "Was ik vandaag de vader die mijn kind nodig had?"',
      'Beantwoord de vraag eerlijk, zonder oordeel of excuses.',
      'Als het antwoord "nee" is: schrijf op wat er in de weg stond (vermoeidheid, stress, afleiding).',
      'Formuleer één klein voornemen voor morgen.',
    ],
    reflection: 'Eén eerlijke vraag per dag is krachtiger dan duizend goede voornemens. Reflectie is een dagelijkse gewoonte.',
    scienceNote: 'Dagelijkse micro-reflectie is effectiever voor gedragsverandering dan periodieke grote evaluaties (Schön, 1983).',
    durationMin: 5,
  },
  {
    id: 'refl_1012_53',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Mijn blinde vlek ontdekken',
    description: 'Vraag feedback aan je partner, vriend of familielid over een mogelijke blinde vlek in je opvoeding.',
    instructions: [
      'Kies iemand die je vertrouwt en die je in actie ziet als vader.',
      'Vraag: "Wat is één ding dat ik als vader niet zie of onderschat?"',
      'Luister zonder te verdedigen – schrijf het antwoord letterlijk op.',
      'Reflecteer: "Herken ik dit? Wat kan ik ermee doen?"',
    ],
    reflection: 'Blinde vlekken kun je per definitie niet zelf zien. Feedback vragen is een teken van kracht, niet van zwakte.',
    scienceNote: 'Het Johari-venster model toont dat zelfinzicht groeit wanneer we actief feedback zoeken van anderen (Luft & Ingham, 1955).',
    durationMin: 10,
  },
  {
    id: 'refl_1012_54',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Mijn energielekken als vader',
    description: 'Identificeer welke aspecten van het ouderschap je energie kosten en welke je energie geven.',
    instructions: [
      'Maak twee kolommen: "Geeft mij energie" en "Kost mij energie".',
      'Schrijf per kolom minstens vijf activiteiten, situaties of momenten op die met je kind te maken hebben.',
      'Kijk naar de balans: overheerst de linker- of rechterkolom?',
      'Bedenk één manier om een energielek te verkleinen en één manier om een energiebron vaker in te zetten.',
    ],
    reflection: 'Een uitgeputte vader is geen goede vader. Je energiebalans kennen is geen luxe maar een noodzaak.',
    scienceNote: 'Ouderburnout ontstaat wanneer de opvoedingsbelasting structureel de opvoedingsbronnen overstijgt (Mikolajczak et al., 2018).',
    durationMin: 10,
  },
  {
    id: 'refl_1012_55',
    skill: 'Reflectie',
    ageGroup: '10-12',
    difficulty: 'expert',
    xpReward: 20,
    title: 'De vader die ik had versus de vader die ik ben',
    description: 'Maak een diepgaande vergelijking tussen je eigen vader en jezelf als vader – en kies bewust wat je overneemt.',
    instructions: [
      'Maak een tabel met drie kolommen: "Mijn vader deed" | "Ik doe nu" | "Ik kies bewust".',
      'Vul minstens vijf rijen in met thema\'s als: conflicten, affectie, aanwezigheid, grenzen, emoties tonen.',
      'Markeer waar je automatisch het patroon van je vader herhaalt.',
      'Kies per rij bewust: "Dit neem ik over" of "Dit doe ik anders" – en beschrijf hoe.',
    ],
    reflection: 'Je bent niet je vader. Maar zonder bewuste reflectie herhaal je onbewust zijn patronen. Keuze begint bij bewustzijn.',
    scienceNote: 'Intergenerationele transmissie van opvoedgedrag wordt gemodereerd door reflectief vermogen van de ouder (Fonagy et al., 2002).',
    durationMin: 15,
  },

  // --- Reflectie · 13-16 jaar ---
  {
    id: 'refl_1316_51',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Wat weet ik écht over mijn tiener?',
    description: 'Test eerlijk hoeveel je weet over het leven van je tiener en reflecteer op de lege plekken.',
    instructions: [
      'Beantwoord deze vragen over je tiener: Wie is zijn/haar beste vriend? Welk liedje luistert hij/zij het meest? Waar maakt hij/zij zich zorgen over?',
      'Scoor jezelf: hoeveel kon je met zekerheid beantwoorden?',
      'Reflecteer: "Wat zegt het over onze verbinding als ik dit niet weet?"',
      'Neem je voor om deze week één vraag oprecht aan je tiener te stellen.',
    ],
    reflection: 'Je tiener kennen vereist actieve nieuwsgierigheid. Wat je niet weet is een uitnodiging om te vragen, niet om je schuldig te voelen.',
    scienceNote: 'Ouderlijke kennis over het leven van de adolescent ("parental knowledge") is de sterkste beschermende factor tegen risicogedrag (Stattin & Kerr, 2000).',
    durationMin: 5,
  },
  {
    id: 'refl_1316_52',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'basis',
    xpReward: 10,
    title: 'Mijn angsten als vader van een tiener',
    description: 'Identificeer en benoem je grootste angsten rondom het opgroeien van je tiener.',
    instructions: [
      'Schrijf drie dingen op waar je je zorgen over maakt als het gaat om je tiener.',
      'Stel per zorg de vraag: "Is dit gebaseerd op feiten of op mijn eigen angst?"',
      'Reflecteer: "In hoeverre beïnvloeden deze angsten hoe ik reageer op mijn tiener?"',
      'Schrijf op hoe je angst soms leidt tot controleren, preken of afstand nemen.',
    ],
    reflection: 'Angst is een slechte raadgever. Een reflectieve vader herkent angst en kiest toch voor vertrouwen.',
    scienceNote: 'Ouderlijke angst leidt tot overcontrole, wat de autonomie-ontwikkeling van adolescenten ondermijnt (Barber, 1996).',
    durationMin: 5,
  },
  {
    id: 'refl_1316_53',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'De controlethermometer',
    description: 'Onderzoek hoe groot je behoefte aan controle is in de opvoeding van je tiener en waar die vandaan komt.',
    instructions: [
      'Schrijf vijf situaties op waarin je de neiging hebt om je tiener te controleren (telefoongebruik, vrienden, schoolwerk, kleding, uitgaan).',
      'Geef per situatie een score van 1-10 voor je controlebehoefte.',
      'Stel per situatie de vraag: "Is mijn controle hier nodig voor veiligheid, of komt het uit mijn eigen onzekerheid?"',
      'Kies één situatie waarin je deze week bewust meer loslaat.',
    ],
    reflection: 'Controle voelt veilig voor de vader, maar verstikt de tiener. Bewust loslaten is een daad van vertrouwen.',
    scienceNote: 'Psychologische controle door ouders voorspelt internaliserende problemen bij adolescenten; autonomie-ondersteuning voorspelt welzijn (Soenens & Vansteenkiste, 2010).',
    durationMin: 10,
  },
  {
    id: 'refl_1316_54',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'gevorderd',
    xpReward: 15,
    title: 'Wat kan mijn tiener mij leren?',
    description: 'Reflecteer op wat je kunt leren van je tiener in plaats van altijd de lerende/wijze vader te zijn.',
    instructions: [
      'Schrijf drie dingen op waar je tiener beter in is dan jij (bijv. technologie, sociale media, empathie, creativiteit).',
      'Reflecteer: "Hoe voelt het om toe te geven dat mijn kind ergens beter in is?"',
      'Bedenk hoe je deze erkenning kunt uiten: "Ik vind het knap dat jij..."',
      'Plan een moment waarop je je tiener oprecht om advies of hulp vraagt.',
    ],
    reflection: 'Een vader die van zijn tiener wil leren bouwt een gelijkwaardigere relatie. Het verschuift van hiërarchie naar partnerschap.',
    scienceNote: 'Wederkerigheid in de ouder-adolescentrelatie bevordert hechtingsveiligheid en autonomie-ontwikkeling (Allen et al., 2003).',
    durationMin: 10,
  },
  {
    id: 'refl_1316_55',
    skill: 'Reflectie',
    ageGroup: '13-16',
    difficulty: 'expert',
    xpReward: 20,
    title: 'Mijn vaderschap evalueren',
    description: 'Doe een diepgaande evaluatie van je vaderschap: wat zijn je sterke punten, blinde vlekken en groeikansen?',
    instructions: [
      'Maak een SWOT-analyse van je vaderschap: Sterktes (wat doe ik goed?), Zwaktes (waar schiet ik tekort?), Kansen (wat kan ik nog ontwikkelen?), Bedreigingen (wat staat mijn groei in de weg?).',
      'Vul elk kwadrant met minstens drie punten.',
      'Kies de belangrijkste sterkte om op voort te bouwen en de belangrijkste zwakte om aan te werken.',
      'Maak een persoonlijk ontwikkelplan met drie concrete stappen voor de komende maand.',
    ],
    reflection: 'Een vader die zichzelf evalueert zonder oordeel is een vader die groeit. Dit is geen afrekening maar een investering.',
    scienceNote: 'Reflective functioning – het vermogen om over eigen mentale processen na te denken – is de sterkste voorspeller van sensitief ouderschap (Fonagy & Target, 1997).',
    durationMin: 15,
  },
];
