import type { PulseQuestion } from './types';

// 60 Vader Pulse check-in vragen – 7-8 per skill
// Antwoord 3 (index 3) is altijd: "Kind niet gezien vandaag"
// Antwoorden zijn observatiegericht, niet emotie-georiënteerd

export const PULSE_QUESTIONS: PulseQuestion[] = [

  // ── AANWEZIGHEID (8 vragen) ────────────────────────────────────

  {
    id: 'pulse_aanw_01',
    skill: 'Aanwezigheid',
    vraag: 'Had je telefoon vandaag invloed op hoe aanwezig je was bij je kind?',
    antwoorden: [
      'Nee, telefoon weg – was er echt',
      'Af en toe gecheckt, maar grotendeels aanwezig',
      'Telefoon trok me vaker weg dan ik wilde',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Ouders die hun telefoon in een andere kamer leggen zijn aantoonbaar responsiever – ook als ze hem niet gebruiken. De aanwezigheid van het apparaat alleen al trekt aandacht.',
    bron: 'Ward et al. (2017) – Brain Drain',
  },
  {
    id: 'pulse_aanw_02',
    skill: 'Aanwezigheid',
    vraag: 'Was er een moment vandaag waarop je kind jou aankeek en jij terugkeek?',
    antwoorden: [
      'Ja, meerdere keren bewust oogcontact',
      'Eén moment dat ik me herinner',
      'Ik denk het niet – was met andere dingen bezig',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Oogcontact activeert het sociale brein van je kind. Drie seconden echte blik zegt meer dan tien minuten halfaanwezig zijn.',
    bron: 'Stern (1985) – The Interpersonal World of the Infant',
  },
  {
    id: 'pulse_aanw_03',
    skill: 'Aanwezigheid',
    vraag: 'Heb je je kind vandaag ergens mee bezig gezien zonder dat je iets zei of deed?',
    antwoorden: [
      'Ja, ik keek gewoon toe en genoot',
      'Even, maar ik mengde me er snel in',
      'Nee, ik was zelf bezig',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Stil toekijken zonder ingrijpen – "sportive watching" – geeft kinderen het gevoel dat ze gezien worden zonder beoordeeld te worden. Een krachtige vorm van aanwezigheid.',
    bron: 'Panksepp (1998) – Affective Neuroscience',
  },
  {
    id: 'pulse_aanw_04',
    skill: 'Aanwezigheid',
    vraag: 'Hoe lang was je langste ononderbroken moment met je kind vandaag?',
    antwoorden: [
      'Meer dan 20 minuten volledig aanwezig',
      'Zo\'n 5-10 minuten',
      'Nauwelijks – steeds iets tussendoor',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Kwaliteit van aanwezigheid telt meer dan duur. Maar kinderen hebben minstens één aaneengesloten moment per dag nodig om zich echt verbonden te voelen.',
    bron: 'Bowlby (1988) – A Secure Base',
  },
  {
    id: 'pulse_aanw_05',
    skill: 'Aanwezigheid',
    vraag: 'Was je vandaag fysiek bij je kind maar innerlijk ergens anders?',
    antwoorden: [
      'Nee, was er ook met mijn hoofd',
      'Even, maar ik merkte het en stuurde bij',
      'Ja, mijn gedachten waren elders',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Kinderen voelen het verschil tussen lichamelijke en mentale aanwezigheid. Een vader die er "bij" is maar wegdroomt, wordt door het kind ervaren als afwezig.',
    bron: 'Siegel & Hartzell (2003) – Parenting from the Inside Out',
  },
  {
    id: 'pulse_aanw_06',
    skill: 'Aanwezigheid',
    vraag: 'Heeft je kind vandaag iets aan jou gevraagd dat je verraste?',
    antwoorden: [
      'Ja, en ik was er volledig voor',
      'Ja, maar ik was afgeleid',
      'Niet dat ik me kan herinneren',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'De vragen van kinderen zijn invitaties tot verbinding. Elk gemist moment van echt luisteren is een kleine gemiste kans op hechting.',
    bron: 'Gottman & DeClaire (1997) – Raising an Emotionally Intelligent Child',
  },
  {
    id: 'pulse_aanw_07',
    skill: 'Aanwezigheid',
    vraag: 'Heb je je kind vandaag ergens voor zien kiezen of beslissen?',
    antwoorden: [
      'Ja, en ik liet het volledig aan hem/haar',
      'Ja, maar ik stuurde toch bij',
      'Ik denk dat ik het gemist heb',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Aanwezig zijn betekent ook getuige zijn van de autonomie van je kind. Niet elk moment van je kind vraagt jouw inbreng.',
    bron: 'Deci & Ryan (2000) – Self-Determination Theory',
  },
  {
    id: 'pulse_aanw_08',
    skill: 'Aanwezigheid',
    vraag: 'Wanneer je kind vandaag iets zei, luisterde je dan om te begrijpen of om te antwoorden?',
    antwoorden: [
      'Om te begrijpen – ik liet het landen',
      'Beetje van beide',
      'Eerlijk gezegd vooral om te reageren',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'De meeste mensen luisteren om te antwoorden, niet om te begrijpen. Kinderen voelen dat verschil direct. Echte luisteraars laten een stilte vallen voor ze reageren.',
    bron: 'Covey (1989) – The 7 Habits of Highly Effective People',
  },

  // ── EMOTIECOACHING (8 vragen) ─────────────────────────────────

  {
    id: 'pulse_emot_01',
    skill: 'Emotiecoaching',
    vraag: 'Heeft je kind vandaag een sterke emotie getoond?',
    antwoorden: [
      'Ja, en ik heb de emotie benoemd',
      'Ja, maar ik heb het genegeerd of opgelost',
      'Niet echt – rustige dag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Het benoemen van een emotie ("je bent boos") halveert de activiteit van de amygdala. Dat ene woord kalmeert sneller dan elke redenering.',
    bron: 'Lieberman et al. (2007) – Putting Feelings into Words',
  },
  {
    id: 'pulse_emot_02',
    skill: 'Emotiecoaching',
    vraag: 'Was er een moment vandaag dat je kind verdrietig was?',
    antwoorden: [
      'Ja, ik zat er naast zonder het op te lossen',
      'Ja, ik heb geprobeerd het snel weg te nemen',
      'Niet vandaag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'De reflex om verdriet weg te halen is begrijpelijk maar contraproductief. Kinderen die leren dat verdriet mag zijn, ontwikkelen meer emotionele veerkracht.',
    bron: 'Gottman (1997) – The Heart of Parenting',
  },
  {
    id: 'pulse_emot_03',
    skill: 'Emotiecoaching',
    vraag: 'Hoe reageerde jij vandaag op de boosheid van je kind?',
    antwoorden: [
      'Rustig en begripvol – ik bleef bij mezelf',
      'Ik probeerde het, maar escaleerde licht mee',
      'Ik werd zelf ook boos of liep weg',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Vaders die bij boosheid van het kind rustig blijven, reguleren actief het zenuwstelsel van het kind mee. Jouw kalmte is biologisch besmettelijk.',
    bron: 'Porges (2011) – The Polyvagal Theory',
  },
  {
    id: 'pulse_emot_04',
    skill: 'Emotiecoaching',
    vraag: 'Heb je je kind vandaag gevraagd hoe het zich voelde?',
    antwoorden: [
      'Ja, en we hadden een echt gesprek erover',
      'Ja, maar het bleef oppervlakkig',
      'Nee, dat is er niet van gekomen',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Kinderen die dagelijks gevraagd worden naar hun gevoel, bouwen een rijkere emotionele woordenschat op – en dat beschermt hen later tegen angst en depressie.',
    bron: 'Fivush et al. (2003) – Family Narratives and Emotion',
  },
  {
    id: 'pulse_emot_05',
    skill: 'Emotiecoaching',
    vraag: 'Was er een moment dat jij jouw eigen emotie liet zien aan je kind?',
    antwoorden: [
      'Ja, passend en eerlijk',
      'Niet bewust, maar misschien onbewust',
      'Nee, ik hield alles binnen',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Vaders die hun eigen emoties passend laten zien, modelleren emotionele openheid. Kinderen leren dat gevoel hebben oké is – van jou.',
    bron: 'Eisenberg et al. (1998) – Parental Emotion-Related Socialization',
  },
  {
    id: 'pulse_emot_06',
    skill: 'Emotiecoaching',
    vraag: 'Heeft je kind vandaag iets gedaan uit angst of onzekerheid?',
    antwoorden: [
      'Ja, en ik heb de angst erkend',
      'Ja, maar ik zei dat het niet nodig was',
      'Niet dat ik zag',
      'Kind niet gezien vandaag',
    ],
    inzicht: '"Wees maar niet bang" werkt niet – het ontkent de ervaring van je kind. "Ik snap dat je het spannend vindt" maakt de angst dragelijk.',
    bron: 'Siegel (2010) – Mindsight',
  },
  {
    id: 'pulse_emot_07',
    skill: 'Emotiecoaching',
    vraag: 'Heb je vandaag een emotie van je kind kunnen verbinden aan een oorzaak?',
    antwoorden: [
      'Ja, ik snapte wat er achter zat',
      'Ik had een vermoeden maar wist het niet zeker',
      'Nee, het gedrag was voor mij onduidelijk',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Mentaliseren – nadenken over de binnenkant van je kind – is de krachtigste vaardigheid voor goed ouderschap. Het gaat niet om altijd gelijk hebben, maar om proberen te begrijpen.',
    bron: 'Fonagy et al. (2002) – Affect Regulation, Mentalization',
  },
  {
    id: 'pulse_emot_08',
    skill: 'Emotiecoaching',
    vraag: 'Was er een moment dat je kind blij was om iets kleins?',
    antwoorden: [
      'Ja, en ik deelde die blijdschap mee',
      'Ja, maar ik was er niet echt bij',
      'Niet dat ik opmerkte',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Positieve emoties delen – "kapitaliseren" – versterkt de band meer dan troosten bij negatieve emoties. Vreugde samen beleven is even belangrijk als samen verdriet dragen.',
    bron: 'Gable et al. (2004) – What Do You Do When Things Go Right?',
  },

  // ── ZELFREGULATIE (7 vragen) ──────────────────────────────────

  {
    id: 'pulse_zelf_01',
    skill: 'Zelfregulatie',
    vraag: 'Was er een moment vandaag dat jij je moest inhouden in de interactie met je kind?',
    antwoorden: [
      'Ja, en dat lukte – ik bleef kalm',
      'Ja, maar gedeeltelijk – ik reageerde toch te snel',
      'Nee, maar niet omdat het makkelijk was',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Zelfregulatie is een spier. Elke keer dat je je inhoudt, versterk je de prefrontale cortex – letterlijk. Het wordt makkelijker door te oefenen.',
    bron: 'Baumeister & Tierney (2011) – Willpower',
  },
  {
    id: 'pulse_zelf_02',
    skill: 'Zelfregulatie',
    vraag: 'Op welk moment vandaag was jouw stressniveau het hoogst tijdens interactie met je kind?',
    antwoorden: [
      'Nauwelijks stress – rustige dag',
      'Even gespannen maar het zakte snel',
      'Hoog – ik voelde het in mijn lichaam',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Stress in het lichaam herkennen vóór je reageert is de kern van zelfregulatie. Je kunt niet denken vanuit een geactiveerd stresssysteem – je moet eerst fysiek kalmeren.',
    bron: 'van der Kolk (2014) – The Body Keeps the Score',
  },
  {
    id: 'pulse_zelf_03',
    skill: 'Zelfregulatie',
    vraag: 'Heb je vandaag een pauze genomen als je merkte dat je grens naderde?',
    antwoorden: [
      'Ja, ik stapte even weg en keerde rustig terug',
      'Nee, ik duwde door maar bleef redelijk',
      'Nee, ik escaleerde',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Even weglopen is geen falen – het is een geavanceerde vaardigheid. Je kunt niet goed reageren als je zenuwstelsel in de rode zone zit.',
    bron: 'Gottman (1994) – Why Marriages Succeed or Fail',
  },
  {
    id: 'pulse_zelf_04',
    skill: 'Zelfregulatie',
    vraag: 'Heb je vandaag iets gezegd wat je liever niet had gezegd?',
    antwoorden: [
      'Nee – mijn woorden kwamen vanuit rust',
      'Eén ding dat ik liever anders had gezegd',
      'Ja, meerdere keren',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Woorden die gezegd zijn, kunnen niet worden teruggenomen – maar hun schade kan worden hersteld. Herstel na een misstap is minstens even belangrijk als de misstap voorkomen.',
    bron: 'Siegel & Bryson (2011) – The Whole-Brain Child',
  },
  {
    id: 'pulse_zelf_05',
    skill: 'Zelfregulatie',
    vraag: 'Hoe goed sliep jij afgelopen nacht – en merkte je dat vandaag in je geduld?',
    antwoorden: [
      'Goed geslapen, geduld was op peil',
      'Matig geslapen, maar ik compenseerde bewust',
      'Slecht geslapen – mijn geduld was er niet',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Slaaptekort verlaagt de activiteit van de prefrontale cortex met 30%. Je zelfregulatie hangt letterlijk af van je nachtrust. Dat is geen excuus – het is biologie.',
    bron: 'Walker (2017) – Why We Sleep',
  },
  {
    id: 'pulse_zelf_06',
    skill: 'Zelfregulatie',
    vraag: 'Was er vandaag een moment dat je kind jou triggerde op iets uit je eigen verleden?',
    antwoorden: [
      'Ja, en ik herkende het op tijd',
      'Misschien – ik realiseer het me nu pas',
      'Nee, niets getriggerd',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Triggers vanuit het verleden zijn de gevaarlijkste momenten in opvoeding. Ze zorgen ervoor dat je reageert op je eigen pijn in plaats van op je kind.',
    bron: 'Siegel & Hartzell (2003) – Parenting from the Inside Out',
  },
  {
    id: 'pulse_zelf_07',
    skill: 'Zelfregulatie',
    vraag: 'Heb je vandaag bewust iets gedaan om je eigen stressniveau te verlagen?',
    antwoorden: [
      'Ja – bewogen, rustig geademd of pauze genomen',
      'Nee, maar ik had het niet nodig',
      'Nee, en ik had het wel nodig',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Vaders die dagelijks iets doen aan stressregulatie zijn gemiddeld responsiever voor hun kinderen. Zelfzorg is geen luxe – het is een opvoedkeuze.',
    bron: 'Mikolajczak & Roskam (2018) – A Theoretical and Clinical Framework for Parental Burnout',
  },

  // ── GRENZEN (7 vragen) ────────────────────────────────────────

  {
    id: 'pulse_gren_01',
    skill: 'Grenzen',
    vraag: 'Heb je vandaag nee gezegd tegen je kind?',
    antwoorden: [
      'Ja, rustig en duidelijk',
      'Ja, maar ik verantwoordde het te lang',
      'Nee – of het werd geen nee',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Een nee zonder lange uitleg is krachtiger dan een nee met tien redenen. Kinderen testen grenzen – ze zoeken de grens, niet het debat.',
    bron: 'Leman (2005) – Have a New Kid by Friday',
  },
  {
    id: 'pulse_gren_02',
    skill: 'Grenzen',
    vraag: 'Was er een moment vandaag dat je een grens stelde die je daarna ook hield?',
    antwoorden: [
      'Ja, gezegd én gedaan',
      'Gezegd, maar na aandringen toch toegegeven',
      'Geen grens gesteld vandaag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Consistentie is de kern van grenzen stellen. Kinderen die weten dat een nee echt nee is, proberen minder te onderhandelen – en voelen zich veiliger.',
    bron: 'Baumrind (1991) – The Influence of Parenting Style',
  },
  {
    id: 'pulse_gren_03',
    skill: 'Grenzen',
    vraag: 'Heeft je kind vandaag een grens geprobeerd te overschrijden?',
    antwoorden: [
      'Ja, en ik bleef kalm en consistent',
      'Ja, en ik reageerde inconsistent',
      'Niet echt – rustige dag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Grenzen testen is de taak van kinderen – het bewijst dat ze gezond ontwikkelen. De taak van de vader is om rustig en consistent te reageren, niet geïrriteerd.',
    bron: 'Erikson (1950) – Childhood and Society',
  },
  {
    id: 'pulse_gren_04',
    skill: 'Grenzen',
    vraag: 'Was er een grens die je stelde vanuit frustratie in plaats van bewuste keuze?',
    antwoorden: [
      'Nee – mijn grenzen kwamen van binnen, niet van stress',
      'Eén moment dat reactief was',
      'Ja, ik reageerde meer vanuit irritatie',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Grenzen gesteld vanuit frustratie zijn grillig en verwarrend voor kinderen. Grenzen gesteld vanuit waarden zijn consistent en veilig.',
    bron: 'Greene (2014) – The Explosive Child',
  },
  {
    id: 'pulse_gren_05',
    skill: 'Grenzen',
    vraag: 'Heb je vandaag je eigen grens bewaakt – wat jij nodig hebt als vader?',
    antwoorden: [
      'Ja, ik paste op mijn eigen grenzen',
      'Ik probeerde het maar gaf te veel',
      'Nee, ik gaf meer dan ik had',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Grenzen stellen voor jezelf is geen egoïsme – het is voorwaarde voor duurzaam vaderschap. Een vader zonder eigen grenzen raakt uitgeput en reageert dan slechter.',
    bron: 'Brown (2010) – The Gifts of Imperfection',
  },
  {
    id: 'pulse_gren_06',
    skill: 'Grenzen',
    vraag: 'Was er vandaag een moment dat je kind een grens accepteerde zonder groot conflict?',
    antwoorden: [
      'Ja, en ik erkende dat dat goed ging',
      'Ja, maar ik stond er niet bij stil',
      'Nee, elke grens was een gevecht',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Erken momenten waarop grenzen goed gaan – dat is net zo leerzaam als de momenten dat ze niet gaan. Positieve bekrachtiging van grensacceptatie werkt.',
    bron: 'Skinner (1953) – Science and Human Behavior',
  },
  {
    id: 'pulse_gren_07',
    skill: 'Grenzen',
    vraag: 'Stelde je vandaag een grens met warmte – of klonk het als een bevel?',
    antwoorden: [
      'Met warmte – stevig maar vriendelijk',
      'Zakelijk – duidelijk maar koel',
      'Als bevel – harder dan nodig',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'De toon van een grens bepaalt hoe het ontvangen wordt. "Dit doen we niet" met warmte wordt beter geaccepteerd dan hetzelfde gezegd met harde stem.',
    bron: 'Gordon (1970) – Parent Effectiveness Training',
  },

  // ── AUTONOMIE (8 vragen) ──────────────────────────────────────

  {
    id: 'pulse_auto_01',
    skill: 'Autonomie',
    vraag: 'Heeft je kind vandaag iets zelf geprobeerd dat jij normaal zou overnemen?',
    antwoorden: [
      'Ja, en ik liet het toe – ook al duurde het langer',
      'Ja, maar ik greep toch in',
      'Niet van toepassing vandaag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Ingrijpen als het kind iets zelf kan is de meest voorkomende autonomiekillers. Kinderen leren sneller van hun eigen pogingen dan van het goede voorbeeld van de vader.',
    bron: 'Deci & Ryan (2000) – Self-Determination Theory',
  },
  {
    id: 'pulse_auto_02',
    skill: 'Autonomie',
    vraag: 'Heb je je kind vandaag laten kiezen – ook als jij iets anders had gewild?',
    antwoorden: [
      'Ja, ik liet de keuze bij hem/haar',
      'Ik gaf een keuze maar stuurde wel',
      'Nee, ik maakte de keuze voor hem/haar',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Kinderen die dagelijks betekenisvolle keuzes maken, ontwikkelen betere besluitvormingsvaardigheden én meer zelfvertrouwen – zelfs als de keuze "fout" is.',
    bron: 'Deci (1995) – Why We Do What We Do',
  },
  {
    id: 'pulse_auto_03',
    skill: 'Autonomie',
    vraag: 'Heb je je kind vandaag ergens voor zien falen – en hoe reageerde je?',
    antwoorden: [
      'Zag het, zei niets – liet het leren',
      'Zag het, gaf een tip maar loste het niet op',
      'Zag het en sprong meteen in om te helpen',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Falen is de primaire leerschool van kinderen. Een vader die te snel ingrijpt, steelt het leermoment. Tenzij er gevaar is, is de beste actie: wachten.',
    bron: 'Dweck (2006) – Mindset',
  },
  {
    id: 'pulse_auto_04',
    skill: 'Autonomie',
    vraag: 'Heeft je kind vandaag een mening geuit die je niet deelde?',
    antwoorden: [
      'Ja, en ik respecteerde die mening',
      'Ja, maar ik probeerde het te corrigeren',
      'Niet vandaag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Kinderen die merken dat hun mening serieus genomen wordt, ook als die anders is, durven later hun eigen stem te gebruiken. Dat is de basis van zelfstandigheid.',
    bron: 'Soenens & Vansteenkiste (2010) – A Theoretical Upgrade of Parenting',
  },
  {
    id: 'pulse_auto_05',
    skill: 'Autonomie',
    vraag: 'Was er vandaag een moment dat je kind iets alleen wilde doen?',
    antwoorden: [
      'Ja, en ik gaf dat ruimte',
      'Ja, maar ik bleef toch dichtbij',
      'Niet vandaag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'De behoefte aan "alleen" is gezond, ook bij jonge kinderen. Ruimte geven om alleen te zijn is een teken van respect voor de eigen wereld van je kind.',
    bron: 'Winnicott (1965) – The Capacity to Be Alone',
  },
  {
    id: 'pulse_auto_06',
    skill: 'Autonomie',
    vraag: 'Heb je je kind vandaag ergens complimenten gegeven voor de inspanning, niet het resultaat?',
    antwoorden: [
      'Ja – "goed geprobeerd" of "doorzetter" ipv "slim"',
      'Compliment gegeven maar meer resultaatgericht',
      'Niet complimentgegeven vandaag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Kinderen die geprezen worden voor inspanning ontwikkelen een groeimindset. Kinderen die geprezen worden voor talent, vermijden moeilijke taken om te falen.',
    bron: 'Mueller & Dweck (1998) – Praise for Intelligence',
  },
  {
    id: 'pulse_auto_07',
    skill: 'Autonomie',
    vraag: 'Heb je je kind vandaag laten weten dat je in hem/haar gelooft?',
    antwoorden: [
      'Ja, expliciet gezegd of getoond',
      'Impliciet misschien, niet direct',
      'Nee',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Het Pygmalion-effect toont: hoe meer een vader gelooft in zijn kind, hoe meer het kind in zichzelf gelooft. Je verwachting is zelfvervullend.',
    bron: 'Rosenthal & Jacobson (1968) – Pygmalion in the Classroom',
  },
  {
    id: 'pulse_auto_08',
    skill: 'Autonomie',
    vraag: 'Was er vandaag iets dat je kind goed deed zonder jouw hulp?',
    antwoorden: [
      'Ja, en ik heb het gezien en erkend',
      'Ja, maar ik heb het niet benoemd',
      'Niet dat ik zag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Zelfstandige prestaties benoemen is krachtiger dan helpen. "Je deed dat zelf" is een van de meest opbouwende zinnen die een vader kan zeggen.',
    bron: 'Bandura (1997) – Self-Efficacy: The Exercise of Control',
  },

  // ── HERSTEL (7 vragen) ────────────────────────────────────────

  {
    id: 'pulse_hers_01',
    skill: 'Herstel',
    vraag: 'Was er vandaag een moment van conflict of spanning tussen jou en je kind?',
    antwoorden: [
      'Ja, en we hebben het hersteld',
      'Ja, en het hangt nog in de lucht',
      'Nee – geen conflict vandaag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Elk conflict is een kans. Niet het conflict zelf bepaalt de kwaliteit van de band – maar hoe je het herstelt.',
    bron: 'Tronick (2007) – The Neurobehavioral and Social-Emotional Development of Infants',
  },
  {
    id: 'pulse_hers_02',
    skill: 'Herstel',
    vraag: 'Heb je vandaag je excuses aangeboden aan je kind?',
    antwoorden: [
      'Ja, oprecht en concreet',
      'Ik wilde het maar deed het niet',
      'Geen reden voor vandaag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Een vader die sorry zegt, leert zijn kind twee dingen tegelijk: verantwoordelijkheid nemen én dat relaties repareerbaar zijn.',
    bron: 'Siegel & Bryson (2011) – The Whole-Brain Child',
  },
  {
    id: 'pulse_hers_03',
    skill: 'Herstel',
    vraag: 'Was er iets onafgerond tussen jou en je kind aan het einde van vandaag?',
    antwoorden: [
      'Nee – alles was afgerond of besproken',
      'Eén ding nog open maar dat komt morgen',
      'Ja, en ik weet niet hoe ik het moet aanpakken',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Niet opgelost conflict gaat mee het bed in – voor jullie allebei. Kleine herstelgebaren voor het slapengaan (aanraking, warme blik, "welterusten") volstaan.',
    bron: 'Gottman (1994) – Why Marriages Succeed or Fail',
  },
  {
    id: 'pulse_hers_04',
    skill: 'Herstel',
    vraag: 'Hoe snel herstelde jij vandaag na een moeilijk moment met je kind?',
    antwoorden: [
      'Snel – ik was er snel weer boven',
      'Het duurde even maar ik keerde terug',
      'Ik draag het nog mee',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Veerkracht is niet het vermijden van moeilijke momenten – maar hoe snel je terugkeert. Dat herstelritme is overdraagbaar op je kind.',
    bron: 'Bonanno (2004) – Loss, Trauma, and Human Resilience',
  },
  {
    id: 'pulse_hers_05',
    skill: 'Herstel',
    vraag: 'Was er vandaag iets wat jij fout deed als vader dat je bewust hebt hersteld?',
    antwoorden: [
      'Ja, ik heb het erkend en goedgemaakt',
      'Ja, maar ik heb het laten gaan',
      'Niets fout gedaan dat ik zie – of niets om van te herstellen',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Bewust herstellen is een van de krachtigste dingen die een vader kan doen. Het maakt de relatie niet zwakker – maar sterker dan voor de fout.',
    bron: 'Johnson (2008) – Hold Me Tight',
  },
  {
    id: 'pulse_hers_06',
    skill: 'Herstel',
    vraag: 'Hoe ga jij om met schuldgevoel na een moment van te hard reageren?',
    antwoorden: [
      'Ik erken het, herstel en ga verder',
      'Ik blijf het mezelf verwijten',
      'Ik negeer het – even door',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Zelfkritiek na een fout vermindert je herstelvermogen. Zelfcompassie – "ik doe mijn best" – vergroot het. Je kunt niet goed herstellen vanuit schaamte.',
    bron: 'Neff (2011) – Self-Compassion',
  },
  {
    id: 'pulse_hers_07',
    skill: 'Herstel',
    vraag: 'Heeft je kind vandaag een fout gemaakt en hoe reageerde jij?',
    antwoorden: [
      'Ik gaf ruimte, benadrukte leren boven straffen',
      'Ik reageerde, maar mild',
      'Ik reageerde harder dan ik had gewild',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Hoe jij reageert op de fouten van je kind bepaalt of het je de volgende keer eerlijk vertelt. Veiligheid na een fout is waardevoller dan de correctie zelf.',
    bron: 'Kohn (2005) – Unconditional Parenting',
  },

  // ── VERBINDING (8 vragen) ─────────────────────────────────────

  {
    id: 'pulse_verb_01',
    skill: 'Verbinding',
    vraag: 'Was er vandaag een moment van echt contact – jij en je kind, zonder afleiding?',
    antwoorden: [
      'Ja, een duidelijk verbindingsmoment',
      'Kort, maar even',
      'Nee – we waren wel samen maar niet echt verbonden',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Verbinding hoeft niet lang te zijn. Vijf minuten vol aanwezigheid vult de "verbindingstank" van je kind meer dan een uur halverwege aanwezig zijn.',
    bron: 'Bowlby (1969) – Attachment and Loss',
  },
  {
    id: 'pulse_verb_02',
    skill: 'Verbinding',
    vraag: 'Heb je je kind vandaag aangeraakt – knuffel, hand op schouder, aai over hoofd?',
    antwoorden: [
      'Ja, meerdere momenten van aanraking',
      'Eén keer kort',
      'Niet echt vandaag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Fysiek contact stimuleert oxytocine bij zowel vader als kind. Regelmatige positieve aanraking is een van de meest directe vormen van verbinding die er bestaat.',
    bron: 'Field (2010) – Touch for Socioemotional and Physical Well-Being',
  },
  {
    id: 'pulse_verb_03',
    skill: 'Verbinding',
    vraag: 'Heb je vandaag gelachen met je kind?',
    antwoorden: [
      'Ja – we hadden een echt lachmoment',
      'Lichte glimlach, niets groots',
      'Niet echt',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Lachen is sociaal lijm. Gedeeld plezier bouwt de band sneller op dan elk serieus gesprek. Vaders die spelen en lachen hebben gemiddeld hechtere relaties met hun kinderen.',
    bron: 'Panksepp (2007) – Can PLAY Diminish ADHD?',
  },
  {
    id: 'pulse_verb_04',
    skill: 'Verbinding',
    vraag: 'Weet jij wat jouw kind vandaag bezighield?',
    antwoorden: [
      'Ja, ik weet wat er in hem/haar speelde',
      'Globaal – niet in detail',
      'Niet echt',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Vaders die weten wat er leeft bij hun kind – hun vrienden, angsten, passies – worden als veiliger en betrokken ervaren. Kennis van het innerlijk leven is verbinding.',
    bron: 'Gottman (1997) – The Heart of Parenting',
  },
  {
    id: 'pulse_verb_05',
    skill: 'Verbinding',
    vraag: 'Heeft je kind vandaag iets met jou gedeeld dat het anders misschien niet had gezegd?',
    antwoorden: [
      'Ja – het deelde iets persoonlijks',
      'Misschien – een klein dingetje',
      'Niet echt',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Kinderen delen alleen wat kwetsbaar is als ze zich veilig voelen. Als je kind iets persoonlijks deelt, is dat een direct teken van verbinding en veiligheid.',
    bron: 'Ainsworth (1978) – Patterns of Attachment',
  },
  {
    id: 'pulse_verb_06',
    skill: 'Verbinding',
    vraag: 'Heb je vandaag iets gedaan wat jouw kind zelf leuk vindt – ook al is het niet jouw ding?',
    antwoorden: [
      'Ja, ik deed mee in zijn/haar wereld',
      'Kort even, maar niet echt',
      'Nee, we deden iets van mij',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'De sterkste verbinding ontstaat als jij afdaalt in de wereld van je kind – zijn spel, zijn muziek, zijn interesses. Dat zegt: "jij telt voor mij."',
    bron: 'Paquette (2004) – Theorizing the Father-Child Relationship',
  },
  {
    id: 'pulse_verb_07',
    skill: 'Verbinding',
    vraag: 'Was er een moment vandaag dat je kind jou zocht?',
    antwoorden: [
      'Ja, en ik was er voor hem/haar',
      'Ja, maar ik was op dat moment niet beschikbaar',
      'Niet dat ik zag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Als een kind zijn vader zoekt, test het de veilige basis. Een vader die er is op die momenten, bouwt het fundament van veilige hechting.',
    bron: 'Ainsworth et al. (1978) – Patterns of Attachment',
  },
  {
    id: 'pulse_verb_08',
    skill: 'Verbinding',
    vraag: 'Hoe zou je de sfeer tussen jou en je kind vandaag omschrijven?',
    antwoorden: [
      'Warm en verbonden',
      'Neutraal – gewoon een doordeweekse dag',
      'Gespannen of afstandelijk',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'De dagelijkse basissfeer bepaalt de kleur van de vader-kindrelatie over jaren. Neutrale dagen zijn oké – maar streef naar meer warme dan koele dagen per week.',
    bron: 'Gottman (1994) – Why Marriages Succeed or Fail',
  },

  // ── REFLECTIE (7 vragen) ──────────────────────────────────────

  {
    id: 'pulse_refl_01',
    skill: 'Reflectie',
    vraag: 'Wat is het eerste dat je denkt als je terugkijkt op jouw vaderschap van vandaag?',
    antwoorden: [
      'Tevredenheid – ik deed wat ik kon',
      'Gemengd – goed en minder goed',
      'Spijt – ik had het beter kunnen doen',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'De eerste gedachte bij terugkijken op de dag onthult veel over jouw innerlijke standaard als vader. Noch te streng, noch te laks – zoek de middenweg.',
    bron: 'Neff (2011) – Self-Compassion',
  },
  {
    id: 'pulse_refl_02',
    skill: 'Reflectie',
    vraag: 'Heb je vandaag iets gedaan als vader dat je trots maakt?',
    antwoorden: [
      'Ja – één moment dat ik kon erkennen',
      'Klein dingetje misschien',
      'Niet echt vandaag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Trots erkennen over eigen gedrag is geen arrogantie – het is zelfkennis. Vaders die hun krachten kennen, kunnen ze bewust inzetten.',
    bron: 'Seligman (2011) – Flourish',
  },
  {
    id: 'pulse_refl_03',
    skill: 'Reflectie',
    vraag: 'Was er vandaag een patroon in je vaderschap dat je herkende van vroeger – van jouw eigen vader?',
    antwoorden: [
      'Ja – iets goeds dat ik door geef',
      'Ja – iets wat ik liever niet herhaal',
      'Niet vandaag bewust herkend',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Intergenerationele patronen zijn krachtig maar niet onontkoombaar. Ze herkennen is de eerste stap naar bewust vaderschap.',
    bron: 'Van IJzendoorn (1995) – Adult Attachment Representations',
  },
  {
    id: 'pulse_refl_04',
    skill: 'Reflectie',
    vraag: 'Heeft jouw stemming vandaag het klimaat thuis beïnvloed?',
    antwoorden: [
      'Positief – ik bracht goede energie',
      'Neutraal – niet opvallend',
      'Negatief – mijn humeur sloeg over',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Vaders reguleren het emotionele klimaat thuis meer dan ze zich realiseren. Kinderen zijn extreem gevoelig voor de gemoedstoestand van hun vader.',
    bron: 'Repetti (1994) – Short-Term and Long-Term Processes Linking Job Stressors',
  },
  {
    id: 'pulse_refl_05',
    skill: 'Reflectie',
    vraag: 'Heb je vandaag iets van je kind geleerd?',
    antwoorden: [
      'Ja – een inzicht dat ik meeneem',
      'Misschien iets kleins',
      'Niet bewust',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Vaders die zich bewust zijn dat ze van hun kinderen leren, zijn opener, flexibeler en groeien sneller als ouder.',
    bron: 'Larson & Richards (1994) – Divergent Realities',
  },
  {
    id: 'pulse_refl_06',
    skill: 'Reflectie',
    vraag: 'Was er vandaag een moment waarop je realiseerde: zo wil ik als vader zijn?',
    antwoorden: [
      'Ja – één helder moment van "dit klopt"',
      'Kort gevoel, maar niet sterk',
      'Niet vandaag',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Momenten waarop vaderschap voelt zoals het hoort te voelen, zijn ankerpunten. Herinner ze – ze geven richting in moeilijke perioden.',
    bron: 'McAdams (2001) – The Psychology of Life Stories',
  },
  {
    id: 'pulse_refl_07',
    skill: 'Reflectie',
    vraag: 'Als je kind jou vandaag zou omschrijven aan een vriend – wat zou het dan zeggen?',
    antwoorden: [
      'Iets positiefs – aanwezig, grappig, lief',
      'Neutraal – gewoon papa',
      'Misschien iets moeilijks – druk, kortaf',
      'Kind niet gezien vandaag',
    ],
    inzicht: 'Je kind ervaart jou anders dan jij jezelf ervaart. Probeer soms door hun ogen te kijken – dat is de meest krachtige reflectievorm.',
    bron: 'Fonagy et al. (2002) – Affect Regulation, Mentalization, and the Development of the Self',
  },
];
